### 1. SZE snapshot data 20180312

In [50]:
# 1. 10:53:21 TickAB data missing
display(SZ[(SZ['WindCode'] == '300002.SZ') & (SZ['Time'] > 105315000)].head(5))
display(SZZ[(SZZ['WindCode'] == '300002.SZ') & (SZZ['Time'] > 105315000)].head(5))

,WindCode,Date,Time,Price,MatchItems,AccVolume,AccTurover,High,Low,Open,PreClose,AskPrice,AskVolume,BidPrice,BidVolume,AveAskPrice,AveBidPrice,AccAskVolume,AccBidVolume,Side_x,OrderItems_x,ABVolume_x,Side_y,OrderItems_y,ABVolume_y
5902,300002.SZ,20180312,105318000,72700,8349,25278122,184723694,75000,71200,71200,70400,72700;72800;72900;73000;73100;73200;73300;7340...,16900;49283;52800;30100;35700;23000;58400;6340...,72600;72500;72400;72300;72200;72100;72000;7190...,67300;148900;93700;43300;87000;53000;169400;13...,76000,70300,5139492,2439800,A,12.0,4100;600;2600;300;100;3400;1000;2600;1400;600;...,B,9.0,700;4400;1800;500;53100;5000;1100;500;200;
5903,300002.SZ,20180312,105324000,72700,8350,25279122,184730964,75000,71200,71200,70400,72700;72800;72900;73000;73100;73200;73300;7340...,16000;49283;52800;30100;35700;23000;58400;6340...,72600;72500;72400;72300;72200;72100;72000;7190...,68800;148900;93700;43300;87000;53000;169400;13...,76000,70300,5138592,2441300,A,13.0,3100;600;2600;100;3400;1000;2600;1400;600;100;...,B,10.0,700;4400;1800;500;53100;5000;1100;500;200;1500;
5904,300002.SZ,20180312,105327000,72700,8350,25279122,184730964,75000,71200,71200,70400,72700;72800;72900;73000;73100;73200;73300;7340...,16000;49283;52800;30100;35700;23000;58400;6340...,72600;72500;72400;72300;72200;72100;72000;7190...,173300;148900;93700;43300;87000;53000;169400;1...,76000,70400,5138592,2545800,A,13.0,3100;600;2600;100;3400;1000;2600;1400;600;100;...,B,13.0,700;4400;1800;500;53100;5000;1100;500;200;1500...
5905,300002.SZ,20180312,105330000,72600,8352,25281122,184745484,75000,71200,71200,70400,72700;72800;72900;73000;73100;73200;73300;7340...,16000;49283;52800;30100;35700;23000;58400;6340...,72600;72500;72400;72300;72200;72100;72000;7190...,171300;148900;93700;43300;87000;53000;169400;1...,76000,70400,5138592,2542800,A,13.0,3100;600;2600;100;3400;1000;2600;1400;600;100;...,B,12.0,3100;1800;500;53100;5000;1100;500;200;1500;100...
5906,300002.SZ,20180312,105333000,72600,8352,25281122,184745484,75000,71200,71200,70400,72700;72800;72900;73000;73100;73200;73300;7340...,16000;49283;52800;30100;35700;23000;58400;6340...,72600;72500;72400;72300;72200;72100;72000;7190...,170200;148900;93700;43300;87000;53000;169400;1...,76000,70400,5138592,2541700,A,13.0,3100;600;2600;100;3400;1000;2600;1400;600;100;...,B,12.0,1800;500;53100;5000;1100;500;200;1500;1000;350...

,WindCode,Date,Time,Side_x,OrderItems_x,ABVolume_x,Side_y,OrderItems_y,ABVolume_y
5038,300002.SZ,20180312,105318000,A,12,4100;600;2600;300;100;3400;1000;2600;1400;600;...,B,9,700;4400;1800;500;53100;5000;1100;500;200;
5039,300002.SZ,20180312,105321000,A,12,4100;600;2600;100;3400;1000;2600;1400;600;100;...,B,9,700;4400;1800;500;53100;5000;1100;500;200;
5040,300002.SZ,20180312,105324000,A,13,3100;600;2600;100;3400;1000;2600;1400;600;100;...,B,10,700;4400;1800;500;53100;5000;1100;500;200;1500;
5041,300002.SZ,20180312,105327000,A,13,3100;600;2600;100;3400;1000;2600;1400;600;100;...,B,13,700;4400;1800;500;53100;5000;1100;500;200;1500...
5042,300002.SZ,20180312,105330000,A,13,3100;600;2600;100;3400;1000;2600;1400;600;100;...,B,12,3100;1800;500;53100;5000;1100;500;200;1500;100...

In [53]:
# 2. 10:17:51 OrderQueue data missing
display(SZZ[(SZZ['WindCode'] == '300012.SZ') & (SZZ['Time'] >= 101745000)].head(5))
SZ[SZ['Side_x'].isnull()]['Time'].describe([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]).astype('int64')

,WindCode,Date,Time,Side_x,OrderItems_x,ABVolume_x,Side_y,OrderItems_y,ABVolume_y
34786,300012.SZ,20180312,101745000,A,4,85300;600;3000;5000;,B,9,143500;1700;6400;6700;1000;3000;4000;18400;5000;
34787,300012.SZ,20180312,101748000,A,5,75500;600;3000;5000;2000;,B,9,143500;1700;6400;6700;1000;3000;4000;18400;5000;
34788,300012.SZ,20180312,101754000,A,5,43900;600;3000;5000;2000;,B,10,143500;1700;6400;6700;1000;3000;4000;18400;500...
34789,300012.SZ,20180312,101757000,A,6,40500;600;3000;5000;2000;500;,B,9,138000;1700;6400;6700;1000;3000;18400;5000;500;
34790,300012.SZ,20180312,101800000,A,7,38900;600;3000;5000;2000;500;1800;,B,9,138000;1700;6400;6700;1000;3000;18400;5000;500;

count       486641
mean     120457844
std       18591245
min       80000000
10%       95121000
20%      101751000
30%      104212000
40%      110715000
50%      130054000
60%      132442000
70%      134815000
80%      141154000
90%      143545000
max      145954000
Name: Time, dtype: int64

In [1]:
import pandas as pd
import random
import numpy as np
import glob
import os
from unrar import rarfile
import py7zr
import pickle
import datetime
import time
pd.set_option("max_columns", 200)

startTm = datetime.datetime.now()
readPath = r'\\192.168.10.30\Kevin_zhenyu\day_stock\***'
dataPathLs = np.array(glob.glob(readPath))
dataPathLs = dataPathLs[[np.array([os.path.basename(i).split('.')[0][:2] == 'SZ' for i in dataPathLs])]]
db = pd.DataFrame()
for p in dataPathLs:
    dayData = pd.read_csv(p, compression='gzip')
    db = pd.concat([db, dayData])
print(datetime.datetime.now() - startTm)

year = "2017"
startDate = '20180312'
endDate = '20180312'
readPath = 'H:\\' + year + '\\***\\TickAB\\SZ\\***'
dataPathLs = np.array(glob.glob(readPath))
dateLs = np.array([os.path.basename(i) for i in dataPathLs])
dataPathLs = dataPathLs[(dateLs >= startDate) & (dateLs <= endDate)]
readPath = 'H:\\' + year + '\\***\\OrderQueue\\SZ\\***'
dataPathLs1 = np.array(glob.glob(readPath))
dateLs = np.array([os.path.basename(i) for i in dataPathLs1])
dataPathLs1 = dataPathLs1[(dateLs >= startDate) & (dateLs <= endDate)]
date_list = np.unique(np.array([os.path.basename(i) for i in dataPathLs1]))
wr_ong = []
mi_ss = []

for date in date_list:  
    dateLs = np.array([os.path.basename(i) for i in dataPathLs])
    path1 = dataPathLs[dateLs == date]
    dateLs = np.array([os.path.basename(i) for i in dataPathLs1])
    path2 = dataPathLs1[dateLs == date]
    SZ = []
    ll = []
    SZZ = []
    ll1 = []
    for data in path1:
        readPath = data + '\\***'
        dataPathLs = np.array(glob.glob(readPath))
        dateLs = np.array([int(os.path.basename(i).split('.')[0]) for i in dataPathLs])
        dataPathLs = dataPathLs[(dateLs < 4000) | ((dateLs > 300000) & (dateLs < 310000))]
        startTm = datetime.datetime.now()
        for i in dataPathLs:
            try:
                df = pd.read_csv(i, usecols = [0,1,2,3,6,10,11,12,13,14,15,16,17,18,19,20,21,22,23])
            except:
                print("empty data")
                print(i)
                ll.append(int(os.path.basename(i).split('.')[0]))
                continue
            SZ += [df]
            del df
    SZ = pd.concat(SZ).reset_index(drop=True)
    print(datetime.datetime.now() - startTm)
    for data in path2:
        readPath = data + '\\***'
        dataPathLs = np.array(glob.glob(readPath))
        dateLs = np.array([int(os.path.basename(i).split('.')[0]) for i in dataPathLs])
        dataPathLs = dataPathLs[(dateLs < 4000) | ((dateLs > 300000) & (dateLs < 310000))]
        startTm = datetime.datetime.now()
        for i in dataPathLs:
            try:
                df = pd.read_csv(i, usecols = [0,1,2,3,5,7])
                df = pd.merge(df[df['Side'] == 'A'], df[df['Side'] == 'B'], on=['WindCode', 'Date', 'Time'], how='outer')
                assert((df[df['Side_x'].isnull()].shape[0] == 0) & ((df[df['Side_y'].isnull()].shape[0] == 0)))
                df.drop(["Side_x", "Side_y"],axis=1,inplace=True)
            except:
                print("empty data")
                print(i)
                ll1.append(int(os.path.basename(i).split('.')[0]))
                continue
            SZZ += [df]
            del df
    SZZ = pd.concat(SZZ).reset_index(drop=True)
    print(datetime.datetime.now() - startTm)
    SZ = pd.merge(SZ, SZZ, on=['WindCode', 'Date', 'Time'], how='left')
    
    startTm = datetime.datetime.now()
    SZ["skey"] = SZ['WindCode'].apply(lambda x: int(x.split('.')[0])) + 2000000
    SZ.drop(["WindCode"],axis=1,inplace=True)
    SZ['QuotTime'] = SZ['Time'] + SZ['Date'] * 1000000000
    SZ["Time"] = SZ['Time'] * 1000
    SZ["clockAtArrival"] = SZ["QuotTime"].astype(str).apply(lambda x: np.int64(datetime.datetime.strptime(x, '%Y%m%d%H%M%S%f').timestamp()*1e6))
    SZ['datetime'] = SZ["clockAtArrival"].apply(lambda x: datetime.datetime.fromtimestamp(x/1e6))
    SZ.drop(["QuotTime"],axis=1,inplace=True)
    print(datetime.datetime.now() - startTm)
    
    startTm = datetime.datetime.now()
    SZ["BidPrice"] = SZ["BidPrice"].apply(lambda x: [float(i) for i in x[:-1].split(';')])
    SZ["AskPrice"] = SZ["AskPrice"].apply(lambda x: [float(i) for i in x[:-1].split(';')])
    SZ["BidVolume"] = SZ["BidVolume"].apply(lambda x: [int(i) for i in x[:-1].split(';')])
    SZ["AskVolume"] = SZ["AskVolume"].apply(lambda x: [int(i) for i in x[:-1].split(';')])

    for i in range(1, 11):
        SZ["bid" + str(i) + 'p'] = SZ["BidPrice"].apply(lambda x: x[i-1],2)
    SZ.drop(["BidPrice"],axis=1,inplace=True)
    print("1")
    for i in range(1, 11):
        SZ["ask" + str(i) + 'p'] = SZ["AskPrice"].apply(lambda x: x[i-1],2)
    SZ.drop(["AskPrice"],axis=1,inplace=True)
    print("2")
    for i in range(1, 11):
        SZ["bid" + str(i) + 'q'] = SZ["BidVolume"].apply(lambda x: x[i-1])
    SZ.drop(["BidVolume"],axis=1,inplace=True)
    print("3")
    for i in range(1, 11):
        SZ["ask" + str(i) + 'q'] = SZ["AskVolume"].apply(lambda x: x[i-1])
    SZ.drop(["AskVolume"],axis=1,inplace=True)
    print("4")
    
    SZ["ABVolume_x"] = SZ["ABVolume_x"].fillna('0;')
    SZ["ABVolume_y"] = SZ["ABVolume_y"].fillna('0;')
    SZ["ABVolume_x"] = SZ["ABVolume_x"].apply(lambda x: [int(i) for i in x[:-1].split(';')])
    SZ["ABVolume_y"] = SZ["ABVolume_y"].apply(lambda x: [int(i) for i in x[:-1].split(';')])

    for i in range(1, 51):
        SZ["bid1Top" + str(i) + 'q'] = 0
        SZ.loc[SZ['OrderItems_y'] >= i,"bid1Top" + str(i) + 'q'] = SZ.loc[SZ['OrderItems_y'] >= i,"ABVolume_y"].apply(lambda x: x[i-1])
        SZ["bid1Top" + str(i) + 'q'] = SZ["bid1Top" + str(i) + 'q'].astype('int32')
    SZ.drop(["ABVolume_y"],axis=1,inplace=True)
    print("5")
    
    for i in range(1, 51):
        SZ["ask1Top" + str(i) + 'q'] = 0
        SZ.loc[SZ['OrderItems_x'] >= i,"ask1Top" + str(i) + 'q'] = SZ.loc[SZ['OrderItems_x'] >= i,"ABVolume_x"].apply(lambda x: x[i-1])
        SZ["ask1Top" + str(i) + 'q'] = SZ["ask1Top" + str(i) + 'q'].astype('int32') 
    SZ.drop(["ABVolume_x"],axis=1,inplace=True)
    print("6")
    print(datetime.datetime.now() - startTm)
        
    
    startTm = datetime.datetime.now()
    SZ.columns = ['date', 'time', 'close', 'cum_trades_cnt', 'cum_volume', 'cum_amount', 'high', 'low', 'open', 'prev_close', 
 'total_ask_vwap', 'total_bid_vwap', 'total_ask_quantity', 'total_bid_quantity', 'ask1n', 'bid1n', 'skey', 'clockAtArrival',
 'datetime', 'bid1p', 'bid2p', 'bid3p', 'bid4p', 'bid5p', 'bid6p', 'bid7p', 'bid8p', 'bid9p', 'bid10p', 'ask1p',
 'ask2p', 'ask3p', 'ask4p', 'ask5p', 'ask6p', 'ask7p', 'ask8p', 'ask9p', 'ask10p', 'bid1q', 'bid2q', 'bid3q', 'bid4q', 'bid5q',
 'bid6q', 'bid7q', 'bid8q', 'bid9q', 'bid10q', 'ask1q', 'ask2q', 'ask3q', 'ask4q', 'ask5q', 'ask6q', 'ask7q', 'ask8q', 'ask9q',
 'ask10q', 'bid1Top1q', 'bid1Top2q', 'bid1Top3q', 'bid1Top4q', 'bid1Top5q', 'bid1Top6q', 'bid1Top7q', 'bid1Top8q', 'bid1Top9q',
 'bid1Top10q', 'bid1Top11q', 'bid1Top12q', 'bid1Top13q', 'bid1Top14q', 'bid1Top15q', 'bid1Top16q', 'bid1Top17q', 'bid1Top18q',
 'bid1Top19q', 'bid1Top20q', 'bid1Top21q', 'bid1Top22q', 'bid1Top23q', 'bid1Top24q', 'bid1Top25q', 'bid1Top26q', 'bid1Top27q', 
 'bid1Top28q', 'bid1Top29q', 'bid1Top30q', 'bid1Top31q', 'bid1Top32q', 'bid1Top33q', 'bid1Top34q', 'bid1Top35q', 'bid1Top36q',
 'bid1Top37q', 'bid1Top38q', 'bid1Top39q', 'bid1Top40q', 'bid1Top41q', 'bid1Top42q', 'bid1Top43q', 'bid1Top44q', 'bid1Top45q', 
 'bid1Top46q', 'bid1Top47q', 'bid1Top48q', 'bid1Top49q', 'bid1Top50q', 'ask1Top1q', 'ask1Top2q', 'ask1Top3q', 'ask1Top4q', 
 'ask1Top5q', 'ask1Top6q', 'ask1Top7q', 'ask1Top8q', 'ask1Top9q', 'ask1Top10q', 'ask1Top11q', 'ask1Top12q', 'ask1Top13q', 
 'ask1Top14q', 'ask1Top15q', 'ask1Top16q', 'ask1Top17q', 'ask1Top18q', 'ask1Top19q', 'ask1Top20q', 'ask1Top21q', 'ask1Top22q',
 'ask1Top23q', 'ask1Top24q', 'ask1Top25q', 'ask1Top26q', 'ask1Top27q', 'ask1Top28q', 'ask1Top29q', 'ask1Top30q', 'ask1Top31q',
 'ask1Top32q', 'ask1Top33q', 'ask1Top34q', 'ask1Top35q', 'ask1Top36q', 'ask1Top37q', 'ask1Top38q', 'ask1Top39q', 'ask1Top40q', 
 'ask1Top41q', 'ask1Top42q', 'ask1Top43q', 'ask1Top44q', 'ask1Top45q', 'ask1Top46q', 'ask1Top47q', 'ask1Top48q', 'ask1Top49q', 
 'ask1Top50q']
    
    SZ = SZ.fillna(0)
#     SZ["p1"] = SZ["bid1p"] + SZ["ask1p"]
#     tt = SZ[(SZ["cum_volume"] > 0) & (SZ["time"] < 145700000000)].groupby("skey")['p1'].min()
#     SZ.drop("p1", axis=1, inplace=True)
#     try:
#         assert(tt[tt == 0].shape[0] == 0)
#     except:
#         display(tt[tt == 0])
#     SZ = SZ[~((SZ["bid1p"] == 0) & (SZ["ask1p"] == 0))]
    SZ["ordering"] = SZ.groupby("skey").cumcount()
    SZ["ordering"] = SZ["ordering"] + 1

    for cols in ["total_bid_orders",'total_ask_orders','total_bid_levels', 'total_ask_levels', 'bid_trade_max_duration',
                 'ask_trade_max_duration', 'cum_canceled_buy_orders', 'cum_canceled_buy_volume', "cum_canceled_buy_amount",
                 "cum_canceled_sell_orders", 'cum_canceled_sell_volume',"cum_canceled_sell_amount", "has_missing",
                 'bid2n', 'bid3n', 'bid4n', 'bid5n', 'bid6n', 'bid7n', 'bid8n', 'bid9n', 'bid10n', 'ask2n', 'ask3n',
                 'ask4n', 'ask5n', 'ask6n', 'ask7n', 'ask8n', 'ask9n', 'ask10n']:
        SZ[cols] = 0
        
#     for col in ["cum_volume", "total_bid_quantity", "total_ask_quantity",'cum_canceled_buy_volume',
#         'cum_canceled_sell_volume']:
#         SZ[col] = SZ[col].astype('int64')
    
    for col in ['close', 'high', 'low', 'open', 'prev_close', 'total_ask_vwap', 'total_bid_vwap', 'bid1p', 'bid2p', 
                'bid3p', 'bid4p', 'bid5p', 'bid6p', 'bid7p', 'bid8p', 'bid9p', 'bid10p', 'ask1p', 'ask2p', 'ask3p', 
                'ask4p', 'ask5p', 'ask6p', 'ask7p', 'ask8p', 'ask9p', 'ask10p']:
        SZ[col] = SZ[col]/10000
        print(col)
        print(SZ[col].astype(str).apply(lambda x: len(x.split('.')[1])).unique())
        
    for col in ["skey", "date", "cum_trades_cnt", "total_bid_orders",
        'total_ask_orders', 'total_bid_levels', 'total_ask_levels', 'cum_canceled_buy_orders','cum_canceled_sell_orders',
            "ordering", 'bid_trade_max_duration', 'ask_trade_max_duration','has_missing']:
        SZ[col] = SZ[col].astype('int32')
    
        
#     for cols in ["prev_close", 'open', "high", "low", "close", 'bid10p','bid9p','bid8p','bid7p','bid6p','bid5p','bid4p','bid3p',
#              'bid2p','bid1p','ask1p','ask2p','ask3p','ask4p','ask5p','ask6p','ask7p','ask8p','ask9p','ask10p', 'total_bid_vwap', "total_ask_vwap",
#                 "cum_amount"]:
# #         SZ[cols] = SZ[cols].apply(lambda x: round(x, 2)).astype('float64')
#         print(cols)
#         print(SZ[cols].astype(str).apply(lambda x: len(str(x.split('.')[1]))).unique())

        
    for cols in ["cum_canceled_sell_amount", "cum_canceled_buy_amount", 'cum_amount']:
        SZ[cols] = SZ[cols].astype('float64')

        
    assert(sum(SZ[SZ["open"] != 0].groupby("skey")["open"].nunique() != 1) == 0)
    assert(sum(SZ[SZ["prev_close"] != 0].groupby("skey")["prev_close"].nunique() != 1) == 0)
    SZ["prev_close"] = np.where(SZ["time"] >= 91500000000, SZ.groupby("skey")["prev_close"].transform("max"), SZ["prev_close"]) 
    SZ["open"] = np.where(SZ["cum_volume"] > 0, SZ.groupby("skey")["open"].transform("max"), SZ["open"])
    assert(sum(SZ[SZ["open"] != 0].groupby("skey")["open"].nunique() != 1) == 0)
    assert(sum(SZ[SZ["prev_close"] != 0].groupby("skey")["prev_close"].nunique() != 1) == 0)
    assert(SZ[SZ["cum_volume"] > 0]["open"].min() > 0)
    
    print(datetime.datetime.now() - startTm)
    
    
    # check 1
    startTm = datetime.datetime.now()
    da_te = str(SZ["date"].iloc[0]) 
    da_te = da_te[:4] + '-' + da_te[4:6] + '-' + da_te[6:8]
    db1 = db[db["date"] == da_te]
    db1["ID"] = db1["ID"].str[2:].astype(int) + 2000000
    db1["date"] = (db1["date"].str[:4] + db1["date"].str[5:7] + db1["date"].str[8:]).astype(int)
    SZ["cum_max"] = SZ.groupby("skey")["cum_volume"].transform(max)
    s2 = SZ[SZ["cum_volume"] == SZ["cum_max"]].groupby("skey").first().reset_index()
    SZ.drop("cum_max", axis=1, inplace=True)
    s2 = s2.rename(columns={"skey": "ID", 'open':"d_open", "prev_close":"d_yclose","high":"d_high", "low":"d_low", "close":"d_close", "cum_volume":"d_volume", "cum_amount":"d_amount"})
    s2 = s2[["ID", "date", "d_open", "d_yclose", "d_high", "d_low", "d_close", "d_volume", "d_amount"]]
    re = pd.merge(db1, s2, on=["ID", "date", "d_open", "d_yclose","d_high", "d_low", "d_volume"], how="outer")
    try:
        assert(sum(re["d_amount_y"].isnull()) == 0)
    except:
        display(re[re["d_amount_y"].isnull()])
        wr_ong += [re[re["d_amount_y"].isnull()]]
    del re
    del s2
    del db1
    print(datetime.datetime.now() - startTm)
    
    # check 2
    # first part
    startTm = datetime.datetime.now()
    date = pd.DataFrame(pd.date_range(start='2019-06-10 08:30:00', end='2019-06-10 18:00:00', freq='s'), columns=["Orig"])
    date["time"] = date["Orig"].apply(lambda x: int(x.strftime("%H%M%S"))*1000)
    date["group"] = date["time"]//10000
    SZ["group"] = SZ["time"]//10000000
    gl = date[((date["time"] >= 93000000) & (date["time"] <= 113000000))|((date["time"] >= 130000000) & (date["time"] <= 150000000))]["group"].unique()
    l = set(gl) - set(SZ["group"].unique())
    SZ["has_missing1"] = 0 
    if len(l) != 0:
        print("massive missing")
        print(l)
        SZ["order"] = SZ.groupby(["skey", "time"]).cumcount()
        for i in l:
            SZ["t"] = SZ[SZ["group"] > i].groupby("StockID")["time"].transform("min")
            SZ["has_missing1"] = np.where((SZ["time"] == SZ["t"]) & (SZ["order"] == 0), 1, 0)
        SZ.drop(["order", "t", "group"], axis=1, inplace=True)   
    else:
        print("no massive missing")
        SZ.drop(["group"], axis=1, inplace=True)
    



    # second part

    SZ["time_interval"] = SZ.groupby("skey")["datetime"].apply(lambda x: x - x.shift(1))
    SZ["time_interval"] = SZ["time_interval"].apply(lambda x: x.seconds)
    SZ["tn_update"] = SZ.groupby("skey")["cum_trades_cnt"].apply(lambda x: x-x.shift(1))

    f1 = SZ[(SZ["time"] >= 93000000000) & (SZ["tn_update"] != 0)].groupby("skey")["time"].min().reset_index()
    f1 = f1.rename(columns={"time": "time1"})
    f2 = SZ[(SZ["time"] >= 130000000000) & (SZ["tn_update"] != 0)].groupby("skey")["time"].min().reset_index()
    f2 = f2.rename(columns={"time": "time2"})
    f3 = SZ[(SZ["time"] >= 150000000000) & (SZ["tn_update"] != 0)].groupby("skey")["time"].min().reset_index()
    f3 = f3.rename(columns={"time": "time3"})
    SZ = pd.merge(SZ, f1, on="skey", how="left")
    del f1
    SZ = pd.merge(SZ, f2, on="skey", how="left")
    del f2
    SZ = pd.merge(SZ, f3, on="skey", how="left")
    del f3
    p99 = SZ[(SZ["time"] > 93000000000) & (SZ["time"] < 145700000000) & (SZ["time"] != SZ["time2"]) & (SZ["tn_update"] != 0)]\
    .groupby("skey")["tn_update"].apply(lambda x: x.describe([0.99])["99%"]).reset_index()
    p99 = p99.rename(columns={"tn_update":"99%"})
    SZ = pd.merge(SZ, p99, on="skey", how="left")

    SZ["has_missing2"] = 0
    SZ["has_missing2"] = np.where((SZ["time_interval"] > 60) & (SZ["tn_update"] > SZ["99%"]) & 
         (SZ["time"] > SZ["time1"]) & (SZ["time"] != SZ["time2"]) & (SZ["time"] != SZ["time3"]), 1, 0)
    SZ.drop(["time_interval", "tn_update", "time1", "time2", "time3", "99%"], axis=1, inplace=True) 

    SZ["has_missing"] = np.where((SZ["has_missing1"] == 1) | (SZ["has_missing2"] == 1), 1, 0)
    SZ.drop(["has_missing1", "has_missing2"], axis=1, inplace=True) 
    if SZ[SZ["has_missing"] == 1].shape[0] != 0:
        print("has missing!!!!!!!!!!!!!!!!!!!!!!!")
        print(SZ[SZ["has_missing"] == 1].shape[0])
        mi_ss += [SZ[SZ["has_missing"] == 1]]
    print(datetime.datetime.now() - startTm)

    
    
    startTm = datetime.datetime.now()
    SZ = SZ[["skey", "date", "time", "clockAtArrival", "datetime", "ordering", "has_missing", "cum_trades_cnt", "cum_volume", "cum_amount", "prev_close",
                            "open", "high", "low", "close", 'bid10p','bid9p','bid8p','bid7p','bid6p','bid5p','bid4p','bid3p','bid2p','bid1p',
                            'ask1p','ask2p','ask3p','ask4p','ask5p','ask6p','ask7p','ask8p','ask9p','ask10p', 'bid10q','bid9q','bid8q',
                             'bid7q','bid6q','bid5q','bid4q','bid3q','bid2q','bid1q', 'ask1q','ask2q','ask3q','ask4q','ask5q','ask6q',
                             'ask7q','ask8q','ask9q','ask10q', 'bid10n', 'bid9n', 'bid8n', 'bid7n', 'bid6n', 'bid5n', 'bid4n', 'bid3n', 'bid2n', 'bid1n', 
                             'ask1n', 'ask2n', 'ask3n', 'ask4n', 'ask5n', 'ask6n','ask7n', 'ask8n', 'ask9n', 'ask10n','bid1Top1q','bid1Top2q','bid1Top3q','bid1Top4q','bid1Top5q','bid1Top6q',
        'bid1Top7q','bid1Top8q','bid1Top9q','bid1Top10q','bid1Top11q','bid1Top12q','bid1Top13q','bid1Top14q','bid1Top15q','bid1Top16q','bid1Top17q','bid1Top18q',
        'bid1Top19q','bid1Top20q','bid1Top21q','bid1Top22q','bid1Top23q','bid1Top24q','bid1Top25q','bid1Top26q','bid1Top27q','bid1Top28q','bid1Top29q',
        'bid1Top30q','bid1Top31q','bid1Top32q','bid1Top33q','bid1Top34q','bid1Top35q','bid1Top36q','bid1Top37q','bid1Top38q','bid1Top39q','bid1Top40q',
        'bid1Top41q','bid1Top42q','bid1Top43q','bid1Top44q','bid1Top45q','bid1Top46q','bid1Top47q','bid1Top48q','bid1Top49q','bid1Top50q', 'ask1Top1q',
        'ask1Top2q','ask1Top3q','ask1Top4q','ask1Top5q','ask1Top6q','ask1Top7q','ask1Top8q','ask1Top9q','ask1Top10q','ask1Top11q','ask1Top12q','ask1Top13q',
        'ask1Top14q','ask1Top15q','ask1Top16q','ask1Top17q','ask1Top18q','ask1Top19q','ask1Top20q','ask1Top21q','ask1Top22q','ask1Top23q',
        'ask1Top24q','ask1Top25q','ask1Top26q','ask1Top27q','ask1Top28q','ask1Top29q','ask1Top30q','ask1Top31q','ask1Top32q','ask1Top33q',
        'ask1Top34q','ask1Top35q','ask1Top36q','ask1Top37q','ask1Top38q','ask1Top39q','ask1Top40q','ask1Top41q','ask1Top42q','ask1Top43q',
        'ask1Top44q','ask1Top45q','ask1Top46q','ask1Top47q','ask1Top48q','ask1Top49q','ask1Top50q',"total_bid_quantity", "total_ask_quantity","total_bid_vwap", "total_ask_vwap",
        "total_bid_orders",'total_ask_orders','total_bid_levels', 'total_ask_levels', 'bid_trade_max_duration', 'ask_trade_max_duration', 'cum_canceled_buy_orders', 'cum_canceled_buy_volume',
        "cum_canceled_buy_amount", "cum_canceled_sell_orders", 'cum_canceled_sell_volume',"cum_canceled_sell_amount"]]
    
    display(SZ["date"].iloc[0])
    print("SZ finished")
    pd.set_option('max_rows', 200)
    print(SZ.dtypes)
    print(datetime.datetime.now() - startTm)

C:\Users\win\Anaconda3\lib\site-packages\ipykernel_launcher.py:16: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  app.launch_new_instance()

0:03:22.978241
0:00:13.628226
0:00:12.224733
0:01:19.474648
1
2
3
4
5
6
0:06:25.548443
close
[1 2]
high
[1 2]
low
[1 2]
open
[1 2]
prev_close
[2 1]
total_ask_vwap
[1 2]
total_bid_vwap
[1 2]
bid1p
[1 2]
bid2p
[1 2]
bid3p
[1 2]
bid4p
[1 2]
bid5p
[1 2]
bid6p
[1 2]
bid7p
[1 2]
bid8p
[1 2]
bid9p
[1 2]
bid10p
[1 2]
ask1p
[1 2]
ask2p
[1 2]
ask3p
[1 2]
ask4p
[1 2]
ask5p
[1 2]
ask6p
[1 2]
ask7p
[1 2]
ask8p
[1 2]
ask9p
[1 2]
ask10p
[1 2]
0:02:22.406792

C:\Users\win\Anaconda3\lib\site-packages\ipykernel_launcher.py:225: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\win\Anaconda3\lib\site-packages\ipykernel_launcher.py:226: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,ID,date,d_open,d_high,d_low,d_close_x,d_yclose,d_cumprodCAA,d_dayReturn,d_5dayReturn,d_ICDayReturn,d_CSIDayReturn,d_volume,d_amount_x,TORate,allZT,hasZT,isZT,allDT,hasDT,isDT,tmrHalted,haltedDays,marketShares,totalShares,d_close_y,d_amount_y
666,2300208,20180312,11.99,11.99,11.99,11.99,10.90,1.000000,0.100000,0.016102,0.014307,0.016137,610586.0,7.320926e+06,0.001055,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,579010002.0,765525000.0,NaN,NaN
901,2001914,20180312,9.25,9.25,9.08,9.15,9.18,0.986228,-0.003268,0.013289,0.014307,0.016137,2506617.0,2.288333e+07,0.003759,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,666780666.0,666961416.0,NaN,NaN
1303,2300073,20180312,26.20,27.96,26.00,27.96,25.42,0.498822,0.099921,0.138900,0.014307,0.016137,26994940.0,7.460403e+08,0.080966,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,333408762.0,366068040.0,NaN,NaN
1679,2002037,20180312,12.29,12.30,12.02,12.30,11.18,0.993938,0.100179,0.046809,0.014307,0.016137,8151426.0,1.000693e+08,0.024900,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,327368160.0,327368160.0,NaN,NaN
1774,2002793,20180312,15.78,16.19,15.60,16.19,15.78,0.491225,0.025982,0.053855,0.014307,0.016137,3240034.0,5.165942e+07,0.050241,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,64490100.0,200000000.0,NaN,NaN

0:00:03.994038
no massive missing
has missing!!!!!!!!!!!!!!!!!!!!!!!
4
0:02:07.897329

20180312

SZ finished
skey                                 int32
date                                 int32
time                                 int64
clockAtArrival                       int64
datetime                    datetime64[ns]
ordering                             int32
has_missing                          int32
cum_trades_cnt                       int32
cum_volume                           int64
cum_amount                           int64
prev_close                         float64
open                               float64
high                               float64
low                                float64
close                              float64
bid10p                             float64
bid9p                              float64
bid8p                              float64
bid7p                              float64
bid6p                              float64
bid5p                              float64
bid4p                              float64
bid3p                              float64
bid2p                              float64
bid1p                              float64
ask1p                              float64
ask2p                              float64
ask3p                              float64
ask4p                              float64
ask5p                              float64
ask6p                              float64
ask7p                              float64
ask8p                              float64
ask9p                              float64
ask10p                             float64
bid10q                               int64
bid9q                                int64
bid8q                                int64
bid7q                                int64
bid6q                                int64
bid5q                                int64
bid4q                                int64
bid3q                                int64
bid2q                                int64
bid1q                                int64
ask1q                                int64
ask2q                                int64
ask3q                                int64
ask4q                                int64
ask5q                                int64
ask6q                                int64
ask7q                                int64
ask8q                                int64
ask9q                                int64
ask10q                               int64
bid10n                               int64
bid9n                                int64
bid8n                                int64
bid7n                                int64
bid6n                                int64
bid5n                                int64
bid4n                                int64
bid3n                                int64
bid2n                                int64
bid1n                              float64
ask1n                              float64
ask2n                                int64
ask3n                                int64
ask4n                                int64
ask5n                                int64
ask6n                                int64
ask7n                                int64
ask8n                                int64
ask9n                                int64
ask10n                               int64
bid1Top1q                            int32
bid1Top2q                            int32
bid1Top3q                            int32
bid1Top4q                            int32
bid1Top5q                            int32
bid1Top6q                            int32
bid1Top7q                            int32
bid1Top8q                            int32
bid1Top9q                            int32
bid1Top10q                           int32
bid1Top11q                           int32
bid1Top12q                           int32
bid1Top13q                           int32
bid1Top14q                           int32
bid1Top15q                           int32
bid1Top16q                           int32
bid1Top17q                           int32
bid1Top18q                           int32
bid1Top19q                           int32
bid1Top20q                           int32
bid1Top21q                           int32
bid1Top22q                           int32
bid1Top23q                           int32
bid1Top24q                           int32
bid1Top25q                           int32
bid1Top26q                           int32
bid1Top27q                           int32
bid1Top28q                           int32
bid1Top29q                           int32
bid1Top30q                           int32
bid1Top31q                           int32
bid1Top32q                           int32
bid1Top33q                           int32
bid1Top34q                           int32
bid1Top35q                           int32
bid1Top36q                           int32
bid1Top37q                           int32
bid1Top38q                           int32
bid1Top39q                           int32
bid1Top40q                           int32
bid1Top41q                           int32
bid1Top42q                           int32
bid1Top43q                           int32
bid1Top44q                           int32
bid1Top45q                           int32
bid1Top46q                           int32
bid1Top47q                           int32
bid1Top48q                           int32
bid1Top49q                           int32
bid1Top50q                           int32
ask1Top1q                            int32
ask1Top2q                            int32
ask1Top3q                            int32
ask1Top4q                            int32
ask1Top5q                            int32
ask1Top6q                            int32
ask1Top7q                            int32
ask1Top8q                            int32
ask1Top9q                            int32
ask1Top10q                           int32
ask1Top11q                           int32
ask1Top12q                           int32
ask1Top13q                           int32
ask1Top14q                           int32
ask1Top15q                           int32
ask1Top16q                           int32
ask1Top17q                           int32
ask1Top18q                           int32
ask1Top19q                           int32
ask1Top20q                           int32
ask1Top21q                           int32
ask1Top22q                           int32
ask1Top23q                           int32
ask1Top24q                           int32
ask1Top25q                           int32
ask1Top26q                           int32
ask1Top27q                           int32
ask1Top28q                           int32
ask1Top29q                           int32
ask1Top30q                           int32
ask1Top31q                           int32
ask1Top32q                           int32
ask1Top33q                           int32
ask1Top34q                           int32
ask1Top35q                           int32
ask1Top36q                           int32
ask1Top37q                           int32
ask1Top38q                           int32
ask1Top39q                           int32
ask1Top40q                           int32
ask1Top41q                           int32
ask1Top42q                           int32
ask1Top43q                           int32
ask1Top44q                           int32
ask1Top45q                           int32
ask1Top46q                           int32
ask1Top47q                           int32
ask1Top48q                           int32
ask1Top49q                           int32
ask1Top50q                           int32
total_bid_quantity                   int64
total_ask_quantity                   int64
total_bid_vwap                     float64
total_ask_vwap                     float64
total_bid_orders                     int32
total_ask_orders                     int32
total_bid_levels                     int32
total_ask_levels                     int32
bid_trade_max_duration               int32
ask_trade_max_duration               int32
cum_canceled_buy_orders              int32
cum_canceled_buy_volume              int64
cum_canceled_buy_amount            float64
cum_canceled_sell_orders             int32
cum_canceled_sell_volume             int64
cum_canceled_sell_amount           float64
dtype: object
0:00:02.600296

In [33]:
SZ[SZ['has_missing'] == 1]

,skey,date,time,clockAtArrival,datetime,ordering,has_missing,cum_trades_cnt,cum_volume,cum_amount,prev_close,open,high,low,close,bid10p,bid9p,bid8p,bid7p,bid6p,bid5p,bid4p,bid3p,bid2p,bid1p,ask1p,ask2p,ask3p,ask4p,ask5p,ask6p,ask7p,ask8p,ask9p,ask10p,bid10q,bid9q,bid8q,bid7q,bid6q,bid5q,bid4q,bid3q,bid2q,bid1q,ask1q,ask2q,ask3q,ask4q,ask5q,ask6q,ask7q,ask8q,ask9q,ask10q,bid10n,bid9n,bid8n,bid7n,bid6n,bid5n,bid4n,bid3n,bid2n,bid1n,ask1n,ask2n,ask3n,ask4n,ask5n,ask6n,ask7n,ask8n,ask9n,ask10n,bid1Top1q,bid1Top2q,bid1Top3q,bid1Top4q,bid1Top5q,bid1Top6q,bid1Top7q,bid1Top8q,bid1Top9q,bid1Top10q,bid1Top11q,bid1Top12q,bid1Top13q,bid1Top14q,bid1Top15q,bid1Top16q,bid1Top17q,bid1Top18q,bid1Top19q,bid1Top20q,bid1Top21q,bid1Top22q,bid1Top23q,bid1Top24q,bid1Top25q,bid1Top26q,bid1Top27q,bid1Top28q,bid1Top29q,bid1Top30q,bid1Top31q,bid1Top32q,bid1Top33q,bid1Top34q,bid1Top35q,bid1Top36q,bid1Top37q,bid1Top38q,bid1Top39q,bid1Top40q,bid1Top41q,bid1Top42q,bid1Top43q,bid1Top44q,bid1Top45q,bid1Top46q,bid1Top47q,bid1Top48q,bid1Top49q,bid1Top50q,ask1Top1q,ask1Top2q,ask1Top3q,ask1Top4q,ask1Top5q,ask1Top6q,ask1Top7q,ask1Top8q,ask1Top9q,ask1Top10q,ask1Top11q,ask1Top12q,ask1Top13q,ask1Top14q,ask1Top15q,ask1Top16q,ask1Top17q,ask1Top18q,ask1Top19q,ask1Top20q,ask1Top21q,ask1Top22q,ask1Top23q,ask1Top24q,ask1Top25q,ask1Top26q,ask1Top27q,ask1Top28q,ask1Top29q,ask1Top30q,ask1Top31q,ask1Top32q,ask1Top33q,ask1Top34q,ask1Top35q,ask1Top36q,ask1Top37q,ask1Top38q,ask1Top39q,ask1Top40q,ask1Top41q,ask1Top42q,ask1Top43q,ask1Top44q,ask1Top45q,ask1Top46q,ask1Top47q,ask1Top48q,ask1Top49q,ask1Top50q,total_bid_quantity,total_ask_quantity,total_bid_vwap,total_ask_vwap,total_bid_orders,total_ask_orders,total_bid_levels,total_ask_levels,bid_trade_max_duration,ask_trade_max_duration,cum_canceled_buy_orders,cum_canceled_buy_volume,cum_canceled_buy_amount,cum_canceled_sell_orders,cum_canceled_sell_volume,cum_canceled_sell_amount,tn_update,time2,99%
1333652,2300423,20180312,141354000000,1520835234000000,2018-03-12 14:13:54,755,1,377,364156,9641683,26.28,26.20,26.75,26.19,26.68,26.42,26.43,26.46,26.50,26.51,26.53,26.54,26.55,26.60,26.68,26.69,26.70,26.71,26.74,26.75,26.79,26.80,26.84,26.85,26.88,2500,900,1000,5800,700,4000,2600,1000,600,12264,20100,6400,2500,800,800,1000,4700,1700,2000,21700,0,0,0,0,0,0,0,0,0,1.0,2.0,0,0,0,0,0,0,0,0,0,12264,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,100,20000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,103624,279340,26.17,27.59,0,0,0,0,0,0,0,0,0.0,0,0,0.0,10.0,1.301570e+11,8.30
2527349,2000403,20180312,135254000000,1520833974000000,2018-03-12 13:52:54,730,1,408,406712,12319498,30.22,30.02,30.45,30.02,30.22,30.13,30.15,30.16,30.17,30.18,30.19,30.20,30.21,30.22,30.23,30.32,30.33,30.34,30.35,30.37,30.38,30.39,30.40,30.41,30.42,4000,5500,3000,11300,400,3000,2356,2700,1200,400,400,1300,2000,5000,1000,4000,4000,26501,6520,1000,0,0,0,0,0,0,0,0,0,1.0,1.0,0,0,0,0,0,0,0,0,0,400,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,400,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,113812,211640,29.88,30.71,0,0,0,0,0,0,0,0,0.0,0,0,0.0,7.0,1.300030e+11,6.00
2882060,2000622,20180312,141418000000,1520835258000000,2018-03-12 14:14:18,909,1,538,1126300,5131891,4.54,4.56,4.60,4.53,4.55,4.45,4.46,4.47,4.48,4.50,4.51,4.52,4.53,4.54,4.55,4.56,4.57,4.58,4.59,4.60,4.61,4.62,4.63,4.64,4.65,33400,600,12000,5000,14200,4600,10500,20800,43600,3000,25100,73300,32300,36800,163900,7000,18700,10000,500,33400,0,0,0,0,0,0,0,0,0,2.0,2.0,0,0,0,0,0,0,0,0,0,2500,500,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5100,20000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,191600,1000900,4.46,4.77,0,0,0,0,0,0,0,0,0.0,0,0,0.0,13.0,1.300030e+11,7.07
3291360,2000803,20180312,140645000000,1520834805000000,2018-03-12 14:06:45,784,1,302,600500,12994122,21.68,21.40,21.94,21.26,21.59,21.39,21.40,21.41,21.42,21.45,21.49,21.50,21.51,21.56,21.59,21.66,21.67,21.68,21.69,21.70,21.72,21.73,21.76,21.78,21.79,3800,1000,500,1000,1000,300,400,500,300,3100,600,100,4801,3500,9900,6801,500,1600,2000,1100,0,0,0,0,0,0,0,0,0,1.0,1.0,0,0,0,0,0,0,0,0,0,3100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,600,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,29100,150202,21.28,22.23,0,0,0,0,0,0,0,0,0.0,0,0,0.0,8.0,1.300060e+11,6.00

In [37]:
SZ[(SZ['skey'] == 2300423) & (SZ['time'] <= 141354000000)].tail(5)

,skey,date,time,clockAtArrival,datetime,ordering,has_missing,cum_trades_cnt,cum_volume,cum_amount,prev_close,open,high,low,close,bid10p,bid9p,bid8p,bid7p,bid6p,bid5p,bid4p,bid3p,bid2p,bid1p,ask1p,ask2p,ask3p,ask4p,ask5p,ask6p,ask7p,ask8p,ask9p,ask10p,bid10q,bid9q,bid8q,bid7q,bid6q,bid5q,bid4q,bid3q,bid2q,bid1q,ask1q,ask2q,ask3q,ask4q,ask5q,ask6q,ask7q,ask8q,ask9q,ask10q,bid10n,bid9n,bid8n,bid7n,bid6n,bid5n,bid4n,bid3n,bid2n,bid1n,ask1n,ask2n,ask3n,ask4n,ask5n,ask6n,ask7n,ask8n,ask9n,ask10n,bid1Top1q,bid1Top2q,bid1Top3q,bid1Top4q,bid1Top5q,bid1Top6q,bid1Top7q,bid1Top8q,bid1Top9q,bid1Top10q,bid1Top11q,bid1Top12q,bid1Top13q,bid1Top14q,bid1Top15q,bid1Top16q,bid1Top17q,bid1Top18q,bid1Top19q,bid1Top20q,bid1Top21q,bid1Top22q,bid1Top23q,bid1Top24q,bid1Top25q,bid1Top26q,bid1Top27q,bid1Top28q,bid1Top29q,bid1Top30q,bid1Top31q,bid1Top32q,bid1Top33q,bid1Top34q,bid1Top35q,bid1Top36q,bid1Top37q,bid1Top38q,bid1Top39q,bid1Top40q,bid1Top41q,bid1Top42q,bid1Top43q,bid1Top44q,bid1Top45q,bid1Top46q,bid1Top47q,bid1Top48q,bid1Top49q,bid1Top50q,ask1Top1q,ask1Top2q,ask1Top3q,ask1Top4q,ask1Top5q,ask1Top6q,ask1Top7q,ask1Top8q,ask1Top9q,ask1Top10q,ask1Top11q,ask1Top12q,ask1Top13q,ask1Top14q,ask1Top15q,ask1Top16q,ask1Top17q,ask1Top18q,ask1Top19q,ask1Top20q,ask1Top21q,ask1Top22q,ask1Top23q,ask1Top24q,ask1Top25q,ask1Top26q,ask1Top27q,ask1Top28q,ask1Top29q,ask1Top30q,ask1Top31q,ask1Top32q,ask1Top33q,ask1Top34q,ask1Top35q,ask1Top36q,ask1Top37q,ask1Top38q,ask1Top39q,ask1Top40q,ask1Top41q,ask1Top42q,ask1Top43q,ask1Top44q,ask1Top45q,ask1Top46q,ask1Top47q,ask1Top48q,ask1Top49q,ask1Top50q,total_bid_quantity,total_ask_quantity,total_bid_vwap,total_ask_vwap,total_bid_orders,total_ask_orders,total_bid_levels,total_ask_levels,bid_trade_max_duration,ask_trade_max_duration,cum_canceled_buy_orders,cum_canceled_buy_volume,cum_canceled_buy_amount,cum_canceled_sell_orders,cum_canceled_sell_volume,cum_canceled_sell_amount,tn_update,time2,99%
1333648,2300423,20180312,141103000000,1520835063000000,2018-03-12 14:11:03,751,0,364,347920,9209031,26.28,26.2,26.75,26.19,26.60,26.41,26.42,26.43,26.46,26.50,26.51,26.53,26.54,26.55,26.60,26.62,26.65,26.66,26.67,26.68,26.69,26.7,26.71,26.74,26.75,7640,2500,900,1000,5800,700,4000,2600,1000,4000,1100,2716,900,2320,5000,20100,6400,2500,800,800,0,0,0,0,0,0,0,0,0,1.0,2.0,0,0,0,0,0,0,0,0,0,4000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,100,1000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,94760,291376,26.12,27.55,0,0,0,0,0,0,0,0,0.0,0,0,0.0,1.0,1.301570e+11,8.3
1333649,2300423,20180312,141109000000,1520835069000000,2018-03-12 14:11:09,752,0,365,348120,9214351,26.28,26.2,26.75,26.19,26.60,26.41,26.42,26.43,26.46,26.50,26.51,26.53,26.54,26.55,26.60,26.62,26.65,26.66,26.67,26.68,26.69,26.7,26.71,26.74,26.75,7640,2500,900,1000,5800,700,4000,2600,1000,4300,1100,2716,900,2320,5000,20100,6400,2500,800,800,0,0,0,0,0,0,0,0,0,2.0,2.0,0,0,0,0,0,0,0,0,0,3800,500,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,100,1000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,95060,291376,26.12,27.55,0,0,0,0,0,0,0,0,0.0,0,0,0.0,1.0,1.301570e+11,8.3
1333650,2300423,20180312,141145000000,1520835105000000,2018-03-12 14:11:45,753,0,365,348120,9214351,26.28,26.2,26.75,26.19,26.60,26.41,26.42,26.43,26.46,26.50,26.51,26.53,26.54,26.55,26.60,26.62,26.65,26.66,26.67,26.68,26.69,26.7,26.71,26.74,26.75,7640,2500,900,1000,5800,700,4000,2600,1000,4600,1100,2716,900,2320,5000,20100,6400,2500,800,800,0,0,0,0,0,0,0,0,0,3.0,2.0,0,0,0,0,0,0,0,0,0,3800,500,300,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,100,1000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,95360,291376,26.12,27.55,0,0,0,0,0,0,0,0,0.0,0,0,0.0,0.0,1.301570e+11,8.3
1333651,2300423,20180312,141233000000,1520835153000000,2018-03-12 14:12:33,754,0,367,352120,9320751,26.28,26.2,26.75,26.19,26.60,26.41,26.42,26.43,26.46,26.50,26.51,26.53,26.54,26.55,26.60,26.62,26.65,26.66,26.67,26.68,26.69,26.7,26.71,26.74,26.75,7640,2500,900,1000,5800,700,4000,2600,1000,600,1100,2716,900,2320,5000,20100,6400,2500,800,800,0,0,0,0,0,0,0,0,0,2.0,2.0,0,0,0,0,0,0,0,0,0,300,300,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,100,1000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,91360,291376,26.10,27.55,0,0,0,0,0,0,0,0,0.0,0,0,0.0,2.0,1.301570e+11,8.3
1333652,2300423,20180312,141354000000,1520835234000000,2018-03-12 14:13:54,755,1,377,364156,9641683,26.28,26.2,26.75,26.19,26.68,26.42,26.43,26.46,26.50,26.51,26.53,26.54,26.55,26.60,26.68,26.69,26.70,26.71,26.74,26.75,26.79,26.8,26.84,26.85,26.88,2500,900,1000,5800,700,4000,2600,1000,600,12264,20100,6400,2500,800,800,1000,4700,1700,2000,21700,0,0,0,0,0,0,0,0,0,1.0,2.0,0,0,0,0,0,0,0,0,0,12264,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,100,20000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,103624,279340,26.17,27.59,0,0,0,0,0,0,0,0,0.0,0,0,0.0,10.0,1.301570e+11,8.3

### 2. SZE trade data 20171130, 20180312

In [1]:
import pandas as pd
import random
import numpy as np
import glob
import os
from unrar import rarfile
import py7zr
import pickle
import datetime
import time
pd.set_option("max_columns", 200)

startTm = datetime.datetime.now()
readPath = r'\\192.168.10.30\Kevin_zhenyu\day_stock\***'
dataPathLs = np.array(glob.glob(readPath))
dataPathLs = dataPathLs[[np.array([os.path.basename(i).split('.')[0][:2] == 'SZ' for i in dataPathLs])]]
db = pd.DataFrame()
for p in dataPathLs:
    dayData = pd.read_csv(p, compression='gzip')
    db = pd.concat([db, dayData])
print(datetime.datetime.now() - startTm)

year = "2017"
startDate = '20180312'
endDate = '20180312'
readPath = 'H:\\' + year + '\\***\\Transaction\\SZ\\***'
dataPathLs = np.array(glob.glob(readPath))
dateLs = np.array([os.path.basename(i) for i in dataPathLs])
dataPathLs = dataPathLs[(dateLs >= startDate) & (dateLs <= endDate)]
date_list = np.unique(np.array([os.path.basename(i) for i in dataPathLs]))
wr_ong = []
mi_ss = []

for date in date_list:  
    dateLs = np.array([os.path.basename(i) for i in dataPathLs])
    path1 = dataPathLs[dateLs == date]
    TradeLog = []
    ll = []
    for data in path1:
        readPath = data + '\\***'
        dataPathLs = np.array(glob.glob(readPath))
        dateLs = np.array([int(os.path.basename(i).split('.')[0]) for i in dataPathLs])
        dataPathLs = dataPathLs[(dateLs < 4000) | ((dateLs > 300000) & (dateLs < 310000))]
        startTm = datetime.datetime.now()
        for i in dataPathLs:
            try:
                df = pd.read_csv(i, usecols = [0,1,2,3,5,6,7,8,9])
            except:
                print("empty data")
                print(i)
                ll.append(int(os.path.basename(i).split('.')[0]))
                continue
            TradeLog += [df]
            del df
    TradeLog = pd.concat(TradeLog).reset_index(drop=True)
    print(datetime.datetime.now() - startTm)
    
    TradeLog["skey"] = TradeLog['WindCode'].apply(lambda x: int(x.split('.')[0])) + 2000000
    TradeLog = TradeLog.rename(columns={"TradeVolume":"trade_qty", "TradePrice":"trade_price", "FunctionCode":"trade_type", 
                                        'Date':"date", "BidOrder":"BidApplSeqNum", "AskOrder":"OfferApplSeqNum", 
                                        "BSFlag":"trade_flag", "Time":"time"})
    TradeLog['trade_price'] = TradeLog['trade_price']/10000
    TradeLog["trade_money"] = TradeLog["trade_price"] * TradeLog["trade_qty"]
    TradeLog["trade_flag"] = np.where(TradeLog["trade_flag"] == 'B', 1, np.where(
        TradeLog["trade_flag"] == 'S', 2, 0))
    TradeLog['TransactTime'] = TradeLog['time'] + TradeLog['date'] * 1000000000
    TradeLog["clockAtArrival"] = TradeLog["TransactTime"].astype(str).apply(lambda x: np.int64(datetime.datetime.strptime(x, '%Y%m%d%H%M%S%f').timestamp()*1e6))
    TradeLog['datetime'] = TradeLog["clockAtArrival"].apply(lambda x: datetime.datetime.fromtimestamp(x/1e6))
    TradeLog["time"] = TradeLog["time"]*1000
    TradeLog["trade_type"] = np.where(TradeLog["trade_type"] == 'C', 4, 1)
    TradeLog['ApplSeqNum'] = 0
    for col in ["skey", "date", "ApplSeqNum", "BidApplSeqNum", "OfferApplSeqNum", "trade_qty", "trade_type", "trade_flag"]:
        TradeLog[col] = TradeLog[col].astype('int32')
    for cols in ["trade_money", "trade_price"]:
        display(cols)
        display(TradeLog[cols].astype(str).apply(lambda x: len(str(x.split('.')[1]))).unique())
#         TradeLog[cols] = TradeLog[cols].round(2)
#         display(TradeLog[cols].astype(str).apply(lambda x: len(str(x.split('.')[1]))).unique())
    for cols in ["trade_money"]:
        TradeLog[cols] = TradeLog[cols].round(2)
    
    da_te = str(TradeLog["date"].iloc[0]) 
    da_te = da_te[:4] + '-' + da_te[4:6] + '-' + da_te[6:8]
    db1 = db[db["date"] == da_te]
    sl = (db1["ID"].str[2:].astype(int) + 2000000).unique()
    db1["max_volume"] = db1.groupby("ID")["d_volume"].transform("max")
    db1["max_amount"] = db1.groupby("ID")["d_amount"].transform("max")
    t1 = db1.groupby("ID")["max_volume", "max_amount"].first().reset_index()
    del db1
    t1["skey"] = t1["ID"].str[2:].astype(int) + 2000000
    trade1 = TradeLog[TradeLog["trade_type"] == 1].groupby("skey")["trade_qty"].sum().reset_index()
    trade1.columns=["skey", "cum_volume"]
    trade2 = TradeLog[TradeLog["trade_type"] == 1].groupby("skey")["trade_money"].sum().reset_index()
    trade2.columns=["skey", "cum_amount"]
    t2 = pd.merge(trade1, trade2, on="skey")
    re = pd.merge(t1, t2, on="skey", how="outer")
    try:
        assert(t1.shape[0] == t2.shape[0])
        assert(re[re["cum_volume"] != re["max_volume"]].shape[0] == 0)
        assert(re[re["cum_amount"].round(2) != re["max_amount"]].shape[0] == 0)
    except:
        display(set(t1["skey"]) - set(t2["skey"]))
        display(re[re["cum_volume"] != re["max_volume"]])
        display(re[re["cum_amount"].round(2) != re["max_amount"]])
    del t1
    del t2
    del re
 
    TradeLog = TradeLog[["skey", "date", "time", "clockAtArrival", "datetime", "ApplSeqNum", "trade_type", "trade_flag",
                                                 "trade_price", "trade_qty", "BidApplSeqNum", "OfferApplSeqNum"]]
    print(da_te)
    print("trade finished")
    pd.set_option('max_rows', 200)
    print(TradeLog.dtypes)
    print(datetime.datetime.now() - startTm)

C:\Users\win\Anaconda3\lib\site-packages\ipykernel_launcher.py:16: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  app.launch_new_instance()

0:03:47.226577

C:\Users\win\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

0:00:11.198016

'trade_money'

array([ 1,  2, 12, 14, 13, 11, 10, 15,  9, 16], dtype=int64)

'trade_price'

array([1, 2], dtype=int64)

C:\Users\win\Anaconda3\lib\site-packages\ipykernel_launcher.py:86: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\win\Anaconda3\lib\site-packages\ipykernel_launcher.py:87: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

{2001914}

           ID  max_volume  max_amount     skey  cum_volume  cum_amount
422  SZ001914   2506617.0  22883332.5  2001914         NaN         NaN

           ID  max_volume  max_amount     skey  cum_volume  cum_amount
422  SZ001914   2506617.0  22883332.5  2001914         NaN         NaN

2018-03-12
trade finished
skey                        int32
date                        int32
time                        int64
clockAtArrival              int64
datetime           datetime64[ns]
ApplSeqNum                  int32
trade_type                  int32
trade_flag                  int32
trade_price               float64
trade_qty                   int32
BidApplSeqNum               int32
OfferApplSeqNum             int32
dtype: object
0:05:15.243948

### 3. data comparison

In [1]:
import pymongo
import pandas as pd
import pickle
import datetime
import time
import gzip
import lzma
import pytz


def DB(host, db_name, user, passwd):
    auth_db = db_name if user not in ('admin', 'root') else 'admin'
    uri = 'mongodb://%s:%s@%s/?authSource=%s' % (user, passwd, host, auth_db)
    return DBObj(uri, db_name=db_name)


class DBObj(object):
    def __init__(self, uri, symbol_column='skey', db_name='white_db'):
        self.db_name = db_name
        self.uri = uri
        self.client = pymongo.MongoClient(self.uri)
        self.db = self.client[self.db_name]
        self.chunk_size = 20000
        self.symbol_column = symbol_column
        self.date_column = 'date'

    def parse_uri(self, uri):
        # mongodb://user:password@example.com
        return uri.strip().replace('mongodb://', '').strip('/').replace(':', ' ').replace('@', ' ').split(' ')

    def drop_table(self, table_name):
        self.db.drop_collection(table_name)

    def rename_table(self, old_table, new_table):
        self.db[old_table].rename(new_table)

    def write(self, table_name, df):
        if len(df) == 0: return

        multi_date = False

        if self.date_column in df.columns:
            date = str(df.head(1)[self.date_column].iloc[0])
            multi_date = len(df[self.date_column].unique()) > 1
        else:
            raise Exception('DataFrame should contain date column')

        collection = self.db[table_name]
        collection.create_index([('date', pymongo.ASCENDING), ('symbol', pymongo.ASCENDING)], background=True)
        collection.create_index([('symbol', pymongo.ASCENDING), ('date', pymongo.ASCENDING)], background=True)

        if multi_date:
            for (date, symbol), sub_df in df.groupby([self.date_column, self.symbol_column]):
                date = str(date)
                symbol = int(symbol)
                collection.delete_many({'date': date, 'symbol': symbol})
                self.write_single(collection, date, symbol, sub_df)
        else:
            for symbol, sub_df in df.groupby([self.symbol_column]):
                collection.delete_many({'date': date, 'symbol': symbol})
                self.write_single(collection, date, symbol, sub_df)

    def write_single(self, collection, date, symbol, df):
        for start in range(0, len(df), self.chunk_size):
            end = min(start + self.chunk_size, len(df))
            df_seg = df[start:end]
            version = 1
            seg = {'ver': version, 'data': self.ser(df_seg, version), 'date': date, 'symbol': symbol, 'start': start}
            collection.insert_one(seg)

    def build_query(self, start_date=None, end_date=None, symbol=None):
        query = {}

        def parse_date(x):
            if type(x) == str:
                if len(x) != 8:
                    raise Exception("`date` must be YYYYMMDD format")
                return x
            elif type(x) == datetime.datetime or type(x) == datetime.date:
                return x.strftime("%Y%m%d")
            elif type(x) == int:
                return parse_date(str(x))
            else:
                raise Exception("invalid `date` type: " + str(type(x)))

        if start_date is not None or end_date is not None:
            query['date'] = {}
            if start_date is not None:
                query['date']['$gte'] = parse_date(start_date)
            if end_date is not None:
                query['date']['$lte'] = parse_date(end_date)

        def parse_symbol(x):
            if type(x) == int:
                return x
            else:
                return int(x)

        if symbol:
            if type(symbol) == list or type(symbol) == tuple:
                query['symbol'] = {'$in': [parse_symbol(x) for x in symbol]}
            else:
                query['symbol'] = parse_symbol(symbol)

        return query

    def delete(self, table_name, start_date=None, end_date=None, symbol=None):
        collection = self.db[table_name]

        query = self.build_query(start_date, end_date, symbol)
        if not query:
            print('cannot delete the whole table')
            return None

        collection.delete_many(query)

    def read(self, table_name, start_date=None, end_date=None, symbol=None):
        collection = self.db[table_name]

        query = self.build_query(start_date, end_date, symbol)
        if not query:
            print('cannot read the whole table')
            return None

        segs = []
        for x in collection.find(query):
            x['data'] = self.deser(x['data'], x['ver'])
            segs.append(x)
        segs.sort(key=lambda x: (x['symbol'], x['date'], x['start']))
        return pd.concat([x['data'] for x in segs], ignore_index=True) if segs else None

    def list_tables(self):
        return self.db.collection_names()

    def list_dates(self, table_name, start_date=None, end_date=None, symbol=None):
        collection = self.db[table_name]
        dates = set()
        if start_date is None:
            start_date = '00000000'
        if end_date is None:
            end_date = '99999999'
        for x in collection.find(self.build_query(start_date, end_date, symbol), {"date": 1, '_id': 0}):
            dates.add(x['date'])
        return sorted(list(dates))

    def ser(self, s, version):
        pickle_protocol = 4
        if version == 1:
            return gzip.compress(pickle.dumps(s, protocol=pickle_protocol), compresslevel=2)
        elif version == 2:
            return lzma.compress(pickle.dumps(s, protocol=pickle_protocol), preset=1)
        else:
            raise Exception('unknown version')

    def deser(self, s, version):
        def unpickle(s):
            return pickle.loads(s)

        if version == 1:
            return unpickle(gzip.decompress(s))
        elif version == 2:
            return unpickle(lzma.decompress(s))
        else:
            raise Exception('unknown version')


def patch_pandas_pickle():
    if pd.__version__ < '0.24':
        import sys
        from types import ModuleType
        from pandas.core.internals import BlockManager
        pkg_name = 'pandas.core.internals.managers'
        if pkg_name not in sys.modules:
            m = ModuleType(pkg_name)
            m.BlockManager = BlockManager
            sys.modules[pkg_name] = m
patch_pandas_pickle()

In [3]:
startDate = 20161230
endDate = 20170301
database_name = 'com_md_eq_cn'
user = "zhenyuy"
password = "bnONBrzSMGoE"

db = DB("192.168.10.178", database_name, user, password)
SZ1 = db.read('md_snapshot_l2', start_date=startDate, end_date=endDate, symbol=[2000001])
SZ1['date'].unique()

array([20170301], dtype=int64)

In [4]:
pd.set_option("max_columns", 200)
len(SZ1[(SZ1['skey'] == 2000001) & (SZ1['cum_volume'] > 0) & (SZ1['time'] < 145700000000) 
    & (SZ1['time'] > 93000000000)]['cum_volume'].unique())

4574

In [5]:
len(SZ[(SZ['skey'] == 2000001) & (SZ['cum_volume'] > 0) & (SZ['time'] < 145700000000) 
   & (SZ['time'] > 93000000000)]['cum_volume'].unique())

4598

In [6]:
import numpy as np

data1 = SZ[(SZ["cum_volume"] > 0) & (SZ["time"] < 145700000000) & (SZ["time"] > 93000000000)]
data2 = SZ1[(SZ1["cum_volume"] > 0) & (SZ1["time"] < 145700000000) & (SZ1["time"] > 93000000000)]

columns = ['date', 'time', 'close', 'cum_trades_cnt', 'cum_volume', 'high', 'low', 'open', 'prev_close', 
 'total_ask_vwap', 'total_bid_vwap', 'total_ask_quantity', 'total_bid_quantity', 'ask1n', 'bid1n', 'skey', 'bid1p', 'bid2p', 
 'bid3p', 'bid4p', 'bid5p', 'bid6p', 'bid7p', 'bid8p', 'bid9p', 'bid10p', 'ask1p',
 'ask2p', 'ask3p', 'ask4p', 'ask5p', 'ask6p', 'ask7p', 'ask8p', 'ask9p', 'ask10p', 'bid1q', 'bid2q', 'bid3q', 'bid4q', 'bid5q',
 'bid6q', 'bid7q', 'bid8q', 'bid9q', 'bid10q', 'ask1q', 'ask2q', 'ask3q', 'ask4q', 'ask5q', 'ask6q', 'ask7q', 'ask8q', 'ask9q',
 'ask10q', 'bid1Top1q', 'bid1Top2q', 'bid1Top3q', 'bid1Top4q', 'bid1Top5q', 'bid1Top6q', 'bid1Top7q', 'bid1Top8q', 'bid1Top9q',
 'bid1Top10q', 'bid1Top11q', 'bid1Top12q', 'bid1Top13q', 'bid1Top14q', 'bid1Top15q', 'bid1Top16q', 'bid1Top17q', 'bid1Top18q',
 'bid1Top19q', 'bid1Top20q', 'bid1Top21q', 'bid1Top22q', 'bid1Top23q', 'bid1Top24q', 'bid1Top25q', 'bid1Top26q', 'bid1Top27q', 
 'bid1Top28q', 'bid1Top29q', 'bid1Top30q', 'bid1Top31q', 'bid1Top32q', 'bid1Top33q', 'bid1Top34q', 'bid1Top35q', 'bid1Top36q',
 'bid1Top37q', 'bid1Top38q', 'bid1Top39q', 'bid1Top40q', 'bid1Top41q', 'bid1Top42q', 'bid1Top43q', 'bid1Top44q', 'bid1Top45q', 
 'bid1Top46q', 'bid1Top47q', 'bid1Top48q', 'bid1Top49q', 'bid1Top50q', 'ask1Top1q', 'ask1Top2q', 'ask1Top3q', 'ask1Top4q', 
 'ask1Top5q', 'ask1Top6q', 'ask1Top7q', 'ask1Top8q', 'ask1Top9q', 'ask1Top10q', 'ask1Top11q', 'ask1Top12q', 'ask1Top13q', 
 'ask1Top14q', 'ask1Top15q', 'ask1Top16q', 'ask1Top17q', 'ask1Top18q', 'ask1Top19q', 'ask1Top20q', 'ask1Top21q', 'ask1Top22q',
 'ask1Top23q', 'ask1Top24q', 'ask1Top25q', 'ask1Top26q', 'ask1Top27q', 'ask1Top28q', 'ask1Top29q', 'ask1Top30q', 'ask1Top31q',
 'ask1Top32q', 'ask1Top33q', 'ask1Top34q', 'ask1Top35q', 'ask1Top36q', 'ask1Top37q', 'ask1Top38q', 'ask1Top39q', 'ask1Top40q', 
 'ask1Top41q', 'ask1Top42q', 'ask1Top43q', 'ask1Top44q', 'ask1Top45q', 'ask1Top46q', 'ask1Top47q', 'ask1Top48q', 'ask1Top49q', 
 'ask1Top50q']
data1_1 = data1.drop_duplicates(subset=columns, keep="first").reset_index()
data2_1 = data2.drop_duplicates(subset=columns, keep="first").reset_index()
n1 = len(data1_1["skey"].unique())
n2 = len(data2_1["skey"].unique())
print(n1)
print(n2)
if n1 != n2:
    sl = list(set(data1_1["skey"].unique()) & (set(data2_1["skey"].unique())))
    data1_1 = data1_1[data1_1["skey"].isin(sl)]
    data2_1 = data2_1[data2_1["skey"].isin(sl)]
test = pd.merge(data1_1, data2_1, left_on=columns, right_on=columns, how="outer")
n1 = test["ordering_x"].count()
n2 = test["ordering_y"].count()
len1 = len(test)
print(n1)
print(n2)
print(len1)
print("-----------------------------------------------")
if n2 < len1:
    display("test is not complete:")
    display(test[np.isnan(test["ordering_y"])])
    print(len(test[np.isnan(test["ordering_y"])])/n1)
if (len1 == n2) & (n1 < len1):
    display("baseline is not complete:")
    display(test[np.isnan(test["ordering_x"])])
    display(n2-n1)

1917
1917
6580820
6714020
8038309
-----------------------------------------------

'test is not complete:'

MemoryError:

### 4. 上交所、深交所历史数据

In [1]:
import pandas as pd
import random
import numpy as np
import glob
import os
from unrar import rarfile
import py7zr
import pickle
import datetime

import pymongo
import pandas as pd
import pickle
import datetime
import time
import gzip
import lzma
import pytz


def DB(host, db_name, user, passwd):
    auth_db = db_name if user not in ('admin', 'root') else 'admin'
    uri = 'mongodb://%s:%s@%s/?authSource=%s' % (user, passwd, host, auth_db)
    return DBObj(uri, db_name=db_name)


class DBObj(object):
    def __init__(self, uri, symbol_column='skey', db_name='white_db'):
        self.db_name = db_name
        self.uri = uri
        self.client = pymongo.MongoClient(self.uri)
        self.db = self.client[self.db_name]
        self.chunk_size = 20000
        self.symbol_column = symbol_column
        self.date_column = 'date'

    def parse_uri(self, uri):
        # mongodb://user:password@example.com
        return uri.strip().replace('mongodb://', '').strip('/').replace(':', ' ').replace('@', ' ').split(' ')

    def drop_table(self, table_name):
        self.db.drop_collection(table_name)

    def rename_table(self, old_table, new_table):
        self.db[old_table].rename(new_table)

    def write(self, table_name, df):
        if len(df) == 0: return

        multi_date = False

        if self.date_column in df.columns:
            date = str(df.head(1)[self.date_column].iloc[0])
            multi_date = len(df[self.date_column].unique()) > 1
        else:
            raise Exception('DataFrame should contain date column')

        collection = self.db[table_name]
        collection.create_index([('date', pymongo.ASCENDING), ('symbol', pymongo.ASCENDING)], background=True)
        collection.create_index([('symbol', pymongo.ASCENDING), ('date', pymongo.ASCENDING)], background=True)

        if multi_date:
            for (date, symbol), sub_df in df.groupby([self.date_column, self.symbol_column]):
                date = str(date)
                symbol = int(symbol)
                collection.delete_many({'date': date, 'symbol': symbol})
                self.write_single(collection, date, symbol, sub_df)
        else:
            for symbol, sub_df in df.groupby([self.symbol_column]):
                collection.delete_many({'date': date, 'symbol': symbol})
                self.write_single(collection, date, symbol, sub_df)

    def write_single(self, collection, date, symbol, df):
        for start in range(0, len(df), self.chunk_size):
            end = min(start + self.chunk_size, len(df))
            df_seg = df[start:end]
            version = 1
            seg = {'ver': version, 'data': self.ser(df_seg, version), 'date': date, 'symbol': symbol, 'start': start}
            collection.insert_one(seg)

    def build_query(self, start_date=None, end_date=None, symbol=None):
        query = {}

        def parse_date(x):
            if type(x) == str:
                if len(x) != 8:
                    raise Exception("`date` must be YYYYMMDD format")
                return x
            elif type(x) == datetime.datetime or type(x) == datetime.date:
                return x.strftime("%Y%m%d")
            elif type(x) == int:
                return parse_date(str(x))
            else:
                raise Exception("invalid `date` type: " + str(type(x)))

        if start_date is not None or end_date is not None:
            query['date'] = {}
            if start_date is not None:
                query['date']['$gte'] = parse_date(start_date)
            if end_date is not None:
                query['date']['$lte'] = parse_date(end_date)

        def parse_symbol(x):
            if type(x) == int:
                return x
            else:
                return int(x)

        if symbol:
            if type(symbol) == list or type(symbol) == tuple:
                query['symbol'] = {'$in': [parse_symbol(x) for x in symbol]}
            else:
                query['symbol'] = parse_symbol(symbol)

        return query

    def delete(self, table_name, start_date=None, end_date=None, symbol=None):
        collection = self.db[table_name]

        query = self.build_query(start_date, end_date, symbol)
        if not query:
            print('cannot delete the whole table')
            return None

        collection.delete_many(query)

    def read(self, table_name, start_date=None, end_date=None, symbol=None):
        collection = self.db[table_name]

        query = self.build_query(start_date, end_date, symbol)
        if not query:
            print('cannot read the whole table')
            return None

        segs = []
        for x in collection.find(query):
            x['data'] = self.deser(x['data'], x['ver'])
            segs.append(x)
        segs.sort(key=lambda x: (x['symbol'], x['date'], x['start']))
        return pd.concat([x['data'] for x in segs], ignore_index=True) if segs else None

    def list_tables(self):
        return self.db.collection_names()

    def list_dates(self, table_name, start_date=None, end_date=None, symbol=None):
        collection = self.db[table_name]
        dates = set()
        if start_date is None:
            start_date = '00000000'
        if end_date is None:
            end_date = '99999999'
        for x in collection.find(self.build_query(start_date, end_date, symbol), {"date": 1, '_id': 0}):
            dates.add(x['date'])
        return sorted(list(dates))

    def ser(self, s, version):
        pickle_protocol = 4
        if version == 1:
            return gzip.compress(pickle.dumps(s, protocol=pickle_protocol), compresslevel=2)
        elif version == 2:
            return lzma.compress(pickle.dumps(s, protocol=pickle_protocol), preset=1)
        else:
            raise Exception('unknown version')

    def deser(self, s, version):
        def unpickle(s):
            return pickle.loads(s)

        if version == 1:
            return unpickle(gzip.decompress(s))
        elif version == 2:
            return unpickle(lzma.decompress(s))
        else:
            raise Exception('unknown version')


def patch_pandas_pickle():
    if pd.__version__ < '0.24':
        import sys
        from types import ModuleType
        from pandas.core.internals import BlockManager
        pkg_name = 'pandas.core.internals.managers'
        if pkg_name not in sys.modules:
            m = ModuleType(pkg_name)
            m.BlockManager = BlockManager
            sys.modules[pkg_name] = m
patch_pandas_pickle()

columns1 = ["Date","OrigTime","SendTime","ercvtime","dbtime","ChannelNo","SecurityID","SecurityIDsource", "MDStreamID","PreClosePx",
                   "PxChnage1","PXChange2","openPrice","HighPx","LowPx","close","NumTrades","cum_volume","cum_amount","PE1","PE2","TradingPhase",
                   "totalofferqty", "wa_offerPrice", "totalbidqty", "wa_bidPrice", "PreNAV", "RealTimeNAV", "WarrantPremiumRate", "UpLimitPx",
                   "DownLimitPx", "TotalLongPosition", "unknown1", "unknown2", "unknown3"]
columns2 = ['Date',"OrigTime","SendTime","ercvtime","dbtime","ChannelNo","SecurityID","SecurityIDsource", "MDStreamID",'ask1p','bid1p',
                   "ask1q","bid1q", 'ask2p','bid2p',"ask2q","bid2q",'ask3p','bid3p',"ask3q","bid3q",'ask4p','bid4p',"ask4q","bid4q",'ask5p',
                    'bid5p',"ask5q","bid5q",'ask6p','bid6p',"ask6q","bid6q",'ask7p','bid7p',"ask7q","bid7q",'ask8p','bid8p',"ask8q","bid8q",
                   'ask9p','bid9p',"ask9q","bid9q",'ask10p','bid10p',"ask10q","bid10q","NUMORDERS_B1","NOORDERS_B1","ORDERQTY_B1",
                    "NUMORDERS_S1","NOORDERS_S1","ORDERQTY_S1"]
columns3 =  ["Date","OrigTime","SendTime","ercvtime","dbtime","ChannelNo","SecurityID","SecurityIDsource", "MDStreamID","PreClosePx",
                   "PxChnage1","PXChange2","openPrice","HighPx","LowPx","close","NumTrades","cum_volume","cum_amount","PE1","PE2","TradingPhase",
                   "totalofferqty", "wa_offerPrice", "totalbidqty", "wa_bidPrice", "PreNAV", "RealTimeNAV", "WarrantPremiumRate", "UpLimitPx",
                   "DownLimitPx", "TotalLongPosition"]


startTm = datetime.datetime.now()
readPath = r'\\192.168.10.30\Kevin_zhenyu\day_stock\***'
dataPathLs = np.array(glob.glob(readPath))
dataPathLs = dataPathLs[[np.array([os.path.basename(i).split('.')[0][:2] == 'SZ' for i in dataPathLs])]]
db = pd.DataFrame()
for p in dataPathLs:
    dayData = pd.read_csv(p, compression='gzip')
    db = pd.concat([db, dayData])
print(datetime.datetime.now() - startTm)

startTm = datetime.datetime.now()
year = "2018"
startDate = "1228"
endDate = "1228"
df = []
bad = []
wr_ong = []
readPath = 'J:\\LEVEL2_shenzhen\\' + year + '\\***'
dataPathLs = np.array(glob.glob(readPath))
dateLs = np.array([os.path.basename(i) for i in dataPathLs])
dataPathLs = dataPathLs[(dateLs >= startDate) & (dateLs <= endDate)]

for data in dataPathLs:
    if len(np.array(glob.glob(data +'\\***'))) == 0:
        continue
    
    if len(np.array(glob.glob(data +'\\am_snap_level_spot.7z'))) == 1:
        date = os.path.basename(data)
        path = 'L:\\backup data\\' + year 
        os.chdir(data)
        try:
            a = py7zr.SevenZipFile(data + '\\am_snap_level_spot.7z','r',filters=None)
        except:
            print("Bad unzip here!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
            print(data + '\\am_snap_level_spot.7z')
            bad.append(data + '\\am_snap_level_spot.7z')
            continue
        path1 = path + '\\' + date
        a.extractall(path = path1)
        a.close()
        try:
            a = py7zr.SevenZipFile(data + '\\pm_snap_level_spot.7z','r',filters=None)
        except:
            print("Bad unzip here!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
            print(data + '\\pm_snap_level_spot.7z')
            bad.append(data + '\\pm_snap_level_spot.7z')
            continue
        a.extractall(path = path1)
        a.close()
        try:
            a = py7zr.SevenZipFile(data + '\\am_hq_snap_spot.7z','r',filters=None)
        except:
            print("Bad unzip here!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
            print(data + '\\am_hq_snap_spot.7z')
            bad.append(data + '\\am_hq_snap_spot.7z')
            continue
        path1 = path + '\\' + os.path.basename(data)
        a.extractall(path = path1)
        a.close()
        try:
            a = py7zr.SevenZipFile(data + '\\pm_hq_snap_spot.7z','r',filters=None)
        except:
            print("Bad unzip here!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
            print(data + '\\am_hq_snap_spot.7z')
            bad.append(data + '\\am_hq_snap_spot.7z')
            continue
        path1 = path + '\\' + os.path.basename(data)
        a.extractall(path = path1)
        a.close()
        
        am_snap1 = pd.read_table(path1 + "\\am_hq_snap_spot.txt", header=None)
        try:
            assert(am_snap1.shape[1] == len(columns1))
            am_snap1.columns = columns1       
        except:
            assert(am_snap1.shape[1] == len(columns3))
            am_snap1.columns = columns3     
        pm_snap1 = pd.read_table(path1 + "\\pm_hq_snap_spot.txt", header=None)
        try:
            assert(pm_snap1.shape[1] == len(columns1))
            pm_snap1.columns = columns1       
        except:
            assert(pm_snap1.shape[1] == len(columns3))
            pm_snap1.columns = columns3     
        snapshot1 = pd.concat([am_snap1, pm_snap1]).sort_values(by=["SecurityID", "OrigTime"])
        del am_snap1
        del pm_snap1
        
        am_snap1 = pd.read_table(path1 + "\\am_snap_level_spot.txt", header=None)
        assert(am_snap1.shape[1] == len(columns2))
        am_snap1.columns = columns2       
        pm_snap1 = pd.read_table(path1 + "\\pm_snap_level_spot.txt", header=None)
        assert(pm_snap1.shape[1] == len(columns2))
        pm_snap1.columns = columns2       
        snapshot2 = pd.concat([am_snap1, pm_snap1]).sort_values(by=["SecurityID", "OrigTime"])
        del am_snap1
        del pm_snap1
        
        snapshot1 = snapshot1[(snapshot1["SecurityID"] < 4000) | (snapshot1["SecurityID"] > 300000)]
        snapshot2 = snapshot2[(snapshot2["SecurityID"] < 4000) | (snapshot2["SecurityID"] > 300000)]
        snapshot1['time'] = (snapshot1['OrigTime'] - int(snapshot1['OrigTime'].iloc[0]//1000000000*1000000000)).astype(int)
        snapshot2['time'] = (snapshot2['OrigTime'] - int(snapshot2['OrigTime'].iloc[0]//1000000000*1000000000)).astype(int)
        snapshot = pd.merge(snapshot1, snapshot2, on=['Date',"OrigTime","ChannelNo","SecurityID","SecurityIDsource", "MDStreamID", "time"], how="outer")
        try:
            assert((snapshot.shape[0] == snapshot1.shape[0]) & (snapshot.shape[0] == snapshot2.shape[0]))
        except:
            if snapshot.shape[0] == snapshot1.shape[0]:
                print("snapshot1 have more ticks than snapshot2")
                if all(snapshot[(snapshot["dbtime_y"].isnull()) & ((snapshot["SecurityID"] < 4000) | (snapshot["SecurityID"] > 200000))]["time"].unique() > 150000000):
                    print("More ticks happens after 15:00")
                elif all(snapshot[(snapshot["dbtime_y"].isnull()) & ((snapshot["SecurityID"] < 4000) | (snapshot["SecurityID"] > 200000))]["time"].unique() < 93000000):
                    print("More ticks happens before 9:30")
                else:
                    print("There are ticks happens before 15:00, after 9:30")
            if snapshot.shape[0] == snapshot2.shape[0]:
                print("snapshot2 have more ticks than snapshot1")
                if all(snapshot[(snapshot["dbtime_x"].isnull()) & ((snapshot["SecurityID"] < 4000) | (snapshot["SecurityID"] > 200000))]["time"].unique() > 150000000):
                    print("More ticks happens after 15:00")
                elif all(snapshot[(snapshot["dbtime_x"].isnull()) & ((snapshot["SecurityID"] < 4000) | (snapshot["SecurityID"] > 200000))]["time"].unique() < 93000000):
                    print("More ticks happens before 9:30")
                else:
                    print("There are ticks happens before 15:00, after 9:30")
            else:
                print("snapshot2 don't join with snapshot1")
            snapshot = pd.merge(snapshot1, snapshot2, on=['Date',"OrigTime","ChannelNo","SecurityID","SecurityIDsource", "MDStreamID", "time"])
        del snapshot1
        del snapshot2
           
        snapshot = snapshot.rename(columns={"SecurityID":"StockID"})
        print(int(snapshot['OrigTime'].iloc[0]//1000000000*1000000000))
        
        print("am & pm data 未分卷")
        
    elif len(np.array(glob.glob(data +'\\am_snap_level_spot.7z.001'))) == 1:    
        date = os.path.basename(data)
        path = 'L:\\backup data\\' + year 
        os.chdir(data)
        os.system("copy /b am_snap_level_spot.7z.* am_snap_level_spot.7z")
        try:
            a = py7zr.SevenZipFile(data + '\\am_snap_level_spot.7z','r',filters=None)
        except:
            print("Bad unzip here!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
            print(data + '\\am_snap_level_spot.7z')
            bad.append(data + '\\am_snap_level_spot.7z')
            continue
        path1 = path + '\\' + date
        a.extractall(path = path1)
        a.close()
        os.system("copy /b pm_snap_level_spot.7z.* pm_snap_level_spot.7z")
        try:
            a = py7zr.SevenZipFile(data + '\\pm_snap_level_spot.7z','r',filters=None)
        except:
            print("Bad unzip here!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
            print(data + '\\pm_snap_level_spot.7z')
            bad.append(data + '\\pm_snap_level_spot.7z')
            continue
        a.extractall(path = path1)
        a.close()
        os.system("copy /b am_hq_snap_spot.7z.* am_hq_snap_spot.7z")
        try:
            a = py7zr.SevenZipFile(data + '\\am_hq_snap_spot.7z','r',filters=None)
        except:
            print("Bad unzip here!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
            print(data + '\\am_hq_snap_spot.7z')
            bad.append(data + '\\am_hq_snap_spot.7z')
            continue
        path1 = path + '\\' + date
        a.extractall(path = path1)
        a.close()
        os.system("copy /b pm_hq_snap_spot.7z.* pm_hq_snap_spot.7z")
        try:
            a = py7zr.SevenZipFile(data + '\\pm_hq_snap_spot.7z','r',filters=None)
        except:
            print("Bad unzip here!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
            print(data + '\\pm_hq_snap_spot.7z')
            bad.append(data + '\\pm_hq_snap_spot.7z')
            continue
        path1 = path + '\\' + date
        a.extractall(path = path1)
        a.close()
        
        
        am_snap1 = pd.read_table(path1 + "\\am_hq_snap_spot.txt", header=None)
        try:
            assert(am_snap1.shape[1] == len(columns1))
            am_snap1.columns = columns1       
        except:
            assert(am_snap1.shape[1] == len(columns3))
            am_snap1.columns = columns3       
        pm_snap1 = pd.read_table(path1 + "\\pm_hq_snap_spot.txt", header=None)
        try:
            assert(pm_snap1.shape[1] == len(columns1))
            pm_snap1.columns = columns1       
        except:
            assert(pm_snap1.shape[1] == len(columns3))
            pm_snap1.columns = columns3     
        snapshot1 = pd.concat([am_snap1, pm_snap1]).sort_values(by=["SecurityID", "OrigTime"])
        del am_snap1
        del pm_snap1
        
        am_snap1 = pd.read_table(path1 + "\\am_snap_level_spot.txt", header=None)
        assert(am_snap1.shape[1] == len(columns2))
        am_snap1.columns = columns2        
        pm_snap1 = pd.read_table(path1 + "\\pm_snap_level_spot.txt", header=None)
        assert(pm_snap1.shape[1] == len(columns2))
        pm_snap1.columns = columns2       
        snapshot2 = pd.concat([am_snap1, pm_snap1]).sort_values(by=["SecurityID", "OrigTime"])
        del am_snap1
        del pm_snap1
        
        snapshot1 = snapshot1[(snapshot1["SecurityID"] < 4000) | (snapshot1["SecurityID"] > 300000)]
        snapshot2 = snapshot2[(snapshot2["SecurityID"] < 4000) | (snapshot2["SecurityID"] > 300000)]
        snapshot1['time'] = (snapshot1['OrigTime'] - int(snapshot1['OrigTime'].iloc[0]//1000000000*1000000000)).astype(int)
        snapshot2['time'] = (snapshot2['OrigTime'] - int(snapshot2['OrigTime'].iloc[0]//1000000000*1000000000)).astype(int)
        snapshot = pd.merge(snapshot1, snapshot2, on=['Date',"OrigTime","ChannelNo","SecurityID","SecurityIDsource", "MDStreamID", "time"], how="outer")
        try:
            assert((snapshot.shape[0] == snapshot1.shape[0]) & (snapshot.shape[0] == snapshot2.shape[0]))
        except:
            if snapshot.shape[0] == snapshot1.shape[0]:
                print("snapshot1 have more ticks than snapshot2")
                if all(snapshot[(snapshot["dbtime_y"].isnull()) & ((snapshot["SecurityID"] < 4000) | (snapshot["SecurityID"] > 200000))]["time"].unique() > 150000000):
                    print("More ticks happens after 15:00")
                elif all(snapshot[(snapshot["dbtime_y"].isnull()) & ((snapshot["SecurityID"] < 4000) | (snapshot["SecurityID"] > 200000))]["time"].unique() < 93000000):
                    print("More ticks happens before 9:30")
                else:
                    print("There are ticks happens before 15:00, after 9:30")
            if snapshot.shape[0] == snapshot2.shape[0]:
                print("snapshot2 have more ticks than snapshot1")
                if all(snapshot[(snapshot["dbtime_x"].isnull()) & ((snapshot["SecurityID"] < 4000) | (snapshot["SecurityID"] > 200000))]["time"].unique() > 150000000):
                    print("More ticks happens after 15:00")
                elif all(snapshot[(snapshot["dbtime_x"].isnull()) & ((snapshot["SecurityID"] < 4000) | (snapshot["SecurityID"] > 200000))]["time"].unique() < 93000000):
                    print("More ticks happens before 9:30")
                else:
                    print("There are ticks happens before 15:00, after 9:30")
            else:
                print("snapshot2 don't join with snapshot1")
            snapshot = pd.merge(snapshot1, snapshot2, on=['Date',"OrigTime","ChannelNo","SecurityID","SecurityIDsource", "MDStreamID", "time"])
        del snapshot1
        del snapshot2
        
        snapshot = snapshot.rename(columns={"SecurityID":"StockID"})
        print(int(snapshot['OrigTime'].iloc[0]//1000000000*1000000000))
        
        print("am & pm data 分卷") 
   

    elif len(np.array(glob.glob(data +'\\snap_level.7z'))) == 1: 
        date = os.path.basename(data)
        path = 'L:\\backup data\\' + year 
        os.chdir(data)
        try:
            a = py7zr.SevenZipFile(data + '\\snap_level.7z','r',filters=None)
        except:
            print("Bad unzip here!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
            print(data + '\\snap_level.7z')
            bad.append(data + '\\snap_level.7z')
            continue
        path1 = path + '\\' + date
        a.extractall(path = path1)
        a.close()
        try:
            a = py7zr.SevenZipFile(data + '\\hq_snap.7z','r',filters=None)
        except:
            print("Bad unzip here!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
            print(data + '\\hq_snap.7z')
            bad.append(data + '\\hq_snap.7z')
            continue
        path1 = path + '\\' + date
        a.extractall(path = path1)
        a.close()
        
        
        snapshot1 = pd.read_table(path1 + "\\hq_snap.txt", header=None, encoding="UTF-8-sig")
        try:
            assert(snapshot1.shape[1] == len(columns1))
            snapshot1.columns = columns1
        except:
            assert(snapshot1.shape[1] == len(columns3))
            snapshot1.columns = columns3
        snapshot2 = pd.read_table(path1 + "\\snap_level.txt", header=None, encoding="UTF-8-sig")
        assert(snapshot2.shape[1] == len(columns2))
        
        snapshot1["SecurityID"] = snapshot1["SecurityID"].astype(int)
        snapshot2["SecurityID"] = snapshot2["SecurityID"].astype(int)
        snapshot1 = snapshot1[(snapshot1["SecurityID"] < 4000) | (snapshot1["SecurityID"] > 300000)]
        snapshot2 = snapshot2[(snapshot2["SecurityID"] < 4000) | (snapshot2["SecurityID"] > 300000)]
        snapshot1['time'] = (snapshot1['OrigTime'] - int(snapshot1['OrigTime'].iloc[0]//1000000000*1000000000)).astype(np.int64)
        snapshot2['time'] = (snapshot2['OrigTime'] - int(snapshot2['OrigTime'].iloc[0]//1000000000*1000000000)).astype(np.int64)
        
        snapshot = pd.merge(snapshot1, snapshot2, on=['Date',"OrigTime","ChannelNo","SecurityID","SecurityIDsource", "MDStreamID", "time"], how="outer")
        try:
            assert((snapshot.shape[0] == snapshot1.shape[0]) & (snapshot.shape[0] == snapshot2.shape[0]))
        except:
            if snapshot.shape[0] == snapshot1.shape[0]:
                print("snapshot1 have more ticks than snapshot2")
                if all(snapshot[(snapshot["dbtime_y"].isnull()) & ((snapshot["SecurityID"] < 4000) | (snapshot["SecurityID"] > 200000))]["time"].unique() > 150000000):
                    print("More ticks happens after 15:00")
                elif all(snapshot[(snapshot["dbtime_y"].isnull()) & ((snapshot["SecurityID"] < 4000) | (snapshot["SecurityID"] > 200000))]["time"].unique() < 93000000):
                    print("More ticks happens before 9:30")
                else:
                    print("There are ticks happens before 15:00, after 9:30")
            if snapshot.shape[0] == snapshot2.shape[0]:
                print("snapshot2 have more ticks than snapshot1")
                if all(snapshot[(snapshot["dbtime_x"].isnull()) & ((snapshot["SecurityID"] < 4000) | (snapshot["SecurityID"] > 200000))]["time"].unique() > 150000000):
                    print("More ticks happens after 15:00")
                elif all(snapshot[(snapshot["dbtime_x"].isnull()) & ((snapshot["SecurityID"] < 4000) | (snapshot["SecurityID"] > 200000))]["time"].unique() < 93000000):
                    print("More ticks happens before 9:30")
                else:
                    print("There are ticks happens before 15:00, after 9:30")
            else:
                print("snapshot2 don't join with snapshot1")
            snapshot = pd.merge(snapshot1, snapshot2, on=['Date',"OrigTime","ChannelNo","SecurityID","SecurityIDsource", "MDStreamID", "time"])
        del snapshot1
        del snapshot2
        
        snapshot = snapshot.rename(columns={"SecurityID":"StockID"})
        print(int(snapshot['OrigTime'].iloc[0]//1000000000*1000000000))
        
        print("深交所数据")
        
        
    snapshot["clockAtArrival"] = snapshot["OrigTime"].astype(str).apply(lambda x: np.int64(datetime.datetime.strptime(x, '%Y%m%d%H%M%S%f').timestamp()*1e6))
    snapshot['datetime'] = snapshot["clockAtArrival"].apply(lambda x: datetime.datetime.fromtimestamp(x/1e6))
    snapshot = snapshot.rename(columns={"Date":"date", "NumTrades":"cum_trades_cnt", "HighPx":"high", "LowPx":"low", "totalofferqty":
                                   "total_ask_quantity", "totalbidqty":"total_bid_quantity", "NUMORDERS_B1":"bid1n", "NUMORDERS_S1":"ask1n", "openPrice":"open",
                                    "PreClosePx":"prev_close", "wa_offerPrice":"total_ask_vwap", "wa_bidPrice":"total_bid_vwap"})
    snapshot["skey"] = snapshot["StockID"] + 2000000
    snapshot["ordering"] = snapshot.groupby("skey").cumcount()
    snapshot["ordering"] = snapshot["ordering"] + 1
    snapshot["time"] = snapshot["time"].astype(np.int64) * 1000
    
    snapshot.loc[(~snapshot["ORDERQTY_B1"].isnull()) & (snapshot["ORDERQTY_B1"].str.contains('\|')), "ORDERQTY_B1"]=snapshot[(~snapshot["ORDERQTY_B1"].isnull()) & (snapshot["ORDERQTY_B1"].str.contains('\|'))]["ORDERQTY_B1"].apply(lambda x: x.split('|'))
    snapshot.loc[(~snapshot["ORDERQTY_S1"].isnull()) & (snapshot["ORDERQTY_S1"].str.contains('\|')), "ORDERQTY_S1"]=snapshot[(~snapshot["ORDERQTY_S1"].isnull()) & (snapshot["ORDERQTY_S1"].str.contains('\|'))]["ORDERQTY_S1"].apply(lambda x: x.split('|'))
    for i in range(1, 51):
        snapshot["bid1Top" + str(i) + 'q'] = 0
        snapshot["ask1Top" + str(i) + 'q'] = 0
    for i in range(1, 51):
        snapshot.loc[i <= snapshot["bid1n"], "bid1Top" + str(i) + 'q'] = snapshot.loc[i <= snapshot["bid1n"], "ORDERQTY_B1"].apply(lambda x: int(x[i-1]))
        snapshot.loc[i <= snapshot["ask1n"], "ask1Top" + str(i) + 'q'] = snapshot.loc[i <= snapshot["ask1n"], "ORDERQTY_S1"].apply(lambda x: int(x[i-1]))   
    
    for cols in ["total_bid_orders",'total_ask_orders','total_bid_levels', 'total_ask_levels', 'bid_trade_max_duration',
                 'ask_trade_max_duration', 'cum_canceled_buy_orders', 'cum_canceled_buy_volume', "cum_canceled_buy_amount",
                 "cum_canceled_sell_orders", 'cum_canceled_sell_volume',"cum_canceled_sell_amount", "has_missing",
                 'bid2n', 'bid3n', 'bid4n', 'bid5n', 'bid6n', 'bid7n', 'bid8n', 'bid9n', 'bid10n', 'ask2n', 'ask3n',
                 'ask4n', 'ask5n', 'ask6n', 'ask7n', 'ask8n', 'ask9n', 'ask10n']:
        snapshot[cols] = 0
    
    for col in ["skey", "date", "cum_trades_cnt", "total_bid_orders",
        'total_ask_orders', 'total_bid_levels', 'total_ask_levels', 'cum_canceled_buy_orders','cum_canceled_sell_orders',
            "ordering", 'bid_trade_max_duration', 'ask_trade_max_duration','has_missing', 'bid10n', 'bid9n', 'bid8n', 'bid7n', 'bid6n', 'bid5n', 'bid4n', 'bid3n', 'bid2n', 'bid1n', 
                             'ask1n', 'ask2n', 'ask3n', 'ask4n', 'ask5n', 'ask6n','ask7n', 'ask8n', 'ask9n', 'ask10n','bid1Top1q','bid1Top2q','bid1Top3q','bid1Top4q','bid1Top5q','bid1Top6q',
        'bid1Top7q','bid1Top8q','bid1Top9q','bid1Top10q','bid1Top11q','bid1Top12q','bid1Top13q','bid1Top14q','bid1Top15q','bid1Top16q','bid1Top17q','bid1Top18q',
        'bid1Top19q','bid1Top20q','bid1Top21q','bid1Top22q','bid1Top23q','bid1Top24q','bid1Top25q','bid1Top26q','bid1Top27q','bid1Top28q','bid1Top29q',
        'bid1Top30q','bid1Top31q','bid1Top32q','bid1Top33q','bid1Top34q','bid1Top35q','bid1Top36q','bid1Top37q','bid1Top38q','bid1Top39q','bid1Top40q',
        'bid1Top41q','bid1Top42q','bid1Top43q','bid1Top44q','bid1Top45q','bid1Top46q','bid1Top47q','bid1Top48q','bid1Top49q','bid1Top50q', 'ask1Top1q',
        'ask1Top2q','ask1Top3q','ask1Top4q','ask1Top5q','ask1Top6q','ask1Top7q','ask1Top8q','ask1Top9q','ask1Top10q','ask1Top11q','ask1Top12q','ask1Top13q',
        'ask1Top14q','ask1Top15q','ask1Top16q','ask1Top17q','ask1Top18q','ask1Top19q','ask1Top20q','ask1Top21q','ask1Top22q','ask1Top23q',
        'ask1Top24q','ask1Top25q','ask1Top26q','ask1Top27q','ask1Top28q','ask1Top29q','ask1Top30q','ask1Top31q','ask1Top32q','ask1Top33q',
        'ask1Top34q','ask1Top35q','ask1Top36q','ask1Top37q','ask1Top38q','ask1Top39q','ask1Top40q','ask1Top41q','ask1Top42q','ask1Top43q',
        'ask1Top44q','ask1Top45q','ask1Top46q','ask1Top47q','ask1Top48q','ask1Top49q','ask1Top50q']:
        snapshot[col] = snapshot[col].astype('int32')
    
    for col in ["total_bid_quantity", "total_ask_quantity"]:
        snapshot[col] = snapshot[col].astype('int64')
    
    for col in ['close', 'high', 'low', 'open', 'prev_close', 'total_ask_vwap', 'total_bid_vwap', 'bid1p', 'bid2p', 
                'bid3p', 'bid4p', 'bid5p', 'bid6p', 'bid7p', 'bid8p', 'bid9p', 'bid10p', 'ask1p', 'ask2p', 'ask3p', 
                'ask4p', 'ask5p', 'ask6p', 'ask7p', 'ask8p', 'ask9p', 'ask10p', 'cum_amount']:
        print(col)
        print(snapshot[col].astype(str).apply(lambda x: len(x.split('.')[1])).unique())
    
    for cols in ["cum_canceled_sell_amount", "cum_canceled_buy_amount", 'cum_amount']:
        snapshot[cols] = snapshot[cols].astype('float64')

    assert(sum(snapshot[snapshot["open"] != 0].groupby("skey")["open"].nunique() != 1) == 0)
    assert(sum(snapshot[snapshot["prev_close"] != 0].groupby("skey")["prev_close"].nunique() != 1) == 0)
    snapshot["prev_close"] = np.where(snapshot["time"] >= 91500000000, snapshot.groupby("skey")["prev_close"].transform("max"), snapshot["prev_close"]) 
    snapshot["open"] = np.where(snapshot["cum_volume"] > 0, snapshot.groupby("skey")["open"].transform("max"), snapshot["open"])
    assert(sum(snapshot[snapshot["open"] != 0].groupby("skey")["open"].nunique() != 1) == 0)
    assert(sum(snapshot[snapshot["prev_close"] != 0].groupby("skey")["prev_close"].nunique() != 1) == 0)
    assert(snapshot[snapshot["cum_volume"] > 0]["open"].min() > 0)
    
    print(datetime.datetime.now() - startTm)
    
    
    # check 1
    startTm = datetime.datetime.now()
    da_te = str(snapshot["date"].iloc[0]) 
    da_te = da_te[:4] + '-' + da_te[4:6] + '-' + da_te[6:8]
    db1 = db[db["date"] == da_te]
    db1["ID"] = db1["ID"].str[2:].astype(int) + 2000000
    db1["date"] = (db1["date"].str[:4] + db1["date"].str[5:7] + db1["date"].str[8:]).astype(int)
    snapshot["cum_max"] = snapshot.groupby("skey")["cum_volume"].transform(max)
    s2 = snapshot[snapshot["cum_volume"] == snapshot["cum_max"]].groupby("skey").first().reset_index()
    snapshot.drop("cum_max", axis=1, inplace=True)
    s2 = s2.rename(columns={"skey": "ID", 'open':"d_open", "prev_close":"d_yclose","high":"d_high", "low":"d_low", "close":"d_close", "cum_volume":"d_volume", "cum_amount":"d_amount"})
    s2 = s2[["ID", "date", "d_open", "d_yclose", "d_high", "d_low", "d_close", "d_volume", "d_amount"]]
    re = pd.merge(db1, s2, on=["ID", "date", "d_open", "d_yclose","d_high", "d_low", "d_volume"], how="outer")
    try:
        assert(sum(re["d_amount_y"].isnull()) == 0)
    except:
        display(re[re["d_amount_y"].isnull()])
        wr_ong += [re[re["d_amount_y"].isnull()]]
    del re
    del s2
    del db1
    print(datetime.datetime.now() - startTm)
    
    # check 2
    # first part
    startTm = datetime.datetime.now()
    date = pd.DataFrame(pd.date_range(start='2019-06-10 08:30:00', end='2019-06-10 18:00:00', freq='s'), columns=["Orig"])
    date["time"] = date["Orig"].apply(lambda x: int(x.strftime("%H%M%S"))*1000)
    date["group"] = date["time"]//10000
    snapshot["group"] = snapshot["time"]//10000000
    gl = date[((date["time"] >= 93000000) & (date["time"] <= 113000000))|((date["time"] >= 130000000) & (date["time"] <= 150000000))]["group"].unique()
    l = set(gl) - set(snapshot["group"].unique())
    snapshot["has_missing1"] = 0 
    if len(l) != 0:
        print("massive missing")
        print(l)
        snapshot["order"] = snapshot.groupby(["skey", "time"]).cumcount()
        for i in l:
            snapshot["t"] = snapshot[snapshot["group"] > i].groupby("skey")["time"].transform("min")
            snapshot["has_missing1"] = np.where((snapshot["time"] == snapshot["t"]) & (snapshot["order"] == 0), 1, 0)
        snapshot.drop(["order", "t", "group"], axis=1, inplace=True)   
    else:
        print("no massive missing")
        snapshot.drop(["group"], axis=1, inplace=True)
    



    # second part

    snapshot["time_interval"] = snapshot.groupby("skey")["datetime"].apply(lambda x: x - x.shift(1))
    snapshot["time_interval"] = snapshot["time_interval"].apply(lambda x: x.seconds)
    snapshot["tn_update"] = snapshot.groupby("skey")["cum_trades_cnt"].apply(lambda x: x-x.shift(1))

    f1 = snapshot[(snapshot["time"] >= 93000000000) & (snapshot["tn_update"] != 0)].groupby("skey")["time"].min().reset_index()
    f1 = f1.rename(columns={"time": "time1"})
    f2 = snapshot[(snapshot["time"] >= 130000000000) & (snapshot["tn_update"] != 0)].groupby("skey")["time"].min().reset_index()
    f2 = f2.rename(columns={"time": "time2"})
    f3 = snapshot[(snapshot["time"] >= 150000000000) & (snapshot["tn_update"] != 0)].groupby("skey")["time"].min().reset_index()
    f3 = f3.rename(columns={"time": "time3"})
    snapshot = pd.merge(snapshot, f1, on="skey", how="left")
    del f1
    snapshot = pd.merge(snapshot, f2, on="skey", how="left")
    del f2
    snapshot = pd.merge(snapshot, f3, on="skey", how="left")
    del f3
    p99 = snapshot[(snapshot["time"] > 93000000000) & (snapshot["time"] < 145700000000) & (snapshot["time"] != snapshot["time2"]) & (snapshot["tn_update"] != 0)]\
    .groupby("skey")["tn_update"].apply(lambda x: x.describe([0.99])["99%"]).reset_index()
    p99 = p99.rename(columns={"tn_update":"99%"})
    snapshot = pd.merge(snapshot, p99, on="skey", how="left")

    snapshot["has_missing2"] = 0
    snapshot["has_missing2"] = np.where((snapshot["time_interval"] > 60) & (snapshot["tn_update"] > snapshot["99%"]) & 
         (snapshot["time"] > snapshot["time1"]) & (snapshot["time"] != snapshot["time2"]) & (snapshot["time"] != snapshot["time3"]), 1, 0)
    snapshot.drop(["time_interval", "tn_update", "time1", "time2", "time3", "99%"], axis=1, inplace=True) 

    snapshot["has_missing"] = np.where((snapshot["has_missing1"] == 1) | (snapshot["has_missing2"] == 1), 1, 0)
    snapshot.drop(["has_missing1", "has_missing2"], axis=1, inplace=True) 
    if snapshot[snapshot["has_missing"] == 1].shape[0] != 0:
        print("has missing!!!!!!!!!!!!!!!!!!!!!!!")
        print(snapshot[snapshot["has_missing"] == 1].shape[0])
        mi_ss += [snapshot[snapshot["has_missing"] == 1]]
    print(datetime.datetime.now() - startTm)

    
    
    startTm = datetime.datetime.now()
    snapshot = snapshot[["skey", "date", "time", "clockAtArrival", "datetime", "ordering", "has_missing", "cum_trades_cnt", "cum_volume", "cum_amount", "prev_close",
                            "open", "high", "low", "close", 'bid10p','bid9p','bid8p','bid7p','bid6p','bid5p','bid4p','bid3p','bid2p','bid1p',
                            'ask1p','ask2p','ask3p','ask4p','ask5p','ask6p','ask7p','ask8p','ask9p','ask10p', 'bid10q','bid9q','bid8q',
                             'bid7q','bid6q','bid5q','bid4q','bid3q','bid2q','bid1q', 'ask1q','ask2q','ask3q','ask4q','ask5q','ask6q',
                             'ask7q','ask8q','ask9q','ask10q', 'bid10n', 'bid9n', 'bid8n', 'bid7n', 'bid6n', 'bid5n', 'bid4n', 'bid3n', 'bid2n', 'bid1n', 
                             'ask1n', 'ask2n', 'ask3n', 'ask4n', 'ask5n', 'ask6n','ask7n', 'ask8n', 'ask9n', 'ask10n','bid1Top1q','bid1Top2q','bid1Top3q','bid1Top4q','bid1Top5q','bid1Top6q',
        'bid1Top7q','bid1Top8q','bid1Top9q','bid1Top10q','bid1Top11q','bid1Top12q','bid1Top13q','bid1Top14q','bid1Top15q','bid1Top16q','bid1Top17q','bid1Top18q',
        'bid1Top19q','bid1Top20q','bid1Top21q','bid1Top22q','bid1Top23q','bid1Top24q','bid1Top25q','bid1Top26q','bid1Top27q','bid1Top28q','bid1Top29q',
        'bid1Top30q','bid1Top31q','bid1Top32q','bid1Top33q','bid1Top34q','bid1Top35q','bid1Top36q','bid1Top37q','bid1Top38q','bid1Top39q','bid1Top40q',
        'bid1Top41q','bid1Top42q','bid1Top43q','bid1Top44q','bid1Top45q','bid1Top46q','bid1Top47q','bid1Top48q','bid1Top49q','bid1Top50q', 'ask1Top1q',
        'ask1Top2q','ask1Top3q','ask1Top4q','ask1Top5q','ask1Top6q','ask1Top7q','ask1Top8q','ask1Top9q','ask1Top10q','ask1Top11q','ask1Top12q','ask1Top13q',
        'ask1Top14q','ask1Top15q','ask1Top16q','ask1Top17q','ask1Top18q','ask1Top19q','ask1Top20q','ask1Top21q','ask1Top22q','ask1Top23q',
        'ask1Top24q','ask1Top25q','ask1Top26q','ask1Top27q','ask1Top28q','ask1Top29q','ask1Top30q','ask1Top31q','ask1Top32q','ask1Top33q',
        'ask1Top34q','ask1Top35q','ask1Top36q','ask1Top37q','ask1Top38q','ask1Top39q','ask1Top40q','ask1Top41q','ask1Top42q','ask1Top43q',
        'ask1Top44q','ask1Top45q','ask1Top46q','ask1Top47q','ask1Top48q','ask1Top49q','ask1Top50q',"total_bid_quantity", "total_ask_quantity","total_bid_vwap", "total_ask_vwap",
        "total_bid_orders",'total_ask_orders','total_bid_levels', 'total_ask_levels', 'bid_trade_max_duration', 'ask_trade_max_duration', 'cum_canceled_buy_orders', 'cum_canceled_buy_volume',
        "cum_canceled_buy_amount", "cum_canceled_sell_orders", 'cum_canceled_sell_volume',"cum_canceled_sell_amount"]]
    
    display(snapshot["date"].iloc[0])
    print("SZ finished")
    pd.set_option('max_rows', 200)
    print(snapshot.dtypes)
    print(datetime.datetime.now() - startTm)
print(wr_ong)

C:\Users\win\Anaconda3\lib\site-packages\ipykernel_launcher.py:207: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.

0:04:05.241624

C:\Users\win\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (51,54) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

20181228000000000
am & pm data 未分卷
close
[1 2]
high
[1 2]
low
[1 2]
open
[1 2]
prev_close
[2 1]
total_ask_vwap
[1 2]
total_bid_vwap
[1 2]
bid1p
[1 2]
bid2p
[1 2]
bid3p
[1 2]
bid4p
[1 2]
bid5p
[1 2]
bid6p
[1 2]
bid7p
[1 2]
bid8p
[1 2]
bid9p
[1 2]
bid10p
[1 2]
ask1p
[1 2]
ask2p
[1 2]
ask3p
[1 2]
ask4p
[1 2]
ask5p
[1 2]
ask6p
[1 2]
ask7p
[1 2]
ask8p
[1 2]
ask9p
[1 2]
ask10p
[1 2]
cum_amount
[1 2]
0:20:05.797666

C:\Users\win\Anaconda3\lib\site-packages\ipykernel_launcher.py:594: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\win\Anaconda3\lib\site-packages\ipykernel_launcher.py:595: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,ID,date,d_open,d_high,d_low,d_close_x,d_yclose,d_cumprodCAA,d_dayReturn,d_5dayReturn,...,isZT,allDT,hasDT,isDT,tmrHalted,haltedDays,marketShares,totalShares,d_close_y,d_amount_y
992,2001914,20181228,7.61,7.61,7.43,7.48,7.46,0.973838,0.002681,0.002681,...,0.0,0.0,0.0,0.0,0.0,0.0,666819666.0,666961416.0,NaN,NaN

0:00:03.993824
no massive missing
0:02:50.690505

20181228

SZ finished
skey                                 int32
date                                 int32
time                                 int64
clockAtArrival                       int64
datetime                    datetime64[ns]
ordering                             int32
has_missing                          int32
cum_trades_cnt                       int32
cum_volume                           int64
cum_amount                         float64
prev_close                         float64
open                               float64
high                               float64
low                                float64
close                              float64
bid10p                             float64
bid9p                              float64
bid8p                              float64
bid7p                              float64
bid6p                              float64
bid5p                              float64
bid4p                              float64
bid3p                              float64
bid2p                              float64
bid1p                              float64
ask1p                              float64
ask2p                              float64
ask3p                              float64
ask4p                              float64
ask5p                              float64
ask6p                              float64
ask7p                              float64
ask8p                              float64
ask9p                              float64
ask10p                             float64
bid10q                               int64
bid9q                                int64
bid8q                                int64
bid7q                                int64
bid6q                                int64
bid5q                                int64
bid4q                                int64
bid3q                                int64
bid2q                                int64
bid1q                                int64
ask1q                                int64
ask2q                                int64
ask3q                                int64
ask4q                                int64
ask5q                                int64
ask6q                                int64
ask7q                                int64
ask8q                                int64
ask9q                                int64
ask10q                               int64
bid10n                               int32
bid9n                                int32
bid8n                                int32
bid7n                                int32
bid6n                                int32
bid5n                                int32
bid4n                                int32
bid3n                                int32
bid2n                                int32
bid1n                                int32
ask1n                                int32
ask2n                                int32
ask3n                                int32
ask4n                                int32
ask5n                                int32
ask6n                                int32
ask7n                                int32
ask8n                                int32
ask9n                                int32
ask10n                               int32
bid1Top1q                            int32
bid1Top2q                            int32
bid1Top3q                            int32
bid1Top4q                            int32
bid1Top5q                            int32
bid1Top6q                            int32
bid1Top7q                            int32
bid1Top8q                            int32
bid1Top9q                            int32
bid1Top10q                           int32
bid1Top11q                           int32
bid1Top12q                           int32
bid1Top13q                           int32
bid1Top14q                           int32
bid1Top15q                           int32
bid1Top16q                           int32
bid1Top17q                           int32
bid1Top18q                           int32
bid1Top19q                           int32
bid1Top20q                           int32
bid1Top21q                           int32
bid1Top22q                           int32
bid1Top23q                           int32
bid1Top24q                           int32
bid1Top25q                           int32
bid1Top26q                           int32
bid1Top27q                           int32
bid1Top28q                           int32
bid1Top29q                           int32
bid1Top30q                           int32
bid1Top31q                           int32
bid1Top32q                           int32
bid1Top33q                           int32
bid1Top34q                           int32
bid1Top35q                           int32
bid1Top36q                           int32
bid1Top37q                           int32
bid1Top38q                           int32
bid1Top39q                           int32
bid1Top40q                           int32
bid1Top41q                           int32
bid1Top42q                           int32
bid1Top43q                           int32
bid1Top44q                           int32
bid1Top45q                           int32
bid1Top46q                           int32
bid1Top47q                           int32
bid1Top48q                           int32
bid1Top49q                           int32
bid1Top50q                           int32
ask1Top1q                            int32
ask1Top2q                            int32
ask1Top3q                            int32
ask1Top4q                            int32
ask1Top5q                            int32
ask1Top6q                            int32
ask1Top7q                            int32
ask1Top8q                            int32
ask1Top9q                            int32
ask1Top10q                           int32
ask1Top11q                           int32
ask1Top12q                           int32
ask1Top13q                           int32
ask1Top14q                           int32
ask1Top15q                           int32
ask1Top16q                           int32
ask1Top17q                           int32
ask1Top18q                           int32
ask1Top19q                           int32
ask1Top20q                           int32
ask1Top21q                           int32
ask1Top22q                           int32
ask1Top23q                           int32
ask1Top24q                           int32
ask1Top25q                           int32
ask1Top26q                           int32
ask1Top27q                           int32
ask1Top28q                           int32
ask1Top29q                           int32
ask1Top30q                           int32
ask1Top31q                           int32
ask1Top32q                           int32
ask1Top33q                           int32
ask1Top34q                           int32
ask1Top35q                           int32
ask1Top36q                           int32
ask1Top37q                           int32
ask1Top38q                           int32
ask1Top39q                           int32
ask1Top40q                           int32
ask1Top41q                           int32
ask1Top42q                           int32
ask1Top43q                           int32
ask1Top44q                           int32
ask1Top45q                           int32
ask1Top46q                           int32
ask1Top47q                           int32
ask1Top48q                           int32
ask1Top49q                           int32
ask1Top50q                           int32
total_bid_quantity                   int64
total_ask_quantity                   int64
total_bid_vwap                     float64
total_ask_vwap                     float64
total_bid_orders                     int32
total_ask_orders                     int32
total_bid_levels                     int32
total_ask_levels                     int32
bid_trade_max_duration               int32
ask_trade_max_duration               int32
cum_canceled_buy_orders              int32
cum_canceled_buy_volume              int64
cum_canceled_buy_amount            float64
cum_canceled_sell_orders             int32
cum_canceled_sell_volume             int64
cum_canceled_sell_amount           float64
dtype: object
0:00:04.058140
[          ID      date  d_open  d_high  d_low  d_close_x  d_yclose  \
992  2001914  20181228    7.61    7.61   7.43       7.48      7.46

     d_cumprodCAA  d_dayReturn  d_5dayReturn  ...  isZT  allDT  hasDT  isDT  \
992      0.973838     0.002681      0.002681  ...   0.0    0.0    0.0   0.0

     tmrHalted  haltedDays  marketShares  totalShares  d_close_y  d_amount_y
992        0.0         0.0   666819666.0  666961416.0        NaN         NaN

[1 rows x 27 columns]]

In [2]:
pd.set_option('max_columns', 200)
snapshot[snapshot['time'] > 93000000000].head(5)

,skey,date,time,clockAtArrival,datetime,ordering,has_missing,cum_trades_cnt,cum_volume,cum_amount,prev_close,open,high,low,close,bid10p,bid9p,bid8p,bid7p,bid6p,bid5p,bid4p,bid3p,bid2p,bid1p,ask1p,ask2p,ask3p,ask4p,ask5p,ask6p,ask7p,ask8p,ask9p,ask10p,bid10q,bid9q,bid8q,bid7q,bid6q,bid5q,bid4q,bid3q,bid2q,bid1q,ask1q,ask2q,ask3q,ask4q,ask5q,ask6q,ask7q,ask8q,ask9q,ask10q,bid10n,bid9n,bid8n,bid7n,bid6n,bid5n,bid4n,bid3n,bid2n,bid1n,ask1n,ask2n,ask3n,ask4n,ask5n,ask6n,ask7n,ask8n,ask9n,ask10n,bid1Top1q,bid1Top2q,bid1Top3q,bid1Top4q,bid1Top5q,bid1Top6q,bid1Top7q,bid1Top8q,bid1Top9q,bid1Top10q,bid1Top11q,bid1Top12q,bid1Top13q,bid1Top14q,bid1Top15q,bid1Top16q,bid1Top17q,bid1Top18q,bid1Top19q,bid1Top20q,bid1Top21q,bid1Top22q,bid1Top23q,bid1Top24q,bid1Top25q,bid1Top26q,bid1Top27q,bid1Top28q,bid1Top29q,bid1Top30q,bid1Top31q,bid1Top32q,bid1Top33q,bid1Top34q,bid1Top35q,bid1Top36q,bid1Top37q,bid1Top38q,bid1Top39q,bid1Top40q,bid1Top41q,bid1Top42q,bid1Top43q,bid1Top44q,bid1Top45q,bid1Top46q,bid1Top47q,bid1Top48q,bid1Top49q,bid1Top50q,ask1Top1q,ask1Top2q,ask1Top3q,ask1Top4q,ask1Top5q,ask1Top6q,ask1Top7q,ask1Top8q,ask1Top9q,ask1Top10q,ask1Top11q,ask1Top12q,ask1Top13q,ask1Top14q,ask1Top15q,ask1Top16q,ask1Top17q,ask1Top18q,ask1Top19q,ask1Top20q,ask1Top21q,ask1Top22q,ask1Top23q,ask1Top24q,ask1Top25q,ask1Top26q,ask1Top27q,ask1Top28q,ask1Top29q,ask1Top30q,ask1Top31q,ask1Top32q,ask1Top33q,ask1Top34q,ask1Top35q,ask1Top36q,ask1Top37q,ask1Top38q,ask1Top39q,ask1Top40q,ask1Top41q,ask1Top42q,ask1Top43q,ask1Top44q,ask1Top45q,ask1Top46q,ask1Top47q,ask1Top48q,ask1Top49q,ask1Top50q,total_bid_quantity,total_ask_quantity,total_bid_vwap,total_ask_vwap,total_bid_orders,total_ask_orders,total_bid_levels,total_ask_levels,bid_trade_max_duration,ask_trade_max_duration,cum_canceled_buy_orders,cum_canceled_buy_volume,cum_canceled_buy_amount,cum_canceled_sell_orders,cum_canceled_sell_volume,cum_canceled_sell_amount
73,2000001,20181228,93003000000,1545960603000000,2018-12-28 09:30:03,74,0,128,1617360,15063593.60,9.28,9.31,9.35,9.31,9.34,9.25,9.26,9.27,9.28,9.29,9.30,9.31,9.32,9.33,9.34,9.35,9.36,9.37,9.38,9.39,9.40,9.41,9.42,9.43,9.44,179300,21800,17300,256500,148000,240100,301740,227500,45900,258300,43800,30700,22600,149500,127900,288300,5300,143600,103400,68600,0,0,0,0,0,0,0,0,0,1,7,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2800,1800,2000,2000,21400,10800,3000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2736940,5937660,9.20,9.64,0,0,0,0,0,0,0,0,0.0,0,0,0.0
74,2000001,20181228,93006000000,1545960606000000,2018-12-28 09:30:06,75,0,142,1691643,15758095.82,9.28,9.31,9.35,9.31,9.34,9.25,9.26,9.27,9.28,9.29,9.30,9.31,9.32,9.33,9.34,9.36,9.37,9.38,9.39,9.40,9.41,9.42,9.43,9.44,9.45,182300,25000,17500,270900,149800,243400,319140,259600,45900,34600,34400,22600,163300,135200,292200,5800,143600,108500,68600,208600,0,0,0,0,0,0,0,0,0,8,17,0,0,0,0,0,0,0,0,0,900,14400,8000,300,1800,800,600,7800,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1000,1100,500,4900,1700,2000,300,1000,100,2900,900,5400,3100,1500,4300,500,3200,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2599640,6049860,9.19,9.64,0,0,0,0,0,0,0,0,0.0,0,0,0.0
75,2000001,20181228,93009000000,1545960609000000,2018-12-28 09:30:09,76,0,160,1735143,16164246.82,9.28,9.31,9.35,9.31,9.35,9.25,9.26,9.27,9.28,9.29,9.30,9.31,9.32,9.33,9.35,9.36,9.37,9.38,9.39,9.40,9.41,9.42,9.43,9.44,9.45,182300,25000,18600,275000,125500,243400,318740,261900,31000,8400,34400,22600,165100,136900,293400,5800,143600,108500,68600,208600,0,0,0,0,0,0,0,0,0,2,17,0,0,0,0,0,0,0,0,0,4800,3600,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1000,1100,500,4900,1700,2000,300,1000,100,2900,900,5400,3100,1500,4300,500,3200,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2706640,6093560,9.16,9.64,0,0,0,0,0,0,0,0,0.0,0,0,0.0
76,2000001,20181228,93012000000,1545960612000000,2018-12-28 09:30:12,77,0,185,1784943,16630222.82,9.28,9.31,9.37,9.31,9.35,9.25,9.26,9.27,9.28,9.29,9.30,9.31,9.32,9.33,9.35,9.37,9.38,9.39,9.40,9.41,9.42,9.43,9.44,9.45,9.46,182300,25000,18600,285000,125500,243400,307240,262900,31000,4800,22500,165100,136900,293400,5800,143600,108500,68600,208800,67700,0,0,0,0,0,0,0,0,0,1,10,0,0,0,0,0,0,0,0,0,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1400,5100,400,8000,2000,2600,100,2000,100,800,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2702640,6066160,9.16,9.64,0,0,0,0,0,0,0,0,0.0,0,0,0.0
77,2000001,20181228,93015000000,1545960615000000,2018-12-28 09:30:15,78,0,191,1797643,16749161.82,9.28,9.31,9.37,9.31,9.37,9.26,9.27,9.28,9.29,9.30,9.31,9.32,9.33,9.35,9.36,9.37,9.38,9.39,9.40,9.41,9.42,9.43,9.44,9.45,9.46,25000,18600,285000,125500,243400,307240,259300,31000,1900,3000,12900,165100,136900,293400,5800,143600,108500,68600,208800,67700,0,0,0,0,0,0,0,0,0,1,7,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5300,2000,2600,100,2000,100,800,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2699240,6056260,9.16,9.64,0,0,0,0,0,0,0,0,0.0,0,0,0.0

In [3]:
database_name = 'com_md_eq_cn'
user = "zhenyuy"
password = "bnONBrzSMGoE"

db1 = DB("192.168.10.178", database_name, user, password)
db1.write('md_snapshot_l2', snapshot)

In [1]:
import pandas as pd
import random
import numpy as np
import glob
import os
from unrar import rarfile
import py7zr
import pickle
import datetime

import pymongo
import pandas as pd
import pickle
import datetime
import time
import gzip
import lzma
import pytz


def DB(host, db_name, user, passwd):
    auth_db = db_name if user not in ('admin', 'root') else 'admin'
    uri = 'mongodb://%s:%s@%s/?authSource=%s' % (user, passwd, host, auth_db)
    return DBObj(uri, db_name=db_name)


class DBObj(object):
    def __init__(self, uri, symbol_column='skey', db_name='white_db'):
        self.db_name = db_name
        self.uri = uri
        self.client = pymongo.MongoClient(self.uri)
        self.db = self.client[self.db_name]
        self.chunk_size = 20000
        self.symbol_column = symbol_column
        self.date_column = 'date'

    def parse_uri(self, uri):
        # mongodb://user:password@example.com
        return uri.strip().replace('mongodb://', '').strip('/').replace(':', ' ').replace('@', ' ').split(' ')

    def drop_table(self, table_name):
        self.db.drop_collection(table_name)

    def rename_table(self, old_table, new_table):
        self.db[old_table].rename(new_table)

    def write(self, table_name, df):
        if len(df) == 0: return

        multi_date = False

        if self.date_column in df.columns:
            date = str(df.head(1)[self.date_column].iloc[0])
            multi_date = len(df[self.date_column].unique()) > 1
        else:
            raise Exception('DataFrame should contain date column')

        collection = self.db[table_name]
        collection.create_index([('date', pymongo.ASCENDING), ('symbol', pymongo.ASCENDING)], background=True)
        collection.create_index([('symbol', pymongo.ASCENDING), ('date', pymongo.ASCENDING)], background=True)

        if multi_date:
            for (date, symbol), sub_df in df.groupby([self.date_column, self.symbol_column]):
                date = str(date)
                symbol = int(symbol)
                collection.delete_many({'date': date, 'symbol': symbol})
                self.write_single(collection, date, symbol, sub_df)
        else:
            for symbol, sub_df in df.groupby([self.symbol_column]):
                collection.delete_many({'date': date, 'symbol': symbol})
                self.write_single(collection, date, symbol, sub_df)

    def write_single(self, collection, date, symbol, df):
        for start in range(0, len(df), self.chunk_size):
            end = min(start + self.chunk_size, len(df))
            df_seg = df[start:end]
            version = 1
            seg = {'ver': version, 'data': self.ser(df_seg, version), 'date': date, 'symbol': symbol, 'start': start}
            collection.insert_one(seg)

    def build_query(self, start_date=None, end_date=None, symbol=None):
        query = {}

        def parse_date(x):
            if type(x) == str:
                if len(x) != 8:
                    raise Exception("`date` must be YYYYMMDD format")
                return x
            elif type(x) == datetime.datetime or type(x) == datetime.date:
                return x.strftime("%Y%m%d")
            elif type(x) == int:
                return parse_date(str(x))
            else:
                raise Exception("invalid `date` type: " + str(type(x)))

        if start_date is not None or end_date is not None:
            query['date'] = {}
            if start_date is not None:
                query['date']['$gte'] = parse_date(start_date)
            if end_date is not None:
                query['date']['$lte'] = parse_date(end_date)

        def parse_symbol(x):
            if type(x) == int:
                return x
            else:
                return int(x)

        if symbol:
            if type(symbol) == list or type(symbol) == tuple:
                query['symbol'] = {'$in': [parse_symbol(x) for x in symbol]}
            else:
                query['symbol'] = parse_symbol(symbol)

        return query

    def delete(self, table_name, start_date=None, end_date=None, symbol=None):
        collection = self.db[table_name]

        query = self.build_query(start_date, end_date, symbol)
        if not query:
            print('cannot delete the whole table')
            return None

        collection.delete_many(query)

    def read(self, table_name, start_date=None, end_date=None, symbol=None):
        collection = self.db[table_name]

        query = self.build_query(start_date, end_date, symbol)
        if not query:
            print('cannot read the whole table')
            return None

        segs = []
        for x in collection.find(query):
            x['data'] = self.deser(x['data'], x['ver'])
            segs.append(x)
        segs.sort(key=lambda x: (x['symbol'], x['date'], x['start']))
        return pd.concat([x['data'] for x in segs], ignore_index=True) if segs else None

    def list_tables(self):
        return self.db.collection_names()

    def list_dates(self, table_name, start_date=None, end_date=None, symbol=None):
        collection = self.db[table_name]
        dates = set()
        if start_date is None:
            start_date = '00000000'
        if end_date is None:
            end_date = '99999999'
        for x in collection.find(self.build_query(start_date, end_date, symbol), {"date": 1, '_id': 0}):
            dates.add(x['date'])
        return sorted(list(dates))

    def ser(self, s, version):
        pickle_protocol = 4
        if version == 1:
            return gzip.compress(pickle.dumps(s, protocol=pickle_protocol), compresslevel=2)
        elif version == 2:
            return lzma.compress(pickle.dumps(s, protocol=pickle_protocol), preset=1)
        else:
            raise Exception('unknown version')

    def deser(self, s, version):
        def unpickle(s):
            return pickle.loads(s)

        if version == 1:
            return unpickle(gzip.decompress(s))
        elif version == 2:
            return unpickle(lzma.decompress(s))
        else:
            raise Exception('unknown version')


def patch_pandas_pickle():
    if pd.__version__ < '0.24':
        import sys
        from types import ModuleType
        from pandas.core.internals import BlockManager
        pkg_name = 'pandas.core.internals.managers'
        if pkg_name not in sys.modules:
            m = ModuleType(pkg_name)
            m.BlockManager = BlockManager
            sys.modules[pkg_name] = m
patch_pandas_pickle()

columns1 = ["Date","OrigTime","SendTime","ercvtime","dbtime","ChannelNo","SecurityID","SecurityIDsource", "MDStreamID","PreClosePx",
                   "PxChnage1","PXChange2","openPrice","HighPx","LowPx","close","NumTrades","cum_volume","cum_amount","PE1","PE2","TradingPhase",
                   "totalofferqty", "wa_offerPrice", "totalbidqty", "wa_bidPrice", "PreNAV", "RealTimeNAV", "WarrantPremiumRate", "UpLimitPx",
                   "DownLimitPx", "TotalLongPosition", "unknown1", "unknown2", "unknown3"]
columns2 = ['Date',"OrigTime","SendTime","ercvtime","dbtime","ChannelNo","SecurityID","SecurityIDsource", "MDStreamID",'ask1p','bid1p',
                   "ask1q","bid1q", 'ask2p','bid2p',"ask2q","bid2q",'ask3p','bid3p',"ask3q","bid3q",'ask4p','bid4p',"ask4q","bid4q",'ask5p',
                    'bid5p',"ask5q","bid5q",'ask6p','bid6p',"ask6q","bid6q",'ask7p','bid7p',"ask7q","bid7q",'ask8p','bid8p',"ask8q","bid8q",
                   'ask9p','bid9p',"ask9q","bid9q",'ask10p','bid10p',"ask10q","bid10q","NUMORDERS_B1","NOORDERS_B1","ORDERQTY_B1",
                    "NUMORDERS_S1","NOORDERS_S1","ORDERQTY_S1"]
columns3 =  ["Date","OrigTime","SendTime","ercvtime","dbtime","ChannelNo","SecurityID","SecurityIDsource", "MDStreamID","PreClosePx",
                   "PxChnage1","PXChange2","openPrice","HighPx","LowPx","close","NumTrades","cum_volume","cum_amount","PE1","PE2","TradingPhase",
                   "totalofferqty", "wa_offerPrice", "totalbidqty", "wa_bidPrice", "PreNAV", "RealTimeNAV", "WarrantPremiumRate", "UpLimitPx",
                   "DownLimitPx", "TotalLongPosition"]


startTm = datetime.datetime.now()
readPath = r'\\192.168.10.30\Kevin_zhenyu\day_stock\***'
dataPathLs = np.array(glob.glob(readPath))
dataPathLs = dataPathLs[[np.array([os.path.basename(i).split('.')[0][:2] == 'SZ' for i in dataPathLs])]]
db = pd.DataFrame()
for p in dataPathLs:
    dayData = pd.read_csv(p, compression='gzip')
    db = pd.concat([db, dayData])
print(datetime.datetime.now() - startTm)

startTm = datetime.datetime.now()
year = "2018"
startDate = "0330"
endDate = "0330"
df = []
bad = []
wr_ong = []
readPath = 'L:\\backup_data\\' + year + '\\***'
dataPathLs = np.array(glob.glob(readPath))
dateLs = np.array([os.path.basename(i) for i in dataPathLs])
dataPathLs = dataPathLs[(dateLs >= startDate) & (dateLs <= endDate)]

for path1 in dataPathLs:

    am_snap1 = pd.read_table(path1 + "\\am_hq_snap_spot.txt", header=None)
    try:
        assert(am_snap1.shape[1] == len(columns1))
        am_snap1.columns = columns1       
    except:
        assert(am_snap1.shape[1] == len(columns3))
        am_snap1.columns = columns3     
    pm_snap1 = pd.read_table(path1 + "\\pm_hq_snap_spot.txt", header=None)
    try:
        assert(pm_snap1.shape[1] == len(columns1))
        pm_snap1.columns = columns1       
    except:
        assert(pm_snap1.shape[1] == len(columns3))
        pm_snap1.columns = columns3     
    snapshot1 = pd.concat([am_snap1, pm_snap1]).sort_values(by=["SecurityID", "OrigTime"])
    del am_snap1
    del pm_snap1

    am_snap1 = pd.read_table(path1 + "\\am_snap_level_spot.txt", header=None)
    assert(am_snap1.shape[1] == len(columns2))
    am_snap1.columns = columns2       
    pm_snap1 = pd.read_table(path1 + "\\pm_snap_level_spot.txt", header=None)
    assert(pm_snap1.shape[1] == len(columns2))
    pm_snap1.columns = columns2       
    snapshot2 = pd.concat([am_snap1, pm_snap1]).sort_values(by=["SecurityID", "OrigTime"])
    del am_snap1
    del pm_snap1

    snapshot1 = snapshot1[(snapshot1["SecurityID"] < 4000) | (snapshot1["SecurityID"] > 300000)]
    snapshot2 = snapshot2[(snapshot2["SecurityID"] < 4000) | (snapshot2["SecurityID"] > 300000)]
    snapshot1['time'] = (snapshot1['OrigTime'] - int(snapshot1['OrigTime'].iloc[0]//1000000000*1000000000)).astype(int)
    snapshot2['time'] = (snapshot2['OrigTime'] - int(snapshot2['OrigTime'].iloc[0]//1000000000*1000000000)).astype(int)
    snapshot = pd.merge(snapshot1, snapshot2, on=['Date',"OrigTime","ChannelNo","SecurityID","SecurityIDsource", "MDStreamID", "time"], how="outer")
    try:
        assert((snapshot.shape[0] == snapshot1.shape[0]) & (snapshot.shape[0] == snapshot2.shape[0]))
    except:
        if snapshot.shape[0] == snapshot1.shape[0]:
            print("snapshot1 have more ticks than snapshot2")
            if all(snapshot[(snapshot["dbtime_y"].isnull()) & ((snapshot["SecurityID"] < 4000) | (snapshot["SecurityID"] > 200000))]["time"].unique() > 150000000):
                print("More ticks happens after 15:00")
            elif all(snapshot[(snapshot["dbtime_y"].isnull()) & ((snapshot["SecurityID"] < 4000) | (snapshot["SecurityID"] > 200000))]["time"].unique() < 93000000):
                print("More ticks happens before 9:30")
            else:
                print("There are ticks happens before 15:00, after 9:30")
        if snapshot.shape[0] == snapshot2.shape[0]:
            print("snapshot2 have more ticks than snapshot1")
            if all(snapshot[(snapshot["dbtime_x"].isnull()) & ((snapshot["SecurityID"] < 4000) | (snapshot["SecurityID"] > 200000))]["time"].unique() > 150000000):
                print("More ticks happens after 15:00")
            elif all(snapshot[(snapshot["dbtime_x"].isnull()) & ((snapshot["SecurityID"] < 4000) | (snapshot["SecurityID"] > 200000))]["time"].unique() < 93000000):
                print("More ticks happens before 9:30")
            else:
                print("There are ticks happens before 15:00, after 9:30")
        else:
            print("snapshot2 don't join with snapshot1")
        snapshot = pd.merge(snapshot1, snapshot2, on=['Date',"OrigTime","ChannelNo","SecurityID","SecurityIDsource", "MDStreamID", "time"])
    del snapshot1
    del snapshot2

    snapshot = snapshot.rename(columns={"SecurityID":"StockID"})
    print(int(snapshot['OrigTime'].iloc[0]//1000000000*1000000000))
        
        
    snapshot["clockAtArrival"] = snapshot["OrigTime"].astype(str).apply(lambda x: np.int64(datetime.datetime.strptime(x, '%Y%m%d%H%M%S%f').timestamp()*1e6))
    snapshot['datetime'] = snapshot["clockAtArrival"].apply(lambda x: datetime.datetime.fromtimestamp(x/1e6))
    snapshot = snapshot.rename(columns={"Date":"date", "NumTrades":"cum_trades_cnt", "HighPx":"high", "LowPx":"low", "totalofferqty":
                                   "total_ask_quantity", "totalbidqty":"total_bid_quantity", "NUMORDERS_B1":"bid1n", "NUMORDERS_S1":"ask1n", "openPrice":"open",
                                    "PreClosePx":"prev_close", "wa_offerPrice":"total_ask_vwap", "wa_bidPrice":"total_bid_vwap"})
    snapshot["skey"] = snapshot["StockID"] + 2000000
    snapshot["ordering"] = snapshot.groupby("skey").cumcount()
    snapshot["ordering"] = snapshot["ordering"] + 1
    snapshot["time"] = snapshot["time"].astype(np.int64) * 1000
    
    snapshot.loc[(~snapshot["ORDERQTY_B1"].isnull()) & (snapshot["ORDERQTY_B1"].str.contains('\|')), "ORDERQTY_B1"]=snapshot[(~snapshot["ORDERQTY_B1"].isnull()) & (snapshot["ORDERQTY_B1"].str.contains('\|'))]["ORDERQTY_B1"].apply(lambda x: x.split('|'))
    snapshot.loc[(~snapshot["ORDERQTY_S1"].isnull()) & (snapshot["ORDERQTY_S1"].str.contains('\|')), "ORDERQTY_S1"]=snapshot[(~snapshot["ORDERQTY_S1"].isnull()) & (snapshot["ORDERQTY_S1"].str.contains('\|'))]["ORDERQTY_S1"].apply(lambda x: x.split('|'))
    for i in range(1, 51):
        snapshot["bid1Top" + str(i) + 'q'] = 0
        snapshot["ask1Top" + str(i) + 'q'] = 0
    for i in range(1, 51):
        snapshot.loc[i <= snapshot["bid1n"], "bid1Top" + str(i) + 'q'] = snapshot.loc[i <= snapshot["bid1n"], "ORDERQTY_B1"].apply(lambda x: int(x[i-1]))
        snapshot.loc[i <= snapshot["ask1n"], "ask1Top" + str(i) + 'q'] = snapshot.loc[i <= snapshot["ask1n"], "ORDERQTY_S1"].apply(lambda x: int(x[i-1]))   
    
    for cols in ["total_bid_orders",'total_ask_orders','total_bid_levels', 'total_ask_levels', 'bid_trade_max_duration',
                 'ask_trade_max_duration', 'cum_canceled_buy_orders', 'cum_canceled_buy_volume', "cum_canceled_buy_amount",
                 "cum_canceled_sell_orders", 'cum_canceled_sell_volume',"cum_canceled_sell_amount", "has_missing",
                 'bid2n', 'bid3n', 'bid4n', 'bid5n', 'bid6n', 'bid7n', 'bid8n', 'bid9n', 'bid10n', 'ask2n', 'ask3n',
                 'ask4n', 'ask5n', 'ask6n', 'ask7n', 'ask8n', 'ask9n', 'ask10n']:
        snapshot[cols] = 0
    
    for col in ["skey", "date", "cum_trades_cnt", "total_bid_orders",
        'total_ask_orders', 'total_bid_levels', 'total_ask_levels', 'cum_canceled_buy_orders','cum_canceled_sell_orders',
            "ordering", 'bid_trade_max_duration', 'ask_trade_max_duration','has_missing', 'bid10n', 'bid9n', 'bid8n', 'bid7n', 'bid6n', 'bid5n', 'bid4n', 'bid3n', 'bid2n', 'bid1n', 
                             'ask1n', 'ask2n', 'ask3n', 'ask4n', 'ask5n', 'ask6n','ask7n', 'ask8n', 'ask9n', 'ask10n','bid1Top1q','bid1Top2q','bid1Top3q','bid1Top4q','bid1Top5q','bid1Top6q',
        'bid1Top7q','bid1Top8q','bid1Top9q','bid1Top10q','bid1Top11q','bid1Top12q','bid1Top13q','bid1Top14q','bid1Top15q','bid1Top16q','bid1Top17q','bid1Top18q',
        'bid1Top19q','bid1Top20q','bid1Top21q','bid1Top22q','bid1Top23q','bid1Top24q','bid1Top25q','bid1Top26q','bid1Top27q','bid1Top28q','bid1Top29q',
        'bid1Top30q','bid1Top31q','bid1Top32q','bid1Top33q','bid1Top34q','bid1Top35q','bid1Top36q','bid1Top37q','bid1Top38q','bid1Top39q','bid1Top40q',
        'bid1Top41q','bid1Top42q','bid1Top43q','bid1Top44q','bid1Top45q','bid1Top46q','bid1Top47q','bid1Top48q','bid1Top49q','bid1Top50q', 'ask1Top1q',
        'ask1Top2q','ask1Top3q','ask1Top4q','ask1Top5q','ask1Top6q','ask1Top7q','ask1Top8q','ask1Top9q','ask1Top10q','ask1Top11q','ask1Top12q','ask1Top13q',
        'ask1Top14q','ask1Top15q','ask1Top16q','ask1Top17q','ask1Top18q','ask1Top19q','ask1Top20q','ask1Top21q','ask1Top22q','ask1Top23q',
        'ask1Top24q','ask1Top25q','ask1Top26q','ask1Top27q','ask1Top28q','ask1Top29q','ask1Top30q','ask1Top31q','ask1Top32q','ask1Top33q',
        'ask1Top34q','ask1Top35q','ask1Top36q','ask1Top37q','ask1Top38q','ask1Top39q','ask1Top40q','ask1Top41q','ask1Top42q','ask1Top43q',
        'ask1Top44q','ask1Top45q','ask1Top46q','ask1Top47q','ask1Top48q','ask1Top49q','ask1Top50q']:
        snapshot[col] = snapshot[col].astype('int32')
    
    for col in ["total_bid_quantity", "total_ask_quantity"]:
        snapshot[col] = snapshot[col].astype('int64')
    
    for col in ['close', 'high', 'low', 'open', 'prev_close', 'total_ask_vwap', 'total_bid_vwap', 'bid1p', 'bid2p', 
                'bid3p', 'bid4p', 'bid5p', 'bid6p', 'bid7p', 'bid8p', 'bid9p', 'bid10p', 'ask1p', 'ask2p', 'ask3p', 
                'ask4p', 'ask5p', 'ask6p', 'ask7p', 'ask8p', 'ask9p', 'ask10p', 'cum_amount']:
        print(col)
        print(snapshot[col].astype(str).apply(lambda x: len(x.split('.')[1])).unique())
    
    for cols in ["cum_canceled_sell_amount", "cum_canceled_buy_amount", 'cum_amount']:
        snapshot[cols] = snapshot[cols].astype('float64')

    assert(sum(snapshot[snapshot["open"] != 0].groupby("skey")["open"].nunique() != 1) == 0)
    assert(sum(snapshot[snapshot["prev_close"] != 0].groupby("skey")["prev_close"].nunique() != 1) == 0)
    snapshot["prev_close"] = np.where(snapshot["time"] >= 91500000000, snapshot.groupby("skey")["prev_close"].transform("max"), snapshot["prev_close"]) 
    snapshot["open"] = np.where(snapshot["cum_volume"] > 0, snapshot.groupby("skey")["open"].transform("max"), snapshot["open"])
    assert(sum(snapshot[snapshot["open"] != 0].groupby("skey")["open"].nunique() != 1) == 0)
    assert(sum(snapshot[snapshot["prev_close"] != 0].groupby("skey")["prev_close"].nunique() != 1) == 0)
    assert(snapshot[snapshot["cum_volume"] > 0]["open"].min() > 0)
    
    print(datetime.datetime.now() - startTm)
    
    
    # check 1
    startTm = datetime.datetime.now()
    da_te = str(snapshot["date"].iloc[0]) 
    da_te = da_te[:4] + '-' + da_te[4:6] + '-' + da_te[6:8]
    db1 = db[db["date"] == da_te]
    db1["ID"] = db1["ID"].str[2:].astype(int) + 2000000
    db1["date"] = (db1["date"].str[:4] + db1["date"].str[5:7] + db1["date"].str[8:]).astype(int)
    snapshot["cum_max"] = snapshot.groupby("skey")["cum_volume"].transform(max)
    s2 = snapshot[snapshot["cum_volume"] == snapshot["cum_max"]].groupby("skey").first().reset_index()
    snapshot.drop("cum_max", axis=1, inplace=True)
    s2 = s2.rename(columns={"skey": "ID", 'open':"d_open", "prev_close":"d_yclose","high":"d_high", "low":"d_low", "close":"d_close", "cum_volume":"d_volume", "cum_amount":"d_amount"})
    s2 = s2[["ID", "date", "d_open", "d_yclose", "d_high", "d_low", "d_close", "d_volume", "d_amount"]]
    re = pd.merge(db1, s2, on=["ID", "date", "d_open", "d_yclose","d_high", "d_low", "d_volume"], how="outer")
    try:
        assert(sum(re["d_amount_y"].isnull()) == 0)
    except:
        display(re[re["d_amount_y"].isnull()])
        wr_ong += [re[re["d_amount_y"].isnull()]]
    del re
    del s2
    del db1
    print(datetime.datetime.now() - startTm)
    
    # check 2
    # first part
    startTm = datetime.datetime.now()
    date = pd.DataFrame(pd.date_range(start='2019-06-10 08:30:00', end='2019-06-10 18:00:00', freq='s'), columns=["Orig"])
    date["time"] = date["Orig"].apply(lambda x: int(x.strftime("%H%M%S"))*1000)
    date["group"] = date["time"]//10000
    snapshot["group"] = snapshot["time"]//10000000
    gl = date[((date["time"] >= 93000000) & (date["time"] <= 113000000))|((date["time"] >= 130000000) & (date["time"] <= 150000000))]["group"].unique()
    l = set(gl) - set(snapshot["group"].unique())
    snapshot["has_missing1"] = 0 
    if len(l) != 0:
        print("massive missing")
        print(l)
        snapshot["order"] = snapshot.groupby(["skey", "time"]).cumcount()
        for i in l:
            snapshot["t"] = snapshot[snapshot["group"] > i].groupby("skey")["time"].transform("min")
            snapshot["has_missing1"] = np.where((snapshot["time"] == snapshot["t"]) & (snapshot["order"] == 0), 1, 0)
        snapshot.drop(["order", "t", "group"], axis=1, inplace=True)   
    else:
        print("no massive missing")
        snapshot.drop(["group"], axis=1, inplace=True)
    



    # second part

    snapshot["time_interval"] = snapshot.groupby("skey")["datetime"].apply(lambda x: x - x.shift(1))
    snapshot["time_interval"] = snapshot["time_interval"].apply(lambda x: x.seconds)
    snapshot["tn_update"] = snapshot.groupby("skey")["cum_trades_cnt"].apply(lambda x: x-x.shift(1))

    f1 = snapshot[(snapshot["time"] >= 93000000000) & (snapshot["tn_update"] != 0)].groupby("skey")["time"].min().reset_index()
    f1 = f1.rename(columns={"time": "time1"})
    f2 = snapshot[(snapshot["time"] >= 130000000000) & (snapshot["tn_update"] != 0)].groupby("skey")["time"].min().reset_index()
    f2 = f2.rename(columns={"time": "time2"})
    f3 = snapshot[(snapshot["time"] >= 150000000000) & (snapshot["tn_update"] != 0)].groupby("skey")["time"].min().reset_index()
    f3 = f3.rename(columns={"time": "time3"})
    snapshot = pd.merge(snapshot, f1, on="skey", how="left")
    del f1
    snapshot = pd.merge(snapshot, f2, on="skey", how="left")
    del f2
    snapshot = pd.merge(snapshot, f3, on="skey", how="left")
    del f3
    p99 = snapshot[(snapshot["time"] > 93000000000) & (snapshot["time"] < 145700000000) & (snapshot["time"] != snapshot["time2"]) & (snapshot["tn_update"] != 0)]\
    .groupby("skey")["tn_update"].apply(lambda x: x.describe([0.99])["99%"]).reset_index()
    p99 = p99.rename(columns={"tn_update":"99%"})
    snapshot = pd.merge(snapshot, p99, on="skey", how="left")

    snapshot["has_missing2"] = 0
    snapshot["has_missing2"] = np.where((snapshot["time_interval"] > 60) & (snapshot["tn_update"] > snapshot["99%"]) & 
         (snapshot["time"] > snapshot["time1"]) & (snapshot["time"] != snapshot["time2"]) & (snapshot["time"] != snapshot["time3"]), 1, 0)
    snapshot.drop(["time_interval", "tn_update", "time1", "time2", "time3", "99%"], axis=1, inplace=True) 

    snapshot["has_missing"] = np.where((snapshot["has_missing1"] == 1) | (snapshot["has_missing2"] == 1), 1, 0)
    snapshot.drop(["has_missing1", "has_missing2"], axis=1, inplace=True) 
    if snapshot[snapshot["has_missing"] == 1].shape[0] != 0:
        print("has missing!!!!!!!!!!!!!!!!!!!!!!!")
        print(snapshot[snapshot["has_missing"] == 1].shape[0])
        mi_ss += [snapshot[snapshot["has_missing"] == 1]]
    print(datetime.datetime.now() - startTm)

    
    
    startTm = datetime.datetime.now()
    snapshot = snapshot[["skey", "date", "time", "clockAtArrival", "datetime", "ordering", "has_missing", "cum_trades_cnt", "cum_volume", "cum_amount", "prev_close",
                            "open", "high", "low", "close", 'bid10p','bid9p','bid8p','bid7p','bid6p','bid5p','bid4p','bid3p','bid2p','bid1p',
                            'ask1p','ask2p','ask3p','ask4p','ask5p','ask6p','ask7p','ask8p','ask9p','ask10p', 'bid10q','bid9q','bid8q',
                             'bid7q','bid6q','bid5q','bid4q','bid3q','bid2q','bid1q', 'ask1q','ask2q','ask3q','ask4q','ask5q','ask6q',
                             'ask7q','ask8q','ask9q','ask10q', 'bid10n', 'bid9n', 'bid8n', 'bid7n', 'bid6n', 'bid5n', 'bid4n', 'bid3n', 'bid2n', 'bid1n', 
                             'ask1n', 'ask2n', 'ask3n', 'ask4n', 'ask5n', 'ask6n','ask7n', 'ask8n', 'ask9n', 'ask10n','bid1Top1q','bid1Top2q','bid1Top3q','bid1Top4q','bid1Top5q','bid1Top6q',
        'bid1Top7q','bid1Top8q','bid1Top9q','bid1Top10q','bid1Top11q','bid1Top12q','bid1Top13q','bid1Top14q','bid1Top15q','bid1Top16q','bid1Top17q','bid1Top18q',
        'bid1Top19q','bid1Top20q','bid1Top21q','bid1Top22q','bid1Top23q','bid1Top24q','bid1Top25q','bid1Top26q','bid1Top27q','bid1Top28q','bid1Top29q',
        'bid1Top30q','bid1Top31q','bid1Top32q','bid1Top33q','bid1Top34q','bid1Top35q','bid1Top36q','bid1Top37q','bid1Top38q','bid1Top39q','bid1Top40q',
        'bid1Top41q','bid1Top42q','bid1Top43q','bid1Top44q','bid1Top45q','bid1Top46q','bid1Top47q','bid1Top48q','bid1Top49q','bid1Top50q', 'ask1Top1q',
        'ask1Top2q','ask1Top3q','ask1Top4q','ask1Top5q','ask1Top6q','ask1Top7q','ask1Top8q','ask1Top9q','ask1Top10q','ask1Top11q','ask1Top12q','ask1Top13q',
        'ask1Top14q','ask1Top15q','ask1Top16q','ask1Top17q','ask1Top18q','ask1Top19q','ask1Top20q','ask1Top21q','ask1Top22q','ask1Top23q',
        'ask1Top24q','ask1Top25q','ask1Top26q','ask1Top27q','ask1Top28q','ask1Top29q','ask1Top30q','ask1Top31q','ask1Top32q','ask1Top33q',
        'ask1Top34q','ask1Top35q','ask1Top36q','ask1Top37q','ask1Top38q','ask1Top39q','ask1Top40q','ask1Top41q','ask1Top42q','ask1Top43q',
        'ask1Top44q','ask1Top45q','ask1Top46q','ask1Top47q','ask1Top48q','ask1Top49q','ask1Top50q',"total_bid_quantity", "total_ask_quantity","total_bid_vwap", "total_ask_vwap",
        "total_bid_orders",'total_ask_orders','total_bid_levels', 'total_ask_levels', 'bid_trade_max_duration', 'ask_trade_max_duration', 'cum_canceled_buy_orders', 'cum_canceled_buy_volume',
        "cum_canceled_buy_amount", "cum_canceled_sell_orders", 'cum_canceled_sell_volume',"cum_canceled_sell_amount"]]
    
    display(snapshot["date"].iloc[0])
    print("SZ finished")
    pd.set_option('max_rows', 200)
    print(snapshot.dtypes)
    print(datetime.datetime.now() - startTm)
print(wr_ong)

C:\Users\win\Anaconda3\lib\site-packages\ipykernel_launcher.py:207: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.

0:03:42.745804

C:\Users\win\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (51,54) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

20180330000000000
close
[1 2]
high
[1 2]
low
[1 2]
open
[1 2]
prev_close
[2 1]
total_ask_vwap
[1 2]
total_bid_vwap
[1 2]
bid1p
[1 2]
bid2p
[1 2]
bid3p
[1 2]
bid4p
[1 2]
bid5p
[1 2]
bid6p
[1 2]
bid7p
[1 2]
bid8p
[1 2]
bid9p
[1 2]
bid10p
[1 2]
ask1p
[1 2]
ask2p
[1 2]
ask3p
[1 2]
ask4p
[1 2]
ask5p
[1 2]
ask6p
[1 2]
ask7p
[1 2]
ask8p
[1 2]
ask9p
[1 2]
ask10p
[1 2]
cum_amount
[1 2]
0:10:46.726785

C:\Users\win\Anaconda3\lib\site-packages\ipykernel_launcher.py:359: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\win\Anaconda3\lib\site-packages\ipykernel_launcher.py:360: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,ID,date,d_open,d_high,d_low,d_close_x,d_yclose,d_cumprodCAA,d_dayReturn,d_5dayReturn,...,isZT,allDT,hasDT,isDT,tmrHalted,haltedDays,marketShares,totalShares,d_close_y,d_amount_y
906,2001914,20180330,9.08,9.18,8.99,9.12,9.0,0.986228,0.013333,0.025872,...,0.0,0.0,0.0,0.0,0.0,0.0,666807166.0,666961416.0,NaN,NaN

0:00:04.643543
no massive missing
0:03:08.729965

20180330

SZ finished
skey                                 int32
date                                 int32
time                                 int64
clockAtArrival                       int64
datetime                    datetime64[ns]
ordering                             int32
has_missing                          int32
cum_trades_cnt                       int32
cum_volume                           int64
cum_amount                         float64
prev_close                         float64
open                               float64
high                               float64
low                                float64
close                              float64
bid10p                             float64
bid9p                              float64
bid8p                              float64
bid7p                              float64
bid6p                              float64
bid5p                              float64
bid4p                              float64
bid3p                              float64
bid2p                              float64
bid1p                              float64
ask1p                              float64
ask2p                              float64
ask3p                              float64
ask4p                              float64
ask5p                              float64
ask6p                              float64
ask7p                              float64
ask8p                              float64
ask9p                              float64
ask10p                             float64
bid10q                               int64
bid9q                                int64
bid8q                                int64
bid7q                                int64
bid6q                                int64
bid5q                                int64
bid4q                                int64
bid3q                                int64
bid2q                                int64
bid1q                                int64
ask1q                                int64
ask2q                                int64
ask3q                                int64
ask4q                                int64
ask5q                                int64
ask6q                                int64
ask7q                                int64
ask8q                                int64
ask9q                                int64
ask10q                               int64
bid10n                               int32
bid9n                                int32
bid8n                                int32
bid7n                                int32
bid6n                                int32
bid5n                                int32
bid4n                                int32
bid3n                                int32
bid2n                                int32
bid1n                                int32
ask1n                                int32
ask2n                                int32
ask3n                                int32
ask4n                                int32
ask5n                                int32
ask6n                                int32
ask7n                                int32
ask8n                                int32
ask9n                                int32
ask10n                               int32
bid1Top1q                            int32
bid1Top2q                            int32
bid1Top3q                            int32
bid1Top4q                            int32
bid1Top5q                            int32
bid1Top6q                            int32
bid1Top7q                            int32
bid1Top8q                            int32
bid1Top9q                            int32
bid1Top10q                           int32
bid1Top11q                           int32
bid1Top12q                           int32
bid1Top13q                           int32
bid1Top14q                           int32
bid1Top15q                           int32
bid1Top16q                           int32
bid1Top17q                           int32
bid1Top18q                           int32
bid1Top19q                           int32
bid1Top20q                           int32
bid1Top21q                           int32
bid1Top22q                           int32
bid1Top23q                           int32
bid1Top24q                           int32
bid1Top25q                           int32
bid1Top26q                           int32
bid1Top27q                           int32
bid1Top28q                           int32
bid1Top29q                           int32
bid1Top30q                           int32
bid1Top31q                           int32
bid1Top32q                           int32
bid1Top33q                           int32
bid1Top34q                           int32
bid1Top35q                           int32
bid1Top36q                           int32
bid1Top37q                           int32
bid1Top38q                           int32
bid1Top39q                           int32
bid1Top40q                           int32
bid1Top41q                           int32
bid1Top42q                           int32
bid1Top43q                           int32
bid1Top44q                           int32
bid1Top45q                           int32
bid1Top46q                           int32
bid1Top47q                           int32
bid1Top48q                           int32
bid1Top49q                           int32
bid1Top50q                           int32
ask1Top1q                            int32
ask1Top2q                            int32
ask1Top3q                            int32
ask1Top4q                            int32
ask1Top5q                            int32
ask1Top6q                            int32
ask1Top7q                            int32
ask1Top8q                            int32
ask1Top9q                            int32
ask1Top10q                           int32
ask1Top11q                           int32
ask1Top12q                           int32
ask1Top13q                           int32
ask1Top14q                           int32
ask1Top15q                           int32
ask1Top16q                           int32
ask1Top17q                           int32
ask1Top18q                           int32
ask1Top19q                           int32
ask1Top20q                           int32
ask1Top21q                           int32
ask1Top22q                           int32
ask1Top23q                           int32
ask1Top24q                           int32
ask1Top25q                           int32
ask1Top26q                           int32
ask1Top27q                           int32
ask1Top28q                           int32
ask1Top29q                           int32
ask1Top30q                           int32
ask1Top31q                           int32
ask1Top32q                           int32
ask1Top33q                           int32
ask1Top34q                           int32
ask1Top35q                           int32
ask1Top36q                           int32
ask1Top37q                           int32
ask1Top38q                           int32
ask1Top39q                           int32
ask1Top40q                           int32
ask1Top41q                           int32
ask1Top42q                           int32
ask1Top43q                           int32
ask1Top44q                           int32
ask1Top45q                           int32
ask1Top46q                           int32
ask1Top47q                           int32
ask1Top48q                           int32
ask1Top49q                           int32
ask1Top50q                           int32
total_bid_quantity                   int64
total_ask_quantity                   int64
total_bid_vwap                     float64
total_ask_vwap                     float64
total_bid_orders                     int32
total_ask_orders                     int32
total_bid_levels                     int32
total_ask_levels                     int32
bid_trade_max_duration               int32
ask_trade_max_duration               int32
cum_canceled_buy_orders              int32
cum_canceled_buy_volume              int64
cum_canceled_buy_amount            float64
cum_canceled_sell_orders             int32
cum_canceled_sell_volume             int64
cum_canceled_sell_amount           float64
dtype: object
0:00:04.465053
[          ID      date  d_open  d_high  d_low  d_close_x  d_yclose  \
906  2001914  20180330    9.08    9.18   8.99       9.12       9.0

     d_cumprodCAA  d_dayReturn  d_5dayReturn  ...  isZT  allDT  hasDT  isDT  \
906      0.986228     0.013333      0.025872  ...   0.0    0.0    0.0   0.0

     tmrHalted  haltedDays  marketShares  totalShares  d_close_y  d_amount_y
906        0.0         0.0   666807166.0  666961416.0        NaN         NaN

[1 rows x 27 columns]]

In [2]:
pd.set_option('max_columns', 200)
snapshot[snapshot['time'] > 93000000000].head(5)

,skey,date,time,clockAtArrival,datetime,ordering,has_missing,cum_trades_cnt,cum_volume,cum_amount,prev_close,open,high,low,close,bid10p,bid9p,bid8p,bid7p,bid6p,bid5p,bid4p,bid3p,bid2p,bid1p,ask1p,ask2p,ask3p,ask4p,ask5p,ask6p,ask7p,ask8p,ask9p,ask10p,bid10q,bid9q,bid8q,bid7q,bid6q,bid5q,bid4q,bid3q,bid2q,bid1q,ask1q,ask2q,ask3q,ask4q,ask5q,ask6q,ask7q,ask8q,ask9q,ask10q,bid10n,bid9n,bid8n,bid7n,bid6n,bid5n,bid4n,bid3n,bid2n,bid1n,ask1n,ask2n,ask3n,ask4n,ask5n,ask6n,ask7n,ask8n,ask9n,ask10n,bid1Top1q,bid1Top2q,bid1Top3q,bid1Top4q,bid1Top5q,bid1Top6q,bid1Top7q,bid1Top8q,bid1Top9q,bid1Top10q,bid1Top11q,bid1Top12q,bid1Top13q,bid1Top14q,bid1Top15q,bid1Top16q,bid1Top17q,bid1Top18q,bid1Top19q,bid1Top20q,bid1Top21q,bid1Top22q,bid1Top23q,bid1Top24q,bid1Top25q,bid1Top26q,bid1Top27q,bid1Top28q,bid1Top29q,bid1Top30q,bid1Top31q,bid1Top32q,bid1Top33q,bid1Top34q,bid1Top35q,bid1Top36q,bid1Top37q,bid1Top38q,bid1Top39q,bid1Top40q,bid1Top41q,bid1Top42q,bid1Top43q,bid1Top44q,bid1Top45q,bid1Top46q,bid1Top47q,bid1Top48q,bid1Top49q,bid1Top50q,ask1Top1q,ask1Top2q,ask1Top3q,ask1Top4q,ask1Top5q,ask1Top6q,ask1Top7q,ask1Top8q,ask1Top9q,ask1Top10q,ask1Top11q,ask1Top12q,ask1Top13q,ask1Top14q,ask1Top15q,ask1Top16q,ask1Top17q,ask1Top18q,ask1Top19q,ask1Top20q,ask1Top21q,ask1Top22q,ask1Top23q,ask1Top24q,ask1Top25q,ask1Top26q,ask1Top27q,ask1Top28q,ask1Top29q,ask1Top30q,ask1Top31q,ask1Top32q,ask1Top33q,ask1Top34q,ask1Top35q,ask1Top36q,ask1Top37q,ask1Top38q,ask1Top39q,ask1Top40q,ask1Top41q,ask1Top42q,ask1Top43q,ask1Top44q,ask1Top45q,ask1Top46q,ask1Top47q,ask1Top48q,ask1Top49q,ask1Top50q,total_bid_quantity,total_ask_quantity,total_bid_vwap,total_ask_vwap,total_bid_orders,total_ask_orders,total_bid_levels,total_ask_levels,bid_trade_max_duration,ask_trade_max_duration,cum_canceled_buy_orders,cum_canceled_buy_volume,cum_canceled_buy_amount,cum_canceled_sell_orders,cum_canceled_sell_volume,cum_canceled_sell_amount
85,2000001,20180330,93003000000,1522373403000000,2018-03-30 09:30:03,86,0,576,1807763,19951946.32,11.05,11.04,11.05,11.01,11.04,10.93,10.94,10.95,10.96,10.97,10.98,10.99,11.00,11.01,11.04,11.05,11.06,11.07,11.08,11.09,11.10,11.11,11.12,11.13,11.14,50000,9100,216300,26100,30100,73900,51000,97200,128800,103490,87140,67200,140300,36900,48600,56800,106000,194700,30700,112300,0,0,0,0,0,0,0,0,0,6,25,0,0,0,0,0,0,0,0,0,99590,100,2000,500,200,1100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8740,600,6300,200,2100,2000,2700,800,100,500,300,23100,2000,1000,13600,4000,1800,3000,6000,2700,2000,1700,400,600,900,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3163790,9767920,10.73,11.54,0,0,0,0,0,0,0,0,0.0,0,0,0.0
86,2000001,20180330,93006000000,1522373406000000,2018-03-30 09:30:06,87,0,611,1877963,20726965.32,11.05,11.04,11.05,11.01,11.04,10.95,10.96,10.97,10.98,10.99,11.00,11.01,11.02,11.03,11.04,11.05,11.06,11.07,11.08,11.09,11.10,11.11,11.12,11.13,11.14,223800,28100,30100,76400,53000,110000,133300,11300,59900,58290,91140,67200,152000,56100,52700,79000,108900,196500,30700,113300,0,0,0,0,0,0,0,0,0,18,27,0,0,0,0,0,0,0,0,0,30490,100,2000,500,200,1100,200,100,2000,2000,9000,2500,200,300,3000,500,100,4000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,7640,600,6300,200,2100,2000,2700,800,100,500,300,23100,2000,1000,13600,4000,1800,3000,6000,2700,2000,1700,400,600,900,100,5000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3259990,10021620,10.74,11.53,0,0,0,0,0,0,0,0,0.0,0,0,0.0
87,2000001,20180330,93009000000,1522373409000000,2018-03-30 09:30:09,88,0,655,1942763,21442359.22,11.05,11.04,11.05,11.01,11.04,10.95,10.96,10.97,10.98,10.99,11.00,11.01,11.02,11.03,11.04,11.05,11.06,11.07,11.08,11.09,11.10,11.11,11.12,11.13,11.14,226600,28100,30100,76700,53000,128700,133300,25500,61290,1700,96840,68800,149300,57000,53500,80500,110900,197000,30700,113300,0,0,0,0,0,0,0,0,0,2,30,0,0,0,0,0,0,0,0,0,100,1600,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5840,600,6300,200,2100,2000,2700,800,100,500,300,23100,2000,1000,13600,4000,1800,3000,6000,2700,2000,1700,400,600,900,100,5000,500,6000,1000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3279290,10099820,10.74,11.53,0,0,0,0,0,0,0,0,0.0,0,0,0.0
88,2000001,20180330,93012000000,1522373412000000,2018-03-30 09:30:12,89,0,668,1968063,21721678.22,11.05,11.04,11.05,11.01,11.04,10.94,10.95,10.96,10.97,10.98,10.99,11.00,11.01,11.02,11.03,11.04,11.05,11.06,11.07,11.08,11.09,11.10,11.11,11.12,11.13,10100,234600,28100,30100,76700,53000,129700,133300,27600,51190,79900,86040,68800,149300,57000,53500,89600,110900,197000,27100,0,0,0,0,0,0,0,0,0,9,1,0,0,0,0,0,0,0,0,0,3290,400,500,8000,10000,1000,5000,20000,3000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3304490,10202720,10.74,11.53,0,0,0,0,0,0,0,0,0.0,0,0,0.0
89,2000001,20180330,93015000000,1522373415000000,2018-03-30 09:30:15,90,0,672,1971363,21758109.22,11.05,11.04,11.05,11.01,11.04,10.94,10.95,10.96,10.97,10.98,10.99,11.00,11.01,11.02,11.03,11.04,11.05,11.06,11.07,11.08,11.09,11.10,11.11,11.12,11.13,10100,234700,28100,30100,76700,53000,129900,135100,27600,61090,126800,86040,69800,149300,57000,53500,89600,110900,207000,27100,0,0,0,0,0,0,0,0,0,10,6,0,0,0,0,0,0,0,0,0,3190,400,500,8000,10000,1000,5000,20000,3000,10000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,76700,500,2000,2100,42900,2600,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3319090,10276220,10.74,11.53,0,0,0,0,0,0,0,0,0.0,0,0,0.0

In [3]:
database_name = 'com_md_eq_cn'
user = "zhenyuy"
password = "bnONBrzSMGoE"

db1 = DB("192.168.10.178", database_name, user, password)
db1.write('md_snapshot_l2', snapshot)

In [9]:
import pandas as pd
import random
import numpy as np
import glob
import os
from unrar import rarfile
import py7zr
import pickle
import datetime

columns1 = ["Date","OrigTime","SendTime","ercvtime","dbtime","ChannelNo","SecurityID","SecurityIDsource", "MDStreamID","PreClosePx",
                   "PxChnage1","PXChange2","openPrice","HighPx","LowPx","close","NumTrades","cum_volume","cum_amount","PE1","PE2","TradingPhase",
                   "totalofferqty", "wa_offerPrice", "totalbidqty", "wa_bidPrice", "PreNAV", "RealTimeNAV", "WarrantPremiumRate", "UpLimitPx",
                   "DownLimitPx", "TotalLongPosition", "unknown1", "unknown2", "unknown3"]
columns2 = ['Date',"OrigTime","SendTime","ercvtime","dbtime","ChannelNo","SecurityID","SecurityIDsource", "MDStreamID",'ask1p','bid1p',
                   "ask1q","bid1q", 'ask2p','bid2p',"ask2q","bid2q",'ask3p','bid3p',"ask3q","bid3q",'ask4p','bid4p',"ask4q","bid4q",'ask5p',
                    'bid5p',"ask5q","bid5q",'ask6p','bid6p',"ask6q","bid6q",'ask7p','bid7p',"ask7q","bid7q",'ask8p','bid8p',"ask8q","bid8q",
                   'ask9p','bid9p',"ask9q","bid9q",'ask10p','bid10p',"ask10q","bid10q","NUMORDERS_B1","NOORDERS_B1","ORDERQTY_B1",
                    "NUMORDERS_S1","NOORDERS_S1","ORDERQTY_S1"]
columns3 =  ["Date","OrigTime","SendTime","ercvtime","dbtime","ChannelNo","SecurityID","SecurityIDsource", "MDStreamID","PreClosePx",
                   "PxChnage1","PXChange2","openPrice","HighPx","LowPx","close","NumTrades","cum_volume","cum_amount","PE1","PE2","TradingPhase",
                   "totalofferqty", "wa_offerPrice", "totalbidqty", "wa_bidPrice", "PreNAV", "RealTimeNAV", "WarrantPremiumRate", "UpLimitPx",
                   "DownLimitPx", "TotalLongPosition"]

startTm = datetime.datetime.now()
readPath = r'\\192.168.10.30\Kevin_zhenyu\day_stock\***'
dataPathLs = np.array(glob.glob(readPath))
dataPathLs = dataPathLs[[np.array([os.path.basename(i).split('.')[0][:2] == 'SZ' for i in dataPathLs])]]
db = pd.DataFrame()
for p in dataPathLs:
    dayData = pd.read_csv(p, compression='gzip')
    db = pd.concat([db, dayData])
print(datetime.datetime.now() - startTm)

startTm = datetime.datetime.now()
year = "2019"
startDate = "1025"
endDate = "1025"
df = []
bad = []
readPath = 'J:\\LEVEL2_shenzhen\\' + year + '\\***'
dataPathLs = np.array(glob.glob(readPath))
dateLs = np.array([os.path.basename(i) for i in dataPathLs])
dataPathLs = dataPathLs[(dateLs >= startDate) & (dateLs <= endDate)]

for data in dataPathLs:
    if len(np.array(glob.glob(data +'\\***'))) == 0:
        continue
    
    if len(np.array(glob.glob(data +'\\am_hq_trade_spot.7z'))) == 1:
        date = os.path.basename(data)
        path = 'L:\\backup data\\' + year 
        os.chdir(data)
        try:
            a = py7zr.SevenZipFile(data + '\\am_hq_trade_spot.7z','r',filters=None)
        except:
            print("Bad unzip here!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
            print(data + '\\am_hq_trade_spot.7z')
            bad.append(data + '\\am_hq_trade_spot.7z')
            continue
        path1 = path + '\\' + date
        a.extractall(path = path1)
        a.close()
        try:
            a = py7zr.SevenZipFile(data + '\\pm_hq_trade_spot.7z','r',filters=None)
        except:
            print("Bad unzip here!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
            print(data + '\\pm_hq_trade_spot.7z')
            bad.append(data + '\\pm_hq_trade_spot.7z')
            continue
        a.extractall(path = path1)
        a.close()

        am_trade = pd.read_table(path1 + "\\am_hq_trade_spot.txt",header=None)
        am_trade.columns = ["date","OrigTime","SendTime","recvtime","dbtime","ChannelNo","MDStreamID","ApplSeqNum", "SecurityID","SecurityIDSource", "BidApplSeqNum",
                   "OfferApplSeqNum","trade_price","trade_qty","trade_type","TransactTime"]
        pm_trade = pd.read_table(path1 + "\\pm_hq_trade_spot.txt",header=None)
        pm_trade.columns = ["date","OrigTime","SendTime","recvtime","dbtime","ChannelNo","MDStreamID","ApplSeqNum", "SecurityID","SecurityIDSource", "BidApplSeqNum",
                   "OfferApplSeqNum","trade_price","trade_qty","trade_type","TransactTime"]
        TradeLogSZ1 = pd.concat([am_trade, pm_trade])
        del am_trade
        del pm_trade
        
    elif len(np.array(glob.glob(data +'\\am_hq_trade_spot.7z.001'))) == 1:
        date = os.path.basename(data)
        path = 'L:\\backup data\\' + year 
        os.chdir(data)
        os.system("copy /b am_hq_trade_spot.7z.* am_hq_trade_spot.7z")
        try:
            a = py7zr.SevenZipFile(data + '\\am_hq_trade_spot.7z','r',filters=None)
        except:
            print("Bad unzip here!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
            print(data + '\\am_hq_trade_spot.7z')
            bad.append(data + '\\am_hq_trade_spot.7z')
            continue
        path1 = path + '\\' + date
        a.extractall(path = path1)
        a.close()
        os.system("copy /b pm_hq_trade_spot.7z.* pm_hq_trade_spot.7z")
        try:
            a = py7zr.SevenZipFile(data + '\\pm_hq_trade_spot.7z','r',filters=None)
        except:
            print("Bad unzip here!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
            print(data + '\\pm_hq_trade_spot.7z')
            bad.append(data + '\\pm_hq_trade_spot.7z')
            continue
        a.extractall(path = path1)
        a.close()
        
        am_trade = pd.read_table(path1 + "\\am_hq_trade_spot.txt",header=None)
        am_trade.columns = ["date","OrigTime","SendTime","recvtime","dbtime","ChannelNo","MDStreamID","ApplSeqNum", "SecurityID","SecurityIDSource", "BidApplSeqNum",
                   "OfferApplSeqNum","trade_price","trade_qty","trade_type","TransactTime"]
        pm_trade = pd.read_table(path1 + "\\pm_hq_trade_spot.txt",header=None)
        pm_trade.columns = ["date","OrigTime","SendTime","recvtime","dbtime","ChannelNo","MDStreamID","ApplSeqNum", "SecurityID","SecurityIDSource", "BidApplSeqNum",
                   "OfferApplSeqNum","trade_price","trade_qty","trade_type","TransactTime"]
        TradeLogSZ1 = pd.concat([am_trade, pm_trade])
        del am_trade
        del pm_trade
        
    elif len(np.array(glob.glob(data +'\\hq_trade.7z'))) == 1:
        date = os.path.basename(data)
        path = 'L:\\backup data\\' + year 
        os.chdir(data)
        try:
            a = py7zr.SevenZipFile(data + '\\hq_trade.7z','r',filters=None)
        except:
            print("Bad unzip here!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
            print(data + '\\hq_trade.7z')
            bad.append(data + '\\hq_trade.7z')
            continue
        path1 = path + '\\' + date
        a.extractall(path = path1)
        a.close()
        
        TradeLogSZ1 = pd.read_table(path1 + "\\hq_trade.txt",header=None)
        TradeLogSZ1.columns = ["date","OrigTime","SendTime","recvtime","dbtime","ChannelNo","MDStreamID","ApplSeqNum", "SecurityID","SecurityIDSource", "BidApplSeqNum",
                   "OfferApplSeqNum","trade_price","trade_qty","trade_type","TransactTime"]

    
    TradeLogSZ1 = TradeLogSZ1[(TradeLogSZ1["SecurityID"] < 4000) | (TradeLogSZ1["SecurityID"] > 300000)]
    TradeLogSZ1["trade_money"] = TradeLogSZ1["trade_price"] * TradeLogSZ1["trade_qty"]
    TradeLogSZ1["trade_flag"] = 0
    TradeLogSZ1["skey"] = TradeLogSZ1["SecurityID"] + 2000000
    TradeLogSZ1["clockAtArrival"] = TradeLogSZ1["TransactTime"].astype(str).apply(lambda x: np.int64(datetime.datetime.strptime(x, '%Y%m%d%H%M%S%f').timestamp()*1e6))
    TradeLogSZ1['datetime'] = TradeLogSZ1["clockAtArrival"].apply(lambda x: datetime.datetime.fromtimestamp(x/1e6))
    TradeLogSZ1["time"] = (TradeLogSZ1['TransactTime'] - int(TradeLogSZ1['TransactTime'].iloc[0]//1000000000*1000000000)).astype(np.int64)*1000
    TradeLogSZ1["trade_type"] = np.where(TradeLogSZ1["trade_type"] == 'F', 1, TradeLogSZ1["trade_type"])
    for col in ["skey", "date", "ApplSeqNum", "BidApplSeqNum", "OfferApplSeqNum", "trade_qty", "trade_type", "trade_flag"]:
        TradeLogSZ1[col] = TradeLogSZ1[col].astype('int32')
    for cols in ["trade_money"]:
        TradeLogSZ1[cols] = TradeLogSZ1[cols].round(2)
    display(TradeLogSZ1["trade_price"].astype(str).apply(lambda x: len(x.split('.')[1])).unique())
    
    da_te = str(TradeLogSZ1["date"].iloc[0]) 
    da_te = da_te[:4] + '-' + da_te[4:6] + '-' + da_te[6:8]
    db1 = db[db["date"] == da_te]
    sl = (db1["ID"].str[2:].astype(int) + 2000000).unique()
    db1["max_volume"] = db1.groupby("ID")["d_volume"].transform("max")
    db1["max_amount"] = db1.groupby("ID")["d_amount"].transform("max")
    t1 = db1.groupby("ID")["max_volume", "max_amount"].first().reset_index()
    del db1
    t1["skey"] = t1["ID"].str[2:].astype(int) + 2000000
    trade1 = TradeLogSZ1[TradeLogSZ1["trade_type"] == 1].groupby("skey")["trade_qty"].sum().reset_index()
    trade1.columns=["skey", "cum_volume"]
    trade2 = TradeLogSZ1[TradeLogSZ1["trade_type"] == 1].groupby("skey")["trade_money"].sum().reset_index()
    trade2.columns=["skey", "cum_amount"]
    t2 = pd.merge(trade1, trade2, on="skey")
    re = pd.merge(t1, t2, on="skey", how="outer")
    try:
        assert(t1.shape[0] == t2.shape[0])
        assert(re[re["cum_volume"] != re["max_volume"]].shape[0] == 0)
        assert(re[re["cum_amount"].round(2) != re["max_amount"]].shape[0] == 0)
    except:
        display(set(t1["skey"]) - set(t2["skey"]))
        display(re[re["cum_volume"] != re["max_volume"]])
        display(re[re["cum_amount"].round(2) != re["max_amount"]])
    del t1
    del t2
    del re
 
    TradeLogSZ1 = TradeLogSZ1[["skey", "date", "time", "clockAtArrival", "datetime", "ApplSeqNum", "trade_type", "trade_flag",
                                                 "trade_price", "trade_qty", "BidApplSeqNum", "OfferApplSeqNum"]]
    print(da_te)
    print("trade finished")

    print(datetime.datetime.now() - startTm)

array([1, 2], dtype=int64)

C:\Users\win\Anaconda3\lib\site-packages\ipykernel_launcher.py:158: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\win\Anaconda3\lib\site-packages\ipykernel_launcher.py:159: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

{2001914}

           ID  max_volume    max_amount     skey  cum_volume  cum_amount
453  SZ001914   7061940.0  1.363304e+08  2001914         NaN         NaN

           ID  max_volume    max_amount     skey  cum_volume  cum_amount
453  SZ001914   7061940.0  1.363304e+08  2001914         NaN         NaN

2019-10-25
trade finished
0:16:33.658275

In [4]:
import pymongo
import pandas as pd
import pickle
import datetime
import time
import gzip
import lzma
import pytz


def DB(host, db_name, user, passwd):
    auth_db = db_name if user not in ('admin', 'root') else 'admin'
    uri = 'mongodb://%s:%s@%s/?authSource=%s' % (user, passwd, host, auth_db)
    return DBObj(uri, db_name=db_name)


class DBObj(object):
    def __init__(self, uri, symbol_column='skey', db_name='white_db'):
        self.db_name = db_name
        self.uri = uri
        self.client = pymongo.MongoClient(self.uri)
        self.db = self.client[self.db_name]
        self.chunk_size = 20000
        self.symbol_column = symbol_column
        self.date_column = 'date'

    def parse_uri(self, uri):
        # mongodb://user:password@example.com
        return uri.strip().replace('mongodb://', '').strip('/').replace(':', ' ').replace('@', ' ').split(' ')

    def drop_table(self, table_name):
        self.db.drop_collection(table_name)

    def rename_table(self, old_table, new_table):
        self.db[old_table].rename(new_table)

    def write(self, table_name, df):
        if len(df) == 0: return

        multi_date = False

        if self.date_column in df.columns:
            date = str(df.head(1)[self.date_column].iloc[0])
            multi_date = len(df[self.date_column].unique()) > 1
        else:
            raise Exception('DataFrame should contain date column')

        collection = self.db[table_name]
        collection.create_index([('date', pymongo.ASCENDING), ('symbol', pymongo.ASCENDING)], background=True)
        collection.create_index([('symbol', pymongo.ASCENDING), ('date', pymongo.ASCENDING)], background=True)

        if multi_date:
            for (date, symbol), sub_df in df.groupby([self.date_column, self.symbol_column]):
                date = str(date)
                symbol = int(symbol)
                collection.delete_many({'date': date, 'symbol': symbol})
                self.write_single(collection, date, symbol, sub_df)
        else:
            for symbol, sub_df in df.groupby([self.symbol_column]):
                collection.delete_many({'date': date, 'symbol': symbol})
                self.write_single(collection, date, symbol, sub_df)

    def write_single(self, collection, date, symbol, df):
        for start in range(0, len(df), self.chunk_size):
            end = min(start + self.chunk_size, len(df))
            df_seg = df[start:end]
            version = 1
            seg = {'ver': version, 'data': self.ser(df_seg, version), 'date': date, 'symbol': symbol, 'start': start}
            collection.insert_one(seg)

    def build_query(self, start_date=None, end_date=None, symbol=None):
        query = {}

        def parse_date(x):
            if type(x) == str:
                if len(x) != 8:
                    raise Exception("`date` must be YYYYMMDD format")
                return x
            elif type(x) == datetime.datetime or type(x) == datetime.date:
                return x.strftime("%Y%m%d")
            elif type(x) == int:
                return parse_date(str(x))
            else:
                raise Exception("invalid `date` type: " + str(type(x)))

        if start_date is not None or end_date is not None:
            query['date'] = {}
            if start_date is not None:
                query['date']['$gte'] = parse_date(start_date)
            if end_date is not None:
                query['date']['$lte'] = parse_date(end_date)

        def parse_symbol(x):
            if type(x) == int:
                return x
            else:
                return int(x)

        if symbol:
            if type(symbol) == list or type(symbol) == tuple:
                query['symbol'] = {'$in': [parse_symbol(x) for x in symbol]}
            else:
                query['symbol'] = parse_symbol(symbol)

        return query

    def delete(self, table_name, start_date=None, end_date=None, symbol=None):
        collection = self.db[table_name]

        query = self.build_query(start_date, end_date, symbol)
        if not query:
            print('cannot delete the whole table')
            return None

        collection.delete_many(query)

    def read(self, table_name, start_date=None, end_date=None, symbol=None):
        collection = self.db[table_name]

        query = self.build_query(start_date, end_date, symbol)
        if not query:
            print('cannot read the whole table')
            return None

        segs = []
        for x in collection.find(query):
            x['data'] = self.deser(x['data'], x['ver'])
            segs.append(x)
        segs.sort(key=lambda x: (x['symbol'], x['date'], x['start']))
        return pd.concat([x['data'] for x in segs], ignore_index=True) if segs else None

    def list_tables(self):
        return self.db.collection_names()

    def list_dates(self, table_name, start_date=None, end_date=None, symbol=None):
        collection = self.db[table_name]
        dates = set()
        if start_date is None:
            start_date = '00000000'
        if end_date is None:
            end_date = '99999999'
        for x in collection.find(self.build_query(start_date, end_date, symbol), {"date": 1, '_id': 0}):
            dates.add(x['date'])
        return sorted(list(dates))

    def ser(self, s, version):
        pickle_protocol = 4
        if version == 1:
            return gzip.compress(pickle.dumps(s, protocol=pickle_protocol), compresslevel=2)
        elif version == 2:
            return lzma.compress(pickle.dumps(s, protocol=pickle_protocol), preset=1)
        else:
            raise Exception('unknown version')

    def deser(self, s, version):
        def unpickle(s):
            return pickle.loads(s)

        if version == 1:
            return unpickle(gzip.decompress(s))
        elif version == 2:
            return unpickle(lzma.decompress(s))
        else:
            raise Exception('unknown version')


def patch_pandas_pickle():
    if pd.__version__ < '0.24':
        import sys
        from types import ModuleType
        from pandas.core.internals import BlockManager
        pkg_name = 'pandas.core.internals.managers'
        if pkg_name not in sys.modules:
            m = ModuleType(pkg_name)
            m.BlockManager = BlockManager
            sys.modules[pkg_name] = m
patch_pandas_pickle()

In [11]:
TradeLogSZ1.head(1)

,skey,date,time,clockAtArrival,datetime,ApplSeqNum,trade_type,trade_flag,trade_price,trade_qty,BidApplSeqNum,OfferApplSeqNum
0,2300551,20191025,91500010000,1571966100010000,2019-10-25 09:15:00.010,393,4,0,0.0,600,392,0

In [12]:
# database_name = 'com_md_eq_cn'
# user = "zhenyuy"
# password = "bnONBrzSMGoE"

# db1 = DB("192.168.10.223", database_name, user, password)
# db1.write('md_trade', TradeLogSZ1)

In [8]:
import pandas as pd
import random
import numpy as np
import glob
import os
from unrar import rarfile
import py7zr
import pickle
import datetime

columns1 = ["Date","OrigTime","SendTime","ercvtime","dbtime","ChannelNo","SecurityID","SecurityIDsource", "MDStreamID","PreClosePx",
                   "PxChnage1","PXChange2","openPrice","HighPx","LowPx","close","NumTrades","cum_volume","cum_amount","PE1","PE2","TradingPhase",
                   "totalofferqty", "wa_offerPrice", "totalbidqty", "wa_bidPrice", "PreNAV", "RealTimeNAV", "WarrantPremiumRate", "UpLimitPx",
                   "DownLimitPx", "TotalLongPosition", "unknown1", "unknown2", "unknown3"]
columns2 = ['Date',"OrigTime","SendTime","ercvtime","dbtime","ChannelNo","SecurityID","SecurityIDsource", "MDStreamID",'ask1p','bid1p',
                   "ask1q","bid1q", 'ask2p','bid2p',"ask2q","bid2q",'ask3p','bid3p',"ask3q","bid3q",'ask4p','bid4p',"ask4q","bid4q",'ask5p',
                    'bid5p',"ask5q","bid5q",'ask6p','bid6p',"ask6q","bid6q",'ask7p','bid7p',"ask7q","bid7q",'ask8p','bid8p',"ask8q","bid8q",
                   'ask9p','bid9p',"ask9q","bid9q",'ask10p','bid10p',"ask10q","bid10q","NUMORDERS_B1","NOORDERS_B1","ORDERQTY_B1",
                    "NUMORDERS_S1","NOORDERS_S1","ORDERQTY_S1"]
columns3 =  ["Date","OrigTime","SendTime","ercvtime","dbtime","ChannelNo","SecurityID","SecurityIDsource", "MDStreamID","PreClosePx",
                   "PxChnage1","PXChange2","openPrice","HighPx","LowPx","close","NumTrades","cum_volume","cum_amount","PE1","PE2","TradingPhase",
                   "totalofferqty", "wa_offerPrice", "totalbidqty", "wa_bidPrice", "PreNAV", "RealTimeNAV", "WarrantPremiumRate", "UpLimitPx",
                   "DownLimitPx", "TotalLongPosition"]

startTm = datetime.datetime.now()
readPath = r'\\192.168.10.30\Kevin_zhenyu\day_stock\***'
dataPathLs = np.array(glob.glob(readPath))
dataPathLs = dataPathLs[[np.array([os.path.basename(i).split('.')[0][:2] == 'SZ' for i in dataPathLs])]]
db = pd.DataFrame()
for p in dataPathLs:
    dayData = pd.read_csv(p, compression='gzip')
    db = pd.concat([db, dayData])
print(datetime.datetime.now() - startTm)

startTm = datetime.datetime.now()
year = "2019"
startDate = "0826"
endDate = "0826"
df = []
bad = []
readPath = 'J:\\LEVEL2_shenzhen\\' + year + '\\***'
dataPathLs = np.array(glob.glob(readPath))
dateLs = np.array([os.path.basename(i) for i in dataPathLs])
dataPathLs = dataPathLs[(dateLs >= startDate) & (dateLs <= endDate)]

for data in dataPathLs:
    if len(np.array(glob.glob(data +'\\***'))) == 0:
        continue
    
    if len(np.array(glob.glob(data +'\\am_hq_order_spot.7z'))) == 1:
        date = os.path.basename(data)
        path = 'L:\\backup_data\\' + year 
        os.chdir(data)
        try:
            a = py7zr.SevenZipFile(data + '\\am_hq_order_spot.7z','r',filters=None)
        except:
            print("Bad unzip here!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
            print(data + '\\am_hq_order_spot.7z')
            bad.append(data + '\\am_hq_order_spot.7z')
            continue
        path1 = path + '\\' + date
        a.extractall(path = path1)
        a.close()
        try:
            a = py7zr.SevenZipFile(data + '\\pm_hq_order_spot.7z','r',filters=None)
        except:
            print("Bad unzip here!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
            print(data + '\\pm_hq_order_spot.7z')
            bad.append(data + '\\pm_hq_order_spot.7z')
            continue
        a.extractall(path = path1)
        a.close()
        
        am_order = pd.read_table(path1 + '\\am_hq_order_spot.txt',header=None)
        am_order.columns = ["date","OrigTime","SendTime","recvtime","dbtime","ChannelNo","MDStreamID","ApplSeqNum", "SecurityID","SecurityIDSource", "order_price",
                   "order_qty","TransactTime","order_side","order_type","ConfirmID","Contactor","ContactInfo","ExpirationDays","ExpirationType"]
        pm_order = pd.read_table(path1 + '\\pm_hq_order_spot.txt',header=None)
        pm_order.columns = ["date","OrigTime","SendTime","recvtime","dbtime","ChannelNo","MDStreamID","ApplSeqNum", "SecurityID","SecurityIDSource", "order_price",
                   "order_qty","TransactTime","order_side","order_type","ConfirmID","Contactor","ContactInfo","ExpirationDays","ExpirationType"]
        OrderLog1 = pd.concat([am_order, pm_order])
        del am_order
        del pm_order
  
    
    elif len(np.array(glob.glob(data +'\\am_hq_order_spot.7z.001'))) == 1:
        date = os.path.basename(data)
        path = 'L:\\backup_data\\' + year 
        os.chdir(data)
        os.system("copy /b am_hq_order_spot.7z.* am_hq_order_spot.7z")
        try:
            a = py7zr.SevenZipFile(data + '\\am_hq_order_spot.7z','r',filters=None)
        except:
            print("Bad unzip here!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
            print(data + '\\am_hq_order_spot.7z')
            bad.append(data + '\\am_hq_order_spot.7z')
            continue
        path1 = path + '\\' + date
        a.extractall(path = path1)
        a.close()
        os.system("copy /b pm_hq_order_spot.7z.* pm_hq_order_spot.7z")
        try:
            a = py7zr.SevenZipFile(data + '\\pm_hq_order_spot.7z','r',filters=None)
        except:
            print("Bad unzip here!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
            print(data + '\\pm_hq_order_spot.7z')
            bad.append(data + '\\pm_hq_order_spot.7z')
            continue
        a.extractall(path = path1)
        a.close()
        
        am_order = pd.read_table(path1 + '\\am_hq_order_spot.txt',header=None)
        am_order.columns = ["date","OrigTime","SendTime","recvtime","dbtime","ChannelNo","MDStreamID","ApplSeqNum", "SecurityID","SecurityIDSource", "order_price",
                   "order_qty","TransactTime","order_side","order_type","ConfirmID","Contactor","ContactInfo","ExpirationDays","ExpirationType"]
        pm_order = pd.read_table(path1 + '\\pm_hq_order_spot.txt',header=None)
        pm_order.columns = ["date","OrigTime","SendTime","recvtime","dbtime","ChannelNo","MDStreamID","ApplSeqNum", "SecurityID","SecurityIDSource", "order_price",
                   "order_qty","TransactTime","order_side","order_type","ConfirmID","Contactor","ContactInfo","ExpirationDays","ExpirationType"]
        OrderLog1 = pd.concat([am_order, pm_order])
        del am_order
        del pm_order

    elif len(np.array(glob.glob(data +'\\hq_order.7z'))) == 1:
        date = os.path.basename(data)
        path = 'L:\\backup_data\\' + year 
        os.chdir(data)
        try:
            a = py7zr.SevenZipFile(data + '\\hq_order.7z','r',filters=None)
        except:
            print("Bad unzip here!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
            print(data + '\\hq_order.7z')
            bad.append(data + '\\hq_order.7z')
            continue
        path1 = path + '\\' + date
        a.extractall(path = path1)
        a.close()
        OrderLog1 = pd.read_table(path1 + '\\hq_order.txt',header=None)
        OrderLog1.columns = ["date","OrigTime","SendTime","recvtime","dbtime","ChannelNo","MDStreamID","ApplSeqNum", "SecurityID","SecurityIDSource", "order_price",
                   "order_qty","TransactTime","order_side","order_type","ConfirmID","Contactor","ContactInfo","ExpirationDays","ExpirationType"]
    
    
    OrderLog1 = OrderLog1[(OrderLog1["SecurityID"] < 4000) | (OrderLog1["SecurityID"] > 300000)]
    OrderLog1["skey"] = OrderLog1["SecurityID"] + 2000000
    OrderLog1["clockAtArrival"] = OrderLog1["TransactTime"].astype(str).apply(lambda x: np.int64(datetime.datetime.strptime(x, '%Y%m%d%H%M%S%f').timestamp()*1e6))
    OrderLog1['datetime'] = OrderLog1["clockAtArrival"].apply(lambda x: datetime.datetime.fromtimestamp(x/1e6))
    OrderLog1["time"] = (OrderLog1['TransactTime'] - int(OrderLog1['TransactTime'].iloc[0]//1000000000*1000000000)).astype(np.int64)*1000
    OrderLog1["order_type"] =np.where(OrderLog1["order_type"] == 'U', 3, OrderLog1["order_type"])
    for col in ["skey", "date", "ApplSeqNum", "order_qty", "order_side", "order_type"]:
        OrderLog1[col] = OrderLog1[col].astype('int32')
    display(OrderLog1["order_price"].astype(str).apply(lambda x: len(x.split('.')[1])).unique())
    
    assert(OrderLog1[((OrderLog1["order_side"] != 1) & (OrderLog1["order_side"] != 2)) | (OrderLog1["order_type"].isnull())].shape[0] == 0)
    da_te = str(OrderLog1["date"].iloc[0]) 
    da_te = da_te[:4] + '-' + da_te[4:6] + '-' + da_te[6:8]
    db1 = db[db["date"] == da_te]
    sl = (db1["ID"].str[2:].astype(int) + 2000000).unique()
    del db1
    try:
        assert(len(set(sl) - set(OrderLog1["skey"].unique())) == 0)
    except:
        print(set(sl) - set(OrderLog1["skey"].unique()))
    
    OrderLog1 = OrderLog1[["skey", "date", "time", "clockAtArrival", "datetime", "ApplSeqNum", "order_side", "order_type", "order_price",
                                                 "order_qty"]]
    
    print(OrderLog1["date"].iloc[0])
    print("order finished")
    
    print(datetime.datetime.now() - startTm)

C:\Users\win\Anaconda3\lib\site-packages\ipykernel_launcher.py:28: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.

0:03:47.571899

array([2, 1], dtype=int64)

{2001914}
20190826
order finished
0:17:06.747386

In [9]:
startDate = 20190826
endDate = 20190826
database_name = 'com_md_eq_cn'
user = "zhenyuy"
password = "bnONBrzSMGoE"
db1 = DB("192.168.10.223", database_name, user, password)
trade = db1.read('md_trade', start_date=startDate, end_date=endDate)
trade = trade[trade['skey'] > 2000000]
t1 = trade.groupby('skey')['BidApplSeqNum'].unique().reset_index()
t2 = trade.groupby('skey')['OfferApplSeqNum'].unique().reset_index()
t3 = OrderLog1.groupby('skey')['ApplSeqNum'].unique().reset_index()
t = pd.merge(t1, t2, on='skey')
t['union'] = [list(set(a) | set(b)) for a, b in zip(t.BidApplSeqNum, t.OfferApplSeqNum)]
t = pd.merge(t, t3, on='skey')
t['less'] = [len(set(a) - set(b)) for a, b in zip(t.union, t.ApplSeqNum)]
t[t['less'] > 1]

Empty DataFrame
Columns: [skey, BidApplSeqNum, OfferApplSeqNum, union, ApplSeqNum, less]
Index: []

In [10]:
OrderLog1.head(5)

,skey,date,time,clockAtArrival,datetime,ApplSeqNum,order_side,order_type,order_price,order_qty
0,2002793,20190826,91500000000,1566782100000000,2019-08-26 09:15:00,1,1,2,17.85,479700
1,2002793,20190826,91500000000,1566782100000000,2019-08-26 09:15:00,2,1,2,17.85,97900
2,2002793,20190826,91500000000,1566782100000000,2019-08-26 09:15:00,3,1,2,17.85,584800
3,2002793,20190826,91500000000,1566782100000000,2019-08-26 09:15:00,4,1,2,17.85,451800
4,2002793,20190826,91500000000,1566782100000000,2019-08-26 09:15:00,5,1,2,17.85,983700

In [11]:
database_name = 'com_md_eq_cn'
user = "zhenyuy"
password = "bnONBrzSMGoE"

db1 = DB("192.168.10.223", database_name, user, password)
db1.write('md_order', OrderLog1)

In [1]:
import pandas as pd
import random
import numpy as np
import glob
import os
from unrar import rarfile
import py7zr
import pickle
import datetime
import time
pd.set_option("max_columns", 200)

startTm = datetime.datetime.now()
readPath = r'\\192.168.10.30\Kevin_zhenyu\day_stock\***'
dataPathLs = np.array(glob.glob(readPath))
dataPathLs = dataPathLs[[np.array([os.path.basename(i).split('.')[0][:2] == 'SZ' for i in dataPathLs])]]
db = pd.DataFrame()
for p in dataPathLs:
    dayData = pd.read_csv(p, compression='gzip')
    db = pd.concat([db, dayData])
print(datetime.datetime.now() - startTm)

import pymongo
import pandas as pd
import pickle
import datetime
import time
import gzip
import lzma
import pytz


def DB(host, db_name, user, passwd):
    auth_db = db_name if user not in ('admin', 'root') else 'admin'
    uri = 'mongodb://%s:%s@%s/?authSource=%s' % (user, passwd, host, auth_db)
    return DBObj(uri, db_name=db_name)


class DBObj(object):
    def __init__(self, uri, symbol_column='skey', db_name='white_db'):
        self.db_name = db_name
        self.uri = uri
        self.client = pymongo.MongoClient(self.uri)
        self.db = self.client[self.db_name]
        self.chunk_size = 20000
        self.symbol_column = symbol_column
        self.date_column = 'date'

    def parse_uri(self, uri):
        # mongodb://user:password@example.com
        return uri.strip().replace('mongodb://', '').strip('/').replace(':', ' ').replace('@', ' ').split(' ')

    def drop_table(self, table_name):
        self.db.drop_collection(table_name)

    def rename_table(self, old_table, new_table):
        self.db[old_table].rename(new_table)

    def write(self, table_name, df):
        if len(df) == 0: return

        multi_date = False

        if self.date_column in df.columns:
            date = str(df.head(1)[self.date_column].iloc[0])
            multi_date = len(df[self.date_column].unique()) > 1
        else:
            raise Exception('DataFrame should contain date column')

        collection = self.db[table_name]
        collection.create_index([('date', pymongo.ASCENDING), ('symbol', pymongo.ASCENDING)], background=True)
        collection.create_index([('symbol', pymongo.ASCENDING), ('date', pymongo.ASCENDING)], background=True)

        if multi_date:
            for (date, symbol), sub_df in df.groupby([self.date_column, self.symbol_column]):
                date = str(date)
                symbol = int(symbol)
                collection.delete_many({'date': date, 'symbol': symbol})
                self.write_single(collection, date, symbol, sub_df)
        else:
            for symbol, sub_df in df.groupby([self.symbol_column]):
                collection.delete_many({'date': date, 'symbol': symbol})
                self.write_single(collection, date, symbol, sub_df)

    def write_single(self, collection, date, symbol, df):
        for start in range(0, len(df), self.chunk_size):
            end = min(start + self.chunk_size, len(df))
            df_seg = df[start:end]
            version = 1
            seg = {'ver': version, 'data': self.ser(df_seg, version), 'date': date, 'symbol': symbol, 'start': start}
            collection.insert_one(seg)

    def build_query(self, start_date=None, end_date=None, symbol=None):
        query = {}

        def parse_date(x):
            if type(x) == str:
                if len(x) != 8:
                    raise Exception("`date` must be YYYYMMDD format")
                return x
            elif type(x) == datetime.datetime or type(x) == datetime.date:
                return x.strftime("%Y%m%d")
            elif type(x) == int:
                return parse_date(str(x))
            else:
                raise Exception("invalid `date` type: " + str(type(x)))

        if start_date is not None or end_date is not None:
            query['date'] = {}
            if start_date is not None:
                query['date']['$gte'] = parse_date(start_date)
            if end_date is not None:
                query['date']['$lte'] = parse_date(end_date)

        def parse_symbol(x):
            if type(x) == int:
                return x
            else:
                return int(x)

        if symbol:
            if type(symbol) == list or type(symbol) == tuple:
                query['symbol'] = {'$in': [parse_symbol(x) for x in symbol]}
            else:
                query['symbol'] = parse_symbol(symbol)

        return query

    def delete(self, table_name, start_date=None, end_date=None, symbol=None):
        collection = self.db[table_name]

        query = self.build_query(start_date, end_date, symbol)
        if not query:
            print('cannot delete the whole table')
            return None

        collection.delete_many(query)

    def read(self, table_name, start_date=None, end_date=None, symbol=None):
        collection = self.db[table_name]

        query = self.build_query(start_date, end_date, symbol)
        if not query:
            print('cannot read the whole table')
            return None

        segs = []
        for x in collection.find(query):
            x['data'] = self.deser(x['data'], x['ver'])
            segs.append(x)
        segs.sort(key=lambda x: (x['symbol'], x['date'], x['start']))
        return pd.concat([x['data'] for x in segs], ignore_index=True) if segs else None

    def list_tables(self):
        return self.db.collection_names()

    def list_dates(self, table_name, start_date=None, end_date=None, symbol=None):
        collection = self.db[table_name]
        dates = set()
        if start_date is None:
            start_date = '00000000'
        if end_date is None:
            end_date = '99999999'
        for x in collection.find(self.build_query(start_date, end_date, symbol), {"date": 1, '_id': 0}):
            dates.add(x['date'])
        return sorted(list(dates))

    def ser(self, s, version):
        pickle_protocol = 4
        if version == 1:
            return gzip.compress(pickle.dumps(s, protocol=pickle_protocol), compresslevel=2)
        elif version == 2:
            return lzma.compress(pickle.dumps(s, protocol=pickle_protocol), preset=1)
        else:
            raise Exception('unknown version')

    def deser(self, s, version):
        def unpickle(s):
            return pickle.loads(s)

        if version == 1:
            return unpickle(gzip.decompress(s))
        elif version == 2:
            return unpickle(lzma.decompress(s))
        else:
            raise Exception('unknown version')


def patch_pandas_pickle():
    if pd.__version__ < '0.24':
        import sys
        from types import ModuleType
        from pandas.core.internals import BlockManager
        pkg_name = 'pandas.core.internals.managers'
        if pkg_name not in sys.modules:
            m = ModuleType(pkg_name)
            m.BlockManager = BlockManager
            sys.modules[pkg_name] = m
patch_pandas_pickle()

red = pd.read_csv(r'L:\backup data\redundancy.csv')

date_list = ['20170628', '20170630', '20170714', '20180312', '20180330', '20181228']
for d in date_list:
    db1 = DB("192.168.10.178", 'com_md_eq_cn', 'zhenyuy', 'bnONBrzSMGoE')
    SZ = db1.read('md_snapshot_l2', start_date=d, end_date=d)
    dd = d[:4] + '-' + d[4:6] + '-' + d[6:]
    sl = (db[db['date'] == dd]['ID'].str[2:].astype(int) + 2000000).unique()
    sl1 = SZ[SZ['skey'] > 2000000]['skey'].unique()
    display(set(sl) - set(sl1))
    assert(SZ[SZ['skey'].isin(set(sl1) - set(sl))]['close'].nunique() == 1)
    assert((len(set(red[red['date'] == int(d)]['skey'].unique()) - (set(sl1) - set(sl))) == 0) & 
          (len((set(sl1) - set(sl)) -  set(red[red['date'] == int(d)]['skey'].unique())) == 0))
    db1.delete('md_snapshot_l2', start_date=d, end_date=d, symbol=list(set(sl1) - set(sl)))
    print(d + ' finished')

C:\Users\win\Anaconda3\lib\site-packages\ipykernel_launcher.py:16: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  app.launch_new_instance()

0:04:10.351442

{2001872, 2001914}

20170628 finished

{2001872, 2001914}

20170630 finished

{2001872, 2001914}

20170714 finished

{2001914}

20180312 finished

{2001914}

20180330 finished

{2001914}

20181228 finished