In [1]:
import pandas as pd
import numpy as np

logSZ = pd.read_csv(r'\\192.168.10.30\Kevin_zhenyu\rawData\logs_20200324_zs_92_01_day_data\mdLog_SZ_20200324_0836.csv',
                    encoding="utf-8").loc[:, ["clockAtArrival", "sequenceNo", "source", "StockID",
                                              "exchange", "time", "cum_volume", "cum_amount", "close",
                                              "bid1p", "bid2p", "bid3p", "bid4p", "bid5p", "bid1q",
                                              "bid2q", "bid3q", "bid4q", "bid5q", "ask1p", "ask2p",
                                              "ask3p", "ask4p", "ask5p", "ask1q", "ask2q", "ask3q",
                                              "ask4q", "ask5q", "openPrice"]]
logSZ1 = pd.read_csv(r'\\192.168.10.30\Kevin_zhenyu\check\20200324\full_20200324_zt_88_02_day_8843.tar\mdLog_SZ_20200324_0838.csv',
                    encoding="utf-8").loc[:, ["clockAtArrival", "sequenceNo", "source", "StockID",
                                              "exchange", "time", "cum_volume", "cum_amount", "close",
                                              "bid1p", "bid2p", "bid3p", "bid4p", "bid5p", "bid1q",
                                              "bid2q", "bid3q", "bid4q", "bid5q", "ask1p", "ask2p",
                                              "ask3p", "ask4p", "ask5p", "ask1q", "ask2q", "ask3q",
                                              "ask4q", "ask5q", "openPrice"]]
# logSZ2 = pd.read_csv('E:\\compare\\temp 8865\\mdLog_SZ_20200120_0834.csv',
#                      encoding="utf-8").loc[:, ["clockAtArrival", "sequenceNo", "source", "StockID",
#                                                "exchange", "time", "cum_volume", "cum_amount", "close",
#                                                "bid1p", "bid2p", "bid3p", "bid4p", "bid5p", "bid1q",
#                                                "bid2q", "bid3q", "bid4q", "bid5q", "ask1p", "ask2p",
#                                                "ask3p", "ask4p", "ask5p", "ask1q", "ask2q", "ask3q",
#                                                "ask4q", "ask5q", "openPrice"]]
# logSZ3 = pd.read_csv('E:\\compare\\native 88\\mdLog_SZ_20200115_0835.csv',
#                      encoding="utf-8").loc[:, ["clockAtArrival", "sequenceNo", "source", "StockID",
#                                                "exchange", "time", "cum_volume", "cum_amount", "close",
#                                                "bid1p", "bid2p", "bid3p", "bid4p", "bid5p", "bid1q",
#                                                "bid2q", "bid3q", "bid4q", "bid5q", "ask1p", "ask2p",
#                                                "ask3p", "ask4p", "ask5p", "ask1q", "ask2q", "ask3q",
#                                                "ask4q", "ask5q", "openPrice"]]
# 1. data format
# 1.1 in general
print("original data source type: ")
print(logSZ["source"].unique())
print("new data source type: ")
print(logSZ1["source"].unique())
print(logSZ["time"].unique())
print(logSZ1["time"].unique())

original data source type:
[4 3]
new data source type:
[11 12]
['08:36:36.000' '08:37:36.000' '08:38:36.000' ... '15:15:03.000'
 '15:16:03.000' '15:17:03.000']
['08:38:36' '08:38:33' '08:39:33' ... '15:32:48' '15:33:00' '15:33:03']

In [26]:
logSZ2 = logSZ1[logSZ1["source"] == 24]
logSZ1 = logSZ1[logSZ1["source"].isin([20, 21])]
print(logSZ["time"].unique())
print(logSZ1["time"].unique())
print(logSZ2["time"].unique())

['08:32:51.000' '08:32:54.000' '08:33:51.000' ... '15:16:03.000'
 '15:17:03.000' '15:18:03.000']
['08:25:51' '08:43:15' '08:25:54' ... '14:59:51' '14:59:54' '15:00:03']
['09:12:51.000' '09:12:54.000' '09:13:51.000' ... '15:19:03.000'
 '15:20:03.000' '15:21:03.000']

In [ ]:
import pandas as pd
import numpy as np
post = pd.read_csv(r'\\192.168.10.30\Kevin_zhenyu\check\20200317\full_20200316_zt_52_01_day_5274\full_20200316_zt_52_01_day_5274.tar.gz\mdLog_SZ_20200316_0912.csv',
                    encoding="utf-8").loc[:, ["clockAtArrival", "sequenceNo", "source", "StockID",
                                              "exchange", "time", "cum_volume", "cum_amount", "close",
                                              "bid1p", "bid2p", "bid3p", "bid4p", "bid5p", "bid1q",
                                              "bid2q", "bid3q", "bid4q", "bid5q", "ask1p", "ask2p",
                                              "ask3p", "ask4p", "ask5p", "ask1q", "ask2q", "ask3q",
                                              "ask4q", "ask5q", "openPrice"]]
pre = pd.read_csv(r'\\192.168.10.30\Kevin_zhenyu\check\20200317\full_20200316_zt_52_01_day_5271\mdLog_SZ_20200316_0909.csv',
                    encoding="utf-8").loc[:, ["clockAtArrival", "sequenceNo", "source", "StockID",
                                              "exchange", "time", "cum_volume", "cum_amount", "close",
                                              "bid1p", "bid2p", "bid3p", "bid4p", "bid5p", "bid1q",
                                              "bid2q", "bid3q", "bid4q", "bid5q", "ask1p", "ask2p",
                                              "ask3p", "ask4p", "ask5p", "ask1q", "ask2q", "ask3q",
                                              "ask4q", "ask5q", "openPrice"]]
tdf = pd.read_csv(r'\\192.168.10.30\Kevin_zhenyu\check\20200317\full_20200316_zt_52_01_day_sidetdf\mdLog_SZ_20200316_0909.csv',
                    encoding="utf-8").loc[:, ["clockAtArrival", "sequenceNo", "source", "StockID",
                                              "exchange", "time", "cum_volume", "cum_amount", "close",
                                              "bid1p", "bid2p", "bid3p", "bid4p", "bid5p", "bid1q",
                                              "bid2q", "bid3q", "bid4q", "bid5q", "ask1p", "ask2p",
                                              "ask3p", "ask4p", "ask5p", "ask1q", "ask2q", "ask3q",
                                              "ask4q", "ask5q", "openPrice"]]



print("post data source type: ")
print(post["source"].unique())
print("pre data source type: ")
print(pre["source"].unique())
print("tdf data source type: ")
print(tdf["source"].unique())

print(post["time"].unique())
print(pre["time"].unique())
print(tdf["time"].unique())

In [ ]:
display(post[(post["StockID"] == 1) & (post["time"] >= 134500000) & (post["time"] <= 135000000)])
display(pre[(pre["StockID"] == 1) & (pre["time"] >= 134500000) & (pre["time"] <= 135000000)])
display(tdf[(tdf["StockID"] == 1) & (tdf["time"] >= 134500000) & (tdf["time"] <= 135000000)])

In [2]:
# logSZ1["time"] = logSZ1["time"].apply(lambda x: int((x.replace(':', "")).replace(".", "")))
logSZ["time"] = logSZ["time"].apply(lambda x: int((x.replace(':', "")).replace(".", "")))
logSZ1["time"] = logSZ1["time"].apply(lambda x: int((x.replace(':', "")).ljust(9, "0")))
# logSZ2["time"] = logSZ2["time"].apply(lambda x: int((x.replace(':', "")).replace(".", "")))

In [3]:
logSZ[(logSZ["StockID"] == 1) & (logSZ["time"] >= 134500000) & (logSZ["time"] <= 135000000)]

,clockAtArrival,sequenceNo,source,StockID,exchange,time,cum_volume,cum_amount,close,bid1p,...,ask2p,ask3p,ask4p,ask5p,ask1q,ask2q,ask3q,ask4q,ask5q,openPrice
11492295,1585028704342257,92761823,4,1,SZ,134500000,70915104,8.815382e+08,12.28,12.28,...,12.30,12.31,12.32,12.33,32900,92800,33600,64000,33800,12.4
11492347,1585028704360597,92762268,3,1,SZ,134500000,70915104,8.815382e+08,12.28,12.28,...,12.30,12.31,12.32,12.33,32900,92800,33600,64000,33800,12.4
11495549,1585028707364595,92783636,4,1,SZ,134503000,70918404,8.815787e+08,12.28,12.28,...,12.30,12.31,12.32,12.33,32100,91800,33600,64000,33800,12.4
11495605,1585028707391778,92783801,3,1,SZ,134503000,70918404,8.815787e+08,12.28,12.28,...,12.30,12.31,12.32,12.33,32100,91800,33600,64000,33800,12.4
11498914,1585028710343427,92805784,4,1,SZ,134506000,70928104,8.816979e+08,12.28,12.28,...,12.30,12.31,12.32,12.33,23600,91800,33600,63800,33800,12.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11827152,1585028998360870,95086148,3,1,SZ,134954000,72529360,9.014392e+08,12.35,12.34,...,12.36,12.37,12.38,12.39,2900,20600,29579,61786,48600,12.4
11830340,1585029001343244,95108002,4,1,SZ,134957000,72530160,9.014490e+08,12.35,12.34,...,12.36,12.37,12.38,12.39,2200,15200,29579,61786,48600,12.4
11830367,1585029001348000,95108057,3,1,SZ,134957000,72530160,9.014490e+08,12.35,12.34,...,12.36,12.37,12.38,12.39,2200,15200,29579,61786,48600,12.4
11833661,1585029004342946,95135238,4,1,SZ,135000000,72539160,9.015603e+08,12.36,12.35,...,12.37,12.38,12.39,12.40,8800,29579,61786,48600,100300,12.4
11833712,1585029004358352,95135811,3,1,SZ,135000000,72539160,9.015603e+08,12.36,12.35,...,12.37,12.38,12.39,12.40,8800,29579,61786,48600,100300,12.4

In [4]:
logSZ1[(logSZ1["StockID"] == 1) & (logSZ1["time"] >= 134500000) & (logSZ1["time"] <= 135000000)]

,clockAtArrival,sequenceNo,source,StockID,exchange,time,cum_volume,cum_amount,close,bid1p,...,ask2p,ask3p,ask4p,ask5p,ask1q,ask2q,ask3q,ask4q,ask5q,openPrice
17465513,1585028661501409,140228679,12,1,SZ,134500000,70915104,881538150.0,12.28,12.28,...,12.30,12.31,12.32,12.33,32900,92800,33600,64000,33800,12.4
17465578,1585028661515034,140228830,11,1,SZ,134500000,70915104,881538150.0,12.28,12.28,...,12.30,12.31,12.32,12.33,32900,92800,33600,64000,33800,12.4
17479659,1585028664539972,140271982,12,1,SZ,134503000,70918404,881578682.0,12.28,12.28,...,12.30,12.31,12.32,12.33,32100,91800,33600,64000,33800,12.4
17479687,1585028664550014,140272153,11,1,SZ,134503000,70918404,881578682.0,12.28,12.28,...,12.30,12.31,12.32,12.33,32100,91800,33600,64000,33800,12.4
17483785,1585028667504363,140305751,12,1,SZ,134506000,70928104,881697893.0,12.28,12.28,...,12.30,12.31,12.32,12.33,23600,91800,33600,63800,33800,12.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17928467,1585028955515649,143723173,11,1,SZ,134954000,72529360,901439169.0,12.35,12.34,...,12.36,12.37,12.38,12.39,2900,20600,29579,61786,48600,12.4
17932424,1585028958500033,143755758,12,1,SZ,134957000,72530160,901449049.0,12.35,12.34,...,12.36,12.37,12.38,12.39,2200,15200,29579,61786,48600,12.4
17932471,1585028958516107,143755928,11,1,SZ,134957000,72530160,901449049.0,12.35,12.34,...,12.36,12.37,12.38,12.39,2200,15200,29579,61786,48600,12.4
17936497,1585028961496859,143795433,12,1,SZ,135000000,72539160,901560266.0,12.36,12.35,...,12.37,12.38,12.39,12.40,8800,29579,61786,48600,100300,12.4
17936532,1585028961508715,143795551,11,1,SZ,135000000,72539160,901560266.0,12.36,12.35,...,12.37,12.38,12.39,12.40,8800,29579,61786,48600,100300,12.4

In [5]:
# check if they start from same time first!!!!!!!!!!!!
# if not, then cut the time of new database to make it match
print(max(logSZ[logSZ["source"] == 4].groupby("StockID")["time"].first()))
print(max(logSZ1[logSZ1["source"] == 24].groupby("StockID")["time"].first()))

83648000

ValueError: max() arg is an empty sequence

In [8]:
# 2. lv1 data compare
# 2.1 drop duplicates
data1 = logSZ[(logSZ["cum_volume"] > 0) & (logSZ["time"] < 145700000) & (logSZ["source"] == 3)]
data2 = logSZ1[(logSZ1["cum_volume"] > 0) & (logSZ1["time"] < 145700000) & (logSZ1["source"] == 11)]
# data1 = logSZ[(logSZ["time"] >= 103000000) & (logSZ["time"] < 145700000) & (logSZ["source"] == 3)]
# data2 = logSZ1[(logSZ1["time"] >= 103000000) & (logSZ1["time"] < 145700000) & (logSZ1["source"] == 20)]
columns = ["StockID", "cum_volume", "close", "bid1p", "bid2p", "bid3p", "bid4p", "bid5p", "bid1q", "bid2q",
           "bid3q", "bid4q", "bid5q", "ask1p", "ask2p", "ask3p", "ask4p", "ask5p", "ask1q", "ask2q", "ask3q",
           "ask4q", "ask5q", "openPrice"]
data1_1 = data1.drop_duplicates(subset=columns, keep="first").reset_index()
data2_1 = data2.drop_duplicates(subset=columns, keep="first").reset_index()
n1 = len(data1_1["StockID"].unique())
n2 = len(data2_1["StockID"].unique())
print(n1)
print(n2)

2192
3234

In [9]:
# 2.2 merge and compare
columns = ["StockID", "cum_volume", "close", "bid1p", "bid2p", "bid3p", "bid4p", "bid5p", "bid1q", "bid2q",
           "bid3q", "bid4q", "bid5q", "ask1p", "ask2p", "ask3p", "ask4p", "ask5p", "ask1q", "ask2q", "ask3q",
           "ask4q", "ask5q", "openPrice"]
data2_1 = data2_1[data2_1["StockID"].isin(data1_1["StockID"].unique())]
test = pd.merge(data1_1, data2_1, left_on=columns, right_on=columns, how="outer")
n1 = test["sequenceNo_x"].count()
n2 = test["sequenceNo_y"].count()
len1 = len(test)
print(n1)
print(n2)
print(len1)
if len1 == n2:
    print((n2-n1)/n1)

7567454
7567454
7567454
0.0

In [22]:
test[test["sequenceNo_y"].isnull()]

,StockID,clockAtArrival_x,sequenceNo_x,source_x,exchange_x,time_x,cum_volume,cum_amount_x,close,bid1p,...,ask3q,ask4q,ask5q,openPrice,clockAtArrival_y,sequenceNo_y,source_y,exchange_y,time_y,cum_amount_y
440329,585,1583807401267171,62376299,3,SZ,103000000,3860001,6574107.69,1.70,1.69,...,72700,64000,62200,1.70,NaN,NaN,NaN,NaN,NaN,NaN
1176232,972,1583807458401858,63074163,3,SZ,103057000,1666900,5417908.00,3.24,3.23,...,166600,54000,99700,3.25,NaN,NaN,NaN,NaN,NaN,NaN
1834662,2207,1583807410519970,62502718,3,SZ,103009000,784901,4305435.47,5.47,5.47,...,32000,3000,4500,5.52,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
logSZ1[(logSZ1["StockID"] == 2207) & (logSZ1["cum_volume"] == 784901) & (logSZ1["source"]==20)]

,clockAtArrival,sequenceNo,source,StockID,exchange,time,cum_volume,cum_amount,close,bid1p,...,ask2p,ask3p,ask4p,ask5p,ask1q,ask2q,ask3q,ask4q,ask5q,openPrice
6303,1583782708695366,60586,20,2207,SZ,102854000,784901,4305435.0,5.47,5.47,...,5.49,5.5,5.51,5.52,35100,29600,32000,3000,4500,5.52
17222,1583782716681518,141267,20,2207,SZ,102909000,784901,4305435.0,5.47,5.47,...,5.49,5.5,5.51,5.52,35100,29600,32000,3000,4500,5.52
102409,1583782791683028,1043516,20,2207,SZ,103024000,784901,4305435.0,5.47,5.47,...,5.49,5.5,5.51,5.52,28200,29600,32000,3000,4500,5.52

In [6]:
# speed check
# test1 = test[~np.isnan(test["sequenceNo_x"])]
diff = test["clockAtArrival_y"] - test["clockAtArrival_x"]
print(np.median(diff[diff < 0]))
print(np.median(diff[diff > 0]))
print(sum(diff > 0)/len(diff))
print(sum(diff>0))

C:\Users\win\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:3118: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
C:\Users\win\Anaconda3\lib\site-packages\numpy\core\_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)

nan
15142704.0
1.0
7631903

In [57]:
# 2.3 find difference
test[np.isnan(test["sequenceNo_x"])]

,StockID,clockAtArrival_x,sequenceNo_x,source_x,exchange_x,time_x,cum_volume,cum_amount_x,close,bid1p,...,ask3q,ask4q,ask5q,openPrice,clockAtArrival_y,sequenceNo_y,source_y,exchange_y,time_y,cum_amount_y
5743140,10,NaN,NaN,NaN,NaN,NaN,1268000,NaN,3.59,3.58,...,55500,12500,16600,3.57,1579054001155409,42856868,24,SZ,100545000,4.590772e+06
5743141,89,NaN,NaN,NaN,NaN,NaN,2705100,NaN,9.82,9.82,...,93600,102700,221400,9.87,1579053992179756,42706323,24,SZ,100536000,2.664220e+07
5743142,151,NaN,NaN,NaN,NaN,NaN,801100,NaN,10.40,10.39,...,6200,22500,20400,10.41,1579053992179759,42706325,24,SZ,100536000,8.327746e+06
5743143,409,NaN,NaN,NaN,NaN,NaN,835432,NaN,5.36,5.35,...,26074,134626,138120,5.29,1579053992179865,42706337,24,SZ,100536000,4.436237e+06
5743144,525,NaN,NaN,NaN,NaN,NaN,4084640,NaN,9.86,9.87,...,1100,800,2800,10.03,1579053992202072,42706898,24,SZ,100536000,4.076168e+07
5743145,551,NaN,NaN,NaN,NaN,NaN,908299,NaN,6.94,6.94,...,12600,25600,7000,6.99,1579053992213107,42707060,24,SZ,100536000,6.321414e+06
5743146,582,NaN,NaN,NaN,NaN,NaN,465100,NaN,8.97,8.97,...,41051,38600,2500,9.03,1579053992225158,42707262,24,SZ,100536000,4.186660e+06
5743147,597,NaN,NaN,NaN,NaN,NaN,2182544,NaN,7.56,7.56,...,5195,11363,12200,7.64,1579053992225352,42707280,24,SZ,100536000,1.670078e+07
5743148,720,NaN,NaN,NaN,NaN,NaN,832000,NaN,5.85,5.84,...,21099,21710,75900,5.92,1579053995269046,42758550,24,SZ,100539000,4.885146e+06
5743149,792,NaN,NaN,NaN,NaN,NaN,19484984,NaN,8.90,8.90,...,71100,52500,35400,8.95,1579053992296862,42708832,24,SZ,100536000,1.765516e+08
5743150,815,NaN,NaN,NaN,NaN,NaN,3656600,NaN,7.47,7.46,...,11200,41100,70300,7.40,1579053992296976,42708849,24,SZ,100536000,2.726050e+07
5743151,821,NaN,NaN,NaN,NaN,NaN,3947801,NaN,7.06,7.06,...,25000,18699,20400,7.17,1579053992297026,42708857,24,SZ,100536000,2.809333e+07
5743152,1872,NaN,NaN,NaN,NaN,NaN,454300,NaN,17.05,17.05,...,10800,1402,500,17.29,1579053992355452,42710264,24,SZ,100536000,7.771649e+06
5743153,2010,NaN,NaN,NaN,NaN,NaN,5539100,NaN,7.23,7.22,...,48000,85200,40600,7.32,1579053992355516,42710276,24,SZ,100536000,4.020110e+07
5743154,2032,NaN,NaN,NaN,NaN,NaN,229793,NaN,74.17,74.00,...,1300,700,100,73.98,1579053992366587,42710522,24,SZ,100536000,1.703608e+07
5743155,2037,NaN,NaN,NaN,NaN,NaN,436500,NaN,7.12,7.12,...,2200,23500,8200,7.17,1579053992378624,42710740,24,SZ,100536000,3.121079e+06
5743156,2055,NaN,NaN,NaN,NaN,NaN,9131782,NaN,12.78,12.78,...,4000,12500,33800,13.20,1579053992366638,42710530,24,SZ,100536000,1.184838e+08
5743157,2082,NaN,NaN,NaN,NaN,NaN,975000,NaN,10.05,10.01,...,5600,6500,7000,10.17,1579053992378682,42710749,24,SZ,100536000,9.791589e+06
5743158,2091,NaN,NaN,NaN,NaN,NaN,7339227,NaN,7.68,7.67,...,81730,12400,2700,7.77,1579053992401017,42711300,24,SZ,100536000,5.675114e+07
5743159,2148,NaN,NaN,NaN,NaN,NaN,1565017,NaN,5.39,5.39,...,21400,26100,137000,5.49,1579053992425189,42711780,24,SZ,100536000,8.502273e+06
5743160,2159,NaN,NaN,NaN,NaN,NaN,226500,NaN,12.53,12.53,...,1900,1500,2000,12.65,1579054004435515,42911108,24,SZ,100548000,2.851776e+06
5743161,2179,NaN,NaN,NaN,NaN,NaN,922270,NaN,39.04,39.02,...,2500,2100,500,39.26,1579053992425135,42711774,24,SZ,100536000,3.605971e+07
5743162,2193,NaN,NaN,NaN,NaN,NaN,639900,NaN,8.01,8.00,...,57300,7200,2700,8.11,1579053992448397,42712329,24,SZ,100536000,5.150794e+06
5743163,2290,NaN,NaN,NaN,NaN,NaN,116000,NaN,4.93,4.92,...,100,8140,10300,4.91,1579054004481817,42912085,24,SZ,100548000,5.732560e+05
5743164,2349,NaN,NaN,NaN,NaN,NaN,636900,NaN,4.57,4.57,...,24500,22300,8400,4.62,1579053992508514,42713859,24,SZ,100536000,2.928746e+06
5743165,2364,NaN,NaN,NaN,NaN,NaN,6283400,NaN,12.91,12.90,...,13100,51200,7100,13.36,1579053992496809,42713599,24,SZ,100536000,8.224268e+07
5743166,2365,NaN,NaN,NaN,NaN,NaN,7134700,NaN,10.40,10.39,...,87200,200,5700,9.94,1579053992496810,42713600,24,SZ,100536000,7.364391e+07
5743167,2427,NaN,NaN,NaN,NaN,NaN,315200,NaN,8.68,8.65,...,8500,11900,19000,8.70,1579053992531302,42714355,24,SZ,100536000,2.742189e+06
5743168,2457,NaN,NaN,NaN,NaN,NaN,1309501,NaN,8.31,8.31,...,13600,17100,26500,8.37,1579053995545909,42765694,24,SZ,100539000,1.093177e+07
5743169,2559,NaN,NaN,NaN,NaN,NaN,1015950,NaN,5.74,5.74,...,50500,19600,20650,5.80,1579053992601979,42716137,24,SZ,100536000,5.857164e+06
5743170,2674,NaN,NaN,NaN,NaN,NaN,261400,NaN,11.01,11.01,...,11300,9200,10000,11.01,1579053992649525,42717293,24,SZ,100536000,2.885798e+06
5743171,2691,NaN,NaN,NaN,NaN,NaN,591600,NaN,6.20,6.20,...,24200,12800,16970,6.27,1579053992638444,42717011,24,SZ,100536000,3.694307e+06
5743172,2742,NaN,NaN,NaN,NaN,NaN,1176200,NaN,6.29,6.29,...,1200,6900,8300,6.40,1579053992672771,42718090,24,SZ,100536000,7.473424e+06
5743173,2782,NaN,NaN,NaN,NaN,NaN,1624293,NaN,11.19,11.19,...,4000,8300,187000,11.40,1579053992683925,42718450,24,SZ,100536000,1.834834e+07
5743174,2783,NaN,NaN,NaN,NaN,NaN,2387964,NaN,12.58,12.57,...,25200,65900,23300,12.80,1579053992693363,42718694,24,SZ,100536000,3.034811e+07
5743175,2806,NaN,NaN,NaN,NaN,NaN,857500,NaN,14.25,14.25,...,1000,3600,4300,14.67,1579053992694934,42718728,24,SZ,100536000,1.235652e+07
5743176,2813,NaN,NaN,NaN,NaN,NaN,403100,NaN,25.25,25.25,...,5800,100,6700,25.53,1579053995688262,42769026,24,SZ,100539000,1.026860e+07
5743177,2858,NaN,NaN,NaN,NaN,NaN,449200,NaN,15.47,15.47,...,3000,700,2100,15.68,1579053992707131,42719135,24,SZ,100536000,6.993000e+06
5743178,2932,NaN,NaN,NaN,NaN,NaN,262400,NaN,37.11,37.16,...,500,1700,500,36.86,1579053992752335,42720313,24,SZ,100536000,9.786442e+06
5743179,300094,NaN,NaN,NaN,NaN,NaN,3894800,NaN,4.44,4.44,...,29400,30900,33700,4.47,1579053992800822,42721399,24,SZ,100536000,1.755410e+07
5743180,300103,NaN,NaN,NaN,NaN,NaN,465800,NaN,9.53,9.53,...,8200,5800,37150,9.67,1579053995791243,42771810,24,SZ,100539000,4.462217e+06
5743181,300110,NaN,NaN,NaN,NaN,NaN,3315000,NaN,4.22,4.22,...,102776,136786,132900,4.27,1579053992800870,42721402,24,SZ,100536000,1.408221e+07
5743182,300121,NaN,NaN,NaN,NaN,NaN,2559690,NaN,7.97,7.97,...,11000,8700,14200,8.05,1579053992812976,42721577,24,SZ,100536000,2.052144e+07
5743183,300153,NaN,NaN,NaN,NaN,NaN,996300,NaN,6.89,6.88,...,10000,15300,18300,6.98,1579053995826487,42772766,24,SZ,100539000,6.902165e+06
5743184,300158,NaN,NaN,NaN,NaN,NaN,2118200,NaN,4.70,4.69,...,67500,198200,353700,4.74,1579054001815439,42870426,24,SZ,100545000,9.985023e+06
5743185,300241,NaN,NaN,NaN,NaN,NaN,4630200,NaN,6.66,6.66,...,24600,75800,26600,6.73,1579053992859239,42722569,24,SZ,100536000,3.097802e+07
5743186,300246,NaN,NaN,NaN,NaN,NaN,491600,NaN,15.79,15.79,...,1200,100,100,15.91,1579053992859291,42722578,24,SZ,100536000,7.819756e+06
5743187,300273,NaN,NaN,NaN,NaN,NaN,3856350,NaN,5.16,5.15,...,26800,192425,16100,5.27,1579053992870435,42722876,24,SZ,100536000,2.009851e+07
5743188,300380,NaN,NaN,NaN,NaN,NaN,636900,NaN,21.16,21.16,...,400,700,3000,21.28,1579053992935419,42724549,24,SZ,100536000,1.359936e+07
5743189,300412,NaN,NaN,NaN,NaN,NaN,452900,NaN,6.75,6.75,...,9300,4800,6000,6.77,1579053992939997,42724681,24,SZ,100536000,3.075104e+06
5743190,300446,NaN,NaN,NaN,NaN,NaN,1954479,NaN,16.96,16.96,...,19700,4000,15400,17.28,1579053995941506,42776017,24,SZ,100539000,3.305056e+07
5743191,300490,NaN,NaN,NaN,NaN,NaN,3634809,NaN,11.50,11.49,...,4200,6000,10100,11.82,1579053992963223,42725233,24,SZ,100536000,4.222532e+07
5743192,300540,NaN,NaN,NaN,NaN,NaN,356600,NaN,14.44,14.39,...,2300,600,5100,14.64,1579054007956874,42968823,24,SZ,100551000,5.179367e+06
5743193,300601,NaN,NaN,NaN,NaN,NaN,1321190,NaN,90.55,90.51,...,300,1200,2900,90.00,1579053992998589,42726161,24,SZ,100536000,1.197087e+08
5743194,300629,NaN,NaN,NaN,NaN,NaN,615950,NaN,21.47,21.46,...,1800,1400,500,21.83,1579053993009666,42726430,24,SZ,100536000,1.324666e+07
5743195,300659,NaN,NaN,NaN,NaN,NaN,302966,NaN,67.91,67.86,...,300,1800,1020,67.43,1579053999047740,42829067,24,SZ,100542000,2.068255e+07
5743196,300742,NaN,NaN,NaN,NaN,NaN,607800,NaN,22.57,22.57,...,9300,5200,300,22.90,1579053993044045,42727351,24,SZ,100536000,1.381653e+07
5743197,300749,NaN,NaN,NaN,NaN,NaN,659340,NaN,13.34,13.33,...,2200,2600,6700,13.48,1579053993044113,42727369,24,SZ,100536000,8.875160e+06
5743198,300769,NaN,NaN,NaN,NaN,NaN,377182,NaN,142.00,141.00,...,100,100,500,144.55,1579053993067073,42727766,24,SZ,100536000,5.405023e+07

In [71]:
logSZ[(logSZ["StockID"] == 10) & (logSZ["time"] >= 100530000)]

,clockAtArrival,sequenceNo,source,StockID,exchange,time,cum_volume,cum_amount,close,bid1p,...,ask2p,ask3p,ask4p,ask5p,ask1q,ask2q,ask3q,ask4q,ask5q,openPrice
541095,1579054001160736,32283142,12,10,SZ,100545000,1268000,4590772.0,3.59,3.58,...,3.60,3.61,3.62,3.63,4900,17500,55500,12500,16600,3.57
545658,1579054004172336,32320779,12,10,SZ,100548000,1272900,4608363.0,3.59,3.59,...,3.61,3.62,3.63,3.64,17500,55500,12500,16600,21800,3.57
545732,1579054004189259,32321014,11,10,SZ,100548000,1272900,4608363.0,3.59,3.59,...,3.61,3.62,3.63,3.64,17500,55500,12500,16600,21800,3.57
577441,1579054019196549,32520385,12,10,SZ,100603000,1272900,4608363.0,3.59,3.59,...,3.61,3.62,3.63,3.64,17500,55500,12500,16600,21800,3.57
577626,1579054019233712,32521027,11,10,SZ,100603000,1272900,4608363.0,3.59,3.59,...,3.61,3.62,3.63,3.64,17500,55500,12500,16600,21800,3.57
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18725259,1579072079620522,126956798,11,10,SZ,150703000,2753801,9999552.0,3.64,3.64,...,3.66,3.67,3.68,3.69,97330,45600,52700,46300,49400,3.57
18740543,1579072139497900,126989290,12,10,SZ,150803000,2753801,9999552.0,3.64,3.64,...,3.66,3.67,3.68,3.69,97330,45600,52700,46300,49400,3.57
18741049,1579072139607714,126989844,11,10,SZ,150803000,2753801,9999552.0,3.64,3.64,...,3.66,3.67,3.68,3.69,97330,45600,52700,46300,49400,3.57
18756444,1579072199518414,127021108,12,10,SZ,150903000,2753801,9999552.0,3.64,3.64,...,3.66,3.67,3.68,3.69,97330,45600,52700,46300,49400,3.57
18756886,1579072199609060,127021576,11,10,SZ,150903000,2753801,9999552.0,3.64,3.64,...,3.66,3.67,3.68,3.69,97330,45600,52700,46300,49400,3.57

In [64]:
data2_1[(data2_1["StockID"] == 10) & (data2_1["time"] >= 100545000)]

,StockID,clockAtArrival,sequenceNo,source,exchange,time,cum_volume,cum_amount,close,bid1p,...,ask2p,ask3p,ask4p,ask5p,ask1q,ask2q,ask3q,ask4q,ask5q,openPrice
23541,10,1579054001155409,42856868,24,SZ,100545000,1268000,4590772.0,3.59,3.58,...,3.60,3.61,3.62,3.63,4900,17500,55500,12500,16600,3.57
23542,10,1579054004157147,42905330,24,SZ,100548000,1272900,4608363.0,3.59,3.59,...,3.61,3.62,3.63,3.64,17500,55500,12500,16600,21800,3.57
23543,10,1579054019194853,43144157,24,SZ,100603000,1272900,4608363.0,3.59,3.59,...,3.61,3.62,3.63,3.64,17500,55500,12500,16600,21800,3.57
23544,10,1579054022146164,43192470,24,SZ,100606000,1272900,4608363.0,3.59,3.59,...,3.61,3.62,3.63,3.64,17500,55500,12500,16600,21800,3.57
23545,10,1579054025157873,43238694,24,SZ,100609000,1272900,4608363.0,3.59,3.59,...,3.61,3.62,3.63,3.64,17500,55500,12500,18600,21800,3.57
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24354,10,1579071410328788,138457959,24,SZ,145554000,2711401,9845132.3,3.64,3.64,...,3.66,3.67,3.68,3.69,101630,45600,53300,46300,49400,3.57
24355,10,1579071419367412,138584541,24,SZ,145603000,2711401,9845132.3,3.64,3.64,...,3.66,3.67,3.68,3.69,101630,45600,52700,46300,49400,3.57
24356,10,1579071431340825,138758281,24,SZ,145615000,2719401,9874332.3,3.65,3.64,...,3.66,3.67,3.68,3.69,93630,45600,52700,46300,49400,3.57
24357,10,1579071443340163,138931682,24,SZ,145627000,2719401,9874332.3,3.65,3.64,...,3.66,3.67,3.68,3.69,96730,45600,52700,46300,49400,3.57
24358,10,1579071458339892,139139428,24,SZ,145642000,2719801,9875792.3,3.65,3.64,...,3.66,3.67,3.68,3.69,96330,45600,52700,46300,49400,3.57

In [10]:
# 3. lv2 data compare
# 3.1 drop duplicates
data1 = logSZ[(logSZ["cum_volume"] > 0) & (logSZ["time"] < 145700000) & (logSZ["source"] == 4)]
data2 = logSZ1[(logSZ1["cum_volume"] > 0) & (logSZ1["time"] < 145700000) & (logSZ1["source"] == 12)]
# data1 = logSZ[(logSZ["time"] >= 130000000) & (logSZ["time"] < 145700000) & (logSZ["source"] == 4)]
# data2 = logSZ1[(logSZ1["time"] >= 130000000) & (logSZ1["time"] < 145700000) & (logSZ1["source"] == 24)]

columns = ["StockID", "cum_volume", "close", "bid1p", "bid2p", "bid3p", "bid4p", "bid5p", "bid1q", "bid2q",
           "bid3q", "bid4q", "bid5q", "ask1p", "ask2p", "ask3p", "ask4p", "ask5p", "ask1q", "ask2q", "ask3q",
           "ask4q", "ask5q", "openPrice"]
data1_1 = data1.drop_duplicates(subset=columns, keep="first").reset_index()
data2_1 = data2.drop_duplicates(subset=columns, keep="first").reset_index()
n1 = len(data1_1["StockID"].unique())
n2 = len(data2_1["StockID"].unique())
print(n1)
print(n2)

2192
2883

In [11]:
# 3.2 merge and compare
columns = ["StockID", "cum_volume", "close", "bid1p", "bid2p", "bid3p", "bid4p", "bid5p", "bid1q", "bid2q",
           "bid3q", "bid4q", "bid5q", "ask1p", "ask2p", "ask3p", "ask4p", "ask5p", "ask1q", "ask2q", "ask3q",
           "ask4q", "ask5q", "openPrice"]
data2_1 = data2_1[data2_1["StockID"].isin(data1_1["StockID"].unique())]
test = pd.merge(data1_1, data2_1, left_on=columns, right_on=columns, how="outer")
n1 = test["sequenceNo_x"].count()
n2 = test["sequenceNo_y"].count()
len1 = len(test)
print(n1)
print(n2)
print(len1)
if len1 == n2:
    print((n2-n1)/n1)

7567454
7567454
7567454
0.0

In [26]:
test[np.isnan(test["sequenceNo_y"])]

,StockID,clockAtArrival_x,sequenceNo_x,source_x,exchange_x,time_x,cum_volume,cum_amount_x,close,bid1p,...,ask3q,ask4q,ask5q,openPrice,clockAtArrival_y,sequenceNo_y,source_y,exchange_y,time_y,cum_amount_y
1834698,2207,1583807410470069,62501221,4,SZ,103009000,784901,4305435.47,5.47,5.47,...,32000,3000,4500,5.52,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
logSZ1[(logSZ1["StockID"] == 2207) & (logSZ1["cum_volume"] == 784901) & (logSZ1["source"]==21)]

,clockAtArrival,sequenceNo,source,StockID,exchange,time,cum_volume,cum_amount,close,bid1p,...,ask2p,ask3p,ask4p,ask5p,ask1q,ask2q,ask3q,ask4q,ask5q,openPrice
660,1583782707933038,2758,21,2207,SZ,102854000,784901,4305435.0,5.47,5.47,...,5.49,5.5,5.51,5.52,35100,29600,32000,3000,4500,5.52
16862,1583782716616763,140305,21,2207,SZ,102909000,784901,4305435.0,5.47,5.47,...,5.49,5.5,5.51,5.52,35100,29600,32000,3000,4500,5.52
102105,1583782791628449,1042815,21,2207,SZ,103024000,784901,4305435.0,5.47,5.47,...,5.49,5.5,5.51,5.52,28200,29600,32000,3000,4500,5.52

In [32]:
logSZ[(logSZ["StockID"] == 300194) & (logSZ["cum_volume"] == 63084040) & (logSZ["source"] == 4)].loc[:, ["bid1p", "bid2p", "bid3p", "bid4p", "bid5p", "bid1q", "bid2q",
           "bid3q", "bid4q", "bid5q", "ask1p", "ask2p", "ask3p", "ask4p", "ask5p", "ask1q", "ask2q", "ask3q",
           "ask4q", "ask5q"]]

,bid1p,bid2p,bid3p,bid4p,bid5p,bid1q,bid2q,bid3q,bid4q,bid5q,ask1p,ask2p,ask3p,ask4p,ask5p,ask1q,ask2q,ask3q,ask4q,ask5q
16979904,6.1,6.09,6.08,6.07,6.06,3800,224954,137275,193500,220000,6.11,6.12,6.13,6.14,6.15,174800,95400,147100,113900,253600

In [35]:
logSZ1[(logSZ1["StockID"] == 300194) & (logSZ1["cum_volume"] == 63084040) & (logSZ1["source"] == 24)]

,clockAtArrival,sequenceNo,source,StockID,exchange,time,cum_volume,cum_amount,close,bid1p,...,ask2p,ask3p,ask4p,ask5p,ask1q,ask2q,ask3q,ask4q,ask5q,openPrice
8459676,1583218061175293,109813214,24,300194,SZ,144754000,63084040,384088435.2,6.1,6.1,...,6.12,6.13,6.14,6.15,174800,95400,147100,113900,253600,5.85
8461414,1583218064153330,109830464,24,300194,SZ,144757000,63084040,384088435.2,6.1,6.1,...,6.12,6.13,6.14,6.15,176800,115400,147100,113900,253600,5.85

In [3]:
# compare speed with another source
print(logSZ2["source"].unique())
print(logSZ2["time"].unique())
print(logSZ3["source"].unique())
print(logSZ3["time"].unique())
logSZ2["time"] = logSZ2["time"].apply(lambda x: int((x.replace(':', "")).ljust(9, "0")))
logSZ3["time"] = logSZ3["time"].apply(lambda x: int((x.replace(':', "")).ljust(9, "0")))

[11 12]
['08:32:24' '08:33:24' '08:34:24' ... '15:11:30' '15:11:33' '15:11:36']
[11 12]
['08:34:33' '08:35:33' '08:36:33' ... '15:09:24' '15:09:27' '15:09:30']

In [4]:
data1 = logSZ3[(logSZ3["cum_volume"] > 0) & (logSZ3["time"] < 145700000) & (logSZ3["source"] == 12)]
data2 = logSZ1[(logSZ1["cum_volume"] > 0) & (logSZ1["time"] < 145700000) & (logSZ1["source"] == 24)]
# data1 = logSZ[(logSZ["time"] >= 100536000) & (logSZ["time"] < 145700000) & (logSZ["source"] == 4)]
# data2 = logSZ1[(logSZ1["time"] >= 100536000) & (logSZ1["time"] < 145700000) & (logSZ1["source"] == 24)]
columns = ["cum_volume", "close", "bid1p", "bid2p", "bid3p", "bid4p", "bid5p", "bid1q", "bid2q",
           "bid3q", "bid4q", "bid5q", "ask1p", "ask2p", "ask3p", "ask4p", "ask5p", "ask1q", "ask2q", "ask3q",
           "ask4q", "ask5q", "openPrice"]
data1_1 = data1.groupby("StockID")[data1.columns[~data1.columns.isin(["StockID"])].values].apply(
    lambda x: x[~x.duplicated(columns, keep="first")]).reset_index()
data2_1 = data2.groupby("StockID")[data2.columns[~data2.columns.isin(["StockID"])].values].apply(
    lambda x: x[~x.duplicated(columns, keep="first")]).reset_index()
data1_1 = data1_1.drop("level_1", axis=1)
data2_1 = data2_1.drop("level_1", axis=1)
n1 = len(data1_1["StockID"].unique())
n2 = len(data2_1["StockID"].unique())
print(n1)
print(n2)

2837
2863

In [5]:
columns = ["StockID", "cum_volume", "close", "bid1p", "bid2p", "bid3p", "bid4p", "bid5p", "bid1q", "bid2q",
           "bid3q", "bid4q", "bid5q", "ask1p", "ask2p", "ask3p", "ask4p", "ask5p", "ask1q", "ask2q", "ask3q",
           "ask4q", "ask5q", "openPrice"]
# data1_1 = data1_1[data1_1["StockID"].isin(data2_1["StockID"].unique())]
data2_1 = data2_1[data2_1["StockID"].isin(data1_1["StockID"].unique())]
test = pd.merge(data1_1, data2_1, left_on=columns, right_on=columns, how="outer")
n1 = test["sequenceNo_x"].count()
n2 = test["sequenceNo_y"].count()
len1 = len(test)
print(n1)
print(n2)
print(len1)
if len1 == n2:
    print((n2-n1)/n1)

6483939
7565659
14049598

In [7]:
test[np.isnan(test["sequenceNo_y"])]

,StockID,clockAtArrival_x,sequenceNo_x,source_x,exchange_x,time_x,cum_volume,cum_amount_x,close,bid1p,...,ask3q,ask4q,ask5q,openPrice,clockAtArrival_y,sequenceNo_y,source_y,exchange_y,time_y,cum_amount_y
0,1,1.579054e+15,31434386.0,12.0,SZ,100439000.0,21065256,352199327.0,16.64,16.63,...,147000,9500,56900,16.79,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1.579054e+15,31472090.0,12.0,SZ,100442000.0,21155956,353706958.0,16.62,16.61,...,13100,33191,147000,16.79,NaN,NaN,NaN,NaN,NaN,NaN
2,1,1.579054e+15,31507072.0,12.0,SZ,100445000.0,21204356,354511452.0,16.63,16.62,...,33191,147000,11500,16.79,NaN,NaN,NaN,NaN,NaN,NaN
3,1,1.579054e+15,31543611.0,12.0,SZ,100448000.0,21207956,354571308.0,16.63,16.62,...,42991,147000,11500,16.79,NaN,NaN,NaN,NaN,NaN,NaN
4,1,1.579054e+15,31579255.0,12.0,SZ,100451000.0,21209156,354591264.0,16.63,16.62,...,42991,147000,11500,16.79,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6483934,300813,1.579071e+15,125096907.0,12.0,SZ,145633000.0,11600,337096.0,29.06,29.06,...,0,0,0,29.06,NaN,NaN,NaN,NaN,NaN,NaN
6483935,300813,1.579071e+15,125206411.0,12.0,SZ,145642000.0,11600,337096.0,29.06,29.06,...,0,0,0,29.06,NaN,NaN,NaN,NaN,NaN,NaN
6483936,300813,1.579071e+15,125242946.0,12.0,SZ,145645000.0,11600,337096.0,29.06,29.06,...,0,0,0,29.06,NaN,NaN,NaN,NaN,NaN,NaN
6483937,300813,1.579071e+15,125344949.0,12.0,SZ,145654000.0,11600,337096.0,29.06,29.06,...,0,0,0,29.06,NaN,NaN,NaN,NaN,NaN,NaN
6483938,300813,1.579071e+15,125377274.0,12.0,SZ,145657000.0,11600,337096.0,29.06,29.06,...,0,0,0,29.06,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
data2_1[(data2_1["StockID"] == 1) & (data2_1["cum_amount"]>= 3.521993e+08)]

,StockID,clockAtArrival,sequenceNo,source,exchange,time,cum_volume,cum_amount,close,bid1p,...,ask2p,ask3p,ask4p,ask5p,ask1q,ask2q,ask3q,ask4q,ask5q,openPrice
982,1,1579486803858813,42555354,12,SZ,101903000,21308697,3.522218e+08,16.46,16.46,...,16.48,16.49,16.50,16.51,5200,155000,44700,22100,10600,16.43
983,1,1579486806840473,42581378,12,SZ,101906000,21315797,3.523388e+08,16.47,16.46,...,16.48,16.49,16.50,16.51,113100,65200,44700,22100,10600,16.43
984,1,1579486809829163,42605717,12,SZ,101909000,21324103,3.524755e+08,16.47,16.46,...,16.48,16.49,16.50,16.51,106200,65000,44700,22100,11300,16.43
985,1,1579486812839714,42631207,12,SZ,101912000,21324603,3.524838e+08,16.46,16.46,...,16.48,16.49,16.50,16.51,117200,65000,44700,22100,11300,16.43
986,1,1579486815828798,42655379,12,SZ,101915000,21327603,3.525332e+08,16.47,16.46,...,16.48,16.49,16.50,16.51,219000,65000,44700,22100,11300,16.43
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4737,1,1579503466018338,129247648,12,SZ,145645000,73697040,1.211488e+09,16.46,16.45,...,16.47,16.48,16.49,16.50,134300,136900,121887,131600,224498,16.43
4738,1,1579503469040767,129281655,12,SZ,145648000,73709940,1.211700e+09,16.45,16.45,...,16.47,16.48,16.49,16.50,135100,136900,121887,131600,225498,16.43
4739,1,1579503472053961,129315173,12,SZ,145651000,73744982,1.212277e+09,16.45,16.45,...,16.47,16.48,16.49,16.50,107400,137900,121887,132100,225498,16.43
4740,1,1579503475030750,129349276,12,SZ,145654000,73754582,1.212435e+09,16.45,16.45,...,16.47,16.48,16.49,16.50,237200,137900,121887,133100,227198,16.43
4741,1,1579503477996819,129381367,12,SZ,145657000,73779382,1.212843e+09,16.45,16.45,...,16.47,16.48,16.49,16.50,238600,137900,121387,133100,226898,16.43

In [12]:
data1_1[(data1_1["StockID"] == 1) & (data1_1["time"]>= 100439000)]

,StockID,clockAtArrival,sequenceNo,source,exchange,time,cum_volume,cum_amount,close,bid1p,...,ask2p,ask3p,ask4p,ask5p,ask1q,ask2q,ask3q,ask4q,ask5q,openPrice
0,1,1579053935149100,31434386,12,SZ,100439000,21065256,3.521993e+08,16.64,16.63,...,16.65,16.66,16.67,16.68,800,24820,147000,9500,56900,16.79
1,1,1579053938159105,31472090,12,SZ,100442000,21155956,3.537070e+08,16.62,16.61,...,16.63,16.64,16.65,16.66,28800,500,13100,33191,147000,16.79
2,1,1579053941159413,31507072,12,SZ,100445000,21204356,3.545115e+08,16.63,16.62,...,16.64,16.65,16.66,16.67,9000,60700,33191,147000,11500,16.79
3,1,1579053944157977,31543611,12,SZ,100448000,21207956,3.545713e+08,16.63,16.62,...,16.64,16.65,16.66,16.67,6600,60700,42991,147000,11500,16.79
4,1,1579053947158338,31579255,12,SZ,100451000,21209156,3.545913e+08,16.63,16.62,...,16.64,16.65,16.66,16.67,28200,60100,42991,147000,11500,16.79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4042,1,1579071461342808,125228326,12,SZ,145645000,84524243,1.401433e+09,16.53,16.52,...,16.54,16.55,16.56,16.57,115100,137200,231200,52000,118100,16.79
4043,1,1579071464334050,125264487,12,SZ,145648000,84730443,1.404842e+09,16.54,16.52,...,16.54,16.55,16.56,16.57,2000,78600,231200,52000,118100,16.79
4044,1,1579071467379470,125298927,12,SZ,145651000,84783343,1.405716e+09,16.54,16.52,...,16.55,16.56,16.57,16.58,65200,234900,52000,118100,41600,16.79
4045,1,1579071470372141,125332779,12,SZ,145654000,84783943,1.405726e+09,16.53,16.53,...,16.55,16.56,16.57,16.58,65200,234900,52000,118100,72200,16.79
4046,1,1579071473323044,125365863,12,SZ,145657000,84809243,1.406144e+09,16.54,16.52,...,16.54,16.55,16.56,16.57,500,45700,234900,52000,118100,16.79

In [34]:
# 3.3 speed check
diff = test["clockAtArrival_y"] - test["clockAtArrival_x"]
print(np.median(diff[diff < 0]))
print(np.median(diff[diff > 0]))
print(sum(diff > 0)/len(diff))
print(sum(diff < 0)/len(diff))

-31909.0
nan

C:\Users\win\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:3118: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
C:\Users\win\Anaconda3\lib\site-packages\numpy\core\_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)

0.0
1.0

In [60]:
test[test["clockAtArrival_y"] - test["clockAtArrival_x"] < 0]

,StockID,clockAtArrival_x,sequenceNo_x,source_x,exchange_x,time_x,cum_volume,cum_amount_x,close,bid1p,...,ask3q,ask4q,ask5q,openPrice,clockAtArrival_y,sequenceNo_y,source_y,exchange_y,time_y,cum_amount_y
3125136,300506,1584428185306773,82170513,24,SZ,145624000,20330128,1.192945e+08,5.94,5.93,...,13900,12500,21500,6.11,1584428185305657,82170437,21,SZ,145624000,1.192945e+08
3139988,300516,1584428185306776,82170514,24,SZ,145624000,2845364,8.714658e+07,30.11,30.11,...,400,200,100,31.50,1584428185305666,82170438,21,SZ,145624000,8.714658e+07
3150162,300525,1584428185306777,82170515,24,SZ,145624000,7153721,2.145186e+08,30.83,30.81,...,7900,3100,5400,29.11,1584428185305671,82170439,21,SZ,145624000,2.145186e+08
3163038,300534,1584428185306778,82170516,24,SZ,145624000,10152860,6.133140e+07,6.06,6.06,...,12300,25500,14500,6.25,1584428185305674,82170440,21,SZ,145624000,6.133140e+07
3168930,300538,1584428185306779,82170517,24,SZ,145624000,5727155,1.054548e+08,18.91,18.91,...,700,4755,14100,18.04,1584428185305680,82170441,21,SZ,145624000,1.054548e+08
3171006,300540,1584428185306780,82170518,24,SZ,145624000,1428054,1.801098e+07,12.71,12.71,...,8551,1100,4100,12.70,1584428185305702,82170444,21,SZ,145624000,1.801098e+07
3174216,300542,1584428185306819,82170521,24,SZ,145624000,5570788,8.916935e+07,15.82,15.82,...,400,7300,21000,16.50,1584428185305628,82170431,21,SZ,145624000,8.916935e+07
3180539,300547,1584428185306861,82170529,24,SZ,145624000,2383440,1.930654e+07,8.15,8.14,...,23700,3500,8620,8.34,1584428185305716,82170447,21,SZ,145624000,1.930654e+07
3182618,300548,1584428185306862,82170530,24,SZ,145624000,2147500,1.927181e+08,91.19,91.19,...,200,200,100,91.69,1584428185305720,82170448,21,SZ,145624000,1.927181e+08
3185677,300551,1584428185306863,82170531,24,SZ,145624000,3485250,8.390658e+07,23.90,23.90,...,5600,5400,32600,25.01,1584428185305730,82170449,21,SZ,145624000,8.390658e+07
3189668,300554,1584428185306820,82170522,24,SZ,145624000,2102160,2.953213e+07,14.01,14.01,...,5000,5600,10800,14.37,1584428185305632,82170432,21,SZ,145624000,2.953212e+07
3192934,300556,1584428185306780,82170519,24,SZ,145624000,3184500,5.009975e+07,15.70,15.70,...,1800,1200,2000,16.30,1584428185305706,82170445,21,SZ,145624000,5.009975e+07
3193839,300557,1584428185306821,82170523,24,SZ,145624000,1054900,2.833982e+07,27.05,27.00,...,900,300,200,26.63,1584428185305637,82170433,21,SZ,145624000,2.833982e+07
3196046,300558,1584428185306863,82170532,24,SZ,145624000,5861797,3.856100e+08,66.13,66.13,...,100,300,100,65.74,1584428185305736,82170450,21,SZ,145624000,3.856100e+08
3198023,300559,1584428185306864,82170533,24,SZ,145624000,3737508,1.045892e+08,28.21,28.15,...,100,4800,16400,28.35,1584428185305740,82170451,21,SZ,145624000,1.045892e+08
3201617,300561,1584428185306865,82170534,24,SZ,145624000,17616681,2.831895e+08,16.00,16.03,...,3100,2000,1400,17.08,1584428185305746,82170452,21,SZ,145624000,2.831895e+08
3203239,300562,1584428185306865,82170535,24,SZ,145624000,5008507,8.379952e+07,17.20,17.19,...,1100,5400,3000,16.85,1584428185305751,82170453,21,SZ,145624000,8.379952e+07
3204869,300563,1584428185306866,82170536,24,SZ,145624000,3155126,9.145848e+07,28.64,28.64,...,3600,900,5200,29.29,1584428185305756,82170454,21,SZ,145624000,9.145848e+07
3208414,300566,1584428185306822,82170524,24,SZ,145624000,3632674,8.292023e+07,22.86,22.86,...,1400,5900,1500,23.00,1584428185305642,82170434,21,SZ,145624000,8.292023e+07
3216491,300570,1584428185306822,82170525,24,SZ,145624000,9278771,2.589325e+08,27.61,27.60,...,100,1500,8300,29.00,1584428185305646,82170435,21,SZ,145624000,2.589325e+08
3242286,300588,1584428185306823,82170526,24,SZ,145624000,3499240,3.466816e+07,10.02,10.02,...,2400,3200,13000,10.10,1584428185305650,82170436,21,SZ,145624000,3.466816e+07
3245412,300590,1584428185306823,82170527,24,SZ,145624000,4415920,2.122879e+08,47.84,47.84,...,1400,1500,8000,48.38,1584428185305685,82170442,21,SZ,145624000,2.122879e+08
3257039,300598,1584428185306824,82170528,24,SZ,145624000,5767448,1.930142e+09,342.49,342.49,...,500,100,400,339.35,1584428185305691,82170443,21,SZ,145624000,1.930142e+09

In [50]:
data2[data2["StockID"] == 1]["time"].unique()

array([113000000, 130000000, 130003000, ..., 145651000, 145654000,
       145657000], dtype=int64)

In [48]:
data2[(data2["time"] >= 130000000) & (data2["StockID"] == 1)]

,clockAtArrival,sequenceNo,source,StockID,exchange,time,cum_volume,cum_amount,close,bid1p,...,ask2p,ask3p,ask4p,ask5p,ask1q,ask2q,ask3q,ask4q,ask5q,openPrice
96686,1584421200492151,221098,21,1,SZ,130000000,77793376,1.049852e+09,13.48,13.47,...,13.49,13.50,13.51,13.52,19800,115000,121560,31300,28700,13.75
96687,1584421200492162,221099,21,1,SZ,130000000,77793376,1.049852e+09,13.48,13.47,...,13.49,13.50,13.51,13.52,19800,115000,121560,31300,28700,13.75
103642,1584421203714242,1015703,21,1,SZ,130003000,77925876,1.051638e+09,13.48,13.47,...,13.49,13.50,13.51,13.52,8800,70600,99680,30500,25700,13.75
111400,1584421206596310,1642715,21,1,SZ,130006000,77984596,1.052430e+09,13.48,13.48,...,13.50,13.51,13.52,13.53,34000,97780,28500,24200,129929,13.75
117822,1584421209564859,1802976,21,1,SZ,130009000,78022274,1.052938e+09,13.50,13.49,...,13.51,13.52,13.53,13.54,99980,28300,24000,129929,66400,13.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11133513,1584428205519966,82538079,21,1,SZ,145645000,116457506,1.564709e+09,13.39,13.38,...,13.40,13.41,13.42,13.43,63100,122471,130800,45700,34200,13.75
11139161,1584428208554970,82590597,21,1,SZ,145648000,116523306,1.565590e+09,13.40,13.39,...,13.41,13.42,13.43,13.44,117951,130100,45700,34200,50600,13.75
11144496,1584428211524680,82640690,21,1,SZ,145651000,116549406,1.565939e+09,13.39,13.39,...,13.41,13.42,13.43,13.44,121351,130100,45700,34200,50600,13.75
11149981,1584428214534446,82690218,21,1,SZ,145654000,116557406,1.566047e+09,13.39,13.39,...,13.41,13.42,13.43,13.44,135851,124000,45700,34200,50600,13.75
11155402,1584428217506098,82740916,21,1,SZ,145657000,116572806,1.566253e+09,13.39,13.39,...,13.41,13.42,13.43,13.44,118351,124000,45700,34200,50600,13.75