In [1]:
import pandas as pd
import random
import numpy as np
import pickle

TradeLog1 = pd.read_csv(r'\\192.168.10.30\Kevin_zhenyu\check\20200324\full_20200324_zt_88_02_day_8843.tar\mdTradeLog_20200324_0838.csv',
                    encoding="utf-8").loc[:, ["clockAtArrival", "sequenceNo", "exchId", "TransactTime",
                                                 "ApplSeqNum", "SecurityID", "ExecType", "TradeBSFlag",
                                                 "TradePrice", "TradeQty", "TradeMoney", "BidApplSeqNum",
                                                 "OfferApplSeqNum"]]
OrderLog1 = pd.read_csv(r'\\192.168.10.30\Kevin_zhenyu\check\20200324\full_20200324_zt_88_02_day_8843.tar\mdOrderLog_20200324_0838.csv',
                    encoding="utf-8").loc[:, ["clockAtArrival", "sequenceNo", "exchId", "TransactTime",
                                                 "ApplSeqNum", "SecurityID", "Side", "OrderType", "Price",
                                                 "OrderQty"]]
TradeLog = pd.read_csv(r'\\192.168.10.30\Kevin_zhenyu\rawData\logs_20200324_zs_92_01_day_data\mdTradeLog_20200324_0836.csv',
                    encoding="utf-8").loc[:, ["clockAtArrival", "sequenceNo", "exchId", "TransactTime",
                                                 "ApplSeqNum", "SecurityID", "ExecType", "TradeBSFlag",
                                                 "TradePrice", "TradeQty", "TradeMoney", "BidApplSeqNum",
                                                 "OfferApplSeqNum"]]
OrderLog = pd.read_csv(r'\\192.168.10.30\Kevin_zhenyu\rawData\logs_20200324_zs_92_01_day_data\mdOrderLog_20200324_0836.csv',
                    encoding="utf-8").loc[:, ["clockAtArrival", "sequenceNo", "exchId", "TransactTime",
                                                 "ApplSeqNum", "SecurityID", "Side", "OrderType", "Price",
                                                 "OrderQty"]]
stocks = OrderLog1["SecurityID"].unique()
l1 = stocks[:1000]
l2 = stocks[1000:]
OrderLogSZ = OrderLog[OrderLog["SecurityID"].isin(l1)]
OrderLogSZ1 = OrderLog1[OrderLog1["SecurityID"].isin(l1)]
print(len(OrderLogSZ["SecurityID"].unique()))
print(len(OrderLogSZ1["SecurityID"].unique()))
OrderLogSZZ = OrderLog[OrderLog["SecurityID"].isin(l2)]
OrderLogSZZ1 = OrderLog1[OrderLog1["SecurityID"].isin(l2)]
print(len(OrderLogSZZ["SecurityID"].unique()))
print(len(OrderLogSZZ1["SecurityID"].unique()))
del OrderLog
del OrderLog1
TradeLogSZ = TradeLog[TradeLog["SecurityID"].isin(l1)]
TradeLogSZ1 = TradeLog1[TradeLog1["SecurityID"].isin(l1)]
print(len(TradeLogSZ["SecurityID"].unique()))
print(len(TradeLogSZ1["SecurityID"].unique()))
TradeLogSZZ = TradeLog[TradeLog["SecurityID"].isin(l2)]
TradeLogSZZ1 = TradeLog1[TradeLog1["SecurityID"].isin(l2)]
print(len(TradeLogSZZ["SecurityID"].unique()))
print(len(TradeLogSZZ1["SecurityID"].unique()))
TradeLogSH = TradeLog[TradeLog["exchId"] == 1]
TradeLogSH1 = TradeLog1[TradeLog1["exchId"] == 1]
print(len(TradeLogSH["SecurityID"].unique()))
print(len(TradeLogSH1["SecurityID"].unique()))
del TradeLog
del TradeLog1

OrderLogSZ.to_pickle(r'F:\\data\\20200324\\baseline\\order1.pkl')
OrderLogSZZ.to_pickle(r'F:\\data\\20200324\\baseline\\order2.pkl')
TradeLogSZ.to_pickle(r'F:\\data\\20200324\\baseline\\trade1.pkl')
TradeLogSZZ.to_pickle(r'F:\\data\\20200324\\baseline\\trade2.pkl')
TradeLogSH.to_pickle(r'F:\\data\\20200324\\baseline\\SH.pkl')
OrderLogSZ1.to_pickle(r'F:\\data\\20200324\\zt_88_02\\order1.pkl')
OrderLogSZZ1.to_pickle(r'F:\\data\\20200324\\zt_88_02\\order2.pkl')
TradeLogSZ1.to_pickle(r'F:\\data\\20200324\\zt_88_02\\trade1.pkl')
TradeLogSZZ1.to_pickle(r'F:\\data\\20200324\\zt_88_02\\trade2.pkl')
TradeLogSH1.to_pickle(r'F:\\data\\20200324\\zt_88_02\\SH.pkl')

C:\Users\win\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
C:\Users\win\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

873
1000
1319
2106
873
998
1319
2085

In [3]:
F1 = open("F:\\data\\20200324\\baseline\\SH.pkl", 'rb')
SH = pickle.load(F1)
F2 = open("F:\\data\\20200324\\zt_88_02\\SH.pkl", 'rb')
SH1 = pickle.load(F2)
sl = list(set(SH["SecurityID"].unique()) & set(SH1['SecurityID'].unique()))
SH = SH[SH["SecurityID"].isin(sl)]
SH1 = SH1[SH1["SecurityID"].isin(sl)]
print(len(SH["SecurityID"].unique()))
print(len(SH1["SecurityID"].unique()))
print(SH[SH["SecurityID"] == 600585].head())
print(SH1[SH1["SecurityID"] == 600585].head())

1585
1585
          clockAtArrival  sequenceNo  exchId  TransactTime  ApplSeqNum  \
261188  1585013112844162     2004787       1      92500430       14127
261189  1585013112844163     2004788       1      92500430       14128
261190  1585013112844164     2004789       1      92500430       14129
261191  1585013112844164     2004790       1      92500430       14130
261192  1585013112844165     2004791       1      92500430       14131

        SecurityID ExecType TradeBSFlag  TradePrice  TradeQty  TradeMoney  \
261188      600585        F           N      531300       700   371910000
261189      600585        F           N      531300       400   212520000
261190      600585        F           N      531300       100    53130000
261191      600585        F           N      531300       100    53130000
261192      600585        F           N      531300       100    53130000

        BidApplSeqNum  OfferApplSeqNum
261188          57945            30336
261189          61646            30336
261190          65071            34606
261191          65071            61300
261192          65071            88763
          clockAtArrival  sequenceNo  exchId  TransactTime  ApplSeqNum  \
287323  1585013070009621     4529197       1      92500430       14127
287324  1585013070009622     4529198       1      92500430       14128
287325  1585013070009623     4529199       1      92500430       14129
287326  1585013070009624     4529200       1      92500430       14130
287327  1585013070009625     4529201       1      92500430       14131

        SecurityID ExecType TradeBSFlag  TradePrice  TradeQty  TradeMoney  \
287323      600585        F           N      531300       700   371910000
287324      600585        F           N      531300       400   212520000
287325      600585        F           N      531300       100    53130000
287326      600585        F           N      531300       100    53130000
287327      600585        F           N      531300       100    53130000

        BidApplSeqNum  OfferApplSeqNum
287323          57945            30336
287324          61646            30336
287325          65071            34606
287326          65071            61300
287327          65071            88763

In [ ]:
import pandas as pd
import random
import numpy as np
TradeLog = pd.read_csv(r'\\192.168.10.30\Kevin_zhenyu\rawData\logs_20200324_zs_92_01_day_data\mdTradeLog_20200324_0836.csv',
                    encoding="utf-8").loc[:, ["clockAtArrival", "sequenceNo", "exchId", "TransactTime",
                                                  "ApplSeqNum", "SecurityID", "ExecType", "TradeBSFlag",
                                                  "TradePrice", "TradeQty", "TradeMoney", "BidApplSeqNum",
                                                  "OfferApplSeqNum"]]
TradeLog1 = pd.read_csv(r'\\192.168.10.30\Kevin_zhenyu\check\20200324\full_20200324_zt_88_02_day_8843.tar\mdTradeLog_20200324_0838.csv',
                    encoding="utf-8").loc[:, ["clockAtArrival", "sequenceNo", "exchId", "TransactTime",
                                                  "ApplSeqNum", "SecurityID", "ExecType", "TradeBSFlag",
                                                  "TradePrice", "TradeQty", "TradeMoney", "BidApplSeqNum",
                                                  "OfferApplSeqNum"]]
SH = TradeLog[TradeLog["exchId"] == 1]
SH1 = TradeLog1[TradeLog1["exchId"] == 1]
print(SH[SH["SecurityID"] == 600585].head())
print(SH1[SH1["SecurityID"] == 600585].head())

In [4]:
df["mdSource"].unique()

array([24, 21], dtype=int64)

In [3]:
import pandas as pd
import numpy as np
post = pd.read_csv(r'\\192.168.10.30\Kevin_zhenyu\check\20200317\full_20200316_zt_52_01_day_5274\full_20200316_zt_52_01_day_5274.tar.gz\mdTradeLog_20200316_0912.csv',
                    encoding="utf-8").loc[:, ["clockAtArrival", "sequenceNo", "exchId", "TransactTime",
                                                  "ApplSeqNum", "SecurityID", "ExecType", "TradeBSFlag",
                                                  "TradePrice", "TradeQty", "TradeMoney", "BidApplSeqNum",
                                                  "OfferApplSeqNum"]]
pre = pd.read_csv(r'\\192.168.10.30\Kevin_zhenyu\check\20200317\full_20200316_zt_52_01_day_5271\mdTradeLog_20200316_0909.csv',\
                    encoding="utf-8").loc[:, ["clockAtArrival", "sequenceNo", "exchId", "TransactTime",
                                                  "ApplSeqNum", "SecurityID", "ExecType", "TradeBSFlag",
                                                  "TradePrice", "TradeQty", "TradeMoney", "BidApplSeqNum",
                                                  "OfferApplSeqNum"]]
tdf = pd.read_csv(r'\\192.168.10.30\Kevin_zhenyu\check\20200317\full_20200316_zt_52_01_day_sidetdf\mdTradeLog_20200316_0909.csv',\
                    encoding="utf-8").loc[:, ["clockAtArrival", "sequenceNo", "exchId", "TransactTime",
                                                  "ApplSeqNum", "SecurityID", "ExecType", "TradeBSFlag",
                                                  "TradePrice", "TradeQty", "TradeMoney", "BidApplSeqNum",
                                                  "OfferApplSeqNum"]]
SH1 = post[post["exchId"] == 1]
SH2 = pre[pre["exchId"] == 1]
SH3 = tdf[tdf["exchId"] == 1]
print(SH1[SH1["SecurityID"] == 600585].head())
print(SH2[SH2["SecurityID"] == 600585].head())
print(SH3[SH3["SecurityID"] == 600585].head())

C:\Users\win\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

          clockAtArrival  sequenceNo  exchId  TransactTime  ApplSeqNum  \
418955  1584321908999260     2710555       1      92500160       12033
418956  1584321908999262     2710556       1      92500160       12034
418957  1584321908999264     2710557       1      92500160       12035
418958  1584321908999267     2710558       1      92500160       12036
418959  1584321908999269     2710559       1      92500160       12037

        SecurityID ExecType TradeBSFlag  TradePrice  TradeQty  TradeMoney  \
418955      600585        F           N      545300       100    54530000
418956      600585        F           N      545300       100    54530000
418957      600585        F           N      545300      3100  1690430000
418958      600585        F           N      545300      1300   708890000
418959      600585        F           N      545300      1000   545300000

        BidApplSeqNum  OfferApplSeqNum
418955          38709            35311
418956          59238            35311
418957          90124            35311
418958         105818            35311
418959         117444            35311
          clockAtArrival  sequenceNo  exchId  TransactTime  ApplSeqNum  \
418955  1584321908998412     2720763       1      92500160       12033
418956  1584321908998420     2720764       1      92500160       12034
418957  1584321908998426     2720765       1      92500160       12035
418958  1584321908998428     2720766       1      92500160       12036
418959  1584321908998433     2720767       1      92500160       12037

        SecurityID ExecType TradeBSFlag  TradePrice  TradeQty  TradeMoney  \
418955      600585        F           N      545300       100    54530000
418956      600585        F           N      545300       100    54530000
418957      600585        F           N      545300      3100  1690430000
418958      600585        F           N      545300      1300   708890000
418959      600585        F           N      545300      1000   545300000

        BidApplSeqNum  OfferApplSeqNum
418955          38709            35311
418956          59238            35311
418957          90124            35311
418958         105818            35311
418959         117444            35311
          clockAtArrival  sequenceNo  exchId  TransactTime  ApplSeqNum  \
415965  1584321909020132     2334148       1      92500160       12033
415966  1584321909020132     2334149       1      92500160       12034
415967  1584321909020132     2334150       1      92500160       12035
415968  1584321909020132     2334151       1      92500160       12036
415969  1584321909020132     2334152       1      92500160       12037

        SecurityID ExecType TradeBSFlag  TradePrice  TradeQty  TradeMoney  \
415965      600585        F           B      545300       100    54530000
415966      600585        F           B      545300       100    54530000
415967      600585        F           B      545300      3100  1690430000
415968      600585        F           B      545300      1300   708890000
415969      600585        F           B      545300      1000   545300000

        BidApplSeqNum  OfferApplSeqNum
415965          38709            35311
415966          59238            35311
415967          90124            35311
415968         105818            35311
415969         117444            35311

In [6]:
print(len(SH1["SecurityID"].unique()))
print(len(SH2["SecurityID"].unique()))
print(len(SH3["SecurityID"].unique()))
sl = SH3["SecurityID"].unique()

1581
1581
1552

In [37]:
SH1["ExecType"] = SH1["ExecType"].apply(lambda x: str(x))
SH2["ExecType"] = SH2["ExecType"].apply(lambda x: str(x))
SH3["ExecType"] = SH3["ExecType"].apply(lambda x: str(x))
columns = ["TransactTime", "ApplSeqNum", "SecurityID", "TradePrice", "TradeQty", "TradeMoney", "TradeBSFlag","ExecType",
           "BidApplSeqNum", "OfferApplSeqNum"]
SH3 = SH3.drop_duplicates(columns)
columns = ["TransactTime", "ApplSeqNum", "SecurityID", "TradePrice", "TradeQty", "ExecType",
           "BidApplSeqNum", "OfferApplSeqNum"]
re = pd.merge(SH2, SH3, left_on=columns, right_on=columns, how="outer", validate="one_to_one")
n1 = re["sequenceNo_x"].count()
n2 = re["sequenceNo_y"].count()
len1 = len(re)
print(n1)
print(n2)
print(len1)
display(re[re["sequenceNo_x"].isnull()]["TransactTime"].unique())
display(re[re["sequenceNo_x"].isnull()])
display(re[re["sequenceNo_y"].isnull()]["TransactTime"].unique())
display(re[re["sequenceNo_y"].isnull()])

22280664
21739091
22280744

array([150500440, 150503270, 150522100, 150532970, 150540430, 150544730,
       150545360, 150602900, 150609930, 150620480, 150622520, 150628710,
       150653650, 150656680, 150701540, 150726930, 150801340, 150816980,
       150817820, 150823050, 150913260, 150916620, 150920390, 150927400,
       150957990, 151004050, 151007370, 151011580, 151106610, 151119670,
       151148290, 151158570, 151304570, 151308740, 151453890, 151507160,
       151549370, 151614670, 151635880, 151653640, 151700360, 151726860,
       151830870, 151841460, 151857440, 151902290, 152011060, 152028390,
       152032140, 152046700, 152127460, 152129240, 152232050, 152234660,
       152521830, 152532500, 152709910, 152733190, 152753280, 152834920,
       152952610], dtype=int64)

,clockAtArrival_x,sequenceNo_x,exchId_x,TransactTime,ApplSeqNum,SecurityID,ExecType,TradeBSFlag_x,TradePrice,TradeQty,TradeMoney_x,BidApplSeqNum,OfferApplSeqNum,clockAtArrival_y,sequenceNo_y,exchId_y,TradeBSFlag_y,TradeMoney_y
22280664,NaN,NaN,NaN,150500440,3,688333,F,NaN,531000,200,NaN,54,44,1.584342e+15,149512384.0,1.0,B,106200000.0
22280665,NaN,NaN,NaN,150500440,4,688333,F,NaN,531000,100,NaN,75,44,1.584342e+15,149512385.0,1.0,B,53100000.0
22280666,NaN,NaN,NaN,150500440,5,688009,F,NaN,66200,500,NaN,39,85,1.584342e+15,149512386.0,1.0,S,33100000.0
22280667,NaN,NaN,NaN,150500440,6,688066,F,NaN,445200,200,NaN,26,66,1.584342e+15,149512387.0,1.0,S,89040000.0
22280668,NaN,NaN,NaN,150500440,7,688268,F,NaN,620100,200,NaN,41,48,1.584342e+15,149512388.0,1.0,S,124020000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22280739,NaN,NaN,NaN,152709910,142,688009,F,NaN,66200,1000,NaN,95,336,1.584344e+15,149512905.0,1.0,S,66200000.0
22280740,NaN,NaN,NaN,152733190,144,688005,F,NaN,331600,500,NaN,177,340,1.584344e+15,149512912.0,1.0,S,165800000.0
22280741,NaN,NaN,NaN,152753280,145,688357,F,NaN,471000,1500,NaN,290,342,1.584344e+15,149512919.0,1.0,S,706500000.0
22280742,NaN,NaN,NaN,152834920,147,688166,F,NaN,450000,51,NaN,345,308,1.584344e+15,149512924.0,1.0,B,22950000.0
22280743,NaN,NaN,NaN,152952610,150,688399,F,NaN,815900,200,NaN,245,356,1.584344e+15,149512937.0,1.0,S,163180000.0

array([ 92500050,  92500100,  92500120, ..., 150000830, 150000680,
       150000930], dtype=int64)

,clockAtArrival_x,sequenceNo_x,exchId_x,TransactTime,ApplSeqNum,SecurityID,ExecType,TradeBSFlag_x,TradePrice,TradeQty,TradeMoney_x,BidApplSeqNum,OfferApplSeqNum,clockAtArrival_y,sequenceNo_y,exchId_y,TradeBSFlag_y,TradeMoney_y
17050,1.584322e+15,2533805.0,1.0,92500050,4336,688026,F,N,789000,204,160956000.0,197664,92153,NaN,NaN,NaN,NaN,NaN
17051,1.584322e+15,2533806.0,1.0,92500050,4337,688026,F,N,789000,96,75744000.0,197664,198498,NaN,NaN,NaN,NaN,NaN
17052,1.584322e+15,2533807.0,1.0,92500050,4338,688026,F,N,789000,200,157800000.0,173727,198498,NaN,NaN,NaN,NaN,NaN
17053,1.584322e+15,2533808.0,1.0,92500050,4339,688026,F,N,789000,323,254847000.0,181811,198498,NaN,NaN,NaN,NaN,NaN
17054,1.584322e+15,2533809.0,1.0,92500050,4340,688026,F,N,789000,1088,858432000.0,214922,198498,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22280659,1.584342e+15,186415685.0,1.0,150000070,4743027,603948,F,N,270400,200,54080000.0,7158716,7205291,NaN,NaN,NaN,NaN,NaN
22280660,1.584342e+15,186415686.0,1.0,150000070,4743028,603948,F,N,270400,400,108160000.0,7158716,7205467,NaN,NaN,NaN,NaN,NaN
22280661,1.584342e+15,186415687.0,1.0,150000070,4743029,603948,F,N,270400,200,54080000.0,7158716,7205792,NaN,NaN,NaN,NaN,NaN
22280662,1.584342e+15,186415688.0,1.0,150000070,4743030,603948,F,N,270400,1900,513760000.0,7158716,7208651,NaN,NaN,NaN,NaN,NaN
22280663,1.584342e+15,186415689.0,1.0,150000070,4743031,603948,F,N,270400,2100,567840000.0,7158716,7208811,NaN,NaN,NaN,NaN,NaN

In [35]:
display(SH1[(SH1["SecurityID"]==601816) & (SH1["ApplSeqNum"] == 1238500)])
display(SH3[(SH3["SecurityID"]==601816) & (SH3["ApplSeqNum"] == 1238500)])

,clockAtArrival,sequenceNo,exchId,TransactTime,ApplSeqNum,SecurityID,ExecType,TradeBSFlag,TradePrice,TradeQty,TradeMoney,BidApplSeqNum,OfferApplSeqNum
18999723,1584324000284658,47719379,1,100000030,1238500,601816,F,B,66900,1000,66900000,2105872,1869663

Empty DataFrame
Columns: [clockAtArrival, sequenceNo, exchId, TransactTime, ApplSeqNum, SecurityID, ExecType, TradeBSFlag, TradePrice, TradeQty, TradeMoney, BidApplSeqNum, OfferApplSeqNum]
Index: []

In [38]:
re = re[~re["sequenceNo_x"].isnull()]
re = re[~re["sequenceNo_y"].isnull()]
diff = re["clockAtArrival_y"] - re["clockAtArrival_x"]
print(np.median(diff[diff < 0]))
print(np.median(diff[diff > 0]))
print(sum(diff < 0)/len(diff))
print(sum(diff > 0)/len(diff))

-548.0
12719.0
5.1658283810611255e-05
0.9999482037154312

In [2]:
# SH = SH[SH["TransactTime"] >= 103000000]
# SH1 = SH1[SH1["TransactTime"] >= 103000000]

In [5]:
# 1. completeness check
SH["ExecType"] = SH["ExecType"].apply(lambda x: str(x))
SH1["ExecType"] = SH1["ExecType"].apply(lambda x: str(x))
# SH1["TradeMoney"] = SH1["TradeMoney"].round(4)
# SH1["TradeMoney"] = SH1["TradeMoney"] * 10000
# SH1["TransactTime"] = SH1["TransactTime"]*10
columns = ["TransactTime", "ApplSeqNum", "SecurityID", "TradePrice", "TradeQty", "TradeMoney", "TradeBSFlag","ExecType",
           "BidApplSeqNum", "OfferApplSeqNum"]
# columns = ["TransactTime", "ApplSeqNum", "SecurityID", "TradePrice", "TradeQty", "ExecType",
#            "BidApplSeqNum", "OfferApplSeqNum"]
# columns = ["TransactTime", "ApplSeqNum", "SecurityID", "TradeBSFlag",
#            "BidApplSeqNum", "OfferApplSeqNum"]
# SH1["innerSeq"] = SH1.index.values
re = pd.merge(SH, SH1, left_on=columns, right_on=columns, how="outer", validate='one_to_one')
n1 = re["sequenceNo_x"].count()
n2 = re["sequenceNo_y"].count()
len1 = len(re)
print(n1)
print(n2)
print(len1)

17200902
17200962
17200962

In [6]:
SH1["Flag"] = np.where(SH1["ExecType"] == "4", np.nan, np.where(
    SH1["BidApplSeqNum"] > SH1["OfferApplSeqNum"], "B", "S"))
re = SH1[SH1["ExecType"] == "F"][SH1[SH1["ExecType"] == "F"]["TradeBSFlag"] != SH1[SH1["ExecType"] == "F"]["Flag"]]

In [8]:
re

,clockAtArrival,sequenceNo,exchId,TransactTime,ApplSeqNum,SecurityID,ExecType,TradeBSFlag,TradePrice,TradeQty,TradeMoney,BidApplSeqNum,OfferApplSeqNum,Flag
55559214,1585033020283710,214032830,1,145659880,3184357,603577,F,N,139500,500,69750000,5172814,5170340,B
55559218,1585033020283718,214032834,1,145659910,3184361,603888,F,N,231000,300,69300000,5172829,5036960,B
55559220,1585033020283721,214032836,1,145659940,3184363,601700,F,N,68300,300,20490000,5172837,5168477,B
55559221,1585033020283723,214032838,1,145659940,3184364,600036,F,N,315000,100,31500000,5170476,5172838,S
55559227,1585033020283732,214032844,1,145659980,3184370,600692,F,N,65100,600,39060000,5171757,5172856,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55564912,1585033200299521,214998964,1,150000050,2818111,601211,F,N,163200,2700,440640000,4655228,4575541,B
55564913,1585033200299521,214998965,1,150000050,2818112,601211,F,N,163200,4228,690000000,4655776,4575541,B
55564914,1585033200299521,214998966,1,150000050,2818113,601211,F,N,163200,1000,163200000,4655776,4587985,B
55564915,1585033200299521,214998967,1,150000050,2818114,601211,F,N,163200,472,77030000,4655776,4588277,B
55564916,1585033200299521,214998968,1,150000050,2818115,601211,F,N,163200,728,118800000,4655904,4588277,B

In [7]:
for i in re["SecurityID"].unique():
    if (len(SH1[(SH1["SecurityID"] == i) & (SH1["TransactTime"] >= 145659880)]["TradePrice"].unique()) >= 2):
        print(i)

603577
603888
600036
600692
603630
600498
688298
600312
601236
600522
601398
600598
601696
600118
601229
601318
601100
600346
600345
603005
600802
600219

In [7]:
display(re[np.isnan(re["sequenceNo_x"])]["TransactTime"].unique())
display(re[np.isnan(re["sequenceNo_x"])])
display(len(re[np.isnan(re["sequenceNo_x"])]))

array([150000060], dtype=int64)

,clockAtArrival_x,sequenceNo_x,exchId_x,TransactTime,ApplSeqNum,SecurityID,ExecType,TradeBSFlag,TradePrice,TradeQty,TradeMoney,BidApplSeqNum,OfferApplSeqNum,clockAtArrival_y,sequenceNo_y,exchId_y
17200902,NaN,NaN,NaN,150000060,3381945,603893,F,N,581900,100,58190000,5599764,5588207,1585033192028097,193576006,1
17200903,NaN,NaN,NaN,150000060,3381946,603893,F,N,581900,17,9892300,5599784,5588207,1585033192028098,193576007,1
17200904,NaN,NaN,NaN,150000060,3381947,603893,F,N,581900,500,290950000,5599784,5588446,1585033192028100,193576008,1
17200905,NaN,NaN,NaN,150000060,3381948,603893,F,N,581900,83,48297700,5599784,5589124,1585033192028101,193576009,1
17200906,NaN,NaN,NaN,150000060,3381949,603893,F,N,581900,100,58190000,5601682,5589124,1585033192028104,193576010,1
17200907,NaN,NaN,NaN,150000060,3381950,603893,F,N,581900,100,58190000,5553607,5589124,1585033192028106,193576011,1
17200908,NaN,NaN,NaN,150000060,3381951,603893,F,N,581900,17,9892300,5553775,5589124,1585033192028107,193576012,1
17200909,NaN,NaN,NaN,150000060,3381952,603893,F,N,581900,183,106487700,5553775,5591134,1585033192028110,193576013,1
17200910,NaN,NaN,NaN,150000060,3381953,603893,F,N,581900,100,58190000,5553810,5591134,1585033192028110,193576014,1
17200911,NaN,NaN,NaN,150000060,3381954,603893,F,N,581900,17,9892300,5553924,5591134,1585033192028111,193576015,1
17200912,NaN,NaN,NaN,150000060,3381955,603893,F,N,581900,300,174570000,5553924,5592222,1585033192028120,193576016,1
17200913,NaN,NaN,NaN,150000060,3381956,603893,F,N,581900,100,58190000,5553924,5592462,1585033192028122,193576017,1
17200914,NaN,NaN,NaN,150000060,3381957,603893,F,N,581900,100,58190000,5553924,5592493,1585033192028122,193576018,1
17200915,NaN,NaN,NaN,150000060,3381958,603893,F,N,581900,600,349140000,5553924,5593180,1585033192028123,193576019,1
17200916,NaN,NaN,NaN,150000060,3381959,603893,F,N,581900,2283,1328477700,5553924,5593432,1585033192028125,193576020,1
17200917,NaN,NaN,NaN,150000060,3381960,603893,F,N,581900,100,58190000,5553940,5593432,1585033192028126,193576021,1
17200918,NaN,NaN,NaN,150000060,3381961,603893,F,N,581900,617,359032300,5563664,5593432,1585033192028127,193576022,1
17200919,NaN,NaN,NaN,150000060,3381962,603893,F,N,581900,300,174570000,5563664,5594045,1585033192028129,193576023,1
17200920,NaN,NaN,NaN,150000060,3381963,603893,F,N,581900,100,58190000,5563664,5602457,1585033192028129,193576024,1
17200921,NaN,NaN,NaN,150000060,3381964,603893,F,N,581900,100,58190000,5563664,5602486,1585033192028131,193576025,1
17200922,NaN,NaN,NaN,150000060,3381965,603893,F,N,581900,283,164677700,5563664,5549057,1585033192028134,193576026,1
17200923,NaN,NaN,NaN,150000060,3381966,603893,F,N,581900,100,58190000,5566355,5549057,1585033192028135,193576027,1
17200924,NaN,NaN,NaN,150000060,3381967,603893,F,N,581900,400,232760000,5569685,5549057,1585033192028136,193576028,1
17200925,NaN,NaN,NaN,150000060,3381968,603893,F,N,581900,100,58190000,5577221,5549057,1585033192028137,193576029,1
17200926,NaN,NaN,NaN,150000060,3381969,603893,F,N,581900,400,232760000,5577778,5549057,1585033192028139,193576030,1
17200927,NaN,NaN,NaN,150000060,3381970,603893,F,N,581900,800,465520000,5581832,5549057,1585033192028139,193576031,1
17200928,NaN,NaN,NaN,150000060,3381971,603893,F,N,581900,500,290950000,5585040,5549057,1585033192028140,193576032,1
17200929,NaN,NaN,NaN,150000060,3381972,603893,F,N,581900,500,290950000,5585950,5549057,1585033192028143,193576033,1
17200930,NaN,NaN,NaN,150000060,3381973,603893,F,N,581900,117,68082300,5585993,5549057,1585033192028143,193576034,1
17200931,NaN,NaN,NaN,150000060,3381974,603893,F,N,581900,500,290950000,5585993,5560431,1585033192028145,193576035,1
17200932,NaN,NaN,NaN,150000060,3381975,603893,F,N,581900,100,58190000,5585993,5594080,1585033192028146,193576036,1
17200933,NaN,NaN,NaN,150000060,3381976,603893,F,N,581900,1100,640090000,5585993,5595365,1585033192028147,193576037,1
17200934,NaN,NaN,NaN,150000060,3381977,603893,F,N,581900,200,116380000,5585993,5598500,1585033192028148,193576038,1
17200935,NaN,NaN,NaN,150000060,3381978,603893,F,N,581900,800,465520000,5585993,5598944,1585033192028151,193576039,1
17200936,NaN,NaN,NaN,150000060,3381979,603893,F,N,581900,183,106487700,5585993,5599688,1585033192028152,193576040,1
17200937,NaN,NaN,NaN,150000060,3381980,603893,F,N,581900,100,58190000,5586761,5599688,1585033192028152,193576041,1
17200938,NaN,NaN,NaN,150000060,3381981,603893,F,N,581900,1000,581900000,5589985,5599688,1585033192028155,193576042,1
17200939,NaN,NaN,NaN,150000060,3381982,603893,F,N,581900,417,242652300,5590769,5599688,1585033192028156,193576043,1
17200940,NaN,NaN,NaN,150000060,3381983,603893,F,N,581900,183,106487700,5590769,5600660,1585033192028157,193576044,1
17200941,NaN,NaN,NaN,150000060,3381984,603893,F,N,581900,17,9892300,5591140,5600660,1585033192028177,193576045,1
17200942,NaN,NaN,NaN,150000060,3381985,603893,F,N,581900,283,164677700,5591140,5602145,1585033192028179,193576046,1
17200943,NaN,NaN,NaN,150000060,3381986,603893,F,N,581900,17,9892300,5591760,5602145,1585033192028182,193576047,1
17200944,NaN,NaN,NaN,150000060,3381987,603948,F,N,285800,1200,342960000,5133924,5556754,1585033192028187,193576048,1
17200945,NaN,NaN,NaN,150000060,3381988,603948,F,N,285800,720,205776000,5133924,5557321,1585033192028191,193576049,1
17200946,NaN,NaN,NaN,150000060,3381989,603948,F,N,285800,280,80024000,5133966,5557321,1585033192028192,193576050,1
17200947,NaN,NaN,NaN,150000060,3381990,603948,F,N,285800,300,85740000,5133966,5559802,1585033192028197,193576051,1
17200948,NaN,NaN,NaN,150000060,3381991,603948,F,N,285800,100,28580000,5133966,5559918,1585033192028197,193576052,1
17200949,NaN,NaN,NaN,150000060,3381992,603948,F,N,285800,500,142900000,5133966,5568535,1585033192028198,193576053,1
17200950,NaN,NaN,NaN,150000060,3381993,603948,F,N,285800,700,200060000,5133966,5571465,1585033192028199,193576054,1
17200951,NaN,NaN,NaN,150000060,3381994,603948,F,N,285800,1000,285800000,5133966,5571818,1585033192028202,193576055,1
17200952,NaN,NaN,NaN,150000060,3381995,603948,F,N,285800,1000,285800000,5133966,5572141,1585033192028203,193576056,1
17200953,NaN,NaN,NaN,150000060,3381996,603948,F,N,285800,200,57160000,5133966,5574597,1585033192028217,193576057,1
17200954,NaN,NaN,NaN,150000060,3381997,603948,F,N,285800,100,28580000,5133966,5577993,1585033192028218,193576058,1
17200955,NaN,NaN,NaN,150000060,3381998,603948,F,N,285800,100,28580000,5133966,5581199,1585033192028220,193576059,1
17200956,NaN,NaN,NaN,150000060,3381999,603948,F,N,285800,200,57160000,5133966,5585501,1585033192028221,193576060,1
17200957,NaN,NaN,NaN,150000060,3382000,603948,F,N,285800,200,57160000,5133966,5586938,1585033192028222,193576061,1
17200958,NaN,NaN,NaN,150000060,3382001,603948,F,N,285800,320,91456000,5133966,5587449,1585033192028225,193576062,1
17200959,NaN,NaN,NaN,150000060,3382002,603948,F,N,285800,500,142900000,5134049,5587449,1585033192028227,193576063,1
17200960,NaN,NaN,NaN,150000060,3382003,603948,F,N,285800,1180,337244000,5134056,5587449,1585033192028228,193576064,1
17200961,NaN,NaN,NaN,150000060,3382004,603948,F,N,285800,100,28580000,5134056,5597894,1585033192028228,193576065,1

60

In [5]:
len(re[np.isnan(re["sequenceNo_y"])])

45

In [4]:
SH[(SH["SecurityID"] == 600538) & (SH["ApplSeqNum"] == 1)]

,clockAtArrival,sequenceNo,exchId,TransactTime,ApplSeqNum,SecurityID,ExecType,TradeBSFlag,TradePrice,TradeQty,TradeMoney,BidApplSeqNum,OfferApplSeqNum
43675,1585013104015007,1776299,1,92500020,1,600538,F,N,66800,64,4275200,4763,44995

In [5]:
SH1[(SH1["SecurityID"] == 600538) & (SH1["ApplSeqNum"] == 1)]

,clockAtArrival,sequenceNo,exchId,TransactTime,ApplSeqNum,SecurityID,ExecType,TradeBSFlag,TradePrice,TradeQty,TradeMoney,BidApplSeqNum,OfferApplSeqNum
42923,1585013100200096,2526430,1,92500020,1,600538,F,S,66800,64,4270000,4763,44995

In [9]:
# 2. Ordering within stocks
stocks = SH["SecurityID"].unique()
m = 0
diff = []
for i in stocks:
    re1 = pd.merge(SH[SH["SecurityID"] == i], SH1[SH1["SecurityID"] == i], left_on=columns, right_on=columns, how="inner")
    if (sorted(re1["innerSeq"]) != re1["innerSeq"]).any() == False:
        m = m + 1
    else:
        diff.append(i)
if m == len(stocks):
    print("SHE Trade Data have same ordering within stocks")
else:
    print("SHE Trade Data don't have same ordering within stocks")

SHE Trade Data have same ordering within stocks

In [18]:
diff

[603105, 600703]

In [24]:
re1 = pd.merge(SH[SH["SecurityID"] == 603105], SH1[SH1["SecurityID"] == 603105], left_on=columns, right_on=columns, how="inner")
re1[sorted(re1["sequenceNo_y"]) != re1["sequenceNo_y"]]

,clockAtArrival_x,sequenceNo_x,exchId_x,TransactTime,ApplSeqNum,SecurityID,ExecType_x,TradeBSFlag,TradePrice,TradeQty,TradeMoney,BidApplSeqNum,OfferApplSeqNum,clockAtArrival_y,sequenceNo_y,exchId_y,ExecType_y
1017,1581643820604644,2520797,1,93000720,22728,603105,F,B,71000,300,21300000,144995,144833,1581643884759952,5378465,1,F
1018,1581643820604645,2520798,1,93000720,22729,603105,F,B,71000,200,14200000,144995,144929,1581643884759953,5378466,1,F
1019,1581643820604649,2520803,1,93000720,22734,603105,F,B,71000,300,21300000,145007,144929,1581643884759957,5378462,1,F
1020,1581643820604651,2520805,1,93000720,22735,603105,F,B,71100,400,28440000,145007,136727,1581643884759957,5378464,1,F

In [8]:
# 3. Ordering among stocks
SH1 = SH1.reset_index(drop=True)
SH1["innerSeq"] = SH1.index.values
re = pd.merge(SH, SH1, left_on=columns, right_on=columns, how="inner")
if (sorted(re["innerSeq"]) != re["innerSeq"]).any():
    print("SHE Trade Data don't have same ordering among stocks")
else:
    print("SHE Trade Data have same ordering among stocks")
print(len(re))
print(len(re[sorted(re["sequenceNo_y"]) != re["sequenceNo_y"]]))

SHE Trade Data have same ordering among stocks
17200902
0

In [9]:
columns = ["TransactTime", "ApplSeqNum", "SecurityID", "TradePrice", "TradeQty", "TradeMoney", "TradeBSFlag",
           "BidApplSeqNum", "OfferApplSeqNum"]
re1 = pd.merge(SH[SH["SecurityID"] == 600547], SH1[SH1["SecurityID"] == 600547], left_on=columns, right_on=columns, how="outer")

In [10]:
re1[sorted(re1["sequenceNo_y"]) != re1["sequenceNo_y"]]

,clockAtArrival_x,sequenceNo_x,exchId_x,TransactTime,ApplSeqNum,SecurityID,ExecType_x,TradeBSFlag,TradePrice,TradeQty,TradeMoney,BidApplSeqNum,OfferApplSeqNum,clockAtArrival_y,sequenceNo_y,exchId_y,ExecType_y
53970,1581056698612887,122106803,1,142442750,2782357,600547,F,S,323500,300,97050000,3957291,4412270,1581056683003639,120903932,1,F
53971,1581056698612887,122106804,1,142442750,2782358,600547,F,S,323500,500,161750000,3961270,4412270,1581056683003640,120903931,1,F

In [11]:
re1.loc[53968:, :]

,clockAtArrival_x,sequenceNo_x,exchId_x,TransactTime,ApplSeqNum,SecurityID,ExecType_x,TradeBSFlag,TradePrice,TradeQty,TradeMoney,BidApplSeqNum,OfferApplSeqNum,clockAtArrival_y,sequenceNo_y,exchId_y,ExecType_y
53968,1581056698612885,122106801,1,142442750,2782355,600547,F,S,323500,100,32350000,3887722,4412270,1581056683003637,120903930,1,F
53969,1581056698612886,122106802,1,142442750,2782356,600547,F,S,323500,100,32350000,3952356,4412270,1581056683003638,120903931,1,F
53970,1581056698612887,122106803,1,142442750,2782357,600547,F,S,323500,300,97050000,3957291,4412270,1581056683003639,120903932,1,F
53971,1581056698612887,122106804,1,142442750,2782358,600547,F,S,323500,500,161750000,3961270,4412270,1581056683003640,120903931,1,F
53972,1581056698612888,122106805,1,142442750,2782359,600547,F,S,323500,1000,323500000,3966963,4412270,1581056683003640,120903932,1,F
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61832,1581058816916615,140391514,1,150000020,3199520,600547,F,N,324200,1365,442533000,5056136,5054901,1581058801051569,138976043,1,F
61833,1581058816916616,140391515,1,150000020,3199521,600547,F,N,324200,200,64840000,5056136,5055050,1581058801051569,138976044,1,F
61834,1581058816916618,140391516,1,150000020,3199522,600547,F,N,324200,200,64840000,5056136,5055332,1581058801051570,138976045,1,F
61835,1581058816916624,140391517,1,150000020,3199523,600547,F,N,324200,235,76187000,5056136,5056143,1581058801051570,138976046,1,F
61836,1581058816916625,140391518,1,150000020,3199524,600547,F,N,324200,265,85913000,5056445,5056143,1581058801051571,138976047,1,F

In [14]:
SH1[(SH1["SecurityID"] == 600547) & ((SH1["sequenceNo"] == 120903931) | (SH1["sequenceNo"] == 120903932))]

,clockAtArrival,sequenceNo,exchId,TransactTime,ApplSeqNum,SecurityID,ExecType,TradeBSFlag,TradePrice,TradeQty,TradeMoney,BidApplSeqNum,OfferApplSeqNum
54573377,1581056683003638,120903931,1,142442750,2782356,600547,F,S,323500,100,32350000,3952356,4412270
54573378,1581056683003639,120903932,1,142442750,2782357,600547,F,S,323500,300,97050000,3957291,4412270
54573379,1581056683003640,120903931,1,142442750,2782358,600547,F,S,323500,500,161750000,3961270,4412270
54573380,1581056683003640,120903932,1,142442750,2782359,600547,F,S,323500,1000,323500000,3966963,4412270

In [8]:
# 4. speed check
re1 = re[~np.isnan(re["sequenceNo_y"])]
diff = re1["clockAtArrival_y"] - re1["clockAtArrival_x"]
print(np.median(diff[diff < 0]))
print(np.median(diff[diff > 0]))
print(sum(diff > 0)/len(diff))

C:\Users\win\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:3118: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
C:\Users\win\Anaconda3\lib\site-packages\numpy\core\_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)

nan
870.0
1.0

In [9]:
re[re["clockAtArrival_y"] - re["clockAtArrival_x"] > 0]

,clockAtArrival_x,sequenceNo_x,exchId_x,TransactTime,ApplSeqNum,SecurityID,ExecType_x,TradeBSFlag,TradePrice_x,TradeQty,TradeMoney_x,BidApplSeqNum,OfferApplSeqNum,clockAtArrival_y,sequenceNo_y,exchId_y,ExecType_y,TradePrice_y,TradeMoney_y
4357175,1.581317e+15,146058208.0,1.0,144420880,2895808,603799,F,B,46.0,600,2.798400e+08,4754489,4613576,1581317061312378,9437004,1,F,466400,279840000
4357176,1.581317e+15,146058209.0,1.0,144420880,2895809,603799,F,B,46.0,600,2.798400e+08,4754489,4613583,1581317061312379,9437005,1,F,466400,279840000
4357181,1.581317e+15,146058214.0,1.0,144420880,2895814,603799,F,B,46.0,2000,9.328000e+08,4754489,4614232,1581317061312386,9437010,1,F,466400,932800000
4357182,1.581317e+15,146058215.0,1.0,144420880,2895815,603799,F,B,46.0,300,1.399200e+08,4754489,4614250,1581317061312387,9437011,1,F,466400,139920000
4357183,1.581317e+15,146058216.0,1.0,144420880,2895816,603799,F,B,46.0,200,9.328000e+07,4754489,4614397,1581317061312387,9437012,1,F,466400,93280000
4357186,1.581317e+15,146058219.0,1.0,144420880,2895819,603799,F,B,46.0,500,2.332000e+08,4754489,4614773,1581317061312393,9437015,1,F,466400,233200000
4357187,1.581317e+15,146058220.0,1.0,144420880,2895820,603799,F,B,46.0,250,1.166000e+08,4754489,4614877,1581317061312394,9437016,1,F,466400,116600000
4357188,1.581317e+15,146058221.0,1.0,144420880,2895821,603799,F,B,46.0,200,9.328000e+07,4754489,4614904,1581317061312395,9437017,1,F,466400,93280000
4357189,1.581317e+15,146058222.0,1.0,144420880,2895822,603799,F,B,46.0,200,9.328000e+07,4754489,4615036,1581317061312395,9437018,1,F,466400,93280000
4357190,1.581317e+15,146058223.0,1.0,144420880,2895823,603799,F,B,46.0,100,4.664000e+07,4754489,4615090,1581317061312400,9437019,1,F,466400,46640000
4357191,1.581317e+15,146058224.0,1.0,144420880,2895824,603799,F,B,46.0,100,4.664000e+07,4754489,4615536,1581317061312401,9437020,1,F,466400,46640000
4357192,1.581317e+15,146058225.0,1.0,144420880,2895825,603799,F,B,46.0,100,4.664000e+07,4754489,4615680,1581317061312402,9437021,1,F,466400,46640000
4357193,1.581317e+15,146058226.0,1.0,144420880,2895826,603799,F,B,46.0,200,9.328000e+07,4754489,4615778,1581317061312405,9437022,1,F,466400,93280000
4357194,1.581317e+15,146058227.0,1.0,144420880,2895827,603799,F,B,46.0,200,9.328000e+07,4754489,4615968,1581317061312405,9437023,1,F,466400,93280000
4357195,1.581317e+15,146058228.0,1.0,144420880,2895828,603799,F,B,46.0,1000,4.664000e+08,4754489,4616056,1581317061312406,9437024,1,F,466400,466400000
4357196,1.581317e+15,146058229.0,1.0,144420880,2895829,603799,F,B,46.0,200,9.328000e+07,4754489,4616057,1581317061312407,9437025,1,F,466400,93280000
4357197,1.581317e+15,146058230.0,1.0,144420880,2895830,603799,F,B,46.0,200,9.328000e+07,4754489,4616074,1581317061312408,9437026,1,F,466400,93280000
4357198,1.581317e+15,146058231.0,1.0,144420880,2895831,603799,F,B,46.0,1000,4.664000e+08,4754489,4616124,1581317061312412,9437027,1,F,466400,466400000
4357199,1.581317e+15,146058232.0,1.0,144420880,2895832,603799,F,B,46.0,400,1.865600e+08,4754489,4616326,1581317061312413,9437028,1,F,466400,186560000
4357200,1.581317e+15,146058233.0,1.0,144420880,2895833,603799,F,B,46.0,1200,5.596800e+08,4754489,4616578,1581317061312414,9437029,1,F,466400,559680000
4357201,1.581317e+15,146058234.0,1.0,144420880,2895834,603799,F,B,46.0,500,2.332000e+08,4754489,4616670,1581317061312414,9437030,1,F,466400,233200000
4357202,1.581317e+15,146058235.0,1.0,144420880,2895835,603799,F,B,46.0,100,4.664000e+07,4754489,4616900,1581317061312415,9437031,1,F,466400,46640000
4357203,1.581317e+15,146058236.0,1.0,144420880,2895836,603799,F,B,46.0,200,9.328000e+07,4754489,4616989,1581317061312416,9437032,1,F,466400,93280000
4357204,1.581317e+15,146058237.0,1.0,144420880,2895837,603799,F,B,46.0,100,4.664000e+07,4754489,4617227,1581317061312422,9437033,1,F,466400,46640000
4357205,1.581317e+15,146058238.0,1.0,144420880,2895838,603799,F,B,46.0,1300,6.063200e+08,4754489,4617396,1581317061312423,9437034,1,F,466400,606320000
4357206,1.581317e+15,146058239.0,1.0,144420880,2895839,603799,F,B,46.0,2200,1.026080e+09,4754489,4617503,1581317061312424,9437035,1,F,466400,1026080000
4357207,1.581317e+15,146058240.0,1.0,144420880,2895840,603799,F,B,46.0,1000,4.664000e+08,4754489,4617651,1581317061312430,9437036,1,F,466400,466400000
4357208,1.581317e+15,146058241.0,1.0,144420880,2895841,603799,F,B,46.0,200,9.328000e+07,4754489,4617727,1581317061312431,9437037,1,F,466400,93280000
4357209,1.581317e+15,146058242.0,1.0,144420880,2895842,603799,F,B,46.0,600,2.798400e+08,4754489,4617948,1581317061312432,9437038,1,F,466400,279840000
4357210,1.581317e+15,146058243.0,1.0,144420880,2895843,603799,F,B,46.0,300,1.399200e+08,4754489,4618279,1581317061312435,9437039,1,F,466400,139920000
4357211,1.581317e+15,146058244.0,1.0,144420880,2895844,603799,F,B,46.0,100,4.664000e+07,4754489,4618728,1581317061312443,9437040,1,F,466400,46640000
4357212,1.581317e+15,146058245.0,1.0,144420880,2895845,603799,F,B,46.0,100,4.664000e+07,4754489,4618956,1581317061312446,9437041,1,F,466400,46640000
4357213,1.581317e+15,146058246.0,1.0,144420880,2895846,603799,F,B,46.0,100,4.664000e+07,4754489,4619043,1581317061312447,9437042,1,F,466400,46640000
4357214,1.581317e+15,146058247.0,1.0,144420880,2895847,603799,F,B,46.0,200,9.328000e+07,4754489,4619078,1581317061312447,9437043,1,F,466400,93280000
4357215,1.581317e+15,146058248.0,1.0,144420880,2895848,603799,F,B,46.0,240,1.119300e+08,4754489,4619839,1581317061312448,9437044,1,F,466400,111936000
4357216,1.581317e+15,146058249.0,1.0,144420880,2895849,603799,F,B,46.0,500,2.332000e+08,4754489,4619865,1581317061312450,9437045,1,F,466400,233200000
4357217,1.581317e+15,146058250.0,1.0,144420880,2895850,603799,F,B,46.0,2000,9.328000e+08,4754489,4620898,1581317061312452,9437046,1,F,466400,932800000
4357218,1.581317e+15,146058251.0,1.0,144420880,2895851,603799,F,B,46.0,2500,1.166000e+09,4754489,4621265,1581317061312454,9437047,1,F,466400,1166000000
4357219,1.581317e+15,146058252.0,1.0,144420880,2895852,603799,F,B,46.0,2000,9.328000e+08,4754489,4621404,1581317061312455,9437048,1,F,466400,932800000
4357220,1.581317e+15,146058253.0,1.0,144420880,2895853,603799,F,B,46.0,100,4.664000e+07,4754489,4621453,1581317061312457,9437049,1,F,466400,46640000
4357221,1.581317e+15,146058254.0,1.0,144420880,2895854,603799,F,B,46.0,200,9.328000e+07,4754489,4621519,1581317061312458,9437050,1,F,466400,93280000
4357222,1.581317e+15,146058255.0,1.0,144420880,2895855,603799,F,B,46.0,1000,4.664000e+08,4754489,4621976,1581317061312465,9437051,1,F,466400,466400000
4357223,1.581317e+15,146058256.0,1.0,144420880,2895856,603799,F,B,46.0,200,9.328000e+07,4754489,4622179,1581317061312469,9437052,1,F,466400,93280000
4357224,1.581317e+15,146058257.0,1.0,144420880,2895857,603799,F,B,46.0,100,4.664000e+07,4754489,4622529,1581317061312470,9437053,1,F,466400,46640000
4357225,1.581317e+15,146058258.0,1.0,144420880,2895858,603799,F,B,46.0,200,9.328000e+07,4754489,4622568,1581317061312470,9437054,1,F,466400,93280000
4357226,1.581317e+15,146058259.0,1.0,144420880,2895859,603799,F,B,46.0,200,9.328000e+07,4754489,4622688,1581317061312471,9437055,1,F,466400,93280000
4357227,1.581317e+15,146058260.0,1.0,144420880,2895860,603799,F,B,46.0,200,9.328000e+07,4754489,4622999,1581317061312472,9437056,1,F,466400,93280000
4357228,1.581317e+15,146058261.0,1.0,144420880,2895861,603799,F,B,46.0,200,9.328000e+07,4754489,4623200,1581317061312477,9437057,1,F,466400,93280000
4357229,1.581317e+15,146058262.0,1.0,144420880,2895862,603799,F,B,46.0,300,1.399200e+08,4754489,4623381,1581317061312478,9437058,1,F,466400,139920000
4357230,1.581317e+15,146058263.0,1.0,144420880,2895863,603799,F,B,46.0,600,2.798400e+08,4754489,4623434,1581317061312478,9437059,1,F,466400,279840000
4357231,1.581317e+15,146058264.0,1.0,144420880,2895864,603799,F,B,46.0,200,9.328000e+07,4754489,4623737,1581317061312480,9437060,1,F,466400,93280000
4357232,1.581317e+15,146058265.0,1.0,144420880,2895865,603799,F,B,46.0,100,4.664000e+07,4754489,4623757,1581317061312480,9437061,1,F,466400,46640000
4357233,1.581317e+15,146058266.0,1.0,144420880,2895866,603799,F,B,46.0,200,9.328000e+07,4754489,4623759,1581317061312482,9437062,1,F,466400,93280000
4357234,1.581317e+15,146058267.0,1.0,144420880,2895867,603799,F,B,46.0,100,4.664000e+07,4754489,4623925,1581317061312484,9437063,1,F,466400,46640000
4357235,1.581317e+15,146058268.0,1.0,144420880,2895868,603799,F,B,46.0,200,9.328000e+07,4754489,4623928,1581317061312487,9437064,1,F,466400,93280000
4357236,1.581317e+15,146058269.0,1.0,144420880,2895869,603799,F,B,46.0,300,1.399200e+08,4754489,4624060,1581317061312488,9437065,1,F,466400,139920000
4357237,1.581317e+15,146058270.0,1.0,144420880,2895870,603799,F,B,46.0,200,9.328000e+07,4754489,4624133,1581317061312489,9437066,1,F,466400,93280000
4357238,1.581317e+15,146058271.0,1.0,144420880,2895871,603799,F,B,46.0,200,9.328000e+07,4754489,4625305,1581317061312493,9437067,1,F,466400,93280000
4357239,1.581317e+15,146058272.0,1.0,144420880,2895872,603799,F,B,46.0,100,4.664000e+07,4754489,4625453,1581317061312500,9437068,1,F,466400,46640000