In [34]:
import pandas as pd
import matplotlib as mpl
import glob
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats
import matplotlib.dates as mdates
import math
from scipy import stats
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm
from pandas.plotting import register_matplotlib_converters
register_matplotlib_converters()
from datetime import timedelta
import calendar
import seaborn as sns

# 1. calculate beta with respect to SH000905
sto_ck1 = pd.read_csv('E:\\all_stock.csv', encoding="GBK").iloc[:, 1:]
sto_ck2 = pd.read_csv('F:\\all_stock_2020.csv', encoding="GBK").iloc[:, 1:]
sto_ck = pd.concat([sto_ck1, sto_ck2]).sort_values(by=["Symbol", "Date"])
in_dex = pd.read_csv(r'F:\Download\index\index_daily_SH000300.csv',
                           encoding="utf-8").iloc[:, 1:]
sto_ck["ret"] = sto_ck["ret"]/100
in_dex["returns"] = in_dex['close']/in_dex['close'].shift(1) - 1

def add_market(x):
    x2 = in_dex.loc[:, ["Date", "returns"]]
    xx = pd.merge(x, x2, left_on="Date", right_on="Date", how='inner')
    xx.columns = ["Date", "s_returns", "m_returns"]
    return xx
da_ta = sto_ck.groupby("Symbol")["Date", "ret"].apply(add_market).reset_index().loc[:,
       ["Date", "Symbol", "s_returns", "m_returns"]]
print(da_ta)

def cal(x):
    x.columns = ["x", "y"]
    x_cov = x.rolling(60).cov().unstack()['x']['y']
    x_var = x['y'].to_frame().rolling(60).var()
    result = x_cov / x_var.iloc[:, 0]
    re = pd.DataFrame(result.values, index=range(0, len(result)))
    print(re)
    return re
da_ta["beta"] = da_ta.groupby("Symbol")['s_returns', 'm_returns'].apply(cal).reset_index().iloc[:, 2]
da_ta["beta"] = da_ta.groupby("Symbol")["beta"].shift(1)
da_ta["alpha"] = da_ta["s_returns"] - da_ta["beta"]*da_ta["m_returns"]
da_ta.to_csv('E:\\new_beta_300.csv', encoding="utf-8")

             Date    Symbol  s_returns  m_returns
0        20100104  SH600000  -0.023052  -0.011314
1        20100105  SH600000   0.007551   0.008149
2        20100106  SH600000  -0.019672  -0.006260
3        20100107  SH600000  -0.022456  -0.019841
4        20100108  SH600000   0.011241   0.002499
...           ...       ...        ...        ...
6715352  20200624  SZ300842   0.100033   0.004172
6715353  20200629  SZ300842   0.100149  -0.007073
6715354  20200630  SZ300842   0.099946   0.013200
6715355  20200701  SZ300842   0.099951   0.020130
6715356  20200701  SZ300846   0.439169   0.020130

[6715357 rows x 4 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2497  0.551493
2498  0.578071
2499  0.574950
2500  0.585281
2501  0.602113

[2502 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2541  1.443495
2542  1.427088
2543  1.446024
2544  1.340989
2545  1.284045

[2546 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2488  0.793856
2489  0.750535
2490  0.747605
2491  0.736260
2492  0.704774

[2493 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2540  0.586162
2541  0.581471
2542  0.596490
2543  0.596915
2544  0.639866

[2545 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2519  0.554146
2520  0.535658
2521  0.524564
2522  0.499384
2523  0.466163

[2524 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2541  1.244652
2542  1.238394
2543  1.241906
2544  1.188367
2545  1.142373

[2546 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2470  0.444010
2471  0.416190
2472  0.422183
2473  0.428463
2474  0.402338

[2475 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2530  0.604187
2531  0.592166
2532  0.586514
2533  0.661018
2534  0.649271

[2535 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2539  0.548449
2540  0.526556
2541  0.529908
2542  0.488466
2543  0.492808

[2544 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2525  0.414019
2526  0.423438
2527  0.422166
2528  0.417379
2529  0.439410

[2530 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2535  0.473160
2536  0.484852
2537  0.477958
2538  0.479177
2539  0.498649

[2540 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2523  0.620448
2524  0.595914
2525  0.605358
2526  0.566176
2527  0.542377

[2528 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2484  0.594074
2485  0.623039
2486  0.641335
2487  0.654271
2488  0.630772

[2489 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2444  0.645037
2445  0.625208
2446  0.629216
2447  0.618308
2448  0.635565

[2449 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2528  0.659910
2529  0.644327
2530  0.647850
2531  0.622159
2532  0.616577

[2533 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2416  0.446957
2417  0.417959
2418  0.431546
2419  0.450642
2420  0.564281

[2421 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2291  0.457033
2292  0.422769
2293  0.454968
2294  0.455588
2295  0.453729

[2296 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1586  0.385727
1587  0.372370
1588  0.387120
1589  0.384784
1590  0.409440

[1591 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
611  0.660281
612  0.665929
613  0.588876
614  0.603251
615  0.551882

[616 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2437  0.940742
2438  1.047694
2439  1.076230
2440  1.234003
2441  1.137318

[2442 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2530  0.357830
2531  0.359011
2532  0.362162
2533  0.479916
2534  0.510916

[2535 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2539  0.705242
2540  0.706142
2541  0.715452
2542  0.706561
2543  0.686088

[2544 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2520  0.932052
2521  0.932722
2522  0.942911
2523  0.921909
2524  0.884879

[2525 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2510  1.231219
2511  1.227871
2512  1.267539
2513  1.293877
2514  1.297303

[2515 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2531  0.807523
2532  0.796362
2533  0.767433
2534  0.829644
2535  0.893048

[2536 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2538  0.392045
2539  0.392280
2540  0.405876
2541  0.409730
2542  0.385216

[2543 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2392  0.749381
2393  0.829534
2394  0.826388
2395  0.809832
2396  0.772413

[2397 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2523  0.984591
2524  1.018400
2525  1.017536
2526  1.016863
2527  1.064567

[2528 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2509  0.890356
2510  0.906336
2511  0.810826
2512  0.812909
2513  0.766020

[2514 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2461  0.480182
2462  0.453247
2463  0.436355
2464  0.571115
2465  0.578179

[2466 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2477  0.401154
2478  0.451228
2479  0.466688
2480  0.453272
2481  0.479480

[2482 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2530  0.732165
2531  0.751042
2532  0.764029
2533  0.796782
2534  1.016848

[2535 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2445  0.715360
2446  0.697860
2447  0.700611
2448  0.717285
2449  0.721186

[2450 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2387  0.993434
2388  1.170521
2389  1.220265
2390  1.369879
2391  1.398332

[2392 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2396  0.509405
2397  0.466166
2398  0.512741
2399  0.486583
2400  0.489598

[2401 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2224  1.246736
2225  1.256414
2226  1.298145
2227  1.327001
2228  1.150401

[2229 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2530  0.833639
2531  0.805359
2532  0.803341
2533  0.712496
2534  0.685904

[2535 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2361  1.587900
2362  1.646367
2363  1.597054
2364  1.539584
2365  1.363844

[2366 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2402  0.449910
2403  0.497784
2404  0.483017
2405  0.427793
2406  0.385266

[2407 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2090  0.154930
2091  0.228830
2092  0.256496
2093  0.296312
2094  0.287475

[2095 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2351  0.763212
2352  0.768385
2353  0.774679
2354  0.786503
2355  0.771263

[2356 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2530  0.307749
2531  0.281893
2532  0.345652
2533  0.322812
2534  0.424593

[2535 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2534  1.012658
2535  0.983090
2536  1.018592
2537  0.920488
2538  1.026062

[2539 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2410  1.305924
2411  1.282298
2412  1.345648
2413  1.415195
2414  1.357206

[2415 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2489  0.457984
2490  0.470306
2491  0.451851
2492  0.476763
2493  0.480990

[2494 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2462  1.234061
2463  1.201933
2464  1.201631
2465  1.179578
2466  1.144764

[2467 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2537  0.694519
2538  0.676490
2539  0.622440
2540  0.544780
2541  0.548006

[2542 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2497  0.558234
2498  0.557405
2499  0.527992
2500  0.478380
2501  0.470393

[2502 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2534  0.213651
2535  0.200188
2536  0.218621
2537  0.271546
2538  0.334200

[2539 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2510  0.840388
2511  0.799578
2512  0.758657
2513  0.829664
2514  0.842949

[2515 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2398  0.149687
2399  0.113843
2400  0.262540
2401  0.700013
2402  0.589731

[2403 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2436  1.285410
2437  1.252872
2438  1.177034
2439  1.183691
2440  0.931970

[2441 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2333  0.229012
2334  0.202658
2335  0.172450
2336  0.100407
2337  0.022307

[2338 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2441  0.348131
2442  0.309020
2443  0.299216
2444  0.460753
2445  0.424240

[2446 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2452  0.934718
2453  0.917039
2454  0.894016
2455  1.006961
2456  0.912115

[2457 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1820  0.325909
1821  0.239655
1822  0.054885
1823  0.029435
1824 -0.004621

[1825 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2376  0.883309
2377  0.871423
2378  0.793182
2379  0.747484
2380  0.692571

[2381 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2348  0.734977
2349  0.738838
2350  0.757841
2351  0.746344
2352  0.760410

[2353 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2496  0.615625
2497  0.608446
2498  0.571161
2499  0.545239
2500  0.710432

[2501 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2463  1.181923
2464  1.124082
2465  1.124859
2466  1.343902
2467  1.291241

[2468 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2506  1.089169
2507  1.068445
2508  1.186524
2509  1.282831
2510  1.177589

[2511 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2505  0.874929
2506  0.894398
2507  0.845549
2508  0.890049
2509  0.641496

[2510 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2522  0.925694
2523  0.971689
2524  0.965655
2525  0.961711
2526  0.900217

[2527 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2526  0.717753
2527  0.693572
2528  0.714556
2529  0.675817
2530  0.675072

[2531 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2406  1.621720
2407  1.518242
2408  1.337396
2409  1.458917
2410  1.535323

[2411 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2294  0.559626
2295  0.570205
2296  0.544778
2297  0.497297
2298  0.445392

[2299 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2540  0.396501
2541  0.419894
2542  0.409033
2543  0.462522
2544  0.483618

[2545 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2251  1.358655
2252  0.930534
2253  1.001756
2254  0.877520
2255  0.499931

[2256 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2440  1.255308
2441  1.279054
2442  1.313187
2443  1.211452
2444  1.257017

[2445 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2515  1.146644
2516  1.095464
2517  1.113098
2518  1.197878
2519  1.247947

[2520 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2363  0.722431
2364  0.721144
2365  0.713580
2366  0.764168
2367  0.551830

[2368 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2336  0.204778
2337  0.205904
2338  0.218598
2339  0.166153
2340  0.132973

[2341 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2487  1.162825
2488  1.210723
2489  1.232145
2490  1.260428
2491  1.181393

[2492 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2073  0.682972
2074  0.676120
2075  0.677865
2076  0.755968
2077  0.741878

[2078 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2503  1.444831
2504  1.515028
2505  1.634105
2506  1.615104
2507  1.717757

[2508 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2419  0.861509
2420  0.879619
2421  0.874696
2422  0.966193
2423  0.900327

[2424 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2387  0.813734
2388  0.858380
2389  0.856711
2390  0.909323
2391  0.850639

[2392 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2518  0.481947
2519  0.479953
2520  0.480015
2521  0.503969
2522  0.501911

[2523 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2345  0.520347
2346  0.511232
2347  0.548867
2348  0.549751
2349  0.545931

[2350 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2388  1.118305
2389  1.109059
2390  1.134252
2391  1.105504
2392  1.043832

[2393 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2537  0.665769
2538  0.662982
2539  0.663677
2540  0.611844
2541  0.578449

[2542 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2443  0.713838
2444  0.686917
2445  0.681233
2446  0.641081
2447  0.583290

[2448 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2478  0.863321
2479  0.846806
2480  0.844246
2481  0.908264
2482  0.918319

[2483 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2448  1.237557
2449  1.186426
2450  1.218426
2451  1.232794
2452  1.157400

[2453 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2435  0.449013
2436  0.440787
2437  0.457831
2438  0.422465
2439  0.424157

[2440 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2494  1.392817
2495  1.418408
2496  1.426998
2497  1.746178
2498  1.627697

[2499 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2523  0.831603
2524  0.934806
2525  0.891966
2526  0.971445
2527  0.894811

[2528 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2507  2.024902
2508  1.988960
2509  2.038785
2510  2.068296
2511  1.961209

[2512 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2257  2.109230
2258  2.070243
2259  2.074089
2260  1.988436
2261  1.907035

[2262 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2537  0.372572
2538  0.376914
2539  0.416393
2540  0.376500
2541  0.394081

[2542 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2364  0.454046
2365  0.471703
2366  0.430351
2367  0.384202
2368  0.299582

[2369 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2303  0.950965
2304  0.942740
2305  0.976478
2306  0.957748
2307  0.927282

[2308 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2518  2.321093
2519  2.293134
2520  2.311803
2521  2.357191
2522  2.184102

[2523 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2516  0.925257
2517  0.926853
2518  0.942776
2519  0.919106
2520  0.884692

[2521 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2510  0.749481
2511  0.774699
2512  0.646787
2513  0.691584
2514  0.696636

[2515 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2450  0.639064
2451  0.605738
2452  0.643659
2453  0.647797
2454  0.634099

[2455 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2532  1.127412
2533  1.077075
2534  1.075941
2535  1.054221
2536  1.002310

[2537 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2528  0.245849
2529  0.403379
2530  0.334414
2531  0.424797
2532  0.500600

[2533 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2349  0.962374
2350  0.926601
2351  0.949782
2352  0.881876
2353  0.784740

[2354 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2442  1.003121
2443  0.985636
2444  0.993865
2445  1.004831
2446  1.006011

[2447 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2267  0.817541
2268  0.745602
2269  0.785477
2270  0.775363
2271  0.784006

[2272 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2538  0.652418
2539  0.639178
2540  0.639265
2541  0.628704
2542  0.652650

[2543 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2536  0.911260
2537  0.885015
2538  0.927313
2539  0.935977
2540  0.879673

[2541 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2454  0.834223
2455  0.759504
2456  0.772103
2457  0.768456
2458  0.341881

[2459 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2468  0.441768
2469  0.592868
2470  0.493564
2471  0.669026
2472  0.642974

[2473 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2509  1.106514
2510  1.103531
2511  1.122588
2512  1.096054
2513  1.013564

[2514 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2391  0.965130
2392  0.985291
2393  1.032752
2394  1.047769
2395  1.258833

[2396 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2532  1.092123
2533  1.030404
2534  1.048900
2535  1.177645
2536  1.054157

[2537 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2523  1.391042
2524  1.363646
2525  1.420141
2526  1.315905
2527  1.195259

[2528 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2495  0.170309
2496  0.173250
2497  0.145862
2498  0.359046
2499  0.311755

[2500 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2240  1.247994
2241  1.357781
2242  1.381332
2243  1.509855
2244  1.445893

[2245 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2517  0.965031
2518  0.938759
2519  0.932826
2520  0.845036
2521  0.822089

[2522 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2160  1.288506
2161  1.267187
2162  1.293756
2163  1.213097
2164  1.147950

[2165 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2468  0.500029
2469  0.564417
2470  0.592026
2471  0.445347
2472  0.445879

[2473 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2526  1.031929
2527  1.001316
2528  1.004610
2529  0.965998
2530  0.927680

[2531 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2217  0.652748
2218  0.623681
2219  0.638077
2220  0.593281
2221  0.587269

[2222 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2463  0.884612
2464  0.932072
2465  0.958627
2466  0.998230
2467  0.933389

[2468 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2444  0.340597
2445  0.382435
2446  0.419373
2447  0.331658
2448  0.222790

[2449 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1213  0.572902
1214  0.588357
1215  0.527648
1216  0.752371
1217  0.627078

[1218 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1857  1.255952
1858  0.967101
1859  0.978912
1860  0.873523
1861  0.696773

[1862 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2442 -0.377266
2443 -0.420121
2444 -0.405534
2445 -0.475776
2446 -0.484203

[2447 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2377  0.274561
2378  0.264316
2379  0.294351
2380  0.273740
2381  0.254970

[2382 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2402  0.413403
2403  0.391886
2404  0.400607
2405  0.508817
2406  0.513891

[2407 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2319  0.444619
2320  0.468081
2321  0.513939
2322  0.436131
2323  0.387242

[2324 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2453  1.301562
2454  1.296308
2455  1.334157
2456  1.282473
2457  1.219901

[2458 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2299  0.369342
2300  0.337836
2301  0.422727
2302  0.472234
2303  0.532519

[2304 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2168  1.348552
2169  1.319415
2170  1.365953
2171  1.382868
2172  1.395847

[2173 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2509  0.551489
2510  0.546126
2511  0.541098
2512  0.615730
2513  0.590905

[2514 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2194  0.516057
2195  0.494030
2196  0.499237
2197  0.485319
2198  0.425770

[2199 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2394  0.922731
2395  0.941681
2396  0.950740
2397  0.882613
2398  0.952806

[2399 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2538  0.574240
2539  0.573663
2540  0.607622
2541  0.545589
2542  0.646697

[2543 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2506  1.404802
2507  1.384030
2508  1.385716
2509  1.333889
2510  1.209933

[2511 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2416  0.612164
2417  0.628001
2418  0.578782
2419  0.537525
2420  0.338245

[2421 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2428  0.536853
2429  0.514362
2430  0.494933
2431  0.449539
2432  0.511657

[2433 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2367  0.399828
2368  0.368761
2369  0.325495
2370  0.290783
2371  0.256640

[2372 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2268  0.364874
2269  0.306300
2270  0.308187
2271  0.311106
2272  0.243271

[2273 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2526  0.563074
2527  0.520321
2528  0.541545
2529  0.559795
2530  0.545427

[2531 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2399  0.495686
2400  0.517751
2401  0.518049
2402  0.607872
2403  0.542688

[2404 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2344  0.790065
2345  0.841249
2346  0.858147
2347  0.878912
2348  0.825248

[2349 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2533  0.664602
2534  0.622890
2535  0.616793
2536  0.625112
2537  0.591183

[2538 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2490  0.576695
2491  0.557878
2492  0.553833
2493  0.566835
2494  0.546141

[2495 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2488  1.555948
2489  1.529167
2490  1.580948
2491  1.505887
2492  1.483530

[2493 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2474  1.066444
2475  1.048987
2476  1.083432
2477  0.967735
2478  1.054992

[2479 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2297  0.878799
2298  0.878480
2299  0.869483
2300  0.833086
2301  0.943731

[2302 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2335  0.544676
2336  0.596161
2337  0.609505
2338  0.514094
2339  0.492877

[2340 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2501  1.541528
2502  1.529858
2503  1.528536
2504  1.387955
2505  1.423212

[2506 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2499  0.530384
2500  0.522223
2501  0.532917
2502  0.504021
2503  0.534736

[2504 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2537  0.267791
2538  0.235735
2539  0.228168
2540  0.239852
2541  0.231067

[2542 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2269  0.649813
2270  0.694102
2271  0.654497
2272  0.695357
2273  0.648842

[2274 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2374  1.162998
2375  1.142835
2376  1.165499
2377  1.113850
2378  1.025121

[2379 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2363  0.607878
2364  0.655685
2365  0.673580
2366  0.687843
2367  0.638881

[2368 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2528  1.778512
2529  1.779269
2530  1.812877
2531  1.754399
2532  1.614582

[2533 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2517  0.264833
2518  0.227670
2519  0.208931
2520  0.199498
2521  0.173625

[2522 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2499  1.158518
2500  1.122896
2501  1.164464
2502  1.113449
2503  1.309891

[2504 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2409  0.813296
2410  0.638169
2411  0.683212
2412  0.688958
2413  0.605235

[2414 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2400  0.728176
2401  0.703946
2402  0.730789
2403  0.704022
2404  0.691407

[2405 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2532  0.712835
2533  0.716846
2534  0.737427
2535  0.788815
2536  0.807797

[2537 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2230  0.556678
2231  0.546119
2232  0.606001
2233  0.672303
2234  0.661510

[2235 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2528  0.499304
2529  0.498969
2530  0.514095
2531  0.417779
2532  0.417741

[2533 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2329  0.893570
2330  1.069147
2331  1.014979
2332  1.280256
2333  1.207970

[2334 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2535  0.983004
2536  0.868201
2537  0.880768
2538  0.803312
2539  0.788409

[2540 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2366  0.298954
2367  0.260696
2368  0.221711
2369  0.043200
2370  0.024643

[2371 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2467  1.495931
2468  1.529888
2469  1.504399
2470  1.566231
2471  1.439639

[2472 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2516  0.426617
2517  0.606628
2518  0.538142
2519  0.583025
2520  0.476174

[2521 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2540  0.823497
2541  0.819375
2542  0.795602
2543  0.717922
2544  0.807449

[2545 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2394  2.383267
2395  2.335779
2396  2.271456
2397  2.119941
2398  1.928615

[2399 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2516  0.738364
2517  0.708303
2518  0.659724
2519  0.661045
2520  0.954167

[2521 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2433  0.118338
2434  0.149485
2435  0.137944
2436  0.060789
2437  0.025064

[2438 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2512  0.849204
2513  0.863049
2514  0.831592
2515  0.902704
2516  0.791548

[2517 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2440  0.699077
2441  0.683565
2442  0.698834
2443  0.651314
2444  0.592007

[2445 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2393  1.504892
2394  1.440085
2395  1.540509
2396  1.470124
2397  1.324789

[2398 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2448  1.130178
2449  1.157433
2450  1.198246
2451  1.140054
2452  1.016839

[2453 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2434  0.976557
2435  0.943882
2436  0.741883
2437  0.717544
2438  0.610242

[2439 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2486  0.764656
2487  0.727093
2488  0.737243
2489  0.709365
2490  0.750255

[2491 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2115 -0.003062
2116 -0.071087
2117 -0.037070
2118 -0.038839
2119 -0.051796

[2120 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2532  0.816872
2533  0.802620
2534  0.807918
2535  0.761326
2536  0.702381

[2537 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2398  0.893067
2399  0.896086
2400  0.912110
2401  1.006611
2402  1.233714

[2403 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2080  0.827550
2081  0.816946
2082  0.869363
2083  0.838721
2084  0.725636

[2085 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2527  0.954447
2528  0.915388
2529  0.914480
2530  0.910354
2531  0.838179

[2532 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2419  0.158990
2420  0.110450
2421 -0.010931
2422 -0.012298
2423 -0.030537

[2424 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2528  1.563440
2529  1.599361
2530  1.621311
2531  1.660885
2532  1.563622

[2533 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2203  0.729142
2204  0.652481
2205  0.571289
2206  0.532829
2207  0.454257

[2208 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2494  0.693725
2495  0.681795
2496  0.687850
2497  0.644257
2498  0.614057

[2499 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2428  0.599452
2429  0.593456
2430  0.575805
2431  0.539595
2432  0.554732

[2433 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2530  0.706632
2531  0.646122
2532  0.621930
2533  0.631969
2534  0.503784

[2535 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2388  0.826766
2389  0.819519
2390  0.859083
2391  0.837017
2392  0.881089

[2393 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2460 -0.327804
2461 -0.219180
2462 -0.234235
2463 -0.130348
2464 -0.126055

[2465 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2527  1.555128
2528  1.500531
2529  1.371880
2530  1.352931
2531  1.164166

[2532 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2380  0.879839
2381  1.009256
2382  0.808949
2383  0.721580
2384  0.539725

[2385 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2089  1.289421
2090  1.217837
2091  1.165433
2092  1.261500
2093  1.142207

[2094 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2230 -0.163941
2231 -0.057581
2232 -0.021698
2233 -0.056984
2234 -0.010031

[2235 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2192  0.039028
2193  0.142426
2194  0.067652
2195  0.163533
2196  0.181816

[2197 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2397  1.147598
2398  1.137666
2399  1.176696
2400  1.115861
2401  1.051720

[2402 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2484  1.244406
2485  1.215935
2486  1.220891
2487  1.212766
2488  1.120070

[2489 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2502  0.628134
2503  0.601554
2504  0.607448
2505  0.597293
2506  0.575100

[2507 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2363  0.757699
2364  0.778179
2365  0.805503
2366  0.784684
2367  0.731672

[2368 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2443  0.951224
2444  0.903587
2445  0.932882
2446  0.942765
2447  1.014082

[2448 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2143  0.550116
2144  0.348783
2145  0.366221
2146  0.370542
2147  0.252826

[2148 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2530  1.004844
2531  1.012466
2532  0.983838
2533  0.875865
2534  0.742116

[2535 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2464  0.357915
2465  0.376105
2466  0.386318
2467  0.372326
2468  0.347684

[2469 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2453  1.330956
2454  1.298860
2455  1.325466
2456  1.304075
2457  1.246473

[2458 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2376  0.653395
2377  0.794496
2378  0.842775
2379  0.673595
2380  0.486239

[2381 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2288 -0.055287
2289 -0.152270
2290 -0.052419
2291 -0.158982
2292  0.047307

[2293 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2331  0.756068
2332  0.849034
2333  0.836070
2334  0.942863
2335  0.331929

[2336 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2338  0.923098
2339  0.844323
2340  0.854081
2341  0.859016
2342  0.776040

[2343 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2200  0.878131
2201  1.115312
2202  1.305912
2203  1.388555
2204  1.063329

[2205 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2406  0.756282
2407  0.698659
2408  0.786714
2409  0.799096
2410  0.683047

[2411 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2326 -0.011867
2327 -0.028419
2328  0.010835
2329  0.141906
2330  0.148751

[2331 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2359  0.096871
2360  0.104399
2361  0.200916
2362  0.086939
2363  0.200690

[2364 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2406  0.277761
2407  0.218766
2408  0.260335
2409  0.264560
2410  0.281482

[2411 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2527  0.544420
2528  0.499994
2529  0.556164
2530  0.499266
2531  0.457694

[2532 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2335  0.928573
2336  0.990248
2337  0.949127
2338  1.104751
2339  1.086881

[2340 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2512  0.476230
2513  0.511831
2514  0.500779
2515  0.604513
2516  0.564948

[2517 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2504  0.512406
2505  0.520002
2506  0.544913
2507  0.485171
2508  0.452768

[2509 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2249  0.654547
2250  0.653915
2251  0.655870
2252  0.644225
2253  0.563472

[2254 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2491  0.823886
2492  0.803494
2493  0.799040
2494  0.730700
2495  0.653142

[2496 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2369  0.946058
2370  1.028643
2371  1.033749
2372  1.089753
2373  1.164188

[2374 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2224  1.668794
2225  1.666591
2226  1.713544
2227  1.626942
2228  1.546266

[2229 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2381  0.274738
2382  0.273675
2383  0.321194
2384  0.259812
2385  0.291815

[2386 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2412  1.559995
2413  1.524769
2414  1.507028
2415  1.393169
2416  1.280870

[2417 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2534  0.778107
2535  0.762957
2536  0.756200
2537  0.710740
2538  0.646384

[2539 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2540 -0.057191
2541 -0.075920
2542 -0.036214
2543 -0.062545
2544  0.003757

[2545 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2421  0.090013
2422  0.079848
2423  0.075704
2424  0.164536
2425  0.136106

[2426 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2519  0.727673
2520  0.708668
2521  0.711521
2522  0.681012
2523  0.711283

[2524 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2494 -0.574665
2495 -0.443809
2496 -0.449842
2497 -0.543343
2498 -0.442971

[2499 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2520  2.097597
2521  1.992816
2522  2.005988
2523  1.963388
2524  1.848653

[2525 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2538  0.428030
2539  0.413947
2540  0.423120
2541  0.409799
2542  0.404262

[2543 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2101  0.578732
2102  0.578670
2103  0.579387
2104  0.580579
2105  0.585445

[2106 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2391  0.755498
2392  0.758955
2393  0.797553
2394  0.706192
2395  0.688362

[2396 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2540  0.816342
2541  0.805684
2542  0.823029
2543  0.749149
2544  0.682500

[2545 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2337  0.895276
2338  0.887861
2339  0.848525
2340  0.800130
2341  0.751916

[2342 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2229  0.819891
2230  0.811495
2231  0.844920
2232  0.799479
2233  0.738044

[2234 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2537  0.952064
2538  0.974721
2539  0.979272
2540  0.960452
2541  0.836743

[2542 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2284  0.656574
2285  0.674397
2286  0.701997
2287  0.622839
2288  0.600937

[2289 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2476  0.977329
2477  1.038507
2478  1.055670
2479  1.015012
2480  1.068680

[2481 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2517  0.569950
2518  0.549411
2519  0.558232
2520  0.522840
2521  0.528343

[2522 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2461  0.681849
2462  0.895442
2463  0.811020
2464  0.810518
2465  0.667230

[2466 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2498  0.370116
2499  0.383647
2500  0.363821
2501  0.330914
2502  0.282673

[2503 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2485  0.762422
2486  0.730147
2487  0.796536
2488  0.749439
2489  0.718532

[2490 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2518  0.518221
2519  0.476624
2520  0.390605
2521  0.475950
2522  0.386427

[2523 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2484  0.255513
2485  0.218853
2486  0.262268
2487  0.266730
2488  0.322871

[2489 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2486  0.429631
2487  0.427232
2488  0.368454
2489  0.375428
2490  0.291504

[2491 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2501  0.932324
2502  0.913756
2503  0.933173
2504  0.914374
2505  0.878276

[2506 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2477  0.658963
2478  0.642382
2479  0.673225
2480  0.685681
2481  0.675506

[2482 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2369 -0.187156
2370 -0.075431
2371 -0.019334
2372 -0.090685
2373 -0.126486

[2374 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2435  0.996020
2436  1.003342
2437  1.002508
2438  0.989581
2439  0.920232

[2440 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2400  0.947117
2401  0.905960
2402  0.946565
2403  1.017730
2404  0.999321

[2405 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2456  0.746355
2457  0.725245
2458  0.720695
2459  0.694973
2460  0.680344

[2461 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2383  1.120666
2384  1.142413
2385  1.162122
2386  1.099201
2387  1.068911

[2388 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2389  0.471067
2390  0.517907
2391  0.533136
2392  0.516079
2393  0.523586

[2394 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2324  1.243934
2325  1.182378
2326  1.232421
2327  1.306190
2328  1.262573

[2329 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2525  0.316207
2526  0.346009
2527  0.312836
2528  0.408765
2529  0.260272

[2530 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2403  1.213811
2404  1.176389
2405  1.131689
2406  1.110104
2407  1.055894

[2408 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2519  0.853473
2520  0.880845
2521  0.890772
2522  0.992289
2523  1.004720

[2524 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2433  0.344035
2434  0.324177
2435  0.325348
2436  0.344710
2437  0.313436

[2438 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2536  0.482181
2537  0.464070
2538  0.336430
2539  0.120345
2540 -0.254550

[2541 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2465  0.590528
2466  0.620187
2467  0.643757
2468  0.533708
2469  0.508047

[2470 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2532  0.714004
2533  0.722919
2534  0.745266
2535  0.693988
2536  0.711208

[2537 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2254  0.847067
2255  0.830457
2256  0.744235
2257  0.725581
2258  0.553225

[2259 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2529  0.517124
2530  0.510742
2531  0.531346
2532  0.543405
2533  0.539163

[2534 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2532  0.775779
2533  0.753504
2534  0.717577
2535  0.704718
2536  0.668607

[2537 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2405  1.579584
2406  1.607220
2407  1.619812
2408  1.565597
2409  1.591786

[2410 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2504  0.714701
2505  0.674311
2506  0.688994
2507  0.625856
2508  0.609189

[2509 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2517  0.373367
2518  0.423501
2519  0.432721
2520  0.479445
2521  0.326577

[2522 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2413  1.285002
2414  1.240588
2415  1.259367
2416  1.376860
2417  1.364777

[2418 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2108  0.076522
2109  0.243336
2110  0.245645
2111  0.512714
2112  0.446049

[2113 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2289  1.043416
2290  0.987118
2291  0.952929
2292  0.838695
2293  0.607552

[2294 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2535  0.471506
2536  0.427209
2537  0.410461
2538  0.412667
2539  0.348448

[2540 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2494  0.418124
2495  0.472946
2496  0.479765
2497  0.480778
2498  0.536961

[2499 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2035  2.064247
2036  1.952444
2037  2.136636
2038  2.275710
2039  2.461969

[2040 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2195  0.337162
2196  0.441400
2197  0.419927
2198  0.341286
2199  0.307506

[2200 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2541  0.392085
2542  0.391316
2543  0.399052
2544  0.396415
2545  0.402363

[2546 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2415  0.724689
2416  0.757995
2417  0.750064
2418  0.777784
2419  0.738253

[2420 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2539  0.730890
2540  0.696145
2541  0.747649
2542  0.681227
2543  0.704847

[2544 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2459  0.710912
2460  0.682882
2461  0.723051
2462  0.658837
2463  0.753181

[2464 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2518  0.803841
2519  0.820939
2520  0.822989
2521  0.848892
2522  0.984547

[2523 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2528  0.685887
2529  0.636996
2530  0.615202
2531  0.609070
2532  0.616357

[2533 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2530  1.069224
2531  1.083901
2532  1.085752
2533  1.022581
2534  0.976576

[2535 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2324  0.241106
2325  0.252133
2326  0.261566
2327  0.256785
2328  0.246936

[2329 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2524  0.145995
2525  0.179669
2526  0.172256
2527  0.163615
2528  0.238535

[2529 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2413  1.779952
2414  1.732586
2415  1.734631
2416  1.640057
2417  1.433313

[2418 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2415  0.778529
2416  0.765061
2417  0.768549
2418  0.736214
2419  0.762366

[2420 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2355  0.627899
2356  0.658416
2357  0.676480
2358  0.746655
2359  0.783670

[2360 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2499  0.042456
2500  0.037552
2501  0.028657
2502 -0.039651
2503 -0.027873

[2504 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2284  0.830481
2285  0.775866
2286  0.756294
2287  0.725029
2288  0.686685

[2289 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2514  0.795198
2515  0.790616
2516  0.727544
2517  0.705577
2518  0.577394

[2519 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2498  1.028744
2499  1.044465
2500  1.072860
2501  0.906556
2502  0.858378

[2503 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2201  1.278003
2202  1.287908
2203  1.207329
2204  1.039332
2205  1.306755

[2206 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2384  0.867595
2385  0.856269
2386  0.849780
2387  0.818478
2388  0.803276

[2389 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2493  1.220212
2494  1.223927
2495  1.250191
2496  1.235044
2497  1.296836

[2498 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2518  0.622235
2519  0.630674
2520  0.655244
2521  0.633063
2522  0.599990

[2523 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2512  1.356851
2513  1.303327
2514  1.346877
2515  1.210110
2516  1.217536

[2517 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2226  0.926474
2227  0.913622
2228  0.941551
2229  0.927524
2230  1.027625

[2231 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2535  0.527666
2536  0.517341
2537  0.533641
2538  0.525799
2539  0.551674

[2540 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2503  0.815315
2504  0.793620
2505  0.810881
2506  0.753446
2507  0.592738

[2508 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2495  0.381324
2496  0.362206
2497  0.355294
2498  0.363609
2499  0.346632

[2500 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2507  1.193249
2508  1.169996
2509  1.194512
2510  1.211649
2511  1.161541

[2512 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2434  0.950482
2435  1.065921
2436  1.029834
2437  0.833114
2438  0.704921

[2439 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2491 -0.002193
2492  0.261769
2493  0.671594
2494  0.611921
2495  0.575202

[2496 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2450  1.450263
2451  1.450416
2452  1.469586
2453  1.413522
2454  1.315628

[2455 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2466  0.759776
2467  0.773240
2468  0.756677
2469  0.740109
2470  0.682895

[2471 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2228  0.807070
2229  0.730120
2230  0.780242
2231  0.764218
2232  0.626351

[2233 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2440  0.956567
2441  0.922433
2442  0.914946
2443  0.986429
2444  0.908296

[2445 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2523  1.668995
2524  1.682761
2525  1.718608
2526  1.570196
2527  1.476038

[2528 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2529  0.844754
2530  0.731126
2531  0.771098
2532  1.038637
2533  0.939517

[2534 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2532  1.007019
2533  0.990219
2534  0.965361
2535  0.934294
2536  0.991676

[2537 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2399  1.300738
2400  1.321468
2401  1.282119
2402  1.224902
2403  1.182878

[2404 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2283  0.987296
2284  0.966470
2285  0.871496
2286  0.916408
2287  0.834313

[2288 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2473  0.393892
2474  0.457349
2475  0.467665
2476  0.743109
2477  0.722813

[2478 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2536  0.745871
2537  0.784941
2538  0.793245
2539  0.759465
2540  0.733553

[2541 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2518  0.926684
2519  0.915782
2520  0.916414
2521  0.939055
2522  0.880488

[2523 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2370  1.164377
2371  1.148071
2372  1.177086
2373  1.168770
2374  1.149333

[2375 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2474  0.472048
2475  0.434916
2476  0.385435
2477  0.392476
2478  0.211681

[2479 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2539  0.648488
2540  0.811630
2541  0.787403
2542  0.854294
2543  0.761555

[2544 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2334  0.728421
2335  0.702584
2336  0.682859
2337  0.662339
2338  0.609516

[2339 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2453  0.804374
2454  0.819617
2455  0.862215
2456  0.783825
2457  0.759927

[2458 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2313  0.027404
2314  0.033721
2315  0.064500
2316 -0.032801
2317 -0.045176

[2318 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2513  0.492505
2514  0.476922
2515  0.497476
2516  0.566825
2517  0.663063

[2518 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2538  0.339470
2539  0.311951
2540  0.321731
2541  0.291980
2542  0.293661

[2543 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2360  2.035422
2361  1.985438
2362  1.964419
2363  1.936591
2364  1.752204

[2365 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2187  1.288502
2188  1.193317
2189  1.223708
2190  1.139931
2191  1.052875

[2192 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2484  1.392156
2485  1.444680
2486  1.442780
2487  1.350090
2488  1.165007

[2489 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2096  0.234136
2097  0.188075
2098 -0.000023
2099 -0.099401
2100  0.084786

[2101 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2507  0.722910
2508  0.734244
2509  0.748307
2510  0.738868
2511  0.742150

[2512 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2533  1.011910
2534  1.033137
2535  1.041478
2536  1.175043
2537  1.456767

[2538 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2128  0.746069
2129  0.836829
2130  0.889538
2131  0.819918
2132  0.664326

[2133 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2538  0.875272
2539  0.909407
2540  0.912698
2541  1.028700
2542  0.985073

[2543 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2417  0.642405
2418  0.634764
2419  0.690875
2420  0.624762
2421  0.570229

[2422 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2516  0.658187
2517  0.655274
2518  0.653297
2519  0.619453
2520  0.597993

[2521 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2394  0.552682
2395  0.584525
2396  0.579484
2397  0.645931
2398  0.616856

[2399 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2394  0.909941
2395  0.892569
2396  0.920105
2397  0.942256
2398  0.915683

[2399 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2512  1.443543
2513  1.412644
2514  1.386883
2515  1.290973
2516  1.245379

[2517 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2290  0.391688
2291  0.380654
2292  0.418537
2293  0.368786
2294  0.375505

[2295 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2287  0.291259
2288  0.293771
2289  0.306622
2290  0.260485
2291  0.312772

[2292 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2489  0.338956
2490  0.313148
2491  0.325885
2492  0.362972
2493  0.359758

[2494 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2427  1.169796
2428  1.311470
2429  1.297797
2430  1.270601
2431  1.282417

[2432 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2446  1.312550
2447  1.280670
2448  1.312383
2449  1.325314
2450  1.356832

[2451 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2486  0.565200
2487  0.569355
2488  0.590802
2489  0.616313
2490  0.602708

[2491 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2295  0.421142
2296  0.450390
2297  0.490527
2298  0.387197
2299  0.336784

[2300 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2439  0.328895
2440  0.342344
2441  0.326423
2442  0.330073
2443  0.308332

[2444 rows x 1 columns]
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2490  0.716649
2491  0.705696
2492  0.733883
2493  0.767227
2494  0.748851

[2495 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2515  1.109562
2516  1.097428
2517  1.130197
2518  1.043749
2519  0.987509

[2520 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2395  1.130874
2396  1.083261
2397  1.105172
2398  1.104462
2399  1.037417

[2400 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2282  0.466888
2283  0.455134
2284  0.466219
2285  0.432129
2286  0.458062

[2287 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2501  1.034066
2502  1.039628
2503  1.009680
2504  0.965470
2505  0.893577

[2506 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2476  1.561385
2477  1.599094
2478  1.597206
2479  1.910414
2480  1.805969

[2481 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2526  1.326771
2527  1.290494
2528  1.374656
2529  1.341570
2530  1.276723

[2531 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2463  0.743313
2464  0.795152
2465  0.849897
2466  0.749521
2467  0.422448

[2468 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2451  0.028293
2452 -0.073420
2453 -0.052832
2454 -0.112192
2455 -0.129765

[2456 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2324  0.678186
2325  0.667645
2326  0.633091
2327  0.814277
2328  0.764598

[2329 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2411  0.266183
2412  0.292589
2413  0.312393
2414  0.394457
2415  0.331597

[2416 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2376  0.617583
2377  0.628231
2378  0.610303
2379  0.656403
2380  0.565972

[2381 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2494  0.449539
2495  0.457767
2496  0.463523
2497  0.548650
2498  0.617246

[2499 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2269  0.370199
2270  0.456997
2271  0.484608
2272  0.330088
2273  0.310408

[2274 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2517  1.219308
2518  1.171739
2519  1.210971
2520  1.141351
2521  1.193458

[2522 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2531  1.276264
2532  1.286806
2533  1.313738
2534  1.258607
2535  1.331521

[2536 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2436  0.744333
2437  0.741691
2438  0.752473
2439  0.766641
2440  0.715728

[2441 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2424  0.273771
2425  0.272183
2426  0.255359
2427  0.420409
2428  0.380682

[2429 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2306  0.812603
2307  0.806080
2308  0.805455
2309  0.752081
2310  0.715793

[2311 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2517  0.430842
2518  0.391807
2519  0.389595
2520  0.383000
2521  0.352082

[2522 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2521  0.790109
2522  0.825445
2523  0.818328
2524  0.846398
2525  0.844058

[2526 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2393  2.087950
2394  2.033807
2395  1.979976
2396  1.865411
2397  1.883769

[2398 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2525  0.795078
2526  0.725009
2527  0.758081
2528  0.630080
2529  0.643346

[2530 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2372  0.842096
2373  0.849514
2374  0.845315
2375  0.817435
2376  0.792804

[2377 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2415  1.782584
2416  1.759592
2417  1.753555
2418  1.772561
2419  1.615627

[2420 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2460  0.159598
2461  0.152076
2462  0.129883
2463  0.142933
2464  0.153305

[2465 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2480  1.441587
2481  1.452682
2482  1.477160
2483  1.554689
2484  1.619819

[2485 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2489  0.914252
2490  0.884786
2491  0.901924
2492  0.939417
2493  0.913190

[2494 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1931  0.665568
1932  0.663473
1933  0.689342
1934  0.650198
1935  0.665230

[1936 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2539  1.132307
2540  1.124353
2541  1.105706
2542  1.004600
2543  0.926042

[2544 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2405  1.216887
2406  1.169732
2407  1.166383
2408  1.135494
2409  1.075588

[2410 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2522  1.816130
2523  1.881109
2524  1.735008
2525  1.603377
2526  1.374667

[2527 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2459  1.577474
2460  1.560457
2461  1.583206
2462  1.540427
2463  1.500217

[2464 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2395  0.580889
2396  0.575238
2397  0.560128
2398  0.590590
2399  0.554550

[2400 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2026  0.319217
2027  0.402669
2028  0.322243
2029  0.491714
2030  0.325405

[2031 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2522  1.310517
2523  1.306750
2524  1.350040
2525  1.303511
2526  1.230301

[2527 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2377  0.818909
2378  0.838557
2379  0.841001
2380  0.827654
2381  1.003601

[2382 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2529  0.952925
2530  0.962807
2531  0.958670
2532  1.025836
2533  0.995539

[2534 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2335  1.015861
2336  0.936634
2337  0.742835
2338  0.594071
2339  0.522989

[2340 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2358  0.876914
2359  0.858643
2360  0.898495
2361  0.853051
2362  0.819459

[2363 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2530  0.708152
2531  0.677429
2532  0.640028
2533  0.684219
2534  0.690976

[2535 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2389  0.724610
2390  0.737657
2391  0.787315
2392  0.783699
2393  0.813584

[2394 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2510  0.889830
2511  0.853556
2512  0.896830
2513  0.856705
2514  0.841451

[2515 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2501  1.250236
2502  1.246662
2503  1.201227
2504  1.221564
2505  1.170909

[2506 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2351  0.986353
2352  0.952964
2353  0.941754
2354  0.864033
2355  0.712795

[2356 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2521  0.384563
2522  0.389134
2523  0.379818
2524  0.404031
2525  0.403685

[2526 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2399  1.399519
2400  1.364201
2401  1.327312
2402  1.261742
2403  1.242900

[2404 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2420  0.642967
2421  0.620798
2422  0.505184
2423  0.504683
2424  0.623211

[2425 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2404  0.255362
2405  0.231058
2406  0.222866
2407  0.418103
2408  0.413747

[2409 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2430  0.506903
2431  0.507301
2432  0.511997
2433  0.508398
2434  0.488343

[2435 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1736  0.290613
1737  0.305730
1738  0.297889
1739  0.339069
1740  0.347680

[1741 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2536  0.520526
2537  0.534377
2538  0.539897
2539  0.535005
2540  0.439736

[2541 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2418  1.020349
2419  1.008119
2420  1.018799
2421  0.893507
2422  0.850786

[2423 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2439  0.332446
2440  0.333505
2441  0.294554
2442  0.238118
2443  0.138837

[2444 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2507  0.430855
2508  0.437738
2509  0.396217
2510  0.324516
2511  0.379484

[2512 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2033  1.118580
2034  1.088025
2035  1.115452
2036  1.097282
2037  1.077043

[2038 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2525  0.243933
2526  0.214389
2527  0.224666
2528  0.185073
2529  0.211473

[2530 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2533  0.723056
2534  0.753193
2535  0.757117
2536  0.735546
2537  0.690778

[2538 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2525  1.009262
2526  0.927316
2527  0.918620
2528  1.094337
2529  1.075960

[2530 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2511  1.236702
2512  1.304381
2513  1.261076
2514  1.333608
2515  1.347314

[2516 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2394  0.784428
2395  0.842938
2396  0.848518
2397  0.836505
2398  0.839974

[2399 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2492  1.950687
2493  1.891547
2494  1.902183
2495  1.759940
2496  1.657378

[2497 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2323  1.159553
2324  1.142692
2325  1.138231
2326  1.053488
2327  0.997682

[2328 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2509  0.956682
2510  0.929853
2511  0.959314
2512  0.916607
2513  0.828689

[2514 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2526  0.698477
2527  0.663040
2528  0.677492
2529  0.637291
2530  0.552972

[2531 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2399  0.789904
2400  0.741279
2401  0.679260
2402  0.722761
2403  0.686757

[2404 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2457  1.097652
2458  1.090165
2459  1.135180
2460  1.075175
2461  1.191775

[2462 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2515  0.781005
2516  0.762889
2517  0.782178
2518  0.666243
2519  0.700483

[2520 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2331  1.273433
2332  1.310376
2333  1.233973
2334  1.272175
2335  1.148818

[2336 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2515  0.556989
2516  0.536181
2517  0.549373
2518  0.548676
2519  0.513571

[2520 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2538  0.393357
2539  0.378477
2540  0.402759
2541  0.389618
2542  0.394564

[2543 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2510  0.325994
2511  0.315648
2512  0.337103
2513  0.286771
2514  0.300122

[2515 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2491  1.309225
2492  1.271397
2493  1.317035
2494  1.352180
2495  1.277679

[2496 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2411  0.700958
2412  0.724543
2413  0.928520
2414  0.857294
2415  0.665635

[2416 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2478  0.937049
2479  0.876892
2480  0.870013
2481  0.924240
2482  0.911503

[2483 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2493  0.488449
2494  0.544438
2495  0.494779
2496  0.434168
2497  0.350480

[2498 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2218  0.197983
2219  0.258183
2220  0.317262
2221  0.459628
2222  0.427438

[2223 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2469  0.728716
2470  0.697972
2471  0.744663
2472  0.726380
2473  0.737721

[2474 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2404  1.270371
2405  1.284143
2406  1.331300
2407  1.286785
2408  1.189641

[2409 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2515  0.068197
2516  0.079938
2517  0.116757
2518  0.121224
2519  0.095435

[2520 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2538  1.110374
2539  1.088621
2540  1.075683
2541  1.042245
2542  1.027131

[2543 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2407 -0.076467
2408 -0.083290
2409 -0.037119
2410 -0.067144
2411  0.020535

[2412 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2520  1.291605
2521  1.400993
2522  1.331942
2523  1.324359
2524  1.098178

[2525 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2455  1.325726
2456  1.369793
2457  1.391657
2458  1.274007
2459  1.113899

[2460 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2512 -0.274931
2513 -0.308371
2514 -0.248027
2515 -0.293276
2516 -0.329497

[2517 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2309  0.655634
2310  0.630380
2311  0.632324
2312  0.591452
2313  0.665678

[2314 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2500  0.419729
2501  0.444302
2502  0.481820
2503  0.450421
2504  0.349166

[2505 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2530  0.523154
2531  0.450561
2532  0.470360
2533  0.398420
2534  0.346614

[2535 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2467  0.878703
2468  0.846892
2469  0.831495
2470  0.895306
2471  0.989089

[2472 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2494  0.652679
2495  0.668059
2496  0.478347
2497  0.451378
2498  0.192884

[2499 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2367  0.659659
2368  0.622669
2369  0.483576
2370  0.508526
2371  0.499467

[2372 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2508  0.882737
2509  0.882341
2510  0.885348
2511  0.808696
2512  0.810992

[2513 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2358 -0.664554
2359 -0.743529
2360 -0.813645
2361 -0.587773
2362 -0.499268

[2363 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2429  0.334669
2430  0.324255
2431  0.388670
2432  0.332921
2433  0.439706

[2434 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2523  0.740526
2524  0.753462
2525  0.707988
2526  0.836145
2527  1.128140

[2528 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2525  1.358721
2526  1.431414
2527  1.479583
2528  1.404166
2529  1.386692

[2530 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2487  1.337147
2488  1.304832
2489  1.262507
2490  1.136253
2491  0.971723

[2492 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2403  0.577826
2404  0.770143
2405  0.742516
2406  0.804201
2407  0.695337

[2408 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2300  0.501897
2301  0.506728
2302  0.539968
2303  0.493752
2304  0.416728

[2305 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2459 -0.015681
2460  0.009977
2461 -0.033181
2462  0.181786
2463  0.171286

[2464 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2515  0.960598
2516  0.974838
2517  0.992536
2518  1.137039
2519  1.180123

[2520 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2414  0.895922
2415  0.879066
2416  0.870697
2417  0.824226
2418  0.792229

[2419 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2475  2.919610
2476  2.875646
2477  2.876051
2478  2.786476
2479  2.539501

[2480 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2350  0.545747
2351  0.582845
2352  0.556548
2353  0.481650
2354  0.481864

[2355 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2537  0.494707
2538  0.470993
2539  0.479661
2540  0.474785
2541  0.626474

[2542 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2526  0.463481
2527  0.436762
2528  0.449577
2529  0.430904
2530  0.417237

[2531 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2493  1.754058
2494  1.670779
2495  1.683798
2496  1.786753
2497  1.717517

[2498 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2415  0.378495
2416  0.361485
2417  0.352459
2418  0.329236
2419  0.357003

[2420 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2305  1.345667
2306  1.321543
2307  1.112805
2308  1.218493
2309  1.064013

[2310 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2390  1.322874
2391  1.299975
2392  1.308124
2393  1.420101
2394  1.220438

[2395 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1372  1.321029
1373  1.259127
1374  1.339404
1375  1.334026
1376  1.116253

[1377 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2522  0.558563
2523  0.610321
2524  0.600143
2525  0.606163
2526  0.655236

[2527 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2437  0.587149
2438  0.567251
2439  0.562167
2440  0.545855
2441  0.504982

[2442 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2312  0.990001
2313  0.970186
2314  0.856882
2315  0.993137
2316  1.258025

[2317 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2538  1.620139
2539  1.477662
2540  1.520248
2541  1.313649
2542  1.332561

[2543 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2460  0.331508
2461  0.295840
2462  0.297763
2463  0.304982
2464  0.312239

[2465 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2494  1.158313
2495  1.159781
2496  1.155456
2497  1.076504
2498  0.967770

[2499 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2541  1.389075
2542  1.357648
2543  1.356349
2544  1.328140
2545  1.115894

[2546 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2316  0.628974
2317  0.589915
2318  0.605099
2319  0.571149
2320  0.623463

[2321 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2412  0.690506
2413  0.723197
2414  0.685679
2415  0.758513
2416  0.686437

[2417 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2460  0.530396
2461  0.509967
2462  0.513207
2463  0.516940
2464  0.510023

[2465 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2221  1.096783
2222  1.104867
2223  1.083804
2224  1.166370
2225  1.087280

[2226 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2466  0.470591
2467  0.444810
2468  0.461499
2469  0.468624
2470  0.498105

[2471 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2477  1.330701
2478  1.336504
2479  1.335456
2480  1.353778
2481  1.216045

[2482 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2372  1.397452
2373  1.358247
2374  1.365815
2375  1.543310
2376  1.415944

[2377 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2382  0.574228
2383  0.574346
2384  0.593368
2385  0.525678
2386  0.478279

[2387 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2538  0.681893
2539  0.664401
2540  0.712380
2541  0.800596
2542  0.857573

[2543 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2232 -0.143267
2233 -0.175557
2234 -0.156992
2235 -0.180432
2236 -0.222118

[2237 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2151  0.722823
2152  0.688298
2153  0.678400
2154  0.627826
2155  0.599286

[2156 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2291  1.060996
2292  1.025831
2293  1.017339
2294  0.932737
2295  0.890355

[2296 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2411  0.438974
2412  0.402672
2413  0.408905
2414  0.361137
2415  0.323688

[2416 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2238  1.062272
2239  1.008132
2240  1.008316
2241  0.964781
2242  0.924049

[2243 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2446  1.201587
2447  1.187300
2448  1.224426
2449  1.172843
2450  1.111822

[2451 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2375  0.548877
2376  0.515750
2377  0.522373
2378  0.573399
2379  0.586569

[2380 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2476  0.751938
2477  0.741124
2478  0.730765
2479  0.695147
2480  0.652717

[2481 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2529  1.404084
2530  1.364438
2531  1.373868
2532  1.298501
2533  1.226730

[2534 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2310  1.717678
2311  1.713256
2312  1.728245
2313  1.617701
2314  1.449582

[2315 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2533  0.974819
2534  0.960416
2535  0.983846
2536  0.994274
2537  1.100175

[2538 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2532  1.202728
2533  1.231664
2534  1.024668
2535  1.186371
2536  1.199066

[2537 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2390  0.452485
2391  0.519726
2392  0.474645
2393  0.581358
2394  0.498308

[2395 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2518  1.464905
2519  1.521288
2520  1.555472
2521  1.557593
2522  1.690906

[2523 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2381  1.450533
2382  1.421344
2383  1.463658
2384  1.356419
2385  1.368298

[2386 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2316  0.862759
2317  0.766015
2318  0.796626
2319  0.695478
2320  0.645688

[2321 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2461  0.033075
2462  0.088073
2463  0.066693
2464  0.141717
2465  0.109613

[2466 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2473 -0.067001
2474 -0.072552
2475 -0.075885
2476 -0.103432
2477 -0.135679

[2478 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2524  0.019868
2525  0.042284
2526 -0.033552
2527 -0.126003
2528 -0.218039

[2529 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2453  0.140723
2454  0.108660
2455  0.091971
2456  0.110362
2457  0.058777

[2458 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2516  0.500091
2517  0.496130
2518  0.537422
2519  0.560015
2520  0.550991

[2521 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2460  1.007387
2461  1.011584
2462  1.012005
2463  1.062767
2464  1.097325

[2465 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2488  0.965434
2489  1.070645
2490  0.900548
2491  0.990824
2492  0.875665

[2493 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2363  1.906893
2364  1.974979
2365  1.962055
2366  1.938771
2367  1.879604

[2368 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2538  0.733418
2539  0.693052
2540  0.704950
2541  0.908763
2542  1.001441

[2543 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2512  1.218105
2513  1.185705
2514  1.180883
2515  1.156255
2516  1.145333

[2517 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2381  0.983095
2382  0.959944
2383  0.976719
2384  0.930496
2385  0.863764

[2386 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2145  0.819546
2146  0.826276
2147  0.830862
2148  0.800981
2149  0.791227

[2150 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2398  1.112663
2399  1.089211
2400  0.968678
2401  0.942231
2402  0.777485

[2403 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2494  0.201247
2495  0.196681
2496  0.205997
2497  0.164309
2498  0.159064

[2499 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2206  0.873219
2207  0.891037
2208  0.888640
2209  1.102156
2210  1.384139

[2211 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2411 -0.066102
2412 -0.096706
2413 -0.068908
2414 -0.128779
2415 -0.101910

[2416 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2316  0.385094
2317  0.341816
2318  0.405387
2319  0.608660
2320  0.709055

[2321 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1820  0.896061
1821  0.908043
1822  0.961504
1823  0.924957
1824  0.932372

[1825 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2539  0.547257
2540  0.539630
2541  0.584308
2542  0.527745
2543  0.514609

[2544 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2530  0.817854
2531  0.771103
2532  0.781206
2533  0.812252
2534  0.816817

[2535 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2470  0.375331
2471  0.362253
2472  0.380324
2473  0.382949
2474  0.341187

[2475 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2174  0.613871
2175  0.563824
2176  0.433795
2177  0.627535
2178  0.637458

[2179 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2416  1.085168
2417  1.094721
2418  1.076027
2419  1.092748
2420  0.999928

[2421 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2536  0.419111
2537  0.395364
2538  0.429675
2539  0.416835
2540  0.610247

[2541 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2332  0.723423
2333  0.681116
2334  0.644836
2335  0.543528
2336  0.514661

[2337 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2537  0.747752
2538  0.729305
2539  0.737706
2540  0.687145
2541  0.656104

[2542 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2458  0.662757
2459  0.669058
2460  0.665988
2461  0.606725
2462  0.567704

[2463 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2459  0.272010
2460  0.276900
2461  0.289235
2462  0.318383
2463  0.647675

[2464 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2475  2.141517
2476  2.175694
2477  2.257374
2478  2.404483
2479  2.227542

[2480 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2513  1.607004
2514  1.624317
2515  1.645599
2516  1.628018
2517  1.676542

[2518 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2451  0.735638
2452  0.718466
2453  0.725067
2454  0.708101
2455  0.679423

[2456 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2527  0.248361
2528  0.227996
2529  0.234823
2530  0.144337
2531  0.038505

[2532 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2488  1.042724
2489  1.023201
2490  0.972700
2491  0.801607
2492  0.771712

[2493 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2492  0.285010
2493  0.233342
2494  0.211369
2495  0.411484
2496  0.345819

[2497 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2339  0.699084
2340  0.690785
2341  0.684851
2342  0.745802
2343  0.676040

[2344 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2538  0.560804
2539  0.552240
2540  0.557214
2541  0.637109
2542  0.621938

[2543 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2042  0.589871
2043  0.683485
2044  0.680831
2045  0.649164
2046  0.589221

[2047 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1732 -0.008404
1733  0.035225
1734  0.103351
1735  0.141992
1736  0.341480

[1737 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2536  0.695873
2537  0.701208
2538  0.750928
2539  0.708840
2540  0.637273

[2541 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2224  0.712714
2225  0.681824
2226  0.716062
2227  0.718806
2228  0.667280

[2229 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2299  0.826421
2300  0.812034
2301  0.827732
2302  0.791398
2303  0.739333

[2304 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2525  0.916987
2526  0.885493
2527  0.765905
2528  0.866176
2529  0.806560

[2530 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2483  1.005561
2484  0.987020
2485  0.991967
2486  1.057360
2487  0.926980

[2488 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2419  1.947719
2420  1.892126
2421  2.063384
2422  1.948261
2423  1.886714

[2424 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2352  2.286929
2353  2.305941
2354  2.378922
2355  2.368114
2356  2.171793

[2357 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2536  0.328779
2537  0.345222
2538  0.320219
2539  0.282828
2540  0.154913

[2541 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2315  1.061921
2316  1.048022
2317  1.074515
2318  1.077333
2319  1.036376

[2320 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2496  0.764014
2497  0.736203
2498  0.758491
2499  0.721036
2500  0.708869

[2501 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2145  0.189376
2146  0.287046
2147  0.216158
2148  0.157277
2149  0.040842

[2150 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2426  0.963903
2427  0.929592
2428  1.008210
2429  0.926787
2430  0.781675

[2431 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2496  0.571381
2497  0.582365
2498  0.576511
2499  0.553689
2500  0.543173

[2501 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2179  0.585349
2180  0.551432
2181  0.503205
2182  0.645554
2183  0.671831

[2184 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2530  0.992667
2531  0.991848
2532  1.012528
2533  0.978892
2534  0.942630

[2535 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2407 -0.057199
2408 -0.098956
2409 -0.131770
2410 -0.066739
2411  0.037341

[2412 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2355  0.944636
2356  1.081206
2357  1.067964
2358  1.053421
2359  0.889990

[2360 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2271  0.741668
2272  0.694787
2273  0.701819
2274  0.685283
2275  0.863408

[2276 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2019  0.622774
2020  0.527796
2021  0.530262
2022  0.558276
2023  0.432379

[2024 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2300  0.523180
2301  0.510649
2302  0.526886
2303  0.467980
2304  0.518830

[2305 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2405  0.883796
2406  0.862044
2407  0.823995
2408  0.806725
2409  1.096473

[2410 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2516  1.175666
2517  1.150039
2518  1.089560
2519  1.211706
2520  1.115388

[2521 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2541  0.984501
2542  0.930758
2543  0.956625
2544  0.873163
2545  0.826123

[2546 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2405  0.770034
2406  0.812417
2407  0.825544
2408  0.775870
2409  0.742884

[2410 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2493  0.442426
2494  0.383238
2495  0.468472
2496  0.588392
2497  0.480842

[2498 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2420  0.763649
2421  0.776322
2422  0.755376
2423  0.754174
2424  0.756467

[2425 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2371  0.171259
2372  0.152613
2373  0.295255
2374  0.264351
2375  0.363854

[2376 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2527  0.159998
2528  0.113211
2529  0.142430
2530  0.127633
2531  0.200638

[2532 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2112  0.306096
2113  0.252409
2114  0.140802
2115  0.113124
2116  0.099406

[2117 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2401  1.577079
2402  1.576991
2403  1.613310
2404  1.538740
2405  1.502452

[2406 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2537  1.060973
2538  1.052724
2539  1.070707
2540  1.085848
2541  1.086293

[2542 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2129  0.196152
2130  0.056998
2131  0.155858
2132  0.053018
2133  0.201790

[2134 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2265  0.562680
2266  0.587549
2267  0.587303
2268  0.635713
2269  0.576370

[2270 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2511  0.472681
2512  0.511627
2513  0.506247
2514  0.460086
2515  0.465191

[2516 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2258  0.599373
2259  0.562290
2260  0.566952
2261  0.539127
2262  0.567829

[2263 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2481  0.661370
2482  0.630829
2483  0.629770
2484  0.495053
2485  0.406823

[2486 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2370  0.239263
2371  0.259111
2372  0.205766
2373  0.086823
2374  0.143632

[2375 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2049  1.485204
2050  1.431006
2051  1.437228
2052  1.253324
2053  1.372660

[2054 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2461  0.541389
2462  0.517012
2463  0.494387
2464  0.450277
2465  0.348457

[2466 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1849  0.552715
1850  0.534346
1851  0.523537
1852  0.481319
1853  0.461648

[1854 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2132  0.750818
2133  0.725332
2134  0.712188
2135  0.726358
2136  0.713868

[2137 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2507  0.762753
2508  0.700246
2509  0.695745
2510  0.641797
2511  0.726574

[2512 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2539  0.515983
2540  0.488449
2541  0.463224
2542  0.416658
2543  0.436679

[2544 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2240  0.410647
2241  0.384890
2242  0.382250
2243  0.621266
2244  0.557501

[2245 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2434  0.671638
2435  0.655508
2436  0.672408
2437  0.624037
2438  0.608931

[2439 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2027  1.132135
2028  1.061158
2029  1.076459
2030  0.930808
2031  0.871162

[2032 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2491  1.211144
2492  1.201858
2493  1.211475
2494  1.194987
2495  1.145269

[2496 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2379  0.600583
2380  0.595517
2381  0.620520
2382  0.594211
2383  0.572851

[2384 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2445  0.953488
2446  0.928697
2447  0.916069
2448  0.788818
2449  0.774881

[2450 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2380  0.507433
2381  0.485570
2382  0.499716
2383  0.432139
2384  0.420269

[2385 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2535  0.928219
2536  0.874852
2537  0.860863
2538  0.775155
2539  0.768891

[2540 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2500  0.350383
2501  0.333441
2502  0.342326
2503  0.348868
2504  0.397694

[2505 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2468  0.450131
2469  0.432306
2470  0.429821
2471  0.421494
2472  0.397097

[2473 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2439  1.959546
2440  1.995977
2441  2.092905
2442  2.102609
2443  1.942738

[2444 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2350 -0.108529
2351 -0.024921
2352 -0.062087
2353 -0.145416
2354 -0.138477

[2355 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2524  0.032331
2525  0.023265
2526  0.040934
2527  0.015885
2528  0.071661

[2529 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2203  0.638290
2204  0.659793
2205  0.565686
2206  0.532436
2207  0.492893

[2208 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2185  1.577516
2186  1.570095
2187  1.489086
2188  1.362726
2189  1.239504

[2190 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2177  0.380455
2178  0.415527
2179  0.397883
2180  0.374951
2181  0.297537

[2182 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2486  0.793226
2487  0.788993
2488  0.707060
2489  0.659349
2490  0.926193

[2491 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2490  2.536928
2491  2.541155
2492  2.569412
2493  2.534825
2494  2.318636

[2495 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2428  0.754817
2429  0.728326
2430  0.731794
2431  0.733253
2432  0.784807

[2433 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1788  1.000327
1789  0.992342
1790  1.016896
1791  1.013532
1792  0.975231

[1793 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2464  1.040701
2465  1.011738
2466  1.018988
2467  0.883075
2468  0.830417

[2469 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2434  1.801569
2435  1.745508
2436  1.691366
2437  1.588496
2438  1.402915

[2439 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2481  0.501428
2482  0.469112
2483  0.453608
2484  0.442965
2485  0.506796

[2486 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2075  0.817682
2076  0.878822
2077  0.900968
2078  0.905067
2079  0.902790

[2080 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2322  1.022861
2323  0.985574
2324  0.849513
2325  1.018378
2326  0.827195

[2327 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2528  0.811514
2529  0.813746
2530  0.866719
2531  0.835721
2532  0.779011

[2533 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2507  0.482070
2508  0.498869
2509  0.502083
2510  0.531813
2511  0.494303

[2512 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2351  1.199711
2352  1.190314
2353  1.140789
2354  1.064641
2355  0.976696

[2356 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2299  1.253370
2300  1.233165
2301  1.263444
2302  1.166499
2303  1.199476

[2304 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2509  0.909855
2510  0.913746
2511  0.905806
2512  0.861138
2513  0.896424

[2514 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2529  0.501347
2530  0.488334
2531  0.495771
2532  0.490687
2533  0.475352

[2534 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2524  0.767711
2525  0.810230
2526  0.835072
2527  0.835285
2528  0.973771

[2529 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2343  0.779168
2344  0.758763
2345  0.630315
2346  0.779976
2347  0.659805

[2348 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2526  1.326851
2527  1.289419
2528  1.308078
2529  1.397943
2530  1.481342

[2531 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2396  0.572934
2397  0.514922
2398  0.528500
2399  0.531230
2400  0.671215

[2401 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2401  0.696080
2402  0.679995
2403  0.696985
2404  0.772781
2405  0.789380

[2406 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2508 -0.468827
2509 -0.524208
2510 -0.483154
2511 -0.217664
2512 -0.141670

[2513 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2459  1.023216
2460  0.999129
2461  0.976490
2462  0.889051
2463  0.868192

[2464 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2155  0.518082
2156  0.483079
2157  0.470827
2158  0.490892
2159  0.399288

[2160 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2510  0.604132
2511  0.667940
2512  0.675913
2513  0.651553
2514  0.599645

[2515 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2064  0.673723
2065  0.673070
2066  0.742397
2067  0.741300
2068  0.749666

[2069 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2313  1.652885
2314  1.618852
2315  1.621680
2316  1.495080
2317  1.384872

[2318 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2373  0.064547
2374  0.058072
2375 -0.108832
2376 -0.215074
2377 -0.220643

[2378 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2403  0.827361
2404  0.800248
2405  0.848619
2406  0.789332
2407  0.728193

[2408 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2510  0.792738
2511  0.811718
2512  0.783378
2513  0.760771
2514  0.759162

[2515 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2071  1.601124
2072  1.608089
2073  1.622657
2074  1.544094
2075  1.543461

[2076 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2032  0.417701
2033  0.364592
2034  0.401370
2035  0.497542
2036  0.467183

[2037 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1990  1.051672
1991  0.905621
1992  0.985583
1993  0.863520
1994  0.556850

[1995 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2169  0.717491
2170  0.694416
2171  0.554149
2172  0.461438
2173  0.386938

[2174 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2413  0.642770
2414  0.669703
2415  0.699284
2416  0.668770
2417  0.651886

[2418 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2504  0.979897
2505  1.080088
2506  1.023405
2507  1.114300
2508  1.027439

[2509 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2378  0.913823
2379  0.884034
2380  0.885951
2381  0.926873
2382  0.886743

[2383 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2377  1.001043
2378  1.034051
2379  1.046108
2380  1.007547
2381  1.001041

[2382 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2376  0.964488
2377  0.931430
2378  0.992784
2379  0.961836
2380  0.975878

[2381 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2475  1.563466
2476  1.554356
2477  1.571789
2478  1.574030
2479  1.678167

[2480 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2540  0.740850
2541  0.698372
2542  0.774046
2543  0.765546
2544  0.780931

[2545 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2524  0.669151
2525  0.643593
2526  0.646878
2527  0.592887
2528  0.622445

[2529 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2437  0.803201
2438  0.790063
2439  0.809627
2440  0.754878
2441  0.787165

[2442 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2047  2.482169
2048  2.422275
2049  2.273020
2050  2.253048
2051  2.253518

[2052 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2444  0.542140
2445  0.506760
2446  0.564836
2447  0.515142
2448  0.520285

[2449 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2147 -0.087907
2148 -0.082099
2149 -0.190421
2150 -0.197705
2151 -0.104767

[2152 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2485  0.840409
2486  0.823688
2487  0.820335
2488  0.746067
2489  0.945152

[2490 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2264  0.689672
2265  0.686200
2266  0.663275
2267  0.595095
2268  0.676850

[2269 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2460  0.437893
2461  0.447514
2462  0.405061
2463  0.370945
2464  0.591542

[2465 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2100  1.079910
2101  1.022853
2102  1.059834
2103  0.995152
2104  0.925260

[2105 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2223  0.546944
2224  0.371984
2225  0.310821
2226  0.042447
2227 -0.002602

[2228 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2408  1.465121
2409  1.427417
2410  1.466992
2411  1.373856
2412  1.410437

[2413 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2530  0.558269
2531  0.535187
2532  0.527243
2533  0.511067
2534  0.545976

[2535 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2428  0.935578
2429  0.956112
2430  0.978351
2431  0.983799
2432  0.899866

[2433 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2328  0.693402
2329  0.673583
2330  0.698348
2331  0.644732
2332  0.624441

[2333 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2426  0.485213
2427  0.445130
2428  0.458796
2429  0.417765
2430  0.400041

[2431 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2107  1.251796
2108  1.230981
2109  1.245689
2110  1.257765
2111  1.186505

[2112 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2384  0.776784
2385  0.761313
2386  0.728130
2387  0.816779
2388  0.864594

[2389 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2535  0.676088
2536  0.663179
2537  0.661496
2538  0.672764
2539  0.579081

[2540 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2382  0.828577
2383  0.836239
2384  0.811395
2385  0.865901
2386  0.738947

[2387 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2179  0.351782
2180  0.304401
2181  0.316536
2182  0.394822
2183  0.389664

[2184 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2463  0.602687
2464  0.559992
2465  0.500662
2466  0.531207
2467  0.435775

[2468 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2299  0.427464
2300  0.359450
2301  0.358165
2302  0.199153
2303  0.198995

[2304 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2291  0.232467
2292  0.237296
2293  0.248012
2294  0.259257
2295  0.245613

[2296 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2230  0.856339
2231  0.860187
2232  0.825029
2233  0.764964
2234  0.730864

[2235 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2363  0.679619
2364  0.696316
2365  0.714700
2366  0.722395
2367  0.760520

[2368 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2444  1.501386
2445  1.470234
2446  1.486425
2447  1.431157
2448  1.455281

[2449 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2407  0.339180
2408  0.310610
2409  0.275761
2410  0.246776
2411  0.381304

[2412 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2415  1.026001
2416  0.987542
2417  0.972877
2418  0.894321
2419  0.905070

[2420 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2524  0.914940
2525  0.976029
2526  0.821585
2527  0.928219
2528  0.972616

[2529 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2449  0.768864
2450  0.747869
2451  0.784888
2452  0.709026
2453  0.658460

[2454 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2535  1.071616
2536  1.032372
2537  1.029908
2538  0.999292
2539  0.939192

[2540 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2187  0.522598
2188  0.498978
2189  0.511902
2190  0.498164
2191  0.495922

[2192 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2425  0.842617
2426  0.772817
2427  0.751847
2428  0.885825
2429  0.844996

[2430 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2525  1.230390
2526  1.248182
2527  1.248261
2528  1.165640
2529  1.224399

[2530 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2158  0.750140
2159  0.726300
2160  0.737437
2161  0.760463
2162  0.733666

[2163 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2453  0.432110
2454  0.444113
2455  0.534675
2456  0.406764
2457  0.186437

[2458 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2451  0.510222
2452  0.490966
2453  0.519446
2454  0.510133
2455  0.518580

[2456 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2534  1.022468
2535  1.003924
2536  1.036393
2537  0.997217
2538  0.901297

[2539 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2305  0.433219
2306  0.447989
2307  0.462911
2308  0.431605
2309  0.444332

[2310 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2436  0.454172
2437  0.424661
2438  0.418574
2439  0.377496
2440  0.360721

[2441 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2510  1.142489
2511  1.073304
2512  1.079482
2513  1.066135
2514  1.020336

[2515 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2531  0.267219
2532  0.336341
2533  0.311433
2534  0.277664
2535  0.228887

[2536 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2409  0.445602
2410  0.436264
2411  0.438311
2412  0.411519
2413  0.394655

[2414 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2532  0.423293
2533  0.397145
2534  0.408921
2535  0.468304
2536  0.510561

[2537 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2495  0.849602
2496  0.832022
2497  0.841164
2498  0.843124
2499  0.816895

[2500 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2321  0.249495
2322  0.226239
2323  0.236933
2324  0.165286
2325  0.144304

[2326 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2391  0.820393
2392  0.796861
2393  0.769906
2394  0.732136
2395  0.678377

[2396 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2464  0.503562
2465  0.513803
2466  0.510790
2467  0.519903
2468  0.509897

[2469 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2304  0.939470
2305  0.922196
2306  0.913087
2307  0.863927
2308  0.774187

[2309 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2397  0.935318
2398  0.992116
2399  1.000935
2400  0.785620
2401  0.753016

[2402 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2351  0.745381
2352  0.808202
2353  0.795383
2354  0.685767
2355  0.637132

[2356 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2409  0.688899
2410  0.796256
2411  0.829735
2412  0.770298
2413  0.738910

[2414 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2533  1.357640
2534  1.334808
2535  1.351793
2536  1.349486
2537  1.376648

[2538 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2535  1.447946
2536  1.391455
2537  1.391493
2538  1.383153
2539  1.472970

[2540 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2393  0.934082
2394  0.949293
2395  1.034921
2396  1.021446
2397  0.988174

[2398 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2467  1.569173
2468  1.488823
2469  1.454801
2470  1.181375
2471  1.022747

[2472 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2537  0.508980
2538  0.490722
2539  0.507316
2540  0.446549
2541  0.464176

[2542 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2123  0.564150
2124  0.622882
2125  0.629449
2126  0.585087
2127  0.658949

[2128 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2539  0.425112
2540  0.396874
2541  0.412747
2542  0.392377
2543  0.408422

[2544 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2528  0.982121
2529  1.014443
2530  0.932850
2531  0.851405
2532  0.916825

[2533 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2462  0.490948
2463  0.464726
2464  0.476419
2465  0.420319
2466  0.391027

[2467 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2412  0.578993
2413  0.563497
2414  0.622256
2415  0.707087
2416  0.660556

[2417 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2507  0.493504
2508  0.396460
2509  0.217601
2510  0.248183
2511  0.073384

[2512 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2404  0.928762
2405  0.892408
2406  0.915753
2407  0.995787
2408  0.885592

[2409 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2510  0.701741
2511  0.731077
2512  0.728165
2513  0.703546
2514  0.666449

[2515 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2192  0.932112
2193  0.942696
2194  0.934900
2195  0.909391
2196  0.894874

[2197 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1355 -0.348232
1356 -0.308307
1357 -0.281130
1358 -0.352841
1359 -0.155984

[1360 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2446  1.155682
2447  1.137360
2448  1.111197
2449  1.070852
2450  1.090511

[2451 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2408  0.640771
2409  0.629534
2410  0.591747
2411  0.607064
2412  0.562271

[2413 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2481  0.710614
2482  0.699205
2483  0.719906
2484  0.677949
2485  0.664621

[2486 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2468  0.306404
2469  0.320230
2470  0.271434
2471  0.264781
2472  0.179715

[2473 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2393  0.488375
2394  0.542256
2395  0.569156
2396  0.586750
2397  0.510718

[2398 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2532  0.358879
2533  0.368792
2534  0.383347
2535  0.509854
2536  0.513946

[2537 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2530  0.733185
2531  0.696116
2532  0.690380
2533  0.807703
2534  0.763286

[2535 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2468  0.555349
2469  0.550331
2470  0.622381
2471  0.634737
2472  0.636161

[2473 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2524  0.547532
2525  0.620179
2526  0.610026
2527  0.585012
2528  0.550972

[2529 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2425  0.677548
2426  0.638377
2427  0.641548
2428  0.779282
2429  0.797126

[2430 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2332  1.066509
2333  1.016798
2334  1.052933
2335  1.128464
2336  1.061121

[2337 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2365 -0.119758
2366 -0.124408
2367 -0.044989
2368 -0.085227
2369 -0.078988

[2370 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2539  1.524720
2540  1.475494
2541  1.531283
2542  1.804632
2543  1.685486

[2544 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2527  0.339364
2528  0.316206
2529  0.372529
2530  0.246223
2531  0.181342

[2532 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2539  1.074170
2540  1.084229
2541  1.132821
2542  1.123084
2543  0.999474

[2544 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2457  0.232592
2458  0.202137
2459  0.221710
2460  0.190338
2461  0.208577

[2462 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2534  0.695390
2535  0.673382
2536  0.664782
2537  0.580172
2538  0.496305

[2539 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2530  0.532739
2531  0.768487
2532  0.696303
2533  0.654054
2534  0.493612

[2535 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2535  1.211572
2536  1.210245
2537  1.278732
2538  1.335113
2539  1.341821

[2540 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2538  0.698084
2539  0.592595
2540  0.544320
2541  0.819801
2542  0.729974

[2543 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2504  1.443243
2505  1.481854
2506  1.516105
2507  1.428469
2508  1.373795

[2509 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2523  0.404330
2524  0.378425
2525  0.413009
2526  0.391549
2527  0.366550

[2528 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2405  0.814093
2406  0.774922
2407  0.776603
2408  0.684134
2409  0.638927

[2410 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2417  0.610941
2418  0.601464
2419  0.659402
2420  0.689187
2421  0.657576

[2422 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2475  1.657265
2476  1.597575
2477  1.619843
2478  1.492982
2479  1.256266

[2480 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2532  0.810267
2533  0.782825
2534  0.792453
2535  0.752360
2536  0.750871

[2537 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2277  0.459146
2278  0.415448
2279  0.404802
2280  0.374564
2281  0.340229

[2282 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2206  0.362773
2207  0.333521
2208  0.338098
2209  0.483141
2210  0.418668

[2211 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2385  1.281919
2386  1.249318
2387  1.283803
2388  1.392575
2389  1.256424

[2390 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2515  0.621958
2516  0.664991
2517  0.655330
2518  0.666662
2519  0.662818

[2520 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2503  0.996421
2504  0.919682
2505  0.943687
2506  0.961434
2507  0.963356

[2508 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2537  0.676787
2538  0.720276
2539  0.743650
2540  0.735252
2541  0.714803

[2542 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2372  0.196794
2373  0.362044
2374  0.301866
2375  0.561127
2376  0.487328

[2377 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2228  0.229010
2229 -0.011964
2230 -0.064121
2231 -0.077689
2232  0.004474

[2233 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2476  0.664012
2477  0.664459
2478  0.664646
2479  0.573642
2480  0.549418

[2481 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2436 -0.134045
2437 -0.161635
2438 -0.081712
2439 -0.049441
2440  0.009569

[2441 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2339 -0.269912
2340 -0.364093
2341 -0.372307
2342 -0.268702
2343  0.023607

[2344 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2337  0.489996
2338  0.482295
2339  0.509940
2340  0.538814
2341  0.447585

[2342 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2536  0.754302
2537  0.763347
2538  0.716580
2539  0.695886
2540  0.561752

[2541 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2395  1.249028
2396  1.236532
2397  1.260292
2398  1.157796
2399  1.039294

[2400 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2518  0.497939
2519  0.509455
2520  0.502076
2521  0.450805
2522  0.424453

[2523 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2396  1.446020
2397  1.429522
2398  1.451574
2399  1.429569
2400  1.349440

[2401 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2522  1.365258
2523  1.268935
2524  1.205868
2525  1.136710
2526  1.036664

[2527 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2301  1.077579
2302  1.118167
2303  1.086122
2304  1.037882
2305  0.995978

[2306 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2491  0.713788
2492  0.715189
2493  0.681854
2494  0.842970
2495  0.643176

[2496 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2501  0.714109
2502  0.675821
2503  0.687366
2504  0.647357
2505  0.620822

[2506 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2439  0.555788
2440  0.492080
2441  0.489241
2442  0.446180
2443  0.408718

[2444 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1928  0.703300
1929  0.611914
1930  0.706005
1931  0.516688
1932  0.296329

[1933 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2375  0.887563
2376  0.868559
2377  0.881220
2378  0.986416
2379  0.957821

[2380 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2451  0.703746
2452  0.737747
2453  0.724383
2454  0.835767
2455  0.818206

[2456 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2349  0.908636
2350  0.914946
2351  0.901303
2352  0.857228
2353  0.818819

[2354 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2532  0.368165
2533  0.334595
2534  0.346367
2535  0.309288
2536  0.307733

[2537 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2463  1.105803
2464  1.072522
2465  1.092458
2466  1.022838
2467  0.983270

[2468 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2278  1.064141
2279  1.097439
2280  1.065006
2281  1.011851
2282  0.924955

[2283 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2228  0.836323
2229  0.851655
2230  0.837502
2231  0.796404
2232  0.738315

[2233 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2438  0.884882
2439  0.850674
2440  0.855322
2441  0.864429
2442  0.795145

[2443 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2290  1.123923
2291  1.304898
2292  1.334972
2293  1.146623
2294  1.122758

[2295 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2493  0.758587
2494  0.734476
2495  0.747556
2496  0.785915
2497  0.763995

[2498 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2308  1.068688
2309  1.059421
2310  1.092963
2311  1.023700
2312  0.840064

[2313 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2535  0.904222
2536  0.805022
2537  0.804420
2538  0.677639
2539  0.923038

[2540 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2515  0.874156
2516  0.813266
2517  0.730244
2518  0.670252
2519  0.634908

[2520 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2442  1.830303
2443  1.805700
2444  1.808939
2445  1.758841
2446  1.611308

[2447 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2467  0.468438
2468  0.478217
2469  0.484107
2470  0.503389
2471  0.500699

[2472 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2505  0.827771
2506  0.828611
2507  0.812124
2508  0.853747
2509  0.875080

[2510 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2489  1.019861
2490  0.962010
2491  0.987435
2492  0.936099
2493  0.941902

[2494 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2504  0.871832
2505  0.809123
2506  0.764241
2507  0.879834
2508  0.823392

[2509 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1895  0.867056
1896  0.734651
1897  0.752141
1898  0.560695
1899  0.502700

[1900 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2286  0.551451
2287  0.557888
2288  0.551521
2289  0.557834
2290  0.601971

[2291 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2376  1.545300
2377  1.180827
2378  1.185512
2379  1.220023
2380  1.074320

[2381 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2383  0.827175
2384  0.855548
2385  0.796856
2386  0.766291
2387  0.712138

[2388 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2459  0.600195
2460  0.594658
2461  0.571982
2462  0.562273
2463  0.585942

[2464 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2536  1.021927
2537  0.962063
2538  0.899622
2539  0.907013
2540  0.719095

[2541 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2358  0.909547
2359  1.100684
2360  1.069554
2361  1.011838
2362  0.906176

[2363 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2540  0.702872
2541  0.705230
2542  0.682959
2543  0.621025
2544  0.593140

[2545 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2116  0.895248
2117  0.979409
2118  1.140817
2119  0.989747
2120  0.590779

[2121 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2427  0.488770
2428  0.479024
2429  0.485205
2430  0.499749
2431  0.555590

[2432 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
563  0.927537
564  0.905517
565  0.923702
566  0.910105
567  0.876126

[568 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
633  0.604520
634  0.591045
635  0.597234
636  0.607242
637  0.574418

[638 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
905  0.564494
906  0.541907
907  0.557727
908  0.552572
909  0.560811

[910 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
863  1.581042
864  1.562602
865  1.612321
866  1.694302
867  1.643664

[868 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1394  0.283427
1395  0.252466
1396  0.248796
1397  0.200403
1398  0.179456

[1399 rows x 1 columns]
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
946  0.481542
947  0.501828
948  0.501618
949  0.484489
950  0.519296

[951 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
891  0.696500
892  0.715981
893  0.738065
894  0.712035
895  0.740617

[896 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
320  0.621521
321  0.621235
322  0.625003
323  0.601337
324  0.590902

[325 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
546  0.936427
547  1.006880
548  0.989758
549  1.031216
550  0.958487

[551 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
631  1.779835
632  1.751479
633  1.738986
634  1.721686
635  1.560922

[636 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
937  0.145070
938  0.113040
939  0.158797
940  0.108188
941  0.097784

[942 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
814  0.730156
815  0.727175
816  0.726942
817  0.691362
818  0.702568

[819 rows x 1 columns]
    0
0 NaN
1 NaN
2 NaN
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1276  1.078702
1277  1.049525
1278  1.083586
1279  1.107145
1280  1.103523

[1281 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1155  0.416522
1156  0.383687
1157  0.384644
1158  0.381975
1159  0.318712

[1160 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2357  0.789575
2358  0.656485
2359  0.703168
2360  0.787102
2361  0.781700

[2362 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2529  1.069582
2530  1.056957
2531  1.056496
2532  0.965314
2533  0.987384

[2534 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2419  0.240461
2420  0.286087
2421  0.306550
2422  0.433431
2423  0.441637

[2424 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2466  0.705838
2467  0.731822
2468  0.705244
2469  0.699282
2470  0.666973

[2471 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2373  0.932124
2374  0.973452
2375  0.959739
2376  1.076238
2377  1.005916

[2378 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2487  1.450486
2488  1.548255
2489  1.387088
2490  1.339961
2491  1.250469

[2492 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2381  0.546432
2382  0.502233
2383  0.473764
2384  0.435271
2385  0.400536

[2386 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
242  0.917916
243  0.899095
244  0.917190
245  0.873440
246  0.844664

[247 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2535  0.605397
2536  0.562234
2537  0.549486
2538  0.533342
2539  0.529850

[2540 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2496  0.692751
2497  0.678337
2498  0.691745
2499  0.680665
2500  0.715656

[2501 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2535  0.581995
2536  0.557575
2537  0.578438
2538  0.596000
2539  0.600633

[2540 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2408  0.981160
2409  0.906557
2410  0.910445
2411  0.841320
2412  0.810817

[2413 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2445  0.380283
2446  0.470241
2447  0.384245
2448  0.549270
2449  0.551753

[2450 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2528  0.555017
2529  0.553437
2530  0.525899
2531  0.500860
2532  0.407542

[2533 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
941  1.033691
942  1.027638
943  1.030792
944  0.966656
945  0.969905

[946 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2292  0.689761
2293  0.567221
2294  0.635457
2295  0.622232
2296  0.770336

[2297 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2409  0.559698
2410  0.540031
2411  0.553819
2412  0.527807
2413  0.505530

[2414 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2508  0.400471
2509  0.413791
2510  0.460588
2511  0.400303
2512  0.432586

[2513 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2358  0.533001
2359  0.580128
2360  0.640045
2361  0.601630
2362  0.501658

[2363 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2428  0.487248
2429  0.457378
2430  0.467691
2431  0.432595
2432  0.432246

[2433 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2371  1.464786
2372  1.659603
2373  1.646610
2374  1.888607
2375  1.757787

[2376 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2431  0.576077
2432  0.519905
2433  0.366640
2434  0.419063
2435  0.265574

[2436 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2301  0.773187
2302  0.791937
2303  0.815480
2304  0.803417
2305  0.823586

[2306 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2329  1.577252
2330  1.531144
2331  1.499246
2332  1.404624
2333  1.311095

[2334 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2475  0.685820
2476  0.665459
2477  0.663510
2478  0.645114
2479  0.602828

[2480 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2250  0.200682
2251  0.229808
2252  0.174659
2253  0.074708
2254  0.064931

[2255 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
270  0.482656
271  0.475762
272  0.495488
273  0.450838
274  0.432525

[275 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2394  0.925771
2395  0.939663
2396  0.907628
2397  0.841398
2398  0.810676

[2399 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2537  0.382463
2538  0.363857
2539  0.380514
2540  0.349789
2541  0.336383

[2542 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2541  0.694097
2542  0.718204
2543  0.534323
2544  0.570884
2545  0.860964

[2546 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2464  0.847690
2465  0.819181
2466  0.831344
2467  0.744017
2468  0.695488

[2469 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
847  0.608765
848  0.587340
849  0.615610
850  0.575985
851  0.542883

[852 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2473  0.614432
2474  0.607738
2475  0.629527
2476  0.612817
2477  0.663879

[2478 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2323  0.076093
2324  0.098939
2325  0.050117
2326  0.057491
2327  0.117120

[2328 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2530  1.106795
2531  1.127248
2532  1.079193
2533  1.224750
2534  1.128091

[2535 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2333  0.484571
2334  0.472174
2335  0.472450
2336  0.438373
2337  0.407793

[2338 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2446  0.997288
2447  0.977342
2448  0.960030
2449  0.932295
2450  0.958755

[2451 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2524  1.054124
2525  1.029122
2526  1.032672
2527  1.134967
2528  1.110633

[2529 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2371  0.312404
2372  0.287846
2373  0.286084
2374  0.247284
2375  0.289391

[2376 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2099  1.093777
2100  1.082880
2101  1.123576
2102  1.081665
2103  1.064683

[2104 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2532  0.467625
2533  0.443784
2534  0.453858
2535  0.447741
2536  0.407030

[2537 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2533  0.840846
2534  0.827810
2535  0.830276
2536  0.733092
2537  0.691179

[2538 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2532  0.554808
2533  0.523372
2534  0.528744
2535  0.474871
2536  0.485607

[2537 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2525  0.299901
2526  0.318463
2527  0.334846
2528  0.311174
2529  0.343472

[2530 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2186  0.720120
2187  0.727348
2188  0.729055
2189  0.683944
2190  0.628069

[2191 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2231  0.977612
2232  0.950662
2233  1.022674
2234  0.977749
2235  0.931505

[2236 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1955  1.269496
1956  1.273767
1957  1.148795
1958  1.186358
1959  1.158962

[1960 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1370  0.538852
1371  0.525640
1372  0.535263
1373  0.533805
1374  0.449466

[1375 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1386  0.748117
1387  0.730445
1388  0.740933
1389  0.685787
1390  0.657904

[1391 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2227  0.663769
2228  0.747282
2229  0.717658
2230  0.500286
2231  0.485045

[2232 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
628  0.625736
629  0.630356
630  0.629645
631  0.615055
632  0.642232

[633 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1030  0.784322
1031  0.758390
1032  0.732918
1033  0.673709
1034  0.715879

[1035 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1296  1.099161
1297  1.127787
1298  1.197967
1299  1.155535
1300  1.204766

[1301 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2021  0.616078
2022  0.554383
2023  0.558402
2024  0.590397
2025  0.606570

[2026 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1914  0.589130
1915  0.595594
1916  0.560409
1917  0.672466
1918  0.555043

[1919 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2147  0.944327
2148  0.948698
2149  0.963303
2150  0.963766
2151  0.917316

[2152 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
489  2.038803
490  2.018953
491  2.002881
492  2.104906
493  1.959903

[494 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
437  0.355111
438  0.318574
439  0.323896
440  0.259232
441  0.255467

[442 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1209  0.474727
1210  0.465670
1211  0.460839
1212  0.371303
1213  0.385110

[1214 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
159  0.358245
160  0.365526
161  0.373514
162  0.349229
163  0.361156

[164 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
661  1.071940
662  1.041272
663  1.030327
664  1.059538
665  0.986922

[666 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2477  0.681109
2478  0.721611
2479  0.740366
2480  0.787941
2481  0.838530

[2482 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2343  0.426667
2344  0.417135
2345  0.430713
2346  0.445375
2347  0.416649

[2348 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2522  1.202221
2523  1.170111
2524  1.211247
2525  1.192266
2526  1.153571

[2527 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2063  0.809977
2064  0.783531
2065  0.803057
2066  1.034904
2067  0.914756

[2068 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2375  1.155716
2376  1.129418
2377  1.124570
2378  1.104660
2379  1.041489

[2380 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2505  0.231464
2506  0.195930
2507  0.221135
2508  0.187191
2509  0.222530

[2510 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2527  0.727978
2528  0.719197
2529  0.720873
2530  0.698578
2531  0.673990

[2532 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
649  1.492086
650  1.463578
651  1.528775
652  1.534948
653  1.626543

[654 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2489  1.332477
2490  1.174000
2491  1.186997
2492  1.179986
2493  1.112020

[2494 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2129  0.601577
2130  0.624110
2131  0.636652
2132  0.590927
2133  0.708463

[2134 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2247  0.775989
2248  0.787362
2249  0.765354
2250  0.846304
2251  0.747712

[2252 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2534  0.700175
2535  0.672520
2536  0.681388
2537  0.710469
2538  0.766565

[2539 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2167  0.664608
2168  0.786239
2169  0.834301
2170  0.807064
2171  0.777507

[2172 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2292  0.615765
2293  0.513140
2294  0.521959
2295  0.565887
2296  0.518291

[2297 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
955  0.822144
956  0.811109
957  0.808674
958  0.749527
959  0.671212

[960 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
905  0.791149
906  0.835306
907  0.807809
908  0.702884
909  0.654209

[910 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2220  1.702077
2221  1.739785
2222  1.696187
2223  1.657793
2224  1.547073

[2225 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
496  1.423578
497  1.455225
498  1.479181
499  1.440278
500  1.395499

[501 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2527  0.635905
2528  0.580601
2529  0.590839
2530  0.584510
2531  0.568111

[2532 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1097  0.958822
1098  1.003735
1099  1.039221
1100  1.102434
1101  1.252410

[1102 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2473  0.448312
2474  0.438395
2475  0.437064
2476  0.418897
2477  0.427354

[2478 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
402  1.972372
403  1.925102
404  1.980983
405  1.923063
406  1.837615

[407 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
918  0.821909
919  0.808210
920  0.821706
921  0.775890
922  0.821168

[923 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2524  0.590602
2525  0.649182
2526  0.641938
2527  0.631411
2528  0.678837

[2529 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2340  1.000764
2341  0.992683
2342  0.951014
2343  0.951394
2344  1.000891

[2345 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2492  0.437972
2493  0.450694
2494  0.449381
2495  0.454602
2496  0.484602

[2497 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2356  0.633453
2357  0.642487
2358  0.669703
2359  0.616137
2360  0.560952

[2361 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2513  1.672204
2514  1.592120
2515  1.591944
2516  1.855662
2517  1.850554

[2518 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2526  0.881310
2527  0.845750
2528  0.840473
2529  0.968561
2530  1.049871

[2531 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2485  0.424434
2486  0.433643
2487  0.439979
2488  0.410048
2489  0.380398

[2490 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1291  1.165659
1292  1.153279
1293  1.198307
1294  1.214045
1295  1.219139

[1296 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2222  0.457342
2223  0.473544
2224  0.497966
2225  0.467546
2226  0.462309

[2227 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
786  0.576319
787  0.532256
788  0.503180
789  0.492651
790  0.496032

[791 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2203  1.369371
2204  1.320857
2205  1.265300
2206  1.256658
2207  1.173104

[2208 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1216  0.880345
1217  0.865011
1218  0.897336
1219  0.926695
1220  0.917645

[1221 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
775  0.903593
776  0.872576
777  0.888377
778  0.816748
779  0.826630

[780 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2145  0.685670
2146  0.672423
2147  0.704025
2148  0.651872
2149  0.641789

[2150 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2205  1.151093
2206  1.102397
2207  1.073680
2208  1.008763
2209  0.971010

[2210 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2139  1.026783
2140  0.970558
2141  0.922812
2142  0.974571
2143  0.889211

[2144 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1559  0.720273
1560  0.719367
1561  0.731913
1562  0.778491
1563  0.776451

[1564 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1346  0.880357
1347  0.860170
1348  0.842406
1349  0.803442
1350  0.783688

[1351 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
788  0.579146
789  0.554095
790  0.568140
791  0.595281
792  0.568230

[793 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
877  0.118582
878  0.130697
879  0.136970
880  0.134208
881  0.155408

[882 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2012  2.286507
2013  2.375606
2014  2.404337
2015  2.330662
2016  2.131525

[2017 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2201  1.047965
2202  1.057619
2203  1.085951
2204  0.955494
2205  0.957113

[2206 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
235  2.403631
236  2.385389
237  2.451432
238  2.383219
239  2.232943

[240 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1990  0.891576
1991  0.870686
1992  0.876230
1993  0.895277
1994  0.846332

[1995 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2196  0.502362
2197  0.441594
2198  0.485265
2199  0.592478
2200  0.553832

[2201 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2412  0.254372
2413  0.261087
2414  0.254906
2415  0.277710
2416  0.273019

[2417 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
344  0.619127
345  0.612222
346  0.623116
347  0.586433
348  0.582699

[349 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2178  0.995237
2179  0.970929
2180  0.996113
2181  0.946478
2182  0.914786

[2183 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2490  0.920278
2491  0.929375
2492  0.950650
2493  0.941339
2494  0.982638

[2495 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
388  0.840858
389  0.827785
390  0.855660
391  0.882403
392  0.979436

[393 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
693  0.574710
694  0.556952
695  0.558388
696  0.534556
697  0.515759

[698 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2531  0.259391
2532  0.266136
2533  0.259270
2534  0.294309
2535  0.299258

[2536 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
495  1.083607
496  1.077281
497  1.048230
498  0.959078
499  0.850265

[500 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2539  0.775131
2540  0.763940
2541  0.720890
2542  0.664263
2543  0.639523

[2544 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2042  1.051897
2043  1.050828
2044  1.076908
2045  1.080279
2046  1.126645

[2047 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1953  0.676106
1954  0.736575
1955  0.800339
1956  0.684950
1957  0.687714

[1958 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1922  1.114871
1923  1.111631
1924  1.157445
1925  1.089885
1926  1.054553

[1927 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
775  0.546178
776  0.640135
777  0.632606
778  0.567807
779  0.571272

[780 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1219  0.502166
1220  0.478464
1221  0.486689
1222  0.444788
1223  0.434631

[1224 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2424  0.737693
2425  0.706930
2426  0.713921
2427  0.688146
2428  0.632006

[2429 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
844  1.388241
845  1.369103
846  1.407382
847  1.437531
848  1.419937

[849 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2339  1.113526
2340  1.104740
2341  1.044046
2342  1.218719
2343  1.132104

[2344 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1834  1.108771
1835  1.074792
1836  1.091338
1837  1.030825
1838  1.021117

[1839 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2451  0.952974
2452  0.927256
2453  0.926831
2454  0.966677
2455  0.994412

[2456 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2531  0.255719
2532  0.267208
2533  0.250449
2534  0.250276
2535  0.243523

[2536 rows x 1 columns]
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
911  0.604462
912  0.582730
913  0.542755
914  0.538909
915  0.512831

[916 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
121  1.004532
122  0.998127
123  0.997783
124  0.951584
125  1.026904

[126 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2027  1.191526
2028  1.193888
2029  1.137879
2030  1.116594
2031  1.039156

[2032 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2445  0.435423
2446  0.407507
2447  0.416464
2448  0.376935
2449  0.385282

[2450 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2134  1.592631
2135  1.589301
2136  1.621895
2137  1.642324
2138  1.537513

[2139 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2059  1.390766
2060  1.407290
2061  1.453746
2062  1.442428
2063  1.454457

[2064 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2241  0.544324
2242  0.532403
2243  0.617285
2244  0.625876
2245  0.697457

[2246 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2189  0.443505
2190  0.443125
2191  0.453354
2192  0.436892
2193  0.425545

[2194 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2140  0.793431
2141  0.766514
2142  0.767277
2143  0.797268
2144  0.719832

[2145 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
420  0.449550
421  0.450883
422  0.455017
423  0.460541
424  0.476674

[425 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1397  0.075847
1398  0.072025
1399  0.126318
1400  0.160001
1401  0.340695

[1402 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2525  0.599550
2526  0.575385
2527  0.536319
2528  0.486385
2529  0.602647

[2530 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
935  0.587932
936  0.629932
937  0.673175
938  0.588538
939  0.634475

[940 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
345  0.597614
346  0.577956
347  0.581687
348  0.582048
349  0.567976

[350 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2044  1.258034
2045  1.227735
2046  1.159376
2047  1.031960
2048  1.117512

[2049 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2425  0.746484
2426  0.726696
2427  0.726468
2428  0.706409
2429  0.727945

[2430 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2541  1.138783
2542  1.119246
2543  1.126080
2544  1.112000
2545  1.177436

[2546 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
456  0.017658
457 -0.011913
458 -0.059274
459  0.017094
460 -0.050178

[461 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2515  0.174231
2516  0.229338
2517  0.246792
2518  0.366886
2519  0.382890

[2520 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1787  0.717852
1788  0.680645
1789  0.691416
1790  0.660397
1791  0.659058

[1792 rows x 1 columns]
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
36 NaN
37 NaN
38 NaN
39 NaN
40 NaN
41 NaN
42 NaN
43 NaN
44 NaN
45 NaN
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
984  0.642997
985  0.621747
986  0.636147
987  0.661585
988  0.667731

[989 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
342  0.640933
343  0.617024
344  0.594981
345  0.502433
346  0.473673

[347 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2267  1.378862
2268  1.332503
2269  1.305780
2270  1.266474
2271  1.250335

[2272 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2465  0.676194
2466  0.652253
2467  0.646967
2468  0.652601
2469  0.685751

[2470 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
583  0.812858
584  0.801158
585  0.766742
586  0.676909
587  0.635370

[588 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2539  1.040922
2540  1.063257
2541  1.118184
2542  1.092748
2543  1.142589

[2544 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2096  0.831533
2097  0.819766
2098  0.854626
2099  0.903458
2100  0.956291

[2101 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2140  0.913568
2141  0.849992
2142  0.758763
2143  0.761940
2144  0.795727

[2145 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
129  0.332627
130  0.381888
131  0.383060
132  0.384014
133  0.388011

[134 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2540  0.621916
2541  0.572196
2542  0.572421
2543  0.589006
2544  0.591936

[2545 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2537  0.688641
2538  0.674365
2539  0.680685
2540  0.701996
2541  0.753859

[2542 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1996  0.873553
1997  0.843189
1998  0.849973
1999  0.859735
2000  0.888996

[2001 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2124  0.531847
2125  0.507588
2126  0.516501
2127  0.589757
2128  0.628201

[2129 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2504  0.792630
2505  0.784109
2506  0.791055
2507  0.741125
2508  0.704496

[2509 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2499  1.021036
2500  1.011866
2501  1.087612
2502  1.103569
2503  1.118255

[2504 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1274  1.853638
1275  1.786785
1276  1.788823
1277  1.772520
1278  1.575499

[1279 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
80  2.399213
81  2.355807
82  2.435722
83  2.470880
84  2.322634

[85 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
240  1.222724
241  1.185438
242  1.158312
243  1.055577
244  0.944288

[245 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2518  0.770476
2519  0.779867
2520  0.797211
2521  0.850672
2522  0.868659

[2523 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2090  1.509836
2091  1.381742
2092  1.351126
2093  1.263837
2094  1.141574

[2095 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2201  1.090051
2202  1.086617
2203  1.081783
2204  1.034923
2205  0.966255

[2206 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2381  0.433462
2382  0.436280
2383  0.432443
2384  0.471829
2385  0.493688

[2386 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2273  0.674549
2274  0.627452
2275  0.633909
2276  0.647631
2277  0.567731

[2278 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2449  0.574599
2450  0.561600
2451  0.542445
2452  0.588203
2453  0.614263

[2454 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2287 -0.058748
2288  0.092586
2289  0.186692
2290 -0.086757
2291 -0.423501

[2292 rows x 1 columns]
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2524  1.272463
2525  1.254486
2526  1.266097
2527  1.422928
2528  1.602762

[2529 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1963  1.827049
1964  1.712442
1965  1.719520
1966  1.602323
1967  1.538288

[1968 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2119  0.525417
2120  0.602450
2121  0.655632
2122  0.641461
2123  0.539421

[2124 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2229  1.053471
2230  1.038246
2231  1.019205
2232  0.956375
2233  0.876092

[2234 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2015  0.906557
2016  0.871192
2017  0.878224
2018  0.903222
2019  0.961393

[2020 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2505  0.133008
2506  0.091846
2507  0.121501
2508  0.094391
2509  0.178710

[2510 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2540  1.992174
2541  1.932941
2542  1.974691
2543  1.883715
2544  1.762138

[2545 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
942  0.538800
943  0.520882
944  0.511662
945  0.415281
946  0.398278

[947 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
103  0.808518
104  0.808165
105  0.820828
106  0.783502
107  0.773645

[108 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2373  0.402156
2374  0.424199
2375  0.423832
2376  0.435502
2377  0.667607

[2378 rows x 1 columns]
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
588  1.116514
589  1.088683
590  1.059062
591  0.961788
592  0.910213

[593 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
579  0.399432
580  0.422160
581  0.428452
582  0.418170
583  0.443355

[584 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2539  0.681592
2540  0.669677
2541  0.666622
2542  0.624036
2543  0.639518

[2544 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
833  1.100271
834  1.073796
835  1.089750
836  1.012969
837  0.983880

[838 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
356  0.556109
357  0.573171
358  0.586200
359  0.554389
360  0.554118

[361 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
330  1.330663
331  1.341257
332  1.149205
333  0.957363
334  0.922261

[335 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2442  0.657416
2443  0.639577
2444  0.665542
2445  0.687506
2446  0.682990

[2447 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
467  1.156334
468  1.107649
469  1.136804
470  1.010425
471  0.933052

[472 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2420  0.713255
2421  0.759961
2422  0.775872
2423  0.983852
2424  0.913238

[2425 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2390  0.997761
2391  1.003087
2392  0.983456
2393  0.950271
2394  0.846689

[2395 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
730  1.668340
731  1.641057
732  1.685441
733  1.702800
734  1.950361

[735 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2310  0.506349
2311  0.531369
2312  0.537868
2313  0.532827
2314  0.522009

[2315 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
830  1.499432
831  1.504800
832  1.529407
833  1.555632
834  1.596932

[835 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
881  0.867981
882  0.805700
883  0.795332
884  0.934071
885  0.853953

[886 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2115  0.753547
2116  0.731973
2117  0.715835
2118  0.704116
2119  0.679073

[2120 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2478  1.497731
2479  1.453617
2480  1.265030
2481  1.291525
2482  1.468405

[2483 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2300  0.067145
2301  0.024294
2302  0.018625
2303  0.126025
2304  0.123525

[2305 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2537  0.605422
2538  0.598048
2539  0.624841
2540  0.612947
2541  0.660533

[2542 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2505  1.020727
2506  1.031757
2507  1.023557
2508  0.961741
2509  1.042753

[2510 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
945  0.841224
946  0.803617
947  0.821622
948  0.763641
949  0.662429

[950 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2036  0.972454
2037  0.954363
2038  0.991057
2039  1.085116
2040  1.074480

[2041 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2115  1.346662
2116  1.327321
2117  1.197877
2118  1.080032
2119  1.087007

[2120 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
139  0.301199
140  0.307218
141  0.316431
142  0.325151
143  0.341797

[144 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2445  0.853651
2446  0.832387
2447  0.860420
2448  0.838978
2449  0.838279

[2450 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2389  1.088542
2390  1.085680
2391  1.075871
2392  1.088410
2393  1.060297

[2394 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2026  0.560299
2027  0.551277
2028  0.568350
2029  0.532165
2030  0.510599

[2031 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2017  0.837714
2018  0.801399
2019  0.814662
2020  0.775960
2021  0.723360

[2022 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2291  0.430961
2292  0.487866
2293  0.474991
2294  0.572585
2295  0.527830

[2296 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2532  0.398390
2533  0.414309
2534  0.415481
2535  0.429824
2536  0.435383

[2537 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
690  1.241024
691  1.224060
692  1.247426
693  1.207275
694  1.189729

[695 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
758  0.803121
759  0.919385
760  0.779663
761  0.899372
762  0.827347

[763 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2540  0.916134
2541  0.902486
2542  0.869679
2543  0.819368
2544  0.801694

[2545 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1946  1.123120
1947  1.139162
1948  1.096826
1949  0.964753
1950  0.974474

[1951 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
950  1.189908
951  1.166115
952  1.201455
953  1.213150
954  1.113452

[955 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1207  0.743525
1208  0.689603
1209  0.694503
1210  0.577337
1211  0.731819

[1212 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1307  0.853700
1308  0.734904
1309  0.760790
1310  0.751083
1311  0.731735

[1312 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
352  0.617499
353  0.588428
354  0.603495
355  0.583635
356  0.553177

[357 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1227  0.680755
1228  0.684840
1229  0.682499
1230  0.645254
1231  0.659153

[1232 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2531  0.257819
2532  0.265051
2533  0.253834
2534  0.262194
2535  0.268457

[2536 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2253  0.360000
2254  0.333613
2255  0.323926
2256  0.364110
2257  0.363590

[2258 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
493  2.078521
494  2.078100
495  2.109900
496  2.185761
497  2.088345

[498 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2519  0.458908
2520  0.438131
2521  0.448393
2522  0.434352
2523  0.438346

[2524 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2238  0.811108
2239  0.766925
2240  0.766304
2241  0.759881
2242  0.786889

[2243 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2019  0.917392
2020  0.883556
2021  0.881843
2022  0.905586
2023  0.842622

[2024 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
936  0.650497
937  0.670445
938  0.669121
939  0.654920
940  0.665842

[941 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2526  0.414330
2527  0.433830
2528  0.361505
2529  0.312539
2530  0.407040

[2531 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2444  1.111616
2445  1.059735
2446  1.088709
2447  1.003409
2448  0.968853

[2449 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1984  1.630092
1985  1.636939
1986  1.690785
1987  1.652220
1988  1.788356

[1989 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1967  0.582908
1968  0.640170
1969  0.601879
1970  0.540197
1971  0.527773

[1972 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1945  1.307634
1946  1.225901
1947  1.252048
1948  1.212174
1949  1.053968

[1950 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1811  2.058070
1812  1.959876
1813  2.017857
1814  1.827766
1815  1.675801

[1816 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1552  1.850687
1553  1.824263
1554  1.717276
1555  1.806630
1556  1.713994

[1557 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1393  0.914121
1394  0.788495
1395  0.826208
1396  0.779500
1397  0.789194

[1398 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
916  0.396785
917  0.368636
918  0.360272
919  0.371522
920  0.362201

[921 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1842  0.805881
1843  0.787610
1844  0.813544
1845  0.783620
1846  0.804055

[1847 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1366  0.881050
1367  0.844346
1368  0.871356
1369  0.788531
1370  0.735501

[1371 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1104  1.373119
1105  1.296159
1106  1.313915
1107  1.178182
1108  1.084528

[1109 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1273  1.005452
1274  0.978940
1275  0.963163
1276  0.774384
1277  0.772886

[1278 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1278  1.386937
1279  1.367397
1280  1.367072
1281  1.315199
1282  1.237199

[1283 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
518  0.007282
519  0.048862
520 -0.010984
521  0.110963
522  0.120735

[523 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1285  0.986902
1286  0.918332
1287  0.941002
1288  0.825111
1289  0.734712

[1290 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
789  0.628895
790  0.680464
791  0.711127
792  0.644610
793  0.521972

[794 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1265  0.930632
1266  0.928119
1267  0.941492
1268  0.994617
1269  0.945990

[1270 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1329  0.555401
1330  0.652653
1331  0.666741
1332  0.943506
1333  1.024852

[1334 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1355  1.777317
1356  1.765143
1357  1.811572
1358  1.713898
1359  1.596452

[1360 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1280  0.868670
1281  0.936403
1282  0.893931
1283  0.994713
1284  0.885108

[1285 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1179  1.023028
1180  0.983368
1181  0.784155
1182  0.799430
1183  0.691280

[1184 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1241  0.513500
1242  0.586111
1243  0.566453
1244  0.587364
1245  0.552172

[1246 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1237  1.106201
1238  1.056737
1239  1.006883
1240  0.881838
1241  0.836634

[1242 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1234  0.947693
1235  0.902158
1236  0.916336
1237  0.924066
1238  0.864366

[1239 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1234  1.272022
1235  1.250386
1236  1.307121
1237  1.466559
1238  1.482095

[1239 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1047  0.617693
1048  0.630986
1049  0.476844
1050  0.451065
1051  0.551351

[1052 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1010  0.570488
1011  0.645481
1012  0.684352
1013  0.615029
1014  0.488835

[1015 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
972  0.756639
973  0.747288
974  0.759805
975  0.711619
976  0.652074

[977 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1269  1.151950
1270  1.161293
1271  1.143275
1272  1.162871
1273  1.076332

[1274 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
931 -0.056690
932 -0.141083
933 -0.065871
934 -0.177719
935 -0.230339

[936 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
690  0.947698
691  0.918462
692  0.908839
693  0.957369
694  0.886330

[695 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
788  0.679790
789  0.607579
790  0.667975
791  0.561184
792  0.550703

[793 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
842  1.811243
843  1.870468
844  1.885802
845  1.981860
846  1.964482

[847 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
860  0.984718
861  0.948305
862  0.955617
863  0.890643
864  0.828895

[865 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
831  0.934138
832  0.921382
833  0.917535
834  0.923116
835  0.830308

[836 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
834  0.261822
835  0.290225
836  0.224782
837  0.308230
838  0.341712

[839 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
769  1.267562
770  1.302002
771  1.289895
772  1.352357
773  1.189528

[774 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
821  1.194373
822  1.200572
823  1.201669
824  1.244428
825  1.153571

[826 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
787  1.173572
788  1.142144
789  1.168315
790  1.224917
791  1.127616

[792 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
746  1.482465
747  1.575908
748  1.541196
749  1.454041
750  1.353315

[751 rows x 1 columns]

            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
729  0.741000
730  0.748946
731  0.719518
732  0.655034
733  0.687123

[734 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
512  0.874610
513  0.840298
514  0.852781
515  0.620308
516  0.409403

[517 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
778  1.246665
779  1.119554
780  1.129894
781  1.034612
782  0.997813

[783 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
124  0.501563
125  0.467419
126  0.469896
127  0.415425
128  0.379577

[129 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
667  0.153732
668  0.118010
669  0.154620
670  0.069662
671  0.042459

[672 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
590  0.833460
591  0.784736
592  0.852879
593  0.826835
594  0.753687

[595 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
848  0.709961
849  0.720675
850  0.780399
851  0.859179
852  1.136578

[853 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
562  1.207216
563  1.237945
564  1.239375
565  1.319522
566  1.257802

[567 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
882 -0.099335
883 -0.120640
884 -0.154403
885 -0.072537
886 -0.156284

[887 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
706  0.849470
707  0.834295
708  0.814600
709  0.856284
710  0.826809

[711 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1152  1.141677
1153  1.100074
1154  1.093759
1155  0.999685
1156  1.134410

[1157 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
914  1.174402
915  1.167185
916  1.130296
917  1.098950
918  0.948113

[919 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
290  2.063325
291  2.103505
292  2.100695
293  1.957238
294  1.980442

[295 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
961  0.568116
962  0.571075
963  0.512529
964  0.302179
965  0.623949

[966 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
635  0.583260
636  0.572020
637  0.573508
638  0.554002
639  0.446249

[640 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1835  0.505608
1836  0.513316
1837  0.519132
1838  0.512788
1839  0.485169

[1840 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
782  1.775642
783  1.711427
784  1.744918
785  1.598492
786  1.336397

[787 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
650  1.001324
651  0.941478
652  0.917790
653  0.881202
654  0.804912

[655 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
597  0.830014
598  0.809715
599  0.828718
600  0.806503
601  0.791269

[602 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
774  1.030558
775  1.007049
776  1.023602
777  0.968194
778  0.911985

[779 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
636  2.239479
637  2.230213
638  2.204156
639  2.140771
640  1.915416

[641 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1193  0.516654
1194  0.473185
1195  0.458756
1196  0.439170
1197  0.490743

[1198 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
760  0.555853
761  0.568759
762  0.558607
763  0.557319
764  0.523353

[765 rows x 1 columns]
    0
0 NaN
1 NaN
2 NaN
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1357  1.011281
1358  0.940293
1359  1.033300
1360  0.926332
1361  0.817959

[1362 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
827  0.502545
828  0.475434
829  0.540551
830  0.493003
831  0.469747

[832 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
869  1.158442
870  1.121851
871  1.146627
872  1.203246
873  1.126539

[874 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
195  1.745291
196  1.709021
197  1.771465
198  1.777928
199  1.661991

[200 rows x 1 columns]
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
36 NaN
37 NaN
38 NaN
39 NaN
40 NaN
41 NaN
42 NaN
43 NaN
44 NaN
45 NaN
46 NaN
47 NaN
48 NaN
49 NaN
50 NaN
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
771  0.794603
772  0.772271
773  0.768289
774  0.838454
775  0.794308

[776 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
854  0.784063
855  0.760773
856  0.753644
857  0.693778
858  0.677720

[859 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1420  0.622951
1421  0.612417
1422  0.597580
1423  0.513873
1424  0.497295

[1425 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1395  0.655599
1396  0.638248
1397  0.639664
1398  0.619413
1399  0.593673

[1400 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1006  0.690708
1007  0.648832
1008  0.718330
1009  0.649004
1010  0.762820

[1011 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
657  1.020455
658  1.006082
659  1.047920
660  0.795973
661  0.862603

[662 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
476  2.206937
477  2.148854
478  2.130459
479  2.006335
480  1.767048

[481 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
667  1.092391
668  1.038856
669  1.100893
670  1.223231
671  1.045923

[672 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1100  0.367292
1101  0.376319
1102  0.367074
1103  0.329531
1104  0.261596

[1105 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
114  2.156101
115  2.220577
116  2.011256
117  1.780744
118  1.538490

[119 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
656  0.951730
657  0.929124
658  0.976843
659  0.950765
660  0.867626

[661 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1244  1.598241
1245  1.590528
1246  1.587476
1247  1.770556
1248  1.663385

[1249 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
760  0.949212
761  0.939637
762  0.960075
763  0.959357
764  0.920656

[765 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
210  1.247241
211  1.236544
212  1.188267
213  1.109557
214  1.106897

[215 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1212  0.646803
1213  0.605094
1214  0.622950
1215  0.328807
1216  0.174196

[1217 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1201  0.797545
1202  0.779758
1203  0.787881
1204  0.740495
1205  0.741160

[1206 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1268  1.214384
1269  1.277361
1270  1.317724
1271  1.428231
1272  1.326664

[1273 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
350  0.492918
351  0.485937
352  0.499348
353  0.465519
354  0.448571

[355 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1902  0.324657
1903  0.333867
1904  0.379595
1905  0.597481
1906  0.694999

[1907 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1376  0.718032
1377  0.660487
1378  0.665473
1379  0.558129
1380  0.586837

[1381 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
686  1.314115
687  1.328204
688  1.207638
689  1.176331
690  0.942206

[691 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1848  0.782318
1849  0.779225
1850  0.796737
1851  0.875390
1852  0.856738

[1853 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
691  1.995814
692  1.982494
693  1.980440
694  1.854441
695  1.781600

[696 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
895  0.941921
896  0.924423
897  0.961544
898  0.907770
899  1.056661

[900 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
795  1.592479
796  1.572035
797  1.633988
798  1.564751
799  1.580328

[800 rows x 1 columns]

            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
663  1.367814
664  1.376916
665  1.389343
666  1.353764
667  1.294111

[668 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
805  1.661054
806  1.696024
807  1.734964
808  1.656796
809  1.456964

[810 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
773  0.555392
774  0.522038
775  0.503933
776  0.398076
777  0.339749

[778 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
571  0.472363
572  0.487735
573  0.481313
574  0.514485
575  0.673235

[576 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
664  0.339383
665  0.123043
666  0.068028
667  0.116044
668 -0.138604

[669 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1244  1.540298
1245  1.519233
1246  1.474525
1247  1.279933
1248  1.199961

[1249 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
938  0.727845
939  0.717506
940  0.763156
941  0.695765
942  0.623554

[943 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
899  1.632440
900  1.620723
901  1.623256
902  1.620870
903  1.551096

[904 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
597  0.608651
598  0.588969
599  0.565144
600  0.530133
601  0.463473

[602 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
833  0.814183
834  0.787932
835  0.761878
836  0.730897
837  0.685063

[838 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1354  0.894747
1355  0.941383
1356  0.944204
1357  1.009900
1358  1.049066

[1359 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1893  1.142548
1894  1.147385
1895  1.131280
1896  1.117076
1897  1.080976

[1898 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1431  0.936374
1432  0.917491
1433  1.000617
1434  0.948380
1435  0.861943

[1436 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1294  1.035557
1295  0.994247
1296  0.975935
1297  0.926681
1298  0.914511

[1299 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
819  0.385031
820  0.369990
821  0.400556
822  0.324074
823  0.267707

[824 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
789  0.737990
790  0.733718
791  0.769602
792  0.777597
793  0.650909

[794 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
796  1.943609
797  1.907529
798  1.898059
799  1.866172
800  1.648924

[801 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
759  0.770569
760  0.739074
761  0.763885
762  0.722056
763  0.787481

[764 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
687  1.088028
688  1.036487
689  1.026332
690  0.985825
691  0.824899

[692 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
673  0.919367
674  0.891841
675  0.906553
676  0.903914
677  0.890186

[678 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
358  1.981893
359  2.012290
360  1.838399
361  1.651601
362  1.519248

[363 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
844  2.357567
845  2.355538
846  2.355771
847  2.300491
848  2.152221

[849 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
379  1.075538
380  1.091343
381  1.112526
382  1.013456
383  0.934174

[384 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1325  0.423651
1326  0.411762
1327  0.407637
1328  0.346534
1329  0.237868

[1330 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
914  1.945729
915  1.863070
916  1.861487
917  1.706675
918  1.949675

[919 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
440  1.022383
441  0.983495
442  1.046535
443  1.152374
444  1.101786

[445 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
94  0.530629
95  0.592558
96  0.656097
97  0.637973
98  0.587355

[99 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
748  0.982386
749  1.032554
750  1.048563
751  1.019998
752  0.995447

[753 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
754  1.617101
755  1.601266
756  1.584163
757  1.590384
758  1.468302

[759 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1236  0.958508
1237  0.948052
1238  0.959704
1239  0.946357
1240  1.218348

[1241 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1279  0.689740
1280  0.700646
1281  0.732551
1282  0.692692
1283  0.672228

[1284 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
747  1.646737
748  1.736984
749  1.732268
750  1.710073
751  1.612376

[752 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
883  1.474934
884  1.495265
885  1.521505
886  1.558874
887  1.445496

[888 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
821  1.652215
822  1.585267
823  1.612000
824  1.619313
825  1.642521

[826 rows x 1 columns]
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
36 NaN
37 NaN
38 NaN
39 NaN
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
542  0.806143
543  0.861584
544  0.941725
545  0.948947
546  0.860893

[547 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
246  0.300011
247  0.290705
248  0.309557
249  0.278704
250  0.239708

[251 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
847  0.467654
848  0.419285
849  0.406629
850  0.429095
851  0.275785

[852 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
389  1.441452
390  1.481673
391  1.492634
392  1.405369
393  1.348737

[394 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
62  0.446380
63  0.313436
64  0.351387
65  0.206923
66  0.198784

[67 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1247 -0.054349
1248  0.007604
1249  0.018472
1250 -0.044486
1251 -0.030550

[1252 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1204 -0.087168
1205 -0.103742
1206 -0.171095
1207 -0.027906
1208  0.043558

[1209 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
776  1.007398
777  0.986829
778  1.009510
779  0.944635
780  0.919139

[781 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
735  1.326455
736  1.257790
737  1.227646
738  1.309256
739  1.254637

[740 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1199  0.770103
1200  0.748481
1201  0.772271
1202  0.746035
1203  0.722710

[1204 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
841  1.413106
842  1.369152
843  1.329651
844  1.372990
845  1.259354

[846 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
762  0.532292
763  0.596220
764  0.727102
765  0.766973
766  0.505897

[767 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
773  1.721902
774  1.715720
775  1.699503
776  1.577176
777  1.421359

[778 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
705  0.490756
706  0.512468
707  0.522824
708  0.636010
709  0.337244

[710 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
228  2.336933
229  2.312850
230  2.333240
231  2.354690
232  2.113493

[233 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
743  1.204168
744  1.208902
745  1.232413
746  1.145199
747  1.135036

[748 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
844  1.224675
845  1.214218
846  1.254697
847  1.443884
848  1.218040

[849 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
225  1.306202
226  1.296482
227  1.288976
228  1.253323
229  1.194755

[230 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
892  0.677886
893  0.677922
894  0.705735
895  0.824696
896  0.776115

[897 rows x 1 columns]

            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
519  1.486166
520  1.517565
521  1.496330
522  1.300392
523  1.118739

[524 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
645  1.040542
646  1.051894
647  1.008656
648  0.908911
649  0.759939

[650 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
839  0.955637
840  0.925883
841  0.913629
842  0.848430
843  0.919960

[844 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
271  1.091758
272  1.060720
273  0.996301
274  0.960276
275  0.835708

[276 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1155  0.190766
1156  0.154671
1157 -0.040338
1158  0.106609
1159  0.284153

[1160 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
756  1.022673
757  1.007465
758  1.000931
759  0.984943
760  0.925555

[761 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
675  1.090574
676  1.036550
677  1.034157
678  0.989759
679  0.876274

[680 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
635  1.181081
636  1.087967
637  1.113167
638  1.202904
639  1.225026

[640 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
219  0.687518
220  0.635290
221  0.665018
222  0.638532
223  0.610773

[224 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
599  2.755169
600  2.716914
601  2.691368
602  2.525955
603  2.384136

[604 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
720  0.388039
721  0.327452
722  0.336416
723  0.326657
724  0.250717

[725 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1554  0.873495
1555  1.021515
1556  0.994053
1557  0.938310
1558  0.861607

[1559 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
644  1.301351
645  1.308404
646  1.372081
647  1.299924
648  1.258750

[649 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
96   1.958560
97   2.081713
98   2.106151
99   2.027888
100  1.848913

[101 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
431  1.152177
432  1.107289
433  1.087282
434  1.188937
435  1.179206

[436 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
848  0.770236
849  0.755142
850  0.783950
851  0.777627
852  0.628309

[853 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
968  0.636993
969  0.674160
970  0.643618
971  0.657918
972  0.627042

[973 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1214  0.693514
1215  0.668260
1216  0.679288
1217  0.700212
1218  0.686878

[1219 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
535  0.065233
536  0.076978
537 -0.097876
538 -0.060391
539  0.008733

[540 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
787  0.857935
788  0.805190
789  0.836856
790  0.749780
791  0.672960

[792 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
720  1.919177
721  1.842172
722  1.846013
723  1.913611
724  1.824430

[725 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1371  1.267640
1372  1.490434
1373  1.600174
1374  1.534701
1375  1.437495

[1376 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1495  1.827846
1496  1.779197
1497  1.786133
1498  1.842449
1499  1.689188

[1500 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1228  0.496494
1229  0.647521
1230  0.553802
1231  0.555496
1232  0.413084

[1233 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1239  0.336915
1240  0.299021
1241  0.325144
1242  0.335817
1243  0.365888

[1244 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
901  2.243149
902  2.227018
903  2.291037
904  2.197894
905  2.075687

[906 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1178  0.649569
1179  0.633519
1180  0.593137
1181  0.599306
1182  0.641892

[1183 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
735  0.259603
736  0.316152
737  0.338057
738  0.308152
739  0.312394

[740 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
289  0.671961
290  0.779284
291  0.744876
292  0.717825
293  0.719207

[294 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1091  0.711870
1092  0.668337
1093  0.542934
1094  0.462630
1095  0.787922

[1096 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
867  0.793059
868  0.830823
869  0.849371
870  0.713002
871  0.727137

[872 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
767  0.455760
768  0.390986
769  0.432364
770  0.430363
771  0.369838

[772 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
671  0.913792
672  0.962696
673  0.997762
674  0.897992
675  0.857488

[676 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
937  1.326723
938  1.257490
939  1.242717
940  1.350285
941  1.261646

[942 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
868  0.566834
869  0.584927
870  0.602320
871  0.581363
872  0.592191

[873 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
735  0.417903
736  0.424740
737  0.411749
738  0.377928
739  0.381703

[740 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
265  1.473892
266  1.455601
267  1.484839
268  1.486475
269  1.412898

[270 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1454  1.143796
1455  1.129302
1456  1.064770
1457  1.003361
1458  0.897122

[1459 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
601  0.733653
602  0.703670
603  0.838399
604  0.813643
605  0.670273

[606 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
807  1.489669
808  1.437682
809  1.526942
810  1.482243
811  1.532654

[812 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
723  0.508195
724  0.455520
725  0.462492
726  0.601625
727  0.558044

[728 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
346 -0.108634
347 -0.113996
348 -0.099400
349 -0.150280
350 -0.111155

[351 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1943  0.575389
1944  0.507140
1945  0.528161
1946  0.507130
1947  0.509688

[1948 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
734  0.470357
735  0.425269
736  0.431648
737  0.438543
738  0.350387

[739 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
859  0.544054
860  0.611134
861  0.642951
862  0.641238
863  0.594800

[864 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
832  1.371540
833  1.381644
834  1.274545
835  1.213773
836  1.237468

[837 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1267  1.268443
1268  1.243524
1269  1.252015
1270  1.114057
1271  1.001417

[1272 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
996   1.083742
997   1.082561
998   1.042441
999   0.968610
1000  0.930885

[1001 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
774  0.883759
775  0.914944
776  0.923497
777  0.861888
778  0.760852

[779 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
524  1.132574
525  1.097366
526  1.121906
527  1.100860
528  1.026296

[529 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
337  0.565568
338  0.567307
339  0.566855
340  0.547909
341  0.498246

[342 rows x 1 columns]

     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
36 NaN
37 NaN
38 NaN
39 NaN
40 NaN
41 NaN
42 NaN
43 NaN
44 NaN
45 NaN
46 NaN
47 NaN
48 NaN
49 NaN
50 NaN
51 NaN
52 NaN
53 NaN
54 NaN
55 NaN
56 NaN
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1247  0.818373
1248  0.813471
1249  0.790174
1250  0.721262
1251  0.650208

[1252 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
584 -0.529654
585 -0.492803
586 -0.465265
587 -0.369418
588 -0.478539

[589 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
704  0.724870
705  0.695053
706  0.695045
707  0.797093
708  0.808819

[709 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
828  1.220901
829  1.228858
830  1.200979
831  1.063356
832  0.963737

[833 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
681  0.960637
682  0.927813
683  0.965232
684  0.960854
685  0.930077

[686 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
825  1.273471
826  1.262502
827  1.240654
828  1.149721
829  1.039406

[830 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
664 -0.018652
665  0.006108
666  0.023441
667  0.160386
668  0.198487

[669 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
630  0.644551
631  0.649265
632  0.609110
633  0.603025
634  0.537160

[635 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1968  1.553071
1969  1.524234
1970  1.536821
1971  1.487630
1972  1.376818

[1973 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
661  0.461027
662  0.482225
663  0.462592
664  0.528084
665  0.469218

[666 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1339  0.414775
1340  0.399644
1341  0.462077
1342  0.419307
1343  0.479087

[1344 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1453  1.080940
1454  1.079891
1455  1.011480
1456  0.988820
1457  1.159142

[1458 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1064  0.620497
1065  0.551738
1066  0.587057
1067  0.576292
1068  0.527077

[1069 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
662  0.916296
663  0.947632
664  0.976752
665  0.970711
666  0.687421

[667 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
298  0.896884
299  0.879170
300  0.860672
301  0.795263
302  0.720834

[303 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
732  0.914441
733  0.823230
734  0.842243
735  0.781425
736  0.712719

[737 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
751  1.571011
752  1.579668
753  1.527103
754  1.570864
755  1.419303

[756 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
785  0.624792
786  0.562149
787  0.612812
788  0.617671
789  0.718133

[790 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
586  1.042934
587  1.055759
588  1.061135
589  1.031105
590  0.968757

[591 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
715  0.249024
716  0.328704
717  0.330799
718  0.230134
719  0.207397

[720 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
790 -0.314828
791 -0.329204
792 -0.321529
793 -0.364677
794 -0.347566

[795 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
855  0.959902
856  0.945560
857  0.904417
858  0.905899
859  0.795364

[860 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
140  1.030280
141  0.942074
142  0.929041
143  0.853668
144  0.785862

[145 rows x 1 columns]
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
36 NaN
37 NaN
38 NaN
39 NaN
40 NaN
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
855  0.466213
856  0.520884
857  0.455506
858  0.504405
859  0.521923

[860 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
653  2.355822
654  2.307245
655  2.273032
656  2.111850
657  1.865580

[658 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
984  0.732960
985  0.691754
986  0.687176
987  0.654220
988  0.596587

[989 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1700  0.487233
1701  0.358654
1702  0.398470
1703  0.397454
1704  0.384764

[1705 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
852  1.466902
853  1.442341
854  1.366405
855  1.374963
856  1.357652

[857 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
903  1.171070
904  1.209227
905  1.219029
906  1.243202
907  1.157609

[908 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
780  1.194374
781  1.265646
782  1.203355
783  1.387881
784  1.640793

[785 rows x 1 columns]
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
36 NaN
37 NaN
38 NaN
39 NaN
40 NaN
41 NaN
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
843  1.127076
844  1.225132
845  1.206061
846  1.199050
847  1.130384

[848 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1353  0.633553
1354  0.581017
1355  0.577144
1356  0.569196
1357  0.660659

[1358 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
698  1.066016
699  1.069578
700  0.998912
701  1.220603
702  1.190801

[703 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
650  0.993991
651  0.989249
652  0.923445
653  0.954398
654  0.912376

[655 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
599  0.676287
600  0.626717
601  0.567954
602  0.580404
603  0.471194

[604 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
505  1.579656
506  1.600501
507  1.651278
508  1.493348
509  1.517075

[510 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
757  0.331091
758  0.305303
759  0.330160
760  0.393317
761  0.377217

[762 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
150  1.138110
151  1.153778
152  1.031326
153  0.840496
154  0.705840

[155 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
743  1.628897
744  1.627497
745  1.591326
746  1.554308
747  1.387059

[748 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
654  0.223380
655  0.211302
656  0.268505
657  0.259533
658  0.371618

[659 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
680  1.031928
681  0.982823
682  1.011591
683  0.996877
684  0.872277

[685 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
594  1.964594
595  1.938965
596  1.974739
597  2.123574
598  2.075371

[599 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
766  1.614460
767  1.581997
768  1.571387
769  1.525935
770  1.431969

[771 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
578  1.578802
579  1.568096
580  1.631067
581  1.551395
582  1.375586

[583 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
640  0.498578
641  0.475675
642  0.493011
643  0.608122
644  0.631589

[645 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1006  1.216837
1007  1.168852
1008  1.182581
1009  1.092663
1010  0.938628

[1011 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
933  0.704048
934  0.686275
935  0.756076
936  0.782793
937  0.636681

[938 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
577  1.657225
578  1.673396
579  1.630287
580  1.449800
581  1.308844

[582 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
796  0.866800
797  0.873753
798  0.844199
799  0.761757
800  0.717670

[801 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1220  0.771389
1221  0.722144
1222  0.721625
1223  0.722103
1224  0.729192

[1225 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1190  1.816451
1191  1.776339
1192  1.813251
1193  1.761557
1194  1.652819

[1195 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
920  1.064384
921  1.024744
922  0.959633
923  0.852890
924  0.402528

[925 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
677  0.683164
678  0.670354
679  0.669855
680  0.620720
681  0.645711

[682 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1007  1.212976
1008  1.279925
1009  1.198325
1010  0.992512
1011  0.717992

[1012 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
214  1.704963
215  1.627768
216  1.565647
217  1.584885
218  1.360246

[219 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
665  2.740945
666  2.625961
667  2.592499
668  2.402666
669  2.105058

[670 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
699  0.736508
700  0.823679
701  0.815062
702  0.769848
703  0.663425

[704 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
739  0.996678
740  1.047508
741  1.031390
742  0.986625
743  0.900730

[744 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
710  1.111827
711  1.086744
712  1.070231
713  0.986291
714  0.827235

[715 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
104  0.512037
105  0.695125
106  0.620125
107  0.583893
108  0.564270

[109 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1454  0.823204
1455  0.689619
1456  0.683549
1457  0.669170
1458  1.001398

[1459 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
881  1.153105
882  1.150907
883  1.169742
884  1.072743
885  1.037814

[886 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
681  0.281135
682  0.278886
683  0.133652
684  0.417958
685  0.328269

[686 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1214  0.871650
1215  0.801120
1216  0.847618
1217  0.794834
1218  1.040660

[1219 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
790  1.647278
791  1.607239
792  1.518299
793  1.484609
794  1.455411

[795 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1239  0.974828
1240  1.004694
1241  1.037703
1242  1.030556
1243  0.826933

[1244 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1244  0.383469
1245  0.367763
1246  0.350930
1247  0.346877
1248  0.290862

[1249 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1236  0.702535
1237  0.706523
1238  0.680485
1239  0.715110
1240  0.604034

[1241 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
940  0.572850
941  0.544463
942  0.561653
943  0.476390
944  0.428811

[945 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
851  1.349029
852  1.178588
853  1.162039
854  1.035257
855  1.121897

[856 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
798  0.741241
799  0.688504
800  0.683835
801  0.600555
802  0.532646

[803 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
838  0.426768
839  0.449285
840  0.479170
841  0.610757
842  0.578587

[843 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
750  0.592949
751  0.642915
752  0.646912
753  0.681880
754  0.636620

[755 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
422  1.649406
423  1.642869
424  1.653308
425  1.610251
426  1.620744

[427 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
857  0.302651
858  0.297202
859  0.296521
860  0.306500
861  0.306186

[862 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
784  0.492420
785  0.477778
786  0.499979
787  0.494271
788  0.447588

[789 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
487  1.070405
488  1.064140
489  1.059028
490  1.017633
491  1.047323

[492 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1232  1.354330
1233  1.402276
1234  1.411146
1235  1.378247
1236  1.260795

[1237 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1215  1.038005
1216  1.104848
1217  1.092289
1218  1.121103
1219  1.228019

[1220 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
441  0.022366
442 -0.009953
443 -0.018284
444 -0.092733
445 -0.162402

[446 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
718  1.118840
719  1.092014
720  1.204564
721  1.102173
722  1.030769

[723 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
524  1.923437
525  1.904215
526  1.861395
527  1.737406
528  1.456815

[529 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1056  1.235239
1057  1.161663
1058  1.104731
1059  0.916770
1060  0.913862

[1061 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1241  0.646321
1242  0.666266
1243  0.638926
1244  0.737146
1245  0.681504

[1246 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1306  0.447250
1307  0.418620
1308  0.454748
1309  0.587335
1310  0.486641

[1311 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1262  0.036910
1263 -0.016275
1264 -0.079443
1265  0.054182
1266 -0.040797

[1267 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
635  0.836096
636  0.809237
637  0.822440
638  1.001396
639  0.943105

[640 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
716  1.172466
717  1.244181
718  1.198213
719  1.184105
720  1.056335

[721 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
633  1.162115
634  1.161428
635  1.149747
636  1.163485
637  1.077455

[638 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1379  1.373599
1380  1.346480
1381  1.216358
1382  1.265576
1383  1.140844

[1384 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
648  0.734874
649  0.740826
650  0.728607
651  0.643081
652  0.516407

[653 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
981  1.202534
982  1.077775
983  1.127948
984  1.278882
985  1.113419

[986 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1418  0.611181
1419  0.641892
1420  0.623378
1421  0.733316
1422  0.755308

[1423 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
159  0.847420
160  0.897491
161  0.929558
162  0.858007
163  0.814394

[164 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1232  1.483323
1233  1.453666
1234  1.423790
1235  1.360805
1236  1.163311

[1237 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
714  1.291854
715  1.249667
716  1.300265
717  1.214779
718  1.225125

[719 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
218  1.815597
219  1.800274
220  1.794973
221  1.770858
222  1.348422

[223 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
820  0.931351
821  0.918328
822  0.952281
823  0.927887
824  0.878948

[825 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1208  0.713534
1209  0.734922
1210  0.688045
1211  0.821910
1212  0.766208

[1213 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
725  0.847505
726  0.839163
727  0.821132
728  0.772120
729  0.645283

[730 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1276  1.205320
1277  1.101879
1278  1.105203
1279  1.008104
1280  0.955328

[1281 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
631  1.377474
632  1.386105
633  1.390854
634  1.318168
635  1.241645

[636 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
822  1.913249
823  1.873932
824  1.910619
825  1.921446
826  1.678953

[827 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
833  0.738669
834  0.744354
835  0.628641
836  0.521832
837  0.498212

[838 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
362  0.984381
363  1.039640
364  1.021951
365  0.894158
366  0.794784

[367 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
800  1.500964
801  1.423547
802  1.356077
803  1.211296
804  1.086434

[805 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
876  1.152421
877  1.090294
878  1.018522
879  0.809327
880  0.714924

[881 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1260  1.428564
1261  1.400839
1262  1.420643
1263  1.343203
1264  1.259975

[1265 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
821  0.676032
822  0.672863
823  0.690636
824  0.694887
825  0.696327

[826 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
831  0.748366
832  0.738438
833  0.644384
834  0.769811
835  0.297734

[836 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
837  0.933417
838  0.936575
839  0.880862
840  0.849693
841  0.755372

[842 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
673  0.653451
674  0.636283
675  0.672927
676  0.689621
677  0.654922

[678 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
484  0.832070
485  0.814291
486  0.758058
487  0.598126
488  0.488129

[489 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
601  0.869665
602  0.903568
603  0.858017
604  0.744801
605  0.330082

[606 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
794  0.974194
795  0.956628
796  0.981899
797  0.926698
798  0.858814

[799 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
461  0.690483
462  0.651323
463  0.629132
464  0.688129
465  0.609221

[466 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
924  0.530691
925  0.584603
926  0.578025
927  0.449313
928  0.221383

[929 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
585  2.007546
586  2.020600
587  2.012200
588  1.984673
589  1.984361

[590 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
864  1.582682
865  1.562541
866  1.566517
867  1.476199
868  1.400522

[869 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
629  0.420949
630  0.405781
631  0.467432
632  0.366749
633  0.277692

[634 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
213  0.959513
214  0.936936
215  0.882395
216  0.786806
217  0.709847

[218 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
947  0.410217
948  0.409961
949  0.433001
950  0.372913
951  0.367644

[952 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
800  0.475213
801  0.515325
802  0.313900
803  0.571159
804  0.396270

[805 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
494  0.971623
495  1.003615
496  0.916387
497  1.035914
498  1.024074

[499 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
821  1.077270
822  1.060754
823  1.106304
824  1.052498
825  0.970507

[826 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
834  1.495184
835  1.462836
836  1.497886
837  1.455396
838  1.327612

[839 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1236  0.670005
1237  0.729558
1238  0.749443
1239  0.936263
1240  0.783564

[1241 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
711  0.154040
712  0.138137
713  0.089670
714  0.074895
715  0.005800

[716 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
823  0.817466
824  0.782404
825  0.798495
826  0.707045
827  0.688671

[828 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1301  1.699578
1302  1.673707
1303  1.684532
1304  1.647342
1305  1.612023

[1306 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
733  1.247392
734  1.245680
735  1.258793
736  1.123668
737  1.069431

[738 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
565  0.703102
566  0.660777
567  0.686505
568  0.684232
569  0.539113

[570 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
303  0.897229
304  0.851887
305  0.813101
306  0.779617
307  0.709898

[308 rows x 1 columns]
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
36 NaN
37 NaN
38 NaN
39 NaN
40 NaN
41 NaN
42 NaN
43 NaN
44 NaN
45 NaN
46 NaN
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
651  0.649979
652  0.643664
653  0.631250
654  0.555378
655  0.505419

[656 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
625  0.200389
626  0.147426
627  0.145066
628 -0.124760
629 -0.277698

[630 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1255  0.602113
1256  0.529125
1257  0.538336
1258  0.421497
1259  0.275166

[1260 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
220  0.947454
221  0.877280
222  0.817017
223  0.842086
224  0.788465

[225 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1373  1.994430
1374  1.982560
1375  1.931306
1376  1.820802
1377  1.704857

[1378 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
839  0.554106
840  0.538845
841  0.563636
842  0.547041
843  0.543822

[844 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
752  2.292347
753  2.261053
754  2.286109
755  2.190771
756  1.969542

[757 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
480  0.942099
481  0.917846
482  0.958612
483  0.911578
484  0.886910

[485 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1071  1.047113
1072  1.027616
1073  0.857746
1074  0.921028
1075  0.724838

[1076 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
276  1.448404
277  1.459948
278  1.345637
279  1.314862
280  1.486176

[281 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1315  0.931652
1316  0.911515
1317  0.904116
1318  0.885215
1319  0.784557

[1320 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1556  0.758149
1557  0.801914
1558  0.867384
1559  0.801323
1560  0.868978

[1561 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
343  1.095467
344  1.103531
345  1.149176
346  1.112727
347  1.267973

[348 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
999   0.235456
1000  0.185376
1001  0.146735
1002  0.261860
1003  0.397437

[1004 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1180  0.082636
1181  0.121117
1182  0.169202
1183  0.146933
1184  0.222929

[1185 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
476  0.682410
477  0.653960
478  0.651490
479  0.550472
480  0.465162

[481 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
713  1.004652
714  0.994652
715  0.936646
716  1.020288
717  0.871926

[718 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
858  0.272780
859  0.325644
860  0.232721
861  0.328642
862  0.053278

[863 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
573  0.016697
574 -0.023556
575 -0.000872
576 -0.046085
577 -0.018868

[578 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
622  1.244440
623  1.294361
624  1.276699
625  1.310817
626  1.144403

[627 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
563  1.006500
564  0.934905
565  0.892910
566  0.734462
567  0.515639

[568 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
472  0.897428
473  0.874777
474  0.901257
475  0.770510
476  0.566503

[477 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
877  0.464253
878  0.476185
879  0.489957
880  0.496754
881  0.482471

[882 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
790  0.325927
791  0.313295
792  0.310213
793  0.264818
794  0.186902

[795 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1206  0.766085
1207  0.676024
1208  0.627988
1209  0.506593
1210  0.661635

[1211 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
82  1.634331
83  1.694690
84  1.671696
85  1.663870
86  1.464316

[87 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
694  1.316442
695  1.224189
696  1.347958
697  1.214960
698  1.224546

[699 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
646  1.145956
647  1.127931
648  1.171559
649  1.175580
650  1.091936

[651 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
663  0.776398
664  0.778651
665  0.780729
666  0.658500
667  0.751091

[668 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1010  1.147670
1011  1.265821
1012  1.216007
1013  1.016955
1014  0.979326

[1015 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
873  1.530209
874  1.537681
875  1.530152
876  1.468315
877  1.465770

[878 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
762  0.534618
763  0.476031
764  0.514638
765  0.742095
766  0.708461

[767 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1203  0.923695
1204  0.890054
1205  0.917875
1206  1.043252
1207  0.892149

[1208 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
691  1.321862
692  1.311537
693  1.357772
694  1.273314
695  1.159391

[696 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
529  0.649827
530  0.634862
531  0.662105
532  0.627765
533  0.654053

[534 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
986  0.619483
987  0.620793
988  0.534082
989  0.499226
990  0.500872

[991 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
907  1.380244
908  1.493819
909  1.523321
910  1.435516
911  1.373958

[912 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
347  0.874906
348  0.869331
349  0.863340
350  0.848786
351  0.775404

[352 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
197  0.825404
198  0.885746
199  0.879409
200  0.901785
201  0.702916

[202 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
719  0.836590
720  0.822807
721  0.761915
722  0.771489
723  0.712722

[724 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
751  0.543345
752  0.472411
753  0.475405
754  0.374836
755  0.281197

[756 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1871  1.010787
1872  1.014200
1873  0.973351
1874  0.893104
1875  0.826831

[1876 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
739  0.343084
740  0.314120
741  0.341607
742  0.477569
743  0.800764

[744 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
791  0.398822
792  0.392950
793  0.431081
794  0.472622
795  0.485257

[796 rows x 1 columns]

            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
532  0.810118
533  0.835129
534  0.871732
535  0.791499
536  0.692175

[537 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
692  1.022533
693  0.986662
694  0.970291
695  0.919426
696  0.842524

[697 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
902  0.884668
903  0.844400
904  0.884667
905  0.840476
906  0.984221

[907 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1059  0.661499
1060  0.632051
1061  0.634403
1062  0.579193
1063  0.561989

[1064 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
993  0.541425
994  0.526871
995  0.495057
996  0.498929
997  0.478781

[998 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
169  1.545442
170  1.481739
171  1.524447
172  1.514173
173  1.184584

[174 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
769  1.390609
770  1.322295
771  1.349531
772  1.458130
773  1.424468

[774 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1307  1.013523
1308  1.063783
1309  1.001180
1310  1.059411
1311  1.077333

[1312 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1239  0.297528
1240  0.312773
1241  0.339871
1242  0.353122
1243  0.394234

[1244 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
429  0.739650
430  0.728213
431  0.707476
432  0.648119
433  0.440605

[434 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
779  0.521846
780  0.514903
781  0.524124
782  0.471165
783  0.471442

[784 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1026  0.879556
1027  0.818116
1028  0.834736
1029  0.787091
1030  0.772330

[1031 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1280  1.996501
1281  1.955344
1282  1.956591
1283  1.941197
1284  1.924989

[1285 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1100  0.460375
1101  0.445375
1102  0.436120
1103  0.598851
1104  0.547729

[1105 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
726  1.564813
727  1.538399
728  1.508245
729  1.533567
730  1.689587

[731 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
771  1.703133
772  1.686371
773  1.701659
774  1.675556
775  1.514213

[776 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1391  0.988399
1392  0.976312
1393  0.922959
1394  0.936969
1395  0.852868

[1396 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1178  1.238637
1179  1.239681
1180  1.283228
1181  1.223881
1182  1.149646

[1183 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
624  1.065734
625  1.107714
626  1.163500
627  1.203231
628  1.149569

[629 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
424  0.733453
425  0.713716
426  0.684415
427  0.644720
428  0.539053

[429 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
798  0.659587
799  0.643171
800  0.662891
801  0.602343
802  0.506352

[803 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
670  1.367026
671  1.365720
672  1.364997
673  1.321811
674  1.257499

[675 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
165  1.248336
166  1.126765
167  1.083875
168  1.166910
169  1.298937

[170 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
900  1.119184
901  1.065285
902  1.075867
903  0.957601
904  1.227618

[905 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
815  0.683272
816  0.670500
817  0.654372
818  0.602157
819  0.564448

[820 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1225  0.394302
1226  0.429355
1227  0.398092
1228  0.435301
1229  0.490455

[1230 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
870  0.513192
871  0.492584
872  0.667891
873  0.585315
874  0.571877

[875 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
923  0.801912
924  0.771577
925  0.781862
926  0.909895
927  0.752029

[928 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
853  0.967750
854  0.945991
855  0.994581
856  1.030460
857  0.916462

[858 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
617  2.297891
618  2.259998
619  2.212711
620  2.074917
621  1.774737

[622 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
778  0.885955
779  0.862621
780  0.882873
781  0.817394
782  0.679692

[783 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1206  1.494373
1207  1.482626
1208  1.524141
1209  1.452089
1210  1.352182

[1211 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
654  0.609623
655  0.534557
656  0.544070
657  0.440458
658  0.426320

[659 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
783  0.901499
784  0.921883
785  0.940616
786  0.833495
787  0.920629

[788 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
910  0.595957
911  0.617073
912  0.576690
913  0.364239
914  0.277005

[915 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
818  1.209407
819  1.269860
820  1.249579
821  1.018291
822  1.073038

[823 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
832  0.873892
833  0.805202
834  0.685800
835  0.750607
836  0.669320

[837 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
621  0.784648
622  0.774105
623  0.729536
624  0.620907
625  0.613344

[626 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
751  0.877709
752  1.050051
753  1.044231
754  1.165180
755  0.916348

[756 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
640  1.237807
641  1.158479
642  1.132999
643  1.159605
644  1.208889

[645 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
875  0.441852
876  0.426113
877  0.399209
878  0.465165
879  0.383155

[880 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
890  1.264536
891  1.191949
892  1.230160
893  1.097473
894  1.094042

[895 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
703  0.401163
704  0.398435
705  0.422068
706  0.380627
707  0.406442

[708 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
955  0.957587
956  0.890094
957  0.898292
958  0.795184
959  0.749542

[960 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
245  0.724519
246  0.683133
247  0.645142
248  0.613929
249  0.544173

[250 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1096  0.619019
1097  0.650564
1098  0.642620
1099  0.659387
1100  0.622123

[1101 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
241  0.542325
242  0.721597
243  0.829971
244  1.137888
245  1.040451

[246 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1019  0.805919
1020  0.778613
1021  0.716304
1022  0.688515
1023  0.976652

[1024 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1183  0.630604
1184  0.575259
1185  0.598747
1186  0.497469
1187  0.467456

[1188 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
575  0.855495
576  0.914743
577  0.933232
578  0.855224
579  0.817336

[580 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
531  1.568119
532  1.560679
533  1.578349
534  1.533754
535  1.438291

[536 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
837  0.260394
838  0.226091
839  0.232154
840  0.233607
841  0.243194

[842 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
854  0.557214
855  0.544957
856  0.546486
857  0.544894
858  0.489658

[859 rows x 1 columns]

            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
738 -0.323250
739 -0.360989
740 -0.329953
741 -0.225217
742 -0.218837

[743 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
611  0.735643
612  0.752148
613  0.563761
614  0.494871
615  0.587248

[616 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
821  1.614855
822  1.658249
823  1.646393
824  1.500621
825  1.298026

[826 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
676  0.765776
677  0.835109
678  0.754031
679  0.639483
680  0.381964

[681 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1167  0.041171
1168  0.047796
1169  0.005868
1170  0.068929
1171 -0.092782

[1172 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1225  1.168486
1226  1.172454
1227  1.183544
1228  1.185830
1229  1.140159

[1230 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
847  0.907830
848  0.954874
849  0.933599
850  0.965724
851  0.905156

[852 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
827  1.398758
828  1.377248
829  1.264626
830  1.197940
831  1.062755

[832 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
888  1.582500
889  1.625271
890  1.681614
891  1.606626
892  1.650001

[893 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1217  0.907500
1218  0.911254
1219  0.914825
1220  0.783227
1221  0.719171

[1222 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
614  1.406869
615  1.343649
616  1.290153
617  1.210842
618  0.856945

[619 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
93  1.994624
94  2.061233
95  2.011280
96  1.914235
97  1.812895

[98 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
586  0.001380
587  0.051284
588  0.051762
589 -0.034897
590  0.041689

[591 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
761  0.142629
762  0.145538
763  0.189666
764  0.364994
765  0.476226

[766 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
537  1.109154
538  1.076669
539  1.088615
540  1.075208
541  1.023282

[542 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1224  0.914475
1225  0.903227
1226  0.919554
1227  0.906098
1228  0.909395

[1229 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1316  0.975804
1317  0.993499
1318  0.988885
1319  1.047780
1320  1.113554

[1321 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
871  1.261829
872  1.225809
873  1.260304
874  1.145611
875  1.099892

[876 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1216  1.097440
1217  1.160238
1218  1.189627
1219  1.117360
1220  1.054924

[1221 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
799  1.223538
800  1.222264
801  1.164543
802  1.074999
803  0.881901

[804 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
782  1.123466
783  1.088773
784  1.166936
785  1.326758
786  1.562708

[787 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
804  0.758046
805  0.700960
806  0.707143
807  0.667090
808  0.648852

[809 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
928  0.100034
929  0.043658
930  0.075895
931 -0.017903
932  0.011412

[933 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
643  1.706530
644  1.646660
645  1.688517
646  1.492863
647  1.533547

[648 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
249  0.563169
250  0.520709
251  0.444615
252  0.522711
253  0.610550

[254 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
636  1.476837
637  1.421070
638  1.589608
639  1.569468
640  1.582748

[641 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
620  0.406286
621  0.336677
622  0.533226
623  0.377016
624  0.278146

[625 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1140  1.299632
1141  1.493067
1142  1.489101
1143  1.661108
1144  1.565557

[1145 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1021  0.560967
1022  0.541332
1023  0.576359
1024  0.659378
1025  0.817267

[1026 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
770  2.128658
771  2.117220
772  2.165062
773  2.136539
774  1.984661

[775 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
650  0.257099
651  0.179221
652  0.101058
653 -0.051943
654 -0.066494

[655 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
761  0.361610
762  0.369326
763  0.386550
764  0.449889
765  0.427919

[766 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
189  1.181433
190  1.206559
191  1.246087
192  1.246500
193  1.145415

[194 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
859  0.789994
860  0.766172
861  0.765214
862  0.726707
863  0.689662

[864 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
845  1.507288
846  1.497395
847  1.571361
848  1.382948
849  1.211159

[850 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
722  0.832963
723  0.793966
724  0.855524
725  0.778931
726  0.687389

[727 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1007  1.618644
1008  1.665142
1009  1.554726
1010  1.425872
1011  1.291816

[1012 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
642  0.134147
643  0.144334
644  0.204138
645  0.236458
646  0.278521

[647 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
728  1.701650
729  1.694973
730  1.628760
731  1.369179
732  1.202435

[733 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1185  0.801860
1186  0.815153
1187  0.782609
1188  0.867199
1189  0.589331

[1190 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
77  0.406664
78  0.281254
79  0.311611
80  0.445746
81  0.398838

[82 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
71  0.327718
72  0.177711
73  0.147094
74  0.415916
75  0.381631

[76 rows x 1 columns]
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
761  1.180583
762  1.140614
763  1.134337
764  1.027574
765  0.999584

[766 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
325  0.361090
326  0.303015
327  0.348391
328  0.388074
329  0.292036

[330 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
970  0.776742
971  0.765325
972  0.749032
973  0.674017
974  0.638921

[975 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
995  1.239370
996  1.217080
997  1.232914
998  1.045420
999  0.930147

[1000 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
742  0.800617
743  0.806264
744  0.835211
745  0.908825
746  1.015202

[747 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
666  0.522082
667  0.494876
668  0.474315
669  0.446601
670  0.398254

[671 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
828  0.652062
829  0.622970
830  0.619551
831  0.596548
832  0.663328

[833 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
280  0.876553
281  0.864023
282  0.885907
283  0.851034
284  0.840866

[285 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1244  0.886385
1245  0.874816
1246  0.858931
1247  0.855327
1248  0.873426

[1249 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1298  1.145697
1299  1.099572
1300  1.052018
1301  1.099807
1302  1.009511

[1303 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
632  0.718511
633  0.737314
634  0.691824
635  0.744152
636  0.639179

[637 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
689  1.586373
690  1.656623
691  1.475351
692  1.559318
693  1.602654

[694 rows x 1 columns]

            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
791  0.669745
792  0.648604
793  0.632032
794  0.574825
795  0.154111

[796 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
697  1.451334
698  1.443640
699  1.405345
700  1.333209
701  1.310312

[702 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1214  0.624474
1215  0.602272
1216  0.596658
1217  0.581549
1218  0.465772

[1219 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
736  0.708803
737  0.682826
738  0.652216
739  0.623790
740  0.518993

[741 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
266  1.420711
267  1.367558
268  1.383913
269  1.489916
270  1.421099

[271 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
221  1.336872
222  1.345645
223  1.348332
224  1.364865
225  1.183595

[226 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
764  0.117760
765  0.095645
766  0.090869
767  0.113770
768  0.013047

[769 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
728  2.394622
729  2.393119
730  2.441844
731  2.467361
732  2.317959

[733 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
874  0.537646
875  0.576126
876  0.583593
877  0.641597
878  0.503499

[879 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1360  1.905055
1361  1.873753
1362  1.912518
1363  2.040848
1364  2.029127

[1365 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1242  1.398689
1243  1.366439
1244  1.372550
1245  1.380245
1246  1.375380

[1247 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
861  0.953967
862  0.987690
863  1.020669
864  0.855463
865  0.822422

[866 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
803  1.068753
804  1.078317
805  1.085304
806  1.046158
807  0.940129

[808 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
199  0.467358
200  0.595637
201  0.670140
202  0.549539
203  0.473694

[204 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1853  1.433337
1854  1.400311
1855  1.403603
1856  1.404325
1857  1.385104

[1858 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
118  0.849627
119  0.855270
120  0.771394
121  0.731421
122  0.521811

[123 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1093  0.627684
1094  0.550038
1095  0.456275
1096  0.414901
1097  0.318153

[1098 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1201  0.961525
1202  0.960132
1203  0.984886
1204  1.228691
1205  1.133158

[1206 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1275  0.719474
1276  0.747613
1277  0.757638
1278  0.735342
1279  0.662504

[1280 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1101  1.093572
1102  1.095251
1103  1.144752
1104  1.089034
1105  1.048246

[1106 rows x 1 columns]
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
    0
0 NaN
1 NaN
2 NaN
3 NaN
4 NaN
5 NaN
6 NaN
7 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
224  1.783259
225  1.762542
226  1.801761
227  1.701910
228  1.587484

[229 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
224  1.834057
225  1.876925
226  1.874392
227  1.807362
228  1.803670

[229 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
224  1.239364
225  1.260944
226  1.323725
227  1.252117
228  1.133739

[229 rows x 1 columns]
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
223  1.437274
224  1.407017
225  1.472102
226  1.443359
227  1.377653

[228 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
224  1.025697
225  1.044420
226  1.091765
227  1.081417
228  1.162719

[229 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
224  1.330335
225  1.326666
226  1.386249
227  1.324804
228  1.208974

[229 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
224  2.081265
225  2.101273
226  2.176203
227  2.153031
228  1.933898

[229 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
224  0.999751
225  0.995140
226  0.994305
227  0.952878
228  0.890828

[229 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
224  1.255040
225  1.235163
226  1.263549
227  1.188333
228  1.164176

[229 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
224  1.323900
225  1.332093
226  1.344150
227  1.227118
228  1.201043

[229 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
224  2.359964
225  2.310298
226  2.401817
227  2.308242
228  2.249357

[229 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
224  1.543332
225  1.507640
226  1.530656
227  1.640690
228  1.515438

[229 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
224  1.654349
225  1.645833
226  1.608899
227  1.568706
228  1.523202

[229 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
224  1.842396
225  1.895707
226  1.847233
227  1.779262
228  1.603309

[229 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
224  2.192002
225  2.155901
226  2.227067
227  2.246830
228  1.961078

[229 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
224  2.024548
225  1.991456
226  2.014508
227  2.081896
228  1.840987

[229 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
153  2.381567
154  2.324321
155  2.327302
156  2.096076
157  1.885232

[158 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
224  1.138693
225  1.112845
226  1.127269
227  1.027938
228  0.981721

[229 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
154  2.335800
155  2.371895
156  2.457907
157  2.429782
158  2.282676

[159 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
157  2.166398
158  2.145400
159  2.037878
160  1.926514
161  1.688080

[162 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
99   0.503180
100  0.413513
101  0.343704
102  0.460551
103  0.374332

[104 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
224  1.563196
225  1.532378
226  1.550100
227  1.419462
228  1.376845

[229 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
224  1.683244
225  1.740003
226  1.773985
227  1.771551
228  1.544223

[229 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
175  1.844738
176  1.866795
177  1.849908
178  1.690965
179  1.524127

[180 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
224  1.200767
225  1.155700
226  1.169711
227  1.117667
228  1.056258

[229 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
175  2.382276
176  2.358544
177  2.321952
178  2.127937
179  1.791074

[180 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
125  1.857812
126  1.994060
127  1.990180
128  2.066111
129  1.899988

[130 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
128  1.681320
129  1.681062
130  1.713959
131  1.711373
132  1.561674

[133 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
63  1.678683
64  1.507149
65  1.492650
66  1.504538
67  1.302361

[68 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
156  2.445813
157  2.529183
158  2.583876
159  2.323040
160  2.247031

[161 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
224  1.327203
225  1.266712
226  1.271042
227  1.183902
228  1.012007

[229 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
175  0.061451
176  0.105161
177  0.027178
178 -0.142940
179 -0.261027

[180 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
115  1.295903
116  1.262997
117  1.232087
118  1.112337
119  0.999870

[120 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
90  1.536324
91  1.522862
92  1.579879
93  1.402030
94  1.405161

[95 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
111  1.351087
112  1.320842
113  1.334846
114  1.199291
115  1.141712

[116 rows x 1 columns]
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
36 NaN
37 NaN
38 NaN
39 NaN
40 NaN
41 NaN
42 NaN
43 NaN
44 NaN
45 NaN
46 NaN
47 NaN
48 NaN
49 NaN
50 NaN
51 NaN
52 NaN
53 NaN
54 NaN
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
80  2.252664
81  2.228876
82  2.277793
83  2.190045
84  1.971429

[85 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
224  2.593059
225  2.603141
226  2.600533
227  2.436389
228  2.464301

[229 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
122  1.822345
123  1.810064
124  1.719367
125  1.612899
126  1.382026

[127 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
87  1.305367
88  1.276955
89  1.354066
90  1.211576
91  1.117929

[92 rows x 1 columns]
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
36 NaN
37 NaN
38 NaN
39 NaN
40 NaN
41 NaN
42 NaN
43 NaN
44 NaN
45 NaN
46 NaN
47 NaN
48 NaN
49 NaN
50 NaN
51 NaN
52 NaN
53 NaN
54 NaN
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
160  1.190566
161  1.188948
162  1.140647
163  1.140542
164  1.010441

[165 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
211  1.627377
212  1.620739
213  1.667315
214  1.598153
215  1.521656

[216 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
100  1.283603
101  1.230344
102  1.302176
103  1.184965
104  1.060973

[105 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
146  1.325271
147  1.308677
148  1.344711
149  1.293822
150  1.241086

[151 rows x 1 columns]
    0
0 NaN
1 NaN
2 NaN
3 NaN
4 NaN
5 NaN
6 NaN
7 NaN
8 NaN
9 NaN
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
158  1.434612
159  1.485332
160  1.471180
161  1.544048
162  1.832137

[163 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
145  1.606738
146  1.736536
147  1.778720
148  1.727755
149  1.454753

[150 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
178  2.325032
179  2.280454
180  2.260090
181  2.082918
182  1.980986

[183 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
133  1.914414
134  1.935355
135  1.975312
136  1.912510
137  1.745401

[138 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
224  1.288029
225  1.246739
226  1.263694
227  1.141936
228  1.082335

[229 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
120  2.821452
121  2.802928
122  2.727874
123  2.548608
124  2.317229

[125 rows x 1 columns]
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
36 NaN
37 NaN
38 NaN
39 NaN
40 NaN
41 NaN
42 NaN
43 NaN
44 NaN
45 NaN
46 NaN
47 NaN
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
154  1.334668
155  1.303157
156  1.340269
157  1.346581
158  1.229827

[159 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
143  2.065035
144  2.010801
145  2.076093
146  2.043948
147  1.846710

[148 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
161  1.125322
162  1.158115
163  1.070105
164  0.980213
165  0.692751

[166 rows x 1 columns]
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
101  2.455277
102  2.436805
103  2.484740
104  2.375254
105  2.219433

[106 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
98   1.315051
99   1.234288
100  1.239833
101  1.147809
102  0.927800

[103 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
151  1.129835
152  1.160595
153  1.137886
154  1.067707
155  0.792769

[156 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
190  1.537520
191  1.524020
192  1.547106
193  1.471592
194  1.366572

[195 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
83  0.965244
84  0.925564
85  0.959119
86  1.108953
87  1.301938

[88 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
83  0.968680
84  0.920501
85  0.852413
86  0.659005
87  0.539121

[88 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
105  1.237866
106  1.217395
107  1.267170
108  1.245403
109  1.199376

[110 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
111  1.543037
112  1.486333
113  1.505006
114  1.436891
115  1.225660

[116 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
91  0.949831
92  0.893696
93  0.918830
94  0.890032
95  0.755496

[96 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
211  1.151048
212  1.154378
213  1.181023
214  1.219351
215  1.359784

[216 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
59 -0.350107
60  1.193467
61  1.240820
62  1.003884
63  0.934578

[64 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
142  1.139827
143  1.087737
144  1.010161
145  1.364587
146  1.413876

[147 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
130  0.937729
131  0.917983
132  0.764902
133  0.882514
134  0.678572

[135 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
154  1.057104
155  1.054362
156  1.092873
157  1.146879
158  1.021958

[159 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
86  2.470880
87  2.426609
88  2.429572
89  2.257828
90  2.277214

[91 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
154  0.987074
155  1.024093
156  0.986222
157  0.965589
158  0.746859

[159 rows x 1 columns]

           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
89  0.890434
90  0.827741
91  0.869310
92  0.794541
93  0.536309

[94 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
128  1.268189
129  1.232419
130  1.270098
131  1.207525
132  1.132719

[133 rows x 1 columns]
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
36 NaN
37 NaN
38 NaN
39 NaN
40 NaN
41 NaN
42 NaN
43 NaN
44 NaN
45 NaN
46 NaN
47 NaN
48 NaN
49 NaN
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
58       NaN
59  2.047060
60  1.846073
61  1.540454
62  1.378516

[63 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
83  0.819265
84  0.768097
85  0.841070
86  0.727562
87  0.562099

[88 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
130  3.056300
131  3.032796
132  3.049625
133  3.042885
134  3.057814

[135 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
98   0.933291
99   0.921102
100  0.845617
101  0.673490
102  0.593561

[103 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
117  2.854815
118  2.852975
119  2.844091
120  2.671373
121  2.412596

[122 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
102  0.715852
103  0.765867
104  0.725142
105  0.628531
106  0.899394

[107 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
153  1.525344
154  1.489357
155  1.390882
156  1.273573
157  1.181919

[158 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
95  1.291176
96  1.317719
97  1.241972
98  1.287091
99  1.202293

[100 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
153  1.967939
154  1.905905
155  1.926083
156  1.957243
157  1.810519

[158 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
146  2.474311
147  2.441399
148  2.343744
149  2.223582
150  2.152099

[151 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
134  1.038633
135  1.041223
136  1.028057
137  1.028971
138  0.943088

[139 rows x 1 columns]
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
36 NaN
37 NaN
38 NaN
39 NaN
40 NaN
41 NaN
42 NaN
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
209  1.295474
210  1.246820
211  1.213254
212  1.122206
213  0.900519

[214 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
224  1.520655
225  1.488239
226  1.472249
227  1.379453
228  1.249066

[229 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
133  1.352118
134  1.369725
135  1.397313
136  1.311629
137  1.283128

[138 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
134  1.393772
135  1.430588
136  1.352864
137  1.647115
138  1.316339

[139 rows x 1 columns]
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
153  1.454874
154  1.416197
155  1.323149
156  1.268418
157  1.103465

[158 rows x 1 columns]
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
36 NaN
37 NaN
38 NaN
39 NaN
40 NaN
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
158  1.287117
159  1.298629
160  1.321191
161  1.287458
162  1.124230

[163 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
170  1.699771
171  1.660182
172  1.680301
173  1.661827
174  1.537353

[175 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
157  1.098699
158  1.087384
159  1.142151
160  1.110347
161  0.976390

[162 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
224  1.772598
225  1.717206
226  1.741489
227  1.688437
228  1.541424

[229 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
154  0.412406
155  0.490964
156  0.429109
157  0.263792
158  0.072531

[159 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
79  2.192523
80  2.191945
81  2.177748
82  2.126688
83  2.158380

[84 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
91  1.102129
92  1.010521
93  1.079040
94  0.978115
95  0.896275

[96 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
132 -0.575293
133 -0.536329
134 -0.704305
135 -0.748117
136 -0.871361

[137 rows x 1 columns]
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
36 NaN
    0
0 NaN
1 NaN
2 NaN
3 NaN
4 NaN
5 NaN
6 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
    0
0 NaN
1 NaN
2 NaN
3 NaN
4 NaN
5 NaN
    0
0 NaN
1 NaN
2 NaN
3 NaN
4 NaN
5 NaN
    0
0 NaN
    0
0 NaN
1 NaN
2 NaN
3 NaN
4 NaN
    0
0 NaN
1 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2474  0.821311
2475  0.867804
2476  0.851402
2477  0.812840
2478  0.850974

[2479 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2389  0.775603
2390  0.783175
2391  0.800455
2392  0.773080
2393  0.990625

[2394 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2296  1.037677
2297  1.024640
2298  0.933301
2299  0.875759
2300  0.864350

[2301 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2203  0.546571
2204  0.534180
2205  0.571128
2206  0.569537
2207  0.590100

[2208 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2419  0.444415
2420  0.409268
2421  0.339459
2422  0.346892
2423  0.654403

[2424 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1937  0.333817
1938  0.284943
1939  0.342719
1940  0.230537
1941  0.224809

[1942 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2223  0.723208
2224  0.681445
2225  0.665720
2226  0.637981
2227  0.627708

[2228 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2434  1.621139
2435  1.543002
2436  1.483869
2437  1.529055
2438  1.424008

[2439 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1787  0.816262
1788  0.766811
1789  0.722151
1790  0.674960
1791  0.615392

[1792 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2517  0.702435
2518  0.598938
2519  0.564898
2520  0.584999
2521  0.841472

[2522 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2499  1.339925
2500  1.321047
2501  1.239471
2502  1.139448
2503  1.024582

[2504 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2538  0.301816
2539  0.256675
2540  0.162333
2541  0.100814
2542  0.337883

[2543 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2450  1.988256
2451  1.974603
2452  1.997142
2453  1.965712
2454  1.932676

[2455 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2167  0.683642
2168  0.544530
2169  0.554255
2170  0.559366
2171  0.511217

[2172 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2293 -0.032959
2294 -0.016090
2295  0.063451
2296  0.015035
2297  0.041543

[2298 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2308 -0.191377
2309 -0.028681
2310 -0.048540
2311  0.128011
2312  0.116679

[2313 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2246  0.546372
2247  0.537074
2248  0.343569
2249  0.521180
2250  0.562303

[2251 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2513  1.549738
2514  1.488826
2515  1.522517
2516  1.342228
2517  1.264644

[2518 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1889  0.977487
1890  0.978408
1891  0.990471
1892  0.998843
1893  0.997337

[1894 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2251 -0.007563
2252 -0.035984
2253 -0.048816
2254  0.015447
2255  0.021416

[2256 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2510  0.654696
2511  0.634682
2512  0.610864
2513  0.603757
2514  0.546326

[2515 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2530  0.677038
2531  0.681481
2532  0.704016
2533  0.650986
2534  0.626935

[2535 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2494  0.436671
2495  0.419515
2496  0.453500
2497  0.457011
2498  0.449483

[2499 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2417  0.440108
2418  0.461867
2419  0.570383
2420  0.517111
2421  0.469250

[2422 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1619  1.095018
1620  1.060330
1621  1.049516
1622  0.811196
1623  0.796712

[1624 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2210  1.620732
2211  1.542067
2212  1.574076
2213  1.601300
2214  1.350258

[2215 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2350  0.817128
2351  0.833468
2352  0.840168
2353  0.877866
2354  0.962328

[2355 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2261  0.899657
2262  0.900497
2263  0.761825
2264  0.692259
2265  0.602494

[2266 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1928  2.248452
1929  2.311304
1930  2.260280
1931  2.075356
1932  1.897114

[1933 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1744  0.694955
1745  0.663689
1746  0.638269
1747  0.578635
1748  0.529363

[1749 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2491  0.660114
2492  0.639017
2493  0.699746
2494  0.720809
2495  0.735386

[2496 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2254  0.759631
2255  0.835334
2256  0.814865
2257  0.716249
2258  0.653907

[2259 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1317  0.430302
1318  0.339358
1319  0.314857
1320  0.292728
1321  0.181799

[1322 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2512  0.513018
2513  0.532273
2514  0.570307
2515  0.598258
2516  0.568990

[2517 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2354  1.332705
2355  1.303921
2356  1.278444
2357  1.243279
2358  1.160847

[2359 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2334  0.287379
2335  0.299443
2336  0.319390
2337  0.247517
2338  0.333253

[2339 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2318  1.357723
2319  1.402094
2320  1.391052
2321  1.388132
2322  1.275188

[2323 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2361  0.571454
2362  0.555304
2363  0.533823
2364  0.676477
2365  0.654393

[2366 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2454  1.186662
2455  1.177945
2456  1.176585
2457  1.158271
2458  1.134862

[2459 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2354  0.320942
2355  0.332740
2356  0.341314
2357  0.383280
2358  0.330264

[2359 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2505  1.422710
2506  1.368629
2507  1.348068
2508  1.268808
2509  1.209298

[2510 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2334  1.423818
2335  1.423019
2336  1.428835
2337  1.397549
2338  1.267100

[2339 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2514  0.803483
2515  0.760971
2516  0.765094
2517  0.729845
2518  0.778195

[2519 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2365  0.813994
2366  0.830670
2367  0.790282
2368  0.817546
2369  0.837488

[2370 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2094  0.492815
2095  0.458852
2096  0.384834
2097  0.453104
2098  0.314451

[2099 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2420  0.677891
2421  0.702116
2422  0.692267
2423  0.672272
2424  0.674728

[2425 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2523  0.769758
2524  0.764702
2525  0.768598
2526  0.723108
2527  0.748227

[2528 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2429  0.491434
2430  0.531016
2431  0.529505
2432  0.581838
2433  0.490593

[2434 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2423  1.171349
2424  1.157045
2425  1.109384
2426  1.052008
2427  0.913564

[2428 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2458  1.897802
2459  1.855095
2460  1.844178
2461  1.872552
2462  1.721948

[2463 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2414  0.749418
2415  0.715234
2416  0.709261
2417  0.649331
2418  0.651567

[2419 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2304  1.734407
2305  1.765728
2306  1.789185
2307  1.753148
2308  1.778562

[2309 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2052  0.727010
2053  0.714092
2054  0.667908
2055  0.650446
2056  0.538934

[2057 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2494  0.742997
2495  0.746912
2496  0.756594
2497  0.748409
2498  0.961572

[2499 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2381  1.069974
2382  1.024317
2383  0.982928
2384  0.897981
2385  0.847281

[2386 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2515  0.149321
2516  0.208924
2517  0.169483
2518  0.126285
2519  0.104243

[2520 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2468  0.282347
2469  0.247563
2470  0.251481
2471  0.258855
2472  0.242062

[2473 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2535  0.726294
2536  0.714204
2537  0.721166
2538  0.727630
2539  0.717314

[2540 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2479  1.089177
2480  1.036026
2481  0.961673
2482  0.931238
2483  1.108273

[2484 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2538  0.671346
2539  0.649659
2540  0.647711
2541  0.672352
2542  0.613874

[2543 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2414  1.012635
2415  0.982789
2416  0.970958
2417  0.939202
2418  0.896260

[2419 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2329  2.072650
2330  2.011110
2331  1.988409
2332  1.858911
2333  1.653724

[2334 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2270  0.023798
2271  0.041901
2272  0.098389
2273  0.100734
2274  0.095526

[2275 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2532  0.643476
2533  0.648294
2534  0.633217
2535  0.629784
2536  0.597175

[2537 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2205  0.358427
2206  0.354915
2207  0.327737
2208  0.396857
2209  0.348613

[2210 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2013  0.960488
2014  0.903470
2015  0.872142
2016  0.883774
2017  0.909656

[2018 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1695  0.703337
1696  0.706748
1697  0.772526
1698  0.709229
1699  0.665049

[1700 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2531  1.079380
2532  1.108508
2533  1.096534
2534  1.178222
2535  1.365617

[2536 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2452  1.725688
2453  1.734151
2454  1.703215
2455  1.630562
2456  1.597029

[2457 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2392  0.975082
2393  0.983315
2394  0.999404
2395  0.961018
2396  0.911741

[2397 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1287  0.992387
1288  0.971716
1289  0.969937
1290  1.054831
1291  1.021794

[1292 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2370  0.669947
2371  0.668479
2372  0.662682
2373  0.668590
2374  0.578159

[2375 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1583  1.062367
1584  1.056799
1585  1.037020
1586  0.944596
1587  1.026417

[1588 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2536  1.222411
2537  1.237906
2538  1.229076
2539  1.147470
2540  1.132492

[2541 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2472  1.211111
2473  1.160226
2474  1.135186
2475  1.220773
2476  1.150060

[2477 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2388  1.248496
2389  1.196802
2390  1.218311
2391  1.245790
2392  1.359553

[2393 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2537  0.610264
2538  0.593903
2539  0.611731
2540  0.634773
2541  0.697285

[2542 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1489  0.640440
1490  0.680565
1491  0.694867
1492  0.577285
1493  0.460389

[1494 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2515  0.943464
2516  0.956751
2517  0.942893
2518  0.901343
2519  0.816548

[2520 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2344  0.909267
2345  0.880007
2346  0.862380
2347  0.817121
2348  0.757055

[2349 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2332  0.280423
2333  0.136112
2334  0.022674
2335  0.132881
2336 -0.015722

[2337 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2265  0.779831
2266  0.877497
2267  0.884692
2268  0.785602
2269  0.761981

[2270 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2477  0.634460
2478  0.608965
2479  0.583387
2480  0.540047
2481  0.527035

[2482 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2376  0.672745
2377  0.696017
2378  0.571438
2379  0.656094
2380  0.583435

[2381 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2383  1.203917
2384  1.175053
2385  1.195141
2386  1.121921
2387  1.017896

[2388 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1980  0.808833
1981  0.783843
1982  0.789700
1983  0.779953
1984  0.716973

[1985 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2392  1.531110
2393  1.498687
2394  1.503461
2395  1.553991
2396  1.399180

[2397 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2529  0.333737
2530  0.256929
2531  0.218581
2532  0.254403
2533  0.176114

[2534 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2201  1.078980
2202  1.078861
2203  1.078539
2204  1.109190
2205  1.131239

[2206 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2532  0.527931
2533  0.487863
2534  0.509033
2535  0.505546
2536  0.495020

[2537 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2497  1.013390
2498  0.972823
2499  0.963545
2500  0.960781
2501  0.874503

[2502 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2490  0.310644
2491  0.287342
2492  0.297373
2493  0.267018
2494  0.265688

[2495 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2479  0.494289
2480  0.509635
2481  0.497155
2482  0.516875
2483  0.478191

[2484 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2535  0.849278
2536  0.830364
2537  0.889377
2538  0.745116
2539  0.597843

[2540 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2509  1.265775
2510  1.240083
2511  1.225737
2512  1.221927
2513  1.288521

[2514 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2219  1.649367
2220  1.676466
2221  1.564095
2222  1.312862
2223  1.569819

[2224 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2425  1.725673
2426  1.675413
2427  1.679540
2428  1.547119
2429  1.383268

[2430 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2396  0.449489
2397  0.450258
2398  0.444818
2399  0.449554
2400  0.434649

[2401 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2485  0.754709
2486  0.770108
2487  0.780739
2488  0.647651
2489  0.632365

[2490 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2511  0.285983
2512  0.269063
2513  0.253197
2514  0.252182
2515  0.217290

[2516 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1668  0.910876
1669  0.908635
1670  0.912628
1671  0.963601
1672  0.939810

[1673 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2462  0.577263
2463  0.572517
2464  0.642897
2465  0.882688
2466  1.163345

[2467 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2243  1.045306
2244  1.009917
2245  0.988968
2246  0.891680
2247  0.996804

[2248 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2308  1.005225
2309  0.981269
2310  1.025324
2311  0.954958
2312  1.259531

[2313 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2042  0.327486
2043  0.377884
2044  0.280215
2045  0.203687
2046  0.295911

[2047 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2291  0.426012
2292  0.593453
2293  0.569112
2294  0.796165
2295  0.742610

[2296 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2175  0.863869
2176  0.815684
2177  0.748511
2178  0.634053
2179  0.644939

[2180 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2512  0.385573
2513  0.364038
2514  0.387520
2515  0.350203
2516  0.363692

[2517 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2099  0.363170
2100  0.248480
2101  0.274938
2102  0.222383
2103  0.039195

[2104 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2398  1.185091
2399  1.204018
2400  1.266139
2401  1.178504
2402  1.138432

[2403 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2440  0.824041
2441  0.918999
2442  0.834009
2443  0.761108
2444  0.619934

[2445 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2447  0.855918
2448  0.811747
2449  0.813969
2450  0.895358
2451  0.916005

[2452 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2342  0.519044
2343  0.538098
2344  0.520162
2345  0.446260
2346  0.438709

[2347 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2483  0.859141
2484  0.833770
2485  0.851688
2486  0.869712
2487  0.965358

[2488 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2419  0.291482
2420  0.337276
2421  0.327624
2422  0.238906
2423  0.196064

[2424 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2339  0.092053
2340  0.041390
2341  0.024885
2342  0.057458
2343  0.070377

[2344 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1975  0.547742
1976  0.598962
1977  0.615656
1978  0.540884
1979  0.486363

[1980 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2509  1.139901
2510  1.191084
2511  1.179021
2512  1.038905
2513  0.978633

[2514 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2402  0.791100
2403  0.792164
2404  0.763014
2405  0.789686
2406  0.782328

[2407 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2356  0.422471
2357  0.391713
2358  0.385390
2359  0.315386
2360  0.317896

[2361 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2515  0.798822
2516  0.881897
2517  0.806351
2518  0.828782
2519  0.732683

[2520 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2017  1.412953
2018  1.391960
2019  1.375969
2020  1.259122
2021  0.958490

[2022 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2528  0.863122
2529  0.838711
2530  0.853508
2531  0.840401
2532  0.857451

[2533 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2434  0.741245
2435  0.759899
2436  0.756714
2437  0.797960
2438  0.677923

[2439 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2523  0.736752
2524  0.752833
2525  0.754474
2526  0.709468
2527  0.726145

[2528 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2436  0.124385
2437  0.073609
2438  0.084522
2439  0.266772
2440  0.256900

[2441 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2486  0.487134
2487  0.459503
2488  0.433366
2489  0.390732
2490  0.288847

[2491 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2360  0.885403
2361  0.821276
2362  0.829804
2363  0.798876
2364  0.731670

[2365 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2144  0.643624
2145  0.640771
2146  0.601538
2147  0.674140
2148  0.664800

[2149 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2373  0.484454
2374  0.403909
2375  0.334141
2376  0.320685
2377  0.225945

[2378 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2397  0.616310
2398  0.580987
2399  0.608507
2400  0.589200
2401  0.673054

[2402 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2377  0.657323
2378  0.726481
2379  0.705180
2380  0.615807
2381  0.528803

[2382 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2423  0.209576
2424  0.207074
2425  0.216929
2426  0.232273
2427  0.251426

[2428 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2124  1.291898
2125  1.287641
2126  1.346544
2127  1.328846
2128  1.288678

[2129 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2509 -0.607227
2510 -0.645506
2511 -0.636349
2512 -0.676078
2513 -0.444665

[2514 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2502  0.543487
2503  0.532721
2504  0.527426
2505  0.512341
2506  0.486750

[2507 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2438  0.486383
2439  0.472648
2440  0.499675
2441  0.626910
2442  0.615845

[2443 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1948  0.927654
1949  0.898310
1950  0.873109
1951  0.800336
1952  0.778459

[1953 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2405  0.557716
2406  0.517297
2407  0.544553
2408  0.483124
2409  0.520529

[2410 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2092  1.164124
2093  1.217044
2094  1.226384
2095  1.223914
2096  1.164278

[2097 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2538  0.572439
2539  0.529810
2540  0.562013
2541  0.509551
2542  0.484543

[2543 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2538  0.678921
2539  0.658575
2540  0.698168
2541  0.660689
2542  0.735198

[2543 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2509  0.139916
2510  0.018537
2511  0.046190
2512 -0.012989
2513 -0.022804

[2514 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2457  0.526052
2458  0.524814
2459  0.536086
2460  0.555518
2461  0.566264

[2462 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2148  0.501879
2149  0.549679
2150  0.526118
2151  0.532663
2152  0.499856

[2153 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2539  1.968939
2540  1.974580
2541  1.997024
2542  1.924162
2543  1.852811

[2544 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2189  1.768852
2190  1.737060
2191  1.791998
2192  1.770278
2193  1.616819

[2194 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1375  1.083463
1376  1.058646
1377  1.059440
1378  1.011085
1379  0.887363

[1380 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2286  0.928007
2287  0.937721
2288  0.946911
2289  0.954602
2290  1.036643

[2291 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2524  0.637446
2525  0.609283
2526  0.604827
2527  0.600081
2528  0.585374

[2529 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2155  1.011061
2156  1.002281
2157  1.023591
2158  1.032228
2159  1.057446

[2160 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2534  0.536206
2535  0.468304
2536  0.463121
2537  0.351897
2538  0.297971

[2539 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2433  1.372109
2434  1.367566
2435  1.406939
2436  1.475826
2437  1.388804

[2438 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2070  0.770635
2071  0.691025
2072  0.722126
2073  0.845149
2074  0.816936

[2075 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2396  0.582404
2397  0.541808
2398  0.544600
2399  0.531746
2400  0.496777

[2401 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2269  0.967497
2270  0.987351
2271  0.985667
2272  0.997953
2273  0.909857

[2274 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2489  1.163368
2490  1.189243
2491  1.229203
2492  1.181670
2493  1.207310

[2494 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2506  1.296136
2507  1.301789
2508  1.315010
2509  1.218373
2510  1.477274

[2511 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2541  0.526365
2542  0.494100
2543  0.507439
2544  0.483578
2545  0.394898

[2546 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2245  0.457083
2246  0.534839
2247  0.496461
2248  0.405304
2249  0.367138

[2250 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2531  0.429275
2532  0.398693
2533  0.443232
2534  0.472480
2535  0.464025

[2536 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2535  0.759802
2536  0.742250
2537  0.758127
2538  0.802979
2539  0.808745

[2540 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2409  1.168205
2410  1.323740
2411  1.350180
2412  1.454828
2413  1.329283

[2414 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2529  0.725589
2530  0.708285
2531  0.679430
2532  0.655651
2533  0.621888

[2534 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2242  0.905235
2243  0.951533
2244  0.957540
2245  0.883272
2246  0.793952

[2247 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2190  1.198328
2191  1.157164
2192  1.170303
2193  1.173710
2194  1.098782

[2195 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2311  0.340969
2312  0.280742
2313  0.282741
2314  0.262262
2315  0.260624

[2316 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2192  1.247897
2193  1.197142
2194  1.226810
2195  1.107291
2196  1.028339

[2197 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1983  1.140419
1984  1.202943
1985  1.136880
1986  1.200187
1987  1.246789

[1988 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2524  0.531969
2525  0.495154
2526  0.497311
2527  0.502707
2528  0.495953

[2529 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2401  0.387394
2402  0.426017
2403  0.439049
2404  0.525527
2405  0.557394

[2406 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2424  1.025148
2425  1.011605
2426  0.976486
2427  0.915998
2428  0.887757

[2429 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2366  0.922401
2367  0.929767
2368  0.928229
2369  1.010011
2370  1.097935

[2371 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2416  0.624676
2417  0.621387
2418  0.637088
2419  0.736483
2420  0.691682

[2421 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2335  0.643317
2336  0.448608
2337  0.403488
2338  0.529848
2339  0.532608

[2340 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2534  0.579013
2535  0.614467
2536  0.609328
2537  0.581980
2538  0.832257

[2539 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2503 -0.128304
2504  0.423268
2505  0.406297
2506  0.365171
2507  0.391900

[2508 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2524  0.382788
2525  0.342569
2526  0.367891
2527  0.384985
2528  0.400827

[2529 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2512  0.582119
2513  0.598641
2514  0.740000
2515  0.696064
2516  0.606551

[2517 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2423  1.091496
2424  1.065332
2425  1.070116
2426  1.052432
2427  1.020576

[2428 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2472  0.937758
2473  0.862804
2474  0.870299
2475  0.749151
2476  0.739193

[2477 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2301  2.100912
2302  2.096417
2303  2.088408
2304  1.874091
2305  1.826560

[2306 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2171  0.139133
2172  0.099492
2173  0.132389
2174  0.096528
2175  0.088484

[2176 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2307  1.465096
2308  1.428976
2309  1.430949
2310  1.376483
2311  1.302840

[2312 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2299  0.672698
2300  0.640905
2301  0.674675
2302  0.626317
2303  0.703532

[2304 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2307  0.674133
2308  0.651684
2309  0.660803
2310  0.698344
2311  0.758117

[2312 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2417  1.879478
2418  1.877675
2419  1.940362
2420  2.105866
2421  2.101442

[2422 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2416  1.112837
2417  1.045483
2418  1.073305
2419  0.881207
2420  0.830867

[2421 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2102  0.200518
2103  0.209471
2104  0.115453
2105  0.003818
2106 -0.016802

[2107 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2278  0.204542
2279  0.176877
2280  0.256781
2281  0.248017
2282  0.384537

[2283 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2399  0.867636
2400  0.957373
2401  1.027408
2402  1.124523
2403  1.104239

[2404 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2308  0.988372
2309  1.055524
2310  0.928399
2311  0.850645
2312  0.973075

[2313 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2287  1.224258
2288  1.207260
2289  1.229677
2290  1.196796
2291  1.201822

[2292 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2406  0.977938
2407  0.970881
2408  1.020761
2409  1.021745
2410  0.946907

[2411 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2490  0.778111
2491  0.764867
2492  0.763408
2493  0.729418
2494  0.884368

[2495 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2146  0.740515
2147  0.693505
2148  0.720125
2149  0.650892
2150  0.960835

[2151 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1624  0.808681
1625  0.778450
1626  0.773206
1627  0.740068
1628  0.688645

[1629 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2530  0.634199
2531  0.683601
2532  0.706071
2533  0.715918
2534  0.709677

[2535 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2442  0.802381
2443  0.711670
2444  0.724548
2445  0.726948
2446  0.699101

[2447 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2368  0.777205
2369  0.751296
2370  0.765873
2371  0.692784
2372  0.656047

[2373 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2413  0.659126
2414  0.629333
2415  0.643302
2416  0.699471
2417  0.663358

[2418 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2164  0.737413
2165  0.710501
2166  0.715519
2167  0.606147
2168  0.589949

[2169 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2046  0.955843
2047  0.951694
2048  0.969615
2049  0.935928
2050  0.914660

[2051 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2376  0.617984
2377  0.589710
2378  0.537721
2379  0.503174
2380  0.582726

[2381 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2537  0.185809
2538  0.274828
2539  0.257849
2540  0.195153
2541  0.200038

[2542 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2534  0.995259
2535  0.974716
2536  0.986723
2537  0.957310
2538  0.952302

[2539 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2079  1.457891
2080  1.441821
2081  1.476534
2082  1.516838
2083  1.413746

[2084 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2452  0.599728
2453  0.580540
2454  0.587936
2455  0.699054
2456  0.747800

[2457 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2366  2.099070
2367  2.028406
2368  2.038135
2369  1.880731
2370  1.701031

[2371 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2531  1.279676
2532  1.264709
2533  1.273478
2534  1.237662
2535  1.167510

[2536 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2174  1.401310
2175  1.356184
2176  1.325052
2177  1.267762
2178  1.171967

[2179 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2407  0.641370
2408  0.730012
2409  0.724476
2410  0.956134
2411  0.822165

[2412 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2461  0.459579
2462  0.515686
2463  0.507401
2464  0.452437
2465  0.468217

[2466 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2376  0.838350
2377  0.833326
2378  0.850167
2379  0.824517
2380  0.818002

[2381 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2370  0.550685
2371  0.494161
2372  0.455382
2373  0.642219
2374  0.601002

[2375 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2429  1.144920
2430  1.150876
2431  1.259333
2432  1.140094
2433  1.051535

[2434 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2461  0.800153
2462  0.835772
2463  0.819458
2464  0.865597
2465  1.170027

[2466 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1697  0.535842
1698  0.544320
1699  0.573723
1700  0.519571
1701  0.519787

[1702 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2398  0.817756
2399  0.801371
2400  0.789274
2401  0.748816
2402  0.651193

[2403 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2491  0.859954
2492  0.880502
2493  0.844389
2494  0.872656
2495  0.722495

[2496 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2190  0.870562
2191  0.894346
2192  0.867997
2193  0.962292
2194  0.675350

[2195 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2352  0.209726
2353  0.059950
2354  0.068870
2355  0.084991
2356 -0.008005

[2357 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2326  0.425183
2327  0.426862
2328  0.493563
2329  0.404928
2330  0.332990

[2331 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2259  0.770148
2260  0.725168
2261  0.763507
2262  0.715306
2263  0.683576

[2264 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2524  0.471609
2525  0.454868
2526  0.442599
2527  0.429657
2528  0.444858

[2529 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2212  0.473958
2213  0.420786
2214  0.400922
2215  0.377489
2216  0.363856

[2217 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2311  0.976506
2312  0.794297
2313  0.732898
2314  0.689012
2315  0.576966

[2316 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1412  0.507406
1413  0.359805
1414  0.344017
1415  0.383102
1416  0.336974

[1417 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2471  1.112015
2472  1.107582
2473  1.137633
2474  1.173204
2475  1.459541

[2476 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1637  1.278854
1638  1.254493
1639  1.284787
1640  1.259135
1641  1.408301

[1642 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2219  1.591821
2220  1.523749
2221  1.531721
2222  1.581730
2223  1.473082

[2224 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2231  1.306080
2232  1.247743
2233  1.254408
2234  1.123155
2235  0.989251

[2236 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1946  0.532448
1947  0.508223
1948  0.508944
1949  0.477408
1950  0.450827

[1951 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2381  0.466011
2382  0.451029
2383  0.431932
2384  0.391891
2385  0.356162

[2386 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2392  1.076434
2393  1.097475
2394  0.983219
2395  0.994749
2396  0.857806

[2397 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2534  1.288555
2535  1.268640
2536  1.261297
2537  1.227482
2538  1.221207

[2539 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1640  0.650273
1641  0.556613
1642  0.637471
1643  0.561603
1644  0.531076

[1645 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2330  1.317384
2331  1.227718
2332  1.249443
2333  1.146029
2334  1.093730

[2335 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2413  0.934556
2414  0.941846
2415  0.935265
2416  0.931222
2417  0.932910

[2418 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2513  0.571659
2514  0.567630
2515  0.587068
2516  0.566832
2517  0.565689

[2518 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2523  1.405149
2524  1.381233
2525  1.428490
2526  1.453426
2527  1.427562

[2528 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2329  1.563933
2330  1.494009
2331  1.536341
2332  1.472235
2333  1.489302

[2334 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1475  0.447103
1476  0.448597
1477  0.458905
1478  0.435385
1479  0.380316

[1480 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2489  0.468412
2490  0.456233
2491  0.438335
2492  0.419479
2493  0.398927

[2494 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2285  1.126718
2286  1.175321
2287  1.127567
2288  0.918823
2289  0.951967

[2290 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2454  0.623901
2455  0.625613
2456  0.605239
2457  0.572273
2458  0.537338

[2459 rows x 1 columns]
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2259  0.202605
2260  0.171727
2261  0.190381
2262  0.080005
2263  0.016668

[2264 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2218  0.896298
2219  0.871539
2220  0.747674
2221  0.664157
2222  0.510386

[2223 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2437  0.713999
2438  0.704302
2439  0.690937
2440  0.629594
2441  0.586728

[2442 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2416  2.056294
2417  2.095000
2418  2.143428
2419  2.162634
2420  2.316094

[2421 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2512  1.169114
2513  1.139763
2514  1.134697
2515  1.135098
2516  1.041678

[2517 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2540  1.200819
2541  1.254791
2542  1.195015
2543  1.213886
2544  1.089127

[2545 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2426  0.790671
2427  0.786033
2428  0.798438
2429  0.905734
2430  0.803356

[2431 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2510  0.299902
2511  0.303181
2512  0.306495
2513  0.279359
2514  0.280922

[2515 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2411  0.286673
2412  0.312591
2413  0.295021
2414  0.310776
2415  0.285647

[2416 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2427  0.470508
2428  0.473425
2429  0.498657
2430  0.409272
2431  0.380940

[2432 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2480  0.607474
2481  0.601209
2482  0.617096
2483  0.611221
2484  0.610387

[2485 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2238  0.882857
2239  0.919598
2240  0.947638
2241  0.737340
2242  0.539282

[2243 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2049  0.605683
2050  0.654264
2051  0.660861
2052  0.735985
2053  0.726580

[2054 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2286  0.999182
2287  0.978933
2288  1.012446
2289  1.083541
2290  1.047149

[2291 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2390  0.566141
2391  0.652828
2392  0.633873
2393  0.781811
2394  0.718727

[2395 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2316  0.478279
2317  0.498727
2318  0.453571
2319  0.739855
2320  0.890723

[2321 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2071  1.472906
2072  1.506637
2073  1.486997
2074  1.546967
2075  1.446796

[2076 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2445  0.761061
2446  0.731335
2447  0.739773
2448  0.763676
2449  0.786648

[2450 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2376  0.544224
2377  0.515985
2378  0.494904
2379  0.464245
2380  0.533059

[2381 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1860  0.594573
1861  0.582002
1862  0.590350
1863  0.533925
1864  0.513416

[1865 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2278  0.779570
2279  0.740544
2280  0.751342
2281  0.650293
2282  0.720511

[2283 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2442  1.454937
2443  1.375008
2444  1.428620
2445  1.288595
2446  1.241984

[2447 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2020  0.742233
2021  0.734895
2022  0.740146
2023  0.692338
2024  0.664601

[2025 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2235  1.026344
2236  1.001852
2237  1.024368
2238  0.966106
2239  0.920653

[2240 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2528  1.715999
2529  1.681482
2530  1.618023
2531  1.505031
2532  1.382935

[2533 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2505  0.634781
2506  0.645394
2507  0.656545
2508  0.621298
2509  0.634607

[2510 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2411  0.846526
2412  0.856942
2413  0.736512
2414  0.687568
2415  0.610083

[2416 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2513  1.326925
2514  1.314393
2515  1.385506
2516  1.413102
2517  1.394356

[2518 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2535  0.751540
2536  0.744189
2537  0.715023
2538  0.716657
2539  0.718273

[2540 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2538  1.154661
2539  1.172826
2540  1.143953
2541  1.200126
2542  1.082535

[2543 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2315  1.393782
2316  1.419174
2317  1.431676
2318  1.376187
2319  1.338871

[2320 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2508  1.969751
2509  1.967373
2510  1.957274
2511  1.853837
2512  1.672629

[2513 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2517  0.442466
2518  0.495308
2519  0.551654
2520  0.553410
2521  0.490288

[2522 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2445  1.221372
2446  1.222899
2447  1.217466
2448  1.233698
2449  1.517099

[2450 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2485  0.559038
2486  0.530518
2487  0.527254
2488  0.500655
2489  0.465350

[2490 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2505  0.929976
2506  0.900367
2507  0.895924
2508  0.835631
2509  0.836089

[2510 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2438  1.153471
2439  1.133155
2440  1.078309
2441  1.238123
2442  1.097728

[2443 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2102  1.194128
2103  1.169880
2104  1.222044
2105  1.254345
2106  1.240202

[2107 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2156  0.753431
2157  0.777823
2158  0.793350
2159  0.747824
2160  0.756379

[2161 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2442  0.082790
2443  0.072613
2444  0.041066
2445  0.010851
2446  0.042887

[2447 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2503  0.807450
2504  0.800203
2505  0.810999
2506  0.779986
2507  0.776746

[2508 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2169  0.475003
2170  0.436530
2171  0.420231
2172  0.390575
2173  0.374351

[2174 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2477  0.985857
2478  1.093867
2479  1.050091
2480  0.973196
2481  0.897102

[2482 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1506  0.457433
1507  0.468145
1508  0.333306
1509  0.410803
1510  0.250574

[1511 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2501  0.684583
2502  0.707874
2503  0.733167
2504  0.684225
2505  0.755812

[2506 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2386  0.410487
2387  0.498214
2388  0.478890
2389  0.566167
2390  0.575660

[2391 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2200  0.155905
2201  0.123675
2202  0.071051
2203  0.065842
2204  0.015914

[2205 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2490  0.697573
2491  0.700786
2492  0.695086
2493  0.709702
2494  0.726315

[2495 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2464  0.659227
2465  0.634439
2466  0.568716
2467  0.519199
2468  0.452977

[2469 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2108  0.529847
2109  0.543890
2110  0.541729
2111  0.503793
2112  0.443927

[2113 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2392  0.488129
2393  0.471114
2394  0.472514
2395  0.455042
2396  0.421904

[2397 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2513  1.060858
2514  1.019516
2515  1.022669
2516  1.023270
2517  1.077210

[2518 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2497  1.066090
2498  1.058703
2499  1.106622
2500  1.117637
2501  1.166891

[2502 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2511  0.785496
2512  0.771751
2513  0.794934
2514  0.744837
2515  0.982246

[2516 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2468  0.611429
2469  0.599816
2470  0.580360
2471  0.553985
2472  0.540779

[2473 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2349  0.417282
2350  0.386868
2351  0.334178
2352  0.443879
2353  0.453880

[2354 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2529  0.643203
2530  0.676389
2531  0.663542
2532  0.715493
2533  0.619326

[2534 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2425  0.419161
2426  0.441333
2427  0.474722
2428  0.445486
2429  0.360800

[2430 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2519  0.991914
2520  0.975585
2521  1.052390
2522  1.063056
2523  1.066148

[2524 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2360  0.741131
2361  0.778421
2362  0.773433
2363  0.768701
2364  0.725081

[2365 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2393  1.231487
2394  1.185524
2395  1.199039
2396  1.162241
2397  1.308615

[2398 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2389  0.521330
2390  0.503105
2391  0.490176
2392  0.465227
2393  0.373619

[2394 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2528  1.096027
2529  1.117577
2530  1.163519
2531  1.181488
2532  1.296208

[2533 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2447  0.537978
2448  0.634688
2449  0.627027
2450  0.635398
2451  0.650305

[2452 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2469  0.954677
2470  0.872716
2471  0.878771
2472  0.753126
2473  0.733177

[2474 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2433  0.587878
2434  0.606646
2435  0.614398
2436  0.590110
2437  0.679925

[2438 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2112  0.461895
2113  0.576817
2114  0.571788
2115  0.595834
2116  0.685289

[2117 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2386  0.667343
2387  0.696735
2388  0.717362
2389  0.732262
2390  0.699121

[2391 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2077  1.290007
2078  1.258317
2079  1.338672
2080  1.359677
2081  1.597822

[2082 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2509  0.650758
2510  0.679632
2511  0.797798
2512  0.732734
2513  0.689590

[2514 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2423  0.949521
2424  1.073269
2425  1.115517
2426  1.169526
2427  1.091891

[2428 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2434  1.236629
2435  1.224431
2436  1.038315
2437  1.091587
2438  1.314688

[2439 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2510  0.672087
2511  0.658266
2512  0.681228
2513  0.684327
2514  0.635966

[2515 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2495  0.991176
2496  0.970706
2497  0.958970
2498  0.906420
2499  0.815440

[2500 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2365  0.912638
2366  0.867256
2367  0.829558
2368  0.807951
2369  1.135981

[2370 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2241  0.178898
2242  0.358335
2243  0.411557
2244  0.440785
2245  0.386297

[2246 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2150  0.112801
2151  0.026336
2152  0.060285
2153  0.060239
2154 -0.101546

[2155 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2430  0.921172
2431  0.888628
2432  0.932629
2433  0.878201
2434  0.944750

[2435 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2528  0.621073
2529  0.585098
2530  0.611190
2531  0.575535
2532  0.603891

[2533 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2179  2.017619
2180  2.015485
2181  2.020698
2182  1.883443
2183  1.759209

[2184 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2445  0.709657
2446  0.706451
2447  0.696047
2448  0.578270
2449  0.707198

[2450 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2234  0.811859
2235  0.791847
2236  0.795854
2237  0.768542
2238  0.728603

[2239 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2222  0.368803
2223  0.329489
2224  0.385331
2225  0.322586
2226  0.209981

[2227 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2185  1.348886
2186  1.273011
2187  1.327416
2188  1.215689
2189  1.162022

[2190 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2430  0.427797
2431  0.402864
2432  0.395116
2433  0.330907
2434  0.363320

[2435 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2093  2.254592
2094  2.233163
2095  2.264120
2096  2.136590
2097  1.998489

[2098 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2537  0.846759
2538  0.829580
2539  0.899457
2540  0.959352
2541  0.848232

[2542 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1627  1.137731
1628  1.162147
1629  1.024545
1630  1.012819
1631  1.073329

[1632 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2341  0.794796
2342  0.770412
2343  0.789665
2344  0.885294
2345  0.829447

[2346 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2534  0.416572
2535  0.419186
2536  0.416660
2537  0.383582
2538  0.382742

[2539 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2537  2.118584
2538  2.100289
2539  2.041017
2540  1.956444
2541  1.763997

[2542 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2431  0.936325
2432  0.924007
2433  0.935141
2434  0.917864
2435  0.890011

[2436 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2463  1.239185
2464  1.227429
2465  1.224092
2466  1.163243
2467  1.145832

[2468 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2467  0.429075
2468  0.410196
2469  0.427263
2470  0.400322
2471  0.398280

[2472 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2284  1.267270
2285  1.212819
2286  1.234082
2287  1.192261
2288  1.012532

[2289 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2535  0.907444
2536  0.915206
2537  0.921848
2538  0.982661
2539  0.976245

[2540 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2063  0.129567
2064  0.145254
2065  0.174688
2066  0.160325
2067  0.160424

[2068 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2344  0.800192
2345  0.876701
2346  0.854978
2347  0.954157
2348  0.855324

[2349 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2237  0.884384
2238  1.015874
2239  1.061928
2240  0.931065
2241  0.592136

[2242 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2270  1.239584
2271  1.165196
2272  1.160256
2273  1.016808
2274  0.985991

[2275 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2465  0.546667
2466  0.568704
2467  0.540355
2468  0.494605
2469  0.310600

[2470 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2413  0.753540
2414  0.738990
2415  0.781990
2416  0.750772
2417  0.786266

[2418 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2410  1.500344
2411  1.493382
2412  1.506214
2413  1.467317
2414  1.417180

[2415 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2540  0.689275
2541  0.706200
2542  0.697689
2543  0.783857
2544  0.836253

[2545 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2384  1.006811
2385  0.982211
2386  0.977385
2387  0.934161
2388  0.884464

[2389 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2335  1.730961
2336  1.571476
2337  1.449475
2338  1.301994
2339  1.218345

[2340 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2457  1.056123
2458  1.136695
2459  1.139087
2460  1.042364
2461  0.996750

[2462 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2517  0.824158
2518  0.921087
2519  0.917129
2520  1.019634
2521  1.000629

[2522 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2480  1.650564
2481  1.657835
2482  1.652860
2483  1.618393
2484  1.712786

[2485 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2520  1.111080
2521  1.048499
2522  1.036873
2523  0.927794
2524  0.846037

[2525 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2499  0.792958
2500  0.840474
2501  0.857469
2502  0.989567
2503  1.029836

[2504 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2431 -0.055715
2432 -0.074634
2433  0.037626
2434  0.210851
2435  0.145465

[2436 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2227  1.148546
2228  1.134187
2229  1.085976
2230  0.972545
2231  0.874811

[2232 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1792  0.433409
1793  0.423621
1794  0.427516
1795  0.441271
1796  0.385705

[1797 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2438  0.222234
2439  0.164379
2440  0.115150
2441  0.075763
2442  0.260464

[2443 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2530  0.456805
2531  0.470675
2532  0.422092
2533  0.451231
2534  0.468533

[2535 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2420  0.965747
2421  0.973003
2422  0.948430
2423  0.772679
2424  0.761154

[2425 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2357  0.473994
2358  0.524342
2359  0.482925
2360  0.598719
2361  0.718197

[2362 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2503  0.914079
2504  0.847123
2505  0.864408
2506  0.916647
2507  1.115430

[2508 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2389  1.467910
2390  1.452512
2391  1.396858
2392  1.358053
2393  1.526245

[2394 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2537  0.414441
2538  0.390853
2539  0.316156
2540  0.307194
2541  0.242652

[2542 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2369  0.703998
2370  0.710426
2371  0.763268
2372  0.641066
2373  0.629553

[2374 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2425  0.869175
2426  0.818021
2427  0.822347
2428  0.817129
2429  0.781861

[2430 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2402  0.493377
2403  0.503820
2404  0.507574
2405  0.515845
2406  0.513418

[2407 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2455  0.708839
2456  0.706418
2457  0.674488
2458  0.607713
2459  0.567770

[2460 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2536  0.907090
2537  0.972524
2538  1.005095
2539  0.990986
2540  0.983114

[2541 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2319  0.752510
2320  0.935933
2321  0.919811
2322  0.922642
2323  0.883870

[2324 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2534  0.738944
2535  0.783555
2536  0.767163
2537  0.676282
2538  0.673433

[2539 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2106  1.827161
2107  1.950649
2108  2.008156
2109  1.872916
2110  1.845976

[2111 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2360  0.791915
2361  0.752791
2362  0.765006
2363  0.783684
2364  0.656363

[2365 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2234  0.905656
2235  0.930920
2236  0.980217
2237  0.971236
2238  0.922450

[2239 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2248  0.650756
2249  0.715116
2250  0.686314
2251  0.742500
2252  0.677864

[2253 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2326  0.731902
2327  0.714567
2328  0.595690
2329  0.610560
2330  0.664874

[2331 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2514  0.452443
2515  0.673477
2516  0.679692
2517  0.708018
2518  0.631651

[2519 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2534  0.760710
2535  0.743300
2536  0.770890
2537  0.798877
2538  0.812943

[2539 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2476  0.321701
2477  0.318473
2478  0.324787
2479  0.286755
2480  0.275671

[2481 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2354  0.608516
2355  0.591515
2356  0.559351
2357  0.534341
2358  0.526964

[2359 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2394  0.950328
2395  0.942624
2396  0.924274
2397  0.896074
2398  0.846397

[2399 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2402  1.118702
2403  1.147559
2404  1.109509
2405  1.198677
2406  1.053582

[2407 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2373  1.429068
2374  1.522593
2375  1.556559
2376  1.474267
2377  1.300528

[2378 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2497  1.188408
2498  1.160887
2499  1.186077
2500  1.202936
2501  1.173911

[2502 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2409  0.709740
2410  0.754521
2411  0.770733
2412  0.788651
2413  0.689962

[2414 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2394 -0.296405
2395 -0.236360
2396 -0.240570
2397 -0.274378
2398 -0.190838

[2399 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2513  1.451325
2514  1.368468
2515  1.220106
2516  1.231914
2517  0.963018

[2518 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2521  1.533958
2522  1.491420
2523  1.490232
2524  1.386013
2525  1.342902

[2526 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2483  0.658945
2484  0.475488
2485  0.500603
2486  0.518005
2487  0.536635

[2488 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2173  0.731103
2174  0.736604
2175  0.752177
2176  0.870075
2177  0.807334

[2178 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2497  0.855648
2498  0.821982
2499  0.785558
2500  0.743556
2501  0.590860

[2502 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2541  0.585419
2542  0.557915
2543  0.603230
2544  0.705901
2545  0.522851

[2546 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2236  0.473612
2237  0.481707
2238  0.535883
2239  0.485778
2240  0.435189

[2241 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2483  0.781640
2484  0.800022
2485  0.879881
2486  0.752519
2487  0.785057

[2488 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2541  0.188863
2542  0.213313
2543  0.232256
2544  0.199785
2545  0.158853

[2546 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2329  0.501479
2330  0.463111
2331  0.311384
2332  0.195972
2333  0.209837

[2334 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2517  1.355227
2518  1.339778
2519  1.340605
2520  1.363019
2521  1.256659

[2522 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2390  1.095869
2391  1.039006
2392  1.048390
2393  0.999406
2394  0.983335

[2395 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2391  0.740310
2392  0.719434
2393  0.767647
2394  0.836502
2395  0.810748

[2396 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2286  1.207033
2287  1.189822
2288  1.151427
2289  1.196348
2290  1.071556

[2291 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2498  0.634473
2499  0.619797
2500  0.633368
2501  0.628396
2502  0.689679

[2503 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2451  0.502440
2452  0.529538
2453  0.484748
2454  0.038400
2455 -0.316967

[2456 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2433  0.709992
2434  0.670296
2435  0.664168
2436  0.674897
2437  0.652491

[2438 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2405  0.421177
2406  0.390388
2407  0.432212
2408  0.431858
2409  0.483420

[2410 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2394  0.704330
2395  0.745501
2396  0.730217
2397  0.818856
2398  0.775518

[2399 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2462  1.161977
2463  1.211340
2464  1.398852
2465  1.063674
2466  0.938105

[2467 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2370  0.618400
2371  0.593032
2372  0.611785
2373  0.611541
2374  0.628803

[2375 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2516  0.653819
2517  0.634866
2518  0.663815
2519  0.688789
2520  0.715157

[2521 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2265  0.858405
2266  0.846312
2267  0.850505
2268  0.798288
2269  0.816501

[2270 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2489  1.177865
2490  1.135754
2491  1.260227
2492  1.150582
2493  0.894807

[2494 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2529  0.709528
2530  0.694162
2531  0.706565
2532  0.691675
2533  0.706221

[2534 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2333  1.615280
2334  1.627817
2335  1.632038
2336  1.629994
2337  1.575754

[2338 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1942  0.534652
1943  0.516810
1944  0.511033
1945  0.504236
1946  0.496622

[1947 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2431  1.020789
2432  1.013842
2433  1.098659
2434  1.084064
2435  0.923176

[2436 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2506  0.676678
2507  0.690477
2508  0.672912
2509  0.745620
2510  0.706790

[2511 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1940  0.411818
1941  0.405217
1942  0.411462
1943  0.373019
1944  0.352061

[1945 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2540  1.000675
2541  1.029326
2542  0.994815
2543  1.117345
2544  0.973141

[2545 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2419  0.353121
2420  0.350421
2421  0.383451
2422  0.391376
2423  0.395817

[2424 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2288  0.523106
2289  0.495019
2290  0.421495
2291  0.586337
2292  0.559296

[2293 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2410  0.571744
2411  0.503779
2412  0.477587
2413  0.591820
2414  0.573560

[2415 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2522  1.127415
2523  1.083947
2524  1.086986
2525  1.092782
2526  1.025222

[2527 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2430  0.802535
2431  0.792933
2432  0.822637
2433  0.761896
2434  0.690353

[2435 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2168  0.341272
2169  0.273723
2170  0.286330
2171  0.248432
2172  0.341678

[2173 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2433  1.174800
2434  1.167004
2435  1.186269
2436  1.168241
2437  1.195542

[2438 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2505  1.086578
2506  1.076738
2507  1.052433
2508  1.071119
2509  1.259752

[2510 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2360  0.886397
2361  0.904040
2362  0.915848
2363  0.819826
2364  0.791431

[2365 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2497  0.734809
2498  0.730488
2499  0.691571
2500  0.733586
2501  0.744772

[2502 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2532  0.582693
2533  0.553726
2534  0.573800
2535  0.537319
2536  0.608899

[2537 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2522  0.510974
2523  0.480479
2524  0.471155
2525  0.446894
2526  0.470482

[2527 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2315  0.323112
2316  0.314703
2317  0.318466
2318  0.332999
2319  0.231606

[2320 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2325  0.804141
2326  0.835336
2327  0.817627
2328  0.777680
2329  0.739743

[2330 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2447  1.209722
2448  1.211711
2449  1.188134
2450  1.289974
2451  1.171191

[2452 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2526  0.508252
2527  0.507143
2528  0.558841
2529  0.592989
2530  0.554799

[2531 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2263  0.661348
2264  0.654514
2265  0.668569
2266  0.539840
2267  0.449239

[2268 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2195  0.398769
2196  0.453868
2197  0.336987
2198  0.319506
2199  0.252879

[2200 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2409  1.101073
2410  1.062916
2411  1.088561
2412  1.053813
2413  0.984554

[2414 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2214  0.652085
2215  0.748177
2216  0.714981
2217  0.559333
2218  0.535267

[2219 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2286  1.299937
2287  1.281838
2288  1.131759
2289  1.241604
2290  1.182513

[2291 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2461  1.735658
2462  1.695068
2463  1.815715
2464  1.857778
2465  1.567175

[2466 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2468  0.834462
2469  0.794929
2470  0.803174
2471  0.689995
2472  0.699261

[2473 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1850  0.862421
1851  0.876290
1852  0.771703
1853  0.699546
1854  0.638375

[1855 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2379  1.407850
2380  1.018586
2381  1.063620
2382  0.941719
2383  0.734302

[2384 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1804 -0.013343
1805 -0.083815
1806 -0.095840
1807 -0.145466
1808 -0.213203

[1809 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1938  0.639992
1939  0.651428
1940  0.672223
1941  0.549407
1942  0.484447

[1943 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2536  0.671746
2537  0.657637
2538  0.647049
2539  0.643414
2540  0.637623

[2541 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2537  0.584478
2538  0.583873
2539  0.634188
2540  0.626118
2541  0.553925

[2542 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2359  0.463550
2360  0.427899
2361  0.515226
2362  0.802155
2363  0.807583

[2364 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2529  1.767061
2530  1.726759
2531  1.739693
2532  1.579749
2533  1.532307

[2534 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2434  0.514696
2435  0.533500
2436  0.566817
2437  0.691605
2438  0.665056

[2439 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2330  1.268346
2331  1.225384
2332  1.225307
2333  1.236928
2334  1.401657

[2335 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2522  0.546364
2523  0.583114
2524  0.609738
2525  0.608517
2526  0.596665

[2527 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1809  0.526730
1810  0.631579
1811  0.652873
1812  0.602134
1813  0.558605

[1814 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2170  1.562344
2171  1.540277
2172  1.574232
2173  1.573038
2174  1.513877

[2175 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2389  1.284579
2390  1.236393
2391  1.242964
2392  1.168445
2393  1.077693

[2394 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2376  0.765142
2377  0.818300
2378  0.806554
2379  0.954655
2380  0.848192

[2381 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2464  0.609924
2465  0.625010
2466  0.638661
2467  0.653826
2468  0.671049

[2469 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2387  0.729261
2388  0.682157
2389  0.516578
2390  0.588933
2391  0.517770

[2392 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
360  0.443850
361  0.474521
362  0.494680
363  0.421603
364  0.320922

[365 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2410  0.716169
2411  0.703345
2412  0.721981
2413  0.648489
2414  0.632755

[2415 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
125  1.132377
126  1.134373
127  1.128463
128  1.044345
129  0.952470

[130 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
605  0.677868
606  0.654891
607  0.650198
608  0.630601
609  0.666433

[610 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1085  0.912164
1086  0.904416
1087  0.844339
1088  0.755242
1089  0.899916

[1090 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2520  1.181247
2521  1.259501
2522  1.212016
2523  1.348245
2524  1.225233

[2525 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2235  0.840299
2236  0.803505
2237  0.799789
2238  0.904247
2239  0.853259

[2240 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2436  0.433598
2437  0.408125
2438  0.446347
2439  0.383496
2440  0.359552

[2441 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2379  0.471572
2380  0.449165
2381  0.417410
2382  0.455565
2383  0.386934

[2384 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2258  0.222488
2259  0.205835
2260  0.284205
2261  0.332523
2262  0.318313

[2263 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2186  0.796880
2187  0.829206
2188  0.783218
2189  0.717371
2190  0.631734

[2191 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2526  0.522737
2527  0.574175
2528  0.507028
2529  0.438429
2530  0.230338

[2531 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2519  1.709560
2520  1.704370
2521  1.660635
2522  1.633576
2523  1.585419

[2524 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2390  0.870139
2391  0.825953
2392  0.859272
2393  0.808330
2394  0.812946

[2395 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2394  0.767137
2395  0.803664
2396  0.819653
2397  0.810317
2398  0.789060

[2399 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2360  1.099101
2361  1.039439
2362  1.008059
2363  1.048905
2364  0.992884

[2365 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2193  1.084533
2194  1.112802
2195  1.131694
2196  1.055067
2197  1.000691

[2198 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2394  0.943702
2395  0.895236
2396  0.887883
2397  0.828208
2398  0.786457

[2399 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2433  0.696394
2434  0.654879
2435  0.672893
2436  0.626970
2437  0.581671

[2438 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1998  1.042386
1999  1.024773
2000  0.976647
2001  0.982156
2002  0.915782

[2003 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2474  0.761601
2475  0.730910
2476  0.745458
2477  0.701685
2478  0.795487

[2479 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2506  1.008297
2507  0.974487
2508  0.968267
2509  0.906615
2510  0.857466

[2511 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2037  0.182792
2038  0.303347
2039  0.338418
2040  0.299198
2041  0.261553

[2042 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2427  1.240454
2428  1.266762
2429  1.312572
2430  1.274184
2431  1.055435

[2432 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2433  0.647685
2434  0.663287
2435  0.630302
2436  0.628579
2437  0.583768

[2438 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2205  0.742340
2206  0.786076
2207  0.793874
2208  0.882383
2209  0.783749

[2210 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2507  0.372512
2508  0.469072
2509  0.430900
2510  0.269838
2511  0.118036

[2512 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2525  1.619183
2526  1.624639
2527  1.610932
2528  1.509467
2529  1.365732

[2530 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2523  0.632138
2524  0.635783
2525  0.663286
2526  0.648853
2527  0.629297

[2528 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2346  1.137783
2347  1.124626
2348  0.983103
2349  0.929491
2350  0.679185

[2351 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2418  0.721596
2419  0.699881
2420  0.722426
2421  0.709265
2422  0.660016

[2423 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2439  1.737794
2440  1.726032
2441  1.751714
2442  1.671219
2443  1.672835

[2444 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2538  2.094505
2539  2.026243
2540  1.904716
2541  1.864060
2542  1.720183

[2543 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2522  0.622523
2523  0.605081
2524  0.611776
2525  0.560345
2526  0.555655

[2527 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2480  0.227157
2481  0.295061
2482  0.290518
2483  0.149917
2484 -0.036714

[2485 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2478  1.111686
2479  1.079464
2480  1.066526
2481  1.023934
2482  0.944996

[2483 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2534  0.676560
2535  0.713448
2536  0.675684
2537  0.606496
2538  0.609981

[2539 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2438  0.846213
2439  0.832835
2440  0.832009
2441  0.717579
2442  0.722649

[2443 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2402  0.895363
2403  0.875485
2404  0.915346
2405  0.803408
2406  0.763445

[2407 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2478  0.864169
2479  0.864762
2480  0.869493
2481  0.926435
2482  0.953335

[2483 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2427  2.433705
2428  2.405793
2429  2.389622
2430  2.338633
2431  2.154634

[2432 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2352  0.387634
2353  0.377492
2354  0.425985
2355  0.382736
2356  0.417705

[2357 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2534  0.656449
2535  0.666277
2536  0.637674
2537  0.699854
2538  0.620176

[2539 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2539  0.541812
2540  0.558014
2541  0.494470
2542  0.413248
2543  0.360733

[2544 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2398  0.629938
2399  0.590241
2400  0.600094
2401  0.548130
2402  0.543553

[2403 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2538  0.708023
2539  0.775986
2540  0.713873
2541  0.899754
2542  0.870793

[2543 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2518  0.385456
2519  0.380587
2520  0.363067
2521  0.347870
2522  0.383253

[2523 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2419  0.923231
2420  0.949725
2421  0.969331
2422  0.838668
2423  0.948567

[2424 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2235  1.937318
2236  2.038478
2237  1.918937
2238  1.857910
2239  1.743015

[2240 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2485  2.236354
2486  2.154449
2487  2.180264
2488  1.957331
2489  1.786230

[2490 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2443  0.621514
2444  0.568771
2445  0.570023
2446  0.533997
2447  0.537101

[2448 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2295  0.302270
2296  0.396302
2297  0.342930
2298  0.354425
2299  0.431236

[2300 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2423  1.794400
2424  1.762495
2425  1.779698
2426  1.728806
2427  1.715337

[2428 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2260  1.854871
2261  2.093956
2262  2.047482
2263  2.000685
2264  2.175522

[2265 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2420  1.493215
2421  1.438466
2422  1.464964
2423  1.481655
2424  1.362911

[2425 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2342  0.938136
2343  0.909408
2344  0.903822
2345  0.856991
2346  0.838100

[2347 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2261  0.970003
2262  0.769952
2263  0.779435
2264  0.822923
2265  0.706596

[2266 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2274  0.654570
2275  0.669938
2276  0.653252
2277  0.546641
2278  0.581786

[2279 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2515  0.934828
2516  0.938028
2517  0.938954
2518  0.914071
2519  0.849140

[2520 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2441  1.319527
2442  1.330719
2443  1.304060
2444  1.232870
2445  1.170856

[2446 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2529  1.544882
2530  1.501662
2531  1.544078
2532  1.438607
2533  1.379813

[2534 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2297  0.228160
2298  0.215623
2299  0.298287
2300  0.257420
2301  0.287361

[2302 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2500  0.303788
2501  0.402120
2502  0.462345
2503  0.343788
2504  0.259568

[2505 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2195  1.534737
2196  1.465300
2197  1.455661
2198  1.321362
2199  1.277869

[2200 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2503  0.609020
2504  0.587127
2505  0.554039
2506  0.648979
2507  0.642550

[2508 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2293  0.596941
2294  0.579742
2295  0.592540
2296  0.579300
2297  0.560338

[2298 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2517  1.073728
2518  0.997078
2519  1.023122
2520  1.130758
2521  1.170428

[2522 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2447  1.715364
2448  1.928030
2449  1.940648
2450  1.748991
2451  1.556170

[2452 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2525  1.260344
2526  1.244276
2527  1.271873
2528  1.228441
2529  1.226573

[2530 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2229  2.152476
2230  2.210678
2231  2.222991
2232  2.086498
2233  1.901244

[2234 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2540  0.673113
2541  0.605614
2542  0.664626
2543  0.661968
2544  0.656126

[2545 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2525  0.749271
2526  0.725028
2527  0.713398
2528  0.667498
2529  0.648136

[2530 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2518  0.655232
2519  0.657365
2520  0.719674
2521  0.802328
2522  0.777014

[2523 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2369  0.176499
2370  0.233546
2371  0.415561
2372  0.516518
2373  0.834565

[2374 rows x 1 columns]
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2181  1.190111
2182  1.192103
2183  1.245058
2184  1.101611
2185  0.721202

[2186 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2036  0.738611
2037  0.750218
2038  0.777182
2039  0.758841
2040  0.681109

[2041 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2497  1.099134
2498  1.046745
2499  1.065680
2500  1.020131
2501  0.975467

[2502 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2316  1.556612
2317  1.570198
2318  1.721458
2319  1.779053
2320  1.805391

[2321 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1623  1.800920
1624  1.754860
1625  1.807713
1626  1.487377
1627  1.280885

[1628 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2217  0.995292
2218  1.095612
2219  1.029182
2220  0.883051
2221  0.764122

[2222 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2433  0.885865
2434  0.860095
2435  0.858530
2436  0.854673
2437  0.672495

[2438 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2504  1.371109
2505  1.343073
2506  1.264822
2507  1.204025
2508  1.257884

[2509 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2480  1.065200
2481  1.126691
2482  1.162911
2483  1.030164
2484  0.930917

[2485 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2420  1.635957
2421  1.641072
2422  1.639111
2423  1.597793
2424  1.338684

[2425 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2480  0.774490
2481  0.736624
2482  0.727900
2483  0.764748
2484  0.835920

[2485 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2159  0.272059
2160  0.388954
2161  0.358168
2162  0.358752
2163  0.277178

[2164 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2540  0.217222
2541  0.161160
2542  0.162618
2543  0.213555
2544  0.355720

[2545 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2483  1.309675
2484  1.291756
2485  1.259884
2486  1.246651
2487  1.457814

[2488 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2385  0.510178
2386  0.496852
2387  0.447391
2388  0.404716
2389  0.445937

[2390 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2423  0.235987
2424 -0.003486
2425 -0.035118
2426  0.022194
2427  0.018326

[2428 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2518  0.510792
2519  0.470016
2520  0.447626
2521  0.539086
2522  0.532470

[2523 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2471  0.604933
2472  0.600408
2473  0.592725
2474  0.543179
2475  0.562850

[2476 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2258  0.873029
2259  0.829884
2260  0.898880
2261  0.728605
2262  0.861835

[2263 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2399  0.926209
2400  0.997634
2401  0.878124
2402  1.134427
2403  1.138397

[2404 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2393  1.309673
2394  1.273262
2395  1.298411
2396  1.215663
2397  1.172628

[2398 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2374  0.792074
2375  0.787837
2376  0.787389
2377  0.742001
2378  0.699333

[2379 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2507  1.660345
2508  1.624139
2509  1.609030
2510  1.509370
2511  1.402151

[2512 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2327  0.466504
2328  0.513994
2329  0.465244
2330  0.438702
2331  0.399850

[2332 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2541  1.043293
2542  1.018199
2543  1.058728
2544  1.116164
2545  1.013734

[2546 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2469  0.438137
2470  0.422927
2471  0.437821
2472  0.422200
2473  0.382474

[2474 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2430  1.267050
2431  1.222474
2432  1.237960
2433  1.201815
2434  1.183815

[2435 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2206  1.012651
2207  0.979778
2208  0.925111
2209  0.881329
2210  0.764361

[2211 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2343  0.354104
2344  0.346228
2345  0.331654
2346  0.345162
2347  0.294060

[2348 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2449  0.681976
2450  0.859142
2451  0.819203
2452  0.889847
2453  1.015530

[2454 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2415  1.226859
2416  1.154710
2417  1.156994
2418  1.007884
2419  0.964215

[2420 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2177  0.668687
2178  0.643112
2179  0.648718
2180  0.571616
2181  0.596256

[2182 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2220  1.181715
2221  1.143090
2222  1.123332
2223  1.034318
2224  0.985648

[2225 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2479  1.857854
2480  1.893786
2481  1.900531
2482  1.875511
2483  1.718128

[2484 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2522  1.296137
2523  1.267131
2524  1.115199
2525  1.030579
2526  0.974028

[2527 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2386  1.055773
2387  1.004366
2388  0.960496
2389  1.023982
2390  0.942454

[2391 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2516  0.565225
2517  0.602295
2518  0.571541
2519  0.618826
2520  0.542244

[2521 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2494  1.387996
2495  1.375874
2496  1.363616
2497  1.309854
2498  1.242422

[2499 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2353  0.305887
2354  0.331133
2355  0.349070
2356  0.521171
2357  0.511613

[2358 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2252  0.716350
2253  0.708500
2254  0.733587
2255  0.762399
2256  0.754650

[2257 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2446  1.009046
2447  0.980337
2448  0.922402
2449  0.942140
2450  0.870581

[2451 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2199  1.149266
2200  1.099608
2201  1.049881
2202  0.936642
2203  0.798239

[2204 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2026  1.571364
2027  1.537146
2028  1.486392
2029  1.469627
2030  1.275649

[2031 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2357  0.727533
2358  0.728788
2359  0.702265
2360  0.636676
2361  0.512728

[2362 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2369  1.383341
2370  1.334438
2371  1.347617
2372  1.234115
2373  1.085444

[2374 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2470  0.779374
2471  0.767821
2472  0.775431
2473  0.764316
2474  0.759477

[2475 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2520  1.523526
2521  1.528970
2522  1.566812
2523  1.545057
2524  1.492707

[2525 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2476  0.852280
2477  0.876751
2478  0.889956
2479  0.838808
2480  0.770242

[2481 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2423  1.265229
2424  1.223246
2425  1.248148
2426  1.113542
2427  1.076426

[2428 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2422  0.978169
2423  0.925041
2424  0.904947
2425  0.883397
2426  0.863291

[2427 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2365  0.223637
2366  0.234426
2367  0.207904
2368  0.326235
2369  0.085079

[2370 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2348  0.970968
2349  1.005157
2350  0.980358
2351  1.026902
2352  0.969615

[2353 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2406  1.173412
2407  1.130260
2408  1.182982
2409  1.087504
2410  0.894597

[2411 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2483  0.689970
2484  0.756682
2485  0.621265
2486  0.745059
2487  0.676401

[2488 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2405  1.965980
2406  2.011562
2407  2.063667
2408  1.908468
2409  1.999395

[2410 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2456  1.091635
2457  1.065893
2458  1.117012
2459  1.179025
2460  1.357342

[2461 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2206  0.932304
2207  0.961627
2208  1.091678
2209  1.116662
2210  1.015131

[2211 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2398  0.627382
2399  0.630557
2400  0.647263
2401  0.629934
2402  0.659263

[2403 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2067  1.737809
2068  1.667017
2069  1.626497
2070  1.626679
2071  1.525760

[2072 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2453  1.181556
2454  1.153614
2455  1.159001
2456  1.102191
2457  1.141117

[2458 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2210  0.906387
2211  0.881641
2212  0.949292
2213  0.835142
2214  0.744708

[2215 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2434  0.559063
2435  0.523276
2436  0.551923
2437  0.601378
2438  0.609199

[2439 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2530  0.673708
2531  0.628122
2532  0.633729
2533  0.594170
2534  0.672800

[2535 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2398  0.156026
2399  0.123413
2400  0.199897
2401  0.164914
2402  0.033548

[2403 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2503  1.387573
2504  1.441571
2505  1.433890
2506  1.483163
2507  1.498958

[2508 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2524  0.973510
2525  0.951423
2526  0.940086
2527  0.877102
2528  0.801924

[2529 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2356  1.788772
2357  1.738907
2358  1.722979
2359  1.661644
2360  1.569272

[2361 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2530  1.660858
2531  1.628342
2532  1.658823
2533  1.665363
2534  1.591675

[2535 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2499  1.546658
2500  1.494479
2501  1.483717
2502  1.405942
2503  1.295549

[2504 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2523  0.683897
2524  0.654038
2525  0.654616
2526  0.586948
2527  0.562766

[2528 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2346  0.220327
2347  0.167930
2348  0.163040
2349  0.154354
2350  0.126026

[2351 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2534  1.268169
2535  1.297786
2536  1.261817
2537  1.156081
2538  1.201010

[2539 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1981  0.198652
1982  0.226680
1983  0.267425
1984  0.213077
1985  0.276701

[1986 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2527  0.620211
2528  0.591674
2529  0.597115
2530  0.588937
2531  0.573210

[2532 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2211  1.110892
2212  1.063029
2213  1.072032
2214  1.070695
2215  1.058261

[2216 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2502  0.912024
2503  0.908531
2504  0.912848
2505  0.913958
2506  1.074112

[2507 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2190  0.764177
2191  0.770231
2192  0.764839
2193  0.750906
2194  0.669467

[2195 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2463  1.628542
2464  1.587969
2465  1.643140
2466  1.624865
2467  1.491897

[2468 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2474  0.964062
2475  0.998196
2476  1.018124
2477  0.918785
2478  0.832043

[2479 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2469  1.302714
2470  1.273819
2471  1.224256
2472  0.908600
2473  0.768260

[2474 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2345  0.598526
2346  0.544582
2347  0.528251
2348  0.424492
2349  0.396425

[2350 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2478  1.917663
2479  1.910908
2480  1.902483
2481  1.907131
2482  1.712682

[2483 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2423  1.337943
2424  1.330949
2425  1.311601
2426  1.128560
2427  0.907294

[2428 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2524  0.672140
2525  0.670896
2526  0.713783
2527  0.794989
2528  0.741514

[2529 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2466  0.573823
2467  0.643019
2468  0.594346
2469  0.501508
2470  0.506161

[2471 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2439  1.611305
2440  1.591754
2441  1.544275
2442  1.492181
2443  1.328877

[2444 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2436  0.716620
2437  0.767535
2438  0.714419
2439  0.741408
2440  0.814126

[2441 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2527  1.775523
2528  1.764302
2529  1.686551
2530  1.846785
2531  1.702258

[2532 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2385  0.864784
2386  0.849188
2387  0.818007
2388  0.750295
2389  0.703810

[2390 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2261  1.588973
2262  1.603128
2263  1.656223
2264  1.575067
2265  1.572314

[2266 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2383  1.389237
2384  1.366497
2385  1.310394
2386  1.148714
2387  1.004057

[2388 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2394  0.709401
2395  0.723687
2396  0.730541
2397  0.725669
2398  0.686869

[2399 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2388  0.933142
2389  0.994117
2390  0.989991
2391  0.929107
2392  0.833499

[2393 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2358  0.909088
2359  0.899054
2360  0.907740
2361  0.949182
2362  0.964320

[2363 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2450  0.324413
2451  0.306929
2452  0.300473
2453  0.422438
2454  0.498599

[2455 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2426  0.445852
2427  0.492303
2428  0.487264
2429  0.480938
2430  0.424682

[2431 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2378  0.254054
2379  0.231399
2380  0.239383
2381  0.182608
2382  0.206696

[2383 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2135  1.126462
2136  1.093201
2137  1.211019
2138  1.125233
2139  0.924245

[2140 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2465  1.859850
2466  1.790899
2467  1.896704
2468  1.746769
2469  1.662665

[2470 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2420  0.650485
2421  0.725549
2422  0.722825
2423  0.839600
2424  0.756584

[2425 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2294  1.020415
2295  1.031514
2296  0.920376
2297  0.761958
2298  0.646246

[2299 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2444  0.663952
2445  0.655541
2446  0.689271
2447  0.660989
2448  0.606807

[2449 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2371  0.665282
2372  0.659961
2373  0.507401
2374  0.358512
2375  0.237985

[2376 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2294  1.558151
2295  1.518528
2296  1.562941
2297  1.451317
2298  1.266940

[2299 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2165  0.811161
2166  0.808870
2167  0.855746
2168  0.779740
2169  0.730291

[2170 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2398  0.946612
2399  0.866734
2400  0.801558
2401  0.910110
2402  1.002330

[2403 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2501  1.183181
2502  1.158943
2503  1.177901
2504  1.173074
2505  1.073697

[2506 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2434  1.629563
2435  1.570796
2436  1.519216
2437  1.463127
2438  1.277972

[2439 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2531  0.751085
2532  0.775656
2533  0.756739
2534  0.940794
2535  0.838093

[2536 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2211  1.735616
2212  1.711825
2213  1.817665
2214  1.728317
2215  1.524158

[2216 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2433  0.945251
2434  0.891319
2435  0.936404
2436  0.873934
2437  0.855736

[2438 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2523  1.518489
2524  1.513360
2525  1.568408
2526  1.503867
2527  1.620041

[2528 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2389  1.883498
2390  1.825451
2391  1.865300
2392  1.775173
2393  1.842617

[2394 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2493  1.662461
2494  1.510976
2495  1.565746
2496  1.480069
2497  1.539126

[2498 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2521  1.869195
2522  1.824711
2523  1.862779
2524  1.821374
2525  1.732351

[2526 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2528  0.299179
2529  0.255432
2530  0.242603
2531  0.142307
2532  0.105530

[2533 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2529  0.266263
2530  0.313223
2531  0.333435
2532  0.222925
2533  0.365778

[2534 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2354  0.591557
2355  0.656886
2356  0.653725
2357  0.608476
2358  0.560100

[2359 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2369  1.401399
2370  1.449185
2371  1.462334
2372  1.348679
2373  1.294155

[2374 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2285  0.540114
2286  0.501682
2287  0.502254
2288  0.485748
2289  0.328768

[2290 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2408  0.626162
2409  0.650262
2410  0.639307
2411  0.666241
2412  0.789993

[2413 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2419  0.876989
2420  0.760696
2421  0.786947
2422  0.892437
2423  1.213010

[2424 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2305  0.542870
2306  0.509152
2307  0.506446
2308  0.672896
2309  0.642615

[2310 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2492  1.755021
2493  1.725638
2494  1.760357
2495  1.644260
2496  1.495202

[2497 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2448  1.309813
2449  1.279643
2450  1.258481
2451  1.201339
2452  1.111458

[2453 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2387  0.939745
2388  0.925091
2389  0.939114
2390  0.891194
2391  0.852497

[2392 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2491  1.494186
2492  1.393839
2493  1.451912
2494  1.374245
2495  1.202328

[2496 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2392  0.798260
2393  0.781279
2394  0.875450
2395  0.808264
2396  1.102293

[2397 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2313  1.198337
2314  1.160530
2315  1.185771
2316  1.131895
2317  1.004753

[2318 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2388  0.017167
2389  0.022613
2390 -0.021703
2391  0.042936
2392  0.079414

[2393 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2320  1.522084
2321  1.524660
2322  1.525303
2323  1.485542
2324  1.638895

[2325 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2522  1.003669
2523  0.972296
2524  0.956273
2525  0.901010
2526  0.855494

[2527 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2303  0.518924
2304  0.498840
2305  0.525506
2306  0.504241
2307  0.471392

[2308 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2511 -0.085116
2512 -0.139381
2513 -0.133229
2514 -0.119282
2515 -0.017531

[2516 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2517  1.186578
2518  1.181959
2519  0.992781
2520  1.304500
2521  1.151459

[2522 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2503  0.662463
2504  0.647674
2505  0.630726
2506  0.575644
2507  0.563513

[2508 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2186  0.675946
2187  0.652764
2188  0.689895
2189  0.690091
2190  0.498557

[2191 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2516  0.864540
2517  0.792713
2518  0.762346
2519  0.721256
2520  0.811696

[2521 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2371  0.774327
2372  0.749428
2373  0.754241
2374  0.746096
2375  0.693527

[2376 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2293  0.222302
2294  0.172485
2295  0.082673
2296  0.105401
2297  0.280065

[2298 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2146  1.147957
2147  1.142687
2148  1.147184
2149  1.319336
2150  1.223100

[2151 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2282  1.785196
2283  1.779407
2284  1.704952
2285  1.596826
2286  1.431022

[2287 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2468  0.783360
2469  0.843367
2470  0.798559
2471  0.746933
2472  0.648110

[2473 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2382  1.289958
2383  1.425094
2384  1.205929
2385  1.166534
2386  1.098006

[2387 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2473  0.756673
2474  0.748965
2475  0.724262
2476  0.691274
2477  0.619227

[2478 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2520  0.603514
2521  0.640289
2522  0.596556
2523  0.599145
2524  0.670789

[2525 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2339  1.685425
2340  1.635088
2341  1.643593
2342  1.605097
2343  1.536257

[2344 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2524  1.322865
2525  1.336027
2526  1.242895
2527  1.238841
2528  1.100694

[2529 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2069  0.669266
2070  0.665250
2071  0.541476
2072  0.662312
2073  0.794628

[2074 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2465  0.543178
2466  0.477746
2467  0.458174
2468  0.340251
2469  0.105941

[2470 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2493  0.684274
2494  0.657602
2495  0.634913
2496  0.720313
2497  0.692091

[2498 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2539  1.264671
2540  1.251141
2541  1.197902
2542  1.161159
2543  0.988079

[2544 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2464  0.854571
2465  1.045115
2466  0.894779
2467  0.918976
2468  0.821290

[2469 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2429  1.009262
2430  0.979461
2431  1.025484
2432  0.977064
2433  0.910475

[2434 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2420  0.480255
2421  0.463406
2422  0.491220
2423  0.487021
2424  0.497292

[2425 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2209  0.740932
2210  0.706286
2211  0.739214
2212  0.664089
2213  0.565563

[2214 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2510  0.862593
2511  0.925233
2512  0.896097
2513  1.153974
2514  1.044053

[2515 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2394 -0.047073
2395 -0.070758
2396  0.055237
2397  0.017074
2398  0.055182

[2399 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2506  1.276867
2507  1.252135
2508  1.206201
2509  1.067427
2510  0.982455

[2511 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2460  1.362457
2461  1.390126
2462  1.386974
2463  1.366396
2464  1.254469

[2465 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2391  1.159048
2392  1.142911
2393  1.103858
2394  1.022078
2395  1.055203

[2396 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2528  1.116959
2529  1.086452
2530  1.040738
2531  0.992933
2532  0.874348

[2533 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2493  1.056704
2494  1.045531
2495  1.049410
2496  1.026643
2497  1.071070

[2498 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2526  0.839512
2527  0.864118
2528  0.871738
2529  1.006053
2530  0.941028

[2531 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2332  1.525019
2333  1.525093
2334  1.549796
2335  1.527515
2336  1.431213

[2337 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2522  1.857334
2523  1.836164
2524  1.815957
2525  1.774769
2526  1.811639

[2527 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2516  0.826929
2517  0.840751
2518  0.837452
2519  0.727820
2520  0.751102

[2521 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2384  0.257658
2385  0.176854
2386  0.264067
2387  0.222921
2388  0.145302

[2389 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2020  1.908353
2021  2.127320
2022  2.278828
2023  2.577563
2024  2.619050

[2025 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2255  0.846951
2256  0.876377
2257  0.925478
2258  0.797717
2259  0.795017

[2260 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2521  2.133130
2522  2.134006
2523  2.159219
2524  2.391403
2525  2.164847

[2526 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2510  1.150969
2511  1.147845
2512  1.129598
2513  1.055813
2514  0.965458

[2515 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2514  0.661331
2515  0.643900
2516  0.622362
2517  0.567126
2518  0.436785

[2519 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2528  0.663269
2529  0.667334
2530  0.694498
2531  0.704364
2532  0.975696

[2533 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2502  1.250949
2503  1.218887
2504  1.211946
2505  1.124818
2506  1.100296

[2507 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2314 -0.062127
2315 -0.080556
2316 -0.082110
2317 -0.029284
2318 -0.039448

[2319 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2422  1.093443
2423  1.060638
2424  1.092777
2425  1.129458
2426  0.958138

[2427 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2275  1.093057
2276  1.058948
2277  1.091470
2278  1.156406
2279  1.139623

[2280 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2420  1.038923
2421  1.013790
2422  1.033755
2423  1.019239
2424  1.019393

[2425 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2514  0.687354
2515  0.639749
2516  0.547579
2517  0.528705
2518  0.711172

[2519 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2462  0.669253
2463  0.663574
2464  0.626683
2465  0.740161
2466  0.585555

[2467 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2062  0.555274
2063  0.570239
2064  0.553848
2065  0.518289
2066  0.433376

[2067 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2518  0.982981
2519  0.950728
2520  0.953679
2521  0.944992
2522  0.875208

[2523 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2502  0.816066
2503  0.787941
2504  0.621202
2505  0.684646
2506  0.711406

[2507 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2341  1.106719
2342  1.017851
2343  0.967714
2344  1.083275
2345  0.937676

[2346 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2161  0.663025
2162  0.458963
2163  0.353748
2164  0.348076
2165  0.273921

[2166 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2507  1.224747
2508  1.273001
2509  1.276144
2510  1.300023
2511  1.332584

[2512 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2296  0.230355
2297  0.193894
2298  0.103589
2299  0.228027
2300  0.184390

[2301 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1850  0.811294
1851  0.828239
1852  0.819692
1853  0.866129
1854  0.890284

[1855 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2372  1.651720
2373  1.556062
2374  1.642099
2375  1.491447
2376  1.759435

[2377 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2540  1.223891
2541  1.234831
2542  1.231344
2543  1.371413
2544  1.108363

[2545 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2059  0.450123
2060  0.513193
2061  0.459644
2062  0.422441
2063  0.389686

[2064 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2328  1.149131
2329  1.131328
2330  1.126852
2331  1.179067
2332  1.040491

[2333 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2436  0.253211
2437  0.216712
2438  0.216661
2439  0.195121
2440  0.201132

[2441 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2383  1.142517
2384  1.111979
2385  1.132403
2386  1.057766
2387  0.970321

[2388 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2532  0.489803
2533  0.480466
2534  0.491139
2535  0.458915
2536  0.435190

[2537 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2416  1.242212
2417  1.241163
2418  1.283983
2419  1.245750
2420  1.147866

[2421 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2492  0.936492
2493  0.920697
2494  0.912720
2495  1.020709
2496  0.985678

[2497 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2350  1.286861
2351  1.171545
2352  1.189349
2353  1.272353
2354  1.166301

[2355 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2522  1.000823
2523  0.970423
2524  0.955625
2525  0.955259
2526  1.047755

[2527 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2338  1.569870
2339  1.486139
2340  1.466105
2341  1.354771
2342  1.270957

[2343 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2471  2.324666
2472  2.292454
2473  2.313766
2474  2.329255
2475  2.216922

[2476 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2500  0.980513
2501  0.952718
2502  0.907861
2503  0.861946
2504  0.783524

[2505 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2535  0.185975
2536  0.195735
2537  0.164581
2538  0.140213
2539  0.234686

[2540 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2444  1.327667
2445  1.324161
2446  1.322000
2447  1.256721
2448  1.262284

[2449 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2523  0.626065
2524  0.575025
2525  0.603683
2526  0.701064
2527  0.593967

[2528 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2325  0.993092
2326  0.967837
2327  1.023535
2328  0.901530
2329  1.184793

[2330 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2390  1.416049
2391  1.368213
2392  1.386309
2393  1.294054
2394  1.159326

[2395 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2276  1.272311
2277  1.322865
2278  1.323884
2279  1.193397
2280  0.937342

[2281 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2479  1.746562
2480  1.730802
2481  1.736487
2482  1.669097
2483  1.490920

[2484 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2373  0.768993
2374  0.687214
2375  0.659844
2376  0.536949
2377  0.501965

[2378 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2393  0.849721
2394  0.810032
2395  0.838219
2396  0.734455
2397  0.693030

[2398 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2504  1.111638
2505  1.062620
2506  0.998950
2507  0.914231
2508  0.962671

[2509 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2509  1.531604
2510  1.540284
2511  1.542042
2512  1.584305
2513  1.618514

[2514 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2385  1.397774
2386  1.324080
2387  1.338366
2388  1.389978
2389  1.340738

[2390 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2533  0.046985
2534  0.038582
2535  0.028137
2536  0.109473
2537  0.125368

[2538 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2375  1.526406
2376  1.500282
2377  1.554048
2378  1.447422
2379  1.358275

[2380 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2109  0.417177
2110  0.441737
2111  0.463356
2112  0.444425
2113  0.351247

[2114 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2399  0.432429
2400  0.449816
2401  0.488253
2402  0.592016
2403  0.657176

[2404 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2400  1.744288
2401  1.694572
2402  1.720626
2403  1.692362
2404  1.588565

[2405 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2394  1.044833
2395  1.073510
2396  1.141004
2397  1.116815
2398  0.972081

[2399 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2514  0.550841
2515  0.529133
2516  0.561040
2517  0.632965
2518  0.605073

[2519 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2540  0.408630
2541  0.415328
2542  0.425869
2543  0.579181
2544  0.348991

[2545 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2449  0.509841
2450  0.485850
2451  0.502133
2452  0.504214
2453  0.491947

[2454 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2396  1.172394
2397  1.139559
2398  1.141155
2399  1.160471
2400  1.089267

[2401 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2298 -0.073571
2299 -0.137352
2300 -0.080190
2301 -0.157533
2302 -0.057162

[2303 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2390  1.347893
2391  1.311656
2392  1.347496
2393  1.283583
2394  1.343283

[2395 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2419  0.425735
2420  0.485241
2421  0.501824
2422  0.646369
2423  0.703953

[2424 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2534  1.335909
2535  1.236094
2536  1.240209
2537  1.137316
2538  1.072653

[2539 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2183  1.331187
2184  1.274608
2185  1.315047
2186  1.219581
2187  1.229150

[2188 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2436  0.977929
2437  0.947577
2438  0.962282
2439  0.943038
2440  0.955047

[2441 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2404  0.848746
2405  0.855947
2406  0.793345
2407  0.758680
2408  0.716740

[2409 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2534  1.198143
2535  1.146104
2536  1.137094
2537  1.050800
2538  1.161503

[2539 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2449  1.472860
2450  1.380334
2451  1.190369
2452  1.103408
2453  1.244505

[2454 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2121  0.402378
2122  0.324016
2123  0.354005
2124  0.333467
2125  0.336484

[2126 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2514  0.848709
2515  0.894349
2516  0.848938
2517  0.836336
2518  1.042627

[2519 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2433  1.679170
2434  1.514010
2435  1.543958
2436  1.386290
2437  1.223907

[2438 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2343  1.076510
2344  0.996465
2345  0.982786
2346  0.843135
2347  0.791869

[2348 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2311  0.986052
2312  0.909850
2313  0.881051
2314  0.748444
2315  0.760966

[2316 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2520  0.948522
2521  0.954765
2522  0.976264
2523  0.987818
2524  0.912445

[2525 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2148  0.944603
2149  0.952406
2150  1.012184
2151  1.083971
2152  1.001357

[2153 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2404  1.341074
2405  1.288385
2406  1.299843
2407  1.196122
2408  1.117056

[2409 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2347  0.864121
2348  0.871388
2349  0.751283
2350  0.642277
2351  0.666010

[2352 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2538  1.370689
2539  1.333897
2540  1.367183
2541  1.340110
2542  1.280680

[2543 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2095  1.099558
2096  1.073787
2097  1.100260
2098  1.053302
2099  0.975265

[2100 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2472  0.785373
2473  0.827162
2474  0.641588
2475  0.830123
2476  0.930543

[2477 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2508  0.889049
2509  0.887116
2510  0.873626
2511  0.869235
2512  0.824485

[2513 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2339  0.714666
2340  0.749097
2341  0.740060
2342  0.724886
2343  0.646812

[2344 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2386  0.944417
2387  0.954648
2388  1.020934
2389  1.065352
2390  1.000835

[2391 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2479  0.987254
2480  1.023648
2481  1.018055
2482  1.118265
2483  1.151339

[2484 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2408  0.954063
2409  0.943603
2410  0.948897
2411  0.871273
2412  1.021170

[2413 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2085  0.709244
2086  0.740323
2087  0.741513
2088  0.653013
2089  0.389162

[2090 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2450  0.489549
2451  0.459157
2452  0.475946
2453  0.492392
2454  0.545215

[2455 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2417  0.808060
2418  0.786718
2419  0.786718
2420  0.860008
2421  0.804513

[2422 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2428  2.175587
2429  2.124439
2430  2.056053
2431  1.915016
2432  1.740539

[2433 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2531  0.748453
2532  0.749329
2533  0.735426
2534  0.747683
2535  0.694277

[2536 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2469  1.581298
2470  1.598304
2471  1.615409
2472  1.486157
2473  1.375254

[2474 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2377  0.421608
2378  0.416371
2379  0.421452
2380  0.500880
2381  0.414326

[2382 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2461  0.694846
2462  0.712816
2463  0.662136
2464  0.677402
2465  0.647788

[2466 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2201  0.704303
2202  0.611264
2203  0.672425
2204  0.492905
2205  0.601876

[2206 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2511  0.991209
2512  0.910680
2513  0.884010
2514  1.018084
2515  0.770799

[2516 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2501  0.370254
2502  0.369169
2503  0.367052
2504  0.355435
2505  0.327279

[2506 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2505  1.279495
2506  1.201427
2507  1.232592
2508  1.139925
2509  1.434100

[2510 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2414  1.736538
2415  1.688697
2416  1.582300
2417  1.349527
2418  1.332127

[2419 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2469  0.262322
2470  0.291590
2471  0.281951
2472  0.288665
2473  0.273574

[2474 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2488  0.607722
2489  0.576709
2490  0.588382
2491  0.482188
2492  0.444381

[2493 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2489  0.451910
2490  0.303330
2491  0.308545
2492  0.152921
2493  0.067195

[2494 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2470  1.293483
2471  1.167864
2472  1.187210
2473  1.081888
2474  1.123006

[2475 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2442  1.351197
2443  1.333724
2444  1.360168
2445  1.385618
2446  1.263554

[2447 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2340  0.882546
2341  0.856528
2342  0.881799
2343  1.060588
2344  1.015980

[2345 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2504  1.308941
2505  1.239319
2506  1.244698
2507  1.135847
2508  1.080249

[2509 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2335  1.823866
2336  1.868339
2337  1.915264
2338  1.702334
2339  1.654557

[2340 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2422  0.822695
2423  0.810951
2424  0.805646
2425  0.794863
2426  0.772081

[2427 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2312  0.951550
2313  0.964281
2314  0.967448
2315  0.902343
2316  0.845410

[2317 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2333  1.180638
2334  1.201672
2335  1.203108
2336  1.126445
2337  1.042299

[2338 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2364  1.041286
2365  1.024002
2366  1.044319
2367  0.955735
2368  0.922641

[2369 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2380  0.976949
2381  0.957206
2382  0.966930
2383  0.925109
2384  0.889944

[2385 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2295  0.240613
2296  0.308709
2297  0.340262
2298  0.346701
2299  0.386212

[2300 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2475  0.865844
2476  0.779076
2477  0.777025
2478  0.516323
2479  0.559908

[2480 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2489  1.980797
2490  1.948911
2491  2.011955
2492  1.906796
2493  1.849148

[2494 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2466  0.680249
2467  0.651401
2468  0.667126
2469  0.740366
2470  0.715061

[2471 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2401  1.834325
2402  1.814351
2403  1.834677
2404  1.719985
2405  1.599512

[2406 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2183  0.709012
2184  0.641757
2185  0.499899
2186  0.473287
2187  0.264448

[2188 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2399  0.765315
2400  0.619579
2401  0.609887
2402  0.514812
2403  0.528086

[2404 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2216  1.009101
2217  1.025721
2218  1.001351
2219  0.847387
2220  0.629700

[2221 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2310  0.958189
2311  0.851239
2312  0.849042
2313  0.793147
2314  0.755918

[2315 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2299  1.458735
2300  1.395363
2301  1.397305
2302  1.276033
2303  1.240663

[2304 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2245  1.087582
2246  1.130884
2247  1.003502
2248  1.146454
2249  0.983069

[2250 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2404  0.628693
2405  0.593455
2406  0.617723
2407  0.601851
2408  0.598495

[2409 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2403  0.452187
2404  0.424895
2405  0.400234
2406  0.335024
2407  0.309629

[2408 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2500  1.426625
2501  1.402341
2502  1.413031
2503  1.413175
2504  1.354214

[2505 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2479  0.747071
2480  0.687690
2481  0.678423
2482  0.766906
2483  0.732277

[2484 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2442  1.931662
2443  1.947555
2444  1.930798
2445  1.739656
2446  1.704222

[2447 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2499  1.178213
2500  1.143111
2501  1.109040
2502  1.094154
2503  0.937020

[2504 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2294  2.019930
2295  1.993239
2296  1.949140
2297  1.881975
2298  1.817996

[2299 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2428  1.105565
2429  1.112515
2430  1.104984
2431  1.009889
2432  0.976597

[2433 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2272  1.419946
2273  1.438511
2274  1.446465
2275  1.373749
2276  1.179537

[2277 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2252  0.825634
2253  0.732117
2254  0.740549
2255  0.557487
2256  0.580616

[2257 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2366  0.370996
2367  0.378666
2368  0.331891
2369  0.243672
2370  0.210282

[2371 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2416  2.558535
2417  2.535901
2418  2.538374
2419  2.444686
2420  2.325395

[2421 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2484  0.834781
2485  0.795613
2486  0.814525
2487  0.797300
2488  0.790860

[2489 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2209  1.359277
2210  1.346349
2211  1.291160
2212  1.202948
2213  1.033125

[2214 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2388  0.766422
2389  0.746806
2390  0.686373
2391  0.681293
2392  0.597944

[2393 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2436  1.573961
2437  1.548814
2438  1.547802
2439  1.581566
2440  1.508712

[2441 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2417  1.015221
2418  1.033602
2419  1.051981
2420  1.022519
2421  0.979006

[2422 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2277  1.317146
2278  1.518679
2279  1.471598
2280  1.357449
2281  1.344716

[2282 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2452  0.657993
2453  0.663341
2454  0.688880
2455  0.643682
2456  0.677288

[2457 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2135  1.264151
2136  1.226335
2137  1.236849
2138  1.235645
2139  1.170425

[2140 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2469  1.268066
2470  1.243498
2471  1.202663
2472  1.136590
2473  1.062847

[2474 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2441  1.037729
2442  1.008355
2443  0.956114
2444  0.891463
2445  0.926648

[2446 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2288 -0.224553
2289 -0.215562
2290 -0.292368
2291 -0.276279
2292 -0.388916

[2293 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2263  0.674353
2264  0.630575
2265  0.684277
2266  0.590450
2267  0.525772

[2268 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2269  2.488465
2270  2.470330
2271  2.491414
2272  2.460104
2273  2.264013

[2274 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2436  1.097183
2437  1.136529
2438  1.123605
2439  1.223747
2440  1.078820

[2441 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2435  0.751873
2436  0.724401
2437  0.725831
2438  0.722982
2439  0.683762

[2440 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2327  0.772865
2328  0.825438
2329  0.848233
2330  0.854222
2331  0.818732

[2332 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2310  0.989635
2311  0.969965
2312  0.914380
2313  0.746679
2314  0.626688

[2315 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2197  1.336075
2198  1.316106
2199  1.293335
2200  1.132573
2201  1.089845

[2202 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2320  0.721422
2321  0.745634
2322  0.749478
2323  0.659514
2324  0.599819

[2325 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2467  0.830748
2468  0.879857
2469  0.789781
2470  0.769243
2471  0.694601

[2472 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2327  0.682083
2328  0.664862
2329  0.659967
2330  0.603421
2331  0.553830

[2332 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2464  0.550215
2465  0.544808
2466  0.537024
2467  0.538514
2468  0.498117

[2469 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2461  0.419804
2462  0.389223
2463  0.396845
2464  0.359915
2465  0.345634

[2466 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2425  0.583274
2426  0.575219
2427  0.543725
2428  0.531607
2429  0.465301

[2430 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2224  1.886754
2225  1.861209
2226  1.821647
2227  1.767346
2228  1.592418

[2229 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2453  0.275755
2454  0.215576
2455  0.240272
2456  0.134609
2457  0.090312

[2458 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2337  1.545672
2338  1.423385
2339  1.435738
2340  1.465212
2341  1.638354

[2342 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2225  1.331564
2226  1.326623
2227  1.236865
2228  1.167246
2229  1.020202

[2230 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2231  1.264062
2232  1.185494
2233  1.127615
2234  1.008900
2235  1.155026

[2236 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2371  1.359349
2372  1.268127
2373  1.263182
2374  1.291650
2375  1.317914

[2376 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2431  1.831930
2432  1.824402
2433  1.818795
2434  1.720576
2435  1.564781

[2436 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2409  0.731884
2410  0.707700
2411  0.675961
2412  0.725538
2413  1.028722

[2414 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2414  0.617289
2415  0.596100
2416  0.649212
2417  0.580677
2418  0.438297

[2419 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2313  1.192467
2314  1.140120
2315  1.050963
2316  0.918666
2317  0.941463

[2318 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2425  0.869276
2426  0.820723
2427  0.879272
2428  0.720538
2429  0.758264

[2430 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2358  0.961331
2359  0.923668
2360  0.937518
2361  0.894344
2362  0.849337

[2363 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2281  0.772545
2282  0.741887
2283  0.717865
2284  0.705812
2285  0.639684

[2286 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2146  1.502441
2147  1.450905
2148  1.425007
2149  1.363450
2150  1.249533

[2151 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2405  1.164423
2406  1.271917
2407  1.311171
2408  1.173376
2409  1.214235

[2410 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2141  0.969847
2142  0.813804
2143  0.812948
2144  0.785028
2145  0.586373

[2146 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2322  0.552475
2323  0.593571
2324  0.617878
2325  0.625720
2326  0.591469

[2327 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2192  0.918323
2193  0.861761
2194  0.873311
2195  0.729231
2196  0.624633

[2197 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2324  1.422286
2325  1.477173
2326  1.397179
2327  1.374904
2328  1.274138

[2329 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2393  1.273251
2394  1.258629
2395  1.293640
2396  1.282964
2397  1.397840

[2398 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2370  1.752180
2371  1.709745
2372  1.727502
2373  1.690781
2374  1.718455

[2375 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2210  1.110604
2211  1.061151
2212  1.077702
2213  1.046109
2214  0.995179

[2215 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2227  0.291760
2228  0.151543
2229  0.113283
2230  0.110721
2231 -0.006432

[2232 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2438  0.471093
2439  0.430046
2440  0.460903
2441  0.401914
2442  0.394254

[2443 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2434  0.700970
2435  0.672376
2436  0.659701
2437  0.649185
2438  0.615010

[2439 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2326  1.391179
2327  1.341141
2328  1.345968
2329  1.310548
2330  1.192498

[2331 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2416  0.856206
2417  0.854392
2418  0.841838
2419  0.824346
2420  0.962400

[2421 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2271  0.916838
2272  0.938508
2273  0.952333
2274  0.925663
2275  0.897747

[2276 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2425  0.348471
2426  0.337545
2427  0.331901
2428  0.279626
2429  0.251375

[2430 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2236  0.976928
2237  0.917869
2238  0.959510
2239  0.900323
2240  0.720694

[2241 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2110  0.959736
2111  1.288827
2112  1.054713
2113  1.077345
2114  0.901082

[2115 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2237  0.397527
2238  0.417977
2239  0.455256
2240  0.353750
2241  0.263341

[2242 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2424  1.343047
2425  1.332312
2426  1.340127
2427  1.249806
2428  1.213343

[2429 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2344  1.847237
2345  1.803924
2346  1.835184
2347  1.739984
2348  1.556034

[2349 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2414  1.109684
2415  1.084109
2416  1.107791
2417  1.169200
2418  1.149207

[2419 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2272  0.764012
2273  0.737065
2274  0.744436
2275  0.672424
2276  0.562424

[2277 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2393  0.716092
2394  0.798306
2395  0.730880
2396  0.680187
2397  0.563736

[2398 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2392  0.541674
2393  0.555414
2394  0.569722
2395  0.525825
2396  0.493356

[2397 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2288  0.974697
2289  0.992749
2290  0.967569
2291  0.953061
2292  0.903827

[2293 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2273  0.681638
2274  0.789965
2275  0.790419
2276  0.713740
2277  0.690965

[2278 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2273  2.197913
2274  2.236074
2275  2.169837
2276  2.038005
2277  1.855470

[2278 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2161  0.138452
2162  0.090003
2163  0.044445
2164  0.058525
2165  0.086193

[2166 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2304  0.520164
2305  0.478065
2306  0.492442
2307  0.543801
2308  0.659544

[2309 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2188  1.411329
2189  1.449760
2190  1.422235
2191  1.390780
2192  1.192618

[2193 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2358  0.976222
2359  0.959317
2360  0.967573
2361  1.041092
2362  0.952926

[2363 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2368  1.146136
2369  1.113755
2370  1.129387
2371  1.077087
2372  1.045608

[2373 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2120  0.814170
2121  0.820712
2122  0.840182
2123  0.810301
2124  0.759032

[2125 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2167  0.754477
2168  0.731303
2169  0.744330
2170  0.721195
2171  0.631881

[2172 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2408  1.283879
2409  1.244506
2410  1.224231
2411  1.161305
2412  1.057062

[2413 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2089  0.652285
2090  0.634134
2091  0.640534
2092  0.627024
2093  0.599596

[2094 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2274  1.136924
2275  1.087321
2276  1.063228
2277  0.939776
2278  0.855660

[2279 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2103  1.269613
2104  1.236227
2105  1.165967
2106  1.118959
2107  0.880074

[2108 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2403  0.806112
2404  0.725766
2405  0.691419
2406  0.657691
2407  0.603464

[2408 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2360  1.912191
2361  1.903719
2362  1.931224
2363  1.846091
2364  1.700071

[2365 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1908  0.710939
1909  0.756040
1910  0.781794
1911  0.778899
1912  0.788350

[1913 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2256  1.000027
2257  0.871024
2258  0.894343
2259  0.821959
2260  0.791529

[2261 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2255  1.570055
2256  1.524091
2257  1.539120
2258  1.662757
2259  1.523388

[2260 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2192  0.550716
2193  0.627130
2194  0.628966
2195  0.578449
2196  0.486825

[2197 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2358  0.793417
2359  0.745958
2360  0.720793
2361  0.663922
2362  0.628731

[2363 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2353  0.724201
2354  0.717603
2355  0.676407
2356  0.645012
2357  0.582109

[2358 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2331  2.127139
2332  2.097306
2333  2.109777
2334  2.144683
2335  2.091701

[2336 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2396  0.636065
2397  0.600175
2398  0.530533
2399  0.576619
2400  0.503349

[2401 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2284  0.614792
2285  0.658919
2286  0.644704
2287  0.832424
2288  0.836333

[2289 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2307  1.491853
2308  1.597820
2309  1.500554
2310  1.549367
2311  1.330541

[2312 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2309  1.964448
2310  1.900068
2311  1.907287
2312  1.826679
2313  1.758305

[2314 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2340  0.910235
2341  0.958246
2342  0.956105
2343  1.060561
2344  0.976507

[2345 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2283  0.496491
2284  0.494977
2285  0.496231
2286  0.522407
2287  0.497828

[2288 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2383  1.571061
2384  1.561923
2385  1.576441
2386  1.487617
2387  1.373562

[2388 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1802  1.254293
1803  1.207099
1804  1.253274
1805  1.246210
1806  1.126344

[1807 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2235  0.635371
2236  0.600472
2237  0.566721
2238  0.572800
2239  0.456212

[2240 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2224  1.911087
2225  1.820088
2226  1.998472
2227  1.719323
2228  1.455807

[2229 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2309  1.352712
2310  1.297956
2311  1.334460
2312  1.237637
2313  1.294162

[2314 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2241  0.879733
2242  0.851458
2243  0.876501
2244  0.869900
2245  0.856437

[2246 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2282  0.751748
2283  0.761686
2284  0.735293
2285  0.785617
2286  0.740149

[2287 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2263  1.204131
2264  1.199242
2265  1.259141
2266  1.201078
2267  1.064149

[2268 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2257  1.229638
2258  1.144489
2259  1.198113
2260  1.139392
2261  1.085581

[2262 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2359  0.650374
2360  0.620437
2361  0.611155
2362  0.540475
2363  0.525845

[2364 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1924  1.101136
1925  1.011944
1926  1.078715
1927  0.994894
1928  0.885615

[1929 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2303  1.174694
2304  1.177966
2305  1.208994
2306  1.128111
2307  1.045978

[2308 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2344  1.971769
2345  1.903481
2346  1.934140
2347  2.133342
2348  1.988573

[2349 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2220  0.943640
2221  0.980648
2222  0.993727
2223  0.934282
2224  0.923089

[2225 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2012 -0.502460
2013 -0.613229
2014 -0.558417
2015 -0.343314
2016 -0.251764

[2017 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2282  0.649867
2283  0.614918
2284  0.650373
2285  0.653005
2286  0.621190

[2287 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2321  0.997668
2322  0.989421
2323  1.004576
2324  0.951735
2325  0.906758

[2326 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2330  0.178061
2331  0.117745
2332  0.163663
2333  0.059087
2334  0.327686

[2335 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2233  1.634558
2234  1.575912
2235  1.592080
2236  1.567967
2237  1.455748

[2238 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2312  0.842777
2313  0.824763
2314  0.824184
2315  0.795700
2316  0.879452

[2317 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2213  1.106605
2214  1.058968
2215  1.023680
2216  0.916309
2217  0.924087

[2218 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2359  1.628663
2360  1.588888
2361  1.598756
2362  1.476647
2363  1.360189

[2364 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2016  0.362463
2017  0.381740
2018  0.432133
2019  0.357100
2020  0.329397

[2021 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2127  1.066236
2128  1.037288
2129  0.995431
2130  1.009932
2131  1.065010

[2132 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2333  1.322097
2334  1.289538
2335  1.269311
2336  1.250770
2337  1.215595

[2338 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2321  1.539675
2322  1.542500
2323  1.520248
2324  1.506907
2325  1.386436

[2326 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2315  0.828869
2316  0.721002
2317  0.781585
2318  0.659042
2319  0.657571

[2320 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2348  0.632991
2349  0.512261
2350  0.476743
2351  0.307261
2352  0.217168

[2353 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2111  1.321486
2112  1.254428
2113  1.259735
2114  1.103435
2115  1.039598

[2116 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2054  0.470659
2055  0.448154
2056  0.509213
2057  0.457115
2058  0.380239

[2059 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2334  0.537731
2335  0.544913
2336  0.527703
2337  0.535575
2338  0.484080

[2339 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2314  0.598918
2315  0.585300
2316  0.560611
2317  0.581344
2318  0.579546

[2319 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2331  0.557369
2332  0.574339
2333  0.568681
2334  0.600438
2335  0.577390

[2336 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2311  0.236752
2312  0.082200
2313  0.050199
2314  0.069641
2315 -0.188593

[2316 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2280  1.744581
2281  1.673687
2282  1.707610
2283  1.629358
2284  1.428832

[2285 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2263  1.697757
2264  1.637927
2265  1.710663
2266  1.835398
2267  1.741186

[2268 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2177  0.609296
2178  0.594120
2179  0.557912
2180  0.518848
2181  0.477013

[2182 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2211  1.037125
2212  0.962922
2213  0.952633
2214  0.993926
2215  0.949820

[2216 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2311 -0.076362
2312  0.040896
2313 -0.074541
2314 -0.150654
2315 -0.159214

[2316 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1972  0.014172
1973  0.058674
1974 -0.001354
1975  0.025314
1976 -0.119865

[1977 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2294  0.742290
2295  0.701573
2296  0.727762
2297  0.797186
2298  0.729368

[2299 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1988  0.577157
1989  0.534689
1990  0.551981
1991  0.600365
1992  0.586121

[1993 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2082  0.819277
2083  0.868458
2084  0.851563
2085  0.940611
2086  0.813337

[2087 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1923  1.496700
1924  1.402374
1925  1.362361
1926  1.335472
1927  1.275261

[1928 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2137  0.933422
2138  0.950135
2139  0.970721
2140  1.006769
2141  1.156311

[2142 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2323  0.784793
2324  0.810468
2325  0.867990
2326  0.971736
2327  1.007985

[2328 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1892  0.637347
1893  0.635081
1894  0.636870
1895  0.599156
1896  0.685795

[1897 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2247  1.551662
2248  1.524112
2249  1.549621
2250  1.605438
2251  1.624732

[2252 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2285  0.172703
2286  0.153710
2287  0.148952
2288  0.264265
2289  0.207382

[2290 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1907  1.252628
1908  1.221127
1909  1.229666
1910  1.173980
1911  1.113454

[1912 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2117  0.400949
2118  0.279381
2119  0.241636
2120  0.215628
2121  0.167279

[2122 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2081  0.293253
2082  0.234556
2083  0.279000
2084  0.232814
2085  0.243592

[2086 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2076  1.334930
2077  1.363768
2078  1.347381
2079  1.348345
2080  1.289867

[2081 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2282  0.847954
2283  0.816630
2284  0.801989
2285  0.734038
2286  0.667317

[2287 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2043  1.067474
2044  1.070764
2045  1.248225
2046  1.089358
2047  1.357050

[2048 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2288  1.490856
2289  1.449468
2290  1.421370
2291  1.257095
2292  1.203408

[2293 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2181  1.304689
2182  1.225359
2183  1.216358
2184  1.090095
2185  1.031739

[2186 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2111  0.198067
2112  0.143609
2113  0.130669
2114  0.249226
2115  0.221501

[2116 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2307  0.793292
2308  0.778011
2309  0.784501
2310  0.742131
2311  0.730873

[2312 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2282  1.303276
2283  1.226154
2284  1.204836
2285  1.032729
2286  0.988696

[2287 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2198  0.607534
2199  0.623746
2200  0.645781
2201  0.606530
2202  0.608887

[2203 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2058  0.850207
2059  0.865772
2060  0.846135
2061  0.755301
2062  0.519006

[2063 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2107  1.155515
2108  1.117801
2109  1.160880
2110  1.087024
2111  1.130740

[2112 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2153  0.943988
2154  0.892267
2155  0.901250
2156  0.827733
2157  0.792883

[2158 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2182  0.548497
2183  0.502643
2184  0.551104
2185  0.541942
2186  0.470446

[2187 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2184 -0.318543
2185 -0.443029
2186 -0.501317
2187 -0.475344
2188 -0.206281

[2189 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2139  2.561334
2140  2.562005
2141  2.599958
2142  2.516215
2143  2.306326

[2144 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2258  1.028927
2259  1.007191
2260  0.950677
2261  0.896226
2262  0.819318

[2263 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2183  1.070627
2184  1.058713
2185  0.941496
2186  0.840153
2187  0.632608

[2188 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2274  0.936070
2275  0.871842
2276  0.868960
2277  0.888480
2278  0.885064

[2279 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2244  0.782713
2245  0.805828
2246  0.802464
2247  0.813045
2248  0.675408

[2249 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2179  0.735297
2180  0.705898
2181  0.653187
2182  0.675842
2183  0.613318

[2184 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2280  0.724596
2281  0.683174
2282  0.796783
2283  0.755473
2284  0.776204

[2285 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2143  2.032025
2144  2.022565
2145  2.049538
2146  2.103527
2147  1.870098

[2148 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2240  0.843126
2241  0.847712
2242  0.867726
2243  0.944873
2244  0.860343

[2245 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2254  0.768668
2255  0.714672
2256  0.735442
2257  0.922031
2258  0.946386

[2259 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2276  0.972939
2277  0.949156
2278  0.968403
2279  0.902209
2280  0.844274

[2281 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2278  1.505866
2279  1.504846
2280  1.431288
2281  1.535119
2282  1.432342

[2283 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2094  0.844193
2095  0.803691
2096  0.806065
2097  0.778700
2098  0.756644

[2099 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2247  0.601460
2248  0.572160
2249  0.596575
2250  0.548579
2251  0.534300

[2252 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2124  1.376525
2125  1.340606
2126  1.339809
2127  1.238163
2128  1.145721

[2129 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2043  0.809148
2044  0.891055
2045  0.866587
2046  0.834930
2047  0.837436

[2048 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2203  1.215296
2204  1.137918
2205  1.140329
2206  1.034924
2207  0.975368

[2208 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2069  1.388072
2070  1.318477
2071  1.341703
2072  1.242934
2073  1.177420

[2074 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2181  0.439972
2182  0.596736
2183  0.546583
2184  0.602395
2185  0.604223

[2186 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2162  0.526668
2163  0.512188
2164  0.558856
2165  0.466884
2166  0.424092

[2167 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2268  0.513308
2269  0.524033
2270  0.542335
2271  0.522966
2272  0.495239

[2273 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2112 -0.445991
2113 -0.313458
2114 -0.472857
2115 -0.362746
2116 -0.406831

[2117 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2184  1.295605
2185  1.292179
2186  1.278506
2187  1.199613
2188  1.198999

[2189 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2141  0.709856
2142  0.694347
2143  0.721964
2144  0.696646
2145  0.598913

[2146 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2230  1.151663
2231  1.138441
2232  1.101229
2233  1.025418
2234  1.004220

[2235 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1980  1.404093
1981  1.428885
1982  1.402956
1983  1.444185
1984  1.259130

[1985 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2242  0.796159
2243  0.819751
2244  0.750216
2245  0.830348
2246  0.770269

[2247 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2221  0.314249
2222  0.349390
2223  0.346288
2224  0.336571
2225  0.279534

[2226 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1894  0.551561
1895  0.514159
1896  0.562311
1897  0.573856
1898  0.501496

[1899 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2197  1.420678
2198  1.268269
2199  1.295931
2200  1.124049
2201  1.145018

[2202 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2119  1.688845
2120  1.695218
2121  1.699518
2122  1.995251
2123  1.917445

[2124 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2262  0.803076
2263  0.775043
2264  0.757288
2265  0.806868
2266  0.743098

[2267 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2216  1.205108
2217  1.137912
2218  1.152332
2219  1.253690
2220  1.294796

[2221 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2241  0.788461
2242  0.792332
2243  0.786984
2244  0.788547
2245  0.695417

[2246 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2124  0.824949
2125  0.776972
2126  0.767628
2127  0.767720
2128  0.741285

[2129 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2178  1.032097
2179  1.019850
2180  1.077053
2181  0.987071
2182  0.938582

[2183 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2186  0.340385
2187  0.399449
2188  0.404472
2189  0.480029
2190  0.470686

[2191 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2023  0.433348
2024  0.468424
2025  0.422518
2026  0.490416
2027  0.460878

[2028 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2175  0.887488
2176  0.922570
2177  0.897329
2178  0.945950
2179  0.847294

[2180 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1708  0.471309
1709  0.500004
1710  0.494170
1711  0.572605
1712  0.644362

[1713 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2120  0.552063
2121  0.564530
2122  0.552007
2123  0.522574
2124  0.500948

[2125 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1835  1.069090
1836  1.180065
1837  1.317598
1838  1.403334
1839  1.180032

[1840 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2205  0.870778
2206  0.880292
2207  0.870380
2208  0.982155
2209  0.985411

[2210 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1983  0.695969
1984  0.671205
1985  0.659614
1986  0.645559
1987  0.607173

[1988 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2045  0.676124
2046  0.751544
2047  0.797013
2048  0.677058
2049  0.646160

[2050 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1780  0.635386
1781  0.540458
1782  0.407013
1783  0.492338
1784  0.539178

[1785 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1858  0.287984
1859  0.199649
1860  0.281545
1861  0.167525
1862  0.117846

[1863 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2074  1.446589
2075  1.417741
2076  1.410179
2077  1.518550
2078  1.757489

[2079 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2056  0.624498
2057  0.658312
2058  0.640417
2059  0.571424
2060  0.443385

[2061 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1944  1.769599
1945  1.753019
1946  1.762987
1947  1.747883
1948  1.624616

[1949 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2061  1.169017
2062  1.164063
2063  1.129857
2064  1.055132
2065  0.993730

[2066 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2101 -0.831129
2102 -0.722680
2103 -0.710031
2104 -0.920598
2105 -1.039694

[2106 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2076  0.502213
2077  0.514797
2078  0.536528
2079  0.534335
2080  0.457287

[2081 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2153  1.220671
2154  1.169461
2155  1.144049
2156  1.007185
2157  0.901043

[2158 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1972  0.460773
1973  0.610251
1974  0.540301
1975  0.559584
1976  0.378862

[1977 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2193  0.857907
2194  0.805302
2195  0.698688
2196  0.882146
2197  1.034217

[2198 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1994  0.853440
1995  0.872413
1996  0.798435
1997  0.773384
1998  0.628700

[1999 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2071  1.418665
2072  1.408772
2073  1.444506
2074  1.407605
2075  1.356430

[2076 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2190  1.049547
2191  1.079193
2192  1.067785
2193  1.206671
2194  1.098238

[2195 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2082  0.275543
2083  0.375850
2084  0.375594
2085  0.358673
2086  0.311483

[2087 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2158  0.982494
2159  0.972488
2160  0.918692
2161  0.824115
2162  0.773628

[2163 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2029  0.921211
2030  0.889259
2031  0.967419
2032  0.936888
2033  1.072415

[2034 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1894  1.312149
1895  1.183323
1896  1.155044
1897  1.167881
1898  1.044664

[1899 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2165  0.961267
2166  0.965210
2167  0.978186
2168  0.853375
2169  0.819178

[2170 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2172  0.772376
2173  0.846532
2174  0.869288
2175  0.955871
2176  0.901817

[2177 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2182  0.733016
2183  0.726125
2184  0.758553
2185  0.763624
2186  0.827256

[2187 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1923  0.336143
1924  0.404752
1925  0.444957
1926  0.457920
1927  0.446822

[1928 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2146  1.290582
2147  1.311886
2148  1.338553
2149  1.327133
2150  1.243268

[2151 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2102  0.979377
2103  0.964392
2104  0.991505
2105  0.971834
2106  0.930346

[2107 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2077  1.309801
2078  1.300896
2079  1.340924
2080  1.311840
2081  1.212248

[2082 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1917  2.270738
1918  2.237251
1919  2.282269
1920  2.197370
1921  1.952307

[1922 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2067  0.758516
2068  0.739088
2069  0.722110
2070  0.804570
2071  0.705545

[2072 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1695  1.310070
1696  1.294259
1697  1.369252
1698  1.242820
1699  1.156349

[1700 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2144 -0.151719
2145 -0.024170
2146 -0.037231
2147 -0.171351
2148 -0.255482

[2149 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1702  0.511872
1703  0.521171
1704  0.547806
1705  0.529193
1706  0.548461

[1707 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1996  1.507115
1997  1.448714
1998  1.338249
1999  1.430856
2000  1.368567

[2001 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1941  1.549905
1942  1.430234
1943  1.390462
1944  1.254566
1945  1.188682

[1946 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1979  0.888272
1980  0.875746
1981  0.870884
1982  0.725464
1983  0.658613

[1984 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1756  0.798060
1757  0.804837
1758  0.821746
1759  0.793406
1760  0.745572

[1761 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2126  1.584540
2127  1.537282
2128  1.527145
2129  1.550259
2130  1.317461

[2131 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1892  0.606817
1893  0.529585
1894  0.472605
1895  0.390259
1896  0.717955

[1897 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1893  0.754182
1894  0.736034
1895  0.729931
1896  0.725120
1897  0.648382

[1898 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1939  0.638872
1940  0.614673
1941  0.394285
1942  0.352580
1943  0.438400

[1944 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2131  1.068714
2132  1.031582
2133  0.833991
2134  1.106391
2135  1.386673

[2136 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2096  0.842358
2097  0.922420
2098  0.750371
2099  0.701785
2100  0.700393

[2101 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2121  0.850988
2122  0.690602
2123  0.712522
2124  0.595369
2125  0.553002

[2126 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2017  0.108868
2018  0.052287
2019  0.066186
2020  0.085442
2021  0.010350

[2022 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1766  1.176721
1767  1.148420
1768  1.138686
1769  1.038686
1770  1.123427

[1771 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2118  0.761768
2119  0.721054
2120  0.695531
2121  0.696976
2122  0.625500

[2123 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1703  1.094861
1704  1.127546
1705  1.178147
1706  1.081438
1707  1.081214

[1708 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2067  0.736617
2068  0.714681
2069  0.726458
2070  0.685919
2071  0.682726

[2072 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1887  0.696735
1888  0.717549
1889  0.726097
1890  0.622921
1891  0.575287

[1892 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1714  1.089288
1715  1.045532
1716  1.045275
1717  1.047693
1718  0.971708

[1719 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2104  1.592229
2105  1.490067
2106  1.562410
2107  1.430460
2108  1.325931

[2109 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1717  0.957465
1718  0.969083
1719  0.983985
1720  0.942550
1721  0.810217

[1722 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1788  0.945833
1789  0.901224
1790  0.912897
1791  0.900273
1792  0.835850

[1793 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2010  1.125499
2011  1.187423
2012  1.128041
2013  1.253577
2014  1.103587

[2015 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2078  0.731797
2079  0.730867
2080  0.632105
2081  0.660947
2082  0.633397

[2083 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2069  0.535889
2070  0.517986
2071  0.523829
2072  0.541019
2073  0.529737

[2074 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1779  0.674518
1780  0.711596
1781  0.604421
1782  0.690105
1783  0.570626

[1784 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1835  1.279150
1836  1.269009
1837  1.235553
1838  1.176543
1839  1.089444

[1840 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1933  1.094772
1934  1.079898
1935  1.047631
1936  1.168392
1937  1.109185

[1938 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1956  0.789149
1957  0.764378
1958  0.795944
1959  0.739431
1960  0.689117

[1961 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1784  0.232161
1785  0.209783
1786  0.220656
1787  0.159899
1788  0.212302

[1789 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2056  0.564051
2057  0.467144
2058  0.402846
2059  0.358467
2060  0.282646

[2061 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1982  2.640991
1983  2.616933
1984  2.546023
1985  2.483460
1986  2.478876

[1987 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1962  1.245785
1963  1.238761
1964  1.154378
1965  1.125776
1966  0.965866

[1967 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2005  0.416955
2006  0.532280
2007  0.567949
2008  0.598431
2009  0.560711

[2010 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1724  0.834565
1725  0.954748
1726  0.945443
1727  1.109129
1728  0.940240

[1729 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1867  1.008935
1868  0.989986
1869  0.996508
1870  0.890949
1871  0.845196

[1872 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1901  1.477171
1902  1.425476
1903  1.198638
1904  1.353995
1905  1.622381

[1906 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2073  1.079842
2074  1.041785
2075  1.008276
2076  1.082917
2077  1.120819

[2078 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1813  0.860078
1814  0.910390
1815  1.014270
1816  1.008873
1817  1.071624

[1818 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1946  1.619119
1947  1.555919
1948  1.489793
1949  1.419809
1950  1.236664

[1951 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2054  0.164572
2055  0.203978
2056  0.179842
2057  0.241672
2058  0.205267

[2059 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1909  0.883986
1910  0.887115
1911  0.902588
1912  0.874093
1913  0.804836

[1914 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2064  0.749535
2065  0.746525
2066  0.701106
2067  0.687631
2068  0.871370

[2069 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1511  0.311816
1512  0.280243
1513  0.112602
1514 -0.055837
1515 -0.118831

[1516 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2035  1.250232
2036  1.240845
2037  1.252194
2038  1.177395
2039  1.096763

[2040 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1989  1.482663
1990  1.430297
1991  1.398023
1992  1.371214
1993  1.336231

[1994 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1726  1.185162
1727  1.109833
1728  1.086367
1729  1.057393
1730  1.239739

[1731 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2010  0.822288
2011  0.777949
2012  0.804629
2013  0.743447
2014  0.631820

[2015 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1759  0.847097
1760  0.759893
1761  0.563037
1762  0.339754
1763  0.143573

[1764 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2043  0.162247
2044  0.197319
2045  0.196537
2046  0.209822
2047  0.117579

[2048 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1708  1.527704
1709  1.502781
1710  1.485356
1711  1.425627
1712  1.396619

[1713 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1817  1.921849
1818  1.895899
1819  1.911270
1820  1.881271
1821  1.798695

[1822 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1736  0.669493
1737  0.686940
1738  0.669530
1739  0.592239
1740  0.525391

[1741 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1954  1.325267
1955  1.312080
1956  1.288378
1957  1.444417
1958  1.282527

[1959 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2005  0.860819
2006  0.845578
2007  0.838617
2008  0.770403
2009  0.720938

[2010 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1818  0.722634
1819  0.714913
1820  0.763866
1821  0.739648
1822  0.620127

[1823 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1836  1.031925
1837  1.116262
1838  1.163330
1839  1.316196
1840  1.332843

[1841 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1941  0.521572
1942  0.546863
1943  0.485999
1944  0.610070
1945  0.502304

[1946 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1833  1.201020
1834  1.115141
1835  1.156152
1836  1.167627
1837  1.138345

[1838 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1781  1.190465
1782  1.230667
1783  1.252363
1784  1.191369
1785  1.181120

[1786 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1799  1.114299
1800  1.104807
1801  1.135552
1802  1.117123
1803  1.085998

[1804 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1724  0.680005
1725  0.709431
1726  0.712194
1727  0.777321
1728  0.719811

[1729 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1995  1.450461
1996  1.444893
1997  1.496487
1998  1.388392
1999  1.313231

[2000 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1822  0.690390
1823  0.675310
1824  0.715119
1825  0.761180
1826  0.715520

[1827 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1776  1.085890
1777  1.084274
1778  1.089748
1779  1.060354
1780  0.954235

[1781 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1780  0.861789
1781  0.859644
1782  0.863129
1783  0.712089
1784  0.590980

[1785 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1783  0.854844
1784  0.861594
1785  0.909755
1786  0.915435
1787  0.893795

[1788 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1881  0.418669
1882  0.418210
1883  0.385980
1884  0.299078
1885  0.258824

[1886 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1883  0.579420
1884  0.556870
1885  0.569068
1886  0.554590
1887  0.572156

[1888 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1962  1.150974
1963  1.109322
1964  1.149475
1965  1.141342
1966  1.114387

[1967 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1958  0.760334
1959  0.752552
1960  0.691139
1961  0.680803
1962  0.623314

[1963 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1583  0.059082
1584  0.038618
1585  0.037790
1586 -0.028018
1587 -0.141061

[1588 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1729  0.927811
1730  0.850074
1731  0.896886
1732  0.949931
1733  0.927468

[1734 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1900  0.753748
1901  0.768071
1902  0.765303
1903  0.716511
1904  0.756279

[1905 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1926 -0.057708
1927 -0.083062
1928 -0.059900
1929 -0.173368
1930 -0.153585

[1931 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1881  1.267418
1882  1.369520
1883  1.357657
1884  1.327754
1885  1.228889

[1886 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1504  0.590724
1505  0.421688
1506  0.553812
1507  0.504937
1508  0.495576

[1509 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1806  1.318638
1807  0.961630
1808  0.920919
1809  1.039803
1810  1.000505

[1811 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1860  0.579314
1861  0.568367
1862  0.580047
1863  0.598445
1864  0.534157

[1865 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1785  1.577892
1786  1.473885
1787  1.473818
1788  1.155280
1789  1.147355

[1790 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1615  0.810646
1616  0.763223
1617  0.734094
1618  0.657162
1619  0.559326

[1620 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1743  1.317615
1744  1.280044
1745  1.270323
1746  1.217258
1747  1.310886

[1748 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1838  0.837106
1839  0.754575
1840  0.777923
1841  0.719985
1842  0.719313

[1843 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1927  0.327820
1928  0.294018
1929  0.325074
1930  0.276775
1931  0.273579

[1932 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1851  1.408100
1852  1.443697
1853  1.489742
1854  1.584862
1855  1.541065

[1856 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1911  1.139489
1912  1.082738
1913  1.119771
1914  1.086230
1915  1.035696

[1916 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1914  1.099169
1915  1.118815
1916  1.103771
1917  0.990339
1918  0.801712

[1919 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1722  0.217978
1723  0.194418
1724  0.205331
1725  0.172383
1726  0.180483

[1727 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1817  0.497633
1818  0.593730
1819  0.644923
1820  0.630933
1821  0.626619

[1822 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1826 -0.357858
1827 -0.306846
1828 -0.298696
1829 -0.156125
1830 -0.189332

[1831 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1649  0.050675
1650  0.037500
1651  0.012801
1652 -0.040537
1653 -0.069453

[1654 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1879  0.808165
1880  0.820470
1881  0.820145
1882  0.805271
1883  0.724711

[1884 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1688  0.851903
1689  1.064223
1690  1.122331
1691  0.939276
1692  0.862687

[1693 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1823  0.677252
1824  0.633335
1825  0.609530
1826  0.555274
1827  0.451313

[1828 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1870  1.001487
1871  1.019987
1872  1.032238
1873  1.030200
1874  0.931632

[1875 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1632  1.487556
1633  1.438268
1634  1.480796
1635  1.417253
1636  1.261327

[1637 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1863  0.505055
1864  0.449947
1865  0.479212
1866  0.462287
1867  0.320316

[1868 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1795  0.531220
1796  0.550884
1797  0.549324
1798  0.539812
1799  0.554164

[1800 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1813  1.216257
1814  1.315033
1815  1.215297
1816  1.126123
1817  1.256170

[1818 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1699  0.877489
1700  0.857467
1701  0.792548
1702  0.709775
1703  0.660676

[1704 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1564  1.146779
1565  1.133647
1566  1.120972
1567  1.001122
1568  0.864773

[1569 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1551  1.217180
1552  1.220772
1553  1.133863
1554  1.335428
1555  1.222405

[1556 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1311  1.004047
1312  0.957082
1313  0.986106
1314  0.772279
1315  0.917606

[1316 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1485  0.926591
1486  0.901810
1487  0.903864
1488  0.816458
1489  0.774661

[1490 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1535  1.753309
1536  1.709019
1537  1.669580
1538  1.547748
1539  1.422986

[1540 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1396  0.345668
1397  0.368363
1398  0.457887
1399  0.916632
1400  0.875915

[1401 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1365  1.333720
1366  1.303196
1367  1.328677
1368  1.222614
1369  1.101282

[1370 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1513  1.473079
1514  1.428897
1515  1.462600
1516  1.341610
1517  1.248303

[1518 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1534  0.489656
1535  0.481304
1536  0.416993
1537  0.528767
1538  0.526336

[1539 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1535  1.149303
1536  1.131796
1537  1.033583
1538  0.877243
1539  0.798958

[1540 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1379  0.590055
1380  0.627672
1381  0.684349
1382  0.673753
1383  0.506282

[1384 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1386  0.645642
1387  0.600393
1388  0.585299
1389  0.528954
1390  0.479851

[1391 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1534  0.718393
1535  0.550628
1536  0.516271
1537  0.692466
1538  0.462972

[1539 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1290  0.709023
1291  0.621535
1292  0.560975
1293  0.587234
1294  0.685665

[1295 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1160  0.907837
1161  0.960777
1162  0.975292
1163  1.021165
1164  0.955035

[1165 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1469  0.717080
1470  0.702124
1471  0.721562
1472  0.721166
1473  0.678286

[1474 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1463  0.080057
1464  0.135270
1465  0.231641
1466  0.168642
1467  0.140608

[1468 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1302  1.021508
1303  0.989186
1304  1.011976
1305  1.011760
1306  1.006426

[1307 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1427  1.486164
1428  1.475262
1429  1.456600
1430  1.326956
1431  1.188484

[1432 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1387  0.409424
1388  0.418033
1389  0.435362
1390  0.533014
1391  0.494452

[1392 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1360  0.624600
1361  0.638440
1362  0.560619
1363  0.686213
1364  0.490957

[1365 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1305  0.695666
1306  0.699004
1307  0.682978
1308  0.646690
1309  0.613265

[1310 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1309  1.260596
1310  1.237760
1311  1.247564
1312  1.236643
1313  1.155244

[1314 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1260  1.307499
1261  1.289065
1262  1.271879
1263  1.142762
1264  1.075501

[1265 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1362  0.297628
1363  0.499807
1364  0.433053
1365  0.185222
1366  0.151609

[1367 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1339  0.862634
1340  0.850600
1341  0.864835
1342  0.889921
1343  0.852709

[1344 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1337  1.229648
1338  1.267897
1339  1.290965
1340  1.220995
1341  1.181043

[1342 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1306  1.423017
1307  1.499551
1308  1.501768
1309  1.595772
1310  1.263175

[1311 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1137  1.251442
1138  1.258905
1139  1.349654
1140  1.241904
1141  1.186388

[1142 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1328  0.946285
1329  0.944865
1330  0.973357
1331  0.992857
1332  0.966877

[1333 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1334  0.315948
1335  0.327293
1336  0.315419
1337  0.338897
1338  0.319935

[1339 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1206  1.243672
1207  1.240166
1208  1.227143
1209  1.177638
1210  1.146237

[1211 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
874  1.100520
875  1.115350
876  1.158035
877  1.024906
878  1.041403

[879 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1148  0.245340
1149  0.346224
1150  0.135198
1151  0.257770
1152  0.606538

[1153 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1257  1.030053
1258  0.994158
1259  1.036627
1260  0.971476
1261  0.865309

[1262 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1217 -0.058572
1218 -0.081731
1219 -0.078870
1220 -0.058086
1221 -0.075493

[1222 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1279  1.281666
1280  1.224653
1281  1.185536
1282  1.204483
1283  1.179216

[1284 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1090  0.720907
1091  0.756769
1092  0.797019
1093  0.648848
1094  0.613669

[1095 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1289  0.753401
1290  0.815172
1291  0.802770
1292  0.856021
1293  0.862264

[1294 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1224  1.796926
1225  1.768159
1226  1.681763
1227  1.633493
1228  1.641289

[1229 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1272  0.519138
1273  0.564741
1274  0.594570
1275  0.636640
1276  0.718898

[1277 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1283  0.618006
1284  0.619690
1285  0.677517
1286  0.604359
1287  0.567759

[1288 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1277  0.544140
1278  0.502053
1279  0.543342
1280  0.492454
1281  0.447402

[1282 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1216  1.070443
1217  1.046698
1218  1.063313
1219  1.065573
1220  0.925031

[1221 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1199  0.119496
1200  0.077963
1201  0.099525
1202  0.074366
1203  0.037487

[1204 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1243  0.410942
1244  0.401830
1245  0.335516
1246  0.413597
1247  0.413643

[1248 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1218  0.758097
1219  0.727019
1220  0.714837
1221  0.920995
1222  0.785614

[1223 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1110  1.154064
1111  1.118416
1112  1.086974
1113  0.991493
1114  0.849826

[1115 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1148  1.653808
1149  1.575565
1150  1.518738
1151  1.338945
1152  1.158133

[1153 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1216  0.594890
1217  0.622562
1218  0.597930
1219  0.644610
1220  0.522426

[1221 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1157  0.858920
1158  0.845015
1159  0.855213
1160  0.867478
1161  0.843125

[1162 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1203  0.352443
1204  0.267576
1205  0.304224
1206  0.269655
1207  0.228487

[1208 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1149  0.589221
1150  0.570411
1151  0.564958
1152  0.653115
1153  0.659131

[1154 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1111  0.880748
1112  0.845959
1113  0.850967
1114  0.885887
1115  0.788365

[1116 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1227  0.767189
1228  0.740750
1229  0.749879
1230  0.717720
1231  0.658136

[1232 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1174  0.612627
1175  0.598156
1176  0.573143
1177  0.665025
1178  0.603244

[1179 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1083  0.009403
1084  0.078999
1085  0.077985
1086 -0.037076
1087  0.058612

[1088 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1225  0.637040
1226  0.577148
1227  0.639742
1228  0.552031
1229  0.479397

[1230 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1210 -0.391919
1211 -0.351500
1212 -0.379421
1213 -0.123740
1214 -0.168806

[1215 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1188  1.035668
1189  0.986266
1190  0.974645
1191  0.912969
1192  0.836388

[1193 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1093  1.290029
1094  1.250394
1095  1.383779
1096  1.221143
1097  1.019559

[1098 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1167  0.492981
1168  0.510249
1169  0.535654
1170  0.467310
1171  0.429625

[1172 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1206  0.651283
1207  0.821580
1208  0.748759
1209  0.810760
1210  0.775949

[1211 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1216  0.603775
1217  0.684038
1218  0.644501
1219  0.786668
1220  0.512243

[1221 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
788  0.522659
789  0.553421
790  0.587597
791  0.447533
792  0.463773

[793 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1209  0.589461
1210  0.564811
1211  0.580108
1212  0.565546
1213  0.741207

[1214 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1204  0.602856
1205  0.660310
1206  0.537079
1207  0.689995
1208  0.853172

[1209 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1079  1.753321
1080  1.799845
1081  1.830239
1082  1.812718
1083  1.704342

[1084 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1025  0.692214
1026  0.707722
1027  0.658667
1028  0.695964
1029  0.486148

[1030 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1061  0.170681
1062  0.146167
1063  0.156282
1064  0.123843
1065  0.223442

[1066 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1095  0.919580
1096  0.896026
1097  1.011572
1098  1.027583
1099  0.852770

[1100 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
991  0.626278
992  0.679968
993  0.707330
994  0.681611
995  0.635082

[996 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1096  0.920972
1097  0.907078
1098  0.949546
1099  1.043412
1100  1.062081

[1101 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1105  0.390589
1106  0.384027
1107  0.390851
1108  0.393289
1109  0.382988

[1110 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1089  0.477104
1090  0.400389
1091  0.417363
1092  0.380535
1093  0.241217

[1094 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1095  1.512248
1096  1.473209
1097  1.491722
1098  1.435283
1099  1.340166

[1100 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
954  0.508302
955  0.483642
956  0.532218
957  0.495057
958  0.501267

[959 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1060  0.649282
1061  0.651112
1062  0.650160
1063  0.654533
1064  0.571666

[1065 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1044  0.585304
1045  0.569085
1046  0.578601
1047  0.540847
1048  0.473373

[1049 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1047  0.528675
1048  0.644224
1049  0.691080
1050  0.472810
1051  0.493467

[1052 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1032  0.879494
1033  0.901404
1034  0.843012
1035  0.962293
1036  0.657984

[1037 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1033  1.402035
1034  1.375126
1035  1.405213
1036  1.281338
1037  1.230698

[1038 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1009  0.238514
1010  0.283175
1011  0.285077
1012  0.334062
1013  0.335278

[1014 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
932  0.524561
933  0.587092
934  0.564397
935  0.628024
936  0.566775

[937 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
942  1.352104
943  1.324321
944  1.363176
945  1.266038
946  1.178276

[947 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
986  1.170744
987  1.152802
988  1.191340
989  1.179613
990  1.185557

[991 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
925  1.530223
926  1.512573
927  1.516179
928  1.528187
929  1.629304

[930 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
924  0.855530
925  0.846493
926  0.919927
927  0.972877
928  0.860569

[929 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
990  0.614073
991  0.626819
992  0.653098
993  0.669063
994  0.668445

[995 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
975  0.655196
976  0.661154
977  0.660978
978  0.641206
979  0.675389

[980 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
970  0.054654
971  0.068940
972  0.103253
973  0.053494
974  0.083435

[975 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
905  1.038607
906  1.080453
907  1.207201
908  1.029946
909  1.192382

[910 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
964  1.005114
965  1.035215
966  1.065374
967  1.016054
968  0.997437

[969 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
795  1.021101
796  0.949161
797  0.995166
798  0.966069
799  0.919757

[800 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
915  0.409320
916  0.411697
917  0.427917
918  0.423858
919  0.423467

[920 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
938  1.606715
939  1.647107
940  1.618563
941  1.536576
942  1.403348

[943 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
898  1.091939
899  1.017489
900  1.049149
901  0.975387
902  0.915281

[903 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
928  1.108331
929  1.071851
930  1.019547
931  1.026739
932  0.886652

[933 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
919  0.806475
920  0.750887
921  0.745577
922  0.684963
923  0.739275

[924 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
834  1.854615
835  1.834807
836  1.840531
837  1.719454
838  1.682072

[839 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
864  0.789498
865  0.850697
866  0.653486
867  0.639500
868  0.518736

[869 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
902  1.809528
903  1.773513
904  1.735815
905  1.716485
906  1.529272

[907 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
806  0.514415
807  0.594026
808  0.564976
809  0.542615
810  0.508124

[811 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
893  0.392835
894  0.303787
895  0.312413
896  0.393410
897  0.332967

[898 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
882  0.739160
883  0.770429
884  0.794062
885  0.873025
886  0.814429

[887 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
792  0.525098
793  0.559609
794  0.600482
795  0.642162
796  0.627547

[797 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
865  1.011919
866  1.057142
867  1.023594
868  1.135100
869  1.034979

[870 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
875  1.172850
876  1.184488
877  1.129120
878  1.066747
879  0.886658

[880 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
867  0.432379
868  0.182648
869  0.177886
870  0.135775
871  0.079289

[872 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
854  1.491368
855  1.457537
856  1.433895
857  1.378603
858  1.285216

[859 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
837  1.259911
838  1.192088
839  1.270103
840  1.399752
841  1.185396

[842 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
867  0.369487
868  0.551578
869  0.548270
870  0.554302
871  0.537198

[872 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
860  0.262330
861  0.225698
862  0.202304
863  0.196095
864  0.167362

[865 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
860  0.549889
861  0.505249
862  0.478026
863  0.462885
864  0.462356

[865 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
859  1.430312
860  1.481919
861  1.471138
862  1.412189
863  1.350520

[864 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
858  1.002324
859  0.888536
860  0.739250
861  0.915592
862  0.968320

[863 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
858  0.871753
859  0.936567
860  0.955615
861  1.003421
862  0.981515

[863 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
855  1.015569
856  1.006911
857  1.032598
858  0.967496
859  0.888602

[860 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
850  0.647684
851  0.619481
852  0.458205
853  0.525326
854  0.543466

[855 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
847  0.923414
848  0.967784
849  0.974879
850  0.972793
851  0.895884

[852 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
847  1.058342
848  1.045257
849  0.975491
850  0.853685
851  0.737597

[852 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
836  1.011857
837  1.002740
838  1.011427
839  1.006963
840  0.927358

[841 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
770  2.692515
771  2.640712
772  2.665324
773  2.484947
774  2.193425

[775 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
826  0.183409
827  0.108575
828  0.058117
829  0.266331
830  0.177895

[831 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
818  0.707436
819  0.757933
820  0.788020
821  0.842538
822  0.928113

[823 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
839  0.946732
840  0.950232
841  0.818470
842  0.774983
843  0.734631

[844 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
832  0.487763
833  0.471445
834  0.475651
835  0.471579
836  0.451314

[837 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
828  0.575962
829  0.585674
830  0.590365
831  0.544107
832  0.575410

[833 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
831  0.894548
832  0.864287
833  0.858160
834  0.926177
835  0.865925

[836 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
828  2.148024
829  2.091896
830  2.062725
831  2.015117
832  1.849108

[833 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
824  1.467593
825  1.445450
826  1.436650
827  1.359768
828  1.244776

[829 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
823  0.460299
824  0.473808
825  0.628666
826  0.847900
827  0.699833

[828 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
820  0.932568
821  0.871558
822  0.882842
823  0.766725
824  0.793254

[825 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
816  0.984507
817  1.011872
818  1.030049
819  1.000188
820  0.946465

[821 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
807  2.218633
808  2.208107
809  2.168930
810  1.986732
811  2.030204

[812 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
725  0.768705
726  0.712559
727  0.721986
728  0.904403
729  0.813786

[730 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
801  0.437790
802  0.502332
803  0.476410
804  0.705664
805  0.724867

[806 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
797  1.100735
798  1.043797
799  1.067380
800  1.075534
801  1.107550

[802 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
794  1.478002
795  1.459902
796  1.470948
797  1.439062
798  1.333117

[799 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
665  0.145116
666  0.120014
667  0.137191
668  0.151483
669  0.156824

[670 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
721  0.553044
722  0.464370
723  0.466660
724  0.457970
725  0.671091

[726 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
783  0.454390
784  0.460795
785  0.473234
786  0.388346
787  0.343216

[788 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
783  0.972494
784  0.972120
785  0.906150
786  0.785092
787  0.817352

[788 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
773  0.820599
774  0.895658
775  0.897278
776  0.836753
777  0.780539

[778 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
777  1.483313
778  1.475696
779  1.468214
780  1.462225
781  1.490034

[782 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
781  0.089374
782  0.004576
783  0.054795
784  0.184541
785  0.181234

[786 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
776  0.848518
777  0.857196
778  0.890285
779  0.809452
780  0.757671

[781 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
626 -0.779427
627 -0.758831
628 -0.704068
629 -0.709627
630 -0.714219

[631 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
771  0.724624
772  0.854646
773  0.878964
774  0.986368
775  0.928628

[776 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
694  1.060235
695  1.054869
696  1.031706
697  0.913866
698  0.762531

[699 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
769  0.654476
770  0.641718
771  0.605742
772  0.621950
773  0.650431

[774 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
766  0.805909
767  0.809764
768  0.693091
769  0.597902
770  0.553798

[771 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
758  1.306845
759  1.342708
760  1.375100
761  1.277760
762  1.313406

[763 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
713  0.847811
714  0.817256
715  0.823841
716  0.773918
717  0.756786

[718 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
760  0.990282
761  0.960436
762  0.943344
763  0.946514
764  0.908616

[765 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
693  0.656514
694  0.660353
695  0.640028
696  0.503379
697  0.471246

[698 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
754  0.466113
755  0.501741
756  0.558829
757  0.481674
758  0.396551

[759 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
747  0.643744
748  0.710801
749  0.710503
750  0.701283
751  0.663169

[752 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
748  1.331834
749  1.302679
750  1.263582
751  1.308906
752  1.081956

[753 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
745  0.960409
746  1.157468
747  1.146612
748  1.122043
749  1.064035

[750 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
744  1.611496
745  1.543858
746  1.583540
747  1.552276
748  1.427134

[749 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
721  1.219203
722  1.164751
723  1.171128
724  1.162227
725  1.127278

[726 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
698  0.939468
699  0.973239
700  0.896181
701  0.843065
702  0.684764

[703 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
732  1.018439
733  1.050829
734  0.909428
735  0.775472
736  0.847191

[737 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
715  0.731450
716  0.708118
717  0.690999
718  0.602800
719  0.572808

[720 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
734  0.994707
735  1.006855
736  0.999077
737  0.943421
738  0.872201

[739 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
713  0.867550
714  0.670866
715  0.666601
716  0.810979
717  0.760999

[718 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
726  1.057671
727  0.995356
728  0.975088
729  0.917644
730  0.865253

[731 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
726  1.405211
727  1.367068
728  1.370452
729  1.322790
730  1.206817

[731 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
704  1.282167
705  1.226346
706  1.264510
707  1.164205
708  1.136222

[709 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
707  1.346940
708  1.325888
709  1.349946
710  1.505675
711  1.450671

[712 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
705  0.739510
706  0.738760
707  0.748729
708  0.721130
709  0.650116

[710 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
703  0.155615
704  0.157789
705  0.178312
706  0.138575
707  0.102701

[708 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
678  1.474311
679  1.469962
680  1.489081
681  1.372592
682  1.302490

[683 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
690  1.102658
691  1.075597
692  1.063065
693  1.001308
694  0.957755

[695 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
669  0.621534
670  0.687882
671  0.737128
672  0.555028
673  0.482844

[674 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
682  1.497562
683  1.539341
684  1.590618
685  1.550867
686  1.604330

[687 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
682  0.538672
683  0.511243
684  0.543336
685  0.597812
686  0.540582

[687 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
677  2.734118
678  2.706423
679  2.651314
680  2.520900
681  2.312164

[682 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
674  0.462051
675  0.457388
676  0.425449
677  0.440568
678  0.431871

[679 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
669  0.615445
670  0.559626
671  0.571132
672  0.513922
673  0.467157

[674 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
666  0.342115
667  0.321807
668  0.319432
669  0.315754
670  0.267963

[671 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
666  1.452644
667  1.521731
668  1.423636
669  1.325434
670  1.118292

[671 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
652  1.238257
653  1.236654
654  1.289123
655  1.182987
656  1.076555

[657 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
655  1.058784
656  1.044034
657  1.021004
658  0.939015
659  0.842347

[660 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
655  1.063404
656  1.082107
657  1.103915
658  1.008609
659  1.050457

[660 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
656  1.793749
657  1.800313
658  1.747551
659  1.685774
660  1.483226

[661 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
647  0.031583
648  0.067402
649  0.060997
650  0.026163
651 -0.015291

[652 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
649  1.541967
650  1.536588
651  1.522426
652  1.507695
653  1.334538

[654 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
645  0.824707
646  0.775709
647  0.871939
648  0.886490
649  0.779254

[650 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
642  0.667417
643  0.521931
644  0.470976
645  0.546938
646  0.499269

[647 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
628  0.349425
629  0.337040
630  0.357062
631  0.294523
632  0.269179

[633 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
629  1.923780
630  1.947338
631  1.920762
632  1.836615
633  1.596683

[634 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
621  1.911465
622  1.946446
623  1.972293
624  1.824668
625  1.657641

[626 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
614  1.318115
615  1.288999
616  1.169615
617  1.019285
618  0.901149

[619 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
611  1.641530
612  1.659928
613  1.657473
614  1.608113
615  1.528144

[616 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
616  0.616584
617  0.566863
618  0.556342
619  0.486578
620  0.443533

[621 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
609  1.538579
610  1.594871
611  1.590279
612  1.449576
613  1.406004

[614 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
608  0.905295
609  1.010456
610  0.928685
611  0.887444
612  0.817855

[613 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
604  1.808377
605  1.773420
606  1.754210
607  1.908562
608  1.884055

[609 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
603  0.771415
604  0.722840
605  0.739379
606  0.699888
607  0.601317

[608 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
599  0.982666
600  0.886367
601  0.801549
602  0.489743
603  0.289155

[604 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
597  0.656985
598  0.614398
599  0.495753
600  0.408375
601  0.415183

[602 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
589  2.012498
590  2.007494
591  2.009585
592  2.031841
593  1.812110

[594 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
576  1.706513
577  1.670982
578  1.729043
579  1.745433
580  1.758186

[581 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
565  1.406338
566  1.370129
567  1.367783
568  1.142447
569  1.108537

[570 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
562  0.965374
563  0.953291
564  0.972190
565  1.004823
566  0.974324

[567 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
563  1.217609
564  1.176038
565  1.169810
566  1.398603
567  1.376380

[568 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
535  0.594465
536  0.627557
537  0.619700
538  0.697372
539  0.565482

[540 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
538  0.462793
539  0.465715
540  0.507513
541  0.534033
542  0.480181

[543 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
475 -0.257350
476 -0.046407
477 -0.104528
478 -0.056751
479  0.119490

[480 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
440  0.497073
441  0.466224
442  0.458114
443  0.446725
444  0.422966

[445 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
436  1.044578
437  1.029708
438  1.011838
439  0.915138
440  0.777001

[441 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
424  0.465575
425  0.465345
426  0.461615
427  0.430376
428  0.412341

[429 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
420  1.040901
421  1.013639
422  1.040862
423  0.976138
424  0.909325

[425 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
425  1.848145
426  1.805615
427  1.824056
428  1.707318
429  1.507557

[430 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
403  1.271591
404  1.247963
405  1.307427
406  1.344823
407  1.300739

[408 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
406  0.536288
407  0.557570
408  0.575969
409  0.460484
410  0.474121

[411 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
380  0.758524
381  0.697273
382  0.713591
383  0.722435
384  0.756567

[385 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
375  0.644748
376  0.645857
377  0.613779
378  0.667344
379  0.598294

[380 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
379  1.361648
380  1.357521
381  1.366966
382  1.291592
383  1.222077

[384 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
346  1.387038
347  1.346385
348  1.364259
349  1.446689
350  1.387820

[351 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
340  0.708985
341  0.732851
342  0.738628
343  0.817083
344  0.840477

[345 rows x 1 columns]

            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
335  1.826907
336  1.830969
337  1.821080
338  1.870808
339  1.789245

[340 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
347  0.474056
348  0.469509
349  0.465939
350  0.436818
351  0.443691

[352 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
323  0.542608
324  0.504921
325  0.508611
326  0.546017
327  0.540518

[328 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
314  0.573217
315  0.613387
316  0.543147
317  0.877302
318  0.873957

[319 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
310  1.145519
311  1.157584
312  1.121484
313  0.986524
314  0.924695

[315 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
301  1.532595
302  1.533046
303  1.538098
304  1.336281
305  1.225671

[306 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
275  0.480819
276  0.639499
277  0.661812
278  0.963282
279  0.895437

[280 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
265  1.227970
266  1.258324
267  1.293545
268  1.072976
269  0.990722

[270 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
247  0.273328
248  0.314172
249  0.190228
250  0.356596
251  0.296709

[252 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
220  1.347969
221  1.432799
222  1.485003
223  1.405795
224  1.337694

[225 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
303  0.980022
304  0.890072
305  0.908285
306  0.850837
307  0.872821

[308 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
199  1.704058
200  1.670316
201  1.699413
202  1.704220
203  1.732450

[204 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
210  0.699177
211  0.745425
212  0.761033
213  0.810104
214  0.901766

[215 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
191  1.633271
192  1.605301
193  1.673088
194  1.658571
195  1.550976

[196 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
184  0.915030
185  0.960484
186  1.009293
187  0.921337
188  1.120152

[189 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
160  0.531514
161  0.523209
162  0.548007
163  0.502598
164  0.474841

[165 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
161  1.294720
162  1.258497
163  1.219315
164  1.154480
165  1.013059

[166 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
215  0.734701
216  0.751021
217  0.759890
218  0.724355
219  0.753641

[220 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
151  1.520167
152  1.519321
153  1.520195
154  1.553267
155  1.498522

[156 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
134  1.315070
135  1.393541
136  1.443535
137  1.555248
138  1.354709

[139 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
135  0.803092
136  0.743801
137  0.723515
138  0.825881
139  0.815704

[140 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
124  2.000203
125  2.011541
126  1.961137
127  1.916765
128  1.708421

[129 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
106  0.991527
107  1.040182
108  1.007688
109  0.934740
110  0.938653

[111 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
116  1.475257
117  1.471321
118  1.470697
119  1.382770
120  1.276514

[121 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
111  1.010537
112  0.979098
113  0.969666
114  0.866536
115  0.773119

[116 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
95  2.041562
96  2.076526
97  2.032880
98  1.840603
99  1.822294

[100 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
73  0.260712
74  0.174699
75  0.213591
76  0.385480
77  0.349385

[78 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
66 -0.090017
67  0.083984
68 -0.061356
69 -0.062159
70  0.052288

[71 rows x 1 columns]
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
36 NaN
37 NaN
38 NaN
39 NaN
40 NaN
41 NaN
42 NaN
43 NaN
44 NaN
45 NaN
46 NaN
47 NaN
48 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
36 NaN
37 NaN
38 NaN
39 NaN
40 NaN
41 NaN
42 NaN
43 NaN
44 NaN
45 NaN
46 NaN
47 NaN
48 NaN
49 NaN
50 NaN
51 NaN
52 NaN
53 NaN
54 NaN
55 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
36 NaN
37 NaN
38 NaN
39 NaN
40 NaN
41 NaN
42 NaN
43 NaN
44 NaN
45 NaN
46 NaN
47 NaN
48 NaN
49 NaN
50 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
36 NaN
37 NaN
38 NaN
39 NaN
40 NaN
41 NaN
42 NaN
43 NaN
44 NaN
45 NaN
46 NaN
47 NaN
48 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
36 NaN
37 NaN
38 NaN
39 NaN
40 NaN
41 NaN
42 NaN
43 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
36 NaN
37 NaN
38 NaN
39 NaN
40 NaN
41 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
36 NaN
37 NaN
38 NaN
39 NaN
40 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
36 NaN
37 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
198  0.346732
199  0.332723
200  0.339403
201  0.330363
202  0.321007

[203 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2451  1.431784
2452  1.362140
2453  1.391475
2454  1.334213
2455  1.358335

[2456 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2426  2.622242
2427  2.547340
2428  2.716138
2429  2.531786
2430  2.370157

[2431 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2423  0.651616
2424  0.668761
2425  0.670343
2426  0.806696
2427  0.749468

[2428 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2370  1.222104
2371  1.233328
2372  1.232046
2373  1.155500
2374  1.049323

[2375 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2462  0.884220
2463  0.843605
2464  0.879529
2465  0.738106
2466  0.683932

[2467 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2410  0.840544
2411  0.853403
2412  0.846159
2413  0.824593
2414  0.821821

[2415 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2414  1.317568
2415  1.435638
2416  1.356398
2417  1.393407
2418  1.240321

[2419 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2358  0.035859
2359 -0.029861
2360  0.038291
2361 -0.013677
2362  0.058598

[2363 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2403  1.013215
2404  1.026004
2405  1.037782
2406  1.078074
2407  0.905709

[2408 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2205  1.664433
2206  1.633694
2207  1.661390
2208  1.712659
2209  1.809410

[2210 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2363  1.391619
2364  1.289305
2365  1.236451
2366  1.135637
2367  1.021509

[2368 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2446  0.739698
2447  0.796662
2448  0.791306
2449  0.829879
2450  0.882535

[2451 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2367  1.538197
2368  1.467150
2369  1.513829
2370  1.372822
2371  1.392305

[2372 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2482  1.840643
2483  1.754162
2484  1.608394
2485  1.625769
2486  1.449660

[2487 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2520  1.041392
2521  0.992865
2522  1.038998
2523  1.017363
2524  0.900491

[2525 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2453  0.160017
2454  0.138256
2455  0.116432
2456  0.031439
2457 -0.139159

[2458 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2490  1.285727
2491  1.276376
2492  1.342602
2493  1.295861
2494  1.216644

[2495 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2458  1.198987
2459  1.054765
2460  1.086171
2461  1.047645
2462  0.950479

[2463 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2462  1.231306
2463  1.189322
2464  1.165473
2465  1.055235
2466  0.891915

[2467 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2366  1.102383
2367  1.200582
2368  1.146486
2369  1.120397
2370  0.750574

[2371 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2508  0.907546
2509  0.929458
2510  0.929355
2511  0.922875
2512  0.860737

[2513 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2348  1.012335
2349  1.045087
2350  1.034171
2351  0.882876
2352  0.739327

[2353 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2432  0.975597
2433  0.904335
2434  0.958635
2435  1.175778
2436  0.931258

[2437 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2534  1.243896
2535  1.226331
2536  1.253987
2537  1.226399
2538  1.186794

[2539 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2127  1.493061
2128  1.481201
2129  1.495378
2130  1.310824
2131  1.224291

[2132 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2421  0.445829
2422  0.402560
2423  0.373901
2424  0.236968
2425  0.133263

[2426 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2349  0.937966
2350  0.936550
2351  0.984080
2352  0.850250
2353  0.810084

[2354 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1710  0.703722
1711  0.638969
1712  0.633714
1713  0.616406
1714  0.664617

[1715 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2422  0.957022
2423  0.791816
2424  0.743339
2425  0.671387
2426  0.642168

[2427 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2348  0.267993
2349  0.351264
2350  0.271440
2351  0.458026
2352  0.331984

[2353 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2406  1.724987
2407  1.781930
2408  1.855784
2409  1.775534
2410  1.924515

[2411 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
...       ...
2315  1.23959
2316  1.12787
2317  1.18257
2318  1.13045
2319  1.04326

[2320 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2524  1.944900
2525  1.912872
2526  1.904867
2527  1.954220
2528  1.788682

[2529 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2447  1.006883
2448  1.009248
2449  0.897685
2450  0.730027
2451  0.571652

[2452 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2407  2.160870
2408  2.129575
2409  2.162409
2410  2.120348
2411  1.923650

[2412 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2461  1.521207
2462  1.528805
2463  1.518153
2464  1.425658
2465  1.261490

[2466 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2451  1.994404
2452  1.969626
2453  1.891270
2454  1.884426
2455  1.703823

[2456 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2141  1.084266
2142  1.058962
2143  1.101302
2144  1.039173
2145  1.004633

[2146 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2531  0.408224
2532  0.439912
2533  0.418738
2534  0.384177
2535  0.368996

[2536 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2302  1.433659
2303  1.325345
2304  1.300445
2305  1.175647
2306  1.065540

[2307 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2486  1.334721
2487  1.416624
2488  1.475466
2489  1.383931
2490  1.382729

[2491 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2510  1.966735
2511  1.923812
2512  1.926201
2513  1.685208
2514  1.505426

[2515 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2191  0.981616
2192  0.973994
2193  1.078041
2194  1.014017
2195  0.885002

[2196 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2329  1.329191
2330  1.275789
2331  1.393145
2332  1.377120
2333  1.291526

[2334 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2478  1.424978
2479  1.323998
2480  1.327455
2481  1.223111
2482  1.094172

[2483 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2386  1.265230
2387  1.329387
2388  1.371429
2389  1.163736
2390  1.035898

[2391 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2325  1.637683
2326  1.596178
2327  1.619236
2328  1.609784
2329  1.465040

[2330 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2448  1.271789
2449  1.469052
2450  1.503804
2451  1.529709
2452  1.388884

[2453 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2294  0.078254
2295  0.094233
2296  0.086638
2297  0.168647
2298  0.098118

[2299 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2389  1.261080
2390  1.368966
2391  1.412963
2392  1.533968
2393  1.467478

[2394 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2288  2.070019
2289  2.084499
2290  2.126957
2291  2.152611
2292  1.993100

[2293 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2310  1.608227
2311  1.610357
2312  1.673956
2313  1.689079
2314  1.767409

[2315 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2341  1.097312
2342  1.061862
2343  1.122555
2344  1.051758
2345  0.931361

[2346 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2382  1.912674
2383  1.869450
2384  1.870176
2385  1.773189
2386  1.743719

[2387 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2439  1.007053
2440  1.004706
2441  1.016905
2442  0.988522
2443  0.900785

[2444 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2191  0.972619
2192  0.951819
2193  0.968753
2194  0.966669
2195  1.074776

[2196 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2308  1.254499
2309  1.265108
2310  1.264985
2311  1.201505
2312  1.132404

[2313 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2302  1.075763
2303  1.026136
2304  1.041755
2305  0.957991
2306  0.981817

[2307 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2430  1.880825
2431  1.851357
2432  1.899309
2433  2.049600
2434  1.905694

[2435 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2331  1.284995
2332  1.265000
2333  1.057401
2334  1.162089
2335  0.928949

[2336 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2343  0.990314
2344  0.897097
2345  0.926289
2346  0.980400
2347  0.914156

[2348 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2208  1.788418
2209  1.752892
2210  1.707188
2211  1.570828
2212  1.658387

[2213 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2384  1.204408
2385  1.174572
2386  1.160291
2387  1.152830
2388  1.104227

[2389 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2269  0.793699
2270  0.794869
2271  0.826881
2272  0.852899
2273  0.816223

[2274 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2438  0.811498
2439  0.799411
2440  0.805634
2441  0.849392
2442  0.801563

[2443 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2375  0.936133
2376  0.935832
2377  0.920161
2378  0.982872
2379  0.873275

[2380 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2378  0.827823
2379  0.813254
2380  0.807726
2381  0.744360
2382  0.726502

[2383 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2367  0.631420
2368  0.589900
2369  0.665389
2370  0.632097
2371  0.514792

[2372 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2388  0.815876
2389  0.766414
2390  0.785405
2391  0.841556
2392  0.848707

[2393 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1911  1.587533
1912  1.571252
1913  1.577113
1914  1.507467
1915  1.417528

[1916 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2400  1.706249
2401  1.681656
2402  1.644865
2403  1.545833
2404  1.667264

[2405 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2358  1.718256
2359  1.687859
2360  1.716865
2361  1.668423
2362  1.545613

[2363 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2394  1.646975
2395  1.652944
2396  1.682705
2397  1.590689
2398  1.508150

[2399 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2374  1.565307
2375  1.529200
2376  1.545604
2377  1.481129
2378  1.437165

[2379 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2331  0.984520
2332  0.935713
2333  0.935885
2334  0.906928
2335  0.809452

[2336 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2388  1.882658
2389  1.857224
2390  1.867914
2391  1.781824
2392  1.691869

[2393 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2378  1.778670
2379  1.700692
2380  1.705639
2381  1.601358
2382  1.401938

[2383 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2437  1.335350
2438  1.309213
2439  1.317455
2440  1.312527
2441  1.201221

[2442 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2073  0.743840
2074  0.817147
2075  0.787380
2076  0.738632
2077  0.705917

[2078 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2251  1.707457
2252  1.673375
2253  1.707710
2254  1.671258
2255  1.592542

[2256 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2429  1.057370
2430  1.051651
2431  1.052306
2432  0.999691
2433  0.962269

[2434 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2330  2.158282
2331  2.120406
2332  2.129881
2333  2.017379
2334  1.859434

[2335 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2338  0.930550
2339  0.964826
2340  0.928757
2341  0.953040
2342  0.964824

[2343 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2234  1.865427
2235  1.845396
2236  1.770235
2237  1.905377
2238  1.784127

[2239 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2265  0.580746
2266  0.589862
2267  0.559131
2268  0.458649
2269  0.411958

[2270 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2204  1.085716
2205  1.213578
2206  1.216014
2207  1.428375
2208  1.290009

[2209 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1992  2.236782
1993  2.219472
1994  2.197095
1995  2.176494
1996  2.103081

[1997 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1972  1.113505
1973  1.073867
1974  1.069106
1975  0.925759
1976  0.806101

[1977 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2169  0.944873
2170  0.970591
2171  0.889599
2172  0.801197
2173  1.017298

[2174 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2338  0.870552
2339  0.833100
2340  0.835531
2341  0.762177
2342  0.706539

[2343 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2256  0.777461
2257  0.789308
2258  0.793088
2259  0.669326
2260  0.579444

[2261 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2160  0.635112
2161  0.598541
2162  0.621517
2163  0.486659
2164  0.460298

[2165 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2308  0.785720
2309  0.876343
2310  0.805325
2311  0.854549
2312  0.802084

[2313 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2331  0.988919
2332  1.009256
2333  0.970152
2334  0.861497
2335  0.864851

[2336 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2275  1.373397
2276  1.404248
2277  1.182399
2278  1.099014
2279  1.037321

[2280 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2304  1.366188
2305  1.571112
2306  1.647213
2307  1.736871
2308  1.830373

[2309 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2189  1.181667
2190  1.163284
2191  1.089753
2192  1.110464
2193  0.979250

[2194 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2225  1.069111
2226  1.030596
2227  1.040268
2228  0.976780
2229  0.957700

[2230 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2130  1.402693
2131  1.395107
2132  1.189106
2133  1.112302
2134  1.038109

[2135 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2316  1.427878
2317  1.399408
2318  1.409041
2319  1.320739
2320  1.206580

[2321 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2303  2.072860
2304  2.032405
2305  2.039033
2306  1.838772
2307  1.767197

[2308 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2302  0.413161
2303  0.392253
2304  0.405476
2305  0.394678
2306  0.329855

[2307 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1682  1.140880
1683  1.144869
1684  1.182980
1685  1.139326
1686  1.048398

[1687 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2387  0.782324
2388  0.715161
2389  0.748940
2390  0.689270
2391  0.653572

[2392 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2328  0.305056
2329  0.249345
2330  0.220085
2331  0.009007
2332  0.004986

[2333 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2384  0.770055
2385  0.743864
2386  0.751531
2387  0.697998
2388  0.646968

[2389 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2059  0.597257
2060  0.562937
2061  0.588798
2062  0.598074
2063  0.494791

[2064 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2033  0.930895
2034  1.010329
2035  1.042449
2036  0.973896
2037  1.107158

[2038 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2149  0.525634
2150  0.549328
2151  0.497867
2152  0.494400
2153  0.436077

[2154 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2178  0.744733
2179  0.742713
2180  0.703376
2181  0.534916
2182  0.483192

[2183 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2196  1.168115
2197  1.179662
2198  1.131700
2199  1.036535
2200  0.934705

[2201 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2240  1.958967
2241  1.951325
2242  2.122052
2243  2.175951
2244  1.967286

[2245 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2306  1.101924
2307  1.071846
2308  1.039093
2309  0.971349
2310  0.880156

[2311 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2346  2.614522
2347  2.587527
2348  2.563372
2349  2.565812
2350  2.441155

[2351 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2087  0.063975
2088  0.240395
2089  0.299934
2090  0.582051
2091  0.546483

[2092 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2281  1.271571
2282  1.254926
2283  1.258738
2284  1.261415
2285  1.550951

[2286 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2228  1.703710
2229  1.661049
2230  1.586502
2231  1.465904
2232  1.389559

[2233 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2327  1.077906
2328  1.075260
2329  1.082291
2330  1.067488
2331  1.003058

[2332 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2252  1.059194
2253  0.958337
2254  0.968626
2255  0.927002
2256  0.833192

[2257 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2326  1.143534
2327  1.158309
2328  1.134361
2329  1.095116
2330  1.251127

[2331 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2290  1.120090
2291  1.128234
2292  1.145660
2293  1.101005
2294  0.906640

[2295 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2107  2.020455
2108  1.996481
2109  1.977330
2110  1.933967
2111  1.812084

[2112 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2345  1.099414
2346  1.153523
2347  1.128076
2348  1.087324
2349  1.052061

[2350 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2221  0.753807
2222  0.821073
2223  0.688878
2224  0.781461
2225  0.644722

[2226 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2238  1.093654
2239  1.046794
2240  1.005979
2241  0.777874
2242  0.744342

[2243 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2357  0.505687
2358  0.562362
2359  0.611848
2360  0.604817
2361  0.641396

[2362 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2199  1.154992
2200  1.140098
2201  1.194652
2202  1.135368
2203  1.057567

[2204 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2314  0.819480
2315  0.799347
2316  0.806934
2317  0.856162
2318  0.776512

[2319 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2225  1.314673
2226  1.288514
2227  1.249438
2228  1.190016
2229  1.101002

[2230 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1992  0.864763
1993  0.892057
1994  0.941798
1995  0.855091
1996  0.811759

[1997 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2235  1.179239
2236  1.149926
2237  1.149848
2238  1.124213
2239  1.019910

[2240 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2224  1.248458
2225  1.182418
2226  1.184191
2227  1.054796
2228  0.971620

[2229 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1968  1.724359
1969  1.719067
1970  1.765981
1971  1.622894
1972  1.526105

[1973 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2212  0.971370
2213  0.964991
2214  0.964936
2215  0.923813
2216  0.868202

[2217 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2269  2.040233
2270  2.020925
2271  2.075621
2272  2.199427
2273  2.080344

[2274 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2277  0.932926
2278  0.909176
2279  0.926502
2280  0.898555
2281  0.855864

[2282 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2311  1.117835
2312  1.055236
2313  1.031651
2314  0.953054
2315  0.746828

[2316 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2323  1.425761
2324  1.411553
2325  1.460384
2326  1.415702
2327  1.380233

[2328 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2126  1.283737
2127  1.194122
2128  1.184344
2129  1.129058
2130  1.086661

[2131 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2234  1.176349
2235  1.400962
2236  1.465153
2237  1.197097
2238  1.336005

[2239 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2064  1.183585
2065  1.182849
2066  1.208594
2067  1.027905
2068  0.877917

[2069 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1908  1.287553
1909  1.376841
1910  1.350803
1911  1.128720
1912  1.064145

[1913 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2227  1.585476
2228  1.547710
2229  1.599898
2230  1.392644
2231  1.360488

[2232 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2174  1.018893
2175  0.989230
2176  0.985542
2177  0.920359
2178  0.841102

[2179 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2143  0.811411
2144  0.803163
2145  0.988814
2146  0.873966
2147  0.904810

[2148 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2293  0.850672
2294  0.838319
2295  0.781330
2296  0.724264
2297  0.634853

[2298 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2007  1.072518
2008  1.037396
2009  1.052269
2010  0.992702
2011  1.168261

[2012 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1895  1.505518
1896  1.548039
1897  1.683111
1898  1.659903
1899  1.531492

[1900 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2117  0.937204
2118  0.905609
2119  0.859462
2120  0.874812
2121  0.822152

[2122 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2213 -0.531985
2214 -0.532903
2215 -0.432648
2216 -0.517651
2217 -0.712572

[2218 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2115  1.255498
2116  1.251352
2117  1.247560
2118  1.217939
2119  1.168945

[2120 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2178  0.703579
2179  0.622131
2180  0.628015
2181  0.548263
2182  0.476033

[2183 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2272  0.957677
2273  0.919657
2274  0.923546
2275  0.821819
2276  0.787094

[2277 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2266  1.620707
2267  1.570129
2268  1.579852
2269  1.554958
2270  1.395823

[2271 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2019  1.046142
2020  1.136074
2021  1.122864
2022  1.039763
2023  1.087112

[2024 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2050  1.270613
2051  1.270704
2052  1.269588
2053  1.240220
2054  1.167790

[2055 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2157  0.154305
2158  0.143959
2159  0.153995
2160  0.133953
2161  0.104821

[2162 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2142  0.921402
2143  0.857901
2144  0.867087
2145  0.815977
2146  0.746512

[2147 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2221  2.443650
2222  2.441198
2223  2.549925
2224  2.732936
2225  2.636333

[2226 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2080  1.286757
2081  1.253494
2082  1.203612
2083  1.251649
2084  1.236568

[2085 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2134  1.359918
2135  1.327332
2136  1.334502
2137  1.314219
2138  1.316366

[2139 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1885  0.486175
1886  0.464540
1887  0.597653
1888  0.595529
1889  0.720202

[1890 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1987  1.139456
1988  1.126765
1989  1.144125
1990  1.271219
1991  1.229386

[1992 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2085  0.388325
2086  0.418018
2087  0.456410
2088  0.348233
2089  0.205282

[2090 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2059  1.407484
2060  1.390827
2061  1.556623
2062  1.409714
2063  1.470744

[2064 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2202  1.169457
2203  1.063361
2204  1.121206
2205  1.026019
2206  0.963652

[2207 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2056  1.125558
2057  1.155943
2058  1.224001
2059  1.148076
2060  0.926261

[2061 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2022  1.480464
2023  1.505130
2024  1.486874
2025  1.502889
2026  1.408350

[2027 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2211  1.331118
2212  1.349224
2213  1.279793
2214  1.185518
2215  1.099141

[2216 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2273  1.134419
2274  1.109447
2275  1.123045
2276  1.171202
2277  1.052525

[2278 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2277  0.962264
2278  0.942160
2279  0.930418
2280  0.866687
2281  0.817997

[2282 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1961  1.602035
1962  1.556373
1963  1.553080
1964  1.420972
1965  1.208388

[1966 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2234  0.477047
2235  0.421529
2236  0.394739
2237  0.519306
2238  0.609873

[2239 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2246  0.346317
2247  0.413793
2248  0.411549
2249  0.420256
2250  0.465185

[2251 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2135  1.165332
2136  1.141375
2137  1.179153
2138  1.215362
2139  1.115019

[2140 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2191  0.384987
2192  0.330467
2193  0.343898
2194  0.232879
2195  0.064382

[2196 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2169  0.605239
2170  0.606643
2171  0.653778
2172  0.666397
2173  0.639264

[2174 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2114  1.374187
2115  1.352235
2116  1.381989
2117  1.310962
2118  1.218553

[2119 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2105  0.341907
2106  0.323577
2107  0.360103
2108  0.449078
2109  0.559162

[2110 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2145  0.171436
2146  0.352040
2147  0.376341
2148  0.214029
2149  0.178432

[2150 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2120  1.550707
2121  1.507811
2122  1.641198
2123  1.555369
2124  1.499812

[2125 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2168  1.910453
2169  1.896669
2170  1.766189
2171  1.666251
2172  1.597489

[2173 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1931  1.121481
1932  1.321187
1933  1.364805
1934  1.442290
1935  1.351904

[1936 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2217  0.864833
2218  0.808466
2219  0.749252
2220  0.759169
2221  0.668785

[2222 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2041  1.316400
2042  1.409030
2043  1.446540
2044  1.384559
2045  1.301301

[2046 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2153  1.325961
2154  1.295614
2155  1.345644
2156  1.294095
2157  1.173382

[2158 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1994  0.272244
1995  0.317451
1996  0.336976
1997  0.410281
1998  0.354362

[1999 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2029  1.049283
2030  1.031482
2031  1.079916
2032  1.151057
2033  1.108207

[2034 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2156  1.344853
2157  1.369664
2158  1.372798
2159  1.444600
2160  1.232921

[2161 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1942  0.852261
1943  1.029537
1944  1.072861
1945  0.995305
1946  1.277412

[1947 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2239  0.734499
2240  0.720229
2241  0.728383
2242  0.739937
2243  0.697412

[2244 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2054  0.197195
2055  0.197697
2056  0.206675
2057  0.345982
2058  0.271969

[2059 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2112  0.829891
2113  0.830403
2114  0.801342
2115  0.830781
2116  0.776162

[2117 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2088  1.445893
2089  1.434155
2090  1.450374
2091  1.399049
2092  1.308359

[2093 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1935  0.797271
1936  0.802786
1937  0.716877
1938  0.524127
1939  0.517169

[1940 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1972  0.561930
1973  0.511157
1974  0.436899
1975  0.449045
1976  0.454084

[1977 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2084  0.245089
2085  0.337682
2086  0.340069
2087  0.347165
2088  0.346309

[2089 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2194  1.320351
2195  1.230493
2196  1.217874
2197  1.081372
2198  0.956350

[2199 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1923  1.805133
1924  1.803848
1925  1.836337
1926  1.775873
1927  1.713863

[1928 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2225  1.611103
2226  1.581578
2227  1.642441
2228  1.690652
2229  1.464399

[2230 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2153  1.102307
2154  1.063571
2155  1.184786
2156  1.016514
2157  0.925995

[2158 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2234  1.234507
2235  1.219097
2236  1.174515
2237  1.091187
2238  0.892139

[2239 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2199  1.150853
2200  1.177274
2201  1.183718
2202  1.109036
2203  1.025500

[2204 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2227  0.828973
2228  0.973901
2229  0.908168
2230  0.733959
2231  0.628540

[2232 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2178  2.867329
2179  2.826478
2180  2.880462
2181  2.849015
2182  2.700921

[2183 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2034  1.061528
2035  1.047074
2036  0.992149
2037  0.859462
2038  0.733863

[2039 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1900  1.099052
1901  1.068740
1902  0.873495
1903  0.924892
1904  0.776630

[1905 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2181  0.986226
2182  0.904365
2183  0.959153
2184  0.967696
2185  0.881610

[2186 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2184  0.445107
2185  0.445308
2186  0.368420
2187  0.394781
2188  0.273612

[2189 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2037  1.720791
2038  1.728432
2039  1.721262
2040  1.789946
2041  1.686000

[2042 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1983  1.515819
1984  1.491080
1985  1.429451
1986  1.279974
1987  1.152187

[1988 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2169  0.726364
2170  0.697930
2171  0.708989
2172  0.698249
2173  0.655051

[2174 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2182  1.109255
2183  1.020591
2184  0.985097
2185  1.045310
2186  1.066120

[2187 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1748  1.289799
1749  1.317901
1750  1.351566
1751  1.359032
1752  1.256927

[1753 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2183  1.503767
2184  1.483308
2185  1.475202
2186  1.372099
2187  1.311327

[2188 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2196  1.110193
2197  1.108872
2198  1.092788
2199  1.084717
2200  1.010233

[2201 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1986  1.570956
1987  1.555907
1988  1.552228
1989  1.411976
1990  1.281989

[1991 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1990  0.305075
1991  0.282928
1992  0.473415
1993  0.475456
1994  0.351511

[1995 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2127  1.139187
2128  1.119255
2129  1.111948
2130  1.037132
2131  0.951534

[2132 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1888  1.170903
1889  1.147576
1890  1.169756
1891  1.113056
1892  1.058419

[1893 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1958  2.490360
1959  2.501040
1960  2.548943
1961  2.484767
1962  2.366033

[1963 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2118  0.683054
2119  0.715201
2120  0.764599
2121  0.982014
2122  1.268298

[2123 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2032  0.572740
2033  0.527495
2034  0.499411
2035  0.420893
2036  0.285204

[2037 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2085  1.562990
2086  1.600338
2087  1.597638
2088  1.509236
2089  1.355664

[2090 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2106  1.535450
2107  1.503075
2108  1.403093
2109  1.335604
2110  1.239116

[2111 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2130  0.904132
2131  0.885883
2132  0.894543
2133  0.844049
2134  0.769323

[2135 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2040  1.506056
2041  1.517105
2042  1.551415
2043  1.615287
2044  1.526828

[2045 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2067  1.659220
2068  1.650974
2069  1.675645
2070  1.696503
2071  1.602636

[2072 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2179  1.022918
2180  0.981536
2181  1.045111
2182  1.017545
2183  0.934732

[2184 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2103  1.433467
2104  1.442196
2105  1.435960
2106  1.405634
2107  1.319321

[2108 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2085 -0.023882
2086  0.106490
2087  0.154914
2088  0.232958
2089  0.459406

[2090 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2100  2.029575
2101  2.032115
2102  1.973594
2103  2.115567
2104  2.001491

[2105 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2048  1.819111
2049  1.797662
2050  1.856504
2051  1.766840
2052  1.653711

[2053 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2146  2.204990
2147  2.177711
2148  2.204399
2149  2.039093
2150  1.857000

[2151 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2059  0.974273
2060  0.952800
2061  0.950828
2062  0.899638
2063  0.864990

[2064 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1946  0.465146
1947  0.541525
1948  0.505765
1949  0.419967
1950  0.304353

[1951 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2102  1.270760
2103  1.285661
2104  1.291823
2105  1.227586
2106  1.135923

[2107 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2028  0.873159
2029  0.885984
2030  0.930384
2031  0.854442
2032  0.818226

[2033 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2052  1.395865
2053  1.381840
2054  1.386188
2055  1.316212
2056  1.169278

[2057 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1890  1.649641
1891  1.588088
1892  1.568453
1893  1.503693
1894  1.359221

[1895 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2003  0.984837
2004  0.997380
2005  0.964175
2006  1.016874
2007  0.859157

[2008 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2078  1.286890
2079  1.408237
2080  1.366502
2081  1.276337
2082  1.121728

[2083 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2160  0.952226
2161  0.908391
2162  0.914185
2163  0.898401
2164  0.786122

[2165 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2167  0.082480
2168  0.236089
2169  0.059435
2170  0.034541
2171 -0.128657

[2172 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1909  0.603321
1910  0.611196
1911  0.657033
1912  0.602323
1913  0.559814

[1914 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2017  1.520151
2018  1.548624
2019  1.561269
2020  1.567296
2021  1.407971

[2022 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2040  1.721685
2041  1.687319
2042  1.660426
2043  1.466591
2044  1.338176

[2045 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2039  1.816606
2040  1.800154
2041  1.822391
2042  1.757097
2043  1.648891

[2044 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2043  1.697591
2044  1.663692
2045  1.730863
2046  1.544181
2047  1.590165

[2048 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2005  1.670186
2006  1.580663
2007  1.571097
2008  1.499727
2009  1.381536

[2010 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2085  1.849524
2086  1.915847
2087  1.881026
2088  1.963749
2089  1.580846

[2090 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2053  0.597313
2054  0.602229
2055  0.609823
2056  0.617813
2057  0.565254

[2058 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2119  0.566157
2120  0.568899
2121  0.549867
2122  0.510818
2123  0.543299

[2124 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1991  1.067415
1992  1.441908
1993  1.584445
1994  1.395952
1995  1.269473

[1996 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2098  1.065731
2099  1.051988
2100  1.045919
2101  0.930293
2102  0.819802

[2103 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2141  0.967799
2142  0.939590
2143  0.998665
2144  0.963959
2145  0.931538

[2146 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2116  1.254890
2117  1.235302
2118  1.274019
2119  1.229457
2120  1.187643

[2121 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2056  2.028171
2057  1.971083
2058  1.773244
2059  1.690802
2060  1.397258

[2061 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2069  1.069249
2070  1.120206
2071  1.089557
2072  0.935642
2073  0.676190

[2074 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2031  0.684063
2032  0.660925
2033  0.672677
2034  0.605798
2035  0.579940

[2036 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1996  1.829141
1997  1.812067
1998  1.835730
1999  1.730184
2000  1.552540

[2001 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2118  1.289660
2119  1.194526
2120  1.216939
2121  1.206872
2122  1.095006

[2123 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1998  1.361728
1999  1.345306
2000  1.348668
2001  1.622662
2002  1.568886

[2003 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1735  1.006981
1736  0.969402
1737  0.988208
1738  0.997803
1739  1.013960

[1740 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1957  0.692406
1958  0.686361
1959  0.673557
1960  0.699035
1961  0.614947

[1962 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1551  0.884069
1552  0.947501
1553  0.979429
1554  0.971581
1555  0.873301

[1556 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1852  1.138580
1853  1.111035
1854  1.151149
1855  1.123054
1856  1.052082

[1857 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2105  1.348600
2106  1.319879
2107  1.336097
2108  1.143537
2109  1.027202

[2110 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1906  1.348663
1907  1.351071
1908  1.358745
1909  1.302584
1910  1.093589

[1911 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1940  1.289064
1941  1.352698
1942  1.240942
1943  1.297745
1944  1.056904

[1945 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1962  0.381534
1963  0.553775
1964  0.579807
1965  0.643794
1966  0.507545

[1967 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2073  1.298912
2074  1.307107
2075  1.209611
2076  1.123161
2077  1.157357

[2078 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2087  0.521363
2088  0.466054
2089  0.470578
2090  0.489181
2091  0.409374

[2092 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1952  0.881783
1953  0.892141
1954  0.877778
1955  0.716754
1956  0.691208

[1957 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2027  1.074471
2028  1.010408
2029  0.985271
2030  1.054359
2031  0.780265

[2032 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1494  1.200146
1495  1.161388
1496  1.224086
1497  1.201198
1498  1.121230

[1499 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1806  1.361407
1807  1.559179
1808  1.583057
1809  1.509157
1810  1.411184

[1811 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1708  1.181595
1709  1.153350
1710  1.204720
1711  1.386837
1712  1.280227

[1713 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2004  0.657740
2005  0.658781
2006  0.646941
2007  0.684077
2008  0.515458

[2009 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1846  0.811212
1847  0.777163
1848  0.782912
1849  0.735255
1850  0.676880

[1851 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2012  1.058977
2013  0.989632
2014  0.977964
2015  0.864541
2016  0.802302

[2017 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1918  1.091062
1919  1.061035
1920  1.042737
1921  1.300067
1922  1.256852

[1923 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1916  1.771558
1917  1.763721
1918  1.731687
1919  1.702727
1920  1.648937

[1921 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2045  0.803490
2046  0.798203
2047  0.815436
2048  0.775855
2049  0.715212

[2050 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1901  1.601745
1902  1.563923
1903  1.578244
1904  1.479341
1905  1.417779

[1906 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1854  1.148262
1855  1.105875
1856  1.157221
1857  1.144639
1858  1.064384

[1859 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1949 -0.057589
1950  0.025505
1951 -0.149124
1952 -0.198922
1953 -0.347768

[1954 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1731  1.334902
1732  1.270337
1733  1.267322
1734  1.222193
1735  1.135579

[1736 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1808  0.819383
1809  0.805026
1810  0.781083
1811  0.698734
1812  0.613890

[1813 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1631  1.488158
1632  1.436732
1633  1.487934
1634  1.383218
1635  1.327744

[1636 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1925  2.151618
1926  2.037017
1927  2.129665
1928  2.179757
1929  2.165451

[1930 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1849  1.252131
1850  1.270178
1851  1.290289
1852  1.143333
1853  1.071960

[1854 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1866  0.763861
1867  0.913694
1868  1.027016
1869  1.145150
1870  1.110763

[1871 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1834  1.669847
1835  1.648276
1836  1.632020
1837  1.526339
1838  1.329489

[1839 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1881  1.489905
1882  1.483813
1883  1.526607
1884  1.464237
1885  1.458161

[1886 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1796  0.758641
1797  0.785101
1798  0.801365
1799  0.650355
1800  0.584572

[1801 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1655  0.935456
1656  0.807503
1657  0.996151
1658  0.818720
1659  0.541815

[1660 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1805  0.434733
1806  0.418941
1807  0.424858
1808  0.459216
1809  0.405454

[1810 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1862  1.147020
1863  1.147380
1864  1.173956
1865  1.270485
1866  1.184365

[1867 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1978  1.721934
1979  1.685414
1980  1.717796
1981  1.673706
1982  1.595218

[1983 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1994  1.757144
1995  1.736312
1996  1.737354
1997  1.645609
1998  1.486094

[1999 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1982  1.123557
1983  1.110413
1984  1.110421
1985  1.054142
1986  0.998958

[1987 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2000  0.995551
2001  1.009705
2002  1.035340
2003  1.092046
2004  1.033802

[2005 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1904  1.262551
1905  1.250438
1906  1.248511
1907  1.330917
1908  1.316255

[1909 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1990  0.846646
1991  0.881101
1992  0.877039
1993  0.799601
1994  0.693335

[1995 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1828  1.794923
1829  1.755442
1830  1.743372
1831  1.710900
1832  1.520147

[1833 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1817  0.006742
1818  0.122539
1819  0.246182
1820  0.220291
1821  0.097532

[1822 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1827  1.272981
1828  1.165589
1829  1.143099
1830  1.237181
1831  1.136011

[1832 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1825  0.804276
1826  0.798602
1827  0.824925
1828  0.772879
1829  0.683625

[1830 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1784  1.476125
1785  1.386853
1786  1.387072
1787  1.277720
1788  1.169576

[1789 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1719  0.740957
1720  0.725646
1721  0.736400
1722  0.895725
1723  0.835230

[1724 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1971  0.612492
1972  0.782691
1973  0.591955
1974  0.830556
1975  0.633787

[1976 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1594  0.869578
1595  0.863083
1596  0.890268
1597  0.877905
1598  0.699533

[1599 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1873  2.044149
1874  2.008283
1875  1.970718
1876  1.839099
1877  1.630292

[1878 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1679  0.757486
1680  0.731673
1681  0.725744
1682  0.625921
1683  0.945411

[1684 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1850  0.372315
1851  0.580260
1852  0.528138
1853  0.540379
1854  0.552445

[1855 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1728  2.031086
1729  1.995125
1730  1.977868
1731  1.907185
1732  1.719870

[1733 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1866  1.196003
1867  1.150224
1868  1.183788
1869  1.087283
1870  1.067901

[1871 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1968  0.733490
1969  0.706001
1970  0.705426
1971  0.688548
1972  0.629510

[1973 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1698  1.654327
1699  1.618320
1700  1.608054
1701  1.540020
1702  1.437109

[1703 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1614  1.509579
1615  1.443875
1616  1.446818
1617  1.344168
1618  1.220721

[1619 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1615  1.764802
1616  1.736883
1617  1.758718
1618  1.682683
1619  1.423253

[1620 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1846 -0.109279
1847 -0.176337
1848 -0.120120
1849 -0.196766
1850 -0.140129

[1851 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1681  1.537713
1682  1.594600
1683  1.581532
1684  1.543104
1685  1.234578

[1686 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1949  1.688936
1950  1.679473
1951  1.693261
1952  1.588418
1953  1.465544

[1954 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1912  1.728408
1913  1.673734
1914  1.679119
1915  1.632504
1916  1.431866

[1917 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1922  0.613020
1923  0.593986
1924  0.588726
1925  0.594497
1926  0.540387

[1927 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1897  1.461983
1898  1.410570
1899  1.423665
1900  1.390653
1901  1.282091

[1902 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1786  2.406351
1787  2.372220
1788  2.338627
1789  2.183924
1790  1.916419

[1791 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1717  1.009288
1718  0.952104
1719  0.973579
1720  0.911056
1721  0.884564

[1722 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1943  1.136507
1944  1.120248
1945  1.142239
1946  1.124594
1947  1.031145

[1948 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1726  0.703807
1727  0.727020
1728  0.612514
1729  0.939692
1730  1.227753

[1731 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1785  0.780142
1786  0.777424
1787  0.788785
1788  0.810518
1789  0.753350

[1790 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1808  0.850752
1809  0.764982
1810  0.765952
1811  0.561250
1812  0.577380

[1813 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1869  0.945660
1870  0.918701
1871  0.939405
1872  0.888152
1873  0.841599

[1874 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1819  0.623796
1820  0.613549
1821  0.630944
1822  0.527562
1823  0.416787

[1824 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1783  1.493082
1784  1.475536
1785  1.433661
1786  1.366349
1787  1.227394

[1788 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1760  0.980481
1761  0.997140
1762  0.988964
1763  1.035214
1764  0.988072

[1765 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1741  2.068168
1742  2.058421
1743  1.921575
1744  1.910854
1745  1.727404

[1746 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1844  1.806055
1845  1.749135
1846  1.770200
1847  1.667419
1848  1.515979

[1849 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1637  1.673960
1638  1.629940
1639  1.596141
1640  1.528831
1641  1.500604

[1642 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1797  1.250805
1798  1.329893
1799  1.350204
1800  1.442512
1801  1.260020

[1802 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1788  0.815258
1789  0.786440
1790  0.753174
1791  0.606982
1792  0.527081

[1793 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1859  2.712194
1860  2.723494
1861  2.706538
1862  2.476343
1863  2.134404

[1864 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1769  1.210378
1770  1.244324
1771  1.164284
1772  0.960290
1773  0.735343

[1774 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1730  1.683235
1731  1.710241
1732  1.708515
1733  1.625651
1734  1.363217

[1735 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1708  1.064432
1709  1.051393
1710  1.078843
1711  1.045180
1712  0.935920

[1713 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1713  1.177175
1714  1.164518
1715  1.176090
1716  1.124076
1717  1.044930

[1718 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1746  1.349267
1747  1.319062
1748  1.283340
1749  1.198182
1750  1.078741

[1751 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1773  1.499830
1774  1.530618
1775  1.592190
1776  1.370217
1777  1.287108

[1778 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1546  1.294016
1547  1.224281
1548  1.268694
1549  1.106519
1550  1.141070

[1551 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1883  1.080917
1884  1.069002
1885  1.037432
1886  0.985999
1887  0.896482

[1888 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1756  0.804168
1757  0.792034
1758  0.798194
1759  0.749724
1760  0.718241

[1761 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1636  1.348225
1637  1.394773
1638  1.533327
1639  1.394448
1640  1.670770

[1641 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1562  0.622196
1563  0.655698
1564  0.652331
1565  0.711712
1566  0.546546

[1567 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1439  0.613587
1440  0.675429
1441  0.475337
1442  0.619754
1443  0.277099

[1444 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1394  1.282449
1395  1.273864
1396  1.204527
1397  1.081856
1398  1.019204

[1399 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1475  1.483135
1476  1.456059
1477  1.412623
1478  1.426463
1479  1.346354

[1480 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1142  1.108097
1143  1.144683
1144  1.193884
1145  1.222938
1146  1.350458

[1147 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1446  1.257539
1447  1.211221
1448  1.138108
1449  1.161239
1450  1.040143

[1451 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1159  2.397030
1160  2.391075
1161  2.424293
1162  2.353943
1163  2.034813

[1164 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1499  1.359460
1500  1.322047
1501  1.367265
1502  1.266727
1503  1.204675

[1504 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1373  1.436758
1374  1.480097
1375  1.480235
1376  1.318088
1377  1.274208

[1378 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1372  0.781655
1373  0.767142
1374  0.853372
1375  0.837631
1376  1.025504

[1377 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1440  1.774245
1441  1.720658
1442  1.715015
1443  1.761538
1444  1.577527

[1445 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1463  1.377551
1464  1.407959
1465  1.378761
1466  1.310155
1467  1.168019

[1468 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1468  1.073195
1469  1.039570
1470  1.080326
1471  1.016746
1472  1.051968

[1473 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1562  1.021843
1563  0.996675
1564  0.984300
1565  0.990633
1566  0.797431

[1567 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1527  2.220046
1528  2.256008
1529  2.126130
1530  2.011315
1531  1.816444

[1532 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1152  1.057722
1153  0.979357
1154  0.905407
1155  0.810111
1156  0.655196

[1157 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1514  1.287145
1515  1.288114
1516  1.259964
1517  1.486804
1518  1.374892

[1519 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1438  1.367180
1439  1.290505
1440  1.226557
1441  1.097300
1442  0.913739

[1443 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1513  1.760039
1514  1.734508
1515  1.714739
1516  1.842374
1517  1.629590

[1518 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1555  1.427797
1556  1.476700
1557  1.405154
1558  1.299502
1559  1.294893

[1560 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1443  1.894667
1444  1.874642
1445  1.916287
1446  1.725738
1447  1.586836

[1448 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1559  1.264884
1560  1.229695
1561  1.249660
1562  1.391716
1563  1.287864

[1564 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1403  0.774457
1404  0.801821
1405  0.746558
1406  0.685870
1407  0.653308

[1408 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1546  0.881566
1547  0.818648
1548  0.843799
1549  0.813593
1550  0.853418

[1551 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1368  1.712234
1369  1.668445
1370  1.696484
1371  1.560399
1372  1.520661

[1373 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1320  1.236789
1321  1.226593
1322  1.214932
1323  1.161251
1324  1.049399

[1325 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1444  1.007270
1445  0.989540
1446  1.008739
1447  0.931098
1448  0.869019

[1449 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1461  2.211010
1462  2.203238
1463  2.183853
1464  2.110629
1465  1.917047

[1466 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1366  0.804453
1367  0.781765
1368  0.820504
1369  0.759200
1370  0.746059

[1371 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1390  0.906950
1391  0.859070
1392  0.835570
1393  0.783200
1394  0.757115

[1395 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1429  1.907421
1430  1.879392
1431  1.877145
1432  1.785025
1433  1.634232

[1434 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1366  2.133815
1367  2.076653
1368  2.096400
1369  1.994786
1370  1.929549

[1371 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1332  0.255499
1333  0.259141
1334  0.254832
1335  0.232497
1336  0.136787

[1337 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1151  1.225650
1152  1.195696
1153  1.169870
1154  1.006521
1155  1.234785

[1156 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1399  0.550229
1400  0.472683
1401  0.394835
1402  0.364812
1403  0.335359

[1404 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1289  1.626477
1290  1.561641
1291  1.506478
1292  1.439707
1293  1.227727

[1294 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1408  1.283553
1409  1.255367
1410  1.195955
1411  1.127462
1412  0.951684

[1413 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1351  1.235960
1352  1.343501
1353  1.470067
1354  1.416302
1355  1.236797

[1356 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1369  2.043196
1370  1.984749
1371  1.939711
1372  1.874525
1373  1.747761

[1374 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1297  2.025585
1298  1.986343
1299  2.051917
1300  2.001121
1301  1.789812

[1302 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1377  1.803821
1378  1.740341
1379  1.780295
1380  1.907766
1381  1.753932

[1382 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1391  0.992074
1392  0.981239
1393  0.904150
1394  0.831114
1395  0.823663

[1396 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1375  1.412435
1376  1.402625
1377  1.270319
1378  1.468466
1379  1.426657

[1380 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1304  0.722877
1305  0.700559
1306  0.667358
1307  0.588933
1308  0.550960

[1309 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1377  1.159063
1378  1.185044
1379  1.208798
1380  1.150618
1381  1.176289

[1382 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1190 -0.313440
1191 -0.342017
1192 -0.383125
1193 -0.226399
1194 -0.213313

[1195 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1300  0.684148
1301  0.652632
1302  0.636944
1303  0.665152
1304  0.645544

[1305 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1377  0.663997
1378  0.726043
1379  0.734210
1380  0.670418
1381  0.549483

[1382 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1234  1.443681
1235  1.324766
1236  1.303946
1237  1.350471
1238  1.254554

[1239 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1343  1.619018
1344  1.573513
1345  1.581482
1346  1.675404
1347  1.425480

[1348 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1263  1.395503
1264  1.386638
1265  1.404744
1266  1.362015
1267  1.290249

[1268 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1118  0.285413
1119  0.251661
1120  0.240126
1121  0.117994
1122  0.039603

[1123 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1052  1.403518
1053  1.448981
1054  1.347973
1055  1.286316
1056  1.302576

[1057 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1238  0.693839
1239  0.733952
1240  0.640074
1241  0.652807
1242  0.443333

[1243 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1060  1.420318
1061  1.479135
1062  1.464219
1063  1.431240
1064  1.170526

[1065 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1038  1.065881
1039  1.091793
1040  1.138577
1041  0.933321
1042  0.907372

[1043 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1309  1.575080
1310  1.550704
1311  1.516259
1312  1.444732
1313  1.514395

[1314 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1310  1.448934
1311  1.459446
1312  1.423728
1313  1.306837
1314  1.203196

[1315 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1318  0.514918
1319  0.493699
1320  0.504371
1321  0.632644
1322  0.541112

[1323 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1249  1.211240
1250  1.197329
1251  1.197684
1252  1.123811
1253  1.027951

[1254 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1218  0.646088
1219  0.648290
1220  0.705166
1221  0.887698
1222  0.946955

[1223 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1150  1.683814
1151  1.659297
1152  1.683564
1153  1.755057
1154  1.613424

[1155 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1260  0.494835
1261  0.485962
1262  0.501226
1263  0.458826
1264  0.434836

[1265 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1290  1.095973
1291  1.057184
1292  1.079021
1293  0.992578
1294  0.943839

[1295 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1043  1.184005
1044  1.148545
1045  1.185009
1046  1.144721
1047  1.025846

[1048 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1206  1.110666
1207  1.093079
1208  1.094845
1209  1.089027
1210  1.039873

[1211 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1167  0.653340
1168  0.595633
1169  0.586057
1170  0.558231
1171  0.525212

[1172 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1216  1.127913
1217  1.123853
1218  1.027275
1219  1.056930
1220  1.180037

[1221 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1097  1.278181
1098  1.368902
1099  1.360623
1100  1.404717
1101  1.635840

[1102 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1113  0.541513
1114  0.551511
1115  0.583175
1116  0.444137
1117  0.299188

[1118 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1185  2.042019
1186  2.082168
1187  2.136481
1188  1.948178
1189  1.757168

[1190 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1213  0.744584
1214  0.749521
1215  0.698512
1216  0.685686
1217  0.608835

[1218 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1045  2.082766
1046  1.963937
1047  2.080566
1048  2.135790
1049  2.040718

[1050 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1197  1.086520
1198  1.049798
1199  1.030600
1200  0.825361
1201  0.733252

[1202 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1260  2.306448
1261  2.264589
1262  2.227853
1263  2.328125
1264  2.325666

[1265 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1136  1.077475
1137  1.106880
1138  1.069254
1139  1.020350
1140  0.914722

[1141 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1268  1.080226
1269  1.088851
1270  1.065287
1271  0.991357
1272  0.918152

[1273 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1210  0.433753
1211  0.389730
1212  0.416471
1213  0.400759
1214  0.379291

[1215 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1143  1.057795
1144  1.070815
1145  1.056106
1146  0.982404
1147  0.905547

[1148 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1214  1.881449
1215  1.885059
1216  1.851748
1217  1.642957
1218  1.572828

[1219 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1257  0.111985
1258  0.212521
1259  0.179856
1260  0.236534
1261  0.120729

[1262 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1125  1.547317
1126  1.477929
1127  1.496856
1128  1.455116
1129  1.232900

[1130 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1014  0.208587
1015  0.170862
1016  0.152971
1017  0.194055
1018  0.400053

[1019 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1259  0.841189
1260  0.825906
1261  0.800145
1262  0.637031
1263  0.758517

[1264 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1255  0.488405
1256  0.497722
1257  0.470679
1258  0.246425
1259  0.273539

[1260 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1153  1.144647
1154  1.100472
1155  1.103144
1156  1.068063
1157  1.027606

[1158 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1259  1.360524
1260  1.302338
1261  1.338740
1262  1.302090
1263  1.246261

[1264 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1260  0.927584
1261  0.889418
1262  0.895979
1263  0.915112
1264  0.858969

[1265 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1162  1.214334
1163  1.168614
1164  1.190477
1165  1.141688
1166  1.028111

[1167 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1253  1.372299
1254  1.448546
1255  1.510741
1256  1.397299
1257  1.264658

[1258 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1177  1.173166
1178  1.149333
1179  1.116929
1180  1.092711
1181  0.918339

[1182 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1095  1.644398
1096  1.590699
1097  1.592413
1098  1.558484
1099  1.386451

[1100 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1176  1.824493
1177  1.895611
1178  1.803647
1179  1.663589
1180  1.410774

[1181 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1245  0.884834
1246  0.948873
1247  0.938558
1248  0.946534
1249  0.698830

[1250 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1235 -0.533774
1236 -0.438358
1237 -0.436031
1238 -0.475324
1239 -0.413742

[1240 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
513  1.613132
514  1.610114
515  1.572043
516  1.569736
517  1.305875

[518 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1112  1.712481
1113  1.692485
1114  1.697234
1115  1.757780
1116  1.558331

[1117 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1095  1.887581
1096  1.863105
1097  1.902533
1098  1.776204
1099  1.666652

[1100 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1185  1.302336
1186  1.401137
1187  1.412961
1188  1.345629
1189  1.205963

[1190 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1235  1.780444
1236  1.750097
1237  1.783391
1238  1.788499
1239  1.649410

[1240 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1026  1.231966
1027  1.227030
1028  1.233950
1029  1.098588
1030  0.847784

[1031 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1235  1.569415
1236  1.543974
1237  1.473095
1238  1.417759
1239  1.254232

[1240 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1033  0.593888
1034  0.572278
1035  0.603865
1036  0.799037
1037  0.800819

[1038 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
951  1.495523
952  1.497968
953  1.537563
954  1.538956
955  1.414984

[956 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1235  0.432132
1236  0.474205
1237  0.426935
1238  0.273551
1239  0.164352

[1240 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1045  1.929058
1046  2.016088
1047  1.783898
1048  2.022449
1049  2.247210

[1050 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1140  1.693267
1141  1.659797
1142  1.657723
1143  1.664659
1144  1.428119

[1145 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
879  0.807738
880  0.718026
881  0.745101
882  0.619922
883  0.960362

[884 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1035  1.286078
1036  1.241300
1037  1.285771
1038  1.240902
1039  1.227060

[1040 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1204  1.874615
1205  1.843102
1206  1.816718
1207  1.776210
1208  1.547308

[1209 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1122 -0.179861
1123 -0.210461
1124 -0.191526
1125 -0.126111
1126 -0.122331

[1127 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1225  0.992847
1226  0.961284
1227  0.954452
1228  0.992615
1229  1.135588

[1230 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1216  1.540304
1217  1.554659
1218  1.565582
1219  1.451872
1220  1.397773

[1221 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1032  0.544460
1033  0.502269
1034  0.450615
1035  0.355869
1036  0.287871

[1037 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1158  0.515116
1159  0.462484
1160  0.493573
1161  0.419420
1162  0.413603

[1163 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1023  1.655400
1024  1.632474
1025  1.685080
1026  1.666285
1027  1.636807

[1028 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1206  0.790831
1207  0.768750
1208  0.787963
1209  0.751318
1210  0.692900

[1211 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1221  1.976330
1222  1.942434
1223  1.958891
1224  1.849512
1225  1.722668

[1226 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1119  0.789320
1120  0.809806
1121  0.846420
1122  0.965246
1123  0.868254

[1124 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1132  0.338727
1133  0.281426
1134  0.352307
1135  0.343494
1136  0.262660

[1137 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1132  1.335020
1133  1.316033
1134  1.343514
1135  1.265913
1136  1.138056

[1137 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1145  0.995523
1146  0.993262
1147  0.980928
1148  1.008584
1149  0.927914

[1150 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1193  1.347833
1194  1.350800
1195  1.334045
1196  1.361831
1197  1.277250

[1198 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1205  0.026266
1206  0.165342
1207  0.070408
1208  0.142569
1209  0.028103

[1210 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1134  0.619466
1135  0.613728
1136  0.597763
1137  0.560166
1138  0.618231

[1139 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1037  1.646720
1038  1.624055
1039  1.654127
1040  1.491470
1041  1.531906

[1042 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1216 -0.675408
1217 -0.544933
1218 -0.547268
1219 -0.526666
1220 -0.469912

[1221 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1079  0.613159
1080  0.609309
1081  0.734406
1082  0.637327
1083  0.542967

[1084 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1203  1.309070
1204  1.318247
1205  1.312891
1206  1.318184
1207  1.387945

[1208 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1073  0.771239
1074  0.771670
1075  0.773454
1076  0.686393
1077  0.684634

[1078 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1208  1.011212
1209  0.887472
1210  0.869538
1211  1.152077
1212  0.962915

[1213 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
946  1.057889
947  1.039031
948  1.033181
949  1.009192
950  0.952269

[951 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1000  1.316999
1001  1.310056
1002  1.356253
1003  1.266265
1004  1.206310

[1005 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
901  1.005189
902  0.957630
903  0.776426
904  0.692967
905  0.612717

[906 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1095  1.446909
1096  1.389647
1097  1.425378
1098  1.401429
1099  1.322602

[1100 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1089  0.548451
1090  0.529586
1091  0.711128
1092  0.670650
1093  0.713568

[1094 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1027  0.888742
1028  0.882675
1029  1.056996
1030  0.995377
1031  0.845610

[1032 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1042  1.911991
1043  1.887954
1044  1.682380
1045  1.614846
1046  1.455944

[1047 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1096  0.875307
1097  0.867305
1098  0.816103
1099  0.824676
1100  0.837934

[1101 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1121  0.767790
1122  0.740504
1123  0.756799
1124  0.852903
1125  0.879579

[1126 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1067  1.523986
1068  1.422154
1069  1.481366
1070  1.355094
1071  1.168972

[1072 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1000  0.831709
1001  0.817195
1002  0.829685
1003  0.782726
1004  0.745046

[1005 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1065  0.912328
1066  0.916396
1067  0.790378
1068  0.621236
1069  0.523693

[1070 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1048  1.732158
1049  1.685897
1050  1.669426
1051  1.650492
1052  1.432897

[1053 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1041  0.512752
1042  0.493895
1043  0.453037
1044  0.495468
1045  0.443226

[1046 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
542  1.837049
543  1.798515
544  1.823026
545  1.759489
546  1.597385

[547 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1037  1.006734
1038  0.980192
1039  0.992936
1040  0.970597
1041  0.968736

[1042 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1024  1.149769
1025  1.074197
1026  1.043821
1027  1.002305
1028  0.973187

[1029 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1007  1.037516
1008  0.992931
1009  0.933312
1010  0.839575
1011  0.779106

[1012 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1014  1.297981
1015  1.251817
1016  1.293093
1017  1.281606
1018  1.241021

[1019 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1010  0.737846
1011  0.710372
1012  0.717048
1013  0.597643
1014  0.515628

[1015 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
736  1.215584
737  1.194617
738  1.176301
739  1.089417
740  1.023041

[741 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1008  0.880632
1009  0.906235
1010  0.725584
1011  0.815141
1012  0.758402

[1013 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
992  0.896364
993  0.818226
994  0.796429
995  0.672643
996  0.511414

[997 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
896  1.741529
897  1.701869
898  1.748285
899  1.675298
900  1.553378

[901 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
770  1.376299
771  1.340827
772  1.349856
773  1.277935
774  1.220307

[775 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
981  0.848886
982  0.711095
983  0.734890
984  0.797210
985  0.831424

[986 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
987  0.446576
988  0.455044
989  0.427115
990  0.484189
991  0.394698

[992 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
956  0.494584
957  0.440795
958  0.424344
959  0.487096
960  0.406959

[961 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
835  0.623500
836  0.578158
837  0.671487
838  0.775405
839  0.572141

[840 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
968  0.346527
969  0.340198
970  0.279991
971  0.175275
972  0.063298

[973 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
952  1.284970
953  1.256281
954  1.296003
955  1.359908
956  1.238462

[957 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
956  0.715085
957  0.728854
958  0.713282
959  0.758043
960  0.746243

[961 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
961  0.260195
962  0.206117
963  0.241352
964  0.294943
965  0.262918

[966 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
869  1.063320
870  1.068142
871  1.053641
872  0.976036
873  0.971325

[874 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
931  0.913598
932  0.872412
933  0.823308
934  0.606233
935  0.657964

[936 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
810  1.061629
811  1.243905
812  1.281929
813  1.464790
814  1.269260

[815 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
941  0.420136
942  0.387286
943  0.302901
944  0.373250
945  0.297895

[946 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
942  0.833979
943  0.848858
944  0.898483
945  0.758062
946  0.760022

[947 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
946  1.359909
947  1.393298
948  1.398895
949  1.509981
950  1.299191

[951 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
936 -0.418797
937 -0.436863
938 -0.378549
939 -0.403415
940 -0.481810

[941 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
936  0.455233
937  0.438194
938  0.373496
939  0.455963
940  0.380837

[941 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
934  1.102802
935  1.087392
936  1.099444
937  1.076317
938  1.161734

[939 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
934  1.363139
935  1.336158
936  1.432471
937  1.425192
938  1.234569

[939 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
916  0.313876
917  0.321463
918  0.321140
919  0.333316
920  0.302750

[921 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
865  0.646994
866  0.629078
867  0.638847
868  0.638938
869  0.589165

[870 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
913  0.221823
914  0.199518
915  0.203049
916  0.174566
917  0.159547

[918 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
848  1.797259
849  1.765944
850  1.744996
851  1.570115
852  1.316096

[853 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
928  1.739177
929  1.641397
930  1.602389
931  1.514510
932  1.279801

[933 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
925  0.794493
926  0.824186
927  0.753478
928  0.667083
929  0.531047

[930 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
926  0.711728
927  0.659689
928  0.673090
929  0.554881
930  0.462616

[931 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
916  1.524652
917  1.474892
918  1.492814
919  1.423345
920  1.301552

[921 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
913  1.141518
914  1.108934
915  1.137386
916  1.110166
917  1.037105

[918 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
837  1.618115
838  1.593498
839  1.626566
840  1.694552
841  1.504883

[842 rows x 1 columns]

            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
907  1.784282
908  1.808690
909  1.822560
910  1.746474
911  1.555200

[912 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
907  1.072836
908  1.048185
909  1.040780
910  0.967304
911  0.864582

[912 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
905  0.627648
906  0.606556
907  0.615980
908  0.570473
909  0.560346

[910 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
902  2.588258
903  2.585180
904  2.592271
905  2.678784
906  2.694138

[907 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
905  0.720880
906  0.686120
907  0.661530
908  0.568972
909  0.560257

[910 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
898  1.253542
899  1.249521
900  1.248788
901  1.205504
902  1.157936

[903 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
890  0.706219
891  0.743344
892  0.670245
893  0.712748
894  0.614010

[895 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
895  1.609129
896  1.626983
897  1.580231
898  1.436048
899  1.351770

[900 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
895  0.696780
896  0.683252
897  0.704176
898  0.722368
899  0.662834

[900 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
773  1.107982
774  1.070368
775  1.035228
776  1.057741
777  0.951985

[778 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
898  1.214955
899  1.196771
900  1.213888
901  1.168112
902  1.089391

[903 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
885  1.282620
886  1.292538
887  1.316074
888  1.430162
889  1.327716

[890 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
888  1.153293
889  1.099351
890  1.086073
891  0.975879
892  0.850431

[893 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
884  0.601074
885  0.616617
886  0.617037
887  0.577678
888  0.420988

[889 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
888  1.370591
889  1.354335
890  1.366099
891  1.339800
892  1.259182

[893 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
888  1.148408
889  1.356073
890  1.325833
891  1.464849
892  1.349128

[893 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
820  1.556284
821  1.617396
822  1.322954
823  1.661695
824  1.541221

[825 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
874  0.847567
875  0.907069
876  0.862314
877  0.795009
878  0.639239

[879 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
879  1.308266
880  1.260940
881  1.316630
882  1.331304
883  1.353503

[884 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
151  0.868282
152  0.848352
153  0.868619
154  0.978725
155  0.968179

[156 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
873  1.245821
874  1.178150
875  1.187929
876  1.194955
877  1.122148

[878 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
868  1.959378
869  1.924670
870  1.953300
871  1.801058
872  1.805527

[873 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
873  1.976799
874  1.952907
875  2.043471
876  1.891368
877  1.970597

[878 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
866  1.681334
867  1.687379
868  1.716979
869  1.624445
870  1.490526

[871 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
870  0.926447
871  0.917642
872  0.908137
873  0.864800
874  0.806906

[875 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
863  1.522107
864  1.494693
865  1.615538
866  1.528962
867  1.387931

[868 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
853  1.584738
854  1.718145
855  1.738667
856  1.735952
857  1.672359

[858 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
863  1.528473
864  1.505457
865  1.468745
866  1.393024
867  1.505416

[868 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
861  0.720526
862  0.695815
863  0.687167
864  0.759845
865  0.635332

[866 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
853  1.221074
854  1.267713
855  1.208576
856  1.275716
857  1.206463

[858 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
843  2.086099
844  2.094625
845  1.989040
846  1.825525
847  1.512061

[848 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
852  1.388999
853  1.378549
854  1.399842
855  1.287956
856  1.219609

[857 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
754  1.631669
755  1.591539
756  1.572912
757  1.520694
758  1.491067

[759 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
850  1.710362
851  1.671233
852  1.732328
853  1.625793
854  1.619083

[855 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
730  1.425436
731  1.352456
732  1.394800
733  1.351681
734  1.192717

[735 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
853  0.926352
854  0.888085
855  0.875706
856  0.811810
857  0.736832

[858 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
805  0.917438
806  0.911985
807  0.886975
808  0.813199
809  0.711525

[810 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
841  0.590962
842  0.562996
843  0.514214
844  0.430535
845  0.386805

[846 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
837  0.704774
838  0.714227
839  0.697277
840  0.651032
841  0.559284

[842 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
840  0.715068
841  0.769720
842  0.827265
843  0.881577
844  0.858353

[845 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
751  0.359919
752  0.313733
753  0.308154
754  0.370652
755  0.340470

[756 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
842  0.544515
843  0.542440
844  0.547214
845  0.585210
846  0.556388

[847 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
842  1.356786
843  1.328679
844  1.329717
845  1.168179
846  1.050337

[847 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
836  0.399814
837  0.379636
838  0.402350
839  0.465606
840  0.407515

[841 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
734  2.537771
735  2.556070
736  2.548205
737  2.431951
738  2.329202

[739 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
839  0.357593
840  0.196972
841  0.115801
842  0.038923
843  0.047583

[844 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
810  1.180998
811  1.044496
812  0.833627
813  0.761227
814  0.604723

[815 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
795  1.564365
796  1.544395
797  1.515368
798  1.347509
799  1.372740

[800 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
245  1.061395
246  1.040692
247  1.045055
248  1.001952
249  0.970017

[250 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
834  0.917810
835  0.939061
836  0.914881
837  0.850278
838  0.569558

[839 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
831  1.677987
832  1.734991
833  1.686965
834  1.604969
835  1.490958

[836 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
825  1.302921
826  1.246592
827  1.194015
828  0.984686
829  0.937647

[830 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
826  2.288774
827  2.422802
828  2.391018
829  2.219745
830  2.031391

[831 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
830  2.130661
831  2.095424
832  2.121654
833  2.120833
834  1.952376

[835 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
828  0.806867
829  0.773038
830  0.807248
831  0.777733
832  0.727202

[833 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
824  0.777857
825  0.824402
826  0.789284
827  0.775016
828  0.660086

[829 rows x 1 columns]

            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
827  2.022871
828  2.003943
829  1.949080
830  1.925586
831  1.767339

[832 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
666  2.542463
667  2.483386
668  2.489498
669  2.408588
670  2.250695

[671 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
776  2.181473
777  2.164941
778  2.133770
779  1.975212
780  1.792098

[781 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
823  1.330058
824  1.306272
825  1.326326
826  1.290610
827  1.205583

[828 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
823  0.665023
824  0.677794
825  0.685610
826  0.743712
827  0.761716

[828 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
810  0.682848
811  0.690070
812  0.602987
813  0.553547
814  0.445628

[815 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
820  1.385533
821  1.341524
822  1.316328
823  1.392422
824  1.253174

[825 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
818  1.570249
819  1.582594
820  1.649267
821  1.516827
822  1.479425

[823 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
820  0.851849
821  0.826753
822  0.830586
823  0.893638
824  0.802173

[825 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
815  0.673591
816  0.676230
817  0.695735
818  0.653323
819  0.617698

[820 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
647  1.419447
648  1.453471
649  1.270464
650  1.314673
651  1.370833

[652 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
815  1.510104
816  1.534681
817  1.541364
818  1.446515
819  1.388226

[820 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
818  1.314646
819  1.224859
820  1.221142
821  1.162684
822  1.098741

[823 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
804  0.804513
805  0.807175
806  0.822641
807  0.846692
808  0.858193

[809 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
809  1.263554
810  1.329058
811  1.304081
812  1.318369
813  1.279156

[814 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
803  1.881876
804  1.849934
805  1.839456
806  1.780162
807  1.687689

[808 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
808  0.847415
809  0.852080
810  0.856682
811  0.841857
812  0.796338

[813 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
801  1.084465
802  1.007483
803  1.055864
804  1.122414
805  1.386107

[806 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
797  0.187910
798  0.165965
799  0.264710
800  0.295774
801  0.268000

[802 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
798  1.300893
799  1.312424
800  1.291376
801  1.260569
802  1.120150

[803 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
799  2.009305
800  2.001359
801  1.978070
802  1.838298
803  1.736004

[804 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
578  1.719959
579  1.740561
580  1.816649
581  1.706663
582  1.730073

[583 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
796  0.570526
797  0.551527
798  0.565511
799  0.532503
800  0.486706

[801 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
795  1.126250
796  1.049816
797  1.029841
798  1.016815
799  0.886763

[800 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
794  1.119136
795  1.092642
796  1.075628
797  1.020157
798  0.879051

[799 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
796  1.552811
797  1.500592
798  1.461857
799  1.320636
800  1.177249

[801 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
748  0.715725
749  0.712816
750  0.754132
751  0.775738
752  0.788017

[753 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
789  0.605413
790  0.600204
791  0.552108
792  0.489732
793  0.356593

[794 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
792  0.947070
793  0.940765
794  0.924826
795  0.863292
796  0.790781

[797 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
784  1.735072
785  1.698711
786  1.752479
787  1.655552
788  1.477277

[789 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
784  0.988038
785  1.009227
786  0.972911
787  0.920575
788  0.672732

[789 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
547  2.232422
548  2.153441
549  2.113548
550  1.902385
551  1.672750

[552 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
781  0.902458
782  0.856956
783  0.863917
784  0.806269
785  0.670948

[786 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
785  0.917109
786  0.872117
787  0.851431
788  0.882138
789  0.827652

[790 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
780  1.356456
781  1.330073
782  1.414815
783  1.312409
784  1.203088

[785 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
779  1.432954
780  1.414272
781  1.351207
782  1.348855
783  1.056282

[784 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
780  0.411914
781  0.549466
782  0.537604
783  0.521330
784  0.442991

[785 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
758  0.943078
759  0.959936
760  0.995643
761  0.813442
762  0.664461

[763 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
776  0.642704
777  0.605213
778  0.627084
779  0.585108
780  0.585135

[781 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
773  0.184167
774  0.239951
775  0.223878
776  0.223038
777  0.156138

[778 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
764  1.963978
765  1.931837
766  1.914374
767  1.878419
768  1.743599

[769 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
572  1.106931
573  1.086499
574  1.031831
575  1.243647
576  1.144894

[577 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
773  0.983069
774  0.881409
775  0.854703
776  0.769382
777  0.678127

[778 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
724  1.083720
725  1.135978
726  1.180492
727  1.120277
728  1.013193

[729 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
771  0.765546
772  0.782904
773  0.845234
774  0.955799
775  0.853580

[776 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
759  0.533607
760  0.518486
761  0.494609
762  0.439896
763  0.410187

[764 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
766  0.468756
767  0.426030
768  0.341140
769  0.253708
770  0.278621

[771 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
762  0.732464
763  0.782696
764  0.908122
765  0.827878
766  0.731571

[767 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
757  0.650795
758  0.633506
759  0.620895
760  0.595573
761  0.585672

[762 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
757  0.976049
758  0.970641
759  0.904704
760  0.806559
761  0.722493

[762 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
664  1.464232
665  1.443151
666  1.462169
667  1.408384
668  1.338987

[669 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
745  2.302567
746  2.236544
747  2.321966
748  2.258723
749  2.126049

[750 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
686  1.694114
687  1.697652
688  1.709688
689  1.664860
690  1.455328

[691 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
717  1.915684
718  1.866987
719  1.918172
720  1.789924
721  1.639103

[722 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
746  0.905683
747  0.862199
748  0.838001
749  0.949918
750  0.848811

[751 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
641  1.755306
642  1.730943
643  1.751840
644  1.501690
645  1.266980

[646 rows x 1 columns]

            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
746  1.078317
747  1.060282
748  1.087765
749  1.073575
750  0.971204

[751 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
734  1.576900
735  1.536827
736  1.600505
737  1.904570
738  1.876571

[739 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
694  0.808098
695  0.781831
696  0.760185
697  0.804030
698  0.544652

[699 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
742  2.042514
743  2.033786
744  2.085118
745  2.221503
746  1.996402

[747 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
597  0.432141
598  0.451565
599  0.442288
600  0.364114
601  0.240042

[602 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
739  0.964888
740  0.910995
741  0.875343
742  0.798346
743  0.739713

[744 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
721  1.141533
722  1.291032
723  1.256744
724  1.270166
725  1.094389

[726 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
719  1.114035
720  1.069559
721  1.010969
722  0.994113
723  0.981944

[724 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
735  0.678619
736  0.653706
737  0.658762
738  0.649130
739  0.604668

[740 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
727 -0.078495
728 -0.070833
729 -0.111123
730 -0.104082
731 -0.096723

[732 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
639  1.350753
640  1.337922
641  1.349186
642  1.210881
643  1.147650

[644 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
723  1.662567
724  1.659494
725  1.607539
726  1.512874
727  1.595194

[728 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
705  1.520260
706  1.514504
707  1.562235
708  1.458857
709  1.363070

[710 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
719  1.442273
720  1.425420
721  1.400830
722  1.287786
723  1.258788

[724 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
395  1.775097
396  1.732556
397  1.743852
398  1.679559
399  1.453734

[400 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
713  0.569841
714  0.546483
715  0.576573
716  0.578269
717  0.623707

[718 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
706  0.311647
707  0.475619
708  0.411605
709  0.389438
710  0.285843

[711 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
711  0.079678
712  0.107112
713 -0.024443
714 -0.072131
715 -0.274525

[716 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
691  1.212264
692  1.208497
693  1.276274
694  1.128435
695  1.049527

[696 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
705  2.131028
706  2.147654
707  2.184143
708  2.093782
709  1.986814

[710 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
625  1.558273
626  1.562236
627  1.542689
628  1.691341
629  1.422540

[630 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
709  0.424103
710  0.368631
711  0.355542
712  0.273025
713  0.201095

[714 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
653  1.604319
654  1.675333
655  1.679177
656  1.594849
657  1.524344

[658 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
641  1.322033
642  1.203641
643  1.259221
644  1.306005
645  1.269756

[646 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
603  1.770576
604  1.740725
605  1.773856
606  1.841784
607  1.631024

[608 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
703  1.383971
704  1.416363
705  1.276407
706  1.151440
707  0.957520

[708 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
701  1.882602
702  1.876740
703  1.807506
704  1.695778
705  1.527809

[706 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
692  1.583333
693  1.616094
694  1.694251
695  1.537475
696  1.374519

[697 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
686  1.154024
687  1.136811
688  1.193939
689  1.214241
690  1.099186

[691 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
698  1.090769
699  1.083239
700  1.111313
701  1.061603
702  1.006425

[703 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
699  0.917969
700  0.916396
701  0.932821
702  1.010245
703  0.978801

[704 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
696  0.795032
697  0.773328
698  0.816088
699  0.697717
700  0.662394

[701 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
685  0.311831
686  0.289856
687  0.276985
688  0.293495
689  0.339690

[690 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
684  0.999051
685  0.952061
686  0.931837
687  0.826766
688  0.745443

[689 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
412  0.692337
413  0.735707
414  0.743848
415  0.718680
416  0.659594

[417 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
676  1.157867
677  1.110050
678  1.162462
679  1.128896
680  1.119217

[681 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
689  0.785584
690  0.762782
691  0.740286
692  0.661112
693  0.708349

[694 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
677  1.142777
678  1.227099
679  1.251082
680  1.083371
681  1.066343

[682 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
682  1.519727
683  1.356812
684  1.391246
685  1.531333
686  1.451704

[687 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
681  1.369299
682  1.377101
683  1.344699
684  1.338259
685  1.253919

[686 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
664  1.029163
665  0.981132
666  0.964608
667  0.897312
668  0.822766

[669 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
671  1.531988
672  1.604083
673  1.538494
674  1.653137
675  1.509176

[676 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
669  1.114714
670  1.126600
671  1.140598
672  1.286915
673  1.082790

[674 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
669  0.614478
670  0.574622
671  0.623269
672  0.543498
673  0.614143

[674 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
659  0.427230
660  0.412777
661  0.414828
662  0.387485
663  0.311780

[664 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
664  1.382722
665  1.470854
666  1.497392
667  1.353236
668  1.118780

[669 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
659  1.665964
660  1.648710
661  1.756654
662  1.670427
663  1.627754

[664 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
655  1.522418
656  1.484128
657  1.511669
658  1.654685
659  1.684937

[660 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
652  2.653866
653  2.609612
654  2.660216
655  2.658202
656  2.511764

[657 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
652  1.037989
653  0.993209
654  0.981002
655  0.919878
656  0.826211

[657 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
643  1.116918
644  1.220845
645  1.274147
646  1.138608
647  1.109029

[648 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
644  0.733426
645  0.655658
646  0.656532
647  0.512344
648  0.458424

[649 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
643  1.402281
644  1.242566
645  1.217572
646  1.008221
647  0.987995

[648 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
641  1.077504
642  0.982629
643  1.006984
644  0.992098
645  0.923010

[646 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
637  1.211864
638  1.193457
639  1.158829
640  1.141485
641  1.076343

[642 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
640  0.894781
641  0.859734
642  0.831306
643  0.856100
644  0.777981

[645 rows x 1 columns]

            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
640  0.892968
641  0.936490
642  0.938935
643  1.033740
644  1.028631

[645 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
637  0.914096
638  0.883510
639  0.807398
640  0.820218
641  0.772218

[642 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
640  1.153196
641  1.125578
642  1.181397
643  1.184275
644  1.016207

[645 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
633  0.347716
634  0.231018
635  0.167973
636  0.030595
637 -0.067200

[638 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
636  0.516488
637  0.480630
638  0.434585
639  0.359127
640  0.436333

[641 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
632  0.923992
633  0.973524
634  1.014567
635  1.117301
636  1.083039

[637 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
452  2.943012
453  2.912672
454  2.944710
455  2.798833
456  2.430577

[457 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
631  1.818268
632  1.815075
633  1.722429
634  1.680552
635  1.435253

[636 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
629  1.439822
630  1.431995
631  1.442628
632  1.393777
633  1.280814

[634 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
625  0.916853
626  0.898339
627  0.872894
628  0.896652
629  0.800530

[630 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
621  0.781997
622  0.789696
623  0.740504
624  0.664345
625  0.525754

[626 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
614  1.626000
615  1.500230
616  1.525683
617  1.422555
618  1.334693

[619 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
601  1.136214
602  1.123080
603  1.138039
604  1.081668
605  0.986478

[606 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
570  0.921118
571  0.886552
572  0.891734
573  0.843237
574  0.850404

[575 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
590  0.717993
591  0.687638
592  0.686245
593  0.632332
594  0.622657

[595 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
601  1.451721
602  1.530540
603  1.534847
604  1.518327
605  1.546158

[606 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
595  1.351347
596  1.353794
597  1.266256
598  1.438292
599  1.157985

[600 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
583  1.422051
584  1.454063
585  1.407709
586  1.517867
587  1.455496

[588 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
587  2.297997
588  2.302954
589  2.275249
590  2.054903
591  1.777333

[592 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
578  1.943319
579  1.965187
580  1.987337
581  1.845562
582  1.691176

[583 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
473  1.154824
474  1.094943
475  1.175769
476  0.985526
477  1.017404

[478 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
563  0.509531
564  0.502373
565  0.479264
566  0.467847
567  0.433141

[568 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
519  0.928779
520  1.002163
521  0.963749
522  0.908031
523  0.786323

[524 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
524  0.963362
525  1.002530
526  1.097559
527  1.005659
528  0.836734

[529 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
508  0.580657
509  0.548369
510  0.582734
511  0.526923
512  0.465817

[513 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
490  1.084499
491  1.083935
492  1.121982
493  1.102709
494  1.044160

[495 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
486  1.020291
487  1.032162
488  1.097873
489  1.041452
490  0.872360

[491 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
422  0.118644
423  0.255067
424  0.322291
425  0.224947
426  0.299322

[427 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
406  0.852338
407  0.849598
408  0.861315
409  0.710506
410  0.654663

[411 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
495  1.442073
496  1.435282
497  1.433199
498  1.462797
499  1.244467

[500 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
393  2.473136
394  2.497429
395  2.485621
396  2.263109
397  1.952481

[398 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
378  1.140896
379  1.146020
380  1.109194
381  1.268622
382  1.096243

[383 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
369  0.789824
370  0.818471
371  0.848866
372  0.792271
373  0.626595

[374 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
338  1.657724
339  1.736492
340  1.521833
341  1.542961
342  1.562360

[343 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
358  0.402522
359  0.401253
360  0.411997
361  0.468361
362  0.486351

[363 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
353  0.623108
354  0.671026
355  0.624468
356  0.788636
357  0.699582

[358 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
325  1.043374
326  1.006373
327  1.020793
328  1.092498
329  1.242157

[330 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
339  1.727311
340  1.815273
341  1.655883
342  1.614184
343  1.427343

[344 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
411  0.518644
412  0.620482
413  0.605175
414  0.583797
415  0.450551

[416 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
329  0.907618
330  0.929122
331  0.910662
332  0.990855
333  0.949614

[334 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
311  1.195197
312  1.210281
313  1.223381
314  1.174236
315  1.446488

[316 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
308  2.180848
309  2.383444
310  2.236568
311  2.108722
312  1.986091

[313 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
305  1.088676
306  1.157805
307  1.109127
308  1.398295
309  1.239565

[310 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
304  1.257913
305  1.154094
306  1.180295
307  1.031465
308  0.820096

[309 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
300  1.871151
301  1.822165
302  1.739130
303  1.590015
304  1.358505

[305 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
291  1.527085
292  1.542226
293  1.540908
294  1.444535
295  1.193352

[296 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
290  2.127098
291  2.124115
292  2.152287
293  2.210864
294  2.009677

[295 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
286  1.317895
287  1.504077
288  1.392566
289  1.274258
290  0.834838

[291 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
285  1.501365
286  1.472445
287  1.500484
288  1.447492
289  1.370295

[290 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
281  0.482403
282  0.492995
283  0.489428
284  0.557919
285  0.506707

[286 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
282  1.537577
283  1.514387
284  1.483291
285  1.468945
286  1.369125

[287 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
267  0.610763
268  0.639209
269  0.623272
270  0.718404
271  0.735183

[272 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
269  0.758701
270  0.747128
271  0.727284
272  0.631186
273  0.737019

[274 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
270  0.904743
271  1.004288
272  0.986281
273  0.903713
274  0.913831

[275 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
274  0.906966
275  0.913818
276  0.840949
277  0.761418
278  0.813792

[279 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
266  0.997312
267  1.051521
268  1.048726
269  1.016747
270  0.988734

[271 rows x 1 columns]

            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
257  1.041972
258  1.055666
259  1.046203
260  1.040739
261  1.010782

[262 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
255  1.987404
256  1.980779
257  1.987859
258  1.954371
259  1.888801

[260 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
248  2.029710
249  2.114247
250  2.175699
251  2.158704
252  2.021323

[253 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
230  1.058764
231  1.091559
232  1.092644
233  1.125594
234  1.016382

[235 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
229  1.818160
230  1.776443
231  1.826834
232  1.920605
233  1.737780

[234 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
223  0.542366
224  0.531085
225  0.504755
226  0.457331
227  0.388778

[228 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
206  1.474226
207  1.472765
208  1.490751
209  1.490474
210  1.358982

[211 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
235  1.066968
236  1.086601
237  1.106688
238  1.013430
239  0.981849

[240 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
197  1.098645
198  1.069822
199  1.090557
200  1.040070
201  0.950824

[202 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
181  0.420881
182  0.359280
183  0.414401
184  0.374128
185  0.445769

[186 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
178  1.088653
179  1.136358
180  0.960574
181  1.055295
182  0.800611

[183 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
176  0.984666
177  0.904786
178  0.925385
179  0.940695
180  0.815415

[181 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
166  1.848044
167  1.760081
168  1.776535
169  1.694441
170  1.543816

[171 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
164  1.110574
165  1.070600
166  1.054629
167  1.019954
168  0.930635

[169 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
146  0.416790
147  0.606631
148  0.586201
149  0.707356
150  0.625264

[151 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
156  0.444449
157  0.459778
158  0.537700
159  0.454317
160  0.491276

[161 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
141  0.801238
142  0.885524
143  0.829846
144  1.002701
145  0.919428

[146 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
159  1.103063
160  1.112619
161  1.116113
162  0.981452
163  0.866618

[164 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
153  1.052826
154  1.010083
155  1.040222
156  1.010436
157  1.108463

[158 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
137  0.572644
138  0.617487
139  0.596112
140  0.758518
141  0.686343

[142 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
146  1.058817
147  1.018044
148  0.901543
149  0.862201
150  0.620025

[151 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
145  2.068130
146  2.039145
147  2.070036
148  2.048641
149  1.949362

[150 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
142  1.977732
143  1.852600
144  1.758466
145  1.652385
146  1.620726

[147 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
140  1.408051
141  1.339022
142  1.373869
143  1.381678
144  1.325681

[145 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
122  0.651522
123  0.627072
124  0.628487
125  0.572722
126  0.576288

[127 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
136  0.779868
137  0.730925
138  0.769510
139  0.680747
140  0.633518

[141 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
133  1.112649
134  1.089101
135  1.071627
136  1.028461
137  0.955889

[138 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
131  0.837466
132  0.819854
133  0.812041
134  0.782857
135  0.812746

[136 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
115  1.299304
116  1.315341
117  1.270710
118  1.138222
119  1.084748

[120 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
108  1.229043
109  1.272503
110  1.195116
111  1.033356
112  0.897586

[113 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
105 -0.259329
106 -0.294499
107 -0.329489
108 -0.439753
109 -0.464574

[110 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
98   1.514186
99   1.574222
100  1.610457
101  1.638919
102  1.616258

[103 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
92  0.986607
93  0.894780
94  0.856868
95  0.741612
96  0.669398

[97 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
86  0.402827
87  0.283808
88  0.274804
89  0.192853
90  0.164897

[91 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
90  0.610009
91  0.570040
92  0.616294
93  0.553512
94  0.510214

[95 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
69  0.330817
70  0.160565
71  0.246824
72  0.330181
73  0.334882

[74 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
89 -0.004715
90  0.251060
91  0.188641
92  0.717648
93  0.786147

[94 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
69  1.598114
70  1.500598
71  1.520176
72  1.610864
73  1.510892

[74 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
68  1.157499
69  1.024997
70  1.074171
71  1.111954
72  1.012457

[73 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
64  1.254575
65  1.464968
66  1.531154
67  1.439055
68  1.342494

[69 rows x 1 columns]
    0
0 NaN
1 NaN
2 NaN
3 NaN
4 NaN
5 NaN
6 NaN
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
58       NaN
59  0.761229
60  0.699268
61  0.945484
62  0.788960

[63 rows x 1 columns]
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
36 NaN
37 NaN
38 NaN
39 NaN
40 NaN
41 NaN
42 NaN
43 NaN
44 NaN
45 NaN
46 NaN
47 NaN
48 NaN
49 NaN
50 NaN
51 NaN
52 NaN
53 NaN
54 NaN
55 NaN
56 NaN
57 NaN

     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
36 NaN
37 NaN
38 NaN
39 NaN
40 NaN
41 NaN
42 NaN
43 NaN
44 NaN
45 NaN
46 NaN
47 NaN
48 NaN
49 NaN
50 NaN
51 NaN
52 NaN
53 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
36 NaN
37 NaN
38 NaN
39 NaN
40 NaN
41 NaN
42 NaN
43 NaN
44 NaN
45 NaN
46 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
36 NaN
37 NaN
38 NaN
39 NaN
40 NaN
41 NaN
42 NaN
43 NaN
44 NaN
45 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
36 NaN
37 NaN
38 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
36 NaN
37 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
    0
0 NaN
1 NaN
    0
0 NaN
1 NaN
2 NaN
3 NaN
4 NaN
5 NaN
6 NaN
7 NaN
8 NaN
9 NaN
    0
0 NaN
1 NaN
2 NaN
3 NaN
4 NaN
5 NaN
6 NaN
7 NaN
    0
0 NaN

In [17]:
import pandas as pd
import matplotlib as mpl
import glob
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats
import matplotlib.dates as mdates
import math
from scipy import stats
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm
from pandas.plotting import register_matplotlib_converters
register_matplotlib_converters()
from datetime import timedelta
import calendar
import seaborn as sns

d1 = pd.read_csv(r"D:\work\project 4 event study - minute\CSIRest_in_202006.csv", encoding="GBK")
d1["证券代码1"] = d1["证券代码"].astype(str).apply(lambda x: x.rjust(6, "0"))
d1["StockID"] = np.where(d1["证券代码"] < 600000, "SZ" + d1["证券代码1"].astype(str), 
                        "SH" + d1["证券代码1"].astype(str))
d1 = d1[["StockID"]]
d1.to_csv(r"D:\work\project 4 event study - minute\CSIRest_in_202006.csv", index=False)

In [11]:
import pandas as pd
import matplotlib as mpl
import glob
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats
import matplotlib.dates as mdates
import math
from scipy import stats
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm
from pandas.plotting import register_matplotlib_converters
register_matplotlib_converters()
from datetime import timedelta
import calendar
import seaborn as sns

kk = pd.read_csv(r"D:\work\project 4 event study - minute\IF_out_202006.csv", encoding="GBK")
da_ta = pd.read_csv('E:\\new_beta_300.csv', encoding="utf-8")
test = da_ta[da_ta["Symbol"].isin(kk["StockID"])]
display(kk.shape[0])
display(len(test[(test["Date"]>=20200616) & (test["Date"]<=20200622)]["Symbol"].unique()))
display(test[(test["Date"]>=20200616) & (test["Date"]<=20200622)].groupby("Symbol")["Date"].count())
re = test[(test["Date"]>=20200616) & (test["Date"]<=20200622)].groupby("Symbol")["alpha"].sum().reset_index().mean().reset_index()
re = re.rename(columns={0:"average cumulative alpha"})
re["index"] = "IF"
re["size"] = 21
re

21

21

Symbol
SH600023    5
SH600100    5
SH600153    5
SH600535    5
SH600566    5
SH600663    5
SH600733    5
SH600816    5
SZ000413    5
SZ000415    5
SZ000423    5
SZ000629    5
SZ000630    5
SZ000898    5
SZ002010    5
SZ002081    5
SZ002294    5
SZ002411    5
SZ300017    5
SZ300024    5
SZ300070    5
Name: Date, dtype: int64

  index  average cumulative alpha  size
0    IF                 -0.000803    21

In [12]:
import pandas as pd
import matplotlib as mpl
import glob
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats
import matplotlib.dates as mdates
import math
from scipy import stats
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm
from pandas.plotting import register_matplotlib_converters
register_matplotlib_converters()
from datetime import timedelta
import calendar
import seaborn as sns

kk = pd.read_csv(r"D:\work\project 3 event study\IF_out_202006.csv", encoding="GBK")
da_ta = pd.read_csv('E:\\new_beta_300.csv', encoding="utf-8")
test = da_ta[da_ta["Symbol"].isin(kk["Symbol"])]
display(kk.shape[0])
display(len(test[(test["Date"]>=20200602) & (test["Date"]<=20200605)]["Symbol"].unique()))
display(test[(test["Date"]>=20200602) & (test["Date"]<=20200605)].groupby("Symbol")["Date"].count())
re = test[(test["Date"]>=20200602) & (test["Date"]<=20200605)].groupby("Symbol")["alpha"].sum().reset_index().mean().reset_index()
re = re.rename(columns={0:"average cumulative alpha"})
re["index"] = "IF"
re["size"] = 21
re

22

22

Symbol
SH600023    4
SH600153    4
SH600372    4
SH600535    4
SH600566    4
SH600663    4
SH600733    4
SH600816    4
SH601216    4
SZ000413    4
SZ000415    4
SZ000423    4
SZ000629    4
SZ000630    4
SZ000898    4
SZ002010    4
SZ002081    4
SZ002294    4
SZ002411    4
SZ300017    4
SZ300024    4
SZ300070    4
Name: Date, dtype: int64

  index  average cumulative alpha  size
0    IF                 -0.025095    21

In [170]:
test[(test["Date"]>=20200518) & (test["Date"]<=20200522)].groupby("Symbol")["alpha"].sum()

Symbol
SH600023    0.025668
SH600100   -0.039639
SH600153    0.017164
SH600535   -0.013877
SH600566   -0.023848
SH600663    0.000187
SH600733    0.050406
SZ000413   -0.035320
SZ000415    0.133694
SZ000423    0.059527
SZ000629   -0.009577
SZ000630   -0.005633
SZ000898   -0.023005
SZ002010   -0.022948
SZ002081   -0.013818
SZ002294    0.004445
SZ002411   -0.060096
SZ300017   -0.009149
SZ300024   -0.006037
SZ300070   -0.079365
Name: alpha, dtype: float64

In [15]:
kk1 = pd.read_csv(r"D:\work\project 3 event study\IC_out_202006.csv", encoding="GBK")
list1 = list(set(kk1["Symbol"]) & set(k["Symbol"]))
list2 = list(set(kk1["Symbol"]) - set(list1))
print(len(list1))
print(len(list2))

8
42

In [163]:
kk1[kk1["Symbol"].isin(list1)].to_csv(r"D:\work\project 3 event study\IC_outtotop_202006.csv", index=False, encoding="GBK")

In [19]:
kk1 = pd.read_csv(r"D:\work\project 3 event study\IC_out_202006.csv", encoding="GBK")
da_ta = pd.read_csv('E:\\new_beta_500.csv', encoding="utf-8")
kk1 = kk1[kk1["Symbol"].isin(list2)]
test = da_ta[da_ta["Symbol"].isin(kk1["Symbol"])]
display(kk1.shape[0])
display(len(test[(test["Date"]>=20200616) & (test["Date"]<=20200622)]["Symbol"].unique()))
display(test[(test["Date"]>=20200616) & (test["Date"]<=20200622)].groupby("Symbol")["Date"].count())
re1 = test[(test["Date"]>=20200616) & (test["Date"]<=20200622)].groupby("Symbol")["alpha"].sum().reset_index().mean().reset_index()
re1 = re1.rename(columns={0:"average cumulative alpha"})
re1["average cumulative alpha"] = re1["average cumulative alpha"]*10000
re1["index"] = "IC"
re1["size"] = 50
re1

42

42

Symbol
SH600098    5
SH600150    5
SH600317    4
SH600499    5
SH600536    5
SH600584    5
SH600759    5
SH600763    5
SH600770    5
SH600845    5
SH600939    5
SH601001    5
SH601326    5
SH601872    5
SH603877    5
SZ000006    5
SZ000536    5
SZ000727    5
SZ000761    5
SZ000766    5
SZ000980    5
SZ002049    5
SZ002065    5
SZ002176    5
SZ002180    5
SZ002358    5
SZ002366    5
SZ002384    5
SZ002426    5
SZ002437    5
SZ002482    5
SZ002573    5
SZ002672    5
SZ002812    5
SZ300002    5
SZ300159    5
SZ300197    5
SZ300199    5
SZ300297    5
SZ300308    5
SZ300383    5
SZ300529    5
Name: Date, dtype: int64

  index  average cumulative alpha  size
0    IC                -36.211379    50

In [155]:
kk1[kk1["StockID"].isin(list2)].to_csv("D:\work\project 4 event study - minute\IC_outtobot_202006.csv", index=False, encoding="GBK")
kk1[kk1["StockID"].isin(list1)].to_csv("D:\work\project 4 event study - minute\IC_outtotop_202006.csv", index=False, encoding="GBK")

In [20]:
kk2 = pd.read_csv(r"D:\work\project 3 event study\CSI1000_out_202006.csv", encoding="GBK")
list1 = list((set(kk2["Symbol"]) & set(k["Symbol"]))|(set(kk2["Symbol"]) & set(k1["Symbol"])))
list2 = list(set(kk2["Symbol"]) - set(list1))
print(len(list1))
print(len(list2))

24
76

In [165]:
kk2[kk2["Symbol"].isin(list1)].to_csv(r"D:\work\project 3 event study\CSI1000_outtotop_202006.csv", index=False, encoding="GBK")

In [40]:
kk2 = pd.read_csv(r"D:\work\project 3 event study\CSI1000_out_202006.csv", encoding="GBK")
da_ta = pd.read_csv('E:\\new_beta_1000.csv', encoding="utf-8")
kk2 = kk2[kk2["Symbol"].isin(list1)]
test = da_ta[da_ta["Symbol"].isin(kk2["Symbol"])]
display(kk2.shape[0])
display(len(test[(test["Date"]>=2020060) & (test["Date"]<=20200605)]["Symbol"].unique()))
display(test[(test["Date"]>=20200602) & (test["Date"]<=20200605)].groupby("Symbol")["Date"].count())
re2 = test[(test["Date"]>=20200602) & (test["Date"]<=20200605)].groupby("Symbol")["alpha"].sum().reset_index().mean().reset_index()
re2 = re2.rename(columns={0:"average cumulative alpha"})
re2["average cumulative alpha"] = re2["average cumulative alpha"]*10000
re2["index"] = "CSI1000"
re2["size"] = 100
re2

24

24

Symbol
SH600529    4
SH600667    4
SH603605    4
SZ000540    4
SZ000708    4
SZ000800    4
SZ001914    4
SZ002080    4
SZ002138    4
SZ002156    4
SZ002185    4
SZ002396    4
SZ002511    4
SZ002557    4
SZ002901    4
SZ300212    4
SZ300271    4
SZ300357    4
SZ300474    4
SZ300482    4
SZ300496    4
SZ300558    4
SZ300595    4
SZ300618    4
Name: Date, dtype: int64

     index  average cumulative alpha  size
0  CSI1000                  6.333763   100

In [32]:
kk3 = pd.read_csv(r"D:\work\project 4 event study - minute\new\CSIRest_out_202006.csv", encoding="GBK")
list1 = list((set(kk3["StockID"]) & set(k["StockID"]))|(set(kk3["StockID"]) & set(k1["StockID"]))|(set(kk3["StockID"]) & set(k2["StockID"])))
list2 = list(set(kk3["StockID"]) - set(list1))
print(len(list1))
print(len(list2))

77
81

In [22]:
kk3[kk3["Symbol"].isin(list1)].to_csv(r"D:\work\project 3 event study\CSIRest_outtotop_202006.csv", encoding="GBK")

In [34]:
kk3 = pd.read_csv(r"D:\work\project 4 event study - minute\new\CSIRest_out_202006.csv", encoding="GBK")
da_ta = pd.read_csv('E:\\new_beta_CSI.csv', encoding="utf-8")
kk3 = kk3[kk3["StockID"].isin(list2)]
test = da_ta[da_ta["Symbol"].isin(kk3["StockID"])]
display(kk3.shape[0])
display(len(test[(test["Date"]>=20200602) & (test["Date"]<=20200605)]["Symbol"].unique()))
display(test[(test["Date"]>=20200602) & (test["Date"]<=20200605)].groupby("Symbol")["Date"].count())
re3 = test[(test["Date"]>=20200602) & (test["Date"]<=20200605)].groupby("Symbol")["alpha"].sum().reset_index().mean().reset_index()
re3 = re3.rename(columns={0:"average cumulative alpha"})
re3["average cumulative alpha"] = re3["average cumulative alpha"]*10000
re3["index"] = "CSIRest"
re3["size"] = 128
re3

81

80

Symbol
SH600083    4
SH600086    4
SH600122    4
SH600212    4
SH600215    4
           ..
SZ300426    4
SZ300431    4
SZ300460    4
SZ300461    4
SZ300466    4
Name: Date, Length: 80, dtype: int64

     index  average cumulative alpha  size
0  CSIRest                546.960694   128

In [13]:
k = pd.read_csv(r"D:\work\project 3 event study\IF_in_202006.csv", encoding="GBK")
k1 = pd.read_csv(r"D:\work\project 3 event study\IC_in_202006.csv", encoding="GBK")
k2 = pd.read_csv(r"D:\work\project 3 event study\CSI1000_in_202006.csv", encoding="GBK")

In [68]:
ree = pd.concat([re, re1, re2, re3])
ree["average cumulative alpha"] = ree["average cumulative alpha"] * 10000
ree

     index  average cumulative alpha  size
0       IF                 23.381965    21
0       IC                -81.921628    50
0  CSI1000                -32.792756   100
0  CSIRest               -139.569718   128

## OUT version

In [45]:
# predict result
import pandas as pd
import matplotlib as mpl
import glob
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats
import matplotlib.dates as mdates
import math
from scipy import stats
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm
from pandas.plotting import register_matplotlib_converters
register_matplotlib_converters()
from datetime import timedelta
import calendar
import seaborn as sns

sd = 20200623
ed = 20200701


# IF out
kk = pd.read_csv(r"D:\work\project 3 event study\IF_out_202006.csv", encoding="GBK")
da_ta = pd.read_csv('E:\\new_beta_300.csv', encoding="utf-8")
test = da_ta[da_ta["Symbol"].isin(kk["Symbol"])]
display(kk.shape[0])
display(len(test[(test["Date"]>=sd) & (test["Date"]<=ed)]["Symbol"].unique()))
display(test[(test["Date"]>=sd) & (test["Date"]<=ed)].groupby("Symbol")["Date"].count())
re = test[(test["Date"]>=sd) & (test["Date"]<=ed)].groupby("Symbol")["alpha"].sum().reset_index().mean().reset_index()
re = re.rename(columns={0:"average cumulative alpha"})
re["index"] = "IF"
re["size"] = 22
display("---------------------IF out--------------------------")
display(re)

k = pd.read_csv(r"D:\work\project 3 event study\IF_in_202006.csv", encoding="GBK")
k1 = pd.read_csv(r"D:\work\project 3 event study\IC_in_202006.csv", encoding="GBK")
k2 = pd.read_csv(r"D:\work\project 3 event study\CSI1000_in_202006.csv", encoding="GBK")

# IC out-to-top
kk1 = pd.read_csv(r"D:\work\project 3 event study\IC_out_202006.csv", encoding="GBK")
list1 = list(set(kk1["Symbol"]) & set(k["Symbol"]))
list2 = list(set(kk1["Symbol"]) - set(list1))
print(len(list1))
print(len(list2))

kk1 = pd.read_csv(r"D:\work\project 3 event study\IC_out_202006.csv", encoding="GBK")
da_ta = pd.read_csv('E:\\new_beta_500.csv', encoding="utf-8")
kk1 = kk1[kk1["Symbol"].isin(list1)]
test = da_ta[da_ta["Symbol"].isin(kk1["Symbol"])]
display(kk1.shape[0])
display(len(test[(test["Date"]>=sd) & (test["Date"]<=ed)]["Symbol"].unique()))
display(test[(test["Date"]>=sd) & (test["Date"]<=ed)].groupby("Symbol")["Date"].count())
re1 = test[(test["Date"]>=sd) & (test["Date"]<=ed)].groupby("Symbol")["alpha"].sum().reset_index().mean().reset_index()
re1 = re1.rename(columns={0:"average cumulative alpha"})
re1["average cumulative alpha"] = re1["average cumulative alpha"]*10000
re1["index"] = "IC"
re1["size"] = 8
display("----------------------IC out-to-top---------------------------")
display(re1)

# IC out-to-bottom
kk1 = pd.read_csv(r"D:\work\project 3 event study\IC_out_202006.csv", encoding="GBK")
da_ta = pd.read_csv('E:\\new_beta_500.csv', encoding="utf-8")
kk1 = kk1[kk1["Symbol"].isin(list2)]
test = da_ta[da_ta["Symbol"].isin(kk1["Symbol"])]
display(kk1.shape[0])
display(len(test[(test["Date"]>=sd) & (test["Date"]<=ed)]["Symbol"].unique()))
display(test[(test["Date"]>=sd) & (test["Date"]<=ed)].groupby("Symbol")["Date"].count())
re1 = test[(test["Date"]>=sd) & (test["Date"]<=ed)].groupby("Symbol")["alpha"].sum().reset_index().mean().reset_index()
re1 = re1.rename(columns={0:"average cumulative alpha"})
re1["average cumulative alpha"] = re1["average cumulative alpha"]*10000
re1["index"] = "IC"
re1["size"] = 42
display("------------------IC out-to-bottom---------------------------")
display(re1)

# CSI1000 out-to-top
kk2 = pd.read_csv(r"D:\work\project 3 event study\CSI1000_out_202006.csv", encoding="GBK")
list1 = list((set(kk2["Symbol"]) & set(k["Symbol"]))|(set(kk2["Symbol"]) & set(k1["Symbol"])))
list2 = list(set(kk2["Symbol"]) - set(list1))
print(len(list1))
print(len(list2))

kk2 = pd.read_csv(r"D:\work\project 3 event study\CSI1000_out_202006.csv", encoding="GBK")
da_ta = pd.read_csv('E:\\new_beta_1000.csv', encoding="utf-8")
kk2 = kk2[kk2["Symbol"].isin(list1)]
test = da_ta[da_ta["Symbol"].isin(kk2["Symbol"])]
display(kk2.shape[0])
display(len(test[(test["Date"]>=sd) & (test["Date"]<=ed)]["Symbol"].unique()))
display(test[(test["Date"]>=sd) & (test["Date"]<=ed)].groupby("Symbol")["Date"].count())
re2 = test[(test["Date"]>=sd) & (test["Date"]<=ed)].groupby("Symbol")["alpha"].sum().reset_index().mean().reset_index()
re2 = re2.rename(columns={0:"average cumulative alpha"})
re2["average cumulative alpha"] = re2["average cumulative alpha"]*10000
re2["index"] = "CSI1000"
re2["size"] = 24
display("------------------CSI1000 out-to-top---------------------------")
display(re2)

#CSI1000 out-to-bottom
kk2 = pd.read_csv(r"D:\work\project 3 event study\CSI1000_out_202006.csv", encoding="GBK")
da_ta = pd.read_csv('E:\\new_beta_1000.csv', encoding="utf-8")
kk2 = kk2[kk2["Symbol"].isin(list2)]
test = da_ta[da_ta["Symbol"].isin(kk2["Symbol"])]
display(kk2.shape[0])
display(len(test[(test["Date"]>=sd) & (test["Date"]<=ed)]["Symbol"].unique()))
display(test[(test["Date"]>=sd) & (test["Date"]<=ed)].groupby("Symbol")["Date"].count())
re2 = test[(test["Date"]>=sd) & (test["Date"]<=ed)].groupby("Symbol")["alpha"].sum().reset_index().mean().reset_index()
re2 = re2.rename(columns={0:"average cumulative alpha"})
re2["average cumulative alpha"] = re2["average cumulative alpha"]*10000
re2["index"] = "CSI1000"
re2["size"] = 76
display("------------------CSI1000 out-to-bottom---------------------------")
display(re2)

# CSIRest out-to-top
kk3 = pd.read_csv(r"D:\work\project 3 event study\CSIRest_out_202006.csv", encoding="GBK")
list1 = list((set(kk3["Symbol"]) & set(k["Symbol"]))|(set(kk3["Symbol"]) & set(k1["Symbol"]))|(set(kk3["Symbol"]) & set(k2["Symbol"])))
list2 = list(set(kk3["Symbol"]) - set(list1))
print(len(list1))
print(len(list2))

kk3 = pd.read_csv(r"D:\work\project 3 event study\CSIRest_out_202006.csv", encoding="GBK")
da_ta = pd.read_csv('E:\\new_beta_CSI.csv', encoding="utf-8")
kk3 = kk3[kk3["Symbol"].isin(list1)]
test = da_ta[da_ta["Symbol"].isin(kk3["Symbol"])]
display(kk3.shape[0])
display(len(test[(test["Date"]>=sd) & (test["Date"]<=ed)]["Symbol"].unique()))
display(test[(test["Date"]>=sd) & (test["Date"]<=ed)].groupby("Symbol")["Date"].count())
re3 = test[(test["Date"]>=sd) & (test["Date"]<=ed)].groupby("Symbol")["alpha"].sum().reset_index().mean().reset_index()
re3 = re3.rename(columns={0:"average cumulative alpha"})
re3["average cumulative alpha"] = re3["average cumulative alpha"]*10000
re3["index"] = "CSIRest"
re3["size"] = 77
display("------------------CSIRest out-to-top---------------------------")
display(re3)

#CSIRest out-to-bottom
kk3 = pd.read_csv(r"D:\work\project 3 event study\CSIRest_out_202006.csv", encoding="GBK")
da_ta = pd.read_csv('E:\\new_beta_CSI.csv', encoding="utf-8")
kk3 = kk3[kk3["Symbol"].isin(list2)]
test = da_ta[da_ta["Symbol"].isin(kk3["Symbol"])]
display(kk3.shape[0])
display(len(test[(test["Date"]>=sd) & (test["Date"]<=ed)]["Symbol"].unique()))
display(test[(test["Date"]>=sd) & (test["Date"]<=ed)].groupby("Symbol")["Date"].count())
re3 = test[(test["Date"]>=sd) & (test["Date"]<=ed)].groupby("Symbol")["alpha"].sum().reset_index().mean().reset_index()
re3 = re3.rename(columns={0:"average cumulative alpha"})
re3["average cumulative alpha"] = re3["average cumulative alpha"]*10000
re3["index"] = "CSIRest"
re3["size"] = 51
display("------------------CSIRest out-to-bottom---------------------------")
display(re3)

22

22

Symbol
SH600023    5
SH600153    5
SH600372    5
SH600535    5
SH600566    5
SH600663    5
SH600733    5
SH600816    5
SH601216    5
SZ000413    5
SZ000415    5
SZ000423    5
SZ000629    5
SZ000630    5
SZ000898    5
SZ002010    5
SZ002081    5
SZ002294    5
SZ002411    5
SZ300017    5
SZ300024    5
SZ300070    5
Name: Date, dtype: int64

'---------------------IF out--------------------------'

  index  average cumulative alpha  size
0    IF                 -0.021879    22

8
42

8

8

Symbol
SH600745    5
SH601100    5
SH601231    5
SZ000066    5
SZ002129    5
SZ002371    5
SZ002463    5
SZ300014    5
Name: Date, dtype: int64

'----------------------IC out-to-top---------------------------'

  index  average cumulative alpha  size
0    IC                199.953844     8

42

41

Symbol
SH600098    5
SH600150    5
SH600499    5
SH600536    5
SH600584    5
SH600759    5
SH600763    5
SH600770    5
SH600845    5
SH600939    5
SH601001    5
SH601326    5
SH601872    5
SH603877    5
SZ000006    5
SZ000536    5
SZ000727    5
SZ000761    5
SZ000766    5
SZ000980    4
SZ002049    5
SZ002065    5
SZ002176    5
SZ002180    5
SZ002358    5
SZ002366    5
SZ002384    5
SZ002426    5
SZ002437    5
SZ002482    5
SZ002573    5
SZ002672    5
SZ002812    5
SZ300002    5
SZ300159    5
SZ300197    5
SZ300199    5
SZ300297    5
SZ300308    5
SZ300383    5
SZ300529    5
Name: Date, dtype: int64

'------------------IC out-to-bottom---------------------------'

  index  average cumulative alpha  size
0    IC                -26.796462    42

24
76

24

24

Symbol
SH600529    5
SH600667    5
SH603605    5
SZ000540    5
SZ000708    5
SZ000800    5
SZ001914    5
SZ002080    5
SZ002138    5
SZ002156    5
SZ002185    5
SZ002396    5
SZ002511    5
SZ002557    5
SZ002901    5
SZ300212    5
SZ300271    5
SZ300357    5
SZ300474    5
SZ300482    5
SZ300496    5
SZ300558    5
SZ300595    5
SZ300618    5
Name: Date, dtype: int64

'------------------CSI1000 out-to-top---------------------------'

     index  average cumulative alpha  size
0  CSI1000                218.978179    24

76

75

Symbol
SH600012    5
SH600067    5
SH600106    5
SH600231    5
SH600255    5
           ..
SZ300410    5
SZ300450    5
SZ300740    5
SZ300759    5
SZ300782    5
Name: Date, Length: 75, dtype: int64

'------------------CSI1000 out-to-bottom---------------------------'

     index  average cumulative alpha  size
0  CSI1000                 -59.66625    76

77
51

77

77

Symbol
SH600157    5
SH600246    5
SH600267    5
SH600393    5
SH600395    5
           ..
SZ300659    5
SZ300663    5
SZ300672    5
SZ300709    5
SZ300762    5
Name: Date, Length: 77, dtype: int64

'------------------CSIRest out-to-top---------------------------'

     index  average cumulative alpha  size
0  CSIRest               -161.063084    77

51

51

Symbol
SH600083    5
SH600122    5
SH600212    5
SH600215    5
SH600225    5
SH600241    5
SH600243    5
SH600280    5
SH600306    5
SH600311    5
SH600358    5
SH600416    5
SH600470    5
SH600530    5
SH600555    5
SH600651    5
SH600821    5
SH600836    5
SH600892    5
SH600898    5
SH603389    5
SZ000017    5
SZ000509    5
SZ000587    5
SZ000595    5
SZ000663    5
SZ000669    5
SZ000673    5
SZ000679    5
SZ000780    5
SZ000803    5
SZ000837    5
SZ000890    5
SZ002052    5
SZ002076    5
SZ002077    5
SZ002247    5
SZ002255    5
SZ002319    5
SZ002354    5
SZ002418    5
SZ002496    5
SZ002502    5
SZ002513    5
SZ002529    5
SZ002535    5
SZ002575    4
SZ002700    5
SZ002719    5
SZ300008    5
SZ300431    4
Name: Date, dtype: int64

'------------------CSIRest out-to-bottom---------------------------'

     index  average cumulative alpha  size
0  CSIRest               -241.957083    51

In [46]:
# real result
import pandas as pd
import matplotlib as mpl
import glob
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats
import matplotlib.dates as mdates
import math
from scipy import stats
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm
from pandas.plotting import register_matplotlib_converters
register_matplotlib_converters()
from datetime import timedelta
import calendar
import seaborn as sns

sd = 20200623
ed = 20200701


# IF out
kk = pd.read_csv(r"D:\work\project 4 event study - minute\IF_out_202006.csv", encoding="GBK")
da_ta = pd.read_csv('E:\\new_beta_300.csv', encoding="utf-8")
test = da_ta[da_ta["Symbol"].isin(kk["StockID"])]
display(kk.shape[0])
display(len(test[(test["Date"]>=sd) & (test["Date"]<=ed)]["Symbol"].unique()))
display(test[(test["Date"]>=sd) & (test["Date"]<=ed)].groupby("Symbol")["Date"].count())
re = test[(test["Date"]>=sd) & (test["Date"]<=ed)].groupby("Symbol")["alpha"].sum().reset_index().mean().reset_index()
re = re.rename(columns={0:"average cumulative alpha"})
re["index"] = "IF"
re["size"] = 21
display("---------------------IF out--------------------------")
display(re)

k = pd.read_csv(r"D:\work\project 4 event study - minute\IF_in_202006.csv", encoding="GBK")
k1 = pd.read_csv(r"D:\work\project 4 event study - minute\IC_in_202006.csv", encoding="GBK")
k2 = pd.read_csv(r"D:\work\project 4 event study - minute\CSI1000_in_202006.csv", encoding="GBK")

# IC out-to-top
kk1 = pd.read_csv(r"D:\work\project 4 event study - minute\IC_out_202006.csv", encoding="GBK")
list1 = list(set(kk1["StockID"]) & set(k["StockID"]))
list2 = list(set(kk1["StockID"]) - set(list1))
print(len(list1))
print(len(list2))

kk1 = pd.read_csv(r"D:\work\project 4 event study - minute\IC_out_202006.csv", encoding="GBK")
da_ta = pd.read_csv('E:\\new_beta_500.csv', encoding="utf-8")
kk1 = kk1[kk1["StockID"].isin(list1)]
test = da_ta[da_ta["Symbol"].isin(kk1["StockID"])]
display(kk1.shape[0])
display(len(test[(test["Date"]>=sd) & (test["Date"]<=ed)]["Symbol"].unique()))
display(test[(test["Date"]>=sd) & (test["Date"]<=ed)].groupby("Symbol")["Date"].count())
re1 = test[(test["Date"]>=sd) & (test["Date"]<=ed)].groupby("Symbol")["alpha"].sum().reset_index().mean().reset_index()
re1 = re1.rename(columns={0:"average cumulative alpha"})
re1["average cumulative alpha"] = re1["average cumulative alpha"]*10000
re1["index"] = "IC"
re1["size"] = 8
display("----------------------IC out-to-top---------------------------")
display(re1)

# IC out-to-bottom
kk1 = pd.read_csv(r"D:\work\project 4 event study - minute\IC_out_202006.csv", encoding="GBK")
da_ta = pd.read_csv('E:\\new_beta_500.csv', encoding="utf-8")
kk1 = kk1[kk1["StockID"].isin(list2)]
test = da_ta[da_ta["Symbol"].isin(kk1["StockID"])]
display(kk1.shape[0])
display(len(test[(test["Date"]>=sd) & (test["Date"]<=ed)]["Symbol"].unique()))
display(test[(test["Date"]>=sd) & (test["Date"]<=ed)].groupby("Symbol")["Date"].count())
re1 = test[(test["Date"]>=sd) & (test["Date"]<=ed)].groupby("Symbol")["alpha"].sum().reset_index().mean().reset_index()
re1 = re1.rename(columns={0:"average cumulative alpha"})
re1["average cumulative alpha"] = re1["average cumulative alpha"]*10000
re1["index"] = "IC"
re1["size"] = 42
display("------------------IC out-to-bottom---------------------------")
display(re1)

# CSI1000 out-to-top
kk2 = pd.read_csv(r"D:\work\project 4 event study - minute\CSI1000_out_202006.csv", encoding="GBK")
list1 = list((set(kk2["StockID"]) & set(k["StockID"]))|(set(kk2["StockID"]) & set(k1["StockID"])))
list2 = list(set(kk2["StockID"]) - set(list1))
print(len(list1))
print(len(list2))

kk2 = pd.read_csv(r"D:\work\project 4 event study - minute\CSI1000_out_202006.csv", encoding="GBK")
da_ta = pd.read_csv('E:\\new_beta_1000.csv', encoding="utf-8")
kk2 = kk2[kk2["StockID"].isin(list1)]
test = da_ta[da_ta["Symbol"].isin(kk2["StockID"])]
display(kk2.shape[0])
display(len(test[(test["Date"]>=sd) & (test["Date"]<=ed)]["Symbol"].unique()))
display(test[(test["Date"]>=sd) & (test["Date"]<=ed)].groupby("Symbol")["Date"].count())
re2 = test[(test["Date"]>=sd) & (test["Date"]<=ed)].groupby("Symbol")["alpha"].sum().reset_index().mean().reset_index()
re2 = re2.rename(columns={0:"average cumulative alpha"})
re2["average cumulative alpha"] = re2["average cumulative alpha"]*10000
re2["index"] = "CSI1000"
re2["size"] = 29
display("------------------CSI1000 out-to-top---------------------------")
display(re2)

#CSI1000 out-to-bottom
kk2 = pd.read_csv(r"D:\work\project 4 event study - minute\CSI1000_out_202006.csv", encoding="GBK")
da_ta = pd.read_csv('E:\\new_beta_1000.csv', encoding="utf-8")
kk2 = kk2[kk2["StockID"].isin(list2)]
test = da_ta[da_ta["Symbol"].isin(kk2["StockID"])]
display(kk2.shape[0])
display(len(test[(test["Date"]>=sd) & (test["Date"]<=ed)]["Symbol"].unique()))
display(test[(test["Date"]>=sd) & (test["Date"]<=ed)].groupby("Symbol")["Date"].count())
re2 = test[(test["Date"]>=sd) & (test["Date"]<=ed)].groupby("Symbol")["alpha"].sum().reset_index().mean().reset_index()
re2 = re2.rename(columns={0:"average cumulative alpha"})
re2["average cumulative alpha"] = re2["average cumulative alpha"]*10000
re2["index"] = "CSI1000"
re2["size"] = 71
display("------------------CSI1000 out-to-bottom---------------------------")
display(re2)

# CSIRest out-to-top
kk3 = pd.read_csv(r"D:\work\project 4 event study - minute\new\CSIRest_out_202006.csv", encoding="GBK")
list1 = list((set(kk3["StockID"]) & set(k["StockID"]))|(set(kk3["StockID"]) & set(k1["StockID"]))|(set(kk3["StockID"]) & set(k2["StockID"])))
list2 = list(set(kk3["StockID"]) - set(list1))
print(len(list1))
print(len(list2))

kk3 = pd.read_csv(r"D:\work\project 4 event study - minute\new\CSIRest_out_202006.csv", encoding="GBK")
da_ta = pd.read_csv('E:\\new_beta_CSI.csv', encoding="utf-8")
kk3 = kk3[kk3["StockID"].isin(list1)]
test = da_ta[da_ta["Symbol"].isin(kk3["StockID"])]
display(kk3.shape[0])
display(len(test[(test["Date"]>=sd) & (test["Date"]<=ed)]["Symbol"].unique()))
display(test[(test["Date"]>=sd) & (test["Date"]<=ed)].groupby("Symbol")["Date"].count())
re3 = test[(test["Date"]>=sd) & (test["Date"]<=ed)].groupby("Symbol")["alpha"].sum().reset_index().mean().reset_index()
re3 = re3.rename(columns={0:"average cumulative alpha"})
re3["average cumulative alpha"] = re3["average cumulative alpha"]*10000
re3["index"] = "CSIRest"
re3["size"] = 77
display("------------------CSIRest out-to-top---------------------------")
display(re3)

#CSIRest out-to-bottom
kk3 = pd.read_csv(r"D:\work\project 4 event study - minute\new\CSIRest_out_202006.csv", encoding="GBK")
da_ta = pd.read_csv('E:\\new_beta_CSI.csv', encoding="utf-8")
kk3 = kk3[kk3["StockID"].isin(list2)]
test = da_ta[da_ta["Symbol"].isin(kk3["StockID"])]
display(kk3.shape[0])
display(len(test[(test["Date"]>=sd) & (test["Date"]<=ed)]["Symbol"].unique()))
display(test[(test["Date"]>=sd) & (test["Date"]<=ed)].groupby("Symbol")["Date"].count())
re3 = test[(test["Date"]>=sd) & (test["Date"]<=ed)].groupby("Symbol")["alpha"].sum().reset_index().mean().reset_index()
re3 = re3.rename(columns={0:"average cumulative alpha"})
re3["average cumulative alpha"] = re3["average cumulative alpha"]*10000
re3["index"] = "CSIRest"
re3["size"] = 81
display("------------------CSIRest out-to-bottom---------------------------")
display(re3)

21

21

Symbol
SH600023    5
SH600100    5
SH600153    5
SH600535    5
SH600566    5
SH600663    5
SH600733    5
SH600816    5
SZ000413    5
SZ000415    5
SZ000423    5
SZ000629    5
SZ000630    5
SZ000898    5
SZ002010    5
SZ002081    5
SZ002294    5
SZ002411    5
SZ300017    5
SZ300024    5
SZ300070    5
Name: Date, dtype: int64

'---------------------IF out--------------------------'

  index  average cumulative alpha  size
0    IF                 -0.021463    21

8
42

8

8

Symbol
SH600745    5
SH601100    5
SH601231    5
SZ000066    5
SZ002129    5
SZ002371    5
SZ002463    5
SZ300014    5
Name: Date, dtype: int64

'----------------------IC out-to-top---------------------------'

  index  average cumulative alpha  size
0    IC                199.953844     8

42

41

Symbol
SH600098    5
SH600150    5
SH600499    5
SH600536    5
SH600584    5
SH600759    5
SH600763    5
SH600939    5
SH601001    5
SH601326    5
SH601872    5
SH603877    5
SZ000006    5
SZ000426    5
SZ000536    5
SZ000727    5
SZ000761    5
SZ000766    5
SZ000980    4
SZ002049    5
SZ002065    5
SZ002176    5
SZ002180    5
SZ002280    4
SZ002358    5
SZ002366    5
SZ002384    5
SZ002426    5
SZ002437    5
SZ002482    5
SZ002573    5
SZ002672    5
SZ002681    5
SZ002812    5
SZ300027    5
SZ300159    5
SZ300199    5
SZ300297    5
SZ300308    5
SZ300383    5
SZ300529    5
Name: Date, dtype: int64

'------------------IC out-to-bottom---------------------------'

  index  average cumulative alpha  size
0    IC                -11.968898    42

29
71

29

29

Symbol
SH600529    5
SH600667    5
SH603605    5
SZ000708    5
SZ000739    5
SZ000800    5
SZ001914    5
SZ002080    5
SZ002124    5
SZ002138    5
SZ002156    5
SZ002185    5
SZ002396    5
SZ002429    5
SZ002458    5
SZ002511    5
SZ002557    5
SZ002648    5
SZ002901    5
SZ300212    5
SZ300271    5
SZ300357    5
SZ300474    5
SZ300482    5
SZ300496    5
SZ300558    5
SZ300595    5
SZ300618    5
SZ300630    5
Name: Date, dtype: int64

'------------------CSI1000 out-to-top---------------------------'

     index  average cumulative alpha  size
0  CSI1000                204.021778    29

71

70

Symbol
SH600012    5
SH600067    5
SH600106    5
SH600146    4
SH600172    5
           ..
SZ300410    5
SZ300450    5
SZ300467    5
SZ300759    5
SZ300782    5
Name: Date, Length: 70, dtype: int64

'------------------CSI1000 out-to-bottom---------------------------'

     index  average cumulative alpha  size
0  CSI1000                -93.706686    71

77
81

77

77

Symbol
SH600246    5
SH600267    5
SH600510    5
SH600675    5
SH600882    5
           ..
SZ300659    5
SZ300663    5
SZ300672    5
SZ300709    5
SZ300762    5
Name: Date, Length: 77, dtype: int64

'------------------CSIRest out-to-top---------------------------'

     index  average cumulative alpha  size
0  CSIRest               -177.600016    77

81

81

Symbol
SH600083    5
SH600086    4
SH600122    5
SH600212    5
SH600215    5
           ..
SZ300426    5
SZ300431    4
SZ300460    5
SZ300461    5
SZ300466    5
Name: Date, Length: 81, dtype: int64

'------------------CSIRest out-to-bottom---------------------------'

     index  average cumulative alpha  size
0  CSIRest               -356.554411    81

## IN version

In [58]:
# predict result
import pandas as pd
import matplotlib as mpl
import glob
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats
import matplotlib.dates as mdates
import math
from scipy import stats
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm
from pandas.plotting import register_matplotlib_converters
register_matplotlib_converters()
from datetime import timedelta
import calendar
import seaborn as sns

sd = 20200623
ed = 20200701


# IF in
kk = pd.read_csv(r"D:\work\project 3 event study\IF_in_202006.csv", encoding="GBK")
da_ta = pd.read_csv('E:\\new_beta_300.csv', encoding="utf-8")
test = da_ta[da_ta["Symbol"].isin(kk["Symbol"])]
display(kk.shape[0])
display(len(test[(test["Date"]>=sd) & (test["Date"]<=ed)]["Symbol"].unique()))
display(test[(test["Date"]>=sd) & (test["Date"]<=ed)].groupby("Symbol")["Date"].count())
re = test[(test["Date"]>=sd) & (test["Date"]<=ed)].groupby("Symbol")["alpha"].sum().reset_index().mean().reset_index()
re = re.rename(columns={0:"average cumulative alpha"})
re["index"] = "IF"
re["size"] = 22
display("---------------------IF out--------------------------")
display(re)

k = pd.read_csv(r"D:\work\project 3 event study\IF_out_202006.csv", encoding="GBK")
k1 = pd.read_csv(r"D:\work\project 3 event study\IC_out_202006.csv", encoding="GBK")
k2 = pd.read_csv(r"D:\work\project 3 event study\CSI1000_out_202006.csv", encoding="GBK")

# IC in-from-top
kk1 = pd.read_csv(r"D:\work\project 3 event study\IC_in_202006.csv", encoding="GBK")
list1 = list(set(kk1["Symbol"]) & set(k["Symbol"]))
list2 = list(set(kk1["Symbol"]) - set(list1))
print(len(list1))
print(len(list2))

kk1 = pd.read_csv(r"D:\work\project 3 event study\IC_in_202006.csv", encoding="GBK")
da_ta = pd.read_csv('E:\\new_beta_500.csv', encoding="utf-8")
kk1 = kk1[kk1["Symbol"].isin(list1)]
test = da_ta[da_ta["Symbol"].isin(kk1["Symbol"])]
display(kk1.shape[0])
display(len(test[(test["Date"]>=sd) & (test["Date"]<=ed)]["Symbol"].unique()))
display(test[(test["Date"]>=sd) & (test["Date"]<=ed)].groupby("Symbol")["Date"].count())
re1 = test[(test["Date"]>=sd) & (test["Date"]<=ed)].groupby("Symbol")["alpha"].sum().reset_index().mean().reset_index()
re1 = re1.rename(columns={0:"average cumulative alpha"})
re1["average cumulative alpha"] = re1["average cumulative alpha"]*10000
re1["index"] = "IC"
re1["size"] = 17
display("----------------------IC in-from-top---------------------------")
display(re1)

# IC in-from-bottom
kk1 = pd.read_csv(r"D:\work\project 3 event study\IC_in_202006.csv", encoding="GBK")
da_ta = pd.read_csv('E:\\new_beta_500.csv', encoding="utf-8")
kk1 = kk1[kk1["Symbol"].isin(list2)]
test = da_ta[da_ta["Symbol"].isin(kk1["Symbol"])]
display(kk1.shape[0])
display(len(test[(test["Date"]>=sd) & (test["Date"]<=ed)]["Symbol"].unique()))
display(test[(test["Date"]>=sd) & (test["Date"]<=ed)].groupby("Symbol")["Date"].count())
re1 = test[(test["Date"]>=sd) & (test["Date"]<=ed)].groupby("Symbol")["alpha"].sum().reset_index().mean().reset_index()
re1 = re1.rename(columns={0:"average cumulative alpha"})
re1["average cumulative alpha"] = re1["average cumulative alpha"]*10000
re1["index"] = "IC"
re1["size"] = 33
display("------------------IC in-from-bottom---------------------------")
display(re1)

# CSI1000 in-from-top
kk2 = pd.read_csv(r"D:\work\project 3 event study\CSI1000_in_202006.csv", encoding="GBK")
list1 = list((set(kk2["Symbol"]) & set(k["Symbol"]))|(set(kk2["Symbol"]) & set(k1["Symbol"])))
list2 = list(set(kk2["Symbol"]) - set(list1))
print(len(list1))
print(len(list2))

kk2 = pd.read_csv(r"D:\work\project 3 event study\CSI1000_in_202006.csv", encoding="GBK")
da_ta = pd.read_csv('E:\\new_beta_1000.csv', encoding="utf-8")
kk2 = kk2[kk2["Symbol"].isin(list1)]
test = da_ta[da_ta["Symbol"].isin(kk2["Symbol"])]
display(kk2.shape[0])
display(len(test[(test["Date"]>=sd) & (test["Date"]<=ed)]["Symbol"].unique()))
display(test[(test["Date"]>=sd) & (test["Date"]<=ed)].groupby("Symbol")["Date"].count())
re2 = test[(test["Date"]>=sd) & (test["Date"]<=ed)].groupby("Symbol")["alpha"].sum().reset_index().mean().reset_index()
re2 = re2.rename(columns={0:"average cumulative alpha"})
re2["average cumulative alpha"] = re2["average cumulative alpha"]*10000
re2["index"] = "CSI1000"
re2["size"] = 11
display("------------------CSI1000 in-from-top---------------------------")
display(re2)

#CSI1000 in-from-bottom
kk2 = pd.read_csv(r"D:\work\project 3 event study\CSI1000_in_202006.csv", encoding="GBK")
da_ta = pd.read_csv('E:\\new_beta_1000.csv', encoding="utf-8")
kk2 = kk2[kk2["Symbol"].isin(list2)]
test = da_ta[da_ta["Symbol"].isin(kk2["Symbol"])]
display(kk2.shape[0])
display(len(test[(test["Date"]>=sd) & (test["Date"]<=ed)]["Symbol"].unique()))
display(test[(test["Date"]>=sd) & (test["Date"]<=ed)].groupby("Symbol")["Date"].count())
re2 = test[(test["Date"]>=sd) & (test["Date"]<=ed)].groupby("Symbol")["alpha"].sum().reset_index().mean().reset_index()
re2 = re2.rename(columns={0:"average cumulative alpha"})
re2["average cumulative alpha"] = re2["average cumulative alpha"]*10000
re2["index"] = "CSI1000"
re2["size"] = 89
display("------------------CSI1000 in-from-bottom---------------------------")
display(re2)

22

22

Symbol
SH600745    5
SH601077    5
SH601100    5
SH601231    5
SH601658    5
SH601816    5
SH601916    5
SH603369    5
SH603658    5
SZ000066    5
SZ000708    5
SZ000860    5
SZ000977    5
SZ002129    5
SZ002157    5
SZ002371    5
SZ002463    5
SZ002600    5
SZ003816    5
SZ300014    5
SZ300601    5
SZ300628    5
Name: Date, dtype: int64

'---------------------IF out--------------------------'

  index  average cumulative alpha  size
0    IF                 -0.019351    22

17
33

17

17

Symbol
SH600153    5
SH600372    5
SH600535    5
SH600566    5
SH600733    5
SH601216    5
SZ000415    5
SZ000629    5
SZ000630    5
SZ000898    5
SZ002010    5
SZ002081    5
SZ002294    5
SZ002411    5
SZ300017    5
SZ300024    5
SZ300070    5
Name: Date, dtype: int64

'----------------------IC in-from-top---------------------------'

  index  average cumulative alpha  size
0    IC                -69.995681    17

33

33

Symbol
SH600157    5
SH600529    5
SH600667    5
SH600675    5
SH601512    5
SH603290    5
SH603605    5
SH603786    5
SH603927    5
SZ000046    5
SZ000540    5
SZ000785    5
SZ000800    5
SZ001914    5
SZ002080    5
SZ002138    5
SZ002156    5
SZ002185    5
SZ002396    5
SZ002506    5
SZ002511    5
SZ002557    5
SZ002563    5
SZ002901    5
SZ300212    5
SZ300271    5
SZ300357    5
SZ300474    5
SZ300482    5
SZ300496    5
SZ300558    5
SZ300595    5
SZ300618    5
Name: Date, dtype: int64

'------------------IC in-from-bottom---------------------------'

  index  average cumulative alpha  size
0    IC                117.076203    33

11
89

11

11

Symbol
SH600499    5
SH600584    5
SH600759    5
SH600770    5
SH601001    5
SZ000006    5
SZ002065    5
SZ002358    5
SZ002482    5
SZ002573    5
SZ002672    5
Name: Date, dtype: int64

'------------------CSI1000 in-from-top---------------------------'

     index  average cumulative alpha  size
0  CSI1000                 60.688947    11

89

89

Symbol
SH600246    5
SH600267    5
SH600393    5
SH600395    5
SH600510    5
           ..
SZ300799    5
SZ300800    5
SZ300803    5
SZ300805    5
SZ300815    5
Name: Date, Length: 89, dtype: int64

'------------------CSI1000 in-from-bottom---------------------------'

     index  average cumulative alpha  size
0  CSI1000                 -4.531224    89

In [60]:
# real result
import pandas as pd
import matplotlib as mpl
import glob
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats
import matplotlib.dates as mdates
import math
from scipy import stats
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm
from pandas.plotting import register_matplotlib_converters
register_matplotlib_converters()
from datetime import timedelta
import calendar
import seaborn as sns

sd = 20200623
ed = 20200701


# IF in
kk = pd.read_csv(r"D:\work\project 4 event study - minute\IF_in_202006.csv", encoding="GBK")
da_ta = pd.read_csv('E:\\new_beta_300.csv', encoding="utf-8")
test = da_ta[da_ta["Symbol"].isin(kk["StockID"])]
display(kk.shape[0])
display(len(test[(test["Date"]>=sd) & (test["Date"]<=ed)]["Symbol"].unique()))
display(test[(test["Date"]>=sd) & (test["Date"]<=ed)].groupby("Symbol")["Date"].count())
re = test[(test["Date"]>=sd) & (test["Date"]<=ed)].groupby("Symbol")["alpha"].sum().reset_index().mean().reset_index()
re = re.rename(columns={0:"average cumulative alpha"})
re["index"] = "IF"
re["size"] = 21
display("---------------------IF in--------------------------")
display(re)

k = pd.read_csv(r"D:\work\project 4 event study - minute\IF_out_202006.csv", encoding="GBK")
k1 = pd.read_csv(r"D:\work\project 4 event study - minute\IC_out_202006.csv", encoding="GBK")
k2 = pd.read_csv(r"D:\work\project 4 event study - minute\CSI1000_out_202006.csv", encoding="GBK")

# IC in-from-top
kk1 = pd.read_csv(r"D:\work\project 4 event study - minute\IC_in_202006.csv", encoding="GBK")
list1 = list(set(kk1["StockID"]) & set(k["StockID"]))
list2 = list(set(kk1["StockID"]) - set(list1))
print(len(list1))
print(len(list2))

kk1 = pd.read_csv(r"D:\work\project 4 event study - minute\IC_in_202006.csv", encoding="GBK")
da_ta = pd.read_csv('E:\\new_beta_500.csv', encoding="utf-8")
kk1 = kk1[kk1["StockID"].isin(list1)]
test = da_ta[da_ta["Symbol"].isin(kk1["StockID"])]
display(kk1.shape[0])
display(len(test[(test["Date"]>=sd) & (test["Date"]<=ed)]["Symbol"].unique()))
display(test[(test["Date"]>=sd) & (test["Date"]<=ed)].groupby("Symbol")["Date"].count())
re1 = test[(test["Date"]>=sd) & (test["Date"]<=ed)].groupby("Symbol")["alpha"].sum().reset_index().mean().reset_index()
re1 = re1.rename(columns={0:"average cumulative alpha"})
re1["average cumulative alpha"] = re1["average cumulative alpha"]*10000
re1["index"] = "IC"
re1["size"] = 14
display("----------------------IC in-from-top---------------------------")
display(re1)

# IC in-from-bottom
kk1 = pd.read_csv(r"D:\work\project 4 event study - minute\IC_in_202006.csv", encoding="GBK")
da_ta = pd.read_csv('E:\\new_beta_500.csv', encoding="utf-8")
kk1 = kk1[kk1["StockID"].isin(list2)]
test = da_ta[da_ta["Symbol"].isin(kk1["StockID"])]
display(kk1.shape[0])
display(len(test[(test["Date"]>=sd) & (test["Date"]<=ed)]["Symbol"].unique()))
display(test[(test["Date"]>=sd) & (test["Date"]<=ed)].groupby("Symbol")["Date"].count())
re1 = test[(test["Date"]>=sd) & (test["Date"]<=ed)].groupby("Symbol")["alpha"].sum().reset_index().mean().reset_index()
re1 = re1.rename(columns={0:"average cumulative alpha"})
re1["average cumulative alpha"] = re1["average cumulative alpha"]*10000
re1["index"] = "IC"
re1["size"] = 36
display("------------------IC in-from-bottom---------------------------")
display(re1)

# CSI1000 in-from-top
kk2 = pd.read_csv(r"D:\work\project 4 event study - minute\CSI1000_in_202006.csv", encoding="GBK")
list1 = list((set(kk2["StockID"]) & set(k["StockID"]))|(set(kk2["StockID"]) & set(k1["StockID"])))
list2 = list(set(kk2["StockID"]) - set(list1))
print(len(list1))
print(len(list2))

kk2 = pd.read_csv(r"D:\work\project 4 event study - minute\CSI1000_in_202006.csv", encoding="GBK")
da_ta = pd.read_csv('E:\\new_beta_1000.csv', encoding="utf-8")
kk2 = kk2[kk2["StockID"].isin(list1)]
test = da_ta[da_ta["Symbol"].isin(kk2["StockID"])]
display(kk2.shape[0])
display(len(test[(test["Date"]>=sd) & (test["Date"]<=ed)]["Symbol"].unique()))
display(test[(test["Date"]>=sd) & (test["Date"]<=ed)].groupby("Symbol")["Date"].count())
re2 = test[(test["Date"]>=sd) & (test["Date"]<=ed)].groupby("Symbol")["alpha"].sum().reset_index().mean().reset_index()
re2 = re2.rename(columns={0:"average cumulative alpha"})
re2["average cumulative alpha"] = re2["average cumulative alpha"]*10000
re2["index"] = "CSI1000"
re2["size"] = 9
display("------------------CSI1000 in-from-top---------------------------")
display(re2)

#CSI1000 in-from-bottom
kk2 = pd.read_csv(r"D:\work\project 4 event study - minute\CSI1000_in_202006.csv", encoding="GBK")
da_ta = pd.read_csv('E:\\new_beta_1000.csv', encoding="utf-8")
kk2 = kk2[kk2["StockID"].isin(list2)]
test = da_ta[da_ta["Symbol"].isin(kk2["StockID"])]
display(kk2.shape[0])
display(len(test[(test["Date"]>=sd) & (test["Date"]<=ed)]["Symbol"].unique()))
display(test[(test["Date"]>=sd) & (test["Date"]<=ed)].groupby("Symbol")["Date"].count())
re2 = test[(test["Date"]>=sd) & (test["Date"]<=ed)].groupby("Symbol")["alpha"].sum().reset_index().mean().reset_index()
re2 = re2.rename(columns={0:"average cumulative alpha"})
re2["average cumulative alpha"] = re2["average cumulative alpha"]*10000
re2["index"] = "CSI1000"
re2["size"] = 91
display("------------------CSI1000 in-from-bottom---------------------------")
display(re2)

# CSIRest in-from-top
kk3 = pd.read_csv(r"D:\work\project 4 event study - minute\new\CSIRest_in_202006.csv", encoding="GBK")
list1 = list((set(kk3["StockID"]) & set(k["StockID"]))|(set(kk3["StockID"]) & set(k1["StockID"]))|(set(kk3["StockID"]) & set(k2["StockID"])))
list2 = list(set(kk3["StockID"]) - set(list1))
print(len(list1))
print(len(list2))

kk3 = pd.read_csv(r"D:\work\project 4 event study - minute\new\CSIRest_in_202006.csv", encoding="GBK")
da_ta = pd.read_csv('E:\\new_beta_CSI.csv', encoding="utf-8")
kk3 = kk3[kk3["StockID"].isin(list1)]
test = da_ta[da_ta["Symbol"].isin(kk3["StockID"])]
display(kk3.shape[0])
display(len(test[(test["Date"]>=sd) & (test["Date"]<=ed)]["Symbol"].unique()))
display(test[(test["Date"]>=sd) & (test["Date"]<=ed)].groupby("Symbol")["Date"].count())
re3 = test[(test["Date"]>=sd) & (test["Date"]<=ed)].groupby("Symbol")["alpha"].sum().reset_index().mean().reset_index()
re3 = re3.rename(columns={0:"average cumulative alpha"})
re3["average cumulative alpha"] = re3["average cumulative alpha"]*10000
re3["index"] = "CSIRest"
re3["size"] = 79
display("------------------CSIRest in-from-top---------------------------")
display(re3)

#CSIRest in-from-bottom
kk3 = pd.read_csv(r"D:\work\project 4 event study - minute\new\CSIRest_in_202006.csv", encoding="GBK")
da_ta = pd.read_csv('E:\\new_beta_CSI.csv', encoding="utf-8")
kk3 = kk3[kk3["StockID"].isin(list2)]
test = da_ta[da_ta["Symbol"].isin(kk3["StockID"])]
display(kk3.shape[0])
display(len(test[(test["Date"]>=sd) & (test["Date"]<=ed)]["Symbol"].unique()))
display(test[(test["Date"]>=sd) & (test["Date"]<=ed)].groupby("Symbol")["Date"].count())
re3 = test[(test["Date"]>=sd) & (test["Date"]<=ed)].groupby("Symbol")["alpha"].sum().reset_index().mean().reset_index()
re3 = re3.rename(columns={0:"average cumulative alpha"})
re3["average cumulative alpha"] = re3["average cumulative alpha"]*10000
re3["index"] = "CSIRest"
re3["size"] = 34
display("------------------CSIRest in-from-bottom---------------------------")
display(re3)

21

21

Symbol
SH600745    5
SH601077    5
SH601100    5
SH601231    5
SH601658    5
SH601816    5
SH601916    5
SH603369    5
SH603658    5
SZ000066    5
SZ000708    5
SZ000860    5
SZ000977    5
SZ002129    5
SZ002157    5
SZ002371    5
SZ002463    5
SZ003816    5
SZ300014    5
SZ300601    5
SZ300628    5
Name: Date, dtype: int64

'---------------------IF in--------------------------'

  index  average cumulative alpha  size
0    IF                 -0.014808    21

14
36

14

14

Symbol
SH600153    5
SH600535    5
SH600566    5
SH600733    5
SZ000415    5
SZ000629    5
SZ000630    5
SZ000898    5
SZ002010    5
SZ002081    5
SZ002294    5
SZ300017    5
SZ300024    5
SZ300070    5
Name: Date, dtype: int64

'----------------------IC in-from-top---------------------------'

  index  average cumulative alpha  size
0    IC                  3.188235    14

36

36

Symbol
SH600529    5
SH600667    5
SH600675    5
SH601512    5
SH603605    5
SH603786    5
SZ000046    5
SZ000739    5
SZ000785    5
SZ000800    5
SZ001914    5
SZ002080    5
SZ002124    5
SZ002138    5
SZ002156    5
SZ002185    5
SZ002396    5
SZ002429    5
SZ002458    5
SZ002506    5
SZ002511    5
SZ002557    5
SZ002563    5
SZ002595    5
SZ002648    5
SZ002901    5
SZ300212    5
SZ300271    5
SZ300357    5
SZ300474    5
SZ300482    5
SZ300496    5
SZ300558    5
SZ300595    5
SZ300618    5
SZ300630    5
Name: Date, dtype: int64

'------------------IC in-from-bottom---------------------------'

  index  average cumulative alpha  size
0    IC                138.917388    36

9
91

9

9

Symbol
SH600499    5
SH600759    5
SH601001    5
SZ000006    5
SZ002065    5
SZ002358    5
SZ002482    5
SZ002573    5
SZ002672    5
Name: Date, dtype: int64

'------------------CSI1000 in-from-top---------------------------'

     index  average cumulative alpha  size
0  CSI1000                101.869503     9

91

91

Symbol
SH600246    5
SH600267    5
SH600510    5
SH600882    5
SH600965    5
           ..
SZ300799    5
SZ300800    5
SZ300803    5
SZ300805    5
SZ300815    5
Name: Date, Length: 91, dtype: int64

'------------------CSI1000 in-from-bottom---------------------------'

     index  average cumulative alpha  size
0  CSI1000                -42.034477    91

79
34

79

78

Symbol
SH600012    5
SH600023    5
SH600067    5
SH600098    5
SH600100    5
           ..
SZ300410    5
SZ300450    5
SZ300529    5
SZ300759    5
SZ300782    5
Name: Date, Length: 78, dtype: int64

'------------------CSIRest in-from-top---------------------------'

     index  average cumulative alpha  size
0  CSIRest               -143.945134    79

34

34

Symbol
SH600615    5
SH603109    5
SH603115    5
SH603662    5
SH603755    5
SH603810    5
SH603995    5
SZ000048    5
SZ000893    5
SZ002963    5
SZ002965    5
SZ002966    5
SZ002968    5
SZ002971    5
SZ002972    5
SZ300093    5
SZ300564    5
SZ300787    5
SZ300789    5
SZ300790    5
SZ300791    5
SZ300795    5
SZ300796    5
SZ300797    5
SZ300801    5
SZ300802    5
SZ300806    5
SZ300807    5
SZ300808    5
SZ300809    5
SZ300810    5
SZ300811    5
SZ300812    5
SZ300813    5
Name: Date, dtype: int64

'------------------CSIRest in-from-bottom---------------------------'

     index  average cumulative alpha  size
0  CSIRest                  3.042805    34