### 1. SH completeness check result

In [21]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import pickle
from matplotlib import pyplot as plt
import statsmodels.api as sm
from matplotlib.ticker import Formatter
import collections
from decimal import Decimal, getcontext, ROUND_HALF_UP
logSH = pd.read_csv(r'F:\data\20200831\logs_20200831_zt_88_03_day_88data\mdLog_SH_20200831_0902.csv',
                    encoding="utf-8").loc[:, ["clockAtArrival", "sequenceNo", "source", "StockID",
                                               "exchange", "time", "cum_volume", "cum_amount", "close",
                                               "bid1p", "bid2p", "bid3p", "bid4p", "bid5p", "bid1q",
                                               "bid2q", "bid3q", "bid4q", "bid5q", "ask1p", "ask2p",
                                               "ask3p", "ask4p", "ask5p", "ask1q", "ask2q", "ask3q",
                                               "ask4q", "ask5q", "openPrice", "numTrades"]]
logSH1 = pd.read_csv(r'F:\data\20200831\full_20200831_zt_70_01_day_test0831\mdLog_SH_20200831_0856.csv',
                    encoding="utf-8").loc[:, ["clockAtArrival", "sequenceNo", "source", "StockID",
                                               "exchange", "time", "cum_volume", "cum_amount", "close",
                                               "bid1p", "bid2p", "bid3p", "bid4p", "bid5p", "bid1q",
                                               "bid2q", "bid3q", "bid4q", "bid5q", "ask1p", "ask2p",
                                               "ask3p", "ask4p", "ask5p", "ask1q", "ask2q", "ask3q",
                                               "ask4q", "ask5q", "openPrice", "numTrades"]]
# logSH1 = pd.concat([SH1, SH2])
# # 1. data format
print(logSH["source"].unique())
print("new data source type: ")
print(logSH1["source"].unique())
print(logSH["time"].unique())
print(logSH1["time"].unique())

[22 23]
new data source type:
[25]
['09:01:23.750' '09:01:22.000' '09:01:24.760' ... '15:23:57.090'
 '15:23:58.000' '15:23:57.640']
['08:56:48' '00:00:00' '08:57:48' ... '15:02:01' '15:02:04' '15:02:10']

In [35]:
logSH1 = pd.read_csv(r'F:\data\20200814\full_20200814_zt_70_01_day_7079\mdLog_SH_20200814_1153.csv',
                    encoding="utf-8").loc[:, ["clockAtArrival", "sequenceNo", "source", "StockID",
                                               "exchange", "time", "cum_volume", "cum_amount", "close",
                                               "bid1p", "bid2p", "bid3p", "bid4p", "bid5p", "bid1q",
                                               "bid2q", "bid3q", "bid4q", "bid5q", "ask1p", "ask2p",
                                               "ask3p", "ask4p", "ask5p", "ask1q", "ask2q", "ask3q",
                                               "ask4q", "ask5q", "openPrice"]]
logSH1["time"] = logSH1["time"].apply(lambda x: int(x.replace(':', ""))) * 1000

In [5]:
logSH["time"] = logSH["time"].apply(lambda x: int(x.replace(':', "").replace('.', "")))
logSH1["time"] = logSH1["time"].apply(lambda x: int(x.replace(':', ""))) * 1000

display(logSH[(logSH["StockID"] == 600000) & (logSH["time"] >= 143338000) & (logSH["time"] <= 144800000)])
display(logSH1[(logSH1["StockID"] == 600000) & (logSH1["time"] >= 143300000) & (logSH1["time"] <= 144800000)])

,clockAtArrival,sequenceNo,source,StockID,exchange,time,cum_volume,cum_amount,close,bid1p,...,ask3p,ask4p,ask5p,ask1q,ask2q,ask3q,ask4q,ask5q,openPrice,numTrades
12496260,1598855658257583,199718072,23,600000,SH,143338000,69261444,7.240454e+08,10.35,10.35,...,10.38,10.39,10.4,74300,198300,246100,112600,127600,10.46,23922
12497233,1598855658923636,199725517,22,600000,SH,143338870,69261444,7.240454e+08,10.35,10.35,...,10.38,10.39,10.4,73700,198300,246100,112600,127600,10.46,23922
12499039,1598855661264413,199756720,23,600000,SH,143341000,69270644,7.241407e+08,10.35,10.35,...,10.38,10.39,10.4,69800,198300,246100,112600,127600,10.46,23933
12500004,1598855661928072,199764306,22,600000,SH,143341870,69271244,7.241469e+08,10.35,10.35,...,10.38,10.39,10.4,70600,198300,246100,112600,126500,10.46,23934
12501785,1598855664268855,199795560,23,600000,SH,143344000,69274544,7.241811e+08,10.35,10.35,...,10.38,10.39,10.4,81400,198300,246100,112600,126800,10.46,23937
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13292612,1598856514094195,211279242,22,600000,SH,144753920,73068637,7.634638e+08,10.36,10.35,...,10.38,10.39,10.4,361990,211300,139500,38800,135700,10.46,25364
13294236,1598856516136609,211306596,23,600000,SH,144756000,73101037,7.637992e+08,10.35,10.35,...,10.38,10.39,10.4,361990,211300,139500,38800,135700,10.46,25371
13295406,1598856517102489,211318415,22,600000,SH,144756930,73101337,7.638023e+08,10.35,10.35,...,10.38,10.39,10.4,361990,211300,133800,38800,135700,10.46,25372
13296986,1598856519137639,211346088,23,600000,SH,144759000,73102237,7.638116e+08,10.36,10.35,...,10.38,10.39,10.4,361090,211300,133800,38800,135700,10.46,25373
13298118,1598856520018850,211356333,22,600000,SH,144759930,73102337,7.638126e+08,10.35,10.35,...,10.38,10.39,10.4,361090,211300,133800,38800,135700,10.46,25374

,clockAtArrival,sequenceNo,source,StockID,exchange,time,cum_volume,cum_amount,close,bid1p,...,ask3p,ask4p,ask5p,ask1q,ask2q,ask3q,ask4q,ask5q,openPrice,numTrades
5227277,1598855584993663,12855379,25,600000,SH,143302000,69162744,723023496.0,10.35,10.35,...,10.38,10.39,10.4,93200,209300,245600,112500,128600,10.46,0
5228634,1598855588459669,12859345,25,600000,SH,143303000,69164044,723036951.0,10.35,10.35,...,10.38,10.39,10.4,98300,209300,245600,112500,128600,10.46,0
5229856,1598855591250055,12862475,25,600000,SH,143307000,69173744,723137346.0,10.35,10.35,...,10.38,10.39,10.4,96600,209300,245600,112600,128600,10.46,0
5230918,1598855594961783,12865396,25,600000,SH,143311000,69177844,723179810.0,10.36,10.35,...,10.38,10.39,10.4,96700,209100,245600,112600,128600,10.46,0
5232177,1598855597057991,12868447,25,600000,SH,143313000,69194844,723355849.0,10.35,10.35,...,10.38,10.39,10.4,85100,209100,245600,112600,128600,10.46,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5581042,1598856470727652,13734406,25,600000,SH,144745000,73062037,763395485.0,10.35,10.35,...,10.38,10.39,10.4,365690,218700,139500,38800,135700,10.46,0
5582179,1598856474521875,13737306,25,600000,SH,144750000,73067237,763449335.0,10.36,10.35,...,10.38,10.39,10.4,362690,218700,139500,38800,135700,10.46,0
5583144,1598856476626811,13740036,25,600000,SH,144751000,73068637,763463832.0,10.36,10.35,...,10.38,10.39,10.4,361990,211300,139500,38800,135700,10.46,0
5584492,1598856479155746,13743185,25,600000,SH,144756000,73101337,763802277.0,10.35,10.35,...,10.38,10.39,10.4,361990,211300,133800,38800,135700,10.46,0
5585704,1598856481205576,13745001,25,600000,SH,144759000,73102337,763812636.0,10.35,10.35,...,10.38,10.39,10.4,361090,211300,133800,38800,135700,10.46,0

In [36]:
logSH1.groupby('StockID')['time'].min().min()

115310000

In [37]:
logSH1.groupby('StockID')['time'].max().max()

153041000

In [32]:
logSH[(logSH['time'] <= 103618000)].groupby('StockID')['time'].max().min()

103519000

In [6]:
in_dex = [16, 300, 852, 905]
data1 = logSH[~logSH["StockID"].isin(in_dex) & (logSH['source'] == 22)]
data2 = logSH1[~logSH1["StockID"].isin(in_dex)]
columns = ["StockID", "cum_volume", "cum_amount", "close", "bid1p", "bid2p", "bid3p", "bid4p", "bid5p", "bid1q", "bid2q",
           "bid3q", "bid4q", "bid5q", "ask1p", "ask2p", "ask3p", "ask4p", "ask5p", "ask1q", "ask2q", "ask3q",
           "ask4q", "ask5q", 'openPrice']
data1_1 = data1.drop_duplicates(subset=columns, keep="first").reset_index()
data2_1 = data2.drop_duplicates(subset=columns, keep="first").reset_index()
n1 = len(data1_1["StockID"].unique())
n2 = len(data2_1["StockID"].unique())
print(n1)
print(n2)
if n1 != n2:
    sl = list(set(data1_1["StockID"].unique()) & (set(data2_1["StockID"].unique())))
    data1_1 = data1_1[data1_1["StockID"].isin(sl)]
    data2_1 = data2_1[data2_1["StockID"].isin(sl)]

# data1_1['openPrice'] = np.where(data1_1['cum_volume'] > 0, data1_1.groupby('StockID')['openPrice'].transform('max'), data1_1['cum_amount'])
# for cols in ["cum_amount"]:
#     data2_1[cols] = (data2_1[cols]*10).round(2) 
#     data1_1[cols] = data1_1[cols].round(2)

# data1_1.loc[data1_1['cum_volume'] > 0, 'openPrice'] = data1_1[data1_1['cum_volume'] > 0].groupby('StockID')['openPrice'].transform('max')
# data2_1.loc[data2_1['cum_volume'] > 0, 'openPrice'] = data2_1[data2_1['cum_volume'] > 0].groupby('StockID')['openPrice'].transform('max')

data2_1['cum_amount'] = data2_1['cum_amount'].round(2) 

test = pd.merge(data1_1, data2_1, left_on=columns, right_on=columns, how="outer")
n1 = test["sequenceNo_x"].count()
n2 = test["sequenceNo_y"].count()
len1 = len(test)
print(n1)
print(n2)
print(len1)
print("-----------------------------------------------")
if n2 < len1:
    display("test is not complete:")
    display(test[np.isnan(test["sequenceNo_y"])])
    display(len(test[np.isnan(test["sequenceNo_y"])])/n1)
if (len1 == n2) & (n1 < len1):
    display("baseline is not complete:")
    display(test[np.isnan(test["sequenceNo_x"])])
    display(n2-n1)
    print((n2-n1)/n1)

1691
1691
5837678
5490221
5837678
-----------------------------------------------

'test is not complete:'

,index_x,clockAtArrival_x,sequenceNo_x,source_x,StockID,exchange_x,time_x,cum_volume,cum_amount,close,...,ask5q,openPrice,numTrades_x,index_y,clockAtArrival_y,sequenceNo_y,source_y,exchange_y,time_y,numTrades_y
2068,75636,1598836543251880,1110090,22,601818,SH,91503420,0,0.0,0.00,...,0,0.00,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2069,75637,1598836543251888,1110091,22,601877,SH,91503420,0,0.0,0.00,...,0,0.00,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2070,75638,1598836543251901,1110092,22,600113,SH,91503420,0,0.0,0.00,...,0,0.00,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2071,75639,1598836543251906,1110093,22,600409,SH,91503420,0,0.0,0.00,...,0,0.00,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2072,75640,1598836543251913,1110094,22,600398,SH,91503420,0,0.0,0.00,...,0,0.00,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5834741,13986239,1598857237535525,222598136,22,600277,SH,145957490,29226450,105253523.0,3.59,...,0,3.57,7105,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5834769,13986267,1598857237536999,222598178,22,603337,SH,145957490,2492202,71699673.0,28.18,...,0,28.28,6396,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5834771,13986269,1598857237537013,222598180,22,603226,SH,145957490,4321804,51945937.0,11.86,...,0,11.91,4370,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5834860,13986423,1598857237547928,222598460,22,603613,SH,145957500,5563916,457579829.0,84.48,...,0,77.81,14881,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5834864,13986427,1598857237548766,222598477,22,688266,SH,145957500,735163,71536942.0,97.68,...,0,97.20,1755,NaN,NaN,NaN,NaN,NaN,NaN,NaN

0.05951972685029904

In [20]:
test[np.isnan(test["sequenceNo_y"]) & (test['time_x'] > 100000000)]

,index_x,clockAtArrival_x,sequenceNo_x,source_x,StockID,exchange_x,time_x,cum_volume,cum_amount,close,bid1p,bid2p,bid3p,bid4p,bid5p,bid1q,bid2q,bid3q,bid4q,bid5q,ask1p,ask2p,ask3p,ask4p,ask5p,ask1q,ask2q,ask3q,ask4q,ask5q,openPrice,numTrades_x,index_y,clockAtArrival_y,sequenceNo_y,source_y,exchange_y,time_y,numTrades_y
960658,2257912,1598839241894145,55329554,22,600816,SH,100002030,11022204,21248089.0,1.93,1.93,1.92,1.91,1.90,1.89,388432,470500,695600,483800,397800,1.94,1.95,1.96,1.97,0.00,479248,796068,1901808,5176110,0,1.88,1542,NaN,NaN,NaN,NaN,NaN,NaN,NaN
960680,2257934,1598839241896086,55329592,22,600083,SH,100002030,1654400,11581667.0,7.01,7.02,7.01,7.00,6.99,6.98,1600,22100,60700,8400,8200,7.04,7.05,7.06,7.07,7.08,15900,9000,400,1000,27200,7.15,737,NaN,NaN,NaN,NaN,NaN,NaN,NaN
960738,2257994,1598839241902689,55329736,22,600829,SH,100002030,658900,5252190.0,7.98,7.97,7.96,7.95,7.94,7.93,15500,19900,2900,4800,11500,7.98,7.99,8.00,8.01,8.02,8800,3000,10500,12900,11200,7.97,646,NaN,NaN,NaN,NaN,NaN,NaN,NaN
960745,2258001,1598839241904206,55329767,22,603226,SH,100002030,1421683,17147841.0,12.06,12.04,12.03,12.02,12.01,12.00,4300,2600,9405,7300,24900,12.06,12.09,12.10,12.11,12.12,2300,7800,7400,1300,3270,11.91,1517,NaN,NaN,NaN,NaN,NaN,NaN,NaN
960763,2258019,1598839241906304,55329818,22,603908,SH,100002030,120100,3242913.0,27.03,27.03,27.01,27.00,26.99,26.97,1300,1700,14100,500,500,27.04,27.05,27.06,27.08,27.09,500,600,2500,3700,3200,27.09,433,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5834741,13986239,1598857237535525,222598136,22,600277,SH,145957490,29226450,105253523.0,3.59,3.58,0.00,0.00,0.00,0.00,117100,367900,0,0,0,3.58,0.00,0.00,0.00,0.00,117100,0,0,0,0,3.57,7105,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5834769,13986267,1598857237536999,222598178,22,603337,SH,145957490,2492202,71699673.0,28.18,27.50,0.00,0.00,0.00,0.00,79900,0,0,0,0,27.50,0.00,0.00,0.00,0.00,79900,11045,0,0,0,28.28,6396,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5834771,13986269,1598857237537013,222598180,22,603226,SH,145957490,4321804,51945937.0,11.86,11.88,0.00,0.00,0.00,0.00,79600,68600,0,0,0,11.88,0.00,0.00,0.00,0.00,79600,0,0,0,0,11.91,4370,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5834860,13986423,1598857237547928,222598460,22,603613,SH,145957500,5563916,457579829.0,84.48,84.48,0.00,0.00,0.00,0.00,10245,310500,0,0,0,84.48,0.00,0.00,0.00,0.00,10245,0,0,0,0,77.81,14881,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5834864,13986427,1598857237548766,222598477,22,688266,SH,145957500,735163,71536942.0,97.68,97.60,0.00,0.00,0.00,0.00,27558,0,0,0,0,97.60,0.00,0.00,0.00,0.00,27558,75513,0,0,0,97.20,1755,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [67]:
pd.set_option('max_columns', 200)
logSH1[(logSH1['StockID'] == 16) & (logSH1['time'] >= '10:00:20')].head(10)[['StockID', 'source', 'time', 'cum_volume', "close", 'openPrice']]

         StockID  source      time  cum_volume      close  openPrice
982069        16      25  10:00:21    14464143  3397.5350  3386.6204
984762        16      25  10:00:31    14504597  3396.4856  3386.6204
987969        16      25  10:00:36    14541163  3395.3109  3386.6204
989836        16      25  10:00:40    14565473  3394.7371  3386.6204
992104        16      25  10:00:46    14582559  3394.7997  3386.6204
993914        16      25  10:00:51    14602075  3394.5362  3386.6204
995878        16      25  10:00:55    14619706  3393.7401  3386.6204
997659        16      25  10:01:01    14638503  3393.8132  3386.6204
1000413       16      25  10:01:06    14661294  3392.6132  3386.6204
1003081       16      25  10:01:10    14678806  3392.9417  3386.6204

In [69]:
logSH[(logSH['StockID'] == 16) & (logSH['time'] >= '10:00:21.000') & (logSH['source'] == 22)].head(10)[['StockID', 'source', 'time', 'cum_volume', "close", 'openPrice']]

         StockID  source          time  cum_volume      close  openPrice
2278385       16      22  10:00:22.070    14464143  3397.5350  3386.6204
2283663       16      22  10:00:27.130    14477272  3397.6844  3386.6204
2288990       16      22  10:00:32.100    14504597  3396.4856  3386.6204
2293186       16      22  10:00:36.500    14504597  3396.4856  3386.6204
2293714       16      22  10:00:37.070    14541163  3395.3109  3386.6204
2298746       16      22  10:00:42.040    14565473  3394.7371  3386.6204
2304349       16      22  10:00:47.130    14582559  3394.7997  3386.6204
2309128       16      22  10:00:52.100    14602075  3394.5362  3386.6204
2314066       16      22  10:00:57.070    14619706  3393.7401  3386.6204
2319591       16      22  10:01:02.160    14638503  3393.8132  3386.6204

In [18]:
data2_1['cum_amount'].astype(str).apply(lambda x: len(x.split('.')[1])).unique()

array([1, 6], dtype=int64)

In [11]:
pd.set_option('max_columns', 200)
test[np.isnan(test["sequenceNo_x"])]

,index_x,clockAtArrival_x,sequenceNo_x,source_x,StockID,exchange_x,time_x,cum_volume,cum_amount,close,bid1p,bid2p,bid3p,bid4p,bid5p,bid1q,bid2q,bid3q,bid4q,bid5q,ask1p,ask2p,ask3p,ask4p,ask5p,ask1q,ask2q,ask3q,ask4q,ask5q,openPrice,numTrades_x,index_y,clockAtArrival_y,sequenceNo_y,source_y,exchange_y,time_y,numTrades_y
5837678,NaN,NaN,NaN,NaN,600519,NaN,NaN,3238622,5.829629e+09,1803.00,1803.00,1802.37,1802.21,1802.10,1802.01,100,200,100,100,100,1804.98,1804.99,1805.00,1805.99,1806.00,100,100,1100,200,1100,1770.58,NaN,3198556.0,1.598850e+15,7846351.0,25.0,SH,130140000.0,0.0
5837679,NaN,NaN,NaN,NaN,600519,NaN,NaN,3238822,5.829990e+09,1803.09,1803.00,1802.37,1802.21,1802.10,1802.01,200,300,100,100,100,1804.98,1804.99,1805.00,1805.99,1806.00,300,100,1100,200,1100,1770.58,NaN,3199281.0,1.598850e+15,7848545.0,25.0,SH,130141000.0,0.0
5837680,NaN,NaN,NaN,NaN,600519,NaN,NaN,3238822,5.829990e+09,1803.09,1803.00,1802.37,1802.21,1802.10,1802.01,200,300,100,100,100,1804.98,1804.99,1805.00,1805.99,1806.00,400,100,1100,200,1100,1770.58,NaN,3200305.0,1.598850e+15,7849974.0,25.0,SH,130141000.0,0.0
5837681,NaN,NaN,NaN,NaN,600519,NaN,NaN,3238822,5.829990e+09,1803.09,1803.09,1803.00,1802.37,1802.10,1802.01,200,200,100,100,100,1804.98,1804.99,1805.00,1805.99,1806.00,400,100,1100,200,1100,1770.58,NaN,3201931.0,1.598850e+15,7854170.0,25.0,SH,130141000.0,0.0
5837682,NaN,NaN,NaN,NaN,600519,NaN,NaN,3240822,5.833600e+09,1805.99,1805.09,1805.00,1803.00,1802.37,1802.10,200,6400,400,100,100,1806.00,1806.80,1806.88,1806.90,1806.94,1100,200,5100,100,400,1770.58,NaN,3202522.0,1.598850e+15,7856098.0,25.0,SH,130152000.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5842694,NaN,NaN,NaN,NaN,600030,NaN,NaN,213766936,6.931516e+09,31.86,31.80,0.00,0.00,0.00,0.00,5128679,714521,0,0,0,31.80,0.00,0.00,0.00,0.00,5128679,0,0,0,0,32.30,NaN,5875554.0,1.598857e+15,14422829.0,25.0,SH,145659000.0,0.0
5842695,NaN,NaN,NaN,NaN,600519,NaN,NaN,4657172,8.387650e+09,1792.97,1786.50,0.00,0.00,0.00,0.00,123864,8236,0,0,0,1786.50,0.00,0.00,0.00,0.00,123864,0,0,0,0,1770.58,NaN,5875856.0,1.598857e+15,14423135.0,25.0,SH,145659000.0,0.0
5842696,NaN,NaN,NaN,NaN,600030,NaN,NaN,218904215,7.094882e+09,31.80,31.80,31.79,31.78,31.77,31.76,722221,27300,143800,134500,25000,31.81,31.82,31.83,31.84,31.85,24500,40200,58800,16300,88700,32.30,NaN,5876142.0,1.598857e+15,14423421.0,25.0,SH,150000000.0,0.0
5842697,NaN,NaN,NaN,NaN,600887,NaN,NaN,173568886,7.315959e+09,41.80,41.94,0.00,0.00,0.00,0.00,2497890,1070010,0,0,0,41.94,0.00,0.00,0.00,0.00,2497890,0,0,0,0,41.50,NaN,5876583.0,1.598857e+15,14423862.0,25.0,SH,145659000.0,0.0
5842698,NaN,NaN,NaN,NaN,600887,NaN,NaN,176066776,7.420721e+09,41.94,41.94,41.91,41.90,41.89,41.88,1070010,1400,4000,2800,18000,41.95,41.96,41.97,41.98,41.99,219700,5400,26400,5600,24600,41.50,NaN,5878411.0,1.598857e+15,14427931.0,25.0,SH,150000000.0,0.0

In [15]:
logSH[(logSH['StockID'] == 600519) & (logSH['cum_volume'] >= 3238622) & (logSH['source'] == 22)][['StockID', 'time', 'source', 
                                                                                  'cum_volume', 'cum_amount', 'close', 
           "bid1p", "bid2p", "bid3p", "bid4p", "bid5p", "bid1q", "bid2q","bid3q", "bid4q", "bid5q", "ask1p", "ask2p","ask3p", "ask4p","ask5p", "ask1q", "ask2q", "ask3q", "ask4q","ask5q", "openPrice"]].head(20)['cum_amount'].iloc[0]

5829629455.0

In [16]:
logSH1[(logSH1['StockID'] == 600519) & (logSH1['cum_volume'] >= 3238622) & (logSH1['source'] == 25)][['StockID', 'time', 'source', 
                                                                                  'cum_volume', 'cum_amount', 'close', 
           "bid1p", "bid2p", "bid3p", "bid4p", "bid5p", "bid1q", "bid2q","bid3q", "bid4q", "bid5q", "ask1p", "ask2p","ask3p", "ask4p","ask5p", "ask1q", "ask2q", "ask3q", "ask4q","ask5q", "openPrice"]].head(20)['cum_amount'].iloc[0]

5829629455.000001

In [37]:
logSH[(logSH['StockID'] == 600419) & (logSH['time'] >= 92459000) & (logSH['source'] == 23)][['StockID', 'time','source',
                                                                                  'cum_volume', 'cum_amount', 'close', 
           "bid1p", "bid2p", "bid1q", "bid2q","ask1p", "ask2p", "ask1q", "ask2q", "openPrice"]].head(5)

,StockID,time,source,cum_volume,cum_amount,close,bid1p,bid2p,bid1q,bid2q,ask1p,ask2p,ask1q,ask2q,openPrice
291247,600419,92459000,23,0,0.0,0.00,16.82,0.0,844470,9830730,16.82,0.0,844470,0,0.00
292975,600419,92500000,23,844470,14203985.4,16.82,16.82,16.8,9844630,1200,0.00,0.0,0,0,0.00
296260,600419,92504000,23,844470,14203985.4,16.82,16.82,16.8,9844630,1200,0.00,0.0,0,0,0.00
298345,600419,92521000,23,844470,14203985.4,16.82,16.82,16.8,9844630,1200,0.00,0.0,0,0,16.82
303351,600419,92621000,23,844470,14203985.4,16.82,16.82,16.8,9844630,1200,0.00,0.0,0,0,16.82

In [44]:
pd.set_option('max_columns', 200)
pd.set_option('max_rows', 200)
test[(np.isnan(test['sequenceNo_y'])) & (test['time_x'] > 145700000)]

,index_x,clockAtArrival_x,sequenceNo_x,source_x,StockID,exchange_x,time_x,cum_volume,cum_amount,close,bid1p,bid2p,bid3p,bid4p,bid5p,bid1q,bid2q,bid3q,bid4q,bid5q,ask1p,ask2p,ask3p,ask4p,ask5p,ask1q,ask2q,ask3q,ask4q,ask5q,openPrice,index_y,clockAtArrival_y,sequenceNo_y,source_y,exchange_y,time_y
2815096,13568598.0,1.597388e+15,213544119.0,23.0,600017,SH,145701000.0,12610458,3.515092e+07,2.80,0.00,0.00,0.00,0.00,0.00,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0,0,0,0,0,2.78,NaN,NaN,NaN,NaN,NaN,NaN
2815097,13568599.0,1.597388e+15,213544120.0,23.0,600019,SH,145701000.0,43977506,2.167836e+08,4.95,0.00,0.00,0.00,0.00,0.00,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0,0,0,0,0,4.94,NaN,NaN,NaN,NaN,NaN,NaN
2815098,13568600.0,1.597388e+15,213544121.0,23.0,600054,SH,145701000.0,4848724,4.422136e+07,9.18,0.00,0.00,0.00,0.00,0.00,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0,0,0,0,0,9.17,NaN,NaN,NaN,NaN,NaN,NaN
2815099,13568601.0,1.597388e+15,213544122.0,23.0,600067,SH,145701000.0,7054371,2.707605e+07,3.84,0.00,0.00,0.00,0.00,0.00,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0,0,0,0,0,3.79,NaN,NaN,NaN,NaN,NaN,NaN
2815100,13568602.0,1.597388e+15,213544123.0,23.0,600091,SH,145701000.0,2574541,7.354033e+06,2.88,0.00,0.00,0.00,0.00,0.00,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0,0,0,0,0,2.88,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2883066,13719305.0,1.597388e+15,214919521.0,23.0,603877,SH,150002000.0,3196901,6.211987e+07,20.23,20.23,20.22,20.21,20.18,20.15,2227998,9400,2600,5000,600,0.00,0.00,0.00,0.00,0.00,0,0,0,0,0,18.33,NaN,NaN,NaN,NaN,NaN,NaN
2883084,13719323.0,1.597388e+15,214919557.0,23.0,603801,SH,150002000.0,5960971,2.319245e+08,39.68,39.68,39.67,39.66,39.49,39.45,328300,1900,100,600,100,0.00,0.00,0.00,0.00,0.00,0,0,0,0,0,36.15,NaN,NaN,NaN,NaN,NaN,NaN
2883086,13719325.0,1.597388e+15,214919559.0,23.0,603157,SH,150002000.0,7705511,1.976853e+07,2.59,2.59,2.58,2.57,2.56,2.55,330250,66300,107400,81900,27200,0.00,0.00,0.00,0.00,0.00,0,0,0,0,0,2.46,NaN,NaN,NaN,NaN,NaN,NaN
2883121,13719360.0,1.597388e+15,214919636.0,23.0,601086,SH,150002000.0,53163008,3.979829e+08,6.84,0.00,0.00,0.00,0.00,0.00,0,0,0,0,0,6.84,6.85,6.86,6.87,6.88,3372674,68200,19600,20800,6200,8.36,NaN,NaN,NaN,NaN,NaN,NaN
2883152,13719391.0,1.597388e+15,214919700.0,23.0,601456,SH,150002000.0,33860835,5.370328e+08,15.86,15.86,15.85,15.84,15.83,15.82,36978613,39000,9100,30900,9700,0.00,0.00,0.00,0.00,0.00,0,0,0,0,0,15.86,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
logSH[(logSH['StockID'] == 601611) & (logSH['time'] >= 103745000.0) & (logSH['source'] == 23)].head(3)

,clockAtArrival,sequenceNo,source,StockID,exchange,time,cum_volume,cum_amount,close,bid1p,bid2p,bid3p,bid4p,bid5p,bid1q,bid2q,bid3q,bid4q,bid5q,ask1p,ask2p,ask3p,ask4p,ask5p,ask1q,ask2q,ask3q,ask4q,ask5q,openPrice
4276742,1597372693240540,85535767,23,601611,SH,103747000,78756043,7.065773e+08,8.57,8.57,8.56,8.55,8.54,0.0,64200,254700,792300,1485700,0,8.59,8.60,8.61,8.62,8.63,125200,52000,163100,73200,40800,9.14
4279546,1597372696238435,85578922,23,601611,SH,103750000,80040167,7.175599e+08,8.56,8.55,8.54,0.00,0.00,0.0,1100,1450776,0,0,0,8.56,8.57,8.58,8.59,8.60,13100,8300,9300,128500,164400,9.14
4282245,1597372699233091,85618815,23,601611,SH,103753000,80152467,7.185207e+08,8.57,8.55,8.54,0.00,0.00,0.0,500,1447576,0,0,0,8.56,8.57,8.58,8.59,8.60,7000,600,24700,28500,344600,9.14

In [20]:
logSH[(logSH['StockID'] == 600088) & (logSH['time'] >= 145900000) & (logSH['source'] == 23)]

,clockAtArrival,sequenceNo,source,StockID,exchange,time,cum_volume,cum_amount,close,bid1p,bid2p,bid3p,bid4p,bid5p,bid1q,bid2q,bid3q,bid4q,bid5q,ask1p,ask2p,ask3p,ask4p,ask5p,ask1q,ask2q,ask3q,ask4q,ask5q,openPrice
14401183,1597647568215795,241755576,23,600543,SH,145900000,53842183,5.410049e+08,10.25,10.25,0.00,0.00,0.00,0.00,7500,2637616,0,0,0,10.25,0.0,0.0,0.0,0.0,7500,0,0,0,0,9.0
14406226,1597647574214071,241808648,23,600543,SH,145906000,53842183,5.410049e+08,10.25,10.25,0.00,0.00,0.00,0.00,7500,2638316,0,0,0,10.25,0.0,0.0,0.0,0.0,7500,0,0,0,0,9.0
14413699,1597647583254301,241868382,23,600543,SH,145915000,53842183,5.410049e+08,10.25,10.25,0.00,0.00,0.00,0.00,7500,2640716,0,0,0,10.25,0.0,0.0,0.0,0.0,7500,0,0,0,0,9.0
14416220,1597647586208565,241889181,23,600543,SH,145918000,53842183,5.410049e+08,10.25,10.25,0.00,0.00,0.00,0.00,7500,2641416,0,0,0,10.25,0.0,0.0,0.0,0.0,7500,0,0,0,0,9.0
14418846,1597647589262855,241909130,23,600543,SH,145921000,53842183,5.410049e+08,10.25,10.25,0.00,0.00,0.00,0.00,9100,2639816,0,0,0,10.25,0.0,0.0,0.0,0.0,9100,0,0,0,0,9.0
14423966,1597647595223868,241948017,23,600543,SH,145927000,53842183,5.410049e+08,10.25,10.25,0.00,0.00,0.00,0.00,9200,2639716,0,0,0,10.25,0.0,0.0,0.0,0.0,9200,0,0,0,0,9.0
14426439,1597647598239918,241966624,23,600543,SH,145930000,53842183,5.410049e+08,10.25,10.25,0.00,0.00,0.00,0.00,9200,2640716,0,0,0,10.25,0.0,0.0,0.0,0.0,9200,0,0,0,0,9.0
14428942,1597647601209050,241982862,23,600543,SH,145933000,53842183,5.410049e+08,10.25,10.25,0.00,0.00,0.00,0.00,9200,2648016,0,0,0,10.25,0.0,0.0,0.0,0.0,9200,0,0,0,0,9.0
14431488,1597647604219908,242002530,23,600543,SH,145936000,53842183,5.410049e+08,10.25,10.25,0.00,0.00,0.00,0.00,9200,2668016,0,0,0,10.25,0.0,0.0,0.0,0.0,9200,0,0,0,0,9.0
14436486,1597647610222176,242038011,23,600543,SH,145942000,53842183,5.410049e+08,10.25,10.25,0.00,0.00,0.00,0.00,10300,2666916,0,0,0,10.25,0.0,0.0,0.0,0.0,10300,0,0,0,0,9.0
14438928,1597647613233074,242056437,23,600543,SH,145945000,53842183,5.410049e+08,10.25,10.25,0.00,0.00,0.00,0.00,10300,2668716,0,0,0,10.25,0.0,0.0,0.0,0.0,10300,0,0,0,0,9.0
14441429,1597647616219347,242074586,23,600543,SH,145948000,53842183,5.410049e+08,10.25,10.25,0.00,0.00,0.00,0.00,10300,2668816,0,0,0,10.25,0.0,0.0,0.0,0.0,10300,0,0,0,0,9.0
14443726,1597647619081918,242089587,23,600543,SH,145951000,53842183,5.410049e+08,10.25,10.25,0.00,0.00,0.00,0.00,10300,2668816,0,0,0,10.25,0.0,0.0,0.0,0.0,10300,0,0,0,0,9.0
14446402,1597647622219810,242109222,23,600543,SH,145954000,53842183,5.410049e+08,10.25,10.25,0.00,0.00,0.00,0.00,10300,2668916,0,0,0,10.25,0.0,0.0,0.0,0.0,10300,0,0,0,0,9.0
14448881,1597647625216302,242128879,23,600543,SH,145957000,53842183,5.410049e+08,10.25,10.25,0.00,0.00,0.00,0.00,10400,2800616,0,0,0,10.25,0.0,0.0,0.0,0.0,10400,0,0,0,0,9.0
14451431,1597647628328554,242167365,23,600543,SH,150000000,53842183,5.410049e+08,10.25,10.25,0.00,0.00,0.00,0.00,10400,2800916,0,0,0,10.25,0.0,0.0,0.0,0.0,10400,0,0,0,0,9.0
14451994,1597647629100571,242248409,23,600543,SH,150001000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,0.00,0.0,0.0,0.0,0.0,0,0,0,0,0,9.0
14454980,1597647631974984,242596808,23,600543,SH,150003000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,0.00,0.0,0.0,0.0,0.0,0,0,0,0,0,9.0
14460071,1597647652025688,243045071,23,600543,SH,150023000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,0.00,0.0,0.0,0.0,0.0,0,0,0,0,0,9.0
14465570,1597647712026343,243226247,23,600543,SH,150123000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,0.00,0.0,0.0,0.0,0.0,0,0,0,0,0,9.0
14470616,1597647772027700,243351931,23,600543,SH,150223000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,0.00,0.0,0.0,0.0,0.0,0,0,0,0,0,9.0
14475622,1597647832029121,243462566,23,600543,SH,150323000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,0.00,0.0,0.0,0.0,0.0,0,0,0,0,0,9.0
14480633,1597647892030197,243569431,23,600543,SH,150423000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,0.00,0.0,0.0,0.0,0.0,0,0,0,0,0,9.0
14487297,1597647952030014,243684625,23,600543,SH,150524000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,0.00,0.0,0.0,0.0,0.0,0,0,0,0,0,9.0
14492303,1597648012030903,243773943,23,600543,SH,150624000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,0.00,0.0,0.0,0.0,0.0,0,0,0,0,0,9.0
14497309,1597648072031824,243864151,23,600543,SH,150723000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,0.00,0.0,0.0,0.0,0.0,0,0,0,0,0,9.0
14502315,1597648132034199,243953212,23,600543,SH,150824000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,0.00,0.0,0.0,0.0,0.0,0,0,0,0,0,9.0
14507321,1597648192034139,244041412,23,600543,SH,150924000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,0.00,0.0,0.0,0.0,0.0,0,0,0,0,0,9.0
14512327,1597648252035036,244132163,23,600543,SH,151024000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,0.00,0.0,0.0,0.0,0.0,0,0,0,0,0,9.0
14517333,1597648312036102,244213788,23,600543,SH,151123000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,0.00,0.0,0.0,0.0,0.0,0,0,0,0,0,9.0
14522339,1597648372035411,244293323,23,600543,SH,151224000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,0.00,0.0,0.0,0.0,0.0,0,0,0,0,0,9.0
14527345,1597648432037267,244373694,23,600543,SH,151324000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,0.00,0.0,0.0,0.0,0.0,0,0,0,0,0,9.0
14532351,1597648492037542,244449217,23,600543,SH,151424000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,0.00,0.0,0.0,0.0,0.0,0,0,0,0,0,9.0
14537357,1597648552038666,244524673,23,600543,SH,151524000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,0.00,0.0,0.0,0.0,0.0,0,0,0,0,0,9.0
14542363,1597648612040384,244599724,23,600543,SH,151623000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,0.00,0.0,0.0,0.0,0.0,0,0,0,0,0,9.0
14547401,1597648672046696,244675190,23,600543,SH,151724000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,0.00,0.0,0.0,0.0,0.0,0,0,0,0,0,9.0
14552375,1597648732041687,244748667,23,600543,SH,151823000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,0.00,0.0,0.0,0.0,0.0,0,0,0,0,0,9.0
14557381,1597648792043002,244820447,23,600543,SH,151924000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,0.00,0.0,0.0,0.0,0.0,0,0,0,0,0,9.0
14562387,1597648852044122,244892620,23,600543,SH,152024000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,0.00,0.0,0.0,0.0,0.0,0,0,0,0,0,9.0
14567393,1597648912044332,244965098,23,600543,SH,152124000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,0.00,0.0,0.0,0.0,0.0,0,0,0,0,0,9.0
14572399,1597648972045857,245038299,23,600543,SH,152224000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,0.00,0.0,0.0,0.0,0.0,0,0,0,0,0,9.0
14577449,1597649032059463,245110511,23,600543,SH,152323000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,0.00,0.0,0.0,0.0,0.0,0,0,0,0,0,9.0
14582411,1597649092048042,245180063,23,600543,SH,152424000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,0.00,0.0,0.0,0.0,0.0,0,0,0,0,0,9.0
14587417,1597649152047874,245251228,23,600543,SH,152524000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,0.00,0.0,0.0,0.0,0.0,0,0,0,0,0,9.0
14592423,1597649212049219,245322408,23,600543,SH,152624000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,0.00,0.0,0.0,0.0,0.0,0,0,0,0,0,9.0
14597473,1597649272059403,245391044,23,600543,SH,152724000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,0.00,0.0,0.0,0.0,0.0,0,0,0,0,0,9.0
14602435,1597649332052269,245456278,23,600543,SH,152824000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,0.00,0.0,0.0,0.0,0.0,0,0,0,0,0,9.0
14607441,1597649392052703,245521132,23,600543,SH,152924000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,0.00,0.0,0.0,0.0,0.0,0,0,0,0,0,9.0
14612459,1597649452054364,245588256,23,600543,SH,153023000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,0.00,0.0,0.0,0.0,0.0,0,0,0,0,0,9.0
14617453,1597649512054342,245650731,23,600543,SH,153123000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,0.00,0.0,0.0,0.0,0.0,0,0,0,0,0,9.0
14622459,1597649572056165,245713221,23,600543,SH,153223000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,0.00,0.0,0.0,0.0,0.0,0,0,0,0,0,9.0
14627465,1597649632055952,245775698,23,600543,SH,153323000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,0.00,0.0,0.0,0.0,0.0,0,0,0,0,0,9.0
14632471,1597649692061503,245838186,23,600543,SH,153423000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,0.00,0.0,0.0,0.0,0.0,0,0,0,0,0,9.0
14637477,1597649752058410,245900673,23,600543,SH,153523000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,0.00,0.0,0.0,0.0,0.0,0,0,0,0,0,9.0
14642483,1597649812059762,245963159,23,600543,SH,153623000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,0.00,0.0,0.0,0.0,0.0,0,0,0,0,0,9.0
14647489,1597649872060091,246025643,23,600543,SH,153723000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,0.00,0.0,0.0,0.0,0.0,0,0,0,0,0,9.0
14652495,1597649932059962,246088132,23,600543,SH,153823000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,0.00,0.0,0.0,0.0,0.0,0,0,0,0,0,9.0
14657527,1597649992065760,246150653,23,600543,SH,153923000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,0.00,0.0,0.0,0.0,0.0,0,0,0,0,0,9.0
14662507,1597650052061911,246213102,23,600543,SH,154023000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,0.00,0.0,0.0,0.0,0.0,0,0,0,0,0,9.0
14667513,1597650112063318,246275588,23,600543,SH,154123000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,0.00,0.0,0.0,0.0,0.0,0,0,0,0,0,9.0
14672519,1597650172064125,246338065,23,600543,SH,154223000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,0.00,0.0,0.0,0.0,0.0,0,0,0,0,0,9.0
14677525,1597650232066340,246400554,23,600543,SH,154323000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,0.00,0.0,0.0,0.0,0.0,0,0,0,0,0,9.0
14682531,1597650292065802,246463043,23,600543,SH,154423000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,0.00,0.0,0.0,0.0,0.0,0,0,0,0,0,9.0
14687537,1597650352067761,246525534,23,600543,SH,154523000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,0.00,0.0,0.0,0.0,0.0,0,0,0,0,0,9.0
14692543,1597650412065770,246588014,23,600543,SH,154623000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,0.00,0.0,0.0,0.0,0.0,0,0,0,0,0,9.0
14697549,1597650472068834,246650499,23,600543,SH,154723000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,0.00,0.0,0.0,0.0,0.0,0,0,0,0,0,9.0
14702555,1597650532069896,246712982,23,600543,SH,154823000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,0.00,0.0,0.0,0.0,0.0,0,0,0,0,0,9.0
14707599,1597650592077491,246775524,23,600543,SH,154923000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,0.00,0.0,0.0,0.0,0.0,0,0,0,0,0,9.0

In [21]:
logSH1[(logSH1['StockID'] == 600543) & (logSH1['time'] >= 145900000)]

,clockAtArrival,sequenceNo,source,StockID,exchange,time,cum_volume,cum_amount,close,bid1p,bid2p,bid3p,bid4p,bid5p,bid1q,bid2q,bid3q,bid4q,bid5q,ask1p,ask2p,ask3p,ask4p,ask5p,ask1q,ask2q,ask3q,ask4q,ask5q,openPrice
4358638,1597647540314546,72831775,25,600543,SH,145900000,53842183,5.410049e+08,10.25,10.25,0.00,10.23,10.22,10.21,7500,2637616,35800,6300,900,10.25,0.0,0.0,0.0,0.0,7500,0,0,0,0,9.0
4361086,1597647546307320,72847065,25,600543,SH,145906000,53842183,5.410049e+08,10.25,10.25,0.00,10.23,10.22,10.21,7500,2638316,35800,6300,900,10.25,0.0,0.0,0.0,0.0,7500,0,0,0,0,9.0
4364706,1597647555347292,72871907,25,600543,SH,145915000,53842183,5.410049e+08,10.25,10.25,0.00,10.23,10.22,10.21,7500,2640716,35800,6300,900,10.25,0.0,0.0,0.0,0.0,7500,0,0,0,0,9.0
4365948,1597647558294653,72881121,25,600543,SH,145918000,53842183,5.410049e+08,10.25,10.25,0.00,10.23,10.22,10.21,7500,2641416,35800,6300,900,10.25,0.0,0.0,0.0,0.0,7500,0,0,0,0,9.0
4367214,1597647561392202,72889725,25,600543,SH,145921000,53842183,5.410049e+08,10.25,10.25,0.00,10.23,10.22,10.21,9100,2639816,35800,6300,900,10.25,0.0,0.0,0.0,0.0,9100,0,0,0,0,9.0
4369684,1597647567321722,72905679,25,600543,SH,145927000,53842183,5.410049e+08,10.25,10.25,0.00,10.23,10.22,10.21,9200,2639716,35800,6300,900,10.25,0.0,0.0,0.0,0.0,9200,0,0,0,0,9.0
4370912,1597647570354981,72913859,25,600543,SH,145930000,53842183,5.410049e+08,10.25,10.25,0.00,10.23,10.22,10.21,9200,2640716,35800,6300,900,10.25,0.0,0.0,0.0,0.0,9200,0,0,0,0,9.0
4372129,1597647573293397,72920455,25,600543,SH,145933000,53842183,5.410049e+08,10.25,10.25,0.00,10.23,10.22,10.21,9200,2648016,35800,6300,900,10.25,0.0,0.0,0.0,0.0,9200,0,0,0,0,9.0
4373324,1597647576319349,72929072,25,600543,SH,145936000,53842183,5.410049e+08,10.25,10.25,0.00,10.23,10.22,10.21,9200,2668016,35800,6300,900,10.25,0.0,0.0,0.0,0.0,9200,0,0,0,0,9.0
4375745,1597647582311893,72944219,25,600543,SH,145942000,53842183,5.410049e+08,10.25,10.25,0.00,10.23,10.22,10.21,10300,2666916,35800,6300,900,10.25,0.0,0.0,0.0,0.0,10300,0,0,0,0,9.0
4376915,1597647585329772,72952083,25,600543,SH,145945000,53842183,5.410049e+08,10.25,10.25,0.00,10.23,10.22,10.21,10300,2668716,35800,6300,900,10.25,0.0,0.0,0.0,0.0,10300,0,0,0,0,9.0
4378101,1597647588317491,72960124,25,600543,SH,145948000,53842183,5.410049e+08,10.25,10.25,0.00,10.23,10.22,10.21,10300,2668816,35800,6300,900,10.25,0.0,0.0,0.0,0.0,10300,0,0,0,0,9.0
4379274,1597647591151481,72966226,25,600543,SH,145951000,53842183,5.410049e+08,10.25,10.25,0.00,10.23,10.22,10.21,10300,2668816,35800,6300,900,10.25,0.0,0.0,0.0,0.0,10300,0,0,0,0,9.0
4380512,1597647594307828,72974517,25,600543,SH,145954000,53842183,5.410049e+08,10.25,10.25,0.00,10.23,10.22,10.21,10300,2668916,35800,6300,900,10.25,0.0,0.0,0.0,0.0,10300,0,0,0,0,9.0
4381710,1597647597325079,72982565,25,600543,SH,145957000,53842183,5.410049e+08,10.25,10.25,0.00,10.23,10.22,10.21,10400,2800616,35800,6300,900,10.25,0.0,0.0,0.0,0.0,10400,0,0,0,0,9.0
4383013,1597647600433938,72999240,25,600543,SH,150000000,53842183,5.410049e+08,10.25,10.25,0.00,10.23,10.22,10.21,10400,2800916,35800,6300,900,10.25,0.0,0.0,0.0,0.0,10400,0,0,0,0,9.0
4383407,1597647601188973,73037214,25,600543,SH,150001000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,10.25,0.0,0.0,0.0,0.0,10400,0,0,0,0,9.0
4385475,1597647604066382,73184871,25,600543,SH,150003000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,10.25,0.0,0.0,0.0,0.0,10400,0,0,0,0,9.0
4387659,1597647624102792,73550722,25,600543,SH,150023000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,10.25,0.0,0.0,0.0,0.0,10400,0,0,0,0,9.0
4389596,1597647684096142,73554900,25,600543,SH,150123000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,10.25,0.0,0.0,0.0,0.0,10400,0,0,0,0,9.0
4391300,1597647744096834,73558845,25,600543,SH,150223000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,10.25,0.0,0.0,0.0,0.0,10400,0,0,0,0,9.0
4392961,1597647804099918,73562747,25,600543,SH,150323000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,10.25,0.0,0.0,0.0,0.0,10400,0,0,0,0,9.0
4394635,1597647864126959,73566662,25,600543,SH,150423000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,10.25,0.0,0.0,0.0,0.0,10400,0,0,0,0,9.0
4396300,1597647924099122,73570568,25,600543,SH,150524000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,10.25,0.0,0.0,0.0,0.0,10400,0,0,0,0,9.0
4397962,1597647984099231,73574471,25,600543,SH,150624000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,10.25,0.0,0.0,0.0,0.0,10400,0,0,0,0,9.0
4399632,1597648044099854,73578382,25,600543,SH,150723000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,10.25,0.0,0.0,0.0,0.0,10400,0,0,0,0,9.0
4401301,1597648104098891,73582292,25,600543,SH,150824000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,10.25,0.0,0.0,0.0,0.0,10400,0,0,0,0,9.0
4402971,1597648164101119,73586203,25,600543,SH,150924000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,10.25,0.0,0.0,0.0,0.0,10400,0,0,0,0,9.0
4404632,1597648224102579,73590105,25,600543,SH,151024000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,10.25,0.0,0.0,0.0,0.0,10400,0,0,0,0,9.0
4406302,1597648284099998,73594016,25,600543,SH,151123000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,10.25,0.0,0.0,0.0,0.0,10400,0,0,0,0,9.0
4407972,1597648344099580,73597927,25,600543,SH,151224000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,10.25,0.0,0.0,0.0,0.0,10400,0,0,0,0,9.0
4409642,1597648404101272,73601838,25,600543,SH,151324000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,10.25,0.0,0.0,0.0,0.0,10400,0,0,0,0,9.0
4411312,1597648464101207,73605749,25,600543,SH,151424000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,10.25,0.0,0.0,0.0,0.0,10400,0,0,0,0,9.0
4412982,1597648524101583,73609660,25,600543,SH,151524000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,10.25,0.0,0.0,0.0,0.0,10400,0,0,0,0,9.0
4414652,1597648584101167,73613571,25,600543,SH,151623000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,10.25,0.0,0.0,0.0,0.0,10400,0,0,0,0,9.0
4416354,1597648644115494,73617514,25,600543,SH,151724000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,10.25,0.0,0.0,0.0,0.0,10400,0,0,0,0,9.0
4417992,1597648704102567,73621393,25,600543,SH,151823000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,10.25,0.0,0.0,0.0,0.0,10400,0,0,0,0,9.0
4419654,1597648764102156,73625296,25,600543,SH,151924000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,10.25,0.0,0.0,0.0,0.0,10400,0,0,0,0,9.0
4421324,1597648824104058,73629207,25,600543,SH,152024000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,10.25,0.0,0.0,0.0,0.0,10400,0,0,0,0,9.0
4422994,1597648884103682,73633118,25,600543,SH,152124000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,10.25,0.0,0.0,0.0,0.0,10400,0,0,0,0,9.0
4424664,1597648944104545,73637029,25,600543,SH,152224000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,10.25,0.0,0.0,0.0,0.0,10400,0,0,0,0,9.0
4426367,1597649004122493,73640973,25,600543,SH,152323000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,10.25,0.0,0.0,0.0,0.0,10400,0,0,0,0,9.0
4427993,1597649064105662,73644840,25,600543,SH,152424000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,10.25,0.0,0.0,0.0,0.0,10400,0,0,0,0,9.0
4429662,1597649124103739,73648750,25,600543,SH,152524000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,10.25,0.0,0.0,0.0,0.0,10400,0,0,0,0,9.0
4431332,1597649184104692,73652661,25,600543,SH,152624000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,10.25,0.0,0.0,0.0,0.0,10400,0,0,0,0,9.0
4433046,1597649244126038,73656616,25,600543,SH,152724000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,10.25,0.0,0.0,0.0,0.0,10400,0,0,0,0,9.0
4434672,1597649304157922,73660483,25,600543,SH,152824000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,10.25,0.0,0.0,0.0,0.0,10400,0,0,0,0,9.0
4436342,1597649364148606,73664394,25,600543,SH,152924000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,10.25,0.0,0.0,0.0,0.0,10400,0,0,0,0,9.0
4438022,1597649424113623,73668315,25,600543,SH,153023000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,10.25,0.0,0.0,0.0,0.0,10400,0,0,0,0,9.0
4439680,1597649484105947,73672214,25,600543,SH,153123000,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,10.25,0.0,0.0,0.0,0.0,10400,0,0,0,0,9.0

In [15]:
test[(np.isnan(test['sequenceNo_x'])) & (test['time_y'] > 150000000)].head(100)

,index_x,clockAtArrival_x,sequenceNo_x,source_x,StockID,exchange_x,time_x,cum_volume,cum_amount,close,bid1p,bid2p,bid3p,bid4p,bid5p,bid1q,bid2q,bid3q,bid4q,bid5q,ask1p,ask2p,ask3p,ask4p,ask5p,ask1q,ask2q,ask3q,ask4q,ask5q,openPrice,index_y,clockAtArrival_y,sequenceNo_y,source_y,exchange_y,time_y
3979707,NaN,NaN,NaN,NaN,600543,NaN,NaN,53852583,5.411115e+08,10.25,10.25,10.24,10.23,10.22,10.21,2800916,3900,35800,7100,900,10.25,0.0,0.000,0.00,0.00,10400,0,0,0,0,9.00,4383407.0,1.597648e+15,73037214.0,25.0,SH,150001000.0
3979708,NaN,NaN,NaN,NaN,601628,NaN,NaN,60320650,2.732049e+09,47.11,47.11,47.10,47.09,47.08,47.07,4853400,203800,1500,21900,1300,47.11,0.0,0.005,0.00,0.00,205101,0,740,0,0,43.01,4383409.0,1.597648e+15,73037216.0,25.0,SH,150001000.0
3979709,NaN,NaN,NaN,NaN,600988,NaN,NaN,124613934,2.545103e+09,21.50,21.50,21.49,21.48,21.47,21.46,245962,57500,28500,23328,26600,21.51,0.0,21.510,0.00,0.00,257100,0,718525,0,0,19.10,4383429.0,1.597648e+15,73037894.0,25.0,SH,150001000.0
3979710,NaN,NaN,NaN,NaN,601838,NaN,NaN,90720549,9.708064e+08,11.08,11.08,11.07,11.06,11.05,11.04,17342298,54300,10200,1400,2200,11.08,0.0,0.000,0.00,0.00,253842,0,0,0,0,10.19,4383432.0,1.597648e+15,73037979.0,25.0,SH,150001000.0
3979711,NaN,NaN,NaN,NaN,600502,NaN,NaN,116059783,5.656504e+08,5.01,5.01,5.00,4.99,4.98,4.97,1913183,136600,162600,82200,77300,5.01,0.0,0.000,0.00,0.00,1985817,0,0,0,0,4.58,4383451.0,1.597648e+15,73039692.0,25.0,SH,150001000.0
3979712,NaN,NaN,NaN,NaN,600095,NaN,NaN,38970182,6.424353e+08,16.51,16.51,16.50,16.49,16.48,16.47,8247017,82900,22100,29800,17600,16.51,0.0,0.000,0.00,0.00,13200,0,0,0,0,16.51,4383471.0,1.597648e+15,73040378.0,25.0,SH,150001000.0
3979713,NaN,NaN,NaN,NaN,600118,NaN,NaN,59921400,2.348162e+09,39.72,39.72,39.71,39.70,39.69,39.68,2052797,11500,41400,10800,23900,39.72,0.0,0.001,0.00,0.00,34134,0,2540,0,0,38.38,4383521.0,1.597648e+15,73044313.0,25.0,SH,150001000.0
3979714,NaN,NaN,NaN,NaN,600132,NaN,NaN,3210168,2.429428e+08,76.40,76.40,76.39,76.38,76.37,76.35,923885,35900,3200,100,800,76.40,0.0,0.000,0.00,0.00,9933,0,0,0,0,73.50,4383530.0,1.597648e+15,73044882.0,25.0,SH,150001000.0
3979715,NaN,NaN,NaN,NaN,601519,NaN,NaN,70895719,7.868347e+08,11.12,11.12,11.11,11.10,11.09,11.08,12646658,179600,260334,36800,50500,11.12,0.0,11.120,0.00,0.00,30100,0,3620100,0,0,11.12,4383560.0,1.597648e+15,73046683.0,25.0,SH,150001000.0
3979716,NaN,NaN,NaN,NaN,603489,NaN,NaN,1501978,2.655850e+08,181.48,181.48,181.47,181.43,181.40,181.36,63600,1300,100,1000,300,181.48,0.0,0.000,0.00,0.00,900,0,0,0,0,168.00,4383601.0,1.597648e+15,73050474.0,25.0,SH,150001000.0
3979717,NaN,NaN,NaN,NaN,600999,NaN,NaN,94259428,2.087382e+09,22.54,22.54,22.53,22.52,22.51,22.50,12299551,45300,145300,10000,38800,22.54,0.0,0.000,0.00,0.00,90546,0,0,0,0,21.61,4383608.0,1.597648e+15,73051622.0,25.0,SH,150001000.0
3979718,NaN,NaN,NaN,NaN,601696,NaN,NaN,66606062,2.111504e+09,32.47,32.47,32.46,32.45,32.44,32.43,6800,220900,23800,400,4900,32.47,0.0,0.000,0.00,0.00,407500,0,0,0,0,30.46,4383679.0,1.597648e+15,73057137.0,25.0,SH,150001000.0
3979719,NaN,NaN,NaN,NaN,600671,NaN,NaN,795000,8.277654e+06,10.56,10.35,10.34,10.33,10.32,10.31,300,10800,1800,4300,6200,10.56,0.0,10.380,10.39,10.40,23418,23418,4000,15200,12100,9.99,4383718.0,1.597648e+15,73059632.0,25.0,SH,150001000.0
3979720,NaN,NaN,NaN,NaN,600178,NaN,NaN,30747692,2.573427e+08,8.49,8.46,0.00,8.45,8.44,8.43,818700,0,24200,39147,88700,8.46,0.0,8.510,8.52,8.53,818700,27800,57600,97700,30200,8.23,4383734.0,1.597648e+15,73064062.0,25.0,SH,150001000.0
3979721,NaN,NaN,NaN,NaN,600179,NaN,NaN,6996053,3.618210e+07,5.11,5.11,0.00,5.07,5.06,5.05,389100,8600,20500,6300,86400,5.11,0.0,5.150,5.16,5.17,389100,0,21000,20000,69600,5.25,4383735.0,1.597648e+15,73064063.0,25.0,SH,150001000.0
3979722,NaN,NaN,NaN,NaN,600210,NaN,NaN,13971813,6.403600e+07,4.60,4.60,0.00,4.57,4.56,4.55,108300,25900,17000,122900,278181,4.60,0.0,4.620,4.63,4.64,108300,0,508100,413500,179100,4.55,4383736.0,1.597648e+15,73064064.0,25.0,SH,150001000.0
3979723,NaN,NaN,NaN,NaN,600479,NaN,NaN,7797360,7.690600e+07,9.90,9.91,0.00,9.87,9.86,9.85,87620,37580,42079,68600,76300,9.91,0.0,9.920,9.93,9.94,87620,0,75100,60400,30400,9.79,4383740.0,1.597648e+15,73064068.0,25.0,SH,150001000.0
3979724,NaN,NaN,NaN,NaN,600730,NaN,NaN,8766002,5.003679e+07,5.75,5.75,0.00,5.72,5.71,5.70,120600,0,21700,84800,120300,5.75,0.0,5.770,5.78,5.79,120600,256112,168000,261700,120500,5.64,4383745.0,1.597648e+15,73064073.0,25.0,SH,150001000.0
3979725,NaN,NaN,NaN,NaN,600746,NaN,NaN,4349020,3.208391e+07,7.42,7.42,0.00,7.39,7.38,7.37,29900,0,26300,26700,54800,7.42,0.0,7.440,7.45,7.46,29900,34640,32000,82976,12600,7.42,4383746.0,1.597648e+15,73064074.0,25.0,SH,150001000.0
3979726,NaN,NaN,NaN,NaN,600771,NaN,NaN,15847510,2.453583e+08,15.62,15.61,0.00,15.58,15.57,15.55,63300,700,15930,8100,10300,15.61,0.0,15.640,15.65,15.66,63300,0,24800,26400,14900,15.01,4383748.0,1.597648e+15,73064076.0,25.0,SH,150001000.0
3979727,NaN,NaN,NaN,NaN,600897,NaN,NaN,2574346,4.714291e+07,18.35,18.37,0.00,18.33,18.32,18.31,34000,0,10466,20800,2100,18.37,0.0,18.390,18.40,18.41,34000,371,1900,2300,10900,18.31,4383751.0,1.597648e+15,73064079.0,25.0,SH,150001000.0
3979728,NaN,NaN,NaN,NaN,603056,NaN,NaN,27719558,4.399398e+08,16.57,16.57,0.00,16.55,16.54,16.53,85230,982994,1400,14000,700,16.57,0.0,0.000,0.00,0.00,85230,0,0,0,0,15.18,4383752.0,1.597648e+15,73064080.0,25.0,SH,150001000.0
3979729,NaN,NaN,NaN,NaN,600096,NaN,NaN,35804010,2.112264e+08,5.97,5.97,0.00,5.94,5.93,5.92,235200,0,12300,22000,22800,5.97,0.0,5.990,6.00,6.01,235200,121900,132600,89100,52000,5.70,4383753.0,1.597648e+15,73064081.0,25.0,SH,150001000.0
3979730,NaN,NaN,NaN,NaN,600173,NaN,NaN,3461909,1.849897e+07,5.37,5.39,0.00,5.34,5.33,5.32,50600,8100,84800,45100,65600,5.39,0.0,5.400,5.41,5.42,50600,0,197800,26500,3200,5.28,4383757.0,1.597648e+15,73064085.0,25.0,SH,150001000.0
3979731,NaN,NaN,NaN,NaN,600115,NaN,NaN,91742707,4.510333e+08,4.91,4.92,0.00,4.88,4.87,4.86,780780,289820,791554,469500,426000,4.92,0.0,4.930,4.94,4.95,780780,0,605400,420300,871700,4.91,4383758.0,1.597648e+15,73064086.0,25.0,SH,150001000.0
3979732,NaN,NaN,NaN,NaN,600131,NaN,NaN,18095212,4.195108e+08,23.16,23.16,0.00,23.13,23.12,23.11,248990,12510,16300,25500,23100,23.16,0.0,23.180,23.19,23.20,248990,0,2400,5300,8500,23.28,4383759.0,1.597648e+15,73064087.0,25.0,SH,150001000.0
3979733,NaN,NaN,NaN,NaN,600145,NaN,NaN,12592835,1.784191e+07,1.41,1.42,0.00,1.39,1.38,1.37,431100,0,315300,92600,50300,1.42,0.0,1.440,1.45,1.46,431100,291230,698140,429500,471150,1.40,4383760.0,1.597648e+15,73064088.0,25.0,SH,150001000.0
3979734,NaN,NaN,NaN,NaN,600176,NaN,NaN,47575707,6.259772e+08,13.30,13.30,0.00,13.27,13.26,13.25,500200,0,15100,9600,8400,13.30,0.0,13.320,13.33,13.34,500200,293870,129600,145200,28100,13.15,4383764.0,1.597648e+15,73064092.0,25.0,SH,150001000.0
3979735,NaN,NaN,NaN,NaN,600220,NaN,NaN,11812785,3.897753e+07,3.31,3.31,0.00,3.28,3.27,3.26,1529526,165774,327000,1003700,654800,3.31,0.0,3.330,3.34,3.35,1529526,0,294192,288600,731300,3.29,4383765.0,1.597648e+15,73064093.0,25.0,SH,150001000.0
3979736,NaN,NaN,NaN,NaN,600232,NaN,NaN,4249483,2.694660e+07,6.37,6.35,0.00,6.34,6.33,6.32,183200,20125,62941,101751,152500,6.35,0.0,6.390,6.40,6.41,183200,0,108400,106600,24100,6.34,4383766.0,1.597648e+15,73064094.0,25.0,SH,150001000.0
3979737,NaN,NaN,NaN,NaN,600476,NaN,NaN,3251709,4.646988e+07,14.38,14.39,0.00,14.35,14.34,14.33,50000,0,18400,4100,4700,14.39,0.0,14.400,14.41,14.42,50000,15600,37600,700,15600,14.15,4383767.0,1.597648e+15,73064095.0,25.0,SH,150001000.0
3979738,NaN,NaN,NaN,NaN,600486,NaN,NaN,3556849,3.306515e+08,93.50,93.55,0.00,93.36,93.34,93.32,39800,0,3500,800,100,93.55,0.0,93.530,93.55,93.58,39800,1300,200,1600,500,94.00,4383768.0,1.597648e+15,73064096.0,25.0,SH,150001000.0
3979739,NaN,NaN,NaN,NaN,600693,NaN,NaN,6611600,3.750208e+07,5.71,5.72,0.00,5.69,5.68,5.67,59600,0,29800,57700,64500,5.72,0.0,5.740,5.75,5.76,59600,47200,45500,123800,93600,5.63,4383775.0,1.597648e+15,73064769.0,25.0,SH,150001000.0
3979740,NaN,NaN,NaN,NaN,600743,NaN,NaN,34395692,7.740275e+07,2.26,2.26,0.00,2.23,2.22,2.21,58300,0,318500,126900,239700,2.26,0.0,2.280,2.29,2.30,58300,602786,501779,469750,577110,2.24,4383776.0,1.597648e+15,73064770.0,25.0,SH,150001000.0
3979741,NaN,NaN,NaN,NaN,600794,NaN,NaN,22048430,7.590808e+07,3.44,3.45,0.00,3.42,3.41,3.40,394800,0,250600,201200,300900,3.45,0.0,3.470,3.48,3.49,394800,392405,700200,472740,668100,3.43,4383779.0,1.597648e+15,73064773.0,25.0,SH,150001000.0
3979742,NaN,NaN,NaN,NaN,600815,NaN,NaN,6703851,1.851603e+07,2.80,2.81,0.00,2.78,2.77,2.76,105100,110000,84900,162800,163400,2.81,0.0,2.830,2.84,0.00,105100,0,331300,784300,0,2.71,4383780.0,1.597648e+15,73064774.0,25.0,SH,150001000.0
3979743,NaN,NaN,NaN,NaN,600869,NaN,NaN,21478730,8.901332e+07,4.16,4.16,0.00,4.14,4.13,4.12,372800,375400,282500,221200,642600,4.16,0.0,4.190,4.20,4.21,372800,0,794800,1012000,217800,4.13,4383781.0,1.597648e+15,73064775.0,25.0,SH,150001000.0
3979744,NaN,NaN,NaN,NaN,600965,NaN,NaN,4789205,3.556427e+07,7.46,7.47,0.00,7.44,7.43,7.42,65600,0,163800,10900,49700,7.47,0.0,7.490,7.50,7.51,65600,105400,50400,61800,10000,7.35,4383782.0,1.597648e+15,73064776.0,25.0,SH,150001000.0
3979745,NaN,NaN,NaN,NaN,600978,NaN,NaN,23459912,2.768943e+07,1.19,1.18,0.00,1.16,1.15,1.14,385700,747800,867500,368800,448100,1.18,0.0,1.210,1.22,1.23,385700,0,2282600,3424200,4218025,1.17,4383784.0,1.597648e+15,73064778.0,25.0,SH,150001000.0
3979746,NaN,NaN,NaN,NaN,600011,NaN,NaN,47655624,2.367924e+08,5.00,5.01,0.00,4.98,4.97,4.96,310400,0,282703,403300,173000,5.01,0.0,5.030,5.04,5.05,310400,75533,1551211,1023400,1345300,4.85,4383785.0,1.597648e+15,73064779.0,25.0,SH,150001000.0
3979747,NaN,NaN,NaN,NaN,600026,NaN,NaN,41104334,3.186682e+08,7.78,7.78,0.00,7.75,7.74,7.73,473043,108257,142900,146393,96800,7.78,0.0,7.800,7.81,7.82,473043,0,557900,173300,349201,7.70,4383786.0,1.597648e+15,73064780.0,25.0,SH,150001000.0
3979748,NaN,NaN,NaN,NaN,600114,NaN,NaN,38861939,4.699822e+08,12.13,12.15,0.00,12.10,12.09,12.08,627398,161902,63100,27600,38900,12.15,0.0,12.150,12.16,12.17,627398,0,82102,53800,110000,12.08,4383788.0,1.597648e+15,73064782.0,25.0,SH,150001000.0
3979749,NaN,NaN,NaN,NaN,600236,NaN,NaN,4892236,2.207373e+07,4.50,4.50,0.00,4.48,4.47,4.46,20507,209250,193200,98000,42600,4.50,0.0,4.530,4.54,4.55,20507,0,116510,243526,389782,4.50,4383789.0,1.597648e+15,73064783.0,25.0,SH,150001000.0
3979750,NaN,NaN,NaN,NaN,600388,NaN,NaN,24339283,2.399092e+08,9.90,9.90,0.00,9.88,9.87,9.86,137850,0,31653,87000,18300,9.90,0.0,9.930,9.94,9.95,137850,32779,34600,40300,179300,9.69,4383792.0,1.597648e+15,73064786.0,25.0,SH,150001000.0
3979751,NaN,NaN,NaN,NaN,600395,NaN,NaN,16376477,1.026301e+08,6.30,6.30,0.00,6.27,6.26,6.25,296900,0,75300,18600,51703,6.30,0.0,6.320,6.33,6.34,296900,64901,168200,61300,72400,6.19,4383793.0,1.597648e+15,73064787.0,25.0,SH,150001000.0
3979752,NaN,NaN,NaN,NaN,600556,NaN,NaN,10150007,2.046499e+08,20.21,20.21,0.00,20.19,20.18,20.17,245500,72100,6000,10300,300,20.21,0.0,20.240,20.25,20.26,245500,0,2700,4400,14800,20.59,4383796.0,1.597648e+15,73064790.0,25.0,SH,150001000.0
3979753,NaN,NaN,NaN,NaN,600636,NaN,NaN,10938348,1.887799e+08,17.35,17.35,0.00,17.32,17.31,17.30,69300,0,6399,5100,1500,17.35,0.0,17.370,17.38,17.39,69300,18000,6800,42100,36300,17.13,4383799.0,1.597648e+15,73064793.0,25.0,SH,150001000.0
3979754,NaN,NaN,NaN,NaN,600691,NaN,NaN,21157753,4.749083e+07,2.25,2.25,0.00,2.22,2.21,2.20,237800,0,161200,142200,273800,2.25,0.0,2.270,2.28,2.29,237800,391080,966700,995600,1259800,2.24,4383803.0,1.597648e+15,73064797.0,25.0,SH,150001000.0
3979755,NaN,NaN,NaN,NaN,600706,NaN,NaN,3108799,2.607498e+07,8.36,8.36,0.00,8.33,8.32,8.31,86880,73920,68700,12149,11300,8.36,0.0,8.380,8.39,8.40,86880,0,14200,22293,8400,8.33,4383805.0,1.597648e+15,73064799.0,25.0,SH,150001000.0
3979756,NaN,NaN,NaN,NaN,600715,NaN,NaN,23200561,7.304303e+07,3.22,3.22,0.00,3.19,3.18,3.17,456300,0,245700,378900,93000,3.22,0.0,3.240,3.25,3.26,456300,169100,37100,169100,33500,3.16,4383807.0,1.597648e+15,73064801.0,25.0,SH,150001000.0
3979757,NaN,NaN,NaN,NaN,600726,NaN,NaN,12049942,2.552973e+07,2.13,2.12,0.00,2.10,2.09,2.08,230700,1007700,962959,257300,213800,2.12,0.0,2.150,2.16,2.17,230700,0,928800,688800,288800,2.12,4383808.0,1.597648e+15,73064802.0,25.0,SH,150001000.0
3979758,NaN,NaN,NaN,NaN,600782,NaN,NaN,44133485,1.970959e+08,4.48,4.48,0.00,4.46,4.45,4.44,322636,416207,770600,306400,387000,4.48,0.0,4.510,4.52,4.53,322636,0,1381900,1616200,245900,4.43,4383809.0,1.597648e+15,73064803.0,25.0,SH,150001000.0
3979759,NaN,NaN,NaN,NaN,600877,NaN,NaN,9392804,6.087641e+07,6.50,6.47,0.00,6.47,6.46,6.45,336300,3976,45400,86100,99400,6.47,0.0,6.520,6.53,6.54,336300,0,28394,66900,79200,6.55,4383811.0,1.597648e+15,73064805.0,25.0,SH,150001000.0
3979760,NaN,NaN,NaN,NaN,600883,NaN,NaN,3271190,3.112822e+07,9.50,9.52,0.00,9.48,9.47,9.45,77700,31700,11000,400,8000,9.52,0.0,9.580,9.59,9.60,77700,0,10100,7800,14500,9.60,4383812.0,1.597648e+15,73064806.0,25.0,SH,150001000.0
3979761,NaN,NaN,NaN,NaN,600982,NaN,NaN,9831156,3.001307e+07,3.06,3.07,0.00,3.04,3.03,3.02,111200,0,107100,210100,295200,3.07,0.0,3.090,3.10,3.11,111200,459700,184200,563000,44900,3.08,4383814.0,1.597648e+15,73064808.0,25.0,SH,150001000.0
3979762,NaN,NaN,NaN,NaN,601010,NaN,NaN,37964577,1.320067e+08,3.47,3.47,0.00,3.45,3.44,3.43,1204100,255500,1000573,213800,258600,3.47,0.0,3.500,3.51,3.52,1204100,0,729100,379600,239800,3.45,4383816.0,1.597648e+15,73064810.0,25.0,SH,150001000.0
3979763,NaN,NaN,NaN,NaN,601238,NaN,NaN,25814471,2.798654e+08,10.83,10.86,0.00,10.81,10.80,10.79,416543,150457,88700,72800,10200,10.86,0.0,10.870,10.88,10.89,416543,0,16000,63109,45404,10.63,4383820.0,1.597648e+15,73064814.0,25.0,SH,150001000.0
3979764,NaN,NaN,NaN,NaN,601339,NaN,NaN,9041600,3.524881e+07,3.90,3.90,0.00,3.87,3.86,3.85,302400,0,100100,139200,117000,3.90,0.0,3.920,3.93,3.94,302400,116821,481400,286800,233588,3.86,4383821.0,1.597648e+15,73064815.0,25.0,SH,150001000.0
3979765,NaN,NaN,NaN,NaN,601799,NaN,NaN,1395673,2.154049e+08,153.99,153.88,0.00,153.95,153.92,153.91,13816,1936,100,200,100,153.88,0.0,154.380,154.45,154.49,13816,0,100,100,200,157.02,4383823.0,1.597648e+15,73064817.0,25.0,SH,150001000.0
3979766,NaN,NaN,NaN,NaN,603508,NaN,NaN,4241083,1.587851e+08,37.81,37.81,0.00,37.77,37.76,37.75,58400,0,900,800,6600,37.81,0.0,37.830,37.84,37.85,58400,3260,5200,4300,6300,36.84,4383830.0,1.597648e+15,73064824.0,25.0,SH,150001000.0
3979767,NaN,NaN,NaN,NaN,603566,NaN,NaN,9773443,2.833881e+08,28.62,28.64,0.00,28.58,28.57,28.55,87700,2800,5000,100,300,28.64,0.0,28.660,28.68,28.72,87700,0,300,1500,200,29.00,4383831.0,1.597648e+15,73064825.0,25.0,SH,150001000.0
3979768,NaN,NaN,NaN,NaN,603583,NaN,NaN,2579223,1.710614e+08,66.21,66.22,0.00,66.04,66.03,66.02,12400,0,400,1000,500,66.22,0.0,66.250,66.30,66.32,12400,2600,600,1600,20000,68.26,4383832.0,1.597648e+15,73064826.0,25.0,SH,150001000.0
3979769,NaN,NaN,NaN,NaN,603599,NaN,NaN,7376340,1.259389e+08,17.11,17.14,0.00,17.09,17.08,17.07,113900,16200,7192,7300,10700,17.14,0.0,17.140,17.15,17.16,113900,0,10400,22200,3000,17.06,4383834.0,1.597648e+15,73064828.0,25.0,SH,150001000.0
3979770,NaN,NaN,NaN,NaN,603618,NaN,NaN,17419090,1.097724e+08,6.33,6.34,0.00,6.31,6.30,6.29,411400,44500,32900,43800,75300,6.34,0.0,6.360,6.37,6.38,411400,0,123300,97700,177000,6.35,4383837.0,1.597648e+15,73064831.0,25.0,SH,150001000.0
3979771,NaN,NaN,NaN,NaN,603686,NaN,NaN,14909391,4.286843e+08,29.03,29.06,0.00,29.01,29.00,28.99,127000,0,4100,17100,3000,29.06,0.0,29.070,29.08,29.09,127000,2811,3000,15400,8160,27.20,4383839.0,1.597648e+15,73064833.0,25.0,SH,150001000.0
3979772,NaN,NaN,NaN,NaN,603716,NaN,NaN,1934059,3.172341e+07,16.58,16.63,0.00,16.47,16.46,16.45,45600,0,3700,1200,2000,16.63,0.0,16.610,16.62,16.63,45600,470,4100,200,500,16.18,4383841.0,1.597648e+15,73064835.0,25.0,SH,150001000.0
3979773,NaN,NaN,NaN,NaN,603717,NaN,NaN,3206760,2.710856e+07,8.50,8.49,0.00,8.47,8.46,8.45,45400,19600,20800,8600,58400,8.49,0.0,8.520,8.53,8.54,45400,0,19400,29500,22000,8.39,4383842.0,1.597648e+15,73064836.0,25.0,SH,150001000.0
3979774,NaN,NaN,NaN,NaN,603719,NaN,NaN,2019343,1.462015e+08,72.90,72.91,0.00,72.87,72.86,72.85,34800,20400,100,4200,2500,72.91,0.0,72.930,72.95,72.96,34800,0,400,500,500,72.70,4383843.0,1.597648e+15,73064837.0,25.0,SH,150001000.0
3979775,NaN,NaN,NaN,NaN,603766,NaN,NaN,56107458,2.612668e+08,4.73,4.72,0.00,4.70,4.69,4.68,353827,43491,400400,110500,139452,4.72,0.0,4.750,4.76,4.77,353827,0,613550,467800,354700,4.53,4383845.0,1.597648e+15,73064839.0,25.0,SH,150001000.0
3979776,NaN,NaN,NaN,NaN,603806,NaN,NaN,6216277,4.294159e+08,69.66,69.66,0.00,69.62,69.61,69.60,58150,10250,100,900,2300,69.66,0.0,69.720,69.74,69.75,58150,0,900,200,300,71.50,4383846.0,1.597648e+15,73064840.0,25.0,SH,150001000.0
3979777,NaN,NaN,NaN,NaN,603889,NaN,NaN,4863440,2.698837e+07,5.57,5.57,0.00,5.55,5.54,5.53,35000,207740,25500,53000,78400,5.57,0.0,5.600,5.61,5.62,35000,0,122360,64600,114400,5.49,4383849.0,1.597648e+15,73064843.0,25.0,SH,150001000.0
3979778,NaN,NaN,NaN,NaN,603928,NaN,NaN,1485000,1.819594e+07,12.30,12.30,0.00,12.28,12.27,12.25,15000,11600,13600,5000,6100,12.30,0.0,12.330,12.34,12.35,15000,0,13400,12500,17800,12.17,4383852.0,1.597648e+15,73064846.0,25.0,SH,150001000.0
3979779,NaN,NaN,NaN,NaN,603956,NaN,NaN,4745501,8.643359e+07,18.28,18.29,0.00,18.25,18.24,18.22,56083,2817,200,2100,800,18.29,0.0,18.310,18.32,18.33,56083,0,1600,500,8300,18.02,4383854.0,1.597648e+15,73064848.0,25.0,SH,150001000.0
3979780,NaN,NaN,NaN,NaN,603987,NaN,NaN,19514156,3.695839e+08,19.53,19.55,0.00,19.50,19.49,19.48,235100,0,20100,5000,15500,19.55,0.0,19.550,19.56,19.57,235100,35960,49400,9600,6100,18.34,4383858.0,1.597648e+15,73064852.0,25.0,SH,150001000.0
3979781,NaN,NaN,NaN,NaN,603990,NaN,NaN,2168858,1.041762e+08,48.03,48.03,0.00,47.97,47.96,47.95,13500,14100,7604,3400,600,48.03,0.0,48.060,48.07,48.08,13500,0,2000,6900,6300,47.80,4383859.0,1.597648e+15,73064853.0,25.0,SH,150001000.0
3979782,NaN,NaN,NaN,NaN,688019,NaN,NaN,535537,2.197732e+08,413.55,414.00,0.00,413.50,413.46,413.45,12548,0,150,200,660,414.00,0.0,413.980,413.99,414.00,12548,3493,230,200,1900,411.00,4383862.0,1.597648e+15,73064856.0,25.0,SH,150001000.0
3979783,NaN,NaN,NaN,NaN,688086,NaN,NaN,1633381,9.921902e+07,60.90,60.92,0.00,60.79,60.76,60.70,12545,9650,37917,2664,137,60.92,0.0,60.930,60.94,60.95,12545,0,1800,6085,3000,61.09,4383863.0,1.597648e+15,73064857.0,25.0,SH,150001000.0
3979784,NaN,NaN,NaN,NaN,688088,NaN,NaN,3186120,2.194881e+08,70.10,70.10,0.00,70.00,69.99,69.98,91698,0,2944,823,500,70.10,0.0,70.130,70.16,70.18,91698,18430,400,2200,1587,67.00,4383864.0,1.597648e+15,73064858.0,25.0,SH,150001000.0
3979785,NaN,NaN,NaN,NaN,688089,NaN,NaN,1872988,1.016530e+08,53.85,54.04,0.00,53.82,53.81,53.70,31806,0,600,1400,5340,54.04,0.0,53.940,54.00,54.05,31806,21990,480,2134,2500,54.14,4383865.0,1.597648e+15,73064859.0,25.0,SH,150001000.0
3979786,NaN,NaN,NaN,NaN,688108,NaN,NaN,2457919,7.002733e+07,28.97,29.09,0.00,28.95,28.93,28.92,50723,26295,4802,2135,2748,29.09,0.0,29.030,29.04,29.05,50723,0,3500,3000,1700,28.27,4383866.0,1.597648e+15,73064860.0,25.0,SH,150001000.0
3979787,NaN,NaN,NaN,NaN,688128,NaN,NaN,1500441,3.370215e+07,22.54,22.52,0.00,22.51,22.50,22.48,10109,19031,2483,11600,4158,22.52,0.0,22.560,22.58,22.59,10109,0,365,6000,700,22.26,4383867.0,1.597648e+15,73064861.0,25.0,SH,150001000.0
3979788,NaN,NaN,NaN,NaN,688199,NaN,NaN,632647,3.833721e+07,60.76,60.89,0.00,60.73,60.70,60.65,5665,0,200,500,300,60.89,0.0,60.990,61.00,61.09,5665,6403,500,2700,12,60.17,4383868.0,1.597648e+15,73064862.0,25.0,SH,150001000.0
3979789,NaN,NaN,NaN,NaN,688311,NaN,NaN,3577527,5.838620e+08,165.50,165.50,0.00,165.05,165.02,165.00,35077,3013,500,1194,200,165.50,0.0,165.670,165.69,165.70,35077,0,1366,1000,1000,163.58,4383871.0,1.597648e+15,73064865.0,25.0,SH,150001000.0
3979790,NaN,NaN,NaN,NaN,688500,NaN,NaN,768261,4.682394e+07,61.27,61.30,0.00,61.25,61.24,61.23,14392,3590,3000,10226,1612,61.30,0.0,61.350,61.36,61.37,14392,0,939,2496,3470,60.35,4383872.0,1.597648e+15,73064866.0,25.0,SH,150001000.0

In [95]:
test[np.isnan(test["sequenceNo_y"]) & (test['time_x'] != 105631000.0)].groupby('StockID')['cum_volume'].size().sort_values(ascending=False)

StockID
601086    1630
601519    1531
603393    1379
600226    1297
600255     892
600118     742
600083     391
603555     315
603661     284
603161     273
600330     249
600095     219
600290     168
603758     147
600234     125
601456      86
603959      54
603313      45
600543      43
600343      40
600158      35
603027       8
600166       5
600354       3
600247       3
600275       3
600719       1
688080       1
Name: cum_volume, dtype: int64

In [113]:
test[np.isnan(test["sequenceNo_y"]) & (test['StockID'] == 600158)]

,index_x,clockAtArrival_x,sequenceNo_x,source_x,StockID,exchange_x,time_x,cum_volume,cum_amount,close,bid1p,bid2p,bid3p,bid4p,bid5p,bid1q,bid2q,bid3q,bid4q,bid5q,ask1p,ask2p,ask3p,ask4p,ask5p,ask1q,ask2q,ask3q,ask4q,ask5q,openPrice,index_y,clockAtArrival_y,sequenceNo_y,source_y,exchange_y,time_y
1283601,2982207.0,1.597630e+15,69583292.0,23.0,600158,SH,101059000.0,48509930,5.707452e+08,11.96,11.96,11.95,11.94,11.93,11.92,85084,67182,17000,58500,1500,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,11.35,NaN,NaN,NaN,NaN,NaN,NaN
1284981,2985180.0,1.597630e+15,69639087.0,23.0,600158,SH,101102000.0,48534230,5.710358e+08,11.96,11.96,11.95,11.94,11.93,11.92,408984,68182,17000,58500,1500,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,11.35,NaN,NaN,NaN,NaN,NaN,NaN
1286371,2988157.0,1.597630e+15,69707386.0,23.0,600158,SH,101105000.0,48545930,5.711758e+08,11.96,11.96,11.95,11.94,11.93,11.92,794184,98182,17000,58500,1500,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,11.35,NaN,NaN,NaN,NaN,NaN,NaN
1287759,2991147.0,1.597630e+15,69766276.0,23.0,600158,SH,101108000.0,48579530,5.715776e+08,11.96,11.96,11.95,11.94,11.93,11.92,899384,98182,17000,59000,1500,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,11.35,NaN,NaN,NaN,NaN,NaN,NaN
1289140,2994121.0,1.597630e+15,69822984.0,23.0,600158,SH,101111000.0,48580430,5.715884e+08,11.96,11.96,11.95,11.94,11.93,11.92,1207984,101582,17000,59000,1500,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,11.35,NaN,NaN,NaN,NaN,NaN,NaN
1290532,2997108.0,1.597630e+15,69878393.0,23.0,600158,SH,101114000.0,48586130,5.716566e+08,11.96,11.96,11.95,11.94,11.93,11.92,1608484,101282,17000,59000,1500,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,11.35,NaN,NaN,NaN,NaN,NaN,NaN
1291930,3000071.0,1.597630e+15,69933542.0,23.0,600158,SH,101117000.0,48596630,5.717822e+08,11.96,11.96,11.95,11.94,11.93,11.92,1904184,100482,17000,67700,1500,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,11.35,NaN,NaN,NaN,NaN,NaN,NaN
1293298,3003032.0,1.597630e+15,69985667.0,23.0,600158,SH,101120000.0,48600630,5.718300e+08,11.96,11.96,11.95,11.94,11.93,11.92,2167284,100482,17000,59000,1500,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,11.35,NaN,NaN,NaN,NaN,NaN,NaN
1294651,3005976.0,1.597630e+15,70039085.0,23.0,600158,SH,101123000.0,48606230,5.718970e+08,11.96,11.96,11.95,11.94,11.93,11.92,3070984,97882,17000,59000,1500,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,11.35,NaN,NaN,NaN,NaN,NaN,NaN
1296032,3008915.0,1.597630e+15,70093360.0,23.0,600158,SH,101126000.0,48607630,5.719137e+08,11.96,11.96,11.95,11.94,11.93,11.92,3295784,97882,17000,59000,1500,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,11.35,NaN,NaN,NaN,NaN,NaN,NaN
1297410,3011881.0,1.597630e+15,70145758.0,23.0,600158,SH,101129000.0,48607830,5.719161e+08,11.96,11.96,11.95,11.94,11.93,11.92,3327884,97882,17000,59000,1000,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,11.35,NaN,NaN,NaN,NaN,NaN,NaN
1298787,3014872.0,1.597630e+15,70199273.0,23.0,600158,SH,101132000.0,48608330,5.719221e+08,11.96,11.96,11.95,11.94,11.93,11.92,3393584,97882,16800,59000,1000,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,11.35,NaN,NaN,NaN,NaN,NaN,NaN
1300168,3017805.0,1.597630e+15,70250384.0,23.0,600158,SH,101135000.0,48611630,5.719616e+08,11.96,11.96,11.95,11.94,11.93,11.92,3398884,107882,16800,59000,1000,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,11.35,NaN,NaN,NaN,NaN,NaN,NaN
1301503,3020699.0,1.597630e+15,70302866.0,23.0,600158,SH,101138000.0,48612530,5.719723e+08,11.96,11.96,11.95,11.94,11.93,11.92,3392684,107882,16700,59000,1000,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,11.35,NaN,NaN,NaN,NaN,NaN,NaN
1302860,3023612.0,1.597630e+15,70354561.0,23.0,600158,SH,101141000.0,48617830,5.720357e+08,11.96,11.96,11.95,11.94,11.93,11.92,3382184,107882,16700,59000,1000,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,11.35,NaN,NaN,NaN,NaN,NaN,NaN
1304218,3026563.0,1.597630e+15,70406452.0,23.0,600158,SH,101144000.0,48830530,5.745796e+08,11.96,11.96,11.95,11.94,11.93,11.92,3139684,107882,16700,59000,1000,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,11.35,NaN,NaN,NaN,NaN,NaN,NaN
1305594,3029512.0,1.597630e+15,70456949.0,23.0,600158,SH,101147000.0,48850530,5.748188e+08,11.96,11.96,11.95,11.94,11.93,11.92,2168584,107100,16700,59000,1000,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,11.35,NaN,NaN,NaN,NaN,NaN,NaN
1307521,3033130.0,1.597630e+15,70519204.0,23.0,600158,SH,101151000.0,48850630,5.748200e+08,11.96,11.96,11.95,11.94,11.93,11.92,956484,106600,16700,59000,1000,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,11.35,NaN,NaN,NaN,NaN,NaN,NaN
1308783,3035995.0,1.597630e+15,70568427.0,23.0,600158,SH,101153000.0,48861830,5.749539e+08,11.96,11.96,11.95,11.94,11.93,11.92,756784,106600,18400,59000,1000,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,11.35,NaN,NaN,NaN,NaN,NaN,NaN
1309916,3038645.0,1.597630e+15,70614172.0,23.0,600158,SH,101156000.0,48862730,5.749647e+08,11.96,11.96,11.95,11.94,11.93,11.92,612884,106600,18400,59000,1000,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,11.35,NaN,NaN,NaN,NaN,NaN,NaN
1311297,3041631.0,1.597630e+15,70667652.0,23.0,600158,SH,101159000.0,48870430,5.750568e+08,11.96,11.96,11.95,11.94,11.93,11.92,567284,106600,18400,59000,1000,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,11.35,NaN,NaN,NaN,NaN,NaN,NaN
1312696,3044600.0,1.597630e+15,70720387.0,23.0,600158,SH,101202000.0,48871130,5.750652e+08,11.96,11.96,11.95,11.94,11.93,11.92,462284,106600,18400,59000,1000,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,11.35,NaN,NaN,NaN,NaN,NaN,NaN
1314055,3047531.0,1.597630e+15,70783330.0,23.0,600158,SH,101205000.0,48936130,5.758426e+08,11.96,11.96,11.95,11.94,11.93,11.92,393284,106600,18400,59000,1000,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,11.35,NaN,NaN,NaN,NaN,NaN,NaN
1315452,3050521.0,1.597630e+15,70838522.0,23.0,600158,SH,101208000.0,48997830,5.765805e+08,11.96,11.96,11.95,11.94,11.93,11.92,325384,106600,21300,59000,1000,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,11.35,NaN,NaN,NaN,NaN,NaN,NaN
1316817,3053497.0,1.597630e+15,70891423.0,23.0,600158,SH,101211000.0,49047830,5.771785e+08,11.96,11.96,11.95,11.94,11.93,11.92,279884,106600,21300,59000,1000,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,11.35,NaN,NaN,NaN,NaN,NaN,NaN
1318169,3056351.0,1.597630e+15,70943348.0,23.0,600158,SH,101214000.0,49074530,5.774978e+08,11.96,11.96,11.95,11.94,11.93,11.92,255484,106600,21300,59000,1000,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,11.35,NaN,NaN,NaN,NaN,NaN,NaN
1319543,3059314.0,1.597630e+15,70993629.0,23.0,600158,SH,101217000.0,49096530,5.777610e+08,11.96,11.96,11.95,11.94,11.93,11.92,233584,106600,16300,59000,1000,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,11.35,NaN,NaN,NaN,NaN,NaN,NaN
1320905,3062313.0,1.597630e+15,71044249.0,23.0,600158,SH,101220000.0,49099230,5.777932e+08,11.96,11.96,11.95,11.94,11.93,11.92,218284,106600,16300,59000,1000,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,11.35,NaN,NaN,NaN,NaN,NaN,NaN
1322259,3065244.0,1.597630e+15,71097386.0,23.0,600158,SH,101223000.0,49126630,5.781210e+08,11.96,11.96,11.95,11.94,11.93,11.92,193184,106600,16300,59000,1000,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,11.35,NaN,NaN,NaN,NaN,NaN,NaN
1323633,3068188.0,1.597630e+15,71149759.0,23.0,600158,SH,101226000.0,49150630,5.784080e+08,11.96,11.96,11.95,11.94,11.93,11.92,182484,104300,16300,59000,1000,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,11.35,NaN,NaN,NaN,NaN,NaN,NaN
1324982,3071124.0,1.597630e+15,71200731.0,23.0,600158,SH,101229000.0,49163830,5.785659e+08,11.96,11.96,11.95,11.94,11.93,11.92,169584,104300,16300,59000,1000,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,11.35,NaN,NaN,NaN,NaN,NaN,NaN
1326334,3074045.0,1.597630e+15,71252340.0,23.0,600158,SH,101232000.0,49302930,5.802295e+08,11.96,11.96,11.95,11.94,11.93,11.92,32784,104300,13400,59000,1000,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,11.35,NaN,NaN,NaN,NaN,NaN,NaN
1327673,3076994.0,1.597630e+15,71302205.0,23.0,600158,SH,101235000.0,49308330,5.802941e+08,11.96,11.96,11.95,11.94,11.93,11.92,40084,104300,13400,59000,1000,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,11.35,NaN,NaN,NaN,NaN,NaN,NaN
1329004,3079862.0,1.597630e+15,71351434.0,23.0,600158,SH,101238000.0,49320030,5.804340e+08,11.96,11.96,11.95,11.94,11.93,11.92,26484,104300,13400,59000,1000,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,11.35,NaN,NaN,NaN,NaN,NaN,NaN
1330340,3082776.0,1.597630e+15,71400258.0,23.0,600158,SH,101241000.0,49336130,5.806266e+08,11.96,11.96,11.95,11.94,11.93,11.92,10084,104300,13400,59000,1000,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,11.35,NaN,NaN,NaN,NaN,NaN,NaN

In [118]:
logSH[(logSH['StockID'] == 600158) & (logSH['time'] >= 101056000.0) & (logSH['source'] == 23)][['StockID', 'time',
                                                                                  'cum_volume', 'cum_amount', 'close', 
           "bid1p", "bid2p", "bid1q", "bid2q","ask1p", "ask2p", "ask1q", "ask2q", "openPrice"]].head(20)

,StockID,time,cum_volume,cum_amount,close,bid1p,bid2p,bid1q,bid2q,ask1p,ask2p,ask1q,ask2q,openPrice
2979260,600158,101056000,48383414,5.692321e+08,11.96,11.95,11.94,60682,16800,11.96,0.0,112816,0,11.35
2982207,600158,101059000,48509930,5.707452e+08,11.96,11.96,11.95,85084,67182,0.00,0.0,0,0,11.35
2985180,600158,101102000,48534230,5.710358e+08,11.96,11.96,11.95,408984,68182,0.00,0.0,0,0,11.35
2988157,600158,101105000,48545930,5.711758e+08,11.96,11.96,11.95,794184,98182,0.00,0.0,0,0,11.35
2991147,600158,101108000,48579530,5.715776e+08,11.96,11.96,11.95,899384,98182,0.00,0.0,0,0,11.35
2994121,600158,101111000,48580430,5.715884e+08,11.96,11.96,11.95,1207984,101582,0.00,0.0,0,0,11.35
2997108,600158,101114000,48586130,5.716566e+08,11.96,11.96,11.95,1608484,101282,0.00,0.0,0,0,11.35
3000071,600158,101117000,48596630,5.717822e+08,11.96,11.96,11.95,1904184,100482,0.00,0.0,0,0,11.35
3003032,600158,101120000,48600630,5.718300e+08,11.96,11.96,11.95,2167284,100482,0.00,0.0,0,0,11.35
3005976,600158,101123000,48606230,5.718970e+08,11.96,11.96,11.95,3070984,97882,0.00,0.0,0,0,11.35
3008915,600158,101126000,48607630,5.719137e+08,11.96,11.96,11.95,3295784,97882,0.00,0.0,0,0,11.35
3011881,600158,101129000,48607830,5.719161e+08,11.96,11.96,11.95,3327884,97882,0.00,0.0,0,0,11.35
3014872,600158,101132000,48608330,5.719221e+08,11.96,11.96,11.95,3393584,97882,0.00,0.0,0,0,11.35
3017805,600158,101135000,48611630,5.719616e+08,11.96,11.96,11.95,3398884,107882,0.00,0.0,0,0,11.35
3020699,600158,101138000,48612530,5.719723e+08,11.96,11.96,11.95,3392684,107882,0.00,0.0,0,0,11.35
3023612,600158,101141000,48617830,5.720357e+08,11.96,11.96,11.95,3382184,107882,0.00,0.0,0,0,11.35
3026563,600158,101144000,48830530,5.745796e+08,11.96,11.96,11.95,3139684,107882,0.00,0.0,0,0,11.35
3029512,600158,101147000,48850530,5.748188e+08,11.96,11.96,11.95,2168584,107100,0.00,0.0,0,0,11.35
3033130,600158,101151000,48850630,5.748200e+08,11.96,11.96,11.95,956484,106600,0.00,0.0,0,0,11.35
3035995,600158,101153000,48861830,5.749539e+08,11.96,11.96,11.95,756784,106600,0.00,0.0,0,0,11.35

In [120]:
logSH1[(logSH1['StockID'] == 600158) & (logSH1['time'] >= 101050000.0)][['StockID', 'time',
                                                                                  'cum_volume', 'cum_amount', 'close', 
           "bid1p", "bid2p", "bid1q", "bid2q","ask1p", "ask2p", "ask1q", "ask2q", "openPrice"]].head(10)

,StockID,time,cum_volume,cum_amount,close,bid1p,bid2p,bid1q,bid2q,ask1p,ask2p,ask1q,ask2q,openPrice
1429136,600158,101050000,47976914,5.643705e+08,11.96,11.95,11.94,75082,16800,11.96,0.0,465116,0,11.35
1430607,600158,101053000,47978514,5.643896e+08,11.96,11.95,11.94,73982,16800,11.96,0.0,483216,0,11.35
1432083,600158,101056000,48383414,5.692321e+08,11.96,11.95,11.94,60682,16800,11.96,0.0,112816,0,11.35
1433544,600158,101059000,48509930,5.707452e+08,11.96,11.96,11.95,85084,67182,11.96,0.0,1266716,0,11.35
1435027,600158,101102000,48534230,5.710358e+08,11.96,11.96,11.95,408984,68182,11.96,0.0,1266716,0,11.35
1436503,600158,101105000,48545930,5.711758e+08,11.96,11.96,11.95,794184,98182,11.96,0.0,1266716,0,11.35
1437979,600158,101108000,48579530,5.715776e+08,11.96,11.96,11.95,899384,98182,11.96,0.0,1266716,0,11.35
1439463,600158,101111000,48580430,5.715884e+08,11.96,11.96,11.95,1207984,101582,11.96,0.0,1266716,0,11.35
1440938,600158,101114000,48586130,5.716566e+08,11.96,11.96,11.95,1608484,101282,11.96,0.0,1266716,0,11.35
1442425,600158,101117000,48596630,5.717822e+08,11.96,11.96,11.95,1904184,100482,11.96,0.0,1266716,0,11.35

In [51]:
logSH[(logSH['StockID'] == 603628) & (logSH['time'] >= 93000000) & (logSH['source'] == 23)][['StockID', 'time',
                                                                                  'cum_volume', 'cum_amount', 'close', 
           "bid1p", "bid2p", "bid1q", "bid2q","ask1p", "ask2p", "ask1q", "ask2q", "openPrice"]].head(5)

,StockID,time,cum_volume,cum_amount,close,bid1p,bid2p,bid1q,bid2q,ask1p,ask2p,ask1q,ask2q,openPrice
431464,603628,93000000,0,0.0,0.00,9.11,9.02,2400,7500,9.12,9.13,4100,2000,0.00
433473,603628,93003000,800,7288.0,9.11,9.11,9.02,1600,7500,9.12,9.13,100,2000,0.00
436677,603628,93006000,7000,63770.0,9.11,9.04,9.02,2400,8500,9.11,9.12,6100,100,9.11
440243,603628,93008000,18400,167625.0,9.11,9.11,9.04,8400,2400,9.12,9.13,10500,2000,9.11
443829,603628,93011000,24500,223207.0,9.11,9.11,9.04,3400,2600,9.12,9.13,9400,2000,9.11

In [53]:
logSH1[(logSH1['StockID'] == 603628) & (logSH1['time'] >= 93000000)][['StockID', 'time',
                                                                                  'cum_volume', 'cum_amount', 'close', 
           "bid1p", "bid2p", "bid1q", "bid2q", "ask1p", "ask2p", "ask1q", "ask2q", "openPrice"]].head(5)

,StockID,time,cum_volume,cum_amount,close,bid1p,bid2p,bid1q,bid2q,ask1p,ask2p,ask1q,ask2q,openPrice
168955,603628,93000000,0,0.0,0.00,9.11,9.02,2400,7500,9.12,9.13,4100,2000,0.00
169984,603628,93003000,800,7288.0,9.11,9.11,9.02,1600,7500,9.12,9.13,100,2000,9.11
171514,603628,93006000,7000,63770.0,9.11,9.04,9.02,2400,8500,9.11,9.12,6100,100,9.11
173254,603628,93008000,18400,167625.0,9.11,9.11,9.04,8400,2400,9.12,9.13,10500,2000,9.11
175003,603628,93011000,24500,223207.0,9.11,9.11,9.04,3400,2600,9.12,9.13,9400,2000,9.11

In [14]:
test[np.isnan(test["sequenceNo_x"])].head(20)

,index_x,clockAtArrival_x,sequenceNo_x,source_x,StockID,exchange_x,time_x,cum_volume,cum_amount,close,bid1p,bid2p,bid3p,bid4p,bid5p,bid1q,bid2q,bid3q,bid4q,bid5q,ask1p,ask2p,ask3p,ask4p,ask5p,ask1q,ask2q,ask3q,ask4q,ask5q,openPrice,index_y,clockAtArrival_y,sequenceNo_y,source_y,exchange_y,time_y
2468048,NaN,NaN,NaN,NaN,600354,NaN,NaN,4479600,17694420.0,3.95,3.95,0.00,0.00,0.00,0.00,4479600,0,0,0,0,3.95,3.96,4.05,4.08,4.09,264994,14900,5000,44100,10300,0.00,156112.0,1.597628e+15,1613328.0,25.0,SH,92500000.0
2468049,NaN,NaN,NaN,NaN,601519,NaN,NaN,6118400,68036608.0,11.12,11.11,11.10,11.09,11.08,11.07,15700,14700,500,1800,2200,11.12,0.00,0.00,0.00,0.00,2882700,2599500,0,0,0,0.00,156116.0,1.597628e+15,1614733.0,25.0,SH,92500000.0
2468050,NaN,NaN,NaN,NaN,600095,NaN,NaN,5688800,93922088.0,16.51,16.50,16.48,16.47,16.46,16.44,67200,2200,300,2600,700,16.51,0.00,0.00,0.00,0.00,798599,798599,0,0,0,0.00,156145.0,1.597628e+15,1627054.0,25.0,SH,92500000.0
2468051,NaN,NaN,NaN,NaN,601086,NaN,NaN,1219800,7513968.0,6.16,6.16,0.00,0.00,0.00,0.00,1219800,0,0,0,0,6.16,6.17,6.18,6.20,6.22,17078473,8500,400,15300,29000,0.00,156203.0,1.597628e+15,1632394.0,25.0,SH,92500000.0
2468052,NaN,NaN,NaN,NaN,601519,NaN,NaN,6118400,68036608.0,11.12,11.11,11.10,11.09,11.08,11.07,15700,14700,500,1800,2200,11.12,0.00,0.00,0.00,0.00,2882700,2599500,0,0,0,11.12,156354.0,1.597628e+15,1635487.0,25.0,SH,92500000.0
2468053,NaN,NaN,NaN,NaN,600247,NaN,NaN,1708600,3998124.0,2.34,2.33,2.32,2.31,2.28,2.27,36800,5800,1700,10300,2000,2.34,0.00,0.00,0.00,0.00,1157720,1157720,0,0,0,0.00,156824.0,1.597628e+15,1650313.0,25.0,SH,92501000.0
2468054,NaN,NaN,NaN,NaN,600226,NaN,NaN,1741100,2246019.0,1.29,1.29,1.28,1.27,1.26,1.25,17903000,143300,123700,340400,190100,1.29,0.00,0.00,0.00,0.00,1741100,0,0,0,0,0.00,157454.0,1.597628e+15,1657640.0,25.0,SH,92501000.0
2468055,NaN,NaN,NaN,NaN,600166,NaN,NaN,36960200,104227764.0,2.82,2.82,0.00,0.00,0.00,0.00,36960200,0,0,0,0,2.82,2.83,2.84,2.85,2.86,12567992,232000,448700,1127452,229600,0.00,157468.0,1.597628e+15,1657750.0,25.0,SH,92501000.0
2468056,NaN,NaN,NaN,NaN,603393,NaN,NaN,744800,22559992.0,30.29,30.29,0.00,0.00,0.00,0.00,744800,0,0,0,0,30.29,30.30,30.50,31.00,31.31,28746233,137208,6500,2500,15000,0.00,157687.0,1.597628e+15,1670325.0,25.0,SH,92502000.0
2468057,NaN,NaN,NaN,NaN,600275,NaN,NaN,1314800,3957548.0,3.01,3.01,0.00,0.00,0.00,0.00,312500,312500,0,0,0,3.05,3.10,3.12,3.13,3.14,4000,11200,2000,2000,2000,0.00,157831.0,1.597628e+15,1675461.0,25.0,SH,92502000.0
2468058,NaN,NaN,NaN,NaN,603027,NaN,NaN,1853300,71352050.0,38.50,38.49,38.45,38.26,38.20,38.05,700,200,5000,800,3700,38.50,0.00,0.00,0.00,0.00,91835,91835,0,0,0,0.00,157917.0,1.597628e+15,1686005.0,25.0,SH,92502000.0
2468059,NaN,NaN,NaN,NaN,600166,NaN,NaN,36960200,104227764.0,2.82,2.82,0.00,0.00,0.00,0.00,36960200,0,0,0,0,2.82,2.83,2.84,2.85,2.86,12567992,232000,448700,1127452,229600,2.82,158641.0,1.597628e+15,1776307.0,25.0,SH,92503000.0
2468060,NaN,NaN,NaN,NaN,600275,NaN,NaN,1314800,3957548.0,3.01,3.01,0.00,0.00,0.00,0.00,312500,312500,0,0,0,3.05,3.10,3.12,3.13,3.14,4000,11200,2000,2000,2000,3.01,158708.0,1.597628e+15,1776836.0,25.0,SH,92503000.0
2468061,NaN,NaN,NaN,NaN,603027,NaN,NaN,1853300,71352050.0,38.50,38.49,38.45,38.26,38.20,38.05,700,200,5000,800,3700,38.50,0.00,0.00,0.00,0.00,91835,91835,0,0,0,38.50,158790.0,1.597628e+15,1776918.0,25.0,SH,92503000.0
2468062,NaN,NaN,NaN,NaN,601086,NaN,NaN,1219800,7513968.0,6.16,6.16,0.00,0.00,0.00,0.00,1219800,0,0,0,0,6.16,6.17,6.18,6.20,6.22,17078473,8500,400,15300,29000,6.16,158840.0,1.597628e+15,1776968.0,25.0,SH,92503000.0
2468063,NaN,NaN,NaN,NaN,600095,NaN,NaN,5688800,93922088.0,16.51,16.50,16.48,16.47,16.46,16.44,67200,2200,300,2600,700,16.51,0.00,0.00,0.00,0.00,798599,798599,0,0,0,16.51,158894.0,1.597628e+15,1817365.0,25.0,SH,92504000.0
2468064,NaN,NaN,NaN,NaN,600226,NaN,NaN,1741100,2246019.0,1.29,1.29,1.28,1.27,1.26,1.25,17903000,143300,123700,340400,190100,1.29,0.00,0.00,0.00,0.00,1741100,0,0,0,0,1.29,158931.0,1.597628e+15,1817402.0,25.0,SH,92504000.0
2468065,NaN,NaN,NaN,NaN,600354,NaN,NaN,4479600,17694420.0,3.95,3.95,0.00,0.00,0.00,0.00,4479600,0,0,0,0,3.95,3.96,4.05,4.08,4.09,264994,14900,5000,44100,10300,3.95,158933.0,1.597628e+15,1817404.0,25.0,SH,92504000.0
2468066,NaN,NaN,NaN,NaN,603393,NaN,NaN,744800,22559992.0,30.29,30.29,0.00,0.00,0.00,0.00,744800,0,0,0,0,30.29,30.30,30.50,31.00,31.31,28746233,137208,6500,2500,15000,30.29,159107.0,1.597628e+15,1817682.0,25.0,SH,92504000.0
2468067,NaN,NaN,NaN,NaN,600255,NaN,NaN,1087300,1598331.0,1.47,1.47,1.46,1.45,1.44,1.43,10509600,109800,90800,85300,62700,1.47,0.00,0.00,0.00,0.00,1087300,0,0,0,0,0.00,159302.0,1.597628e+15,1836071.0,25.0,SH,92505000.0

In [10]:
for i in test[np.isnan(test["sequenceNo_y"]) & (test['time_x'] == 105650000.0)]['StockID'].unique():
    try:
        assert(data2_1[data2_1['StockID'] == i]['time'].max() < 105650000)
    except:
        print(data2_1[(data2_1['StockID'] == i) & (data2_1['time'] >= 105650000)])
        print(data1_1[(data1_1['StockID'] == i) & (data1_1['time'] >= 105650000)])

           index    clockAtArrival  sequenceNo  source  StockID exchange  \
2467673  2727931  1597632991139249    67765267      25   600255       SH

              time  cum_volume  cum_amount  close  ...  ask2p  ask3p  ask4p  \
2467673  105631000     3435700   5050479.0   1.47  ...    0.0    0.0    0.0

         ask5p    ask1q  ask2q  ask3q  ask4q  ask5q  openPrice
2467673    0.0  1087300      0      0      0      0       1.47

[1 rows x 31 columns]
           index    clockAtArrival  sequenceNo  source  StockID exchange  \
2467677  5557715  1597633018925056   110647792      23   600255       SH

              time  cum_volume  cum_amount  close  ...  ask2p  ask3p  ask4p  \
2467677  105631000     3435700   5050479.0   1.47  ...    0.0    0.0    0.0

         ask5p  ask1q  ask2q  ask3q  ask4q  ask5q  openPrice
2467677    0.0      0      0      0      0      0       1.47

[1 rows x 31 columns]
           index    clockAtArrival  sequenceNo  source  StockID exchange  \
2467839  2728107  1597632991499342    67768451      25   601992       SH

              time  cum_volume  cum_amount  close  ...  ask2p  ask3p  ask4p  \
2467839  105631000    23197776  76091241.3    3.3  ...   3.31   3.32   3.33

         ask5p    ask1q    ask2q    ask3q    ask4q   ask5q  openPrice
2467839   3.34  2502400  2091600  1792400  1854500  876200       3.26

[1 rows x 31 columns]
           index    clockAtArrival  sequenceNo  source  StockID exchange  \
2467843  5558009  1597633019283127   110653218      23   601992       SH
2467924  5558155  1597633019469959   110656184      23   601992       SH

              time  cum_volume  cum_amount  close  ...  ask2p  ask3p  ask4p  \
2467843  105631000    23197776  76091241.3   3.30  ...   3.31   3.32   3.33
2467924  105631000    23198276  76092886.3   3.29  ...   3.31   3.32   3.33

         ask5p    ask1q    ask2q    ask3q    ask4q   ask5q  openPrice
2467843   3.34  2502400  2091600  1792400  1854500  876200       3.26
2467924   3.34  2502400  2091600  1792400  1854500  876200       3.26

[2 rows x 31 columns]

In [6]:
for i in test[np.isnan(test["sequenceNo_y"]) & (test['time_x'] == 105650000.0)]['StockID'].unique():
    try:
        assert(data2_1[data2_1['StockID'] == i]['time'].min() > 105650000)
    except:
        print(data2_1[(data2_1['StockID'] == i) & (data2_1['time'] <= 105650000)])
        print(data1_1[(data1_1['StockID'] == i) & (data1_1['time'] <= 105650000)])

    index    clockAtArrival  sequenceNo  source  StockID exchange       time  \
87     87  1597633010597459        1634      25   600118       SH  105650000

    cum_volume    cum_amount  close  ...  ask2p  ask3p  ask4p  ask5p  ask1q  \
87    54759563  2.143149e+09   39.7  ...  39.71  39.72  0.001    0.0  15100

    ask2q   ask3q  ask4q  ask5q  openPrice
87  25900  336872   2540      0      38.38

[1 rows x 31 columns]
       index    clockAtArrival  sequenceNo  source  StockID exchange  \
125  5575644  1597633038381940   110917608      23   600118       SH

          time  cum_volume    cum_amount  close  ...  ask2p  ask3p  ask4p  \
125  105650000    54759563  2.143149e+09   39.7  ...  39.71  39.72    0.0

     ask5p  ask1q  ask2q   ask3q  ask4q  ask5q  openPrice
125    0.0  15100  25900  336872      0      0      38.38

[1 rows x 31 columns]
     index    clockAtArrival  sequenceNo  source  StockID exchange       time  \
349    349  1597633011020939        4643      25   600330       SH  105650000

     cum_volume    cum_amount  close  ...  ask2p  ask3p  ask4p  ask5p  \
349    81978651  9.326142e+08  11.59  ...    0.0    0.0    0.0    0.0

       ask1q  ask2q  ask3q  ask4q  ask5q  openPrice
349  3808016      0      0      0      0      10.69

[1 rows x 31 columns]
       index    clockAtArrival  sequenceNo  source  StockID exchange  \
387  5575959  1597633038805816   110922456      23   600330       SH

          time  cum_volume    cum_amount  close  ...  ask2p  ask3p  ask4p  \
387  105650000    81978651  9.326142e+08  11.59  ...    0.0    0.0    0.0

     ask5p  ask1q  ask2q  ask3q  ask4q  ask5q  openPrice
387    0.0      0      0      0      0      0      10.69

[1 rows x 31 columns]
     index    clockAtArrival  sequenceNo  source  StockID exchange       time  \
379    379  1597633011075531        4919      25   601456       SH  105650000

     cum_volume    cum_amount  close  ...  ask2p  ask3p  ask4p  ask5p  \
379   292259186  4.724390e+09  17.45  ...    0.0    0.0    0.0    0.0

       ask1q  ask2q  ask3q  ask4q  ask5q  openPrice
379  1368024      0      0      0      0       15.6

[1 rows x 31 columns]
       index    clockAtArrival  sequenceNo  source  StockID exchange  \
417  5575989  1597633038850816   110922766      23   601456       SH

          time  cum_volume    cum_amount  close  ...  ask2p  ask3p  ask4p  \
417  105650000   292259186  4.724390e+09  17.45  ...    0.0    0.0    0.0

     ask5p  ask1q  ask2q  ask3q  ask4q  ask5q  openPrice
417    0.0      0      0      0      0      0       15.6

[1 rows x 31 columns]
     index    clockAtArrival  sequenceNo  source  StockID exchange       time  \
386    386  1597633011075711        5013      25   603393       SH  105650000

     cum_volume  cum_amount  close  ...  ask2p  ask3p  ask4p  ask5p     ask1q  \
386     1735300  52562237.0  30.29  ...   30.3  30.31  30.32  30.33  29178287

      ask2q  ask3q  ask4q  ask5q  openPrice
386  316648    800   1600    200      30.29

[1 rows x 31 columns]
       index    clockAtArrival  sequenceNo  source  StockID exchange  \
424  5575996  1597633038855788   110922813      23   603393       SH

          time  cum_volume  cum_amount  close  ...  ask2p  ask3p  ask4p  \
424  105650000     1735300  52562237.0  30.29  ...   30.3  30.31  30.32

     ask5p     ask1q   ask2q  ask3q  ask4q  ask5q  openPrice
424  30.33  29178287  316648    800   1600    200      30.29

[1 rows x 31 columns]

In [8]:
data2_1['cum_amount'].astype(str).apply(lambda x: len(x.split('.')[1])).unique()

array([1, 2, 6, 7], dtype=int64)

In [165]:
test[np.isnan(test["sequenceNo_y"])& (test['time_x'] != 135634000.0) & (test['time_x'] != 135941000.0) & ((test['bid1p'] != 0) & (test['ask1p'] != 0) & (test['bid2q'] != 0) & (test['ask2q'] != 0))]

,index_x,clockAtArrival_x,sequenceNo_x,ID,time_x,cum_volume,cum_amount,close,bid1p,bid2p,bid3p,bid4p,bid5p,bid1q,bid2q,bid3q,bid4q,bid5q,ask1p,ask2p,ask3p,ask4p,ask5p,ask1q,ask2q,ask3q,ask4q,ask5q,openPrice,StockID,index_y,clockAtArrival_y,sequenceNo_y,source,exchange,time_y
1026,9319847.0,1.597212e+15,45223893.0,1600363.0,135636000.0,90249491,20730185360800,218200,218100,218000,217900,0,0,800,31200,164700,0,0,218200,218500,219000,219500,219600,16200,2500,1300,1000,9400,249200,600363,NaN,NaN,NaN,NaN,NaN,NaN
2178,9321792.0,1.597212e+15,45231313.0,1600363.0,135639000.0,90250091,20730316240800,218100,218100,218000,217900,0,0,700,31500,164700,0,0,218200,218500,219000,219500,219600,16000,2500,1300,1000,9400,249200,600363,NaN,NaN,NaN,NaN,NaN,NaN
3290,9323748.0,1.597212e+15,45238238.0,1600363.0,135642000.0,90256291,20731668810800,218200,218100,218000,217900,0,0,2600,32400,166700,0,0,218200,218300,218500,219000,219500,12500,1400,2500,1300,1000,249200,600363,NaN,NaN,NaN,NaN,NaN,NaN
4414,9325695.0,1.597212e+15,45245299.0,1600363.0,135645000.0,90260291,20732541610800,218200,218100,218000,217900,0,0,2600,32400,184600,0,0,218200,218300,218500,219000,219500,8500,1400,2500,1300,1000,249200,600363,NaN,NaN,NaN,NaN,NaN,NaN
5529,9327627.0,1.597212e+15,45252368.0,1600363.0,135648000.0,90263791,20733305050800,218100,218000,217900,0,0,0,32400,180700,0,0,0,218100,218200,218300,218500,219000,3400,7600,1400,2500,1300,249200,600363,NaN,NaN,NaN,NaN,NaN,NaN
6608,9329575.0,1.597212e+15,45259005.0,1600363.0,135651000.0,90272191,20735137130800,218100,218000,217900,0,0,0,35000,181000,0,0,0,218200,218300,218500,219000,219500,7200,1400,2500,1300,6000,249200,600363,NaN,NaN,NaN,NaN,NaN,NaN
7668,9331450.0,1.597212e+15,45266069.0,1600363.0,135654000.0,90277091,20736206020800,218100,218100,218000,217900,0,0,17600,36000,182800,0,0,218200,218300,218500,219000,219500,8600,1400,2500,1300,6000,249200,600363,NaN,NaN,NaN,NaN,NaN,NaN
8779,9333405.0,1.597212e+15,45273009.0,1600363.0,135657000.0,90279791,20736794910800,218200,218100,218000,217900,0,0,15600,36100,184800,0,0,218200,218300,218500,219000,219500,8400,1400,2500,1300,6000,249200,600363,NaN,NaN,NaN,NaN,NaN,NaN
9824,9335247.0,1.597212e+15,45279932.0,1600363.0,135700000.0,90280091,20736860370800,218200,218100,218000,217900,0,0,15800,35900,184900,0,0,218200,218300,218500,219000,219500,3100,1400,2500,1300,6000,249200,600363,NaN,NaN,NaN,NaN,NaN,NaN
10971,9337196.0,1.597212e+15,45287556.0,1600363.0,135703000.0,90283191,20737536790800,218200,218200,218100,218000,217900,0,6500,15800,35900,186200,0,218300,218500,219000,219500,219600,1400,2500,1300,6000,9400,249200,600363,NaN,NaN,NaN,NaN,NaN,NaN
12133,9339198.0,1.597212e+15,45295085.0,1600363.0,135706000.0,90286091,20738169570800,218200,218200,218100,218000,217900,0,4400,19700,35900,187600,0,218300,218500,219000,219500,219600,21200,2500,1300,6000,9400,249200,600363,NaN,NaN,NaN,NaN,NaN,NaN
13311,9341688.0,1.597212e+15,45304387.0,1600363.0,135709000.0,90296291,20740394710800,218200,218100,218000,217900,0,0,14700,35900,188800,0,0,218200,218300,218500,219000,219500,900,21200,2500,1300,6000,249200,600363,NaN,NaN,NaN,NaN,NaN,NaN
14511,9343725.0,1.597212e+15,45312983.0,1600363.0,135712000.0,90300791,20741376270800,218300,218200,218100,218000,217900,0,1600,13300,45900,188300,0,218300,218500,219000,219500,219600,21100,2500,1300,6000,9400,249200,600363,NaN,NaN,NaN,NaN,NaN,NaN
15713,9345765.0,1.597212e+15,45322144.0,1600363.0,135715000.0,90526391,20790543300800,218300,218200,217900,0,0,0,9000,28000,0,0,0,218300,218500,219000,219500,219600,18500,3100,1300,6000,9400,249200,600363,NaN,NaN,NaN,NaN,NaN,NaN
18085,9349814.0,1.597212e+15,45338410.0,1600363.0,135721000.0,90548891,20795450970800,218100,218000,217900,0,0,0,600,24300,0,0,0,218100,218200,218300,218400,218500,8200,34800,13500,500,3100,249200,600363,NaN,NaN,NaN,NaN,NaN,NaN

In [136]:
test[np.isnan(test["sequenceNo_y"])& (test['time_x'] != 103618000.0)]

,index_x,clockAtArrival_x,sequenceNo_x,ID,time_x,cum_volume,cum_amount,close,bid1p,bid2p,bid3p,bid4p,bid5p,bid1q,bid2q,bid3q,bid4q,bid5q,ask1p,ask2p,ask3p,ask4p,ask5p,ask1q,ask2q,ask3q,ask4q,ask5q,openPrice,StockID,index_y,clockAtArrival_y,sequenceNo_y,source,exchange,time_y
89703,421497.0,1.597196e+15,1277827.0,1601456.0,92500000.0,815099,106859478900,131100,131100,131000,130900,130800,130700,630171301,121000,6100,3600,1300,0,0,0,0,0,0,0,0,0,0,0,601456,NaN,NaN,NaN,NaN,NaN,NaN
90362,422709.0,1.597196e+15,1292183.0,1600988.0,92501000.0,6030600,1148226240000,190400,0,0,0,0,0,0,0,0,0,0,190400,190500,190600,190700,190800,21533017,195600,106200,12400,8200,0,600988,NaN,NaN,NaN,NaN,NaN,NaN
90575,422929.0,1.597196e+15,1292403.0,1600234.0,92501000.0,700,74620000,106600,106600,106000,104800,103500,101900,3520600,100,2300,2000,10000,0,0,0,0,0,0,0,0,0,0,0,600234,NaN,NaN,NaN,NaN,NaN,NaN
90688,423087.0,1.597196e+15,1292561.0,1600139.0,92501000.0,9295400,357872900000,38500,0,0,0,0,0,0,0,0,0,0,38500,38600,38700,38800,38900,7457564,61600,20700,11400,14300,0,600139,NaN,NaN,NaN,NaN,NaN,NaN
90752,423161.0,1.597196e+15,1292635.0,1601113.0,92501000.0,1569277,45038249900,28700,28700,0,0,0,0,222323,0,0,0,0,28800,29000,29200,29900,30000,10000,5300,3500,1000,287900,0,601113,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2028679,3612007.0,1.597200e+15,21882818.0,1600543.0,103615000.0,20566166,1880120357300,90100,0,0,0,0,0,0,0,0,0,0,90100,90200,90300,90400,90500,5388880,25100,27100,14300,14895,93200,600543,NaN,NaN,NaN,NaN,NaN,NaN
2028930,3612816.0,1.597200e+15,21886069.0,1600988.0,103616000.0,23363500,4448410400000,190400,0,0,0,0,0,0,0,0,0,0,190400,190500,190600,190700,190800,45939723,275200,52600,37100,80600,190400,600988,NaN,NaN,NaN,NaN,NaN,NaN
2029212,3613150.0,1.597200e+15,21887310.0,1600489.0,103617000.0,82003125,8289475647600,99700,99700,99600,99500,0,0,78100,270108,5916665,0,0,99800,99900,100000,100100,100200,22821,23200,287300,9900,74304,101200,600489,NaN,NaN,NaN,NaN,NaN,NaN
2029305,3613263.0,1.597200e+15,21888209.0,1601086.0,103617000.0,42992573,2970786794300,69100,69100,69000,68900,68800,68700,23719227,51400,500,13100,19700,0,0,0,0,0,0,0,0,0,0,69100,601086,NaN,NaN,NaN,NaN,NaN,NaN
2029481,3613482.0,1.597200e+15,21889467.0,1600416.0,103617000.0,10188701,2082369504100,202200,0,0,0,0,0,0,0,0,0,0,202200,202500,202800,202900,203000,671651,600,5200,4500,24800,211100,600416,NaN,NaN,NaN,NaN,NaN,NaN

In [137]:
logSH[(logSH['StockID'] == 601113) & (logSH['time'] >= 92459000)][['StockID', 'time',
                                                                                  'cum_volume', 'cum_amount', 'close', 
           "bid1p", "bid2p", "bid3p", "bid4p", "bid5p", "bid1q", "bid2q", "bid3q",
           "bid4q", "bid5q", "ask1p", "ask1q" ]].head(20)

,StockID,time,cum_volume,cum_amount,close,bid1p,bid2p,bid3p,bid4p,bid5p,bid1q,bid2q,bid3q,bid4q,bid5q,ask1p,ask1q
420615,601113,92459000,0,0,0,28700,0,0,0,0,1569277,222323,0,0,0,28700,1569277
423161,601113,92501000,1569277,45038249900,28700,28700,0,0,0,0,222323,0,0,0,0,28800,10000
435152,601113,92504000,1569277,45038249900,28700,28700,0,0,0,0,222323,0,0,0,0,28800,10000
438173,601113,92514000,1569277,45038249900,28700,28700,0,0,0,0,222323,0,0,0,0,28800,10000
450494,601113,92614000,1569277,45038249900,28700,28700,0,0,0,0,222323,0,0,0,0,28800,10000
462603,601113,92714000,1569277,45038249900,28700,28700,0,0,0,0,222323,0,0,0,0,28800,10000
474668,601113,92814000,1569277,45038249900,28700,28700,0,0,0,0,222323,0,0,0,0,28800,10000
486655,601113,92914000,1569277,45038249900,28700,28700,0,0,0,0,222323,0,0,0,0,28800,10000
495850,601113,93000000,1569277,45038249900,28700,28700,0,0,0,0,242323,0,0,0,0,28800,10000
498631,601113,93003000,1705977,48971559900,28800,28800,28700,0,0,0,28200,369123,0,0,0,29100,3000
501494,601113,93006000,1789977,51394079900,28800,28800,28700,0,0,0,114000,693223,0,0,0,29200,4800
504821,601113,93009000,1867477,53629339900,29200,29200,28800,28700,0,0,2500,104200,766823,0,0,29400,1800
507489,601113,93012000,2081277,59973129900,28800,28800,28700,0,0,0,126500,793523,0,0,0,29300,2000
510819,601113,93015000,2081277,59973129900,28800,28900,28800,28700,0,0,200,136500,835723,0,0,29300,2000
512985,601113,93018000,2081277,59973129900,28800,28900,28800,28700,0,0,200,136500,835223,0,0,29300,2000
515410,601113,93021000,2081877,59990429900,28800,28800,28700,0,0,0,136100,840723,0,0,0,29300,2000
517529,601113,93024000,2081877,59990429900,28800,28800,28700,0,0,0,136100,836723,0,0,0,29300,2000
519995,601113,93027000,2081877,59990429900,28800,28800,28700,0,0,0,136100,843123,0,0,0,29300,2000
522444,601113,93030000,2081877,59990429900,28800,28900,28800,28700,0,0,71000,155000,1215623,0,0,29300,2000
524862,601113,93033000,2081877,59990429900,28800,28900,28800,28700,0,0,71000,141300,1225623,0,0,29300,2000

In [139]:
logSH1[(logSH1['StockID'] == 601113) & (logSH1['time'] >= 92459000)][['StockID', 'time',
                                                                                  'cum_volume', 'cum_amount', 'close', 
           "bid1p", "bid2p", "bid3p", "bid4p", "bid5p", "bid1q", "bid2q", "bid3q",
           "bid4q", "bid5q",  "ask1p", "ask1q"]].head(20)

,StockID,time,cum_volume,cum_amount,close,bid1p,bid2p,bid3p,bid4p,bid5p,bid1q,bid2q,bid3q,bid4q,bid5q,ask1p,ask1q
158817,601113,92459000,0,0.000,0.00,2.87,0.00,0.00,0.0,0.0,1569277,222323,0,0,0,2.87,1569277
160675,601113,92501000,1569277,450382.499,2.87,2.87,0.00,0.00,0.0,0.0,222323,222323,0,0,0,2.88,10000
162443,601113,92504000,1569277,450382.499,2.87,2.87,0.00,0.00,0.0,0.0,222323,222323,0,0,0,2.88,10000
163409,601113,92514000,1569277,450382.499,2.87,2.87,0.00,0.00,0.0,0.0,222323,222323,0,0,0,2.88,10000
165212,601113,92614000,1569277,450382.499,2.87,2.87,0.00,0.00,0.0,0.0,222323,222323,0,0,0,2.88,10000
166894,601113,92714000,1569277,450382.499,2.87,2.87,0.00,0.00,0.0,0.0,222323,222323,0,0,0,2.88,10000
168564,601113,92814000,1569277,450382.499,2.87,2.87,0.00,0.00,0.0,0.0,222323,222323,0,0,0,2.88,10000
170239,601113,92914000,1569277,450382.499,2.87,2.87,0.00,0.00,0.0,0.0,222323,222323,0,0,0,2.88,10000
172113,601113,93000000,1569277,450382.499,2.87,2.87,0.00,0.00,0.0,0.0,242323,222323,0,0,0,2.88,10000
173840,601113,93003000,1705977,489715.599,2.88,2.88,2.87,0.00,0.0,0.0,28200,369123,0,0,0,2.91,3000
175631,601113,93006000,1789977,513940.799,2.88,2.88,2.87,0.00,0.0,0.0,114000,693223,0,0,0,2.92,4800
177454,601113,93009000,1867477,536293.399,2.92,2.92,2.88,2.87,0.0,0.0,2500,104200,766823,0,0,2.94,1800
179179,601113,93012000,2081277,599731.299,2.88,2.88,2.87,0.00,0.0,0.0,126500,793523,0,0,0,2.93,2000
181379,601113,93015000,2081277,599731.299,2.88,2.89,2.88,2.87,0.0,0.0,200,136500,835723,0,0,2.93,2000
182928,601113,93018000,2081277,599731.299,2.88,2.89,2.88,2.87,0.0,0.0,200,136500,835223,0,0,2.93,2000
184577,601113,93021000,2081877,599904.299,2.88,2.88,2.87,0.00,0.0,0.0,136100,840723,0,0,0,2.93,2000
185963,601113,93024000,2081877,599904.299,2.88,2.88,2.87,0.00,0.0,0.0,136100,836723,0,0,0,2.93,2000
187623,601113,93027000,2081877,599904.299,2.88,2.88,2.87,0.00,0.0,0.0,136100,843123,0,0,0,2.93,2000
189266,601113,93030000,2081877,599904.299,2.88,2.89,2.88,2.87,0.0,0.0,71000,155000,1215623,0,0,2.93,2000
190909,601113,93033000,2081877,599904.299,2.88,2.89,2.88,2.87,0.0,0.0,71000,141300,1225623,0,0,2.93,2000

In [107]:
pd.set_option('max_rows', 200)
logSH[(logSH['StockID'] == 600416) & (logSH['time'] >= 103530000)].head(200)

,clockAtArrival,sequenceNo,ID,time,cum_volume,cum_amount,close,bid1p,bid2p,bid3p,bid4p,bid5p,bid1q,bid2q,bid3q,bid4q,bid5q,ask1p,ask2p,ask3p,ask4p,ask5p,ask1q,ask2q,ask3q,ask4q,ask5q,openPrice,StockID
3577166,1597199753741797,21718887,1600416,103530000,10088352,2062078936300,202200,202200,0,0,0,0,11649,0,0,0,0,202500,202800,202900,203000,203100,600,5200,4500,24800,30000,211100,600416
3579616,1597199756874033,21730343,1600416,103533000,10088352,2062078936300,202200,202200,0,0,0,0,24349,0,0,0,0,202500,202800,202900,203000,203100,600,5200,4500,24800,30000,211100,600416
3581635,1597199759538951,21740144,1600416,103535000,10113201,2067103404100,202200,0,0,0,0,0,0,0,0,0,0,202200,202500,202800,202900,203000,26151,600,5200,4500,24800,211100,600416
3583931,1597199762533965,21751259,1600416,103539000,10115401,2067548244100,202200,0,0,0,0,0,0,0,0,0,0,202200,202500,202800,202900,203000,24551,600,5200,4500,24800,211100,600416
3586191,1597199765539862,21761284,1600416,103542000,10137401,2071996644100,202200,0,0,0,0,0,0,0,0,0,0,202200,202500,202800,202900,203000,4251,600,5200,4500,24800,211100,600416
3588379,1597199768518213,21771701,1600416,103544000,10137901,2072097744100,202200,0,0,0,0,0,0,0,0,0,0,202200,202500,202800,202900,203000,3751,600,5200,4500,24800,211100,600416
3590619,1597199771499685,21781892,1600416,103547000,10138401,2072198844100,202200,0,0,0,0,0,0,0,0,0,0,202200,202500,202800,202900,203000,3251,600,5200,4500,24800,211100,600416
3592918,1597199774506112,21792480,1600416,103550000,10169401,2078467044100,202200,0,0,0,0,0,0,0,0,0,0,202200,202500,202800,202900,203000,647251,600,5200,4500,24800,211100,600416
3595129,1597199777507947,21803056,1600416,103553000,10175701,2079740904100,202200,0,0,0,0,0,0,0,0,0,0,202200,202500,202800,202900,203000,649951,600,5200,4500,24800,211100,600416
3597369,1597199780507802,21813099,1600416,103556000,10177901,2080185744100,202200,0,0,0,0,0,0,0,0,0,0,202200,202500,202800,202900,203000,673551,600,5200,4500,24800,211100,600416
3599543,1597199783476148,21823591,1600416,103559000,10177901,2080185744100,202200,0,0,0,0,0,0,0,0,0,0,202200,202500,202800,202900,203000,673551,600,5200,4500,24800,211100,600416
3602266,1597199787003732,21836004,1600416,103603000,10178801,2080367724100,202200,0,0,0,0,0,0,0,0,0,0,202200,202500,202800,202900,203000,672651,600,5200,4500,24800,211100,600416
3604196,1597199789666086,21846201,1600416,103606000,10178901,2080387944100,202200,0,0,0,0,0,0,0,0,0,0,202200,202500,202800,202900,203000,672551,600,5200,4500,24800,211100,600416
3606771,1597199792473640,21857443,1600416,103608000,10178901,2080387944100,202200,0,0,0,0,0,0,0,0,0,0,202200,202500,202800,202900,203000,678451,600,5200,4500,24800,211100,600416
3609011,1597199795491363,21868132,1600416,103611000,10183301,2081277624100,202200,0,0,0,0,0,0,0,0,0,0,202200,202500,202800,202900,203000,674051,600,5200,4500,24800,211100,600416
3611261,1597199798435675,21878946,1600416,103614000,10183401,2081297844100,202200,0,0,0,0,0,0,0,0,0,0,202200,202500,202800,202900,203000,676951,600,5200,4500,24800,211100,600416
3613482,1597199801452123,21889467,1600416,103617000,10188701,2082369504100,202200,0,0,0,0,0,0,0,0,0,0,202200,202500,202800,202900,203000,671651,600,5200,4500,24800,211100,600416
3616498,1597199805453379,21904379,1600416,103621000,10189701,2082571704100,202200,0,0,0,0,0,0,0,0,0,0,202200,202500,202800,202900,203000,670651,600,5200,4500,24800,211100,600416
3619880,1597199810086761,21919526,1600416,103626000,10189701,2082571704100,202200,0,0,0,0,0,0,0,0,0,0,202200,202500,202800,202900,203000,672651,600,5200,4500,24800,211100,600416
3622131,1597199813098058,21930971,1600416,103629000,10192701,2083178304100,202200,0,0,0,0,0,0,0,0,0,0,202200,202500,202800,202900,203000,669651,600,5200,4500,24800,211100,600416
3624340,1597199816064243,21941257,1600416,103632000,10192701,2083178304100,202200,0,0,0,0,0,0,0,0,0,0,202200,202500,202800,202900,203000,669651,600,5200,4500,24800,211100,600416
3626523,1597199819066971,21951504,1600416,103635000,10193701,2083380504100,202200,0,0,0,0,0,0,0,0,0,0,202200,202500,202800,202900,203000,668651,600,5200,4500,24800,211100,600416
3628543,1597199821738755,21961108,1600416,103638000,10193701,2083380504100,202200,0,0,0,0,0,0,0,0,0,0,202200,202500,202800,202900,203000,668651,600,5200,4500,24800,211100,600416
3633090,1597199827914382,21980945,1600416,103644000,10194001,2083441164100,202200,0,0,0,0,0,0,0,0,0,0,202200,202500,202800,202900,203000,668351,600,5200,4500,24800,211100,600416
3635615,1597199831330258,21992997,1600416,103647000,10194001,2083441164100,202200,0,0,0,0,0,0,0,0,0,0,202200,202500,202800,202900,203000,668451,600,5200,4500,24800,211100,600416
3637887,1597199834330917,22003998,1600416,103650000,10195701,2083784904100,202200,0,0,0,0,0,0,0,0,0,0,202200,202500,202800,202900,203000,667351,600,5200,4400,24800,211100,600416
3640101,1597199837325785,22014081,1600416,103653000,10207201,2086110204100,202200,0,0,0,0,0,0,0,0,0,0,202200,202500,202800,202900,203000,655851,600,5200,4400,24800,211100,600416
3642378,1597199840397974,22024641,1600416,103656000,10207201,2086110204100,202200,0,0,0,0,0,0,0,0,0,0,202200,202500,202800,202900,203000,656851,600,5200,4400,24800,211100,600416
3644631,1597199843411380,22035142,1600416,103659000,10207201,2086110204100,202200,0,0,0,0,0,0,0,0,0,0,202200,202500,202800,202900,203000,659551,600,5200,4400,24800,211100,600416
3646885,1597199846411918,22045103,1600416,103702000,10209201,2086514604100,202200,0,0,0,0,0,0,0,0,0,0,202200,202500,202800,202900,203000,657551,600,5200,4400,24800,211100,600416
3649086,1597199849409450,22055434,1600416,103705000,10209701,2086615704100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,657051,2400,600,5200,4400,211100,600416
3653240,1597199854247403,22072642,1600416,103710000,10209801,2086635924100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,656951,2400,600,5200,4400,211100,600416
3655439,1597199857249205,22082942,1600416,103713000,10216701,2088031104100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,650051,2400,600,5200,4400,211100,600416
3658540,1597199861605731,22097016,1600416,103718000,10216701,2088031104100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,651451,2400,600,5200,4400,211100,600416
3660744,1597199864598075,22106860,1600416,103721000,10222501,2089203864100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,645651,2400,600,5200,4400,211100,600416
3664472,1597199869740685,22122923,1600416,103726000,10222501,2089203864100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,655651,2400,600,5200,4400,211100,600416
3666673,1597199872744182,22132475,1600416,103729000,10228001,2090315964100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,650251,2400,600,5200,4400,211100,600416
3668812,1597199875737075,22141420,1600416,103732000,10228001,2090315964100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,650251,2400,600,5200,4400,211100,600416
3670985,1597199878742261,22151201,1600416,103735000,10232101,2091144984100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,646151,2400,600,5200,4400,211100,600416
3673182,1597199881741861,22161269,1600416,103738000,10232101,2091144984100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,646151,2400,600,5200,4400,211100,600416
3675106,1597199884176961,22169478,1600416,103740000,10232501,2091225864100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,645751,2400,600,5200,4400,211100,600416
3677291,1597199887199840,22179060,1600416,103743000,10238001,2092337964100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,640251,2400,600,5200,4400,211100,600416
3679409,1597199890192922,22187891,1600416,103746000,10246401,2094036444100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,631851,2400,600,5200,4400,211100,600416
3681493,1597199892846202,22196266,1600416,103749000,10246401,2094036444100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,632851,2400,600,5200,4400,211100,600416
3683629,1597199895846574,22205389,1600416,103752000,10246401,2094036444100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,633851,2400,600,5200,4400,211100,600416
3686815,1597199900658837,22219304,1600416,103757000,10246401,2094036444100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,633851,2400,600,5200,4400,211100,600416
3691073,1597199906707456,22238137,1600416,103803000,10247001,2094157764100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,633251,2400,600,5200,4400,211100,600416
3693060,1597199909473798,22246722,1600416,103805000,10247501,2094258864100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,633751,2400,600,5200,4400,211100,600416
3695684,1597199912426318,22256377,1600416,103808000,10247501,2094258864100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,633751,2400,600,5200,4400,211100,600416
3697832,1597199915433564,22265502,1600416,103811000,10247601,2094279084100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,633651,2400,600,5200,4400,211100,600416
3699964,1597199918428552,22275355,1600416,103814000,10247601,2094279084100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,633651,2400,600,5200,4400,211100,600416
3702086,1597199921429232,22284438,1600416,103817000,10247601,2094279084100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,633751,2400,600,5200,4400,211100,600416
3704210,1597199924425042,22293658,1600416,103820000,10247801,2094319524100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,633551,2400,600,5200,4400,211100,600416
3708384,1597199930347115,22312104,1600416,103826000,10247801,2094319524100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,636151,2400,600,5200,4400,211100,600416
3710555,1597199933348001,22321779,1600416,103829000,10247801,2094319524100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,654351,2400,600,5200,4400,211100,600416
3716707,1597199941746500,22348984,1600416,103838000,10247801,2094319524100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,654351,2400,600,5200,4400,211100,600416
3718829,1597199944618934,22358262,1600416,103841000,10247801,2094319524100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,655551,2400,600,5200,4400,211100,600416
3721007,1597199947618475,22367847,1600416,103844000,10249801,2094723924100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,714551,2400,600,5200,4400,211100,600416
3723122,1597199950622199,22376665,1600416,103847000,10254201,2095613604100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,710151,2400,600,5200,4400,211100,600416
3725316,1597199953617643,22386227,1600416,103850000,10256201,2096018004100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,710151,2400,600,5200,4400,211100,600416
3727458,1597199956621964,22395046,1600416,103853000,10256201,2096018004100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,712151,2400,600,5200,4400,211100,600416
3730790,1597199961356000,22409390,1600416,103857000,10256201,2096018004100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,712351,2400,600,5200,4400,211100,600416
3732919,1597199964356581,22419049,1600416,103900000,10256901,2096159544100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,711651,2400,600,5200,4400,211100,600416
3734887,1597199967045079,22427002,1600416,103903000,10306401,2106168444100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,662151,2400,600,5200,4400,211100,600416
3736819,1597199969796817,22435447,1600416,103906000,10306401,2106168444100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,663051,2400,600,5200,4400,211100,600416
3739478,1597199972792824,22445269,1600416,103909000,10306401,2106168444100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,664051,2400,600,5200,4400,211100,600416
3742147,1597199976550974,22456792,1600416,103913000,10306401,2106168444100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,664051,2400,600,5200,4400,211100,600416
3744309,1597199979544970,22466200,1600416,103916000,10306801,2106249324100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,663651,2400,600,5200,4400,211100,600416
3746469,1597199982582258,22475755,1600416,103919000,10311801,2107260324100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,658651,2400,600,5200,4400,211100,600416
3748454,1597199985204114,22483912,1600416,103921000,10311801,2107260324100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,658651,2400,600,5200,4400,211100,600416
3750586,1597199988217119,22492982,1600416,103924000,10312701,2107442304100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,657751,2400,600,5200,4400,211100,600416
3753547,1597199992167484,22506585,1600416,103928000,10312901,2107482744100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,657551,2400,600,5200,4400,211100,600416
3755694,1597199995115453,22515330,1600416,103931000,10313201,2107543404100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,657251,2400,600,5200,4400,211100,600416
3757802,1597199997784747,22524141,1600416,103934000,10313201,2107543404100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,737651,2400,600,5200,4400,211100,600416
3760057,1597200000778497,22533319,1600416,103937000,10314501,2107806264100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,739351,2400,600,5200,4400,211100,600416
3761672,1597200003451754,22541334,1600416,103939000,10314501,2107806264100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,744351,2400,600,5200,4400,211100,600416
3762546,1597200004584310,22544831,1600416,103941000,10317901,2108493744100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,740951,2400,600,5200,4400,211100,600416
3765030,1597200008067531,22554680,1600416,103944000,10367901,2118603744100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,690951,2400,600,5200,4400,211100,600416
3767204,1597200011084742,22563557,1600416,103947000,10368601,2118745284100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,690651,2400,600,5200,4400,211100,600416
3769407,1597200014071630,22572650,1600416,103950000,10369101,2118846384100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,690151,2400,600,5200,4400,211100,600416
3772079,1597200017713550,22584508,1600416,103954000,10369101,2118846384100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,691651,2400,600,5200,4400,211100,600416
3774221,1597200020709086,22593448,1600416,103957000,10372101,2119452984100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,689651,2400,600,5200,4400,211100,600416
3776430,1597200023770901,22603828,1600416,104000000,10372101,2119452984100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,709651,2400,600,5200,4400,211100,600416
3778643,1597200026770691,22614381,1600416,104003000,10372101,2119452984100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,709651,2400,600,5200,4400,211100,600416
3780880,1597200029772013,22624865,1600416,104006000,10373601,2119756284100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,708151,2400,600,5200,4400,211100,600416
3783378,1597200032503292,22635047,1600416,104008000,10374101,2119857384100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,707251,2400,600,5200,4400,211100,600416
3785533,1597200035462858,22644373,1600416,104011000,10374101,2119857384100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,706251,2400,600,5200,4400,211100,600416
3787770,1597200038489836,22654427,1600416,104014000,10378301,2120706624100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,702051,2400,600,5200,4400,211100,600416
3789942,1597200041448157,22665593,1600416,104017000,10381801,2121414324100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,699551,2400,600,5200,4400,211100,600416
3792136,1597200044441585,22675443,1600416,104020000,10393201,2123719404100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,691351,2400,600,5200,4400,211100,600416
3794311,1597200047452257,22685216,1600416,104023000,10393301,2123739624100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,690651,2400,600,5200,4400,211100,600416
3796521,1597200050445505,22694669,1600416,104026000,10394301,2123941824100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,688751,2400,600,5200,4400,211100,600416
3798757,1597200053481052,22705568,1600416,104029000,10394301,2123941824100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,688751,2400,600,5200,4400,211100,600416
3800957,1597200056464608,22716901,1600416,104032000,10397301,2124548424100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,685751,2400,600,5200,4400,211100,600416
3803192,1597200059445540,22728360,1600416,104035000,10401101,2125316784100,202200,0,0,0,0,0,0,0,0,0,0,202200,202300,202500,202800,202900,679951,2400,600,5200,4400,211100,600416
3805524,1597200062503887,22740035,1600416,104038000,10401101,2125316784100,202200,0,0,0,0,0,0,0,0,0,0,202200,202500,202800,202900,203000,679951,600,5200,4400,24800,211100,600416
3807481,1597200065150792,22749239,1600416,104041000,10403601,2125822284100,202200,0,0,0,0,0,0,0,0,0,0,202200,202500,202800,202900,203000,677451,600,5200,4400,24800,211100,600416
3809687,1597200068153903,22760243,1600416,104044000,10405301,2126166024100,202200,0,0,0,0,0,0,0,0,0,0,202200,202500,202800,202900,203000,675751,600,5200,4400,24800,211100,600416
3811908,1597200071170008,22770388,1600416,104047000,10408101,2126732184100,202200,0,0,0,0,0,0,0,0,0,0,202200,202500,202800,202900,203000,593151,600,5200,4400,24800,211100,600416
3814163,1597200074151349,22780269,1600416,104050000,10410201,2127156804100,202200,0,0,0,0,0,0,0,0,0,0,202200,202500,202800,202900,203000,591951,600,5200,4400,24800,211100,600416
3816341,1597200077156588,22790767,1600416,104053000,10419901,2129118144100,202200,0,0,0,0,0,0,0,0,0,0,202200,202500,202800,202900,203000,582251,600,5200,4400,24800,211100,600416
3821233,1597200083861572,22814267,1600416,104100000,10419901,2129118144100,202200,0,0,0,0,0,0,0,0,0,0,202200,202500,202800,202900,203000,659951,600,5200,4400,24800,211100,600416
3823400,1597200086858645,22824271,1600416,104103000,10421901,2129522544100,202200,0,0,0,0,0,0,0,0,0,0,202200,202500,202800,202900,203000,657051,600,5200,4400,24800,211100,600416
3827195,1597200091366822,22839421,1600416,104107000,10421901,2129522544100,202200,0,0,0,0,0,0,0,0,0,0,202200,202500,202800,202900,203000,657451,600,5200,4400,24800,211100,600416
3830660,1597200096206911,22855474,1600416,104112000,10421901,2129522544100,202200,0,0,0,0,0,0,0,0,0,0,202200,202500,202800,202900,203000,657451,600,5200,4400,24800,211100,600416
3832825,1597200099198433,22864877,1600416,104115000,10421901,2129522544100,202200,0,0,0,0,0,0,0,0,0,0,202200,202500,202800,202900,203000,657551,600,5200,4400,24800,211100,600416
3835003,1597200102216989,22874367,1600416,104118000,10421901,2129522544100,202200,0,0,0,0,0,0,0,0,0,0,202200,202500,202800,202900,203000,657551,600,5200,4400,24800,211100,600416
3837875,1597200105915720,22886573,1600416,104122000,10422001,2129542764100,202200,0,0,0,0,0,0,0,0,0,0,202200,202500,202800,202900,203000,657451,600,5200,4400,24800,211100,600416
3840032,1597200108886712,22895995,1600416,104125000,10424001,2129947164100,202200,0,0,0,0,0,0,0,0,0,0,202200,202500,202800,202900,203000,670151,600,5200,4400,24800,211100,600416
3842198,1597200111876075,22905612,1600416,104128000,10428001,2130755964100,202200,0,0,0,0,0,0,0,0,0,0,202200,202500,202800,202900,203000,695651,600,5200,4400,24800,211100,600416
3843759,1597200114538624,22912948,1600416,104131000,10428001,2130755964100,202200,0,0,0,0,0,0,0,0,0,0,202200,202500,202800,202900,203000,698151,600,5200,4400,24800,211100,600416

In [110]:
test[np.isnan(test["sequenceNo_y"])]['time_x'].describe([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]).astype('int64')

count        19143
mean     144092416
std         394255
min      143430000
10%      143542000
20%      143658000
30%      143819000
40%      143945000
50%      144106000
60%      144230000
70%      144353000
80%      144513000
90%      144635000
max      144800000
Name: time_x, dtype: int64

In [107]:
test[(np.isnan(test["sequenceNo_x"]))]

,index_x,clockAtArrival_x,sequenceNo_x,ID,time_x,cum_volume,cum_amount,close,bid1p,bid2p,bid3p,bid4p,bid5p,bid1q,bid2q,bid3q,bid4q,bid5q,ask1p,ask2p,ask3p,ask4p,ask5p,ask1q,ask2q,ask3q,ask4q,ask5q,openPrice,StockID,index_y,clockAtArrival_y,sequenceNo_y,source,exchange,time_y
350370,NaN,NaN,NaN,NaN,NaN,7814633,403724054300,51900,51900,51800,51700,0,51500,64500,110800,56600,0,111300,52000,52100,52200,52300,52400,27800,246400,301307,181377,126416,50900,600405,24211.0,1.597041e+15,476087.0,25.0,SH,143430000.0
350371,NaN,NaN,NaN,NaN,NaN,628067,1784720629000,2900000,2894800,0,2890100,2890000,2889900,200,0,2000,200,1000,2907300,2911500,2917000,2917200,2917300,110,500,200,200,500,2834200,688016,24213.0,1.597041e+15,476118.0,25.0,SH,143430000.0
350372,NaN,NaN,NaN,NaN,NaN,5465838,1295272987400,235800,235800,235700,0,235500,235400,300,3200,0,2700,16400,236100,236200,236300,236400,236500,3300,1000,20000,600,1600,233800,603738,24237.0,1.597041e+15,476286.0,25.0,SH,143430000.0
350373,NaN,NaN,NaN,NaN,NaN,2093712,583089247900,278300,278300,0,278100,278000,277900,300,0,3100,2300,500,278400,278500,278600,278800,278900,400,400,600,900,100,278000,603826,24261.0,1.597041e+15,476326.0,25.0,SH,143430000.0
350374,NaN,NaN,NaN,NaN,NaN,1529803,388632309800,256600,256100,255900,0,255700,255600,1000,700,0,2700,200,256600,256700,256800,256900,257000,3800,5500,42400,6300,1500,249800,603332,24265.0,1.597041e+15,476330.0,25.0,SH,143430000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
369496,NaN,NaN,NaN,NaN,NaN,20996030,3744347734700,169900,169800,169700,0,169500,169300,2500,200,0,1800,1900,169900,170000,170100,170200,170300,400,20000,17000,3000,12500,182600,600876,399733.0,1.597042e+15,7500506.0,25.0,SH,144800000.0
369497,NaN,NaN,NaN,NaN,NaN,1177414,902486827200,777900,777200,777100,776800,0,776400,200,8159,1000,0,366,777900,778000,778100,779500,779800,301,116,94,200,400,776700,688181,399764.0,1.597042e+15,7500698.0,25.0,SH,144800000.0
369498,NaN,NaN,NaN,NaN,NaN,1285432,2075674633500,1650000,1648500,1646800,1646600,1646400,0,400,300,200,100,0,1650000,1650200,1651000,1651100,1651800,500,900,250,100,1400,1550000,603489,399772.0,1.597042e+15,7500706.0,25.0,SH,144800000.0
369499,NaN,NaN,NaN,NaN,NaN,1369432,1501745861300,1074000,1073800,0,1070600,1070000,1069900,200,0,500,463,500,1074000,1075000,1076800,1076900,1077400,33,1500,200,219,200,1090000,688258,399786.0,1.597042e+15,7501234.0,25.0,SH,144800000.0
369500,NaN,NaN,NaN,NaN,NaN,14246045,16073986060100,1135300,1135300,1134900,1134400,1134000,0,200,1400,758,200,0,1135600,1135700,1135800,1135900,1136000,700,5200,400,1500,7400,1117600,603259,399816.0,1.597042e+15,7501757.0,25.0,SH,144800000.0

In [111]:
pd.set_option('max_columns', 200)
data2_1['cum_amount'] = data2_1['cum_amount'].astype('int64')
logSH[(logSH['StockID'] == 600405) & (logSH['time'] >= 143430000)][['StockID', 'time',
                                                                                  'cum_volume', 'cum_amount', 'close', 
           "bid1p", "bid2p", "bid3p", "bid4p", "bid5p", "bid1q", "bid2q", "bid3q",
           "bid4q", "bid5q", "ask1p", "ask2p", "ask1q", "ask2q",]].head(20)

,StockID,time,cum_volume,cum_amount,close,bid1p,bid2p,bid3p,bid4p,bid5p,bid1q,bid2q,bid3q,bid4q,bid5q,ask1p,ask2p,ask1q,ask2q
10778271,600405,143430000,7814633,403724054300,51900,51900,51800,51700,51600,51500,64500,110800,56600,56600,111300,52000,52100,27800,246400
10782197,600405,143434000,7814633,403724054300,51900,51900,51800,51700,51600,51500,64500,110800,56600,56600,111300,52000,52100,28000,246400
10784419,600405,143437000,7815333,403760384300,51900,51900,51800,51700,51600,51500,63800,110800,56600,56600,111300,52000,52100,30300,246400
10786403,600405,143440000,7818233,403910894300,51900,51900,51800,51700,51600,51500,60900,110800,56600,56600,111300,52000,52100,30300,246400
10788553,600405,143443000,7818233,403910894300,51900,51900,51800,51700,51600,51500,61800,110800,56600,56600,111300,52000,52100,24100,246600
10790752,600405,143446000,7818233,403910894300,51900,51900,51800,51700,51600,51500,61800,110800,38000,56600,111300,52000,52100,25600,246600
10793067,600405,143449000,7818233,403910894300,51900,51900,51800,51700,51600,51500,61800,110800,38000,56600,111300,52000,52100,25600,246600
10795002,600405,143452000,7818233,403910894300,51900,51900,51800,51700,51600,51500,61800,110800,38000,56600,111300,52000,52100,25600,246600
10796511,600405,143455000,7818233,403910894300,51900,51900,51800,51700,51600,51500,61800,110800,38000,56600,111300,52000,52100,25600,246600
10798702,600405,143458000,7848233,405467894300,51900,51900,51800,51700,51600,51500,31800,110800,38000,56600,111300,52000,52100,25600,249600
10801541,600405,143501000,7848233,405467894300,51900,51900,51800,51700,51600,51500,31800,110800,38000,56600,111300,52000,52100,25600,248900
10803732,600405,143504000,7848233,405467894300,51900,51900,51800,51700,51600,51500,31800,110800,38000,56600,111300,52000,52100,28600,248900
10806412,600405,143507000,7848233,405467894300,51900,51900,51800,51700,51600,51500,31800,110800,38000,56600,111300,52000,52100,29300,248900
10808688,600405,143510000,7853233,405727394300,51900,51900,51800,51700,51600,51500,26800,110800,38000,56600,111300,52000,52100,29300,248900
10810892,600405,143513000,7853233,405727394300,51900,51900,51800,51700,51600,51500,26800,110800,38000,56600,111300,52000,52100,29300,248900
10813102,600405,143516000,7853233,405727394300,51900,51900,51800,51700,51600,51500,26800,110800,38000,56600,111300,52000,52100,29800,248900
10815306,600405,143519000,7853233,405727394300,51900,51900,51800,51700,51600,51500,26800,113400,38000,56600,111300,52000,52100,30400,237700
10817484,600405,143522000,7858233,405986894300,51900,51900,51800,51700,51600,51500,21300,113400,38000,56600,111300,52000,52100,30400,237700
10819702,600405,143525000,7865933,406386524300,51900,51900,51800,51700,51600,51500,13600,113400,38000,56600,111300,52000,52100,30400,237700
10822278,600405,143529000,7865933,406386524300,51900,51900,51800,51700,51600,51500,13600,93400,38000,56600,111300,52000,52100,60600,237700

In [83]:
data2_1[(data2_1['StockID'] == 688016) & (data2_1['cum_volume'] == 628067)]

,index,clockAtArrival,sequenceNo,source,StockID,exchange,time,cum_volume,cum_amount,close,bid1p,bid2p,bid3p,bid4p,bid5p,bid1q,bid2q,bid3q,bid4q,bid5q,ask1p,ask2p,ask3p,ask4p,ask5p,ask1q,ask2q,ask3q,ask4q,ask5q,openPrice
9321,9897,1597041239635916,178653,25,688016,SH,143359000,628067,1784720629000,2900000.0,2894800.0,0.0,2890100.0,2890000.0,2889900.0,200,0,2000,200,1000,2907300.0,2911500.0,2917000.0,2917200.0,2917300.0,110,500,200,200,500,2834200.0
24104,25648,1597041273182865,504274,25,688016,SH,143433000,628067,1784720629000,2900000.0,2894800.0,2890100.0,2890000.0,2889900.0,2881900.0,200,2000,200,1000,200,2907300.0,2911500.0,2917000.0,2917200.0,2917300.0,110,500,200,200,500,2834200.0
25440,27063,1597041276195207,532275,25,688016,SH,143436000,628067,1784720629000,2900000.0,2894800.0,2890100.0,2890000.0,2889900.0,2881900.0,200,2000,200,1000,200,2907300.0,2911500.0,2917000.0,2917200.0,2917300.0,690,500,200,200,500,2834200.0

In [84]:
data1_1[(data1_1['ID'] == 1688016.0) & (data1_1['cum_volume'] == 628067)]

,index,clockAtArrival,sequenceNo,ID,time,cum_volume,cum_amount,close,bid1p,bid2p,bid3p,bid4p,bid5p,bid1q,bid2q,bid3q,bid4q,bid5q,ask1p,ask2p,ask3p,ask4p,ask5p,ask1q,ask2q,ask3q,ask4q,ask5q,openPrice,StockID
22,10778273,1597041292017836,51341067,1688016,143430000,628067,1784720629000,2900000,2894800,2894500,2890100,2890000,2889900,200,200,2000,200,1000,2907300,2911500,2917000,2917200,2917300,110,500,200,200,500,2834200,688016
2233,10780486,1597041295003421,51353149,1688016,143433000,628067,1784720629000,2900000,2894800,2890100,2890000,2889900,2881900,200,2000,200,1000,200,2907300,2911500,2917000,2917200,2917300,110,500,200,200,500,2834200,688016
4381,10782719,1597041298020210,51364243,1688016,143436000,628067,1784720629000,2900000,2894800,2890100,2890000,2889900,2881900,200,2000,200,1000,200,2907300,2911500,2917000,2917200,2917300,690,500,200,200,500,2834200,688016

In [69]:
logSH1 = pd.read_csv(r'F:\data\20200812\full_20200812_zt_70_01_day_7079\mdLog_SH_20200812_1359.csv',
                    encoding="utf-8").loc[:, ["clockAtArrival", "sequenceNo", "source", "StockID",
                                               "exchange", "time", "cum_volume", "cum_amount", "close",
                                               "bid1p", "bid2p", "bid3p", "bid4p", "bid5p", "bid1q",
                                               "bid2q", "bid3q", "bid4q", "bid5q", "ask1p", "ask2p",
                                               "ask3p", "ask4p", "ask5p", "ask1q", "ask2q", "ask3q",
                                               "ask4q", "ask5q", "openPrice"]]
logSH1["time"] = logSH1["time"].apply(lambda x: int(x.replace(':', ""))) * 1000
logSH1['time'].min()

135956000

In [70]:
logSH1['time'].max()

151949000

In [53]:
in_dex = [16, 300, 852, 905]
# logSH1 = pd.read_csv(r'F:\data\20200812\full_20200812_zt_70_01_day_7079\mdLog_SH_20200812_1036.csv',
#                     encoding="utf-8").loc[:, ["clockAtArrival", "sequenceNo", "source", "StockID",
#                                                "exchange", "time", "cum_volume", "cum_amount", "close",
#                                                "bid1p", "bid2p", "bid3p", "bid4p", "bid5p", "bid1q",
#                                                "bid2q", "bid3q", "bid4q", "bid5q", "ask1p", "ask2p",
#                                                "ask3p", "ask4p", "ask5p", "ask1q", "ask2q", "ask3q",
#                                                "ask4q", "ask5q", "openPrice"]]
# logSH1["time"] = logSH1["time"].apply(lambda x: int(x.replace(':', ""))) * 1000
# logSH = pd.read_csv(r'F:\data\20200812\logs_20200812_zt_88_03_day_88data\mdLog_SH_20200812_0849.csv',
#                     encoding="utf-8").loc[:, ["clockAtArrival", "sequenceNo", "source", "StockID",
#                                                "time", "cum_volume", "cum_amount", "close", "openPrice"]]
# logSH["time"] = logSH["time"].apply(lambda x: int(x.replace(':', "").replace('.', "")))


data1 = logSH[logSH["StockID"].isin(in_dex)]
data2 = logSH1[logSH1["StockID"].isin(in_dex)]

columns = ["StockID", "cum_volume", "cum_amount", "close", "openPrice"]
data1_1 = data1.drop_duplicates(subset=columns, keep="first").reset_index()
data2_1 = data2.drop_duplicates(subset=columns, keep="first").reset_index()

# for cols in ["openPrice"]:
#     data2_1[cols] = (data2_1[cols]/1000000).round(4)    
for cols in ["cum_amount"]:
    data2_1[cols] = data2_1[cols].round(4) 
    data1_1[cols] = data1_1[cols].round(4) 
    
test = pd.merge(data1_1, data2_1, left_on=columns, right_on=columns, how="outer")
n1 = test["sequenceNo_x"].count()
n2 = test["sequenceNo_y"].count()
len1 = len(test)
print(n1)
print(n2)
print(len1)
if n2 < len1:
    display("test is not complete:")
    display(test[np.isnan(test["sequenceNo_y"])])

11412
11350
11412

'test is not complete:'

,index_x,clockAtArrival_x,sequenceNo_x,source_x,StockID,exchange_x,time_x,cum_volume,cum_amount,close,bid1p_x,bid2p_x,bid3p_x,bid4p_x,bid5p_x,bid1q_x,bid2q_x,bid3q_x,bid4q_x,bid5q_x,ask1p_x,ask2p_x,ask3p_x,ask4p_x,ask5p_x,ask1q_x,ask2q_x,ask3q_x,ask4q_x,ask5q_x,openPrice,numTrades_x,index_y,clockAtArrival_y,sequenceNo_y,source_y,exchange_y,time_y,bid1p_y,bid2p_y,bid3p_y,bid4p_y,bid5p_y,bid1q_y,bid2q_y,bid3q_y,bid4q_y,bid5q_y,ask1p_y,ask2p_y,ask3p_y,ask4p_y,ask5p_y,ask1q_y,ask2q_y,ask3q_y,ask4q_y,ask5q_y,numTrades_y
1468,2283663,1598839267033435,55879959,22,16,SH,100027130,14477272,3.289329e+10,3397.6844,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,3386.6204,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1469,2283673,1598839267069883,55880663,22,300,SH,100027210,64845570,1.138465e+11,4878.0919,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,4870.9337,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1470,2283677,1598839267078832,55880806,22,852,SH,100027220,55091088,6.720379e+10,7264.5947,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,7238.6587,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1471,2283678,1598839267078846,55880807,22,905,SH,100027220,45561179,4.958526e+10,6722.7487,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,6719.2859,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3084,4207689,1598841287014107,87265680,22,16,SH,103407130,21456971,4.840383e+10,3404.2147,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,3386.6204,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10451,12703168,1598855882190250,202661886,22,905,SH,143722160,140532886,1.560027e+11,6691.5560,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,6719.2859,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11404,13995983,1598857247256396,223157910,22,16,SH,150007100,47789890,1.029078e+11,3344.1435,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,3386.6204,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11405,13995984,1598857247256877,223157911,22,300,SH,150007180,202134688,3.565814e+11,4816.5146,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,4870.9337,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11406,13995985,1598857247256928,223157912,22,852,SH,150007190,184704375,2.265239e+11,7224.1970,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,7238.6587,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11407,13995986,1598857247256938,223157913,22,905,SH,150007190,155872760,1.731497e+11,6667.6792,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,6719.2859,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [57]:
test[np.isnan(test["sequenceNo_y"])]['time_x'].describe([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]).astype('int64')

count           62
mean     117554994
std       16880690
min      100027130
10%      103407220
20%      104837172
30%      104947154
40%      105163166
50%      110457175
60%      111638124
70%      130737217
80%      135737190
90%      143722143
max      150007190
Name: time_x, dtype: int64

In [184]:
test[np.isnan(test["sequenceNo_x"])]

,index_x,clockAtArrival_x,sequenceNo_x,ID,time_x,cum_volume,cum_amount,close,openPrice,StockID,index_y,clockAtArrival_y,sequenceNo_y,source,exchange,time_y,bid1p,bid2p,bid3p,bid4p,bid5p,bid1q,bid2q,bid3q,bid4q,bid5q,ask1p,ask2p,ask3p,ask4p,ask5p,ask1q,ask2q,ask3q,ask4q,ask5q
2391,NaN,NaN,NaN,NaN,NaN,1747025,24736189881000,46688899,46688899,300,163737,1597195523190919,2005393,25,SH,92523000,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0
2392,NaN,NaN,NaN,NaN,NaN,1944532,28314355472000,46696349,46688899,300,173520,1597195803429847,2145162,25,SH,93003000,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0
2393,NaN,NaN,NaN,NaN,NaN,3131344,44496626265000,46717502,46688899,300,176430,1597195808247002,2281242,25,SH,93008000,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0
2394,NaN,NaN,NaN,NaN,NaN,3757268,54062218493000,46720362,46688899,300,179734,1597195813303642,2477625,25,SH,93013000,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0
2395,NaN,NaN,NaN,NaN,NaN,4005427,58545740711000,46706504,46688899,300,182074,1597195818257039,2657477,25,SH,93018000,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3183,NaN,NaN,NaN,NaN,NaN,96748961,1609625835028000,46081194,46688899,300,2204829,1597199758281282,65848724,25,SH,103558000,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0
3184,NaN,NaN,NaN,NaN,NaN,96814746,1610749794862000,46078489,46688899,300,2207238,1597199763245935,65898078,25,SH,103603000,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0
3185,NaN,NaN,NaN,NaN,NaN,96899466,1611907419710000,46085986,46688899,300,2209618,1597199768223470,65947385,25,SH,103608000,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0
3186,NaN,NaN,NaN,NaN,NaN,96975985,1613097878629000,46085175,46688899,300,2212347,1597199773271758,65995179,25,SH,103613000,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0
3187,NaN,NaN,NaN,NaN,NaN,97053320,1614416002696000,46078847,46688899,300,2214781,1597199778248023,66043861,25,SH,103618000,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0

In [188]:
data1_1['StockID'].unique()

array([ 16, 852, 905], dtype=int64)

In [180]:
data2_1[data2_1['StockID'] == 16]['openPrice'].iloc[0]

32555383.0

In [169]:
data2_1[data2_1['StockID'] == 16]

,index,clockAtArrival,sequenceNo,source,StockID,exchange,time,cum_volume,cum_amount,close,bid1p,bid2p,bid3p,bid4p,bid5p,bid1q,bid2q,bid3q,bid4q,bid5q,ask1p,ask2p,ask3p,ask4p,ask5p,ask1q,ask2q,ask3q,ask4q,ask5q,openPrice
0,163736,1597195523110761,2005392,25,16,SH,92523000,456008,7.902066e+07,3255.5383,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,3.255538e+09
4,173274,1597195803323501,2141856,25,16,SH,93003000,501381,9.289188e+07,3256.8585,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,3.255538e+09
8,176429,1597195808233679,2281241,25,16,SH,93008000,776388,1.398281e+08,3257.8677,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,3.255538e+09
12,179730,1597195813296704,2477621,25,16,SH,93013000,927726,1.741770e+08,3258.3956,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,3.255538e+09
16,181904,1597195818218585,2655758,25,16,SH,93018000,968410,1.830758e+08,3257.6941,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,3.255538e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3168,2204819,1597199758200689,65848246,25,16,SH,103558000,23126570,4.471782e+09,3229.3356,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,3.255538e+09
3172,2207200,1597199763167220,65897215,25,16,SH,103603000,23147291,4.474999e+09,3228.7553,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,3.255538e+09
3176,2209558,1597199768134068,65946269,25,16,SH,103608000,23160800,4.477669e+09,3229.5348,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,3.255538e+09
3180,2212334,1597199773229308,65994901,25,16,SH,103613000,23175538,4.480636e+09,3229.6854,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,3.255538e+09
3184,2214737,1597199778166243,66042927,25,16,SH,103618000,23200223,4.484250e+09,3228.8850,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,3.255538e+09

### 2. SZ completeness check result

In [1]:
import pandas as pd
import numpy as np

logSZ = pd.read_csv(r'F:\data\20200831\logs_20200831_zs_96_03_day_96data\mdLog_SZ_20200831_0901.csv',
                    encoding="utf-8").loc[:, ["clockAtArrival", "sequenceNo", "StockID", 'source', "time", "cum_volume", "cum_amount", "close",
                                              "bid1p", "bid2p", "bid3p", "bid4p", "bid5p", "bid1q",
                                              "bid2q", "bid3q", "bid4q", "bid5q", "ask1p", "ask2p",
                                              "ask3p", "ask4p", "ask5p", "ask1q", "ask2q", "ask3q",
                                              "ask4q", "ask5q", "openPrice", "numTrades"]]
logSZ1 = pd.read_csv(r'F:\data\20200831\full_20200831_zt_70_01_day_test0831\mdLog_SZ_20200831_0856.csv',
                    encoding="utf-8").loc[:, ["clockAtArrival", "sequenceNo", "source", "StockID",
                                              "exchange", "time", "cum_volume", "cum_amount", "close",
                                              "bid1p", "bid2p", "bid3p", "bid4p", "bid5p", "bid1q",
                                              "bid2q", "bid3q", "bid4q", "bid5q", "ask1p", "ask2p",
                                              "ask3p", "ask4p", "ask5p", "ask1q", "ask2q", "ask3q",
                                              "ask4q", "ask5q", "openPrice", "numTrades"]]

print("new data source type: ")
print(logSZ1["source"].unique())
print(logSZ["time"].unique())
print(logSZ1["time"].unique())

new data source type:
[25]
['09:01:48.000' '09:02:48.000' '09:03:48.000' ... '15:40:03.000'
 '15:41:03.000' '15:42:03.000']
['08:56:48' '08:57:48' '08:58:48' ... '15:33:03' '15:34:03' '15:35:03']

In [32]:
logSZ1 = pd.read_csv(r'F:\data\20200813\full_20200813_zt_70_01_day_7079\mdLog_SZ_20200813_1122.csv',
                    encoding="utf-8").loc[:, ["clockAtArrival", "sequenceNo", "source", "StockID",
                                              "exchange", "time", "cum_volume", "cum_amount", "close",
                                              "bid1p", "bid2p", "bid3p", "bid4p", "bid5p", "bid1q",
                                              "bid2q", "bid3q", "bid4q", "bid5q", "ask1p", "ask2p",
                                              "ask3p", "ask4p", "ask5p", "ask1q", "ask2q", "ask3q",
                                              "ask4q", "ask5q", "openPrice"]]
logSZ1["time"] = logSZ1["time"].apply(lambda x: int((x.replace(':', "")))) * 1000

In [2]:
# logSZ = logSZ[~logSZ['time'].isnull()]
logSZ["time"] = logSZ["time"].apply(lambda x: int(x.replace(':', "").replace('.', "")))
logSZ1["time"] = logSZ1["time"].apply(lambda x: int((x.replace(':', "")))) * 1000

display(logSZ[(logSZ["StockID"] == 1) & (logSZ["time"] >= 94500000) & (logSZ["time"] <= 95000000)])
display(logSZ1[(logSZ1["StockID"] == 1) & (logSZ1["time"] >= 94500000) & (logSZ1["time"] <= 95000000)])

,clockAtArrival,sequenceNo,StockID,source,time,cum_volume,cum_amount,close,bid1p,bid2p,...,ask3p,ask4p,ask5p,ask1q,ask2q,ask3q,ask4q,ask5q,openPrice,numTrades
761912,1598838313616777,45658511,1,24,94500000,56010736,8.685574e+08,15.57,15.56,15.55,...,15.59,15.60,15.61,16452,131400,223020,475500,130200,15.3,26468
764006,1598838316641190,45770866,1,24,94503000,56098036,8.699158e+08,15.57,15.56,15.55,...,15.59,15.60,15.61,52,132200,223020,486500,130200,15.3,26530
766094,1598838319627617,45886173,1,24,94506000,56153136,8.707736e+08,15.58,15.57,15.56,...,15.60,15.61,15.62,117252,223020,486500,129600,95900,15.3,26567
768220,1598838322615694,45999688,1,24,94509000,56189436,8.713388e+08,15.58,15.57,15.56,...,15.60,15.61,15.62,114952,240020,487500,129600,95900,15.3,26598
770300,1598838325617715,46115271,1,24,94512000,56244936,8.722030e+08,15.58,15.57,15.56,...,15.60,15.61,15.62,108452,240020,487200,129600,94900,15.3,26656
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
959661,1598838601617748,54206391,1,24,94948000,63477788,9.850783e+08,15.59,15.58,15.57,...,15.61,15.62,15.63,11700,141800,199809,195800,148218,15.3,30705
961721,1598838604619318,54285229,1,24,94951000,63495788,9.853589e+08,15.59,15.58,15.57,...,15.61,15.62,15.63,10500,147100,204709,224500,148218,15.3,30723
963754,1598838607617175,54364481,1,24,94954000,63532188,9.859263e+08,15.59,15.58,15.57,...,15.61,15.62,15.63,9700,149100,193209,232600,157218,15.3,30750
965806,1598838610627369,54452274,1,24,94957000,63552688,9.862457e+08,15.58,15.58,15.57,...,15.61,15.62,15.63,42600,154700,194209,235900,160218,15.3,30772
967853,1598838613618539,54552467,1,24,95000000,63566188,9.864562e+08,15.58,15.58,15.57,...,15.61,15.62,15.63,34900,173100,194209,240200,159718,15.3,30788

,clockAtArrival,sequenceNo,source,StockID,exchange,time,cum_volume,cum_amount,close,bid1p,...,ask3p,ask4p,ask5p,ask1q,ask2q,ask3q,ask4q,ask5q,openPrice,numTrades
757485,1598838300657974,1323209,25,1,SZ,94500000,56010736,8.685574e+08,15.57,15.56,...,15.59,15.60,15.61,16452,131400,223020,475500,130200,15.3,26468
759522,1598838303682296,1326302,25,1,SZ,94503000,56098036,8.699158e+08,15.57,15.56,...,15.59,15.60,15.61,52,132200,223020,486500,130200,15.3,26530
761536,1598838306724339,1331135,25,1,SZ,94506000,56153136,8.707736e+08,15.58,15.57,...,15.60,15.61,15.62,117252,223020,486500,129600,95900,15.3,26567
763604,1598838309757686,1333203,25,1,SZ,94509000,56189436,8.713388e+08,15.58,15.57,...,15.60,15.61,15.62,114952,240020,487500,129600,95900,15.3,26598
765638,1598838312664124,1337115,25,1,SZ,94512000,56244936,8.722030e+08,15.58,15.57,...,15.60,15.61,15.62,108452,240020,487200,129600,94900,15.3,26656
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
948367,1598838589721302,1647226,25,1,SZ,94948000,63477788,9.850783e+08,15.59,15.58,...,15.61,15.62,15.63,11700,141800,199809,195800,148218,15.3,30705
950351,1598838592061535,1650442,25,1,SZ,94951000,63495788,9.853589e+08,15.59,15.58,...,15.61,15.62,15.63,10500,147100,204709,224500,148218,15.3,30723
952300,1598838594799195,1652573,25,1,SZ,94954000,63532188,9.859263e+08,15.59,15.58,...,15.61,15.62,15.63,9700,149100,193209,232600,157218,15.3,30750
954275,1598838597646696,1657012,25,1,SZ,94957000,63552688,9.862457e+08,15.58,15.58,...,15.61,15.62,15.63,42600,154700,194209,235900,160218,15.3,30772
956235,1598838600723333,1660235,25,1,SZ,95000000,63566188,9.864562e+08,15.58,15.58,...,15.61,15.62,15.63,34900,173100,194209,240200,159718,15.3,30788

In [11]:
logSZ1['time'].max()

153203000

In [12]:
logSZ1['time'].min()

105651000

In [7]:
logSZ1['cum_amount'].astype(str).apply(lambda x: len(x.split('.')[1])).unique()

array([1, 2, 6], dtype=int64)

In [3]:
data1 = logSZ
data2 = logSZ1
columns = ["StockID", "cum_volume", "cum_amount", "close", "bid1p", "bid2p", "bid3p", "bid4p", "bid5p", "bid1q", "bid2q",
           "bid3q", "bid4q", "bid5q", "ask1p", "ask2p", "ask3p", "ask4p", "ask5p", "ask1q", "ask2q", "ask3q",
           "ask4q", "ask5q", 'openPrice', "numTrades"]
data1_1 = data1.drop_duplicates(subset=columns, keep="first").reset_index()
data2_1 = data2.drop_duplicates(subset=columns, keep="first").reset_index()
n1 = len(data1_1["StockID"].unique())
n2 = len(data2_1["StockID"].unique())
print(n1)
print(n2)
if n1 != n2:
    sl = list(set(data1_1["StockID"].unique()) & (set(data2_1["StockID"].unique())))
    data1_1 = data1_1[data1_1["StockID"].isin(sl)]
    data2_1 = data2_1[data2_1["StockID"].isin(sl)]

for cols in ["cum_amount"]:
    data2_1[cols] = data2_1[cols].round(2)
    data1_1[cols] = data1_1[cols].round(2)
    
test = pd.merge(data1_1, data2_1, left_on=columns, right_on=columns, how="outer")
n1 = test["sequenceNo_x"].count()
n2 = test["sequenceNo_y"].count()
len1 = len(test)
print(n1)
print(n2)
print(len1)
print("-----------------------------------------------")
if n2 < len1:
    display("test is not complete:")
    display(test[np.isnan(test["sequenceNo_y"])])
    print(len(test[np.isnan(test["sequenceNo_y"])])/n1)
if (len1 == n2) & (n1 < len1):
    display("baseline is not complete:")
    display(test[np.isnan(test["sequenceNo_x"])])
    display(n2-n1)

2241
2241
8279654
8279654
8279654
-----------------------------------------------

In [16]:
for i in test[np.isnan(test["sequenceNo_y"])]['StockID'].unique():
    assert(logSZ1[logSZ1['StockID'] == i]['time'].min() > 103630000)

In [18]:
logSZ1[(logSZ1['StockID'] == 2) & (logSZ1['cum_volume'] > 0)].head(2)

,clockAtArrival,sequenceNo,source,StockID,exchange,time,cum_volume,cum_amount,close,bid1p,bid2p,bid3p,bid4p,bid5p,bid1q,bid2q,bid3q,bid4q,bid5q,ask1p,ask2p,ask3p,ask4p,ask5p,ask1q,ask2q,ask3q,ask4q,ask5q,openPrice
154352,1597195500739695,1651178,25,2,SZ,92500000,515801,1438568.989,27.89,27.89,27.88,27.87,27.86,27.85,148399,59900,400,4700,3200,27.9,27.92,27.93,27.94,27.95,2500,1000,4800,2000,2000,27.89
157315,1597195560552600,2006356,25,2,SZ,92600000,515801,1438568.989,27.89,27.89,27.88,27.87,27.86,27.85,148399,59900,400,4700,3200,27.9,27.92,27.93,27.94,27.95,2500,1000,4800,2000,2000,27.89

In [45]:
test[np.isnan(test["sequenceNo_y"]) & ((test['bid4p'] == 0) | (test['bid3p'] == 0) | (test['bid5p'] == 0)| (test['bid2p'] == 0) | (test['bid1p'] == 0))]

,index_x,clockAtArrival_x,sequenceNo_x,ID,time_x,cum_volume,cum_amount,close,bid1p,bid2p,bid3p,bid4p,bid5p,bid1q,bid2q,bid3q,bid4q,bid5q,ask1p,ask2p,ask3p,ask4p,ask5p,ask1q,ask2q,ask3q,ask4q,ask5q,openPrice,StockID,index_y,clockAtArrival_y,sequenceNo_y,source,exchange,time_y
256267,11325540.0,1.597042e+15,245140735.0,2300777.0,144148000.0,9782449,5102487400600,488600,488600,488500,487500,487400,0,200,200,48600,89100,0,488700,488800,489000,489200,489300,1200,12000,16700,2300,1100,537000,300777,NaN,NaN,NaN,NaN,NaN,NaN
442258,11580488.0,1.597042e+15,250699292.0,2002965.0,144703000.0,11937438,4890916232300,400900,400900,400800,400700,0,0,2900,2900,43727,0,0,401000,401100,401200,401500,401600,4900,31900,2700,1300,900,430000,2965,NaN,NaN,NaN,NaN,NaN,NaN

In [46]:
data1_1[(data1_1['StockID'] == 300777.0) & (data1_1['time'] == 144148000.0)]

,index,clockAtArrival,sequenceNo,ID,time,cum_volume,cum_amount,close,bid1p,bid2p,bid3p,bid4p,bid5p,bid1q,bid2q,bid3q,bid4q,bid5q,ask1p,ask2p,ask3p,ask4p,ask5p,ask1q,ask2q,ask3q,ask4q,ask5q,openPrice,StockID
286131,11325540,1597041717367768,245140735,2300777,144148000,9782449,5102487400600,488600,488600,488500,487500,487400,0,200,200,48600,89100,0,488700,488800,489000,489200,489300,1200,12000,16700,2300,1100,537000,300777

In [47]:
data2_1[(data2_1['StockID'] == 300777.0) & (data2_1['time'] == 144148000.0)]

,index,clockAtArrival,sequenceNo,source,StockID,exchange,time,cum_volume,cum_amount,close,bid1p,bid2p,bid3p,bid4p,bid5p,bid1q,bid2q,bid3q,bid4q,bid5q,ask1p,ask2p,ask3p,ask4p,ask5p,ask1q,ask2q,ask3q,ask4q,ask5q,openPrice
256266,298141,1597041709938002,4185605,25,300777,SZ,144148000,9782449,5.102487e+12,488600.0,488600.0,0.0,487500.0,487400.0,0.0,200,0,48600,89100,0,488700.0,488800.0,489000.0,489200.0,489300.0,1200,12000,16700,2300,1100,537000.0

In [43]:
test[np.isnan(test["sequenceNo_x"]) & ((test['bid4p'] == 0) | (test['bid3p'] == 0) | (test['bid5p'] == 0)| (test['bid2p'] == 0) | (test['bid1p'] == 0))]

,index_x,clockAtArrival_x,sequenceNo_x,ID,time_x,cum_volume,cum_amount,close,bid1p,bid2p,bid3p,bid4p,bid5p,bid1q,bid2q,bid3q,bid4q,bid5q,ask1p,ask2p,ask3p,ask4p,ask5p,ask1q,ask2q,ask3q,ask4q,ask5q,openPrice,StockID,index_y,clockAtArrival_y,sequenceNo_y,source,exchange,time_y
476292,NaN,NaN,NaN,NaN,NaN,4466650,389762135000,88200,88200,88100,88000,87900,0,10600,56400,41300,22000,0,88300,88400,88500,88600,88700,84850,16300,31800,33700,51800,85700,7,31068.0,1.597041e+15,479348.0,25.0,SZ,143430000.0
476293,NaN,NaN,NaN,NaN,NaN,2303196,1857373844800,799100,799100,0,797200,797100,796700,200,0,500,400,300,799400,799800,799900,805000,805400,700,1100,7900,300,100,819600,526,31140.0,1.597041e+15,479676.0,25.0,SZ,143430000.0
476294,NaN,NaN,NaN,NaN,NaN,44374170,5211833580500,114800,114600,114300,0,114100,114000,5200,900,0,11000,42600,114800,115000,115200,115300,115500,4000,2000,3200,700,12200,120900,576,31195.0,1.597041e+15,480006.0,25.0,SZ,143430000.0
476295,NaN,NaN,NaN,NaN,NaN,1609407,3293253048400,2061300,2059700,2059600,2059500,2057800,0,400,200,100,500,0,2061300,2061800,2062000,2062200,2065000,800,300,200,300,300,2051900,596,31200.0,1.597041e+15,480044.0,25.0,SZ,143430000.0
476296,NaN,NaN,NaN,NaN,NaN,4625835,3524354590000,769000,769000,0,768100,768000,0,400,0,100,200,0,769900,770000,770100,770300,770400,200,700,1500,600,900,769500,710,31242.0,1.597041e+15,480229.0,25.0,SZ,143430000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
496073,NaN,NaN,NaN,NaN,NaN,7705861,2876510409300,352900,351900,351800,351300,351100,0,100,1600,1500,100,0,352900,353000,353600,354100,354500,100,29400,400,3800,100,372100,300823,527066.0,1.597042e+15,7508413.0,25.0,SZ,144800000.0
496074,NaN,NaN,NaN,NaN,NaN,2136921,1758933703900,820200,820200,820100,820000,0,819800,1300,1000,700,0,900,820500,821300,821400,821500,821600,1300,100,500,1200,1000,789400,300811,527071.0,1.597042e+15,7508475.0,25.0,SZ,144800000.0
496075,NaN,NaN,NaN,NaN,NaN,2300951,2059822894000,899000,899000,898700,0,898300,898000,900,100,0,200,500,899100,899400,900000,900200,900400,800,100,100,300,200,920000,300829,527079.0,1.597042e+15,7508484.0,25.0,SZ,144800000.0
496076,NaN,NaN,NaN,NaN,NaN,1655977,2622327767300,1580000,1579800,1578800,0,0,1578000,300,100,0,0,800,1580000,1580200,1583800,1584000,1584400,4200,300,200,200,900,1611800,300832,527080.0,1.597042e+15,7508485.0,25.0,SZ,144800000.0
496077,NaN,NaN,NaN,NaN,NaN,648700,558834310000,853800,853800,0,853600,853500,853000,200,0,100,1200,3600,854000,854100,855900,856300,856700,1900,900,100,100,100,902000,300816,527086.0,1.597042e+15,7508508.0,25.0,SZ,144800000.0

In [26]:
data1_1[(data1_1['ask1p'] == 0)]

,index,clockAtArrival,sequenceNo,ID,time,cum_volume,cum_amount,close,bid1p,bid2p,bid3p,bid4p,bid5p,bid1q,bid2q,bid3q,bid4q,bid5q,ask1p,ask2p,ask3p,ask4p,ask5p,ask1q,ask2q,ask3q,ask4q,ask5q,openPrice,StockID
254,10980775,1597041278558928,238033045,2000516,143430000,117450631,7894045855600,69000,69000,68900,68800,68700,68600,15970000,13600,5200,2100,900,0,0,0,0,0,0,0,0,0,0,62300,516
284,10980805,1597041278570075,238033256,2000572,143430000,2405602,87082792400,36200,36200,36100,36000,35900,35800,13197498,27300,395800,11500,71700,0,0,0,0,0,0,0,0,0,0,36200,572
313,10980834,1597041278599921,238034002,2000616,143430000,135860057,4632267032000,34400,34400,34300,34200,34100,34000,11422239,198700,58800,140500,249100,0,0,0,0,0,0,0,0,0,0,32500,616
344,10980865,1597041278601518,238034077,2000683,143430000,263912481,7171782511200,27900,27900,27800,27700,27600,27500,13446730,1632900,380300,121600,166877,0,0,0,0,0,0,0,0,0,0,26500,683
381,10980902,1597041278624334,238034508,2000727,143430000,56084915,1330789923900,23900,23900,23800,23700,23600,23500,4191747,392700,834000,967200,620300,0,0,0,0,0,0,0,0,0,0,22800,727
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
530654,11620410,1597042089122186,251626454,2300067,144800000,14376029,746115905100,51900,51900,51800,51700,51600,51500,20793371,71700,15400,34500,43500,0,0,0,0,0,0,0,0,0,0,51900,300067
530692,11620452,1597042089134332,251626673,2300099,144800000,151429891,17192952103600,113600,113600,113500,113400,113300,113200,7740735,324500,29400,93017,54200,0,0,0,0,0,0,0,0,0,0,113600,300099
530829,11620591,1597042089204018,251628119,2300297,144800000,60462336,2715438359700,46100,46100,46000,45900,45800,45700,15520294,23400,7800,20600,9000,0,0,0,0,0,0,0,0,0,0,41400,300297
530843,11620607,1597042089216066,251628325,2300274,144800000,32247920,6922217615600,218400,218400,218300,218200,218000,217900,3990520,26964,900,3100,9000,0,0,0,0,0,0,0,0,0,0,200700,300274
530905,11620669,1597042089241446,251628831,2300358,144800000,21575066,3355459751900,163200,163200,163100,163000,162900,162800,4124760,25900,5600,5600,24500,0,0,0,0,0,0,0,0,0,0,146200,300358

### 3. SZ order completeness check result

In [1]:
import pandas as pd
import random
import numpy as np
import pickle 

OrderLog = pd.read_csv(r'F:\data\20200821\logs_20200821_zs_96_03_day_96data\mdOrderLog_20200821_0859.csv',
                    encoding="utf-8").loc[:, ["clockAtArrival", "sequenceNo", "TransactTime", "exchId", 
                                                 "ApplSeqNum", "SecurityID", "Side", "OrderType", "Price",
                                                 "OrderQty"]]
OrderLog1 = pd.read_csv(r'F:\data\20200821\full_20200821_zt_70_01_day_7079\mdOrderLog_20200821_0834.csv').loc[:, ["clockAtArrival", "sequenceNo", "exchId", "TransactTime",
                                                 "ApplSeqNum", "SecurityID", "Side", "OrderType", "Price",
                                                 "OrderQty"]]
m_ax = OrderLog1.groupby('SecurityID')['TransactTime'].max().max()
display(m_ax)
m_in = OrderLog1.groupby('SecurityID')['TransactTime'].min().min()
display(m_in)
m_ax = OrderLog.groupby('SecurityID')['TransactTime'].max().max()
display(m_ax)
m_in = OrderLog.groupby('SecurityID')['TransactTime'].min().min()
display(m_in)

# OrderLog = OrderLog[(OrderLog['TransactTime'] >= m_in)]
display(set(OrderLog['SecurityID'].unique()) - set(OrderLog1['SecurityID'].unique()))
display(set(OrderLog1['SecurityID'].unique()) - set(OrderLog['SecurityID'].unique()))
stocks = list(set(OrderLog1["SecurityID"].unique()) & set(OrderLog["SecurityID"].unique()))
OrderLogSZ = OrderLog[OrderLog["SecurityID"].isin(stocks)]
OrderLogSZ1 = OrderLog1[OrderLog1["SecurityID"].isin(stocks)]
del OrderLog
del OrderLog1
OrderLogSZ["OrderType"] = OrderLogSZ["OrderType"].apply(lambda x: str(x))
OrderLogSZ1["OrderType"] = OrderLogSZ1["OrderType"].apply(lambda x: str(x))
print(len(OrderLogSZ["SecurityID"].unique()))
print(len(OrderLogSZ1["SecurityID"].unique()))

columns = ["TransactTime", "ApplSeqNum","Side",'OrderType', 'Price', 'OrderQty', "SecurityID"]
# OrderLogSZ1['OrderQty'] = (OrderLogSZ1['OrderQty']/100).round(0)
ree = pd.merge(OrderLogSZ, OrderLogSZ1, left_on=columns, right_on=columns, how="outer", validate='one_to_one')
n1 = ree["sequenceNo_x"].count()
n2 = ree["sequenceNo_y"].count()
len1 = len(ree)
print(n1)
print(n2)
print(len1)
print("-----------------------------------------------")
if n2 < len1:
    display("test is not complete:")
    display(ree[np.isnan(ree["sequenceNo_y"])])
    print(len(ree[np.isnan(ree["sequenceNo_y"])]))
    print(np.sort(ree[np.isnan(ree["sequenceNo_y"])]["TransactTime"].unique()))
    print(len(ree[np.isnan(ree["sequenceNo_y"])]["SecurityID"].unique()))
    print(ree[np.isnan(ree["sequenceNo_y"])]["SecurityID"].unique())
if (len1 == n2) & (n1 < len1):
    display("test is complete, baseline is not complete:")
    display(ree[np.isnan(ree["sequenceNo_x"])])
    print(np.sort(ree[np.isnan(ree["sequenceNo_x"])]["TransactTime"].unique()))
    print(len(ree[np.isnan(ree["sequenceNo_x"])]["SecurityID"].unique()))
    print(ree[np.isnan(ree["sequenceNo_x"])]["SecurityID"].unique())
    display(n2-n1)

C:\Users\win\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

145959990

91500000

145959990

91500000

set()

set()

2233
2233
45263817
45263817
45263817
-----------------------------------------------

In [10]:
ree[np.isnan(ree["sequenceNo_y"]) & (ree['TransactTime'] == 141303300)]

,clockAtArrival_x,sequenceNo_x,TransactTime,exchId_x,ApplSeqNum,SecurityID,Side,OrderType,Price,OrderQty,clockAtArrival_y,sequenceNo_y,exchId_y
18081820,1597644793016334,223092643,141303300,2,22451008,2346,2,2,120400,700,NaN,NaN,NaN

In [2]:
for i in ree[np.isnan(ree["sequenceNo_y"]) & (ree['TransactTime'] == 105650260 )]['SecurityID'].unique():
    try:
        assert(OrderLogSZ1[OrderLogSZ1['SecurityID'] == i]['TransactTime'].min() > 105650260 )
    except:
        print(OrderLogSZ1[(OrderLogSZ1['SecurityID'] == i) & (OrderLogSZ1['TransactTime'] <= 105650260 )].shape[0])
        print(OrderLogSZ[(OrderLogSZ['SecurityID'] == i) & (OrderLogSZ['TransactTime'] <= 105650260 )].shape[0])

1
2
1
2

### 4. SH & SZ trade completeness check result

In [1]:
import pandas as pd
import random
import numpy as np
import pickle 

TradeLog = pd.read_csv(r'F:\data\20200814\logs_20200814_zt_88_03_day_88data\mdTradeLog_20200814_0902.csv',
                    encoding="utf-8").loc[:, ["clockAtArrival", "sequenceNo", "TransactTime", "SecurityID", "exchId", 
                                                 "ApplSeqNum", "ExecType", "TradeBSFlag","TradePrice", "TradeQty", "TradeMoney", "BidApplSeqNum","OfferApplSeqNum"]]
TradeLog1 = pd.read_csv(r'F:\data\20200814\full_20200814_zt_70_01_day_7079\mdTradeLog_20200814_1153.csv').loc[:, ["clockAtArrival", "sequenceNo", "exchId", "TransactTime",
                                                 "ApplSeqNum", "SecurityID", "ExecType", "TradeBSFlag",
                                                 "TradePrice", "TradeQty", "TradeMoney", "BidApplSeqNum",
                                                 "OfferApplSeqNum"]]
TradeLog1 = TradeLog1[TradeLog1['exchId'] == 1]
TradeLog = TradeLog[TradeLog['exchId'] == 1]
display(TradeLog1.groupby('SecurityID')['TransactTime'].max().max())
display(TradeLog1.groupby('SecurityID')['TransactTime'].min().min())
m_ax = TradeLog1['TransactTime'].max()
m_in = TradeLog1['TransactTime'].min()
TradeLog = TradeLog[(TradeLog['TransactTime'] >= m_in)]
display(set(TradeLog['SecurityID'].unique()) - set(TradeLog1['SecurityID'].unique()))
display(set(TradeLog1['SecurityID'].unique()) - set(TradeLog['SecurityID'].unique()))
stocks = list(set(TradeLog1["SecurityID"].unique()) & set(TradeLog["SecurityID"].unique()))
display(len(stocks))
SH = TradeLog[TradeLog["SecurityID"].isin(stocks)]
SH1 = TradeLog1[TradeLog1["SecurityID"].isin(stocks)]
del TradeLog
del TradeLog1
print(len(SH["SecurityID"].unique()))
print(len(SH1["SecurityID"].unique()))


columns = ["TransactTime", "ApplSeqNum", "SecurityID", "TradePrice", "TradeQty", "TradeMoney", "TradeBSFlag","ExecType",
           "BidApplSeqNum", "OfferApplSeqNum"]
# SH1['TradeQty'] = (SH1['TradeQty']/100).round(0)
# SH1['TradeMoney'] = (SH1['TradeMoney']/100).round(0)
re = pd.merge(SH, SH1, left_on=columns, right_on=columns, how="outer", validate='one_to_one')
n1 = re["sequenceNo_x"].count()
n2 = re["sequenceNo_y"].count()
len1 = len(re)
print(n1)
print(n2)
print(len1)
print("-----------------------------------------------")
if n2 < len1:
    display("test is not complete:")
    display(re[np.isnan(re["sequenceNo_y"])])
    print(len(re[np.isnan(re["sequenceNo_y"])]))
    print(np.sort(re[np.isnan(re["sequenceNo_y"])]["TransactTime"].unique()))
    print(len(re[np.isnan(re["sequenceNo_y"])]["SecurityID"].unique()))
    print(re[np.isnan(re["sequenceNo_y"])]["SecurityID"].unique())
if (len1 == n2) & (n1 < len1):
    display("baseline is not complete:")
    display(re[np.isnan(re["sequenceNo_x"])])
    print(np.sort(re[np.isnan(re["sequenceNo_x"])]["TransactTime"].unique()))
    print(len(re[np.isnan(re["sequenceNo_x"])]["SecurityID"].unique()))
    print(re[np.isnan(re["sequenceNo_x"])]["SecurityID"].unique())
    display(n2-n1)

C:\Users\win\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

150000840

130000000

set()

set()

1663

1663
1663
8430968
8430968
8430968
-----------------------------------------------

In [6]:
for i in re[np.isnan(re["sequenceNo_y"]) & (re['TransactTime'] == 103618280)]['SecurityID'].unique():
    try:
        assert(SH1[SH1['SecurityID'] == i]['TransactTime'].max() < 103618280)
    except:
        print(SH1[(SH1['SecurityID'] == i) & (SH1['TransactTime'] >= 103618280)].shape[0])
        print(SH[(SH['SecurityID'] == i) & (SH['TransactTime'] >= 103618280)].shape[0])

In [ ]:
import pandas as pd
import random
import numpy as np
import pickle 

TradeLog = pd.read_csv(r'F:\data\20200817\logs_20200817_zs_96_03_day_96data\mdTradeLog_20200817_0839.csv',
                    encoding="utf-8").loc[:, ["clockAtArrival", "sequenceNo", "TransactTime", "SecurityID", "exchId", 
                                                 "ApplSeqNum", "ExecType", "TradeBSFlag","TradePrice", "TradeQty", "TradeMoney", "BidApplSeqNum","OfferApplSeqNum"]]
TradeLog1 = pd.read_csv(r'F:\data\20200817\full_20200817_zt_70_01_day_7079\mdTradeLog_20200817_1056.csv').loc[:, ["clockAtArrival", "sequenceNo", "exchId", "TransactTime",
                                                 "ApplSeqNum", "SecurityID", "ExecType", "TradeBSFlag",
                                                 "TradePrice", "TradeQty", "TradeMoney", "BidApplSeqNum",
                                                 "OfferApplSeqNum"]]
TradeLog1 = TradeLog1[TradeLog1['exchId'] == 2]
TradeLog = TradeLog[TradeLog['exchId'] == 2]
m_ax = TradeLog1.groupby('SecurityID')['TransactTime'].max().max()
m_in = TradeLog1.groupby('SecurityID')['TransactTime'].min().min()
display(m_ax)
display(m_in)
display(TradeLog1['TradeBSFlag'].unique())
display(TradeLog['TradeBSFlag'].unique())
display(TradeLog1['ExecType'].unique())
TradeLog = TradeLog[(TradeLog['TransactTime'] <= m_ax)]
display(set(TradeLog['SecurityID'].unique()) - set(TradeLog1['SecurityID'].unique()))
display(set(TradeLog1['SecurityID'].unique()) - set(TradeLog['SecurityID'].unique()))
stocks = list(set(TradeLog1["SecurityID"].unique()) & set(TradeLog["SecurityID"].unique()))
display(len(stocks))
TradeLogSZ = TradeLog[TradeLog["SecurityID"].isin(stocks)]
TradeLogSZ1 = TradeLog1[TradeLog1["SecurityID"].isin(stocks)]
del TradeLog
del TradeLog1
print(len(TradeLogSZ["SecurityID"].unique()))
print(len(TradeLogSZ1["SecurityID"].unique()))

TradeLogSZ["ExecType"] = TradeLogSZ["ExecType"].apply(lambda x: str(x))
TradeLogSZ1["ExecType"] = TradeLogSZ1["ExecType"].apply(lambda x: str(x))

columns = ["TransactTime","ApplSeqNum", "SecurityID", "ExecType", "TradeBSFlag","TradePrice", "TradeQty", "TradeMoney", "BidApplSeqNum","OfferApplSeqNum"]
# TradeLogSZ1['TradeQty'] = (TradeLogSZ1['TradeQty']/100).round(0)
# TradeLogSZ1['TradeMoney'] = (TradeLogSZ1['TradeMoney']/100).round(0)
re = pd.merge(TradeLogSZ, TradeLogSZ1, left_on=columns, right_on=columns, how="outer", validate='one_to_one')
n1 = re["sequenceNo_x"].count()
n2 = re["sequenceNo_y"].count()
len1 = len(re)
print(n1)
print(n2)
print(len1)
print("-----------------------------------------------")
if n2 < len1:
    display("test is not complete:")
    display(re[np.isnan(re["sequenceNo_y"])])
    print(len(re[np.isnan(re["sequenceNo_y"])]))
    print(np.sort(re[np.isnan(re["sequenceNo_y"])]["TransactTime"].unique()))
    print(len(re[np.isnan(re["sequenceNo_y"])]["SecurityID"].unique()))
    print(re[np.isnan(re["sequenceNo_y"])]["SecurityID"].unique())
if (len1 == n2) & (n1 < len1):
    display("baseline is not complete:")
    display(re[np.isnan(re["sequenceNo_x"])])
    print(np.sort(re[np.isnan(re["sequenceNo_x"])]["TransactTime"].unique()))
    print(len(re[np.isnan(re["sequenceNo_x"])]["SecurityID"].unique()))
    print(re[np.isnan(re["sequenceNo_x"])]["SecurityID"].unique())
    display(n2-n1)

150000000

105650260

array(['N'], dtype=object)

array(['N'], dtype=object)

array(['F', '4'], dtype=object)

set()

set()

2234

2234
2234

In [2]:
for i in re[np.isnan(re["sequenceNo_y"]) & (re['TransactTime'] == 105631530 )]['SecurityID'].unique():
    try:
        assert(TradeLogSZ1[TradeLogSZ1['SecurityID'] == i]['TransactTime'].max() < 105631530 )
    except:
        print(TradeLogSZ1[(TradeLogSZ1['SecurityID'] == i) & (TradeLogSZ1['TransactTime'] >= 105631530 )].shape[0])
        print(TradeLogSZ[(TradeLogSZ['SecurityID'] == i) & (TradeLogSZ['TransactTime'] >= 105631530 )].shape[0])

In [4]:
import pandas as pd
import glob
import os
readPath = 'A:\\KR_daily_data\\20200812\\SH' + '\\snapshot\\***2\\***'
dataPathLs = np.array(glob.glob(readPath))
dateLs = np.array([int(os.path.basename(i).split('.')[0]) for i in dataPathLs])
dataPathLs = dataPathLs[((dateLs >= 600000) & (dateLs <= 700000))]
SH = []
ll = []
for i in dataPathLs:
    try:
        df = pd.read_csv(i, usecols = [0,1,3,5,7,9,10,11,15,17,18,19,20,21,22,23,25,26,28,29,30,31,32,33,37,39,40,41,
                                      42,46,47,49,50])
    except:
        print("empty data")
        print(i)
        ll.append(int(os.path.basename(i).split('.')[0]))
        continue
    df["StockID"] = int(os.path.basename(i).split('.')[0])
    SH += [df]
del df
SH = pd.concat(SH).reset_index(drop=True)

In [11]:
pd.set_option('max_columns', 200)
SH[SH['Volume'] > 0].groupby('StockID')['OpenPx'].nunique().sort_values()

StockID
688981    1
600839    1
600843    1
600847    1
600189    1
         ..
600692    2
600691    2
600690    2
600702    2
601116    2
Name: OpenPx, Length: 1673, dtype: int64

In [17]:
SH[(SH['StockID'] == 600189) & (SH['OpenPx'] != 0)]

,NumTrades,OfferTradeMaxDuration,TotalBidNumber,WithdrawSellMoney,BidOrders,TotalOfferQty,WithdrawBuyNumber,WeightedAvgOfferPx,WithdrawSellAmount,Volume,BidOrderQty,OpenPx,HighPx,PreClosePx,LowPx,WeightedAvgBidPx,OfferNumOrders,WithdrawSellNumber,TotalOfferNumber,OfferPrice,NumOfferOrders,BidPrice,OfferOrderQty,TotalBidQty,WithdrawBuyAmount,BidTradeMaxDuration,NumBidOrders,LastPx,Amount,BidNumOrders,WithdrawBuyMoney,QuotTime,OfferOrders,StockID
975335,0,-1,0,0.00,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",0,0,0.000,0,0,"[0,0,0,0,0,0,0,0,0,0]",4.56,0.00,4.71,0.00,0.000,"[0,0,0,0,0,0,0,0,0,0]",0,0,"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0]",0,"[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0]","[0,0,0,0,0,0,0,0,0,0]",0,0,-1,0,0.00,0.0,"[0,0,0,0,0,0,0,0,0,0]",0.00,20200812092500000,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",600189
975336,91,0,107,710134.00,"[16400,218300,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...",394400,2,4.927,151800,506700,"[234700,102300,4500,7700,91600,99600,5100,1900...",4.56,4.56,4.71,4.56,4.487,"[1,2,1,1,1,6,1,9,3,1]",4,100,"[4.59,4.6,4.61,4.62,4.64,4.67,4.68,4.7,4.71,4.74]",34,"[4.56,4.55,4.54,4.53,4.52,4.51,4.5,4.49,4.48,4...","[2700,900,2600,1000,1000,8100,1000,21500,6900,...",878300,3500,0,27,4.56,2310552.0,"[2,8,2,5,8,9,6,2,3,2]",15720.00,20200812092500000,"[2700,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...",600189
975337,91,0,107,710134.00,"[16400,218300,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...",394400,2,4.927,151800,506700,"[234700,102300,4500,7700,91600,99600,5100,1900...",4.56,4.56,4.71,4.56,4.487,"[1,2,1,1,1,6,1,9,3,1]",4,100,"[4.59,4.6,4.61,4.62,4.64,4.67,4.68,4.7,4.71,4.74]",34,"[4.56,4.55,4.54,4.53,4.52,4.51,4.5,4.49,4.48,4...","[2700,900,2600,1000,1000,8100,1000,21500,6900,...",878300,3500,0,27,4.56,2310552.0,"[2,8,2,5,8,9,6,2,3,2]",15720.00,20200812092521000,"[2700,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...",600189
975338,91,0,107,710134.00,"[16400,218300,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...",394400,2,4.927,151800,506700,"[234700,102300,4500,7700,91600,99600,5100,1900...",4.56,4.56,4.71,4.56,4.487,"[1,2,1,1,1,6,1,9,3,1]",4,100,"[4.59,4.6,4.61,4.62,4.64,4.67,4.68,4.7,4.71,4.74]",34,"[4.56,4.55,4.54,4.53,4.52,4.51,4.5,4.49,4.48,4...","[2700,900,2600,1000,1000,8100,1000,21500,6900,...",878300,3500,0,27,4.56,2310552.0,"[2,8,2,5,8,9,6,2,3,2]",15720.00,20200812092621000,"[2700,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...",600189
975339,91,0,107,710134.00,"[16400,218300,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...",394400,2,4.927,151800,506700,"[234700,102300,4500,7700,91600,99600,5100,1900...",4.56,4.56,4.71,4.56,4.487,"[1,2,1,1,1,6,1,9,3,1]",4,100,"[4.59,4.6,4.61,4.62,4.64,4.67,4.68,4.7,4.71,4.74]",34,"[4.56,4.55,4.54,4.53,4.52,4.51,4.5,4.49,4.48,4...","[2700,900,2600,1000,1000,8100,1000,21500,6900,...",878300,3500,0,27,4.56,2310552.0,"[2,8,2,5,8,9,6,2,3,2]",15720.00,20200812092721000,"[2700,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...",600189
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
979568,7623,9244,372,35134257.91,"[3600,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...",1870910,1890,4.857,7560216,12458435,"[3700,9500,83400,53768,16200,15500,39000,24900...",4.56,4.77,4.71,4.48,4.455,"[1,6,3,3,6,11,3,8,3,11]",1087,285,"[4.61,4.62,4.63,4.64,4.65,4.66,4.67,4.68,4.69,...",50,"[4.6,4.59,4.58,4.57,4.56,4.55,4.54,4.53,4.52,4...","[32080,18000,21100,15300,14800,34300,10500,521...",1178948,6316317,7610,34,4.61,57107653.2,"[2,9,13,15,5,8,6,12,7,11]",28687717.58,20200812154050000,"[32080,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",600189
979569,7623,9244,372,35134257.91,"[3600,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...",1870910,1890,4.857,7560216,12458435,"[3700,9500,83400,53768,16200,15500,39000,24900...",4.56,4.77,4.71,4.48,4.455,"[1,6,3,3,6,11,3,8,3,11]",1087,285,"[4.61,4.62,4.63,4.64,4.65,4.66,4.67,4.68,4.69,...",50,"[4.6,4.59,4.58,4.57,4.56,4.55,4.54,4.53,4.52,4...","[32080,18000,21100,15300,14800,34300,10500,521...",1178948,6316317,7610,34,4.61,57107653.2,"[2,9,13,15,5,8,6,12,7,11]",28687717.58,20200812154150000,"[32080,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",600189
979570,7623,9244,372,35134257.91,"[3600,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...",1870910,1890,4.857,7560216,12458435,"[3700,9500,83400,53768,16200,15500,39000,24900...",4.56,4.77,4.71,4.48,4.455,"[1,6,3,3,6,11,3,8,3,11]",1087,285,"[4.61,4.62,4.63,4.64,4.65,4.66,4.67,4.68,4.69,...",50,"[4.6,4.59,4.58,4.57,4.56,4.55,4.54,4.53,4.52,4...","[32080,18000,21100,15300,14800,34300,10500,521...",1178948,6316317,7610,34,4.61,57107653.2,"[2,9,13,15,5,8,6,12,7,11]",28687717.58,20200812154250000,"[32080,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",600189
979571,7623,9244,372,35134257.91,"[3600,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...",1870910,1890,4.857,7560216,12458435,"[3700,9500,83400,53768,16200,15500,39000,24900...",4.56,4.77,4.71,4.48,4.455,"[1,6,3,3,6,11,3,8,3,11]",1087,285,"[4.61,4.62,4.63,4.64,4.65,4.66,4.67,4.68,4.69,...",50,"[4.6,4.59,4.58,4.57,4.56,4.55,4.54,4.53,4.52,4...","[32080,18000,21100,15300,14800,34300,10500,521...",1178948,6316317,7610,34,4.61,57107653.2,"[2,9,13,15,5,8,6,12,7,11]",28687717.58,20200812154351000,"[32080,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",600189
979572,7623,9244,372,35134257.91,"[3600,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...",1870910,1890,4.857,7560216,12458435,"[3700,9500,83400,53768,16200,15500,39000,24900...",4.56,4.77,4.71,4.48,4.455,"[1,6,3,3,6,11,3,8,3,11]",1087,285,"[4.61,4.62,4.63,4.64,4.65,4.66,4.67,4.68,4.69,...",50,"[4.6,4.59,4.58,4.57,4.56,4.55,4.54,4.53,4.52,4...","[32080,18000,21100,15300,14800,34300,10500,521...",1178948,6316317,7610,34,4.61,57107653.2,"[2,9,13,15,5,8,6,12,7,11]",28687717.58,20200812154451000,"[32080,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",600189