In [4]:
import pandas as pd
import matplotlib as mpl
import glob
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats
import matplotlib.dates as mdates
import math
from scipy import stats
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm
from pandas.plotting import register_matplotlib_converters
register_matplotlib_converters()
from datetime import timedelta
import calendar
import seaborn as sns

# 1. calculate beta with respect to SH000905
sto_ck1 = pd.read_csv('E:\\all_stock.csv', encoding="GBK").iloc[:, 1:]
sto_ck2 = pd.read_csv('F:\\all_stock_2020.csv', encoding="GBK").iloc[:, 1:]
sto_ck = pd.concat([sto_ck1, sto_ck2]).sort_values(by=["Symbol", "Date"])
in_dex = pd.read_csv(r'F:\Download\index\index_daily_SH000985.csv',
                           encoding="utf-8").iloc[:, 1:]
sto_ck["ret"] = sto_ck["ret"]/100
in_dex["returns"] = in_dex['close']/in_dex['close'].shift(1) - 1

def add_market(x):
    x2 = in_dex.loc[:, ["Date", "returns"]]
    xx = pd.merge(x, x2, left_on="Date", right_on="Date", how='inner')
    xx.columns = ["Date", "s_returns", "m_returns"]
    return xx
da_ta = sto_ck.groupby("Symbol")["Date", "ret"].apply(add_market).reset_index().loc[:,
       ["Date", "Symbol", "s_returns", "m_returns"]]
print(da_ta)

def cal(x):
    x.columns = ["x", "y"]
    x_cov = x.rolling(60).cov().unstack()['x']['y']
    x_var = x['y'].to_frame().rolling(60).var()
    result = x_cov / x_var.iloc[:, 0]
    re = pd.DataFrame(result.values, index=range(0, len(result)))
    print(re)
    return re
da_ta["beta"] = da_ta.groupby("Symbol")['s_returns', 'm_returns'].apply(cal).reset_index().iloc[:, 2]
da_ta["beta"] = da_ta.groupby("Symbol")["beta"].shift(1)
da_ta["alpha"] = da_ta["s_returns"] - da_ta["beta"]*da_ta["m_returns"]
da_ta.to_csv('E:\\new_beta_CSI.csv', encoding="utf-8")

             Date    Symbol  s_returns  m_returns
0        20100104  SH600000  -0.023052  -0.006016
1        20100105  SH600000   0.007551   0.009077
2        20100106  SH600000  -0.019672  -0.004712
3        20100107  SH600000  -0.022456  -0.019865
4        20100108  SH600000   0.011241   0.005882
...           ...       ...        ...        ...
6715352  20200624  SZ300842   0.100033   0.001029
6715353  20200629  SZ300842   0.100149  -0.005731
6715354  20200630  SZ300842   0.099946   0.015164
6715355  20200701  SZ300842   0.099951   0.011840
6715356  20200701  SZ300846   0.439169   0.011840

[6715357 rows x 4 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2497  0.351977
2498  0.369099
2499  0.370841
2500  0.392384
2501  0.411443

[2502 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2541  1.097617
2542  1.081892
2543  1.082592
2544  0.965091
2545  0.962808

[2546 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2488  0.954973
2489  0.921861
2490  0.920824
2491  0.926470
2492  0.919162

[2493 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2540  0.468410
2541  0.463698
2542  0.501118
2543  0.511499
2544  0.540822

[2545 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2519  0.605581
2520  0.592857
2521  0.593753
2522  0.575363
2523  0.565373

[2524 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2541  1.064181
2542  1.059500
2543  1.042739
2544  0.982438
2545  0.981225

[2546 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2470  0.501865
2471  0.482861
2472  0.495469
2473  0.507969
2474  0.500621

[2475 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2530  0.537540
2531  0.526087
2532  0.530740
2533  0.634137
2534  0.638495

[2535 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2539  0.425004
2540  0.402557
2541  0.413732
2542  0.367661
2543  0.378323

[2544 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2525  0.335553
2526  0.341256
2527  0.341594
2528  0.341758
2529  0.359250

[2530 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2535  0.342279
2536  0.350606
2537  0.353974
2538  0.362306
2539  0.380368

[2540 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2523  0.624846
2524  0.608543
2525  0.626409
2526  0.584201
2527  0.580728

[2528 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2484  0.552532
2485  0.573438
2486  0.591400
2487  0.612534
2488  0.611622

[2489 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2444  0.584586
2445  0.568402
2446  0.581656
2447  0.581352
2448  0.599790

[2449 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2528  0.496054
2529  0.478256
2530  0.497430
2531  0.474469
2532  0.482996

[2533 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2416  0.420161
2417  0.388902
2418  0.398317
2419  0.426274
2420  0.486928

[2421 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2291  0.422644
2292  0.405033
2293  0.441365
2294  0.446807
2295  0.452543

[2296 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1586  0.334291
1587  0.324059
1588  0.340300
1589  0.341312
1590  0.359147

[1591 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
611  0.611179
612  0.597163
613  0.546695
614  0.577424
615  0.561690

[616 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2437  0.754050
2438  0.857578
2439  0.906533
2440  1.120401
2441  1.095646

[2442 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2530  0.242455
2531  0.250972
2532  0.293853
2533  0.445970
2534  0.468238

[2535 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2539  0.589536
2540  0.589950
2541  0.600896
2542  0.604110
2543  0.605809

[2544 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2520  0.756558
2521  0.753332
2522  0.753892
2523  0.736539
2524  0.734733

[2525 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2510  1.060403
2511  1.053685
2512  1.089552
2513  1.130978
2514  1.153459

[2515 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2531  0.601977
2532  0.588182
2533  0.591625
2534  0.682788
2535  0.726629

[2536 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2538  0.321864
2539  0.321845
2540  0.333835
2541  0.340546
2542  0.335811

[2543 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2392  0.683871
2393  0.760313
2394  0.739052
2395  0.728360
2396  0.721866

[2397 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2523  0.682671
2524  0.703272
2525  0.708187
2526  0.722086
2527  0.763710

[2528 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2509  1.102587
2510  1.125971
2511  1.123203
2512  1.117661
2513  1.171244

[2514 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2461  0.425158
2462  0.408032
2463  0.399457
2464  0.581111
2465  0.591417

[2466 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2477  0.436559
2478  0.477512
2479  0.485280
2480  0.481277
2481  0.548778

[2482 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2530  0.500240
2531  0.498372
2532  0.518519
2533  0.560578
2534  0.680062

[2535 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2445  0.698188
2446  0.686589
2447  0.688877
2448  0.724601
2449  0.736287

[2450 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2387  1.115290
2388  1.264980
2389  1.318873
2390  1.429702
2391  1.455916

[2392 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2396  0.536893
2397  0.506699
2398  0.542906
2399  0.515292
2400  0.524314

[2401 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2224  0.973391
2225  0.922068
2226  0.965760
2227  0.992561
2228  0.932057

[2229 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2530  0.848908
2531  0.823044
2532  0.845930
2533  0.742412
2534  0.740008

[2535 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2361  1.831509
2362  1.912611
2363  1.849266
2364  1.819930
2365  1.752637

[2366 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2402  0.721610
2403  0.763039
2404  0.734045
2405  0.679589
2406  0.660566

[2407 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2090  0.163050
2091  0.245528
2092  0.246587
2093  0.311066
2094  0.312878

[2095 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2351  0.785211
2352  0.794785
2353  0.806668
2354  0.829793
2355  0.833266

[2356 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2530  0.420825
2531  0.400205
2532  0.446890
2533  0.424128
2534  0.475915

[2535 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2534  0.922217
2535  0.887197
2536  0.900973
2537  0.792635
2538  0.857848

[2539 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2410  1.171789
2411  1.169158
2412  1.221432
2413  1.309048
2414  1.302915

[2415 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2489  0.541926
2490  0.559176
2491  0.538724
2492  0.575111
2493  0.582350

[2494 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2462  1.301122
2463  1.285268
2464  1.286201
2465  1.277288
2466  1.275683

[2467 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2537  0.653796
2538  0.637259
2539  0.602748
2540  0.513557
2541  0.523265

[2542 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2497  0.500511
2498  0.497949
2499  0.490741
2500  0.436323
2501  0.441570

[2502 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2534  0.286189
2535  0.265945
2536  0.290367
2537  0.365903
2538  0.397401

[2539 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2510  0.712774
2511  0.672411
2512  0.701238
2513  0.809883
2514  0.827900

[2515 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2398  0.259804
2399  0.240296
2400  0.322463
2401  0.727083
2402  0.623735

[2403 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2436  1.663907
2437  1.656273
2438  1.607013
2439  1.618679
2440  1.507575

[2441 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2333  0.329947
2334  0.317784
2335  0.294942
2336  0.200313
2337  0.162995

[2338 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2441  0.452738
2442  0.424393
2443  0.420534
2444  0.640829
2445  0.627284

[2446 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2452  0.936952
2453  0.929417
2454  0.912963
2455  1.071573
2456  1.040843

[2457 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1820  0.467604
1821  0.380943
1822  0.194167
1823  0.144138
1824  0.095091

[1825 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2376  0.916072
2377  0.910661
2378  0.875820
2379  0.834176
2380  0.818271

[2381 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2348  0.764062
2349  0.778372
2350  0.789972
2351  0.791786
2352  0.808899

[2353 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2496  0.594713
2497  0.586904
2498  0.560218
2499  0.534340
2500  0.621350

[2501 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2463  1.363622
2464  1.363567
2465  1.350948
2466  1.667717
2467  1.655820

[2468 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2506  1.088969
2507  1.081010
2508  1.215233
2509  1.329673
2510  1.341310

[2511 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2505  0.984516
2506  1.024588
2507  1.005038
2508  1.008614
2509  0.871039

[2510 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2522  1.079206
2523  1.086580
2524  1.080676
2525  1.123063
2526  1.099253

[2527 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2526  0.807560
2527  0.787909
2528  0.804761
2529  0.761938
2530  0.769811

[2531 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2406  1.531808
2407  1.397682
2408  1.265832
2409  1.374040
2410  1.405387

[2411 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2294  0.700279
2295  0.716657
2296  0.706163
2297  0.656407
2298  0.639333

[2299 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2540  0.369992
2541  0.398312
2542  0.392909
2543  0.463216
2544  0.479696

[2545 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2251  1.572375
2252  1.274286
2253  1.333787
2254  1.204264
2255  0.920241

[2256 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2440  1.560865
2441  1.554283
2442  1.570616
2443  1.480947
2444  1.515595

[2445 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2515  1.245713
2516  1.202667
2517  1.242393
2518  1.374148
2519  1.411232

[2520 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2363  1.046883
2364  1.073562
2365  1.079805
2366  1.109209
2367  1.044436

[2368 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2336  0.435569
2337  0.448468
2338  0.458061
2339  0.399197
2340  0.381935

[2341 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2487  1.483700
2488  1.545725
2489  1.545892
2490  1.583710
2491  1.558629

[2492 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2073  0.773986
2074  0.779322
2075  0.757157
2076  0.868727
2077  0.872280

[2078 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2503  1.443954
2504  1.513328
2505  1.611118
2506  1.590795
2507  1.858254

[2508 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2419  0.948800
2420  0.974687
2421  0.962539
2422  1.099376
2423  1.081414

[2424 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2387  0.907830
2388  0.961998
2389  0.950800
2390  1.034072
2391  1.018657

[2392 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2518  0.514231
2519  0.512604
2520  0.514824
2521  0.550822
2522  0.556122

[2523 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2345  0.758025
2346  0.758467
2347  0.784110
2348  0.787410
2349  0.790066

[2350 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2388  1.282997
2389  1.277101
2390  1.296496
2391  1.282842
2392  1.266354

[2393 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2537  0.757359
2538  0.759273
2539  0.762672
2540  0.708179
2541  0.699330

[2542 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2443  0.862964
2444  0.847727
2445  0.849421
2446  0.808861
2447  0.787874

[2448 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2478  0.780526
2479  0.757513
2480  0.777637
2481  0.882672
2482  0.900011

[2483 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2448  1.372469
2449  1.325209
2450  1.344798
2451  1.368668
2452  1.346997

[2453 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2435  0.488170
2436  0.482782
2437  0.512780
2438  0.478949
2439  0.484733

[2440 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2494  1.578462
2495  1.619429
2496  1.706524
2497  2.145853
2498  2.104588

[2499 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2523  0.983159
2524  1.100288
2525  1.044849
2526  1.175884
2527  1.153076

[2528 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2507  1.802902
2508  1.784534
2509  1.837073
2510  1.896576
2511  1.877410

[2512 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2257  2.293577
2258  2.285636
2259  2.273593
2260  2.213128
2261  2.198346

[2262 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2537  0.447020
2538  0.466743
2539  0.482006
2540  0.434458
2541  0.449035

[2542 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2364  0.572806
2365  0.563035
2366  0.528257
2367  0.475083
2368  0.437628

[2369 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2303  1.088934
2304  1.088312
2305  1.114367
2306  1.107066
2307  1.104225

[2308 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2518  2.287847
2519  2.272474
2520  2.271571
2521  2.339864
2522  2.290208

[2523 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2516  0.800786
2517  0.801770
2518  0.806192
2519  0.788963
2520  0.787631

[2521 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2510  0.670310
2511  0.674508
2512  0.584923
2513  0.672165
2514  0.745651

[2515 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2450  0.530204
2451  0.508502
2452  0.540931
2453  0.558497
2454  0.562333

[2455 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2532  1.333678
2533  1.318334
2534  1.332010
2535  1.334172
2536  1.319534

[2537 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2528  0.416000
2529  0.557483
2530  0.508081
2531  0.591189
2532  0.606724

[2533 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2349  0.952090
2350  0.909454
2351  0.931857
2352  0.864690
2353  0.831381

[2354 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2442  0.965066
2443  0.960077
2444  0.978208
2445  1.010432
2446  1.024942

[2447 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2267  0.919382
2268  0.864873
2269  0.906172
2270  0.923965
2271  0.897585

[2272 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2538  0.669084
2539  0.659464
2540  0.669782
2541  0.666334
2542  0.686076

[2543 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2536  0.822126
2537  0.805525
2538  0.835771
2539  0.842398
2540  0.830128

[2541 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2454  0.599763
2455  0.550552
2456  0.582973
2457  0.598341
2458  0.406777

[2459 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2468  0.769169
2469  0.946250
2470  0.868163
2471  1.135042
2472  1.127562

[2473 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2509  1.209595
2510  1.202747
2511  1.223705
2512  1.214871
2513  1.188553

[2514 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2391  1.030232
2392  1.091168
2393  1.118550
2394  1.141525
2395  1.255452

[2396 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2532  1.344106
2533  1.315019
2534  1.327304
2535  1.454271
2536  1.407206

[2537 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2523  1.583623
2524  1.567269
2525  1.602577
2526  1.498807
2527  1.457004

[2528 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2495  0.097748
2496  0.129106
2497  0.102090
2498  0.346469
2499  0.327618

[2500 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2240  1.093786
2241  1.201410
2242  1.200236
2243  1.388234
2244  1.380095

[2245 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2517  1.225384
2518  1.211783
2519  1.222577
2520  1.129984
2521  1.126088

[2522 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2160  1.445692
2161  1.435128
2162  1.451658
2163  1.379432
2164  1.361938

[2165 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2468  0.616370
2469  0.689972
2470  0.703968
2471  0.523388
2472  0.528535

[2473 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2526  0.935645
2527  0.912090
2528  0.919063
2529  0.871499
2530  0.868020

[2531 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2217  0.954838
2218  0.942989
2219  0.941740
2220  0.898526
2221  0.899844

[2222 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2463  1.007491
2464  1.056249
2465  1.063575
2466  1.140477
2467  1.122072

[2468 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2444  0.548612
2445  0.602885
2446  0.611457
2447  0.508764
2448  0.458275

[2449 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1213  0.591095
1214  0.566108
1215  0.500564
1216  0.653452
1217  0.607577

[1218 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1857  1.287553
1858  1.075192
1859  1.079591
1860  0.986022
1861  0.924858

[1862 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2442  0.259264
2443  0.234525
2444  0.235876
2445  0.153415
2446  0.132119

[2447 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2377  0.258387
2378  0.248045
2379  0.271865
2380  0.245218
2381  0.240674

[2382 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2402  0.517773
2403  0.506094
2404  0.513738
2405  0.664110
2406  0.671002

[2407 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2319  0.529080
2320  0.554301
2321  0.577469
2322  0.488018
2323  0.469752

[2324 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2453  1.372108
2454  1.379127
2455  1.399325
2456  1.350596
2457  1.337781

[2458 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2299  0.321243
2300  0.290709
2301  0.360656
2302  0.426223
2303  0.462859

[2304 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2168  1.226979
2169  1.205436
2170  1.264568
2171  1.302554
2172  1.330614

[2173 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2509  0.674365
2510  0.674827
2511  0.675372
2512  0.776512
2513  0.769591

[2514 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2194  0.705035
2195  0.693249
2196  0.697554
2197  0.683979
2198  0.659510

[2199 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2394  0.940548
2395  0.966664
2396  0.973207
2397  0.902248
2398  0.948125

[2399 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2538  0.579982
2539  0.568255
2540  0.597695
2541  0.527297
2542  0.582994

[2543 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2506  1.536452
2507  1.513032
2508  1.511247
2509  1.466784
2510  1.424479

[2511 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2416  0.762927
2417  0.786986
2418  0.729186
2419  0.693456
2420  0.604627

[2421 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2428  0.685602
2429  0.664698
2430  0.651835
2431  0.608090
2432  0.641583

[2433 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2367  0.514053
2368  0.489846
2369  0.456273
2370  0.409992
2371  0.395637

[2372 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2268  0.469699
2269  0.424855
2270  0.410208
2271  0.416174
2272  0.386298

[2273 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2526  0.549989
2527  0.517091
2528  0.534394
2529  0.566192
2530  0.567393

[2531 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2399  0.506893
2400  0.524960
2401  0.532172
2402  0.645273
2403  0.623355

[2404 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2344  0.704031
2345  0.759649
2346  0.766838
2347  0.800699
2348  0.787948

[2349 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2533  0.704763
2534  0.670162
2535  0.676054
2536  0.698227
2537  0.689478

[2538 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2490  0.492345
2491  0.474488
2492  0.489383
2493  0.514795
2494  0.513654

[2495 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2488  1.637560
2489  1.610648
2490  1.634741
2491  1.560429
2492  1.570190

[2493 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2474  1.115087
2475  1.103972
2476  1.112615
2477  0.989863
2478  1.044068

[2479 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2297  0.842103
2298  0.834795
2299  0.831215
2300  0.794329
2301  0.859443

[2302 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2335  0.494916
2336  0.564372
2337  0.571873
2338  0.483395
2339  0.527929

[2340 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2501  1.387424
2502  1.375783
2503  1.395332
2504  1.255237
2505  1.293591

[2506 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2499  0.478493
2500  0.472093
2501  0.484865
2502  0.455400
2503  0.477840

[2504 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2537  0.555154
2538  0.541765
2539  0.535957
2540  0.553420
2541  0.547161

[2542 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2269  0.842104
2270  0.885340
2271  0.860909
2272  0.900779
2273  0.818708

[2274 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2374  1.191357
2375  1.184806
2376  1.201959
2377  1.160619
2378  1.133535

[2379 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2363  0.655983
2364  0.690265
2365  0.706200
2366  0.721920
2367  0.693815

[2368 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2528  1.840488
2529  1.835685
2530  1.852295
2531  1.815020
2532  1.772167

[2533 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2517  0.493209
2518  0.466022
2519  0.447518
2520  0.440186
2521  0.427030

[2522 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2499  1.201819
2500  1.172591
2501  1.224338
2502  1.183081
2503  1.339971

[2504 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2409  0.947204
2410  0.824299
2411  0.861820
2412  0.839277
2413  0.859273

[2414 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2400  0.719406
2401  0.703686
2402  0.732303
2403  0.707386
2404  0.711629

[2405 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2532  0.589235
2533  0.594345
2534  0.619331
2535  0.690712
2536  0.712395

[2537 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2230  0.816398
2231  0.843114
2232  0.878699
2233  0.960540
2234  0.961429

[2235 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2528  0.541008
2529  0.535288
2530  0.554722
2531  0.440326
2532  0.446644

[2533 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2329  1.110554
2330  1.300594
2331  1.340368
2332  1.714600
2333  1.694533

[2334 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2535  1.117284
2536  1.017224
2537  0.995278
2538  0.909805
2539  0.912537

[2540 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2366  0.545429
2367  0.549282
2368  0.512300
2369  0.334916
2370  0.321740

[2371 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2467  1.578863
2468  1.621985
2469  1.568376
2470  1.643534
2471  1.604696

[2472 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2516  0.610986
2517  0.796256
2518  0.717206
2519  0.794498
2520  0.747934

[2521 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2540  0.796364
2541  0.806629
2542  0.794953
2543  0.710148
2544  0.764087

[2545 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2394  2.383594
2395  2.379199
2396  2.326861
2397  2.192860
2398  2.130263

[2399 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2516  0.702571
2517  0.691497
2518  0.661412
2519  0.660791
2520  0.810611

[2521 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2433  0.593843
2434  0.642379
2435  0.610200
2436  0.522208
2437  0.497676

[2438 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2512  0.932123
2513  0.955438
2514  0.915937
2515  1.002693
2516  0.961715

[2517 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2440  0.787068
2441  0.782982
2442  0.793998
2443  0.743331
2444  0.723042

[2445 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2393  1.898940
2394  1.850224
2395  1.894206
2396  1.811657
2397  1.756866

[2398 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2448  1.344873
2449  1.377102
2450  1.376940
2451  1.308602
2452  1.263226

[2453 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2434  0.992581
2435  0.974975
2436  0.826712
2437  0.800752
2438  0.758311

[2439 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2486  0.882434
2487  0.848558
2488  0.862593
2489  0.841541
2490  0.868712

[2491 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2115  0.025991
2116 -0.045451
2117 -0.016749
2118 -0.023690
2119 -0.018684

[2120 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2532  0.741435
2533  0.726864
2534  0.767541
2535  0.719746
2536  0.703179

[2537 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2398  0.793871
2399  0.846112
2400  0.831437
2401  0.911872
2402  1.036913

[2403 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2080  1.017667
2081  1.022685
2082  1.062525
2083  1.018019
2084  0.925752

[2085 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2527  1.018172
2528  0.987023
2529  0.983207
2530  0.995292
2531  0.973566

[2532 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2419  0.236677
2420  0.174600
2421  0.076288
2422  0.073138
2423 -0.014416

[2424 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2528  1.498631
2529  1.533194
2530  1.552132
2531  1.640709
2532  1.617995

[2533 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2203  0.708361
2204  0.668880
2205  0.609238
2206  0.574779
2207  0.528607

[2208 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2494  0.841966
2495  0.844746
2496  0.842175
2497  0.797114
2498  0.789391

[2499 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2428  0.574270
2429  0.566902
2430  0.552832
2431  0.518772
2432  0.534318

[2433 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2530  0.701388
2531  0.654872
2532  0.640273
2533  0.666264
2534  0.612954

[2535 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2388  0.815310
2389  0.810087
2390  0.827652
2391  0.802562
2392  0.835879

[2393 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2460  0.094733
2461  0.215270
2462  0.177387
2463  0.293797
2464  0.286468

[2465 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2527  1.582127
2528  1.495361
2529  1.452398
2530  1.432168
2531  1.358741

[2532 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2380  1.090919
2381  1.181008
2382  1.023555
2383  0.902969
2384  0.735325

[2385 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2089  1.362599
2090  1.309818
2091  1.372710
2092  1.419265
2093  1.356046

[2094 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2230  0.035061
2231  0.147699
2232  0.162202
2233  0.127379
2234  0.146374

[2235 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2192  0.106899
2193  0.181949
2194  0.164432
2195  0.299534
2196  0.308705

[2197 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2397  1.278899
2398  1.288296
2399  1.305314
2400  1.252170
2401  1.235416

[2402 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2484  1.246567
2485  1.224423
2486  1.222171
2487  1.235803
2488  1.208421

[2489 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2502  0.699906
2503  0.691528
2504  0.700348
2505  0.697238
2506  0.693380

[2507 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2363  0.837271
2364  0.854823
2365  0.870712
2366  0.864644
2367  0.849467

[2368 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2443  0.813480
2444  0.784400
2445  0.812967
2446  0.840756
2447  0.890773

[2448 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2143  0.513163
2144  0.352094
2145  0.364986
2146  0.373243
2147  0.290755

[2148 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2530  1.064720
2531  1.060933
2532  1.045470
2533  0.932575
2534  0.879976

[2535 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2464  0.309921
2465  0.312595
2466  0.323547
2467  0.312541
2468  0.307411

[2469 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2453  1.703681
2454  1.689006
2455  1.695739
2456  1.697243
2457  1.683596

[2458 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2376  0.656329
2377  0.772465
2378  0.807033
2379  0.634859
2380  0.540027

[2381 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2288  0.265142
2289  0.207683
2290  0.256892
2291  0.147594
2292  0.238325

[2293 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2331  0.275578
2332  0.373558
2333  0.393900
2334  0.463835
2335  0.018793

[2336 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2338  1.084040
2339  1.038345
2340  1.044438
2341  1.048846
2342  1.014526

[2343 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2200  1.393633
2201  1.627148
2202  1.838482
2203  1.859130
2204  1.711098

[2205 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2406  1.093823
2407  1.089951
2408  1.162239
2409  1.150259
2410  1.072130

[2411 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2326 -0.426779
2327 -0.440030
2328 -0.400922
2329 -0.221755
2330 -0.210670

[2331 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2359  0.267791
2360  0.281127
2361  0.393323
2362  0.320814
2363  0.302219

[2364 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2406  0.382868
2407  0.357326
2408  0.393486
2409  0.412857
2410  0.422202

[2411 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2527  0.756544
2528  0.730172
2529  0.773782
2530  0.704807
2531  0.688826

[2532 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2335  0.987273
2336  1.050032
2337  1.082252
2338  1.299229
2339  1.303429

[2340 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2512  0.765507
2513  0.820254
2514  0.798311
2515  0.950446
2516  0.936614

[2517 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2504  0.772122
2505  0.785301
2506  0.790993
2507  0.727726
2508  0.715230

[2509 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2249  0.399789
2250  0.358517
2251  0.360105
2252  0.349657
2253  0.251030

[2254 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2491  0.787015
2492  0.765449
2493  0.764626
2494  0.699530
2495  0.673635

[2496 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2369  1.179646
2370  1.265238
2371  1.238579
2372  1.333302
2373  1.382810

[2374 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2224  1.449748
2225  1.457481
2226  1.491555
2227  1.399297
2228  1.386964

[2229 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2381  0.306563
2382  0.320812
2383  0.337898
2384  0.255488
2385  0.276349

[2386 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2412  1.961289
2413  1.927248
2414  1.918204
2415  1.800556
2416  1.759428

[2417 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2534  0.885707
2535  0.884177
2536  0.878966
2537  0.830258
2538  0.807169

[2539 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2540  0.251433
2541  0.249455
2542  0.270418
2543  0.242505
2544  0.269552

[2545 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2421  0.194071
2422  0.198914
2423  0.202072
2424  0.312230
2425  0.298956

[2426 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2519  0.588832
2520  0.565806
2521  0.574774
2522  0.541335
2523  0.567770

[2524 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2494 -0.102220
2495  0.033506
2496  0.001258
2497 -0.120178
2498 -0.088419

[2499 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2520  2.426621
2521  2.332735
2522  2.360127
2523  2.376933
2524  2.342166

[2525 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2538  0.352035
2539  0.338617
2540  0.347209
2541  0.333545
2542  0.337872

[2543 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2101  0.564338
2102  0.564201
2103  0.564540
2104  0.560670
2105  0.562533

[2106 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2391  0.970832
2392  0.978127
2393  1.007332
2394  0.904381
2395  0.902360

[2396 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2540  1.087455
2541  1.093961
2542  1.090852
2543  1.004530
2544  0.979455

[2545 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2337  0.887795
2338  0.887444
2339  0.856001
2340  0.810585
2341  0.798856

[2342 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2229  0.977161
2230  0.956597
2231  0.974075
2232  0.933762
2233  0.914430

[2234 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2537  0.861867
2538  0.897706
2539  0.907240
2540  0.906075
2541  0.861935

[2542 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2284  0.902817
2285  0.926544
2286  0.937970
2287  0.853493
2288  0.848057

[2289 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2476  0.997943
2477  1.056657
2478  1.063543
2479  1.018043
2480  1.057446

[2481 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2517  0.573096
2518  0.556695
2519  0.569366
2520  0.532070
2521  0.542351

[2522 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2461  0.765260
2462  0.944791
2463  0.866862
2464  0.890943
2465  0.751184

[2466 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2498  0.421740
2499  0.438284
2500  0.421129
2501  0.384584
2502  0.365048

[2503 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2485  0.741350
2486  0.736049
2487  0.813325
2488  0.772656
2489  0.767721

[2490 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2518  0.256299
2519  0.220374
2520  0.238881
2521  0.362299
2522  0.328479

[2523 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2484  0.190376
2485  0.157543
2486  0.196087
2487  0.202982
2488  0.259704

[2489 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2486  0.560236
2487  0.569191
2488  0.518614
2489  0.522427
2490  0.484947

[2491 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2501  0.886342
2502  0.876690
2503  0.894940
2504  0.883617
2505  0.880178

[2506 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2477  0.797208
2478  0.777877
2479  0.789927
2480  0.817155
2481  0.819559

[2482 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2369  0.053301
2370  0.140651
2371  0.142201
2372  0.037945
2373  0.015902

[2374 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2435  1.100129
2436  1.108613
2437  1.112024
2438  1.099036
2439  1.081314

[2440 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2400  0.973769
2401  0.947254
2402  0.973381
2403  1.079041
2404  1.083539

[2405 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2456  0.840977
2457  0.825764
2458  0.832196
2459  0.809215
2460  0.810151

[2461 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2383  1.294435
2384  1.335219
2385  1.339936
2386  1.282025
2387  1.279610

[2388 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2389  0.432412
2390  0.479671
2391  0.484670
2392  0.470430
2393  0.482143

[2394 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2324  1.149181
2325  1.090462
2326  1.125940
2327  1.241142
2328  1.239479

[2329 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2525  0.276648
2526  0.313643
2527  0.273349
2528  0.378732
2529  0.316613

[2530 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2403  1.219429
2404  1.193695
2405  1.165918
2406  1.168017
2407  1.158150

[2408 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2519  1.149631
2520  1.193789
2521  1.171264
2522  1.332341
2523  1.348878

[2524 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2433  0.309219
2434  0.295310
2435  0.308670
2436  0.339974
2437  0.330055

[2438 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2536  0.720542
2537  0.686555
2538  0.603260
2539  0.381598
2540  0.200055

[2541 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2465  0.905883
2466  0.954317
2467  0.941909
2468  0.807667
2469  0.800265

[2470 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2532  0.756035
2533  0.769679
2534  0.782896
2535  0.738977
2536  0.757668

[2537 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2254  1.024388
2255  1.009550
2256  0.934572
2257  0.914026
2258  0.818478

[2259 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2529  0.454550
2530  0.444046
2531  0.471313
2532  0.491809
2533  0.498227

[2534 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2532  0.716433
2533  0.702921
2534  0.683025
2535  0.681895
2536  0.675238

[2537 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2405  1.371755
2406  1.376260
2407  1.392493
2408  1.344941
2409  1.384158

[2410 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2504  0.881960
2505  0.849192
2506  0.874262
2507  0.811718
2508  0.809716

[2509 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2517  0.519097
2518  0.572767
2519  0.575661
2520  0.602491
2521  0.414431

[2522 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2413  1.466721
2414  1.434098
2415  1.453607
2416  1.635914
2417  1.644290

[2418 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2108  0.299775
2109  0.480520
2110  0.437522
2111  0.793066
2112  0.767257

[2113 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2289  0.944399
2290  0.922397
2291  0.897439
2292  0.776237
2293  0.678754

[2294 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2535  0.617227
2536  0.577203
2537  0.563190
2538  0.582797
2539  0.555121

[2540 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2494  0.428619
2495  0.473744
2496  0.471490
2497  0.467098
2498  0.523011

[2499 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2035  2.275317
2036  2.119576
2037  2.215002
2038  2.379642
2039  2.498739

[2040 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2195  0.398600
2196  0.498443
2197  0.503491
2198  0.413858
2199  0.402596

[2200 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2541  0.365847
2542  0.364676
2543  0.375699
2544  0.374366
2545  0.383267

[2546 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2415  0.909791
2416  0.962861
2417  0.958103
2418  0.980945
2419  1.005391

[2420 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2539  0.764902
2540  0.746339
2541  0.787361
2542  0.719551
2543  0.739761

[2544 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2459  0.821801
2460  0.806270
2461  0.827601
2462  0.759763
2463  0.812378

[2464 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2518  0.653340
2519  0.659768
2520  0.693561
2521  0.724893
2522  0.803098

[2523 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2528  0.806535
2529  0.776167
2530  0.770049
2531  0.780685
2532  0.789819

[2533 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2530  1.160903
2531  1.188669
2532  1.197791
2533  1.139239
2534  1.130323

[2535 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2324  0.416030
2325  0.425513
2326  0.421670
2327  0.418245
2328  0.415285

[2329 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2524  0.305209
2525  0.356286
2526  0.332507
2527  0.329237
2528  0.364198

[2529 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2413  1.845812
2414  1.823832
2415  1.814833
2416  1.728759
2417  1.651915

[2418 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2415  1.002459
2416  1.000824
2417  1.001798
2418  0.971882
2419  0.990921

[2420 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2355  0.627525
2356  0.666079
2357  0.673428
2358  0.764473
2359  0.792353

[2360 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2499  0.234505
2500  0.233665
2501  0.225435
2502  0.140860
2503  0.142106

[2504 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2284  0.849142
2285  0.828603
2286  0.816504
2287  0.794210
2288  0.785854

[2289 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2514  1.075499
2515  1.077984
2516  1.046868
2517  1.013234
2518  0.956508

[2519 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2498  0.907371
2499  0.919144
2500  0.979208
2501  0.792020
2502  0.782835

[2503 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2201  1.301656
2202  1.320904
2203  1.252654
2204  1.072953
2205  1.215577

[2206 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2384  0.882044
2385  0.875476
2386  0.884327
2387  0.859368
2388  0.863544

[2389 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2493  0.918657
2494  0.912522
2495  0.950797
2496  0.936696
2497  0.988091

[2498 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2518  0.856335
2519  0.875301
2520  0.879487
2521  0.865611
2522  0.854892

[2523 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2512  1.441558
2513  1.401726
2514  1.409890
2515  1.260506
2516  1.280208

[2517 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2226  0.816783
2227  0.793491
2228  0.815756
2229  0.789660
2230  0.853757

[2231 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2535  0.449443
2536  0.442797
2537  0.460238
2538  0.458740
2539  0.479738

[2540 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2503  0.335291
2504  0.307498
2505  0.322733
2506  0.259504
2507  0.201586

[2508 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2495  0.548880
2496  0.543128
2497  0.530322
2498  0.544013
2499  0.538026

[2500 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2507  1.125221
2508  1.099090
2509  1.118612
2510  1.144627
2511  1.138865

[2512 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2434  1.122870
2435  1.212155
2436  1.157267
2437  0.919530
2438  0.867174

[2439 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2491  0.311332
2492  0.533236
2493  0.877211
2494  0.813804
2495  0.764050

[2496 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2450  1.725754
2451  1.738215
2452  1.734741
2453  1.691810
2454  1.660531

[2455 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2466  0.775136
2467  0.794344
2468  0.807075
2469  0.797515
2470  0.779917

[2471 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2228  0.910694
2229  0.828830
2230  0.860338
2231  0.832321
2232  0.733633

[2233 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2440  1.329084
2441  1.321367
2442  1.237382
2443  1.364272
2444  1.337909

[2445 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2523  1.840531
2524  1.860070
2525  1.866872
2526  1.710550
2527  1.684999

[2528 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2529  0.935308
2530  0.857150
2531  0.913936
2532  1.278604
2533  1.245372

[2534 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2532  0.864329
2533  0.852446
2534  0.839816
2535  0.813609
2536  0.856644

[2537 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2399  1.495611
2400  1.518357
2401  1.471865
2402  1.412912
2403  1.407188

[2404 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2283  1.164397
2284  1.160861
2285  1.089869
2286  1.134418
2287  1.105372

[2288 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2473  0.395805
2474  0.475480
2475  0.468183
2476  0.831538
2477  0.833265

[2478 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2536  0.783907
2537  0.830932
2538  0.822801
2539  0.794630
2540  0.792377

[2541 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2518  0.852662
2519  0.844532
2520  0.854182
2521  0.887310
2522  0.872538

[2523 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2370  1.085175
2371  1.078800
2372  1.107076
2373  1.107526
2374  1.115440

[2375 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2474  0.665617
2475  0.654944
2476  0.616809
2477  0.614036
2478  0.491229

[2479 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2539  0.875615
2540  1.063875
2541  1.018222
2542  1.130848
2543  1.097408

[2544 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2334  0.724861
2335  0.710138
2336  0.696232
2337  0.688664
2338  0.672534

[2339 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2453  1.018158
2454  1.042588
2455  1.089182
2456  1.007765
2457  1.002986

[2458 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2313  0.221088
2314  0.228872
2315  0.267330
2316  0.170419
2317  0.160373

[2318 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2513  0.242344
2514  0.221095
2515  0.253213
2516  0.330233
2517  0.387756

[2518 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2538  0.193444
2539  0.156860
2540  0.172404
2541  0.135771
2542  0.143414

[2543 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2360  2.029475
2361  1.989795
2362  1.960980
2363  1.957563
2364  1.896499

[2365 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2187  1.408085
2188  1.327138
2189  1.350430
2190  1.259486
2191  1.231199

[2192 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2484  1.445134
2485  1.509467
2486  1.503084
2487  1.420584
2488  1.350653

[2489 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2096  0.383195
2097  0.382160
2098  0.243870
2099  0.134739
2100  0.217877

[2101 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2507  0.755355
2508  0.769562
2509  0.792532
2510  0.778663
2511  0.790011

[2512 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2533  0.610479
2534  0.609643
2535  0.646331
2536  0.805591
2537  0.962681

[2538 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2128  0.752545
2129  0.793867
2130  0.829102
2131  0.760370
2132  0.648921

[2133 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2538  1.079215
2539  1.124015
2540  1.113435
2541  1.283897
2542  1.272943

[2543 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2417  0.832101
2418  0.827398
2419  0.868648
2420  0.800733
2421  0.783855

[2422 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2516  0.720063
2517  0.721209
2518  0.721429
2519  0.684515
2520  0.681980

[2521 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2394  0.529098
2395  0.569911
2396  0.568267
2397  0.662103
2398  0.657426

[2399 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2394  0.867571
2395  0.852510
2396  0.871076
2397  0.906967
2398  0.908207

[2399 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2512  1.642441
2513  1.632407
2514  1.600405
2515  1.513703
2516  1.506277

[2517 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2290  0.548318
2291  0.563926
2292  0.574795
2293  0.521073
2294  0.530227

[2295 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2287  0.411927
2288  0.416018
2289  0.420986
2290  0.369533
2291  0.396378

[2292 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2489  0.347909
2490  0.320983
2491  0.330928
2492  0.378868
2493  0.382181

[2494 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2427  1.247377
2428  1.380341
2429  1.374123
2430  1.381706
2431  1.499684

[2432 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2446  1.119973
2447  1.093450
2448  1.118088
2449  1.154312
2450  1.190396

[2451 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2486  0.492741
2487  0.496807
2488  0.536592
2489  0.576230
2490  0.578804

[2491 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2295  0.393018
2296  0.414479
2297  0.405702
2298  0.280857
2299  0.263144

[2300 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2439  0.459947
2440  0.469336
2441  0.461520
2442  0.469761
2443  0.460929

[2444 rows x 1 columns]
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2490  0.744215
2491  0.741150
2492  0.763858
2493  0.818578
2494  0.820430

[2495 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2515  1.263468
2516  1.254959
2517  1.262861
2518  1.173575
2519  1.158794

[2520 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2395  1.128729
2396  1.087205
2397  1.105811
2398  1.133619
2399  1.116376

[2400 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2282  0.518948
2283  0.501126
2284  0.551162
2285  0.520896
2286  0.538265

[2287 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2501  1.209204
2502  1.210223
2503  1.195266
2504  1.163725
2505  1.139792

[2506 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2476  1.609330
2477  1.667465
2478  1.621348
2479  2.046454
2480  2.022788

[2481 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2526  1.276473
2527  1.262152
2528  1.332264
2529  1.314881
2530  1.303032

[2531 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2463  0.780681
2464  0.822108
2465  0.852571
2466  0.770829
2467  0.487041

[2468 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2451  0.257369
2452  0.184411
2453  0.175955
2454  0.105232
2455  0.092039

[2456 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2324  0.487052
2325  0.480938
2326  0.461182
2327  0.679571
2328  0.670724

[2329 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2411  0.501088
2412  0.525565
2413  0.541589
2414  0.660575
2415  0.630944

[2416 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2376  0.657711
2377  0.655636
2378  0.648737
2379  0.730157
2380  0.736807

[2381 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2494  0.662196
2495  0.678044
2496  0.676000
2497  0.786434
2498  0.822294

[2499 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2269  0.473984
2270  0.561494
2271  0.572427
2272  0.407639
2273  0.402288

[2274 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2517  1.192905
2518  1.133052
2519  1.163930
2520  1.101499
2521  1.142171

[2522 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2531  1.246153
2532  1.257410
2533  1.260112
2534  1.223402
2535  1.277588

[2536 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2436  0.770848
2437  0.768597
2438  0.779157
2439  0.795980
2440  0.782638

[2441 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2424  0.394128
2425  0.406456
2426  0.386851
2427  0.597238
2428  0.582732

[2429 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2306  0.850662
2307  0.849501
2308  0.849192
2309  0.797096
2310  0.789751

[2311 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2517  0.646186
2518  0.623166
2519  0.619440
2520  0.623614
2521  0.610261

[2522 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2521  0.631534
2522  0.673572
2523  0.669998
2524  0.705291
2525  0.718406

[2526 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2393  1.856394
2394  1.783128
2395  1.784049
2396  1.682394
2397  1.720291

[2398 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2525  0.915361
2526  0.859787
2527  0.886262
2528  0.738905
2529  0.752267

[2530 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2372  0.994356
2373  1.017329
2374  1.023523
2375  1.007622
2376  1.004265

[2377 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2415  1.813282
2416  1.808571
2417  1.809146
2418  1.843616
2419  1.792480

[2420 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2460  0.273735
2461  0.280368
2462  0.303839
2463  0.326570
2464  0.328705

[2465 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2480  1.120261
2481  1.129048
2482  1.181748
2483  1.308102
2484  1.365617

[2485 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2489  1.057535
2490  1.046283
2491  1.062651
2492  1.116366
2493  1.113932

[2494 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1931  0.940113
1932  0.947503
1933  0.965876
1934  0.923738
1935  0.935636

[1936 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2539  1.035642
2540  1.016929
2541  1.004220
2542  0.896686
2543  0.875648

[2544 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2405  1.245000
2406  1.211536
2407  1.221135
2408  1.207155
2409  1.193579

[2410 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2522  1.809738
2523  1.901091
2524  1.764526
2525  1.636634
2526  1.549354

[2527 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2459  1.694590
2460  1.684721
2461  1.694063
2462  1.666283
2463  1.666749

[2464 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2395  0.491690
2396  0.483672
2397  0.488987
2398  0.546733
2399  0.538912

[2400 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2026 -0.072754
2027  0.007083
2028 -0.010934
2029  0.194803
2030  0.125573

[2031 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2522  1.412072
2523  1.403034
2524  1.430997
2525  1.402021
2526  1.384147

[2527 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2377  0.629816
2378  0.621831
2379  0.647539
2380  0.639161
2381  0.737259

[2382 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2529  1.273795
2530  1.302269
2531  1.276329
2532  1.393275
2533  1.390618

[2534 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2335  1.133996
2336  1.061122
2337  0.907605
2338  0.737507
2339  0.709598

[2340 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2358  0.879600
2359  0.869705
2360  0.904887
2361  0.862568
2362  0.858428

[2363 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2530  0.835426
2531  0.829681
2532  0.805761
2533  0.821444
2534  0.903761

[2535 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2389  0.758587
2390  0.788275
2391  0.820328
2392  0.834342
2393  0.858951

[2394 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2510  1.092146
2511  1.079044
2512  1.112036
2513  1.070744
2514  1.071976

[2515 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2501  1.305772
2502  1.317289
2503  1.307483
2504  1.354456
2505  1.346278

[2506 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2351  1.063296
2352  1.047020
2353  1.036753
2354  0.972012
2355  0.910513

[2356 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2521  0.555910
2522  0.561933
2523  0.549378
2524  0.581219
2525  0.584170

[2526 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2399  1.435372
2400  1.414443
2401  1.369989
2402  1.303301
2403  1.311587

[2404 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2420  0.619687
2421  0.603968
2422  0.532590
2423  0.529743
2424  0.593082

[2425 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2404  0.312413
2405  0.294325
2406  0.289443
2407  0.550980
2408  0.551672

[2409 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2430  0.518380
2431  0.515527
2432  0.527211
2433  0.530969
2434  0.528626

[2435 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1736  0.296419
1737  0.311990
1738  0.301409
1739  0.323516
1740  0.342549

[1741 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2536  0.596315
2537  0.627522
2538  0.633508
2539  0.632990
2540  0.594304

[2541 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2418  1.307048
2419  1.301202
2420  1.293623
2421  1.155010
2422  1.142386

[2423 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2439  0.505276
2440  0.520102
2441  0.470124
2442  0.411437
2443  0.364033

[2444 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2507  0.512858
2508  0.510340
2509  0.485213
2510  0.403885
2511  0.433111

[2512 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2033  1.165854
2034  1.137702
2035  1.155631
2036  1.145950
2037  1.151359

[2038 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2525  0.356194
2526  0.332565
2527  0.352272
2528  0.312990
2529  0.327100

[2530 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2533  0.820570
2534  0.856568
2535  0.863280
2536  0.849055
2537  0.836407

[2538 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2525  1.083810
2526  1.011367
2527  1.026746
2528  1.272475
2529  1.276402

[2530 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2511  1.286618
2512  1.353017
2513  1.327875
2514  1.448368
2515  1.472856

[2516 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2394  0.751072
2395  0.814340
2396  0.812902
2397  0.805518
2398  0.820307

[2399 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2492  2.084046
2493  2.032019
2494  2.017893
2495  1.870035
2496  1.844439

[2497 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2323  1.167670
2324  1.157942
2325  1.164455
2326  1.075534
2327  1.063159

[2328 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2509  0.846952
2510  0.805471
2511  0.830162
2512  0.793992
2513  0.767042

[2514 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2526  1.114357
2527  1.099845
2528  1.097320
2529  1.065440
2530  1.027089

[2531 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2399  0.675048
2400  0.637014
2401  0.656513
2402  0.729725
2403  0.721942

[2404 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2457  1.200451
2458  1.170625
2459  1.195244
2460  1.146904
2461  1.216699

[2462 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2515  1.048199
2516  1.034068
2517  1.050521
2518  0.923190
2519  0.944559

[2520 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2331  1.433373
2332  1.483167
2333  1.430955
2334  1.511781
2335  1.468102

[2336 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2515  0.608049
2516  0.596479
2517  0.613308
2518  0.622366
2519  0.612565

[2520 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2538  0.412355
2539  0.396871
2540  0.416822
2541  0.405135
2542  0.412736

[2543 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2510  0.475604
2511  0.479189
2512  0.488782
2513  0.433031
2514  0.440991

[2515 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2491  1.310830
2492  1.285259
2493  1.306993
2494  1.351835
2495  1.336002

[2496 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2411  0.866430
2412  0.838640
2413  0.969547
2414  0.970919
2415  0.889145

[2416 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2478  1.122984
2479  1.077195
2480  1.097419
2481  1.187612
2482  1.190707

[2483 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2493  1.082704
2494  1.164410
2495  1.087104
2496  1.032951
2497  0.988875

[2498 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2218  0.465221
2219  0.546522
2220  0.573364
2221  0.699009
2222  0.686798

[2223 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2469  0.834879
2470  0.814426
2471  0.849789
2472  0.842536
2473  0.856310

[2474 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2404  1.396067
2405  1.419370
2406  1.445301
2407  1.417540
2408  1.387798

[2409 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2515  0.246435
2516  0.261407
2517  0.286209
2518  0.288072
2519  0.274884

[2520 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2538  0.858110
2539  0.839029
2540  0.839000
2541  0.818895
2542  0.831121

[2543 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2407  0.549207
2408  0.565504
2409  0.578048
2410  0.541706
2411  0.572683

[2412 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2520  1.328945
2521  1.447171
2522  1.473643
2523  1.503464
2524  1.412573

[2525 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2455  1.643627
2456  1.696949
2457  1.678060
2458  1.544980
2459  1.481276

[2460 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2512  0.007667
2513 -0.009385
2514  0.022967
2515 -0.037871
2516 -0.063731

[2517 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2309  0.594100
2310  0.563695
2311  0.559935
2312  0.517355
2313  0.562553

[2314 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2500  0.648842
2501  0.693271
2502  0.741409
2503  0.744403
2504  0.676667

[2505 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2530  1.102745
2531  1.067181
2532  1.073179
2533  1.027608
2534  0.997290

[2535 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2467  0.773560
2468  0.742933
2469  0.766431
2470  0.865736
2471  0.922392

[2472 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2494  0.625254
2495  0.644157
2496  0.523238
2497  0.485276
2498  0.367775

[2499 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2367  0.714447
2368  0.684899
2369  0.577846
2370  0.599556
2371  0.604218

[2372 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2508  0.849489
2509  0.846432
2510  0.854007
2511  0.773864
2512  0.787116

[2513 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2358 -0.596409
2359 -0.667758
2360 -0.759169
2361 -0.539441
2362 -0.505577

[2363 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2429  0.478616
2430  0.458318
2431  0.506790
2432  0.433604
2433  0.487182

[2434 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2523  0.901477
2524  0.927176
2525  0.891728
2526  1.026383
2527  1.174253

[2528 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2525  1.731568
2526  1.818503
2527  1.811909
2528  1.735086
2529  1.741093

[2530 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2487  1.405283
2488  1.387691
2489  1.353826
2490  1.231024
2491  1.166892

[2492 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2403  0.694457
2404  0.876780
2405  0.871069
2406  0.975704
2407  0.931749

[2408 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2300  0.521986
2301  0.520621
2302  0.544626
2303  0.496237
2304  0.467979

[2305 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2459  0.701380
2460  0.750805
2461  0.685029
2462  0.977855
2463  0.964225

[2464 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2515  1.105161
2516  1.141438
2517  1.144694
2518  1.332201
2519  1.366533

[2520 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2414  0.826679
2415  0.816248
2416  0.828436
2417  0.784116
2418  0.781467

[2419 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2475  2.790768
2476  2.764985
2477  2.756451
2478  2.719909
2479  2.641411

[2480 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2350  0.569172
2351  0.595200
2352  0.594494
2353  0.513706
2354  0.520178

[2355 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2537  0.389035
2538  0.363023
2539  0.374808
2540  0.362676
2541  0.443804

[2542 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2526  0.542581
2527  0.536485
2528  0.544784
2529  0.521628
2530  0.520691

[2531 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2493  1.959191
2494  1.898913
2495  1.918562
2496  2.096156
2497  2.082274

[2498 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2415  0.499954
2416  0.509223
2417  0.497098
2418  0.480500
2419  0.495751

[2420 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2305  1.391707
2306  1.372386
2307  1.221086
2308  1.316395
2309  1.257856

[2310 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2390  1.273440
2391  1.236391
2392  1.244263
2393  1.360292
2394  1.167719

[2395 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1372  1.840446
1373  1.853735
1374  1.941575
1375  1.893900
1376  1.770491

[1377 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2522  0.696461
2523  0.758881
2524  0.753475
2525  0.759727
2526  0.789410

[2527 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2437  0.591804
2438  0.579043
2439  0.582705
2440  0.567435
2441  0.558605

[2442 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2312  0.895137
2313  0.883468
2314  0.805963
2315  0.933505
2316  1.075175

[2317 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2538  1.875935
2539  1.737039
2540  1.694357
2541  1.453194
2542  1.477719

[2543 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2460  0.493878
2461  0.468146
2462  0.466895
2463  0.477336
2464  0.482185

[2465 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2494  1.290345
2495  1.289661
2496  1.287198
2497  1.219487
2498  1.180308

[2499 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2541  1.386910
2542  1.371364
2543  1.388276
2544  1.357047
2545  1.273995

[2546 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2316  0.610542
2317  0.572730
2318  0.591042
2319  0.555354
2320  0.588586

[2321 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2412  0.687516
2413  0.729108
2414  0.698462
2415  0.777394
2416  0.753984

[2417 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2460  0.498688
2461  0.480011
2462  0.484645
2463  0.500544
2464  0.504884

[2465 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2221  1.126308
2222  1.148513
2223  1.136842
2224  1.189568
2225  1.162614

[2226 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2466  0.459359
2467  0.447383
2468  0.465050
2469  0.480870
2470  0.500859

[2471 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2477  1.371009
2478  1.380131
2479  1.374115
2480  1.408360
2481  1.360817

[2482 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2372  1.593632
2373  1.570932
2374  1.569523
2375  1.764142
2376  1.721768

[2377 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2382  0.846688
2383  0.853579
2384  0.857561
2385  0.790659
2386  0.770770

[2387 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2538  0.849430
2539  0.850968
2540  0.889229
2541  1.015770
2542  1.051824

[2543 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2232 -0.018525
2233 -0.041728
2234 -0.023319
2235 -0.054112
2236 -0.078330

[2237 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2151  0.862995
2152  0.848462
2153  0.843567
2154  0.791729
2155  0.784342

[2156 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2291  1.231871
2292  1.209412
2293  1.204701
2294  1.121267
2295  1.111950

[2296 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2411  0.473287
2412  0.443316
2413  0.453527
2414  0.405229
2415  0.391514

[2416 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2238  1.382725
2239  1.346702
2240  1.350343
2241  1.317875
2242  1.307312

[2243 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2446  1.325457
2447  1.322911
2448  1.336745
2449  1.293816
2450  1.279151

[2451 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2375  0.556573
2376  0.534744
2377  0.548674
2378  0.625640
2379  0.639061

[2380 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2476  0.667215
2477  0.663817
2478  0.667813
2479  0.631414
2480  0.621992

[2481 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2529  1.448859
2530  1.414282
2531  1.413292
2532  1.344826
2533  1.329257

[2534 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2310  1.936587
2311  1.937467
2312  1.919324
2313  1.813895
2314  1.752510

[2315 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2533  0.765078
2534  0.743124
2535  0.785822
2536  0.815405
2537  0.882576

[2538 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2532  1.132957
2533  1.101581
2534  0.958436
2535  1.120823
2536  1.144424

[2537 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2390  0.520462
2391  0.596288
2392  0.559370
2393  0.697440
2394  0.663723

[2395 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2518  1.575180
2519  1.622115
2520  1.625694
2521  1.648426
2522  1.732000

[2523 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2381  1.673297
2382  1.689081
2383  1.693178
2384  1.579076
2385  1.580543

[2386 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2316  1.140304
2317  1.065304
2318  1.066571
2319  0.952616
2320  0.933519

[2321 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2461 -0.018871
2462  0.021164
2463  0.020468
2464  0.097590
2465  0.085849

[2466 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2473 -0.014652
2474 -0.019148
2475 -0.015434
2476 -0.048553
2477 -0.065950

[2478 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2524  0.254887
2525  0.272167
2526  0.195478
2527  0.084847
2528  0.035491

[2529 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2453  0.316325
2454  0.313441
2455  0.297881
2456  0.316809
2457  0.255897

[2458 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2516  0.569914
2517  0.561669
2518  0.596661
2519  0.592509
2520  0.590910

[2521 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2460  0.930515
2461  0.955008
2462  0.953114
2463  1.028414
2464  1.061603

[2465 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2488  0.823048
2489  0.936411
2490  0.790557
2491  0.916495
2492  0.878978

[2493 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2363  2.140737
2364  2.189395
2365  2.186169
2366  2.154796
2367  2.166629

[2368 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2538  0.575223
2539  0.541247
2540  0.552581
2541  0.791065
2542  0.849581

[2543 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2512  1.350123
2513  1.332894
2514  1.324975
2515  1.311195
2516  1.319703

[2517 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2381  1.237988
2382  1.224912
2383  1.233689
2384  1.191857
2385  1.169143

[2386 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2145  0.865478
2146  0.875223
2147  0.874720
2148  0.845512
2149  0.851928

[2150 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2398  1.109105
2399  1.073874
2400  0.983722
2401  0.960174
2402  0.894440

[2403 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2494  0.351862
2495  0.355733
2496  0.364282
2497  0.322085
2498  0.320328

[2499 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2206  0.632876
2207  0.636801
2208  0.654022
2209  0.874899
2210  1.028205

[2211 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2411  0.094603
2412  0.071167
2413  0.081079
2414  0.002630
2415  0.011530

[2416 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2316  0.687024
2317  0.660972
2318  0.673359
2319  0.887863
2320  0.939364

[2321 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1820  1.191735
1821  1.197848
1822  1.229476
1823  1.191279
1824  1.116854

[1825 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2539  0.531383
2540  0.521781
2541  0.551879
2542  0.492143
2543  0.494283

[2544 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2530  0.587813
2531  0.555166
2532  0.563878
2533  0.614014
2534  0.630823

[2535 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2470  0.632633
2471  0.639735
2472  0.637596
2473  0.649827
2474  0.630477

[2475 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2174  0.420111
2175  0.398688
2176  0.314445
2177  0.518082
2178  0.504807

[2179 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2416  0.995273
2417  1.015144
2418  0.999214
2419  1.005951
2420  0.979989

[2421 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2536  0.404135
2537  0.385958
2538  0.412347
2539  0.393004
2540  0.492172

[2541 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2332  0.785262
2333  0.753340
2334  0.745519
2335  0.627878
2336  0.620255

[2337 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2537  0.861705
2538  0.851276
2539  0.856298
2540  0.801864
2541  0.794674

[2542 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2458  0.700295
2459  0.709319
2460  0.754043
2461  0.692415
2462  0.681321

[2463 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2459  0.275889
2460  0.282887
2461  0.300279
2462  0.341836
2463  0.503161

[2464 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2475  1.807315
2476  1.856690
2477  1.921943
2478  2.147627
2479  2.102685

[2480 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2513  1.366226
2514  1.375388
2515  1.415685
2516  1.413185
2517  1.462254

[2518 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2451  0.756413
2452  0.745838
2453  0.757614
2454  0.747117
2455  0.742776

[2456 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2527  0.358215
2528  0.327503
2529  0.322973
2530  0.210394
2531  0.160715

[2532 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2488  1.146134
2489  1.132576
2490  1.097933
2491  0.901404
2492  0.895958

[2493 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2492  0.126688
2493  0.079362
2494  0.142644
2495  0.412683
2496  0.384699

[2497 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2339  0.668273
2340  0.662567
2341  0.667611
2342  0.751252
2343  0.728296

[2344 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2538  0.655391
2539  0.647033
2540  0.658970
2541  0.776870
2542  0.775954

[2543 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2042  0.789168
2043  0.891811
2044  0.936411
2045  0.913656
2046  0.890305

[2047 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1732 -0.039778
1733 -0.035739
1734  0.044065
1735  0.050908
1736  0.148134

[1737 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2536  0.567944
2537  0.536502
2538  0.575476
2539  0.532140
2540  0.511333

[2541 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2224  0.735503
2225  0.716206
2226  0.741337
2227  0.731208
2228  0.716590

[2229 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2299  0.962990
2300  0.961872
2301  0.970220
2302  0.940024
2303  0.923374

[2304 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2525  1.004343
2526  0.981429
2527  0.906890
2528  1.018931
2529  1.000433

[2530 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2483  0.923128
2484  0.906753
2485  0.909486
2486  0.991865
2487  0.946306

[2488 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2419  2.299443
2420  2.281782
2421  2.385780
2422  2.297101
2423  2.289012

[2424 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2352  2.269842
2353  2.282844
2354  2.322378
2355  2.309986
2356  2.250246

[2357 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2536  0.234931
2537  0.219315
2538  0.206561
2539  0.173859
2540  0.118709

[2541 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2315  0.942226
2316  0.931518
2317  0.960242
2318  0.972506
2319  0.970166

[2320 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2496  0.828081
2497  0.806670
2498  0.825425
2499  0.792211
2500  0.795290

[2501 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2145  0.516113
2146  0.576476
2147  0.497354
2148  0.426212
2149  0.368371

[2150 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2426  1.052436
2427  1.026305
2428  1.082971
2429  0.995886
2430  0.938659

[2431 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2496  0.536381
2497  0.547700
2498  0.546356
2499  0.523726
2500  0.527373

[2501 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2179  0.487185
2180  0.458940
2181  0.453310
2182  0.614025
2183  0.636164

[2184 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2530  1.023865
2531  1.025424
2532  1.036179
2533  1.011244
2534  1.007302

[2535 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2407  0.089620
2408  0.075014
2409  0.040027
2410  0.077075
2411  0.193529

[2412 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2355  1.069082
2356  1.187645
2357  1.178411
2358  1.162610
2359  1.052151

[2360 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2271  0.769628
2272  0.733789
2273  0.741789
2274  0.724347
2275  0.818516

[2276 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2019  0.402688
2020  0.299776
2021  0.304515
2022  0.341253
2023  0.237627

[2024 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2300  0.560879
2301  0.553920
2302  0.568427
2303  0.494765
2304  0.524880

[2305 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2405  0.687606
2406  0.669838
2407  0.651619
2408  0.642975
2409  0.795390

[2410 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2516  1.357160
2517  1.341057
2518  1.311411
2519  1.447566
2520  1.414531

[2521 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2541  0.818774
2542  0.762611
2543  0.777710
2544  0.686721
2545  0.680115

[2546 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2405  0.941679
2406  0.992671
2407  0.990575
2408  0.945900
2409  0.938477

[2410 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2493  0.440672
2494  0.388418
2495  0.453869
2496  0.569377
2497  0.510849

[2498 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2420  0.710261
2421  0.719938
2422  0.715278
2423  0.725233
2424  0.737528

[2425 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2371  0.500774
2372  0.501400
2373  0.588233
2374  0.556834
2375  0.603739

[2376 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2527  0.215391
2528  0.163265
2529  0.188240
2530  0.171412
2531  0.207361

[2532 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2112  0.290128
2113  0.259480
2114  0.179701
2115  0.194636
2116  0.261411

[2117 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2401  1.689849
2402  1.690049
2403  1.685014
2404  1.620267
2405  1.622790

[2406 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2537  0.902339
2538  0.894335
2539  0.917016
2540  0.944585
2541  0.962674

[2542 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2129  0.457853
2130  0.396247
2131  0.473212
2132  0.366592
2133  0.404906

[2134 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2265  0.641817
2266  0.678083
2267  0.664000
2268  0.717231
2269  0.696413

[2270 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2511  0.374413
2512  0.408300
2513  0.405242
2514  0.356123
2515  0.367237

[2516 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2258  0.555162
2259  0.520650
2260  0.524568
2261  0.496745
2262  0.520062

[2263 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2481  0.661970
2482  0.666560
2483  0.667450
2484  0.520294
2485  0.483641

[2486 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2370  0.219685
2371  0.243505
2372  0.202870
2373  0.117520
2374  0.152520

[2375 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2049  1.623754
2050  1.583910
2051  1.579203
2052  1.367016
2053  1.438800

[2054 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2461  0.658981
2462  0.649994
2463  0.634311
2464  0.595190
2465  0.550639

[2466 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1849  0.549942
1850  0.536795
1851  0.537802
1852  0.495752
1853  0.493143

[1854 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2132  0.848956
2133  0.822303
2134  0.819095
2135  0.828958
2136  0.831566

[2137 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2507  0.636823
2508  0.583860
2509  0.579749
2510  0.517409
2511  0.568820

[2512 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2539  0.555079
2540  0.532711
2541  0.518983
2542  0.470705
2543  0.485533

[2544 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2240  0.654518
2241  0.649863
2242  0.650863
2243  0.978959
2244  0.952613

[2245 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2434  0.785554
2435  0.777610
2436  0.780778
2437  0.734112
2438  0.734782

[2439 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2027  1.041643
2028  0.975903
2029  0.990941
2030  0.830610
2031  0.816706

[2032 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2491  1.237945
2492  1.237459
2493  1.245707
2494  1.243762
2495  1.236223

[2496 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2379  0.758209
2380  0.763949
2381  0.775791
2382  0.751875
2383  0.747579

[2384 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2445  0.658820
2446  0.612660
2447  0.614156
2448  0.474341
2449  0.484105

[2450 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2380  0.667796
2381  0.651484
2382  0.657301
2383  0.585425
2384  0.583406

[2385 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2535  1.155677
2536  1.096227
2537  1.075987
2538  0.991930
2539  0.997798

[2540 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2500  0.352319
2501  0.341157
2502  0.351615
2503  0.371499
2504  0.399934

[2505 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2468  0.445016
2469  0.444676
2470  0.455648
2471  0.445462
2472  0.439468

[2473 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2439  1.840500
2440  1.882101
2441  1.954758
2442  1.985735
2443  1.940828

[2444 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2350 -0.060455
2351 -0.013492
2352 -0.025244
2353 -0.100617
2354 -0.099494

[2355 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2524  0.211790
2525  0.216128
2526  0.242224
2527  0.207750
2528  0.231158

[2529 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2203  0.728130
2204  0.754924
2205  0.688537
2206  0.656639
2207  0.663203

[2208 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2185  1.753350
2186  1.735735
2187  1.663071
2188  1.543497
2189  1.500484

[2190 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2177  0.325216
2178  0.348533
2179  0.319467
2180  0.281002
2181  0.204629

[2182 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2486  0.561769
2487  0.550488
2488  0.499796
2489  0.447332
2490  0.587576

[2491 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2490  2.526896
2491  2.541006
2492  2.538799
2493  2.509854
2494  2.442496

[2495 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2428  0.723824
2429  0.705763
2430  0.713137
2431  0.725998
2432  0.762150

[2433 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1788  0.924350
1789  0.918610
1790  0.943996
1791  0.946412
1792  0.943636

[1793 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2464  1.159262
2465  1.145145
2466  1.162237
2467  1.005082
2468  0.990532

[2469 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2434  1.705658
2435  1.668378
2436  1.634911
2437  1.536180
2438  1.470301

[2439 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2481  0.412730
2482  0.381518
2483  0.388881
2484  0.380774
2485  0.418365

[2486 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2075  0.957646
2076  1.022682
2077  1.025010
2078  1.044956
2079  1.054414

[2080 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2322  1.126532
2323  1.109153
2324  1.019465
2325  1.192340
2326  1.112951

[2327 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2528  0.774062
2529  0.800067
2530  0.820160
2531  0.778655
2532  0.764309

[2533 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2507  0.580459
2508  0.598087
2509  0.592873
2510  0.640702
2511  0.627902

[2512 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2351  1.182234
2352  1.200972
2353  1.164046
2354  1.102976
2355  1.075668

[2356 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2299  1.330958
2300  1.339056
2301  1.358207
2302  1.261282
2303  1.291593

[2304 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2509  0.962255
2510  0.969730
2511  0.960749
2512  0.921632
2513  0.949740

[2514 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2529  0.485656
2530  0.471633
2531  0.481675
2532  0.482882
2533  0.482796

[2534 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2524  1.035831
2525  1.089209
2526  1.088726
2527  1.092302
2528  1.165623

[2529 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2343  0.807207
2344  0.808974
2345  0.754614
2346  0.974104
2347  0.925582

[2348 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2526  0.990296
2527  0.957941
2528  0.991078
2529  1.109870
2530  1.173416

[2531 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2396  0.609827
2397  0.567966
2398  0.588314
2399  0.602228
2400  0.688062

[2401 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2401  0.941708
2402  0.936647
2403  0.950829
2404  1.061950
2405  1.075725

[2406 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2508 -0.135959
2509 -0.149251
2510 -0.114121
2511  0.161870
2512  0.188272

[2513 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2459  1.049020
2460  1.040273
2461  1.059187
2462  0.954811
2463  0.955799

[2464 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2155  0.450336
2156  0.422681
2157  0.444592
2158  0.466419
2159  0.429687

[2160 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2510  0.612204
2511  0.664475
2512  0.670802
2513  0.674363
2514  0.656368

[2515 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2064  0.725507
2065  0.719671
2066  0.789103
2067  0.774966
2068  0.853266

[2069 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2313  2.074238
2314  2.056311
2315  2.039979
2316  1.919092
2317  1.880397

[2318 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2373  0.046442
2374  0.038855
2375 -0.086248
2376 -0.158422
2377 -0.115328

[2378 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2403  0.758501
2404  0.746523
2405  0.791099
2406  0.729061
2407  0.711355

[2408 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2510  0.611242
2511  0.629219
2512  0.593358
2513  0.585488
2514  0.599290

[2515 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2071  1.456480
2072  1.433295
2073  1.426537
2074  1.344962
2075  1.368685

[2076 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2032  0.584658
2033  0.547529
2034  0.575115
2035  0.715575
2036  0.706033

[2037 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1990  1.320652
1991  1.252964
1992  1.317091
1993  1.172362
1994  0.986085

[1995 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2169  0.809570
2170  0.794456
2171  0.703743
2172  0.609180
2173  0.577549

[2174 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2413  0.690475
2414  0.715156
2415  0.725331
2416  0.689428
2417  0.690736

[2418 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2504  0.959343
2505  1.057290
2506  1.013405
2507  1.156415
2508  1.132282

[2509 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2378  0.849202
2379  0.857203
2380  0.844870
2381  0.882587
2382  0.867819

[2383 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2377  1.195015
2378  1.241269
2379  1.263461
2380  1.221288
2381  1.229124

[2382 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2376  0.932034
2377  0.923045
2378  0.965549
2379  0.945545
2380  0.966458

[2381 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2475  1.529200
2476  1.535742
2477  1.573378
2478  1.593426
2479  1.665410

[2480 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2540  0.870873
2541  0.827632
2542  0.876831
2543  0.882202
2544  0.898610

[2545 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2524  0.583322
2525  0.562617
2526  0.578395
2527  0.514292
2528  0.537948

[2529 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2437  1.033309
2438  1.027369
2439  1.045186
2440  0.995820
2441  1.017628

[2442 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2047  2.556799
2048  2.510773
2049  2.378964
2050  2.325800
2051  2.397981

[2052 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2444  0.807587
2445  0.779976
2446  0.832116
2447  0.779099
2448  0.783726

[2449 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2147  0.218683
2148  0.243125
2149  0.186195
2150  0.204666
2151  0.288368

[2152 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2485  0.877221
2486  0.862016
2487  0.872767
2488  0.789201
2489  0.894522

[2490 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2264  0.717340
2265  0.716849
2266  0.705187
2267  0.634152
2268  0.680566

[2269 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2460  0.536210
2461  0.559198
2462  0.518276
2463  0.484638
2464  0.593127

[2465 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2100  1.351301
2101  1.315531
2102  1.336099
2103  1.268384
2104  1.244340

[2105 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2223  0.859826
2224  0.712368
2225  0.592571
2226  0.263975
2227  0.236312

[2228 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2408  1.094923
2409  1.074473
2410  1.104559
2411  1.003998
2412  1.046868

[2413 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2530  0.656304
2531  0.633216
2532  0.629293
2533  0.617117
2534  0.640134

[2535 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2428  1.047883
2429  1.080000
2430  1.084127
2431  1.095060
2432  1.067164

[2433 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2328  0.773163
2329  0.761391
2330  0.781941
2331  0.729122
2332  0.727184

[2333 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2426  0.616728
2427  0.583804
2428  0.596353
2429  0.550291
2430  0.545921

[2431 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2107  1.391493
2108  1.378911
2109  1.388643
2110  1.414584
2111  1.396321

[2112 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2384  0.706522
2385  0.703466
2386  0.692576
2387  0.822431
2388  0.856356

[2389 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2535  0.584632
2536  0.566001
2537  0.571764
2538  0.594764
2539  0.561079

[2540 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2382  0.665592
2383  0.681459
2384  0.671772
2385  0.724411
2386  0.680083

[2387 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2179  0.482637
2180  0.435169
2181  0.445198
2182  0.555763
2183  0.556107

[2184 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2463  0.754325
2464  0.725651
2465  0.682133
2466  0.737083
2467  0.695751

[2468 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2299  0.640761
2300  0.577829
2301  0.563925
2302  0.370408
2303  0.369190

[2304 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2291  0.304792
2292  0.310962
2293  0.319283
2294  0.341115
2295  0.336997

[2296 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2230  0.940813
2231  0.956016
2232  0.956125
2233  0.898362
2234  0.890650

[2235 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2363  0.722400
2364  0.740628
2365  0.768044
2366  0.772713
2367  0.801276

[2368 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2444  1.531093
2445  1.505661
2446  1.521358
2447  1.471706
2448  1.502684

[2449 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2407  0.430161
2408  0.414887
2409  0.384722
2410  0.345436
2411  0.410723

[2412 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2415  1.071046
2416  1.048539
2417  1.051243
2418  0.969810
2419  0.985971

[2420 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2524  0.744400
2525  0.811481
2526  0.743805
2527  0.879129
2528  0.914120

[2529 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2449  0.978517
2450  0.946190
2451  0.963607
2452  0.886241
2453  0.869087

[2454 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2535  1.222450
2536  1.193830
2537  1.193059
2538  1.168630
2539  1.151526

[2540 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2187  0.525590
2188  0.511285
2189  0.519536
2190  0.507305
2191  0.513430

[2192 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2425  0.873370
2426  0.818241
2427  0.836695
2428  1.021065
2429  1.012757

[2430 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2525  0.881604
2526  0.889214
2527  0.910840
2528  0.822543
2529  0.873419

[2530 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2158  0.806162
2159  0.787017
2160  0.798907
2161  0.846013
2162  0.842558

[2163 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2453  0.473350
2454  0.476446
2455  0.544313
2456  0.422819
2457  0.309195

[2458 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2451  0.487013
2452  0.467553
2453  0.494483
2454  0.492787
2455  0.504253

[2456 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2534  0.932112
2535  0.892618
2536  0.915497
2537  0.866991
2538  0.836909

[2539 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2305  0.538569
2306  0.561340
2307  0.569388
2308  0.527989
2309  0.538719

[2310 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2436  0.538225
2437  0.516330
2438  0.512412
2439  0.472952
2440  0.468713

[2441 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2510  1.178405
2511  1.117802
2512  1.128972
2513  1.136573
2514  1.129260

[2515 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2531  0.791031
2532  0.881151
2533  0.835550
2534  0.803473
2535  0.774755

[2536 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2409  0.474009
2410  0.469634
2411  0.484019
2412  0.458815
2413  0.455623

[2414 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2532  0.464990
2533  0.436785
2534  0.468714
2535  0.552889
2536  0.578735

[2537 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2495  0.813420
2496  0.802326
2497  0.815413
2498  0.828259
2499  0.828335

[2500 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2321  0.372709
2322  0.350074
2323  0.350606
2324  0.258539
2325  0.249174

[2326 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2391  0.976201
2392  0.960020
2393  0.938681
2394  0.911151
2395  0.892854

[2396 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2464  0.460402
2465  0.459913
2466  0.464945
2467  0.482639
2468  0.486071

[2469 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2304  1.210544
2305  1.214809
2306  1.205895
2307  1.165990
2308  1.131170

[2309 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2397  1.228175
2398  1.298032
2399  1.338535
2400  1.081696
2401  1.073361

[2402 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2351  0.753658
2352  0.817585
2353  0.850371
2354  0.720909
2355  0.708711

[2356 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2409  0.823669
2410  0.931743
2411  0.926417
2412  0.867678
2413  0.861543

[2414 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2533  1.111573
2534  1.083000
2535  1.124535
2536  1.146525
2537  1.181178

[2538 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2535  1.228861
2536  1.168755
2537  1.185924
2538  1.196902
2539  1.261157

[2540 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2393  0.902746
2394  0.909738
2395  0.981104
2396  0.961394
2397  1.006199

[2398 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2467  1.935851
2468  1.886620
2469  1.833315
2470  1.523944
2471  1.458817

[2472 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2537  0.803777
2538  0.798023
2539  0.820325
2540  0.756317
2541  0.766409

[2542 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2123  0.627516
2124  0.677986
2125  0.661053
2126  0.645045
2127  0.728696

[2128 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2539  0.483078
2540  0.465712
2541  0.477537
2542  0.456815
2543  0.468748

[2544 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2528  0.671695
2529  0.706912
2530  0.663027
2531  0.571612
2532  0.619975

[2533 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2462  0.671339
2463  0.650796
2464  0.650334
2465  0.583683
2466  0.572079

[2467 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2412  0.897031
2413  0.892925
2414  0.886651
2415  1.010147
2416  0.995320

[2417 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2507  0.805189
2508  0.739207
2509  0.656329
2510  0.711897
2511  0.595588

[2512 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2404  0.933446
2405  0.935026
2406  1.030075
2407  1.144347
2408  1.104259

[2409 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2510  0.834566
2511  0.891522
2512  0.899875
2513  0.888212
2514  0.877139

[2515 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2192  0.925852
2193  0.929369
2194  0.923274
2195  0.898904
2196  0.895727

[2197 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1355 -0.201878
1356 -0.147827
1357 -0.119495
1358 -0.209234
1359 -0.122482

[1360 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2446  1.031687
2447  1.027975
2448  1.001076
2449  0.974821
2450  1.000437

[2451 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2408  0.501490
2409  0.488648
2410  0.477390
2411  0.509556
2412  0.498624

[2413 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2481  0.574418
2482  0.564150
2483  0.588499
2484  0.546590
2485  0.551683

[2486 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2468  0.433021
2469  0.446736
2470  0.417189
2471  0.408112
2472  0.363538

[2473 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2393  0.595997
2394  0.625682
2395  0.647871
2396  0.665665
2397  0.636630

[2398 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2532  0.252914
2533  0.252577
2534  0.285644
2535  0.427242
2536  0.437429

[2537 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2530  0.949654
2531  0.940593
2532  0.937207
2533  1.101727
2534  1.081709

[2535 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2468  0.474543
2469  0.482252
2470  0.582603
2471  0.615267
2472  0.625746

[2473 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2524  0.582750
2525  0.644743
2526  0.656556
2527  0.625718
2528  0.617008

[2529 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2425  0.827685
2426  0.822059
2427  0.832257
2428  0.985147
2429  1.001109

[2430 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2332  0.867386
2333  0.834466
2334  0.887875
2335  0.999659
2336  0.985308

[2337 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2365  0.134903
2366  0.156330
2367  0.188442
2368  0.131437
2369  0.129566

[2370 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2539  1.799620
2540  1.761633
2541  1.807930
2542  2.137680
2543  2.099878

[2544 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2527  0.845978
2528  0.837124
2529  0.864788
2530  0.733477
2531  0.697983

[2532 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2539  1.223508
2540  1.241883
2541  1.269215
2542  1.270425
2543  1.224682

[2544 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2457  0.401692
2458  0.380867
2459  0.388408
2460  0.335849
2461  0.344497

[2462 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2534  0.696366
2535  0.673684
2536  0.662755
2537  0.576240
2538  0.544200

[2539 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2530  0.469946
2531  0.650021
2532  0.589186
2533  0.578822
2534  0.472497

[2535 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2535  1.068632
2536  1.062561
2537  1.122569
2538  1.202143
2539  1.226407

[2540 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2538  0.734853
2539  0.655598
2540  0.656426
2541  0.976467
2542  0.943196

[2543 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2504  1.491566
2505  1.548788
2506  1.561140
2507  1.481675
2508  1.474551

[2509 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2523  0.508610
2524  0.489429
2525  0.525330
2526  0.498829
2527  0.490843

[2528 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2405  0.760144
2406  0.723614
2407  0.721623
2408  0.621590
2409  0.610531

[2410 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2417  0.536622
2418  0.526131
2419  0.570740
2420  0.615356
2421  0.611555

[2422 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2475  1.721641
2476  1.693316
2477  1.671529
2478  1.535887
2479  1.443970

[2480 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2532  0.916164
2533  0.894511
2534  0.903689
2535  0.867175
2536  0.875532

[2537 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2277  0.642597
2278  0.612494
2279  0.602211
2280  0.568166
2281  0.554042

[2282 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2206  0.367716
2207  0.341662
2208  0.341850
2209  0.524001
2210  0.500207

[2211 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2385  1.450362
2386  1.428412
2387  1.444807
2388  1.547958
2389  1.499876

[2390 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2515  0.763470
2516  0.814996
2517  0.806202
2518  0.823583
2519  0.829836

[2520 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2503  1.019195
2504  0.952356
2505  0.984098
2506  1.029359
2507  1.044862

[2508 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2537  0.602992
2538  0.618203
2539  0.674791
2540  0.685960
2541  0.687019

[2542 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2372  0.492689
2373  0.673762
2374  0.687872
2375  1.040741
2376  1.007046

[2377 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2228  0.293813
2229  0.083452
2230  0.031807
2231  0.033079
2232  0.057062

[2233 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2476  0.756419
2477  0.750980
2478  0.783509
2479  0.682161
2480  0.675663

[2481 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2436  0.131344
2437  0.104252
2438  0.161725
2439  0.185980
2440  0.209929

[2441 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2339  0.380309
2340  0.338842
2341  0.320230
2342  0.407285
2343  0.531464

[2344 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2337  0.577658
2338  0.549635
2339  0.561325
2340  0.566865
2341  0.528942

[2342 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2536  0.633655
2537  0.657934
2538  0.649943
2539  0.628537
2540  0.576176

[2541 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2395  0.986070
2396  0.973952
2397  0.973320
2398  0.849219
2399  0.813798

[2400 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2518  0.450230
2519  0.466614
2520  0.476095
2521  0.419680
2522  0.414044

[2523 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2396  1.405507
2397  1.389834
2398  1.413973
2399  1.410158
2400  1.392414

[2401 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2522  1.326236
2523  1.264792
2524  1.267040
2525  1.208181
2526  1.176330

[2527 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2301  1.262669
2302  1.311977
2303  1.281701
2304  1.244782
2305  1.238652

[2306 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2491  0.837392
2492  0.850890
2493  0.812302
2494  0.982605
2495  0.896695

[2496 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2501  0.755637
2502  0.723445
2503  0.734238
2504  0.696353
2505  0.692031

[2506 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2439  0.857234
2440  0.800461
2441  0.788375
2442  0.750539
2443  0.733238

[2444 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1928  0.704440
1929  0.652493
1930  0.709067
1931  0.514196
1932  0.416058

[1933 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2375  0.843002
2376  0.828837
2377  0.843242
2378  0.993848
2379  0.993922

[2380 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2451  0.636361
2452  0.673649
2453  0.663778
2454  0.802074
2455  0.807895

[2456 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2349  0.881318
2350  0.898707
2351  0.887207
2352  0.848907
2353  0.844208

[2354 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2532  0.354816
2533  0.322036
2534  0.325862
2535  0.282205
2536  0.287347

[2537 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2463  1.284851
2464  1.264041
2465  1.278001
2466  1.214029
2467  1.206468

[2468 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2278  1.204505
2279  1.242212
2280  1.204661
2281  1.153201
2282  1.123646

[2283 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2228  0.939554
2229  0.958742
2230  0.962466
2231  0.955661
2232  0.926931

[2233 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2438  1.176823
2439  1.158585
2440  1.166947
2441  1.199102
2442  1.172425

[2443 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2290  1.342147
2291  1.538146
2292  1.522692
2293  1.321738
2294  1.322405

[2295 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2493  0.708917
2494  0.689144
2495  0.699259
2496  0.762670
2497  0.763696

[2498 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2308  1.134780
2309  1.154738
2310  1.177205
2311  1.120019
2312  1.045995

[2313 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2535  1.112703
2536  1.022375
2537  1.003726
2538  0.863249
2539  0.985651

[2540 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2515  0.961773
2516  0.938899
2517  0.871201
2518  0.810091
2519  0.799900

[2520 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2442  1.711543
2443  1.698026
2444  1.718891
2445  1.668547
2446  1.625353

[2447 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2467  0.360058
2468  0.365179
2469  0.367858
2470  0.398734
2471  0.406674

[2472 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2505  0.621941
2506  0.611204
2507  0.611106
2508  0.674874
2509  0.700965

[2510 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2489  0.947042
2490  0.901212
2491  0.918597
2492  0.865638
2493  0.882977

[2494 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2504  0.752184
2505  0.689446
2506  0.652751
2507  0.743262
2508  0.718715

[2509 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1895  0.942102
1896  0.817169
1897  0.818783
1898  0.588149
1899  0.568077

[1900 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2286  0.521207
2287  0.528540
2288  0.530648
2289  0.525107
2290  0.565736

[2291 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2376  1.612517
2377  1.310570
2378  1.316620
2379  1.349704
2380  1.226564

[2381 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2383  0.908391
2384  0.942754
2385  0.898139
2386  0.860580
2387  0.809950

[2388 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2459  0.733885
2460  0.737144
2461  0.799192
2462  0.796956
2463  0.813054

[2464 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2536  0.864962
2537  0.818274
2538  0.769219
2539  0.774128
2540  0.699168

[2541 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2358  1.168903
2359  1.368800
2360  1.377228
2361  1.319220
2362  1.278422

[2363 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2540  0.586143
2541  0.584205
2542  0.575180
2543  0.507918
2544  0.505313

[2545 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2116  1.013068
2117  1.063961
2118  1.201223
2119  1.023321
2120  0.745931

[2121 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2427  0.292252
2428  0.271214
2429  0.280991
2430  0.309160
2431  0.346309

[2432 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
563  0.867058
564  0.849939
565  0.869951
566  0.869194
567  0.866427

[568 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
633  0.760296
634  0.752256
635  0.753460
636  0.774596
637  0.765238

[638 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
905  0.468700
906  0.437236
907  0.447822
908  0.450131
909  0.463382

[910 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
863  1.506220
864  1.496321
865  1.544319
866  1.649454
867  1.649581

[868 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1394  0.273824
1395  0.248860
1396  0.249167
1397  0.194482
1398  0.187462

[1399 rows x 1 columns]
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
946  0.364022
947  0.378374
948  0.383796
949  0.368635
950  0.393657

[951 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
891  0.555969
892  0.559968
893  0.590406
894  0.570917
895  0.596488

[896 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
320  0.632602
321  0.623438
322  0.627082
323  0.607984
324  0.611402

[325 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
546  1.137291
547  1.212909
548  1.186636
549  1.268161
550  1.245750

[551 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
631  1.702417
632  1.680977
633  1.658415
634  1.640339
635  1.589027

[636 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
937  0.438862
938  0.429653
939  0.452993
940  0.396987
941  0.388859

[942 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
814  0.753639
815  0.756104
816  0.761225
817  0.729788
818  0.744063

[819 rows x 1 columns]
    0
0 NaN
1 NaN
2 NaN
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1276  0.978280
1277  0.959715
1278  0.992674
1279  1.025572
1280  1.040994

[1281 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1155  0.524356
1156  0.496204
1157  0.492816
1158  0.493636
1159  0.466874

[1160 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2357  0.811789
2358  0.694702
2359  0.732648
2360  0.846676
2361  0.853244

[2362 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2529  1.018051
2530  1.006282
2531  1.007410
2532  0.910843
2533  0.936212

[2534 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2419  0.537667
2420  0.594572
2421  0.595977
2422  0.773414
2423  0.778178

[2424 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2466  0.797276
2467  0.829805
2468  0.824295
2469  0.836635
2470  0.830130

[2471 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2373  1.135449
2374  1.184072
2375  1.147334
2376  1.325010
2377  1.304290

[2378 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2487  1.298089
2488  1.383680
2489  1.261377
2490  1.221532
2491  1.199449

[2492 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2381  0.765124
2382  0.733435
2383  0.710912
2384  0.677318
2385  0.662331

[2386 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
242  0.878050
243  0.862604
244  0.878436
245  0.839131
246  0.838648

[247 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2535  0.598230
2536  0.554523
2537  0.562522
2538  0.554472
2539  0.560017

[2540 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2496  0.688172
2497  0.679365
2498  0.703704
2499  0.702079
2500  0.728165

[2501 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2535  0.438744
2536  0.427607
2537  0.447747
2538  0.480145
2539  0.492821

[2540 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2408  1.110464
2409  1.050064
2410  1.062732
2411  0.995421
2412  0.989822

[2413 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2445  0.430356
2446  0.527167
2447  0.449889
2448  0.675448
2449  0.683786

[2450 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2528  0.717973
2529  0.732569
2530  0.705627
2531  0.681743
2532  0.641469

[2533 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
941  0.985153
942  0.988424
943  0.979766
944  0.903864
945  0.919994

[946 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2292  0.972734
2293  0.894542
2294  0.947984
2295  0.937287
2296  1.020929

[2297 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2409  0.644695
2410  0.629278
2411  0.645838
2412  0.620224
2413  0.615349

[2414 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2508  0.640874
2509  0.672622
2510  0.698422
2511  0.623927
2512  0.642063

[2513 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2358  0.740689
2359  0.790504
2360  0.817882
2361  0.775025
2362  0.734169

[2363 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2428  0.583217
2429  0.562509
2430  0.579062
2431  0.541570
2432  0.545553

[2433 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2371  1.632817
2372  1.830564
2373  1.902006
2374  2.267874
2375  2.229460

[2376 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2431  0.621304
2432  0.584866
2433  0.474277
2434  0.552011
2435  0.482562

[2436 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2301  0.665303
2302  0.684171
2303  0.715456
2304  0.712549
2305  0.734503

[2306 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2329  1.827006
2330  1.817893
2331  1.787892
2332  1.708298
2333  1.678466

[2334 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2475  0.660086
2476  0.642593
2477  0.649087
2478  0.635081
2479  0.625353

[2480 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2250  0.323235
2251  0.307851
2252  0.297567
2253  0.177337
2254  0.171240

[2255 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
270  0.562770
271  0.564454
272  0.578982
273  0.531358
274  0.527712

[275 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2394  1.048093
2395  1.074731
2396  1.074085
2397  1.008275
2398  1.002294

[2399 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2537  0.540164
2538  0.531189
2539  0.546676
2540  0.510111
2541  0.506406

[2542 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2541  0.669933
2542  0.676079
2543  0.534161
2544  0.564491
2545  0.711061

[2546 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2464  0.863153
2465  0.832673
2466  0.863139
2467  0.766909
2468  0.753682

[2469 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
847  0.859732
848  0.848921
849  0.865773
850  0.831088
851  0.819354

[852 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2473  0.609184
2474  0.607787
2475  0.629744
2476  0.621566
2477  0.654641

[2478 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2323  0.368641
2324  0.397064
2325  0.349469
2326  0.359453
2327  0.383445

[2328 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2530  0.906138
2531  0.892663
2532  0.871970
2533  1.033664
2534  1.008455

[2535 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2333  0.453490
2334  0.445743
2335  0.450822
2336  0.417279
2337  0.409389

[2338 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2446  0.934021
2447  0.924433
2448  0.914566
2449  0.901247
2450  0.927318

[2451 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2524  1.118802
2525  1.103609
2526  1.140764
2527  1.296489
2528  1.298005

[2529 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2371  0.305334
2372  0.292200
2373  0.293661
2374  0.253081
2375  0.276417

[2376 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2099  0.977357
2100  0.960277
2101  0.998864
2102  0.971993
2103  0.980669

[2104 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2532  0.357102
2533  0.334378
2534  0.350311
2535  0.346539
2536  0.335096

[2537 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2533  0.743679
2534  0.728413
2535  0.714153
2536  0.595002
2537  0.587333

[2538 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2532  0.638041
2533  0.616377
2534  0.626010
2535  0.565977
2536  0.576676

[2537 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2525  0.218035
2526  0.230919
2527  0.245721
2528  0.221034
2529  0.241957

[2530 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2186  0.776333
2187  0.790406
2188  0.788861
2189  0.741637
2190  0.723654

[2191 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2231  1.047727
2232  1.024888
2233  1.076360
2234  1.035384
2235  1.026596

[2236 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1955  0.924851
1956  0.897777
1957  0.830685
1958  0.897450
1959  0.905751

[1960 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1370  0.732092
1371  0.729899
1372  0.732724
1373  0.730410
1374  0.697676

[1375 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1386  0.771152
1387  0.753827
1388  0.749852
1389  0.692104
1390  0.688446

[1391 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2227  0.629516
2228  0.709099
2229  0.744809
2230  0.469651
2231  0.470348

[2232 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
628  0.635346
629  0.633848
630  0.634191
631  0.624346
632  0.646011

[633 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1030  0.892622
1031  0.876883
1032  0.860615
1033  0.785804
1034  0.813274

[1035 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1296  0.928978
1297  0.957551
1298  1.002500
1299  0.958409
1300  1.001805

[1301 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2021  0.684738
2022  0.601046
2023  0.593527
2024  0.604590
2025  0.621279

[2026 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1914  0.695230
1915  0.735702
1916  0.695445
1917  0.837912
1918  0.790951

[1919 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2147  0.576947
2148  0.584548
2149  0.601694
2150  0.608800
2151  0.605599

[2152 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
489  1.813739
490  1.806775
491  1.809809
492  1.950786
493  1.913812

[494 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
437  0.508718
438  0.482676
439  0.487522
440  0.410011
441  0.409582

[442 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1209  0.577700
1210  0.567003
1211  0.565187
1212  0.462752
1213  0.472823

[1214 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
159  0.347178
160  0.347585
161  0.352832
162  0.325307
163  0.336333

[164 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
661  1.070003
662  1.050105
663  1.036965
664  1.090121
665  1.069798

[666 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2477  0.465469
2478  0.501586
2479  0.535382
2480  0.610758
2481  0.648356

[2482 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2343  0.427038
2344  0.425705
2345  0.425651
2346  0.454956
2347  0.447490

[2348 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2522  1.102983
2523  1.085339
2524  1.124467
2525  1.113431
2526  1.113038

[2527 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2063  0.649852
2064  0.624692
2065  0.650747
2066  0.922878
2067  0.882362

[2068 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2375  1.179429
2376  1.177087
2377  1.172762
2378  1.173436
2379  1.157630

[2380 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2505  0.208294
2506  0.177727
2507  0.198278
2508  0.159513
2509  0.179203

[2510 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2527  0.811659
2528  0.810833
2529  0.808984
2530  0.795185
2531  0.791624

[2532 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
649  1.400420
650  1.388467
651  1.442828
652  1.473319
653  1.539808

[654 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2489  1.164035
2490  1.014084
2491  1.028908
2492  1.007224
2493  0.996425

[2494 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2129  0.788698
2130  0.807640
2131  0.814372
2132  0.768305
2133  0.829820

[2134 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2247  0.659584
2248  0.680320
2249  0.693746
2250  0.805414
2251  0.771869

[2252 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2534  0.645134
2535  0.613644
2536  0.627487
2537  0.676573
2538  0.714106

[2539 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2167  0.755851
2168  0.885266
2169  0.897272
2170  0.874864
2171  0.872812

[2172 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2292  0.897659
2293  0.820587
2294  0.832007
2295  0.902668
2296  0.881251

[2297 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
955  1.046897
956  1.038523
957  1.029787
958  0.977176
959  0.946238

[960 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
905  0.600201
906  0.621776
907  0.608218
908  0.490023
909  0.479904

[910 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2220  1.393734
2221  1.423513
2222  1.374209
2223  1.345834
2224  1.321813

[2225 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
496  1.355581
497  1.328619
498  1.336397
499  1.312790
500  1.314854

[501 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2527  0.551643
2528  0.503378
2529  0.516393
2530  0.503070
2531  0.506509

[2532 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1097  0.597560
1098  0.627031
1099  0.681163
1100  0.767826
1101  0.860479

[1102 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2473  0.402860
2474  0.392853
2475  0.398186
2476  0.382343
2477  0.392929

[2478 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
402  1.887473
403  1.866267
404  1.909496
405  1.869525
406  1.855914

[407 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
918  0.812564
919  0.801359
920  0.816307
921  0.771685
922  0.804232

[923 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2524  0.367015
2525  0.411044
2526  0.414676
2527  0.410398
2528  0.445031

[2529 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2340  0.845578
2341  0.834235
2342  0.807593
2343  0.817198
2344  0.856961

[2345 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2492  0.297348
2493  0.304853
2494  0.311356
2495  0.322264
2496  0.344926

[2497 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2356  0.659306
2357  0.671601
2358  0.687439
2359  0.628841
2360  0.610906

[2361 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2513  1.759793
2514  1.706512
2515  1.752788
2516  2.135245
2517  2.154273

[2518 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2526  0.706758
2527  0.668675
2528  0.700605
2529  0.880496
2530  0.933602

[2531 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2485  0.413130
2486  0.425929
2487  0.437309
2488  0.403308
2489  0.395196

[2490 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1291  1.075753
1292  1.068355
1293  1.106426
1294  1.136079
1295  1.156876

[1296 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2222  0.514193
2223  0.529623
2224  0.557706
2225  0.526130
2226  0.529216

[2227 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
786  0.584424
787  0.543608
788  0.550496
789  0.551339
790  0.558442

[791 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2203  1.395004
2204  1.363047
2205  1.316914
2206  1.304367
2207  1.281200

[2208 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1216  0.768249
1217  0.746444
1218  0.775831
1219  0.818933
1220  0.829513

[1221 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
775  1.001085
776  0.974764
777  0.994906
778  0.917901
779  0.932428

[780 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2145  0.756629
2146  0.751518
2147  0.773375
2148  0.722816
2149  0.726174

[2150 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2205  1.201146
2206  1.165427
2207  1.154165
2208  1.088577
2209  1.083391

[2210 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2139  1.016470
2140  0.964444
2141  0.922076
2142  0.989722
2143  0.962635

[2144 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1559  0.468934
1560  0.455738
1561  0.473519
1562  0.539677
1563  0.554135

[1564 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1346  0.926751
1347  0.913864
1348  0.908388
1349  0.872637
1350  0.873286

[1351 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
788  0.548379
789  0.525579
790  0.540365
791  0.578413
792  0.574563

[793 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
877  0.122770
878  0.130803
879  0.130361
880  0.121633
881  0.133823

[882 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2012  2.285782
2013  2.348859
2014  2.342840
2015  2.269735
2016  2.208612

[2017 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2201  1.064928
2202  1.043595
2203  1.060052
2204  0.914579
2205  0.930198

[2206 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
235  2.346730
236  2.362222
237  2.422174
238  2.379961
239  2.341008

[240 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1990  0.855920
1991  0.833780
1992  0.830816
1993  0.872618
1994  0.861819

[1995 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2196  0.260576
2197  0.205832
2198  0.232378
2199  0.384046
2200  0.377394

[2201 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2412  0.157448
2413  0.159350
2414  0.161328
2415  0.192461
2416  0.195179

[2417 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
344  0.606421
345  0.604940
346  0.628422
347  0.591359
348  0.598522

[349 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2178  0.955968
2179  0.931601
2180  0.946266
2181  0.896992
2182  0.895832

[2183 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2490  0.642045
2491  0.646988
2492  0.661679
2493  0.661070
2494  0.698693

[2495 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
388  0.725831
389  0.706490
390  0.729825
391  0.769059
392  0.829703

[393 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
693  0.594280
694  0.579252
695  0.591024
696  0.570662
697  0.568726

[698 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2531  0.157770
2532  0.159686
2533  0.162706
2534  0.210543
2535  0.218088

[2536 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
495  1.253320
496  1.254935
497  1.234766
498  1.146047
499  1.104711

[500 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2539  0.713109
2540  0.705949
2541  0.685828
2542  0.630663
2543  0.629013

[2544 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2042  0.835357
2043  0.829294
2044  0.851825
2045  0.870328
2046  0.910768

[2047 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1953  0.853441
1954  0.920360
1955  0.890148
1956  0.755722
1957  0.765008

[1958 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1922  1.256897
1923  1.247722
1924  1.289987
1925  1.227981
1926  1.224126

[1927 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
775  0.480481
776  0.572004
777  0.590987
778  0.518669
779  0.529538

[780 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1219  0.605456
1220  0.590838
1221  0.601570
1222  0.555963
1223  0.555634

[1224 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2424  0.655501
2425  0.629587
2426  0.632859
2427  0.605247
2428  0.589899

[2429 rows x 1 columns]

            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
844  1.278859
845  1.273019
846  1.307790
847  1.362715
848  1.375434

[849 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2339  1.032286
2340  1.029806
2341  0.995103
2342  1.179955
2343  1.156281

[2344 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1834  1.126448
1835  1.105399
1836  1.119875
1837  1.068008
1838  1.078002

[1839 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2451  0.826022
2452  0.800933
2453  0.830752
2454  0.898561
2455  0.926578

[2456 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2531  0.170801
2532  0.171563
2533  0.165773
2534  0.170864
2535  0.172052

[2536 rows x 1 columns]
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
911  0.540210
912  0.529084
913  0.564201
914  0.574645
915  0.569367

[916 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
121  0.970316
122  0.961108
123  0.967747
124  0.922917
125  0.972788

[126 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2027  1.268808
2028  1.277056
2029  1.227004
2030  1.222821
2031  1.199637

[2032 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2445  0.504316
2446  0.477148
2447  0.484601
2448  0.441091
2449  0.449268

[2450 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2134  1.644753
2135  1.623035
2136  1.651382
2137  1.687604
2138  1.659853

[2139 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2059  1.276081
2060  1.302244
2061  1.339521
2062  1.340727
2063  1.368259

[2064 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2241  0.484819
2242  0.478337
2243  0.561818
2244  0.575748
2245  0.672223

[2246 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2189  0.522300
2190  0.525229
2191  0.546526
2192  0.530182
2193  0.529584

[2194 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2140  0.864481
2141  0.848223
2142  0.860866
2143  0.897616
2144  0.869971

[2145 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
420  0.410243
421  0.406888
422  0.413529
423  0.424965
424  0.439456

[425 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1397  0.170504
1398  0.176976
1399  0.212801
1400  0.243793
1401  0.330914

[1402 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2525  0.551978
2526  0.528070
2527  0.510971
2528  0.455781
2529  0.518781

[2530 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
935  0.483423
936  0.532017
937  0.557764
938  0.431147
939  0.463305

[940 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
345  0.603265
346  0.591541
347  0.601380
348  0.610681
349  0.612288

[350 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2044  1.360292
2045  1.352197
2046  1.304460
2047  1.172099
2048  1.224989

[2049 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2425  0.703542
2426  0.688007
2427  0.691266
2428  0.678090
2429  0.698903

[2430 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2541  0.735829
2542  0.711184
2543  0.727467
2544  0.721853
2545  0.774991

[2546 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
456  0.256023
457  0.234351
458  0.193774
459  0.290491
460  0.254102

[461 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2515  0.294266
2516  0.343082
2517  0.335460
2518  0.498881
2519  0.509429

[2520 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1787  0.657597
1788  0.628974
1789  0.641320
1790  0.609663
1791  0.618931

[1792 rows x 1 columns]
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
36 NaN
37 NaN
38 NaN
39 NaN
40 NaN
41 NaN
42 NaN
43 NaN
44 NaN
45 NaN
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
984  0.629769
985  0.612448
986  0.632269
987  0.676816
988  0.688564

[989 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
342  0.506044
343  0.490801
344  0.487747
345  0.386863
346  0.382159

[347 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2267  1.393492
2268  1.368218
2269  1.355135
2270  1.325244
2271  1.333909

[2272 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2465  0.616281
2466  0.594312
2467  0.614781
2468  0.633061
2469  0.658271

[2470 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
583  0.851227
584  0.846755
585  0.823119
586  0.729828
587  0.718907

[588 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2539  0.670942
2540  0.676934
2541  0.717722
2542  0.700687
2543  0.746096

[2544 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2096  0.740079
2097  0.722924
2098  0.756728
2099  0.832030
2100  0.870825

[2101 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2140  0.781288
2141  0.723912
2142  0.654632
2143  0.655052
2144  0.683413

[2145 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
129  0.243564
130  0.286539
131  0.293722
132  0.297190
133  0.306081

[134 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2540  0.558679
2541  0.513346
2542  0.514468
2543  0.543839
2544  0.554214

[2545 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2537  0.538825
2538  0.521948
2539  0.551539
2540  0.591267
2541  0.627305

[2542 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1996  0.795300
1997  0.768456
1998  0.810224
1999  0.835903
2000  0.861853

[2001 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2124  0.642979
2125  0.627721
2126  0.641027
2127  0.747015
2128  0.770959

[2129 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2504  0.876016
2505  0.874185
2506  0.871531
2507  0.826720
2508  0.818272

[2509 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2499  0.938587
2500  0.929745
2501  0.983842
2502  1.019290
2503  1.043376

[2504 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1274  1.673337
1275  1.620618
1276  1.622434
1277  1.623681
1278  1.557304

[1279 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
80  2.399700
81  2.385270
82  2.440418
83  2.529197
84  2.492005

[85 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
240  1.696775
241  1.686082
242  1.656699
243  1.565081
244  1.518256

[245 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2518  0.614953
2519  0.625048
2520  0.642448
2521  0.720441
2522  0.742916

[2523 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2090  1.615974
2091  1.506716
2092  1.461139
2093  1.379621
2094  1.337016

[2095 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2201  1.054942
2202  1.064430
2203  1.067100
2204  1.021548
2205  1.003450

[2206 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2381  0.618992
2382  0.627673
2383  0.627653
2384  0.687246
2385  0.699648

[2386 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2273  0.603440
2274  0.572580
2275  0.583424
2276  0.613317
2277  0.584555

[2278 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2449  0.441352
2450  0.430681
2451  0.460236
2452  0.527311
2453  0.548718

[2454 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2287  0.298210
2288  0.461064
2289  0.475990
2290  0.172438
2291  0.009192

[2292 rows x 1 columns]

     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2524  1.032581
2525  1.010341
2526  1.027328
2527  1.185961
2528  1.295498

[2529 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1963  2.167675
1964  2.069791
1965  2.089765
1966  1.976311
1967  1.961646

[1968 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2119  0.578985
2120  0.652820
2121  0.691464
2122  0.671036
2123  0.627612

[2124 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2229  1.111003
2230  1.104412
2231  1.101101
2232  1.024975
2233  0.999590

[2234 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2015  0.842037
2016  0.812791
2017  0.844997
2018  0.895391
2019  0.935547

[2020 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2505  0.359397
2506  0.346843
2507  0.362094
2508  0.325965
2509  0.363700

[2510 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2540  2.013938
2541  1.963664
2542  1.989807
2543  1.904626
2544  1.874196

[2545 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
942  0.477393
943  0.463891
944  0.464838
945  0.349833
946  0.350577

[947 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
103  0.681687
104  0.679689
105  0.686535
106  0.650087
107  0.658584

[108 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2373  0.257806
2374  0.274682
2375  0.276606
2376  0.298487
2377  0.416974

[2378 rows x 1 columns]
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
588  1.152029
589  1.130006
590  1.113410
591  1.015740
592  1.003765

[593 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
579  0.303517
580  0.317396
581  0.323662
582  0.312540
583  0.331981

[584 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2539  0.670923
2540  0.660337
2541  0.653805
2542  0.608931
2543  0.625490

[2544 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
833  1.293301
834  1.282180
835  1.289116
836  1.210030
837  1.207634

[838 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
356  0.584810
357  0.578621
358  0.588183
359  0.549852
360  0.557226

[361 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
330  1.134860
331  1.089837
332  0.955288
333  0.751937
334  0.751603

[335 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2442  0.654283
2443  0.641941
2444  0.667312
2445  0.702686
2446  0.710759

[2447 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
467  1.307560
468  1.249745
469  1.263280
470  1.122779
471  1.097534

[472 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2420  0.630117
2421  0.673139
2422  0.688253
2423  0.946325
2424  0.930421

[2425 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2390  0.932898
2391  0.932877
2392  0.927252
2393  0.902797
2394  0.867644

[2395 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
730  1.526738
731  1.512269
732  1.554125
733  1.598712
734  1.742511

[735 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2310  0.498975
2311  0.517516
2312  0.514443
2313  0.506643
2314  0.501749

[2315 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
830  1.294785
831  1.297850
832  1.319641
833  1.374463
834  1.418714

[835 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
881  1.046956
882  0.998203
883  0.975403
884  1.179711
885  1.149596

[886 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2115  0.748142
2116  0.731721
2117  0.730632
2118  0.729751
2119  0.727418

[2120 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2478  1.366188
2479  1.328718
2480  1.187753
2481  1.185715
2482  1.289423

[2483 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2300  0.268310
2301  0.238591
2302  0.234877
2303  0.382044
2304  0.378306

[2305 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2537  0.578299
2538  0.572261
2539  0.596070
2540  0.588000
2541  0.619866

[2542 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2505  0.891570
2506  0.884373
2507  0.885193
2508  0.822224
2509  0.876733

[2510 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
945  0.967393
946  0.948824
947  0.961650
948  0.905733
949  0.867569

[950 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2036  0.934679
2037  0.925095
2038  0.955706
2039  1.084877
2040  1.094863

[2041 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2115  1.479136
2116  1.456122
2117  1.348850
2118  1.232093
2119  1.247903

[2120 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
139  0.221349
140  0.220145
141  0.226796
142  0.241174
143  0.255118

[144 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2445  0.757930
2446  0.745000
2447  0.770141
2448  0.755311
2449  0.768224

[2450 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2389  0.997181
2390  0.991311
2391  0.998456
2392  1.023575
2393  1.027984

[2394 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2026  0.653402
2027  0.654717
2028  0.666397
2029  0.625564
2030  0.621408

[2031 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2017  0.939401
2018  0.923710
2019  0.937929
2020  0.906983
2021  0.890773

[2022 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2291  0.392751
2292  0.458381
2293  0.457637
2294  0.599506
2295  0.585954

[2296 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2532  0.259083
2533  0.268176
2534  0.280344
2535  0.301568
2536  0.311778

[2537 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
690  1.231932
691  1.227831
692  1.255713
693  1.225980
694  1.234539

[695 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
758  0.761587
759  0.883433
760  0.778245
761  0.951824
762  0.930795

[763 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2540  0.923938
2541  0.910882
2542  0.889203
2543  0.841355
2544  0.844799

[2545 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1946  0.950574
1947  0.974339
1948  0.964169
1949  0.825009
1950  0.847471

[1951 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
950  1.034494
951  1.009026
952  1.039298
953  1.068326
954  1.040560

[955 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1207  0.719047
1208  0.698114
1209  0.709048
1210  0.588925
1211  0.670624

[1212 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1307  0.870163
1308  0.757564
1309  0.775535
1310  0.771163
1311  0.767071

[1312 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
352  0.578271
353  0.561993
354  0.571707
355  0.553014
356  0.548624

[357 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1227  0.663252
1228  0.663745
1229  0.670790
1230  0.637090
1231  0.653223

[1232 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2531  0.180121
2532  0.182801
2533  0.178814
2534  0.191526
2535  0.199029

[2536 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2253  0.355332
2254  0.333941
2255  0.336136
2256  0.397917
2257  0.402033

[2258 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
493  1.872184
494  1.885409
495  1.933398
496  2.067175
497  2.053641

[498 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2519  0.536744
2520  0.519994
2521  0.531428
2522  0.522705
2523  0.529347

[2524 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2238  0.745065
2239  0.703575
2240  0.716609
2241  0.721678
2242  0.745752

[2243 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2019  1.064280
2020  1.046834
2021  1.050485
2022  1.097548
2023  1.078495

[2024 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
936  0.474157
937  0.486673
938  0.488086
939  0.477101
940  0.494277

[941 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2526  0.299909
2527  0.311363
2528  0.264425
2529  0.219072
2530  0.269600

[2531 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2444  1.516424
2445  1.514791
2446  1.517050
2447  1.438537
2448  1.429027

[2449 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1984  1.801422
1985  1.822184
1986  1.855070
1987  1.835618
1988  1.921005

[1989 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1967  0.618999
1968  0.704225
1969  0.756338
1970  0.701065
1971  0.698297

[1972 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1945  1.376059
1946  1.311246
1947  1.334389
1948  1.308910
1949  1.248829

[1950 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1811  2.351037
1812  2.265345
1813  2.329801
1814  2.138139
1815  2.085975

[1816 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1552  1.689999
1553  1.635396
1554  1.587511
1555  1.738016
1556  1.720235

[1557 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1393  1.072600
1394  1.004253
1395  1.032389
1396  0.988214
1397  0.985163

[1398 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
916  0.604763
917  0.586947
918  0.581240
919  0.598874
920  0.595846

[921 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1842  0.861098
1843  0.846895
1844  0.871070
1845  0.852980
1846  0.872977

[1847 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1366  1.091209
1367  1.062815
1368  1.063286
1369  0.976557
1370  0.958910

[1371 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1104  1.501462
1105  1.460252
1106  1.467634
1107  1.320858
1108  1.289751

[1109 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1273  1.261975
1274  1.247588
1275  1.291458
1276  1.061076
1277  1.064895

[1278 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1278  1.296453
1279  1.281028
1280  1.279770
1281  1.232257
1282  1.215000

[1283 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
518  0.073440
519  0.090910
520  0.044777
521  0.214391
522  0.221236

[523 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1285  1.090312
1286  1.032989
1287  1.022140
1288  0.882723
1289  0.850476

[1290 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
789  0.860210
790  0.925140
791  0.916543
792  0.855001
793  0.803964

[794 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1265  1.031251
1266  1.040002
1267  1.042816
1268  1.129408
1269  1.118571

[1270 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1329  0.509276
1330  0.601662
1331  0.620634
1332  0.989399
1333  1.042130

[1334 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1355  1.928748
1356  1.927341
1357  1.993338
1358  1.908643
1359  1.874138

[1360 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1280  1.181360
1281  1.266412
1282  1.206039
1283  1.359362
1284  1.316823

[1285 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1179  1.175293
1180  1.152202
1181  1.011839
1182  1.009084
1183  0.965256

[1184 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1241  0.521030
1242  0.598718
1243  0.577036
1244  0.612464
1245  0.605251

[1246 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1237  1.220257
1238  1.181855
1239  1.132075
1240  1.005075
1241  0.992892

[1242 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1234  1.053281
1235  1.024320
1236  1.038911
1237  1.056830
1238  1.039644

[1239 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1234  1.551664
1235  1.548225
1236  1.581278
1237  1.751920
1238  1.775460

[1239 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1047  0.672357
1048  0.699114
1049  0.578946
1050  0.543601
1051  0.597924

[1052 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1010  0.713966
1011  0.788983
1012  0.834994
1013  0.746920
1014  0.693897

[1015 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
972  0.726279
973  0.722776
974  0.737914
975  0.697427
976  0.679652

[977 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1269  1.331846
1270  1.306437
1271  1.314806
1272  1.346230
1273  1.318345

[1274 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
931 -0.082779
932 -0.127367
933 -0.070247
934 -0.207008
935 -0.235137

[936 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
690  0.953777
691  0.924455
692  0.914303
693  0.967893
694  0.932398

[695 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
788  0.805089
789  0.774502
790  0.858075
791  0.748076
792  0.747574

[793 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
842  1.757012
843  1.827366
844  1.813112
845  1.978715
846  1.999613

[847 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
860  1.076028
861  1.061026
862  1.059644
863  0.997142
864  0.978303

[865 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
831  1.083150
832  1.079765
833  1.078507
834  1.082812
835  1.049233

[836 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
834  0.304428
835  0.343694
836  0.294267
837  0.398436
838  0.417547

[839 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
769  1.208268
770  1.236369
771  1.218132
772  1.277656
773  1.221641

[774 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
821  1.334568
822  1.352871
823  1.347542
824  1.397267
825  1.369637

[826 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
787  1.214181
788  1.200856
789  1.235426
790  1.306678
791  1.276303

[792 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
746  1.772608
747  1.869543
748  1.806836
749  1.727687
750  1.694674

[751 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
729  0.598943
730  0.605283
731  0.608906
732  0.526514
733  0.553537

[734 rows x 1 columns]

            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
512  1.072205
513  1.035311
514  1.002796
515  0.726756
516  0.632284

[517 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
778  1.424887
779  1.309599
780  1.288474
781  1.185273
782  1.179294

[783 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
124  0.538475
125  0.514568
126  0.522147
127  0.459978
128  0.448576

[129 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
667  0.365679
668  0.341710
669  0.366669
670  0.272113
671  0.257206

[672 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
590  0.870777
591  0.853387
592  0.896250
593  0.888067
594  0.864754

[595 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
848  0.803782
849  0.785616
850  0.821858
851  0.905593
852  1.049071

[853 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
562  1.307328
563  1.345441
564  1.344431
565  1.467012
566  1.453605

[567 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
882  0.158613
883  0.145782
884  0.115077
885  0.201212
886  0.157255

[887 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
706  0.887758
707  0.887025
708  0.870993
709  0.942282
710  0.938868

[711 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1152  1.549213
1153  1.521245
1154  1.517803
1155  1.428925
1156  1.500616

[1157 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
914  1.714822
915  1.730827
916  1.698609
917  1.689642
918  1.623369

[919 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
290  2.150918
291  2.134786
292  2.134961
293  1.990647
294  2.029025

[295 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
961  1.057601
962  1.065597
963  0.991030
964  0.793996
965  0.943732

[966 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
635  0.709815
636  0.697393
637  0.718413
638  0.711630
639  0.664063

[640 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1835  0.556575
1836  0.569923
1837  0.566311
1838  0.564671
1839  0.557997

[1840 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
782  1.902916
783  1.863283
784  1.856095
785  1.700703
786  1.596681

[787 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
650  0.995956
651  0.957407
652  0.935401
653  0.891529
654  0.867793

[655 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
597  0.863083
598  0.844624
599  0.858465
600  0.842474
601  0.845747

[602 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
774  1.131813
775  1.122550
776  1.137306
777  1.084347
778  1.069201

[779 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
636  2.309839
637  2.299624
638  2.287893
639  2.254995
640  2.176390

[641 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1193  0.806545
1194  0.784991
1195  0.771125
1196  0.752245
1197  0.777503

[1198 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
760  0.576199
761  0.585303
762  0.574122
763  0.576473
764  0.567842

[765 rows x 1 columns]
    0
0 NaN
1 NaN
2 NaN
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1357  0.955849
1358  0.888160
1359  0.954736
1360  0.822345
1361  0.784317

[1362 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
827  0.753133
828  0.742295
829  0.785677
830  0.736930
831  0.728894

[832 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
869  1.110705
870  1.082931
871  1.127830
872  1.226002
873  1.206014

[874 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
195  1.847955
196  1.826191
197  1.878827
198  1.913442
199  1.880841

[200 rows x 1 columns]
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
36 NaN
37 NaN
38 NaN
39 NaN
40 NaN
41 NaN
42 NaN
43 NaN
44 NaN
45 NaN
46 NaN
47 NaN
48 NaN
49 NaN
50 NaN
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
771  0.729619
772  0.732681
773  0.738738
774  0.817448
775  0.808482

[776 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
854  0.774624
855  0.759653
856  0.755214
857  0.692808
858  0.695159

[859 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1420  0.789647
1421  0.788621
1422  0.791854
1423  0.696243
1424  0.692549

[1425 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1395  0.745920
1396  0.736725
1397  0.732250
1398  0.718710
1399  0.713446

[1400 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1006  1.029727
1007  1.002814
1008  1.054934
1009  1.005260
1010  1.063014

[1011 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
657  1.042848
658  1.027527
659  1.052266
660  0.749101
661  0.791797

[662 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
476  2.162669
477  2.130081
478  2.092394
479  1.977935
480  1.894513

[481 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
667  1.453131
668  1.431903
669  1.468648
670  1.593298
671  1.519859

[672 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1100  0.753551
1101  0.800511
1102  0.776192
1103  0.739437
1104  0.704907

[1105 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
114  1.820779
115  1.840386
116  1.705394
117  1.478439
118  1.394585

[119 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
656  1.098382
657  1.092865
658  1.115553
659  1.093354
660  1.064367

[661 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1244  1.412690
1245  1.426789
1246  1.463190
1247  1.724939
1248  1.699826

[1249 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
760  1.027022
761  1.017079
762  1.033630
763  1.044896
764  1.038533

[765 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
210  1.360301
211  1.350759
212  1.329968
213  1.255228
214  1.266955

[215 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1212  1.012348
1213  0.990681
1214  0.971421
1215  0.643765
1216  0.569542

[1217 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1201  0.940312
1202  0.933422
1203  0.940553
1204  0.897160
1205  0.905659

[1206 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1268  1.518467
1269  1.582679
1270  1.595982
1271  1.751576
1272  1.715318

[1273 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
350  0.626969
351  0.645741
352  0.646611
353  0.611433
354  0.607359

[355 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1902  0.167391
1903  0.182114
1904  0.241698
1905  0.487378
1906  0.547555

[1907 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1376  0.946366
1377  0.899138
1378  0.911272
1379  0.786129
1380  0.802987

[1381 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
686  1.221200
687  1.256523
688  1.170280
689  1.133600
690  1.040019

[691 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1848  0.807566
1849  0.811963
1850  0.847329
1851  0.971087
1852  0.972561

[1853 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
691  1.811260
692  1.808027
693  1.786043
694  1.660775
695  1.655187

[696 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
895  1.310710
896  1.289497
897  1.302079
898  1.253995
899  1.331539

[900 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
795  1.734800
796  1.726617
797  1.762450
798  1.706435
799  1.733365

[800 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
663  1.197804
664  1.217405
665  1.227377
666  1.189111
667  1.182675

[668 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
805  2.035734
806  2.078092
807  2.065648
808  2.006278
809  1.928294

[810 rows x 1 columns]

            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
773  0.728227
774  0.716804
775  0.694016
776  0.579504
777  0.553888

[778 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
571  0.547052
572  0.568169
573  0.565554
574  0.610058
575  0.692221

[576 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
664  0.439849
665  0.284050
666  0.256931
667  0.370862
668  0.185198

[669 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1244  1.861326
1245  1.861605
1246  1.801418
1247  1.615551
1248  1.589401

[1249 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
938  0.906778
939  0.892306
940  0.920198
941  0.851726
942  0.824250

[943 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
899  1.595811
900  1.549935
901  1.575647
902  1.603492
903  1.593519

[904 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
597  0.617234
598  0.602924
599  0.590629
600  0.555145
601  0.529525

[602 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
833  0.873556
834  0.855521
835  0.843761
836  0.817354
837  0.804989

[838 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1354  0.942125
1355  1.010665
1356  1.005958
1357  1.106213
1358  1.138313

[1359 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1893  1.078223
1894  1.088543
1895  1.079618
1896  1.078968
1897  1.078286

[1898 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1431  1.161038
1432  1.142936
1433  1.202961
1434  1.160646
1435  1.130031

[1436 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1294  1.000604
1295  0.971577
1296  0.958461
1297  0.910419
1298  0.917955

[1299 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
819  0.622691
820  0.621428
821  0.662861
822  0.583365
823  0.556729

[824 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
789  1.121349
790  1.133917
791  1.137950
792  1.152174
793  1.095874

[794 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
796  2.081537
797  2.054539
798  2.048260
799  2.040871
800  1.961207

[801 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
759  0.988607
760  0.965950
761  0.991666
762  0.947875
763  0.985570

[764 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
687  1.004006
688  0.954220
689  0.950164
690  0.894737
691  0.833844

[692 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
673  1.208904
674  1.197770
675  1.211282
676  1.228103
677  1.228933

[678 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
358  1.785994
359  1.817807
360  1.774225
361  1.547632
362  1.510000

[363 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
844  2.361193
845  2.343694
846  2.337711
847  2.302259
848  2.263171

[849 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
379  0.895904
380  0.922311
381  0.920388
382  0.807197
383  0.786555

[384 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1325  0.534356
1326  0.526942
1327  0.515664
1328  0.443257
1329  0.394952

[1330 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
914  2.307808
915  2.242939
916  2.200162
917  2.026332
918  2.160943

[919 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
440  0.969548
441  0.935632
442  1.011807
443  1.165678
444  1.156677

[445 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
94  0.549659
95  0.617928
96  0.650029
97  0.625908
98  0.611900

[99 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
748  0.860395
749  0.909082
750  0.940249
751  0.915471
752  0.920593

[753 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
754  1.767963
755  1.768640
756  1.744636
757  1.768462
758  1.731187

[759 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1236  0.743491
1237  0.764752
1238  0.792345
1239  0.781238
1240  0.927473

[1241 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1279  0.738186
1280  0.758096
1281  0.773775
1282  0.735674
1283  0.734793

[1284 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
747  1.920356
748  2.032672
749  2.033789
750  2.058162
751  2.029585

[752 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
883  1.523618
884  1.547047
885  1.559513
886  1.606832
887  1.574067

[888 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
821  1.645489
822  1.603487
823  1.655426
824  1.700366
825  1.733756

[826 rows x 1 columns]
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
36 NaN
37 NaN
38 NaN
39 NaN
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
542  0.771603
543  0.822653
544  0.909851
545  0.929579
546  0.901972

[547 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
246  0.500525
247  0.499366
248  0.509483
249  0.473760
250  0.456465

[251 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
847  0.525890
848  0.480361
849  0.471470
850  0.475293
851  0.407492

[852 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
389  1.533942
390  1.584194
391  1.564402
392  1.472091
393  1.463187

[394 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
62  0.896585
63  0.779854
64  0.729662
65  0.529318
66  0.523919

[67 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1247 -0.080919
1248 -0.018218
1249 -0.076064
1250 -0.158096
1251 -0.150058

[1252 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1204 -0.026107
1205 -0.045313
1206 -0.069949
1207  0.045149
1208  0.077693

[1209 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
776  1.006356
777  0.990285
778  0.994421
779  0.933163
780  0.935354

[781 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
735  1.467782
736  1.403697
737  1.464723
738  1.596585
739  1.586292

[740 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1199  0.932213
1200  0.922420
1201  0.943338
1202  0.926716
1203  0.923244

[1204 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
841  1.388439
842  1.365441
843  1.343596
844  1.426986
845  1.390933

[846 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
762  0.990412
763  1.046836
764  1.105839
765  1.172116
766  1.050599

[767 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
773  2.047696
774  2.052610
775  2.016427
776  1.869060
777  1.811232

[778 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
705  0.362694
706  0.399351
707  0.411454
708  0.519865
709  0.388862

[710 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
228  2.122682
229  2.098681
230  2.097093
231  2.121482
232  2.042870

[233 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
743  1.404288
744  1.420898
745  1.432479
746  1.353471
747  1.361252

[748 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
844  1.410995
845  1.413587
846  1.432782
847  1.655277
848  1.564395

[849 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
225  1.485711
226  1.491809
227  1.491861
228  1.458711
229  1.444730

[230 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
892  1.149090
893  1.148803
894  1.147545
895  1.265208
896  1.246601

[897 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
519  1.465984
520  1.485311
521  1.440669
522  1.226813
523  1.160663

[524 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
645  1.097864
646  1.104774
647  1.075403
648  0.974895
649  0.915707

[650 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
839  1.233118
840  1.212974
841  1.198270
842  1.143181
843  1.184564

[844 rows x 1 columns]

            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
271  1.215855
272  1.199706
273  1.143814
274  1.123866
275  1.075103

[276 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1155  0.061843
1156  0.030015
1157 -0.090467
1158  0.043875
1159  0.130588

[1160 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
756  0.945172
757  0.934975
758  0.941345
759  0.930053
760  0.916747

[761 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
675  0.937704
676  0.899999
677  0.900331
678  0.853767
679  0.816441

[680 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
635  1.371114
636  1.296190
637  1.307231
638  1.446972
639  1.470071

[640 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
219  0.713649
220  0.660695
221  0.684264
222  0.661287
223  0.657370

[224 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
599  2.956153
600  2.951064
601  2.916031
602  2.765513
603  2.729993

[604 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
720  0.617700
721  0.577718
722  0.577001
723  0.559506
724  0.524091

[725 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1554  0.666764
1555  0.798171
1556  0.801853
1557  0.752698
1558  0.735506

[1559 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
644  1.235987
645  1.238254
646  1.282759
647  1.216018
648  1.215986

[649 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
96   1.880855
97   1.973273
98   1.946601
99   1.885014
100  1.831251

[101 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
431  1.121851
432  1.086257
433  1.073477
434  1.161267
435  1.174282

[436 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
848  0.657003
849  0.613035
850  0.637024
851  0.633824
852  0.576413

[853 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
968  0.809019
969  0.847766
970  0.816061
971  0.856338
972  0.848436

[973 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1214  0.817951
1215  0.796249
1216  0.807571
1217  0.842023
1218  0.842694

[1219 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
535  0.466977
536  0.485259
537  0.360281
538  0.416421
539  0.438279

[540 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
787  0.859360
788  0.820011
789  0.839939
790  0.739564
791  0.714088

[792 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
720  1.768450
721  1.717007
722  1.740399
723  1.865716
724  1.850192

[725 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1371  1.235989
1372  1.382677
1373  1.457823
1374  1.391806
1375  1.390111

[1376 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1495  2.015875
1496  1.999216
1497  1.991951
1498  2.076393
1499  2.025258

[1500 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1228  0.820230
1229  0.966791
1230  0.901683
1231  0.924756
1232  0.858328

[1233 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1239  0.623834
1240  0.603500
1241  0.611969
1242  0.634702
1243  0.647875

[1244 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
901  2.092564
902  2.085236
903  2.130029
904  2.058554
905  2.033293

[906 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1178  0.784632
1179  0.775011
1180  0.746359
1181  0.759488
1182  0.785879

[1183 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
735  0.203921
736  0.255081
737  0.263112
738  0.210480
739  0.217199

[740 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
289  0.884530
290  0.997952
291  0.962046
292  0.940662
293  0.949028

[294 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1091  1.054680
1092  1.034600
1093  0.933234
1094  0.851386
1095  1.005909

[1096 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
867  0.890758
868  0.937229
869  0.950263
870  0.772287
871  0.787348

[872 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
767  0.865568
768  0.827361
769  0.853970
770  0.859869
771  0.833310

[772 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
671  1.278308
672  1.337495
673  1.340022
674  1.234013
675  1.221153

[676 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
937  1.585780
938  1.540789
939  1.510203
940  1.669422
941  1.639535

[942 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
868  0.541121
869  0.548303
870  0.557885
871  0.536835
872  0.550921

[873 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
735  0.481162
736  0.470676
737  0.483218
738  0.451756
739  0.457640

[740 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
265  1.631034
266  1.623864
267  1.633102
268  1.651321
269  1.634443

[270 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1454  1.296308
1455  1.283240
1456  1.239693
1457  1.184293
1458  1.144992

[1459 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
601  1.046287
602  1.039838
603  1.119441
604  1.101721
605  1.040369

[606 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
807  1.464281
808  1.411443
809  1.445096
810  1.393728
811  1.439846

[812 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
723  0.435390
724  0.393806
725  0.408232
726  0.577525
727  0.566125

[728 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
346  0.147860
347  0.142472
348  0.143856
349  0.076922
350  0.089781

[351 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1943  0.818977
1944  0.756926
1945  0.763768
1946  0.752998
1947  0.760723

[1948 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
734  0.416011
735  0.363938
736  0.368544
737  0.357715
738  0.323802

[739 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
859  0.754547
860  0.865381
861  0.831616
862  0.843597
863  0.829080

[864 rows x 1 columns]

            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
832  1.112555
833  1.061511
834  0.977655
835  0.918653
836  0.951484

[837 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1267  1.394225
1268  1.383973
1269  1.395030
1270  1.248523
1271  1.208829

[1272 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
996   1.143569
997   1.160313
998   1.124881
999   1.051247
1000  1.045561

[1001 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
774  1.047843
775  1.106740
776  1.099725
777  1.037633
778  1.000677

[779 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
524  1.261232
525  1.242007
526  1.243757
527  1.243544
528  1.220500

[529 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
337  0.636891
338  0.645296
339  0.665639
340  0.657505
341  0.639198

[342 rows x 1 columns]
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
36 NaN
37 NaN
38 NaN
39 NaN
40 NaN
41 NaN
42 NaN
43 NaN
44 NaN
45 NaN
46 NaN
47 NaN
48 NaN
49 NaN
50 NaN
51 NaN
52 NaN
53 NaN
54 NaN
55 NaN
56 NaN
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1247  0.804475
1248  0.787123
1249  0.786205
1250  0.707965
1251  0.684584

[1252 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
584 -0.238555
585 -0.198819
586 -0.196739
587 -0.105198
588 -0.166661

[589 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
704  0.834952
705  0.812102
706  0.829192
707  0.976319
708  0.989722

[709 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
828  1.284612
829  1.304143
830  1.263633
831  1.123615
832  1.090248

[833 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
681  1.017505
682  0.983376
683  0.988794
684  0.996529
685  0.995636

[686 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
825  1.378945
826  1.368463
827  1.356814
828  1.271145
829  1.232884

[830 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
664  0.226960
665  0.258790
666  0.244216
667  0.408455
668  0.428028

[669 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
630  0.702731
631  0.715302
632  0.688314
633  0.684327
634  0.660445

[635 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1968  1.708607
1969  1.693687
1970  1.709846
1971  1.664275
1972  1.629092

[1973 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
661  0.629941
662  0.660771
663  0.648914
664  0.735901
665  0.712053

[666 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1339  0.501891
1340  0.484521
1341  0.529852
1342  0.482090
1343  0.516044

[1344 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1453  0.726936
1454  0.728224
1455  0.704314
1456  0.682075
1457  0.782308

[1458 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1064  0.549568
1065  0.483353
1066  0.508172
1067  0.508319
1068  0.495189

[1069 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
662  1.030237
663  1.094049
664  1.096622
665  1.086667
666  0.962600

[667 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
298  1.038372
299  1.033287
300  1.018287
301  0.955167
302  0.928412

[303 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
732  1.291786
733  1.211670
734  1.203750
735  1.108158
736  1.080921

[737 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
751  1.768830
752  1.773031
753  1.740710
754  1.801207
755  1.747066

[756 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
785  0.796470
786  0.744928
787  0.792916
788  0.829928
789  0.884100

[790 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
586  1.267952
587  1.285493
588  1.289971
589  1.264977
590  1.246000

[591 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
715  0.583435
716  0.652641
717  0.630837
718  0.524746
719  0.511474

[720 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
790 -0.221566
791 -0.233372
792 -0.231497
793 -0.298762
794 -0.296622

[795 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
855  1.156128
856  1.168773
857  1.139402
858  1.127775
859  1.055577

[860 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
140  1.283726
141  1.217162
142  1.197941
143  1.113909
144  1.089221

[145 rows x 1 columns]
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
36 NaN
37 NaN
38 NaN
39 NaN
40 NaN
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
855  0.582932
856  0.648928
857  0.622907
858  0.711082
859  0.721783

[860 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
653  2.609355
654  2.575732
655  2.548550
656  2.405934
657  2.312183

[658 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
984  0.789768
985  0.763347
986  0.764876
987  0.728130
988  0.708495

[989 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1700  0.628425
1701  0.514439
1702  0.512666
1703  0.515449
1704  0.512679

[1705 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
852  1.382614
853  1.349763
854  1.338200
855  1.369524
856  1.381583

[857 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
903  1.395547
904  1.445800
905  1.437829
906  1.465432
907  1.438129

[908 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
780  0.955951
781  1.036918
782  0.988273
783  1.222747
784  1.365670

[785 rows x 1 columns]
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
36 NaN
37 NaN
38 NaN
39 NaN
40 NaN
41 NaN
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
843  1.158094
844  1.196517
845  1.177281
846  1.169960
847  1.155791

[848 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1353  0.728468
1354  0.702795
1355  0.709650
1356  0.732066
1357  0.780857

[1358 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
698  1.033469
699  1.029472
700  0.984373
701  1.304405
702  1.306583

[703 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
650  0.893510
651  0.849584
652  0.834341
653  0.897448
654  0.891243

[655 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
599  0.687179
600  0.650651
601  0.613212
602  0.614457
603  0.583003

[604 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
505  1.696567
506  1.703157
507  1.752798
508  1.598671
509  1.629443

[510 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
757  0.465745
758  0.458317
759  0.470417
760  0.540735
761  0.536110

[762 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
150  1.436230
151  1.440214
152  1.323473
153  1.115651
154  1.057205

[155 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
743  1.867705
744  1.872934
745  1.825662
746  1.794533
747  1.732668

[748 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
654  0.485365
655  0.493262
656  0.531941
657  0.546483
658  0.598386

[659 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
680  1.234134
681  1.204099
682  1.253105
683  1.249936
684  1.200171

[685 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
594  1.863579
595  1.842609
596  1.892381
597  2.127591
598  2.134166

[599 rows x 1 columns]

            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
766  1.572315
767  1.564455
768  1.565665
769  1.532464
770  1.509709

[771 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
578  1.378857
579  1.354387
580  1.410499
581  1.341391
582  1.283109

[583 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
640  0.502266
641  0.492263
642  0.503941
643  0.626342
644  0.645883

[645 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1006  1.328884
1007  1.291868
1008  1.295912
1009  1.202687
1010  1.142925

[1011 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
933  0.657329
934  0.641143
935  0.686199
936  0.712155
937  0.655419

[938 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
577  1.742466
578  1.776440
579  1.729851
580  1.522900
581  1.474513

[582 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
796  0.774324
797  0.805160
798  0.782237
799  0.690712
800  0.683087

[801 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1220  0.881928
1221  0.849680
1222  0.873093
1223  0.888358
1224  0.898236

[1225 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1190  1.903186
1191  1.887030
1192  1.913782
1193  1.877855
1194  1.847881

[1195 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
920  1.234914
921  1.216520
922  1.239859
923  1.145239
924  0.937153

[925 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
677  0.851429
678  0.852127
679  0.861193
680  0.812212
681  0.829077

[682 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1007  1.390184
1008  1.457754
1009  1.384638
1010  1.166801
1011  1.046030

[1012 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
214  1.497757
215  1.398120
216  1.363008
217  1.447521
218  1.366041

[219 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
665  2.558611
666  2.481958
667  2.473218
668  2.265921
669  2.161021

[670 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
699  0.935944
700  0.984075
701  0.953258
702  0.887933
703  0.846808

[704 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
739  1.124673
740  1.204877
741  1.163380
742  1.135093
743  1.108853

[744 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
710  1.313623
711  1.336531
712  1.320381
713  1.244200
714  1.178261

[715 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
104  0.531216
105  0.716237
106  0.744623
107  0.707433
108  0.701735

[109 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1454  0.801331
1455  0.679173
1456  0.675557
1457  0.755394
1458  1.203691

[1459 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
881  1.054271
882  1.059936
883  1.071980
884  0.966209
885  0.966068

[886 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
681  0.195409
682  0.196112
683  0.106636
684  0.472626
685  0.434154

[686 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1214  1.070394
1215  1.032410
1216  1.062614
1217  1.011657
1218  1.135696

[1219 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
790  1.988856
791  1.958774
792  1.865425
793  1.866416
794  1.866536

[795 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1239  1.141754
1240  1.204764
1241  1.181944
1242  1.198045
1243  1.113783

[1244 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1244  0.560282
1245  0.559387
1246  0.537601
1247  0.529360
1248  0.504616

[1249 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1236  0.769631
1237  0.771717
1238  0.754949
1239  0.790520
1240  0.747067

[1241 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
940  0.632350
941  0.616916
942  0.637666
943  0.556176
944  0.539461

[945 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
851  1.218703
852  1.064811
853  1.026824
854  0.882284
855  0.940421

[856 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
798  0.738466
799  0.701966
800  0.688919
801  0.587565
802  0.564512

[803 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
838  0.320304
839  0.342845
840  0.397693
841  0.578343
842  0.570776

[843 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
750  0.699230
751  0.761846
752  0.794037
753  0.843429
754  0.829071

[755 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
422  1.765445
423  1.776446
424  1.765608
425  1.734365
426  1.760266

[427 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
857  0.447237
858  0.445099
859  0.444820
860  0.457915
861  0.460288

[862 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
784  0.656358
785  0.649537
786  0.656600
787  0.655450
788  0.638337

[789 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
487  1.071016
488  1.064197
489  1.081363
490  1.048577
491  1.076619

[492 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1232  1.495555
1233  1.534693
1234  1.542586
1235  1.491986
1236  1.429383

[1237 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1215  0.785517
1216  0.840724
1217  0.868670
1218  0.900402
1219  0.970809

[1220 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
441  0.391738
442  0.366935
443  0.363544
444  0.280834
445  0.240127

[446 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
718  1.253375
719  1.193212
720  1.257044
721  1.155455
722  1.135878

[723 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
524  1.886809
525  1.888973
526  1.857129
527  1.744800
528  1.635471

[529 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1056  1.946006
1057  1.924940
1058  1.868268
1059  1.678480
1060  1.678499

[1061 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1241  0.680288
1242  0.703046
1243  0.713087
1244  0.833551
1245  0.815754

[1246 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1306  0.484607
1307  0.480000
1308  0.469752
1309  0.632770
1310  0.593406

[1311 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1262  0.322625
1263  0.286744
1264  0.227836
1265  0.396029
1266  0.344261

[1267 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
635  0.856246
636  0.835634
637  0.826290
638  1.068477
639  1.052883

[640 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
716  1.617701
717  1.704271
718  1.706143
719  1.683320
720  1.628954

[721 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
633  1.195075
634  1.207694
635  1.196665
636  1.227101
637  1.202489

[638 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1379  1.418813
1380  1.398083
1381  1.291627
1382  1.381795
1383  1.338760

[1384 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
648  0.761930
649  0.784174
650  0.771010
651  0.684888
652  0.632542

[653 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
981  1.466019
982  1.418138
983  1.531559
984  1.755296
985  1.684931

[986 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1418  0.658714
1419  0.698349
1420  0.669903
1421  0.826015
1422  0.847499

[1423 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
159  1.088070
160  1.117806
161  1.126961
162  1.050718
163  1.038507

[164 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1232  1.570139
1233  1.550021
1234  1.526649
1235  1.458904
1236  1.381966

[1237 rows x 1 columns]

            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
714  1.300675
715  1.267971
716  1.308510
717  1.218096
718  1.240284

[719 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
218  2.068549
219  2.065507
220  2.037258
221  2.026079
222  1.845524

[223 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
820  1.056238
821  1.054160
822  1.086602
823  1.071751
824  1.059617

[825 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1208  0.600876
1209  0.629627
1210  0.633884
1211  0.821516
1212  0.805633

[1213 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
725  1.022889
726  1.025709
727  1.018086
728  0.984798
729  0.933056

[730 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1276  1.365473
1277  1.271092
1278  1.242655
1279  1.144086
1280  1.130025

[1281 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
631  1.534249
632  1.545579
633  1.544215
634  1.481120
635  1.462558

[636 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
822  1.889023
823  1.872813
824  1.888816
825  1.905505
826  1.817307

[827 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
833  0.782635
834  0.784328
835  0.708243
836  0.584531
837  0.578638

[838 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
362  1.041767
363  1.057401
364  1.068220
365  0.926999
366  0.892211

[367 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
800  1.754243
801  1.702904
802  1.664616
803  1.509421
804  1.462308

[805 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
876  1.113161
877  1.037488
878  0.974210
879  0.749580
880  0.716921

[881 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1260  1.697393
1261  1.680795
1262  1.678141
1263  1.607639
1264  1.582367

[1265 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
821  0.713522
822  0.699712
823  0.726572
824  0.745990
825  0.756463

[826 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
831  0.651104
832  0.643022
833  0.603744
834  0.743318
835  0.532110

[836 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
837  0.876743
838  0.891034
839  0.852207
840  0.832879
841  0.800533

[842 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
673  0.758826
674  0.744902
675  0.770316
676  0.807050
677  0.799104

[678 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
484  1.124454
485  1.104727
486  1.056217
487  0.888128
488  0.839410

[489 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
601  0.892484
602  0.890059
603  0.846205
604  0.721513
605  0.533386

[606 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
794  1.124741
795  1.126480
796  1.139496
797  1.083488
798  1.061934

[799 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
461  0.651621
462  0.621523
463  0.607106
464  0.687379
465  0.659044

[466 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
924  0.547945
925  0.624479
926  0.609291
927  0.486740
928  0.384020

[929 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
585  1.832776
586  1.848537
587  1.825998
588  1.824674
589  1.854089

[590 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
864  1.909825
865  1.909104
866  1.906524
867  1.826810
868  1.805568

[869 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
629  0.780460
630  0.770376
631  0.805334
632  0.701469
633  0.658560

[634 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
213  1.237637
214  1.211772
215  1.175981
216  1.075677
217  1.045424

[218 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
947  0.617308
948  0.620626
949  0.623880
950  0.559347
951  0.559032

[952 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
800  0.394593
801  0.431409
802  0.313725
803  0.586120
804  0.510229

[805 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
494  0.963685
495  0.986921
496  0.917540
497  1.033791
498  1.043390

[499 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
821  1.056117
822  1.054261
823  1.085134
824  1.042540
825  1.018619

[826 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
834  1.361829
835  1.338728
836  1.349542
837  1.321156
838  1.286189

[839 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1236  0.669954
1237  0.735277
1238  0.748207
1239  1.005590
1240  0.944804

[1241 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
711  0.324951
712  0.313705
713  0.262882
714  0.243358
715  0.209464

[716 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
823  0.918724
824  0.896287
825  0.906847
826  0.805242
827  0.805075

[828 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1301  1.786403
1302  1.773982
1303  1.772455
1304  1.749947
1305  1.754886

[1306 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
733  1.262282
734  1.279177
735  1.350471
736  1.209837
737  1.198165

[738 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
565  0.655611
566  0.627652
567  0.664126
568  0.651049
569  0.591540

[570 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
303  1.037391
304  1.002320
305  0.980226
306  0.951839
307  0.926906

[308 rows x 1 columns]
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
36 NaN
37 NaN
38 NaN
39 NaN
40 NaN
41 NaN
42 NaN
43 NaN
44 NaN
45 NaN
46 NaN
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
651  0.753391
652  0.744364
653  0.732437
654  0.651553
655  0.633941

[656 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
625  0.436358
626  0.395804
627  0.395616
628  0.132248
629  0.053789

[630 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1255  0.806165
1256  0.753300
1257  0.725716
1258  0.593073
1259  0.526266

[1260 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
220  1.260680
221  1.199575
222  1.235861
223  1.295205
224  1.272812

[225 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1373  2.166006
1374  2.168093
1375  2.123735
1376  2.023265
1377  1.990207

[1378 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
839  0.598536
840  0.588600
841  0.609523
842  0.601104
843  0.607031

[844 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
752  2.264676
753  2.224779
754  2.212496
755  2.123878
756  2.051282

[757 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
480  0.824179
481  0.795980
482  0.826757
483  0.803232
484  0.805638

[485 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1071  1.396232
1072  1.423562
1073  1.233935
1074  1.304620
1075  1.220237

[1076 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
276  1.545102
277  1.576167
278  1.520676
279  1.509770
280  1.609200

[281 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1315  0.922166
1316  0.913820
1317  0.910750
1318  0.901064
1319  0.865344

[1320 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1556  0.685524
1557  0.740537
1558  0.792858
1559  0.717930
1560  0.762658

[1561 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
343  1.244300
344  1.258759
345  1.269085
346  1.249087
347  1.336616

[348 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
999   0.421975
1000  0.391248
1001  0.362941
1002  0.528515
1003  0.594213

[1004 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1180 -0.103599
1181 -0.064463
1182 -0.033499
1183 -0.068279
1184 -0.026388

[1185 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
476  0.996810
477  0.967689
478  0.966229
479  0.868041
480  0.830198

[481 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
713  0.970466
714  0.974863
715  0.922123
716  1.013037
717  0.958055

[718 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
858  0.230540
859  0.276415
860  0.225827
861  0.315572
862  0.190940

[863 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
573 -0.300026
574 -0.342909
575 -0.304509
576 -0.379483
577 -0.361786

[578 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
622  1.479598
623  1.552346
624  1.540662
625  1.595379
626  1.531185

[627 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
563  1.310192
564  1.253757
565  1.224245
566  1.031265
567  0.931296

[568 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
472  0.798458
473  0.777756
474  0.798736
475  0.643366
476  0.559271

[477 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
877  0.750789
878  0.779601
879  0.783982
880  0.799483
881  0.794392

[882 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
790  0.448363
791  0.439689
792  0.440220
793  0.388625
794  0.354660

[795 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1206  0.750097
1207  0.717145
1208  0.675833
1209  0.542588
1210  0.624092

[1211 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
82  1.449619
83  1.528733
84  1.494443
85  1.518246
86  1.452094

[87 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
694  2.043621
695  2.002920
696  2.087033
697  1.959527
698  1.968508

[699 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
646  1.288834
647  1.277413
648  1.313648
649  1.314537
650  1.290304

[651 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
663  0.539006
664  0.539371
665  0.542782
666  0.410597
667  0.468111

[668 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1010  1.235757
1011  1.357388
1012  1.311234
1013  1.074174
1014  1.066780

[1015 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
873  1.639911
874  1.651953
875  1.649156
876  1.589587
877  1.607523

[878 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
762  0.597265
763  0.556128
764  0.579123
765  0.895312
766  0.890514

[767 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1203  1.098853
1204  1.070080
1205  1.083512
1206  1.203677
1207  1.143603

[1208 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
691  1.449152
692  1.449608
693  1.464320
694  1.399648
695  1.361349

[696 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
529  0.836053
530  0.838679
531  0.856749
532  0.825004
533  0.843642

[534 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
986  0.567016
987  0.588113
988  0.537397
989  0.502052
990  0.509998

[991 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
907  1.610667
908  1.724328
909  1.699954
910  1.606703
911  1.595890

[912 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
347  0.843175
348  0.852209
349  0.841020
350  0.824498
351  0.802843

[352 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
197  0.709130
198  0.788681
199  0.806198
200  0.819792
201  0.739685

[202 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
719  0.809208
720  0.803067
721  0.772427
722  0.803496
723  0.785911

[724 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
751  0.610866
752  0.558746
753  0.550253
754  0.439160
755  0.398361

[756 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1871  0.977380
1872  0.964995
1873  0.951755
1874  0.879063
1875  0.860280

[1876 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
739  0.485249
740  0.462084
741  0.475703
742  0.634908
743  0.793007

[744 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
791  0.455537
792  0.450135
793  0.473973
794  0.502819
795  0.514645

[796 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
532  1.057018
533  1.087331
534  1.097665
535  1.016414
536  0.976203

[537 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
692  1.066506
693  1.034997
694  1.025576
695  0.974506
696  0.950088

[697 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
902  1.315450
903  1.305873
904  1.299058
905  1.258529
906  1.333778

[907 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1059  0.768067
1060  0.747415
1061  0.759267
1062  0.703207
1063  0.701324

[1064 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
993  0.547143
994  0.535416
995  0.521661
996  0.513711
997  0.511222

[998 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
169  1.778440
170  1.744674
171  1.770337
172  1.769575
173  1.629332

[174 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
769  1.558942
770  1.556955
771  1.575739
772  1.687985
773  1.688576

[774 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1307  1.052553
1308  1.087874
1309  1.037463
1310  1.116834
1311  1.139687

[1312 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1239  0.244681
1240  0.249880
1241  0.262530
1242  0.285154
1243  0.311600

[1244 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
429  0.927448
430  0.919779
431  0.887859
432  0.850910
433  0.760982

[434 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
779  0.579097
780  0.573016
781  0.578602
782  0.519613
783  0.525934

[784 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1026  0.955135
1027  0.899851
1028  0.909732
1029  0.861921
1030  0.865182

[1031 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1280  2.056719
1281  2.037916
1282  2.019011
1283  2.034356
1284  2.053140

[1285 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1100  0.501588
1101  0.496094
1102  0.496563
1103  0.711765
1104  0.695562

[1105 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
726  1.578685
727  1.568819
728  1.574775
729  1.621733
730  1.716276

[731 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
771  2.016646
772  2.001670
773  2.007108
774  1.974743
775  1.916695

[776 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1391  0.961508
1392  0.924619
1393  0.879486
1394  0.910778
1395  0.883646

[1396 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1178  1.522031
1179  1.534374
1180  1.592635
1181  1.533807
1182  1.510351

[1183 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
624  0.964134
625  1.007394
626  1.025050
627  1.084958
628  1.077386

[629 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
424  0.518314
425  0.498207
426  0.474221
427  0.431677
428  0.393800

[429 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
798  0.431163
799  0.433433
800  0.438639
801  0.371653
802  0.338698

[803 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
670  1.387796
671  1.397074
672  1.426792
673  1.400469
674  1.387742

[675 rows x 1 columns]

            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
165  1.383510
166  1.285681
167  1.270929
168  1.398275
169  1.474588

[170 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
900  1.108157
901  1.061613
902  1.072206
903  0.940726
904  1.084424

[905 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
815  0.807456
816  0.802984
817  0.792225
818  0.736386
819  0.724919

[820 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1225  0.407757
1226  0.442252
1227  0.431464
1228  0.443065
1229  0.474890

[1230 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
870  0.598234
871  0.528124
872  0.646551
873  0.553673
874  0.556067

[875 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
923  0.915448
924  0.899544
925  0.910982
926  1.045569
927  0.981154

[928 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
853  1.125624
854  1.130640
855  1.152650
856  1.231972
857  1.189582

[858 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
617  2.568943
618  2.569187
619  2.535440
620  2.389965
621  2.271411

[622 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
778  0.948658
779  0.944277
780  0.954859
781  0.885187
782  0.832961

[783 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1206  1.406560
1207  1.395839
1208  1.431434
1209  1.370543
1210  1.345087

[1211 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
654  0.814896
655  0.748400
656  0.745299
657  0.628356
658  0.624291

[659 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
783  0.940533
784  0.952981
785  0.985860
786  0.862802
787  0.916132

[788 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
910  0.604511
911  0.627932
912  0.632518
913  0.403466
914  0.366176

[915 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
818  1.342240
819  1.416189
820  1.408936
821  1.136715
822  1.173646

[823 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
832  0.879202
833  0.814322
834  0.809989
835  0.927600
836  0.895213

[837 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
621  0.943367
622  0.954838
623  0.939902
624  0.820177
625  0.821809

[626 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
751  0.840269
752  1.011845
753  0.969710
754  1.088427
755  0.986688

[756 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
640  1.159040
641  1.095269
642  1.122043
643  1.171623
644  1.210591

[645 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
875  0.503866
876  0.503242
877  0.477820
878  0.551769
879  0.517412

[880 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
890  1.571763
891  1.520342
892  1.517327
893  1.372949
894  1.382400

[895 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
703  0.526739
704  0.535454
705  0.559741
706  0.512793
707  0.529443

[708 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
955  0.884464
956  0.827136
957  0.838294
958  0.719767
959  0.709960

[960 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
245  0.926827
246  0.914448
247  0.904979
248  0.885684
249  0.857082

[250 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1096  0.506097
1097  0.545004
1098  0.589329
1099  0.602575
1100  0.596687

[1101 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
241  0.781327
242  0.975298
243  1.027361
244  1.439883
245  1.404702

[246 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1019  0.746366
1020  0.725553
1021  0.689796
1022  0.660414
1023  0.808291

[1024 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1183  0.555659
1184  0.511241
1185  0.524577
1186  0.403903
1187  0.398158

[1188 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
575  0.785234
576  0.833508
577  0.840873
578  0.772817
579  0.768346

[580 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
531  1.595249
532  1.599179
533  1.611946
534  1.581811
535  1.556888

[536 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
837  0.489970
838  0.468431
839  0.496803
840  0.497541
841  0.500385

[842 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
854  0.546970
855  0.548265
856  0.573620
857  0.583539
858  0.566003

[859 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
738  0.101345
739  0.084458
740  0.092338
741  0.226431
742  0.220582

[743 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
611  1.217940
612  1.259397
613  1.123996
614  1.067365
615  1.107347

[616 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
821  2.077781
822  2.138480
823  2.086663
824  1.930723
825  1.847411

[826 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
676  1.033719
677  1.109549
678  1.056744
679  0.942999
680  0.823982

[681 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1167  0.230008
1168  0.251232
1169  0.216760
1170  0.280825
1171  0.201796

[1172 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1225  1.038566
1226  1.043083
1227  1.045552
1228  1.065553
1229  1.062806

[1230 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
847  0.921200
848  0.978644
849  0.978781
850  1.045001
851  1.029688

[852 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
827  1.696474
828  1.684745
829  1.593508
830  1.533437
831  1.480097

[832 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
888  1.736667
889  1.792392
890  1.821630
891  1.759390
892  1.799783

[893 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1217  0.969439
1218  0.965221
1219  0.977591
1220  0.842651
1221  0.821984

[1222 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
614  1.393810
615  1.353257
616  1.336437
617  1.247642
618  1.094305

[619 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
93  1.906004
94  1.916548
95  1.846238
96  1.734951
97  1.716748

[98 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
586  0.213247
587  0.260199
588  0.239745
589  0.130644
590  0.163839

[591 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
761  0.404291
762  0.408707
763  0.427890
764  0.638866
765  0.692765

[766 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
537  1.186671
538  1.170945
539  1.165711
540  1.124929
541  1.114150

[542 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1224  1.014567
1225  1.009178
1226  1.026959
1227  1.018927
1228  1.031708

[1229 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1316  0.914621
1317  0.936979
1318  0.942604
1319  1.014666
1320  1.061582

[1321 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
871  1.367934
872  1.361330
873  1.385911
874  1.262100
875  1.254637

[876 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1216  1.352692
1217  1.423142
1218  1.422048
1219  1.354968
1220  1.336856

[1221 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
799  1.268016
800  1.280522
801  1.245795
802  1.162593
803  1.084145

[804 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
782  1.099436
783  1.076190
784  1.121807
785  1.289687
786  1.421467

[787 rows x 1 columns]

            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
804  0.779607
805  0.744496
806  0.762722
807  0.722358
808  0.721500

[809 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
928  0.256873
929  0.206003
930  0.225963
931  0.104031
932  0.115174

[933 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
643  2.060394
644  2.001813
645  2.009829
646  1.821327
647  1.856708

[648 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
249  0.755689
250  0.714312
251  0.657123
252  0.725473
253  0.771222

[254 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
636  1.149249
637  1.162224
638  1.296821
639  1.304700
640  1.338182

[641 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
620  0.676370
621  0.681290
622  0.806656
623  0.670106
624  0.622509

[625 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1140  1.464629
1141  1.666190
1142  1.647493
1143  1.894906
1144  1.869119

[1145 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1021  0.402520
1022  0.387191
1023  0.394866
1024  0.478754
1025  0.593007

[1026 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
770  2.212414
771  2.206478
772  2.224924
773  2.219240
774  2.175103

[775 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
650  0.193575
651  0.129682
652  0.103059
653 -0.080123
654 -0.087649

[655 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
761  0.341216
762  0.351644
763  0.369168
764  0.439499
765  0.434754

[766 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
189  1.356268
190  1.379032
191  1.394909
192  1.407840
193  1.374600

[194 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
859  1.082859
860  1.068490
861  1.068072
862  1.034047
863  1.021639

[864 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
845  1.665212
846  1.655508
847  1.707337
848  1.494981
849  1.429132

[850 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
722  1.186052
723  1.174175
724  1.213793
725  1.134678
726  1.095769

[727 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1007  1.797243
1008  1.826178
1009  1.730584
1010  1.602417
1011  1.555798

[1012 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
642  0.200332
643  0.218778
644  0.261109
645  0.306873
646  0.329346

[647 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
728  1.927904
729  1.904063
730  1.843568
731  1.552376
732  1.488714

[733 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1185  0.727427
1186  0.752203
1187  0.727812
1188  0.815753
1189  0.698179

[1190 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
77  0.736925
78  0.629679
79  0.635049
80  0.815732
81  0.792403

[82 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
71  0.458016
72  0.326681
73  0.298071
74  0.652166
75  0.638445

[76 rows x 1 columns]
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
761  1.346739
762  1.313640
763  1.349096
764  1.237136
765  1.237597

[766 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
325  0.703123
326  0.677180
327  0.701692
328  0.746755
329  0.700448

[330 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
970  0.729600
971  0.724761
972  0.717511
973  0.644931
974  0.637798

[975 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
995  1.183501
996  1.176866
997  1.221596
998  1.024168
999  0.984657

[1000 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
742  0.992480
743  0.990164
744  1.014645
745  1.107487
746  1.167225

[747 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
666  0.703184
667  0.693076
668  0.665226
669  0.639667
670  0.619699

[671 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
828  0.779613
829  0.762727
830  0.761540
831  0.739868
832  0.778361

[833 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
280  1.042094
281  1.031211
282  1.050724
283  1.022953
284  1.027954

[285 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1244  0.833432
1245  0.838570
1246  0.821054
1247  0.828270
1248  0.849308

[1249 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1298  1.090422
1299  1.047250
1300  1.033581
1301  1.120020
1302  1.090518

[1303 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
632  0.651434
633  0.683023
634  0.619294
635  0.701928
636  0.665204

[637 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
689  1.685203
690  1.722759
691  1.571990
692  1.656486
693  1.696659

[694 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
791  0.883753
792  0.872629
793  0.822331
794  0.771420
795  0.578028

[796 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
697  1.635988
698  1.635395
699  1.607450
700  1.539472
701  1.544068

[702 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1214  0.674987
1215  0.660985
1216  0.657318
1217  0.632898
1218  0.584881

[1219 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
736  0.838041
737  0.814576
738  0.793501
739  0.760257
740  0.716455

[741 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
266  1.524259
267  1.475781
268  1.480344
269  1.639869
270  1.625812

[271 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
221  1.298541
222  1.327265
223  1.331323
224  1.356697
225  1.290722

[226 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
764  0.383059
765  0.335326
766  0.342054
767  0.390821
768  0.339184

[769 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
728  2.256776
729  2.246745
730  2.297773
731  2.382526
732  2.346187

[733 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
874  0.718952
875  0.750171
876  0.733003
877  0.816757
878  0.755068

[879 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1360  1.859753
1361  1.843207
1362  1.872349
1363  2.015392
1364  2.039377

[1365 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1242  1.342618
1243  1.323669
1244  1.315089
1245  1.324073
1246  1.343096

[1247 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
861  1.097440
862  1.140508
863  1.160743
864  0.993872
865  0.987516

[866 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
803  1.364264
804  1.394024
805  1.367239
806  1.332026
807  1.291961

[808 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
199  0.828202
200  0.967363
201  0.968505
202  0.827843
203  0.793285

[204 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1853  1.407235
1854  1.387151
1855  1.384529
1856  1.409027
1857  1.420093

[1858 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
118  0.929527
119  0.945722
120  0.904872
121  0.859564
122  0.767516

[123 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1093  0.779896
1094  0.721950
1095  0.659191
1096  0.612948
1097  0.504295

[1098 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1201  1.062754
1202  1.063898
1203  1.085753
1204  1.432072
1205  1.403916

[1206 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1275  0.839378
1276  0.875761
1277  0.881666
1278  0.862972
1279  0.835679

[1280 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1101  1.320494
1102  1.344726
1103  1.369387
1104  1.323695
1105  1.315628

[1106 rows x 1 columns]
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
    0
0 NaN
1 NaN
2 NaN
3 NaN
4 NaN
5 NaN
6 NaN
7 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
224  2.355372
225  2.338458
226  2.349531
227  2.275598
228  2.235673

[229 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
224  1.894437
225  1.921236
226  1.921841
227  1.871078
228  1.893578

[229 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
224  1.679266
225  1.696678
226  1.733922
227  1.680921
228  1.635185

[229 rows x 1 columns]
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
223  1.819694
224  1.796380
225  1.829411
226  1.836473
227  1.818405

[228 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
224  1.302881
225  1.344516
226  1.355917
227  1.356424
228  1.406126

[229 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
224  1.659991
225  1.660563
226  1.690691
227  1.643066
228  1.601287

[229 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
224  2.151833
225  2.124799
226  2.182750
227  2.200047
228  2.126346

[229 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
224  1.035630
225  1.020248
226  1.036159
227  0.999789
228  0.982964

[229 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
224  1.667370
225  1.664226
226  1.672113
227  1.607069
228  1.605750

[229 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
224  1.704140
225  1.714855
226  1.717043
227  1.605296
228  1.604162

[229 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
224  2.535644
225  2.506192
226  2.572110
227  2.515065
228  2.516415

[229 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
224  1.545225
225  1.506144
226  1.548904
227  1.728749
228  1.690770

[229 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
224  1.547598
225  1.560138
226  1.549853
227  1.520733
228  1.521320

[229 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
224  2.167951
225  2.195675
226  2.138051
227  2.098869
228  2.034539

[229 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
224  2.466402
225  2.462574
226  2.480291
227  2.492986
228  2.383621

[229 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
224  2.251044
225  2.220747
226  2.226521
227  2.310992
228  2.221904

[229 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
153  2.205799
154  2.159101
155  2.134514
156  1.906805
157  1.837457

[158 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
224  1.468056
225  1.451677
226  1.477136
227  1.382900
228  1.369682

[229 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
154  2.486790
155  2.544550
156  2.556272
157  2.530966
158  2.491914

[159 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
157  2.352654
158  2.357769
159  2.281600
160  2.200673
161  2.109302

[162 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
99   1.019214
100  0.966718
101  0.911760
102  1.075175
103  1.028508

[104 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
224  1.962630
225  1.947674
226  1.961090
227  1.831885
228  1.824495

[229 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
224  1.612523
225  1.656630
226  1.696194
227  1.711484
228  1.626658

[229 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
175  2.254577
176  2.264681
177  2.237415
178  2.077655
179  2.015231

[180 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
224  1.450582
225  1.419480
226  1.427073
227  1.387399
228  1.369766

[229 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
175  2.322645
176  2.334126
177  2.299664
178  2.100726
179  1.969852

[180 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
125  2.220346
126  2.328442
127  2.284803
128  2.444755
129  2.388474

[130 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
128  2.086633
129  2.082845
130  2.087613
131  2.111496
132  2.057741

[133 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
63  1.932078
64  1.776022
65  1.710289
66  1.741287
67  1.660681

[68 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
156  3.271250
157  3.353115
158  3.336847
159  3.067870
160  3.052053

[161 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
224  1.806551
225  1.780397
226  1.763891
227  1.689358
228  1.616011

[229 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
175  1.090636
176  1.164701
177  1.068743
178  0.873976
179  0.798019

[180 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
115  1.919200
116  1.908324
117  1.883036
118  1.766084
119  1.717468

[120 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
90  2.072662
91  2.058558
92  2.071074
93  1.884825
94  1.896997

[95 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
111  1.725256
112  1.717556
113  1.731357
114  1.588071
115  1.570769

[116 rows x 1 columns]
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
36 NaN
37 NaN
38 NaN
39 NaN
40 NaN
41 NaN
42 NaN
43 NaN
44 NaN
45 NaN
46 NaN
47 NaN
48 NaN
49 NaN
50 NaN
51 NaN
52 NaN
53 NaN
54 NaN
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
80  2.331105
81  2.303649
82  2.321895
83  2.232552
84  2.157986

[85 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
224  2.938942
225  2.900847
226  2.894598
227  2.754158
228  2.796226

[229 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
122  2.080766
123  2.088179
124  2.003885
125  1.908536
126  1.817038

[127 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
87  1.600782
88  1.577771
89  1.620281
90  1.463816
91  1.431515

[92 rows x 1 columns]
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
36 NaN
37 NaN
38 NaN
39 NaN
40 NaN
41 NaN
42 NaN
43 NaN
44 NaN
45 NaN
46 NaN
47 NaN
48 NaN
49 NaN
50 NaN
51 NaN
52 NaN
53 NaN
54 NaN
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
160  1.781678
161  1.807726
162  1.765644
163  1.766301
164  1.709554

[165 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
211  2.051859
212  2.035056
213  2.066986
214  2.020803
215  1.999892

[216 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
100  1.777847
101  1.747742
102  1.784400
103  1.667477
104  1.616424

[105 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
146  1.549156
147  1.564083
148  1.581776
149  1.543177
150  1.531802

[151 rows x 1 columns]
    0
0 NaN
1 NaN
2 NaN
3 NaN
4 NaN
5 NaN
6 NaN
7 NaN
8 NaN
9 NaN
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
158  1.888394
159  1.973353
160  1.940642
161  2.026516
162  2.177530

[163 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
145  1.718231
146  1.836151
147  1.855710
148  1.764811
149  1.658902

[150 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
178  2.535121
179  2.482818
180  2.458949
181  2.304064
182  2.281387

[183 rows x 1 columns]

            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
133  2.356531
134  2.377346
135  2.385478
136  2.345435
137  2.285311

[138 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
224  1.505900
225  1.470846
226  1.487883
227  1.370296
228  1.354458

[229 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
120  3.284612
121  3.261475
122  3.199457
123  3.050402
124  2.966940

[125 rows x 1 columns]
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
36 NaN
37 NaN
38 NaN
39 NaN
40 NaN
41 NaN
42 NaN
43 NaN
44 NaN
45 NaN
46 NaN
47 NaN
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
154  1.640685
155  1.626211
156  1.646737
157  1.662520
158  1.620621

[159 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
143  2.523362
144  2.493046
145  2.514334
146  2.494713
147  2.422217

[148 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
161  1.478519
162  1.542877
163  1.462884
164  1.388435
165  1.257654

[166 rows x 1 columns]
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
101  2.980852
102  2.956555
103  2.957774
104  2.868845
105  2.819290

[106 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
98   1.837253
99   1.780166
100  1.753133
101  1.672589
102  1.576454

[103 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
151  1.390063
152  1.430719
153  1.450773
154  1.391603
155  1.270382

[156 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
190  1.713714
191  1.696137
192  1.704669
193  1.631160
194  1.599008

[195 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
83  1.166952
84  1.128641
85  1.139500
86  1.348449
87  1.452557

[88 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
83  1.397955
84  1.363364
85  1.283718
86  1.065776
87  1.010491

[88 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
105  1.480239
106  1.469937
107  1.499891
108  1.494158
109  1.485644

[110 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
111  1.457858
112  1.424439
113  1.432443
114  1.362963
115  1.283839

[116 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
91  1.458459
92  1.431707
93  1.438866
94  1.419606
95  1.358996

[96 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
211  1.263482
212  1.254853
213  1.268036
214  1.311770
215  1.394002

[216 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
59  0.330200
60  1.834252
61  1.748089
62  1.463747
63  1.436071

[64 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
142  1.425005
143  1.368611
144  1.293197
145  1.642674
146  1.680928

[147 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
130  1.364596
131  1.387571
132  1.251101
133  1.345504
134  1.252228

[135 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
154  1.310834
155  1.297395
156  1.323789
157  1.383389
158  1.336274

[159 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
86  2.503037
87  2.439756
88  2.431235
89  2.272593
90  2.313525

[91 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
154  1.070515
155  1.130655
156  1.096108
157  1.058458
158  0.964924

[159 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
89  1.234297
90  1.161166
91  1.176434
92  1.094428
93  0.976915

[94 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
128  1.587557
129  1.573197
130  1.590434
131  1.533496
132  1.509559

[133 rows x 1 columns]
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
36 NaN
37 NaN
38 NaN
39 NaN
40 NaN
41 NaN
42 NaN
43 NaN
44 NaN
45 NaN
46 NaN
47 NaN
48 NaN
49 NaN
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
58       NaN
59  2.056677
60  2.322825
61  1.972680
62  1.910271

[63 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
83  1.275565
84  1.225426
85  1.281475
86  1.159097
87  1.082857

[88 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
130  3.527017
131  3.494138
132  3.489335
133  3.536026
134  3.577507

[135 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
98   1.193061
99   1.186089
100  1.105704
101  0.908599
102  0.875608

[103 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
117  3.067407
118  3.095245
119  3.065417
120  2.891501
121  2.801642

[122 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
102  1.214427
103  1.300156
104  1.231093
105  1.121926
106  1.251549

[107 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
153  1.862103
154  1.858060
155  1.773907
156  1.664931
157  1.632310

[158 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
95  1.612711
96  1.620710
97  1.544010
98  1.654571
99  1.626419

[100 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
153  2.163335
154  2.125785
155  2.123317
156  2.158196
157  2.112251

[158 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
146  2.502507
147  2.487627
148  2.391735
149  2.280590
150  2.276677

[151 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
134  1.369753
135  1.394746
136  1.375306
137  1.381007
138  1.348425

[139 rows x 1 columns]
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
36 NaN
37 NaN
38 NaN
39 NaN
40 NaN
41 NaN
42 NaN
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
209  1.512611
210  1.486158
211  1.454682
212  1.371643
213  1.277560

[214 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
224  1.836654
225  1.814599
226  1.799848
227  1.715148
228  1.667119

[229 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
133  1.634697
134  1.661922
135  1.663577
136  1.577799
137  1.578089

[138 rows x 1 columns]

            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
134  1.696072
135  1.759634
136  1.669162
137  1.965877
138  1.826092

[139 rows x 1 columns]
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
153  1.578694
154  1.561489
155  1.480951
156  1.438382
157  1.374210

[158 rows x 1 columns]
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
36 NaN
37 NaN
38 NaN
39 NaN
40 NaN
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
158  1.507717
159  1.529086
160  1.530528
161  1.494957
162  1.432102

[163 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
170  2.027277
171  1.995429
172  2.004513
173  2.008508
174  1.967806

[175 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
157  1.656917
158  1.634064
159  1.645798
160  1.609250
161  1.553001

[162 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
224  1.751528
225  1.729607
226  1.752236
227  1.722339
228  1.674599

[229 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
154  1.096297
155  1.195176
156  1.110353
157  0.912442
158  0.812904

[159 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
79  2.348129
80  2.334837
81  2.318667
82  2.271481
83  2.314006

[84 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
91  1.445310
92  1.378126
93  1.423024
94  1.309805
95  1.278660

[96 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
132  0.267021
133  0.307713
134  0.134054
135  0.050925
136 -0.033261

[137 rows x 1 columns]
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
36 NaN
    0
0 NaN
1 NaN
2 NaN
3 NaN
4 NaN
5 NaN
6 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
    0
0 NaN
1 NaN
2 NaN
3 NaN
4 NaN
5 NaN
    0
0 NaN
1 NaN
2 NaN
3 NaN
4 NaN
5 NaN
    0
0 NaN
    0
0 NaN
1 NaN
2 NaN
3 NaN
4 NaN
    0
0 NaN
1 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2474  0.586509
2475  0.619851
2476  0.618544
2477  0.582357
2478  0.615500

[2479 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2389  0.507294
2390  0.491888
2391  0.520139
2392  0.489710
2393  0.608645

[2394 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2296  1.592476
2297  1.590571
2298  1.501291
2299  1.455823
2300  1.453131

[2301 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2203  0.670936
2204  0.666891
2205  0.680976
2206  0.683157
2207  0.699148

[2208 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2419  0.540400
2420  0.503734
2421  0.456617
2422  0.458047
2423  0.607508

[2424 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1937  0.427687
1938  0.398928
1939  0.438411
1940  0.310465
1941  0.310559

[1942 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2223  0.674893
2224  0.635609
2225  0.647850
2226  0.618186
2227  0.622317

[2228 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2434  1.597333
2435  1.537982
2436  1.487443
2437  1.546597
2438  1.517459

[2439 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1787  0.712795
1788  0.670505
1789  0.641059
1790  0.601504
1791  0.584090

[1792 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2517  0.905301
2518  0.852831
2519  0.819860
2520  0.832508
2521  0.959676

[2522 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2499  1.224851
2500  1.193762
2501  1.138911
2502  1.031924
2503  0.994762

[2504 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2538  0.598576
2539  0.566381
2540  0.497212
2541  0.424335
2542  0.533475

[2543 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2450  2.179653
2451  2.165112
2452  2.176795
2453  2.181155
2454  2.190208

[2455 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2167  0.846155
2168  0.750840
2169  0.765872
2170  0.758441
2171  0.701509

[2172 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2293 -0.075022
2294 -0.058165
2295  0.016599
2296 -0.044600
2297 -0.012856

[2298 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2308  0.297441
2309  0.473473
2310  0.433589
2311  0.665685
2312  0.654787

[2313 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2246  0.632968
2247  0.637822
2248  0.492686
2249  0.665086
2250  0.689393

[2251 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2513  1.764213
2514  1.706453
2515  1.760844
2516  1.607596
2517  1.583450

[2518 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1889  0.961622
1890  0.960362
1891  0.968879
1892  0.977715
1893  0.988360

[1894 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2251  0.512615
2252  0.497715
2253  0.475030
2254  0.544885
2255  0.538987

[2256 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2510  0.737874
2511  0.723851
2512  0.704148
2513  0.699290
2514  0.678779

[2515 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2530  0.913122
2531  0.931320
2532  0.943780
2533  0.884324
2534  0.878192

[2535 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2494  0.368638
2495  0.362242
2496  0.390412
2497  0.401389
2498  0.404999

[2499 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2417  0.557582
2418  0.567616
2419  0.640586
2420  0.590441
2421  0.573723

[2422 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1619  1.112646
1620  1.090782
1621  1.075804
1622  0.781080
1623  0.762395

[1624 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2210  1.683597
2211  1.620857
2212  1.620358
2213  1.668848
2214  1.572459

[2215 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2350  0.727664
2351  0.741246
2352  0.757664
2353  0.811851
2354  0.865066

[2355 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2261  1.070895
2262  1.055274
2263  0.954544
2264  0.864474
2265  0.827754

[2266 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1928  2.635200
1929  2.696140
1930  2.588369
1931  2.403149
1932  2.342743

[1933 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1744  0.749812
1745  0.724988
1746  0.712709
1747  0.648559
1748  0.632022

[1749 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2491  0.676009
2492  0.661996
2493  0.708642
2494  0.722266
2495  0.738850

[2496 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2254  0.635648
2255  0.680925
2256  0.652482
2257  0.533344
2258  0.516416

[2259 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1317  0.605961
1318  0.537718
1319  0.498569
1320  0.461481
1321  0.410520

[1322 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2512  0.467203
2513  0.478603
2514  0.510187
2515  0.554993
2516  0.550057

[2517 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2354  1.349511
2355  1.322719
2356  1.306376
2357  1.284742
2358  1.262103

[2359 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2334  0.398830
2335  0.410192
2336  0.423527
2337  0.337878
2338  0.380640

[2339 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2318  1.281096
2319  1.308974
2320  1.376296
2321  1.377083
2322  1.311504

[2323 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2361  0.726389
2362  0.708454
2363  0.686118
2364  0.846205
2365  0.842009

[2366 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2454  1.064780
2455  1.069027
2456  1.073556
2457  1.072286
2458  1.078850

[2459 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2354  0.172163
2355  0.185831
2356  0.184416
2357  0.248945
2358  0.233044

[2359 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2505  1.582963
2506  1.567150
2507  1.550339
2508  1.479188
2509  1.465308

[2510 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2334  1.325158
2335  1.308668
2336  1.315925
2337  1.293796
2338  1.252733

[2339 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2514  0.980228
2515  0.937044
2516  0.947702
2517  0.916797
2518  0.946806

[2519 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2365  0.893986
2366  0.874031
2367  0.846528
2368  0.874893
2369  0.894839

[2370 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2094  0.692394
2095  0.647009
2096  0.592023
2097  0.663186
2098  0.599805

[2099 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2420  0.744766
2421  0.775036
2422  0.773317
2423  0.762108
2424  0.771943

[2425 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2523  0.695839
2524  0.691214
2525  0.698531
2526  0.654289
2527  0.677826

[2528 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2429  0.682381
2430  0.746396
2431  0.713336
2432  0.796275
2433  0.760357

[2434 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2423  1.093765
2424  1.090066
2425  1.056999
2426  1.008076
2427  0.957641

[2428 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2458  1.782357
2459  1.746859
2460  1.752352
2461  1.812437
2462  1.768246

[2463 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2414  0.779778
2415  0.753590
2416  0.763995
2417  0.705117
2418  0.714291

[2419 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2304  1.771685
2305  1.812013
2306  1.813884
2307  1.784036
2308  1.820345

[2309 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2052  0.460202
2053  0.437058
2054  0.402920
2055  0.371145
2056  0.331603

[2057 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2494  0.573021
2495  0.571129
2496  0.588092
2497  0.588282
2498  0.702830

[2499 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2381  1.221227
2382  1.181815
2383  1.143887
2384  1.047565
2385  1.033173

[2386 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2515  0.611447
2516  0.685422
2517  0.628120
2518  0.588104
2519  0.570879

[2520 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2468  0.425481
2469  0.404572
2470  0.398422
2471  0.396752
2472  0.390171

[2473 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2535  0.627591
2536  0.610183
2537  0.615254
2538  0.631352
2539  0.638331

[2540 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2479  1.175218
2480  1.139672
2481  1.098738
2482  1.089167
2483  1.183839

[2484 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2538  0.724107
2539  0.709509
2540  0.707217
2541  0.757950
2542  0.739186

[2543 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2414  1.048403
2415  1.029246
2416  1.020054
2417  0.984582
2418  0.976637

[2419 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2329  2.039005
2330  1.990910
2331  1.968419
2332  1.845983
2333  1.773432

[2334 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2270  0.553586
2271  0.586570
2272  0.582781
2273  0.605444
2274  0.597441

[2275 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2532  0.814654
2533  0.829866
2534  0.813343
2535  0.824340
2536  0.814591

[2537 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2205  0.514418
2206  0.526701
2207  0.496249
2208  0.598595
2209  0.579095

[2210 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2013  1.033739
2014  1.006827
2015  0.982092
2016  1.015856
2017  1.040327

[2018 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1695  1.030946
1696  1.053813
1697  1.090487
1698  1.026215
1699  1.009509

[1700 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2531  0.929838
2532  0.961580
2533  0.978550
2534  1.082811
2535  1.189066

[2536 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2452  2.244205
2453  2.249207
2454  2.184956
2455  2.110619
2456  2.109263

[2457 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2392  1.161532
2393  1.179222
2394  1.197493
2395  1.167795
2396  1.155413

[2397 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1287  0.884904
1288  0.871294
1289  0.874725
1290  0.970550
1291  0.971082

[1292 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2370  0.590188
2371  0.601393
2372  0.607858
2373  0.616879
2374  0.583906

[2375 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1583  0.841024
1584  0.830394
1585  0.825964
1586  0.729242
1587  0.785309

[1588 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2536  1.166838
2537  1.171197
2538  1.156550
2539  1.067012
2540  1.077181

[2541 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2472  1.098311
2473  1.053348
2474  1.046579
2475  1.177610
2476  1.161067

[2477 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2388  1.071749
2389  1.021365
2390  1.068828
2391  1.128497
2392  1.201850

[2393 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2537  0.534674
2538  0.514093
2539  0.531701
2540  0.564038
2541  0.603710

[2542 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1489  0.685008
1490  0.730419
1491  0.740546
1492  0.634911
1493  0.578649

[1494 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2515  1.037639
2516  1.061830
2517  1.074187
2518  1.030354
2519  1.000080

[2520 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2344  0.976242
2345  0.951501
2346  0.928933
2347  0.893735
2348  0.877374

[2349 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2332  0.498597
2333  0.405411
2334  0.322577
2335  0.433465
2336  0.336942

[2337 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2265  0.743896
2266  0.840100
2267  0.868861
2268  0.753342
2269  0.752758

[2270 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2477  0.781848
2478  0.774515
2479  0.752628
2480  0.709521
2481  0.708309

[2482 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2376  0.707274
2377  0.735867
2378  0.653149
2379  0.737774
2380  0.711004

[2381 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2383  1.267275
2384  1.238495
2385  1.250591
2386  1.180332
2387  1.145550

[2388 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1980  0.779440
1981  0.764117
1982  0.773421
1983  0.771756
1984  0.752799

[1985 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2392  1.468886
2393  1.461280
2394  1.470612
2395  1.540340
2396  1.488499

[2397 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2529  0.386819
2530  0.346752
2531  0.350679
2532  0.404148
2533  0.368286

[2534 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2201  0.973400
2202  0.928412
2203  0.933298
2204  0.968974
2205  1.004190

[2206 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2532  0.589992
2533  0.563444
2534  0.586502
2535  0.585941
2536  0.586866

[2537 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2497  1.262390
2498  1.233329
2499  1.228703
2500  1.243229
2501  1.209855

[2502 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2490  0.138351
2491  0.115809
2492  0.134638
2493  0.090686
2494  0.096689

[2495 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2479  0.451418
2480  0.474207
2481  0.458327
2482  0.492039
2483  0.482341

[2484 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2535  0.676342
2536  0.671693
2537  0.721956
2538  0.556550
2539  0.499681

[2540 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2509  1.177555
2510  1.151900
2511  1.159930
2512  1.177853
2513  1.227098

[2514 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2219  1.627439
2220  1.655786
2221  1.585279
2222  1.341190
2223  1.481669

[2224 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2425  1.821451
2426  1.790991
2427  1.771593
2428  1.634000
2429  1.576294

[2430 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2396  0.307928
2397  0.303580
2398  0.313632
2399  0.319790
2400  0.321058

[2401 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2485  0.800996
2486  0.820675
2487  0.825493
2488  0.662540
2489  0.663826

[2490 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2511  0.308621
2512  0.297089
2513  0.292335
2514  0.297501
2515  0.284995

[2516 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1668  0.826177
1669  0.811181
1670  0.863726
1671  0.948019
1672  0.950221

[1673 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2462  0.681210
2463  0.674291
2464  0.744361
2465  1.004868
2466  1.149010

[2467 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2243  1.291069
2244  1.253353
2245  1.238434
2246  1.134142
2247  1.192805

[2248 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2308  1.326664
2309  1.324645
2310  1.350393
2311  1.281965
2312  1.434845

[2313 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2042  0.199606
2043  0.203246
2044  0.134280
2045  0.057579
2046  0.069180

[2047 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2291  0.865203
2292  1.049392
2293  1.002612
2294  1.328646
2295  1.308935

[2296 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2175  1.010262
2176  0.959639
2177  0.915508
2178  0.792749
2179  0.804221

[2180 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2512  0.499144
2513  0.491451
2514  0.509268
2515  0.467668
2516  0.477483

[2517 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2099  0.507378
2100  0.418741
2101  0.428358
2102  0.353506
2103  0.161979

[2104 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2398  1.318764
2399  1.309738
2400  1.347639
2401  1.266781
2402  1.262517

[2403 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2440  0.897293
2441  0.997125
2442  0.941062
2443  0.888155
2444  0.829712

[2445 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2447  0.757954
2448  0.714630
2449  0.749095
2450  0.869753
2451  0.891800

[2452 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2342  0.664879
2343  0.686295
2344  0.666427
2345  0.583485
2346  0.583805

[2347 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2483  0.722714
2484  0.690809
2485  0.719710
2486  0.753069
2487  0.812550

[2488 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2419  0.938250
2420  0.998188
2421  0.962419
2422  0.869547
2423  0.842003

[2424 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2339  0.417915
2340  0.377716
2341  0.360360
2342  0.403511
2343  0.404448

[2344 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1975  0.531035
1976  0.565303
1977  0.560202
1978  0.477346
1979  0.460317

[1980 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2509  1.283533
2510  1.345949
2511  1.376291
2512  1.217217
2513  1.200099

[2514 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2402  0.895755
2403  0.908558
2404  0.908627
2405  0.953834
2406  0.959783

[2407 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2356  0.312501
2357  0.285633
2358  0.275762
2359  0.190918
2360  0.198327

[2361 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2515  0.844873
2516  0.945212
2517  0.874014
2518  0.933460
2519  0.899279

[2520 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2017  1.447036
2018  1.430664
2019  1.416314
2020  1.289147
2021  1.162624

[2022 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2528  0.714586
2529  0.689979
2530  0.710243
2531  0.704091
2532  0.726425

[2533 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2434  0.781311
2435  0.815190
2436  0.812541
2437  0.868646
2438  0.823165

[2439 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2523  0.860193
2524  0.872920
2525  0.871453
2526  0.829784
2527  0.845533

[2528 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2436  0.084757
2437  0.048931
2438  0.062247
2439  0.283744
2440  0.283773

[2441 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2486  0.538528
2487  0.496743
2488  0.473510
2489  0.422700
2490  0.378969

[2491 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2360  1.195021
2361  1.146586
2362  1.152226
2363  1.132155
2364  1.106029

[2365 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2144  0.706813
2145  0.712344
2146  0.693010
2147  0.804388
2148  0.807607

[2149 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2373  0.692970
2374  0.642702
2375  0.590852
2376  0.564455
2377  0.484100

[2378 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2397  0.589183
2398  0.549374
2399  0.575670
2400  0.558965
2401  0.607716

[2402 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2377  0.471097
2378  0.534247
2379  0.540640
2380  0.443868
2381  0.415350

[2382 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2423  0.185450
2424  0.183424
2425  0.200087
2426  0.222525
2427  0.234776

[2428 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2124  1.287896
2125  1.276160
2126  1.324845
2127  1.306783
2128  1.306455

[2129 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2509 -0.399117
2510 -0.423965
2511 -0.422095
2512 -0.484100
2513 -0.386546

[2514 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2502  0.561913
2503  0.552463
2504  0.555934
2505  0.546176
2506  0.540602

[2507 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2438  0.504697
2439  0.491941
2440  0.514753
2441  0.688699
2442  0.691252

[2443 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1948  0.950259
1949  0.926934
1950  0.910365
1951  0.835945
1952  0.836959

[1953 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2405  0.610941
2406  0.582078
2407  0.599808
2408  0.532148
2409  0.555923

[2410 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2092  1.210612
2093  1.294481
2094  1.282774
2095  1.281862
2096  1.269510

[2097 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2538  0.647867
2539  0.631013
2540  0.652676
2541  0.595865
2542  0.589952

[2543 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2538  0.818987
2539  0.803682
2540  0.813828
2541  0.774550
2542  0.817240

[2543 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2509  0.344812
2510  0.251163
2511  0.241815
2512  0.161031
2513  0.152001

[2514 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2457  0.539864
2458  0.549377
2459  0.554904
2460  0.587290
2461  0.599644

[2462 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2148  0.606485
2149  0.657820
2150  0.611627
2151  0.635668
2152  0.626521

[2153 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2539  2.083043
2540  2.097394
2541  2.116372
2542  2.069214
2543  2.061257

[2544 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2189  2.115469
2190  2.085514
2191  2.090777
2192  2.078926
2193  2.027273

[2194 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1375  1.088267
1376  1.076210
1377  1.082384
1378  1.035234
1379  0.990377

[1380 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2286  1.022820
2287  1.041274
2288  1.076439
2289  1.102989
2290  1.152662

[2291 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2524  0.699643
2525  0.680458
2526  0.680834
2527  0.685841
2528  0.686058

[2529 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2155  0.922319
2156  0.913271
2157  0.937748
2158  0.951497
2159  0.979349

[2160 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2534  0.964749
2535  0.906946
2536  0.889149
2537  0.765459
2538  0.737541

[2539 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2433  1.257789
2434  1.254434
2435  1.289871
2436  1.370470
2437  1.351427

[2438 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2070  0.724942
2071  0.686667
2072  0.704221
2073  0.817855
2074  0.816519

[2075 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2396  0.692324
2397  0.664083
2398  0.669911
2399  0.663261
2400  0.653193

[2401 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2269  1.028528
2270  1.057226
2271  1.071049
2272  1.095889
2273  1.066844

[2274 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2489  1.165487
2490  1.249588
2491  1.283394
2492  1.238910
2493  1.268394

[2494 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2506  0.898431
2507  0.909467
2508  0.939582
2509  0.835643
2510  0.983396

[2511 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2541  0.535265
2542  0.521921
2543  0.535952
2544  0.501160
2545  0.466399

[2546 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2245  0.466577
2246  0.529144
2247  0.495032
2248  0.398686
2249  0.385718

[2250 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2531  0.601804
2532  0.591992
2533  0.624719
2534  0.664802
2535  0.712706

[2536 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2535  0.752852
2536  0.742827
2537  0.757150
2538  0.812481
2539  0.826402

[2540 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2409  1.215686
2410  1.366134
2411  1.381545
2412  1.536870
2413  1.498555

[2414 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2529  0.755607
2530  0.747375
2531  0.721297
2532  0.708143
2533  0.700281

[2534 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2242  0.608314
2243  0.660470
2244  0.661229
2245  0.587755
2246  0.562153

[2247 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2190  1.449765
2191  1.429599
2192  1.428469
2193  1.431085
2194  1.408313

[2195 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2311  0.465547
2312  0.419723
2313  0.422491
2314  0.398583
2315  0.371250

[2316 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2192  1.362766
2193  1.316228
2194  1.305060
2195  1.179174
2196  1.156749

[2197 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1983  1.353234
1984  1.393289
1985  1.356034
1986  1.415144
1987  1.442460

[1988 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2524  0.592780
2525  0.559002
2526  0.561301
2527  0.582107
2528  0.584745

[2529 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2401  0.544368
2402  0.594853
2403  0.571644
2404  0.686650
2405  0.706342

[2406 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2424  1.035131
2425  1.014308
2426  0.997299
2427  0.940143
2428  0.939090

[2429 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2366  1.150201
2367  1.186269
2368  1.175602
2369  1.288375
2370  1.341375

[2371 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2416  0.694385
2417  0.696771
2418  0.701811
2419  0.830980
2420  0.818368

[2421 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2335  0.517671
2336  0.341875
2337  0.295785
2338  0.412230
2339  0.496160

[2340 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2534  0.348364
2535  0.388129
2536  0.395907
2537  0.371521
2538  0.502903

[2539 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2503  0.001125
2504  0.578836
2505  0.572092
2506  0.554204
2507  0.583917

[2508 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2524  0.370391
2525  0.328852
2526  0.353079
2527  0.368931
2528  0.381737

[2529 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2512  0.823772
2513  0.829470
2514  0.937572
2515  0.915880
2516  0.879393

[2517 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2423  1.026213
2424  1.005181
2425  1.024695
2426  1.009730
2427  1.009520

[2428 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2472  0.926728
2473  0.862586
2474  0.870802
2475  0.726509
2476  0.732520

[2477 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2301  2.168745
2302  2.163780
2303  2.161317
2304  1.933745
2305  1.937771

[2306 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2171  0.394038
2172  0.373373
2173  0.397068
2174  0.354235
2175  0.347528

[2176 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2307  1.590909
2308  1.563983
2309  1.573842
2310  1.533401
2311  1.515100

[2312 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2299  0.921095
2300  0.917113
2301  0.943589
2302  0.899237
2303  0.940547

[2304 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2307  0.617554
2308  0.597711
2309  0.630731
2310  0.669000
2311  0.707618

[2312 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2417  1.562308
2418  1.551064
2419  1.600046
2420  1.782455
2421  1.815171

[2422 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2416  1.177260
2417  1.116373
2418  1.112760
2419  0.880243
2420  0.867556

[2421 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2102  0.353336
2103  0.364825
2104  0.291198
2105  0.167318
2106  0.154590

[2107 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2278  0.473221
2279  0.473504
2280  0.534557
2281  0.598405
2282  0.677831

[2283 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2399  0.874864
2400  0.986644
2401  0.992297
2402  1.107858
2403  1.116665

[2404 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2308  0.807585
2309  0.836764
2310  0.730320
2311  0.640837
2312  0.749922

[2313 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2287  1.383270
2288  1.389363
2289  1.405368
2290  1.381547
2291  1.397734

[2292 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2406  0.846657
2407  0.844762
2408  0.896300
2409  0.903266
2410  0.884294

[2411 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2490  0.786774
2491  0.781533
2492  0.791227
2493  0.757382
2494  0.841153

[2495 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2146  0.751047
2147  0.713947
2148  0.738571
2149  0.667303
2150  0.823941

[2151 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1624  0.958446
1625  0.939918
1626  0.933682
1627  0.901535
1628  0.884883

[1629 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2530  0.683407
2531  0.735336
2532  0.753952
2533  0.769628
2534  0.775832

[2535 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2442  0.805950
2443  0.726107
2444  0.742203
2445  0.776447
2446  0.772345

[2447 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2368  0.952423
2369  0.933450
2370  0.949007
2371  0.870876
2372  0.860394

[2373 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2413  0.564928
2414  0.537185
2415  0.544571
2416  0.629396
2417  0.622932

[2418 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2164  0.790586
2165  0.781490
2166  0.787901
2167  0.662131
2168  0.662301

[2169 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2046  0.895714
2047  0.889796
2048  0.907429
2049  0.879918
2050  0.884331

[2051 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2376  0.575555
2377  0.552667
2378  0.522377
2379  0.496973
2380  0.542219

[2381 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2537  0.197761
2538  0.282201
2539  0.289665
2540  0.215190
2541  0.220627

[2542 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2534  1.144416
2535  1.132599
2536  1.135508
2537  1.112462
2538  1.120992

[2539 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2079  1.453953
2080  1.448947
2081  1.468836
2082  1.539743
2083  1.512284

[2084 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2452  0.611980
2453  0.601596
2454  0.624325
2455  0.773288
2456  0.804688

[2457 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2366  2.321103
2367  2.291338
2368  2.273328
2369  2.129672
2370  2.066132

[2371 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2531  1.266541
2532  1.266309
2533  1.280706
2534  1.260348
2535  1.244275

[2536 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2174  1.355751
2175  1.338977
2176  1.316934
2177  1.269497
2178  1.241493

[2179 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2407  0.750903
2408  0.873359
2409  0.844763
2410  1.172656
2411  1.120446

[2412 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2461  0.685970
2462  0.745070
2463  0.723796
2464  0.666523
2465  0.676852

[2466 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2376  0.548157
2377  0.531312
2378  0.543330
2379  0.521875
2380  0.535407

[2381 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2370  0.784922
2371  0.742923
2372  0.741821
2373  0.997112
2374  0.979141

[2375 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2429  1.105778
2430  1.107005
2431  1.191996
2432  1.062200
2433  1.037255

[2434 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2461  0.545520
2462  0.559576
2463  0.559833
2464  0.620869
2465  0.781776

[2466 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1697  0.646687
1698  0.658207
1699  0.669073
1700  0.609325
1701  0.615672

[1702 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2398  1.009160
2399  0.991739
2400  0.986890
2401  0.952438
2402  0.912858

[2403 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2491  0.814943
2492  0.851168
2493  0.849721
2494  0.893233
2495  0.834364

[2496 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2190  1.694608
2191  1.795817
2192  1.802356
2193  1.843643
2194  1.720430

[2195 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2352  0.134791
2353  0.007368
2354  0.014899
2355 -0.001229
2356 -0.090573

[2357 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2326  0.796283
2327  0.819655
2328  0.842942
2329  0.746108
2330  0.711908

[2331 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2259  0.875994
2260  0.837346
2261  0.858717
2262  0.812445
2263  0.805896

[2264 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2524  0.393128
2525  0.376903
2526  0.379087
2527  0.365138
2528  0.379114

[2529 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2212  0.607743
2213  0.558661
2214  0.544144
2215  0.551125
2216  0.541629

[2217 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2311  1.153013
2312  1.038568
2313  0.993377
2314  0.926583
2315  0.865489

[2316 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1412  0.551618
1413  0.409562
1414  0.398299
1415  0.433369
1416  0.418141

[1417 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2471  0.720794
2472  0.700882
2473  0.751159
2474  0.816044
2475  0.974514

[2476 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1637  1.085419
1638  1.043211
1639  1.076730
1640  1.064144
1641  1.155582

[1642 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2219  1.558874
2220  1.487361
2221  1.507129
2222  1.547128
2223  1.526520

[2224 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2231  1.859804
2232  1.846666
2233  1.836239
2234  1.703746
2235  1.645848

[2236 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1946  0.593069
1947  0.580086
1948  0.584951
1949  0.549712
1950  0.542368

[1951 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2381  0.458179
2382  0.450796
2383  0.429189
2384  0.382525
2385  0.356587

[2386 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2392  1.138026
2393  1.173081
2394  1.081106
2395  1.070930
2396  0.983168

[2397 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2534  1.174207
2535  1.163273
2536  1.160291
2537  1.135382
2538  1.150614

[2539 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1640  0.823041
1641  0.759330
1642  0.803951
1643  0.713618
1644  0.704760

[1645 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2330  1.443947
2331  1.367550
2332  1.370667
2333  1.260459
2334  1.248727

[2335 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2413  0.969106
2414  0.978878
2415  0.974176
2416  0.983258
2417  0.996342

[2418 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2513  0.507527
2514  0.504552
2515  0.516578
2516  0.496579
2517  0.505309

[2518 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2523  1.286567
2524  1.272264
2525  1.314714
2526  1.359471
2527  1.369084

[2528 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2329  2.065783
2330  2.077672
2331  2.112316
2332  2.030247
2333  2.030751

[2334 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1475  0.615689
1476  0.615963
1477  0.605469
1478  0.581010
1479  0.557719

[1480 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2489  0.442560
2490  0.428633
2491  0.418539
2492  0.409229
2493  0.405165

[2494 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2285  1.086880
2286  1.109507
2287  1.033981
2288  0.809869
2289  0.840154

[2290 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2454  0.687673
2455  0.694377
2456  0.684884
2457  0.657832
2458  0.647934

[2459 rows x 1 columns]
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2259  0.363617
2260  0.357789
2261  0.365871
2262  0.237728
2263  0.206155

[2264 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2218  1.001021
2219  0.987219
2220  0.889831
2221  0.805275
2222  0.738759

[2223 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2437  0.876309
2438  0.870682
2439  0.901100
2440  0.833526
2441  0.818626

[2442 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2416  2.122866
2417  2.171565
2418  2.177889
2419  2.234724
2420  2.336808

[2421 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2512  1.481454
2513  1.472386
2514  1.460353
2515  1.469390
2516  1.435256

[2517 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2540  1.412299
2541  1.476422
2542  1.473222
2543  1.518425
2544  1.472461

[2545 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2426  0.720846
2427  0.713253
2428  0.728183
2429  0.859002
2430  0.825755

[2431 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2510  0.446684
2511  0.458233
2512  0.450997
2513  0.419201
2514  0.421610

[2515 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2411  0.504828
2412  0.529685
2413  0.513452
2414  0.541563
2415  0.530351

[2416 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2427  0.581806
2428  0.587466
2429  0.626143
2430  0.514810
2431  0.504671

[2432 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2480  0.622009
2481  0.617752
2482  0.631505
2483  0.634567
2484  0.642365

[2485 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2238  1.280345
2239  1.350957
2240  1.340144
2241  1.114005
2242  1.023326

[2243 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2049  0.913960
2050  0.976843
2051  0.993687
2052  1.096556
2053  1.096447

[2054 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2286  1.003819
2287  0.990646
2288  1.023883
2289  1.124968
2290  1.121840

[2291 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2390  0.818081
2391  0.928845
2392  0.885650
2393  1.099063
2394  1.077734

[2395 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2316  0.550493
2317  0.577048
2318  0.556183
2319  0.869038
2320  0.951072

[2321 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2071  1.696052
2072  1.749259
2073  1.710331
2074  1.827772
2075  1.799678

[2076 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2445  0.751303
2446  0.730792
2447  0.755092
2448  0.802861
2449  0.824210

[2450 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2376  0.516043
2377  0.489050
2378  0.482651
2379  0.450262
2380  0.489784

[2381 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1860  0.649809
1861  0.639966
1862  0.644776
1863  0.584734
1864  0.581554

[1865 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2278  0.951797
2279  0.924098
2280  0.926314
2281  0.817636
2282  0.858211

[2283 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2442  1.483876
2443  1.434018
2444  1.463069
2445  1.309565
2446  1.304478

[2447 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2020  0.800923
2021  0.802804
2022  0.814816
2023  0.767097
2024  0.762370

[2025 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2235  1.049852
2236  1.028305
2237  1.032770
2238  0.979230
2239  0.970713

[2240 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2528  1.596910
2529  1.578559
2530  1.537885
2531  1.422737
2532  1.386655

[2533 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2505  0.553403
2506  0.568730
2507  0.595461
2508  0.559771
2509  0.576178

[2510 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2411  0.739080
2412  0.732355
2413  0.644288
2414  0.602639
2415  0.554873

[2416 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2513  1.166121
2514  1.148888
2515  1.205550
2516  1.254660
2517  1.268181

[2518 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2535  0.705664
2536  0.699652
2537  0.684138
2538  0.694252
2539  0.705777

[2540 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2538  1.025480
2539  1.046986
2540  1.028104
2541  1.117178
2542  1.080501

[2543 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2315  1.439406
2316  1.452867
2317  1.478544
2318  1.420479
2319  1.392484

[2320 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2508  2.117352
2509  2.112766
2510  2.097792
2511  2.005258
2512  1.942765

[2513 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2517  0.605879
2518  0.676611
2519  0.705983
2520  0.718268
2521  0.695675

[2522 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2445  0.906014
2446  0.886502
2447  0.917109
2448  0.962460
2449  1.117703

[2450 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2485  0.679290
2486  0.660367
2487  0.661821
2488  0.634582
2489  0.623173

[2490 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2505  0.983164
2506  0.963633
2507  0.947120
2508  0.890154
2509  0.900657

[2510 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2438  1.185349
2439  1.184484
2440  1.168810
2441  1.379183
2442  1.328296

[2443 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2102  1.099707
2103  1.084469
2104  1.129631
2105  1.180745
2106  1.192965

[2107 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2156  0.797454
2157  0.825579
2158  0.834276
2159  0.790946
2160  0.805359

[2161 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2442  0.192017
2443  0.182664
2444  0.163570
2445  0.130099
2446  0.144011

[2447 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2503  0.953233
2504  0.956200
2505  0.958900
2506  0.939479
2507  0.946546

[2508 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2169  0.626201
2170  0.598236
2171  0.593482
2172  0.560685
2173  0.556015

[2174 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2477  1.349738
2478  1.474018
2479  1.465959
2480  1.386901
2481  1.358483

[2482 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1506  0.363909
1507  0.370441
1508  0.266118
1509  0.352884
1510  0.282758

[1511 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2501  0.775929
2502  0.821362
2503  0.821383
2504  0.767617
2505  0.811078

[2506 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2386  0.441652
2387  0.538597
2388  0.534984
2389  0.646036
2390  0.657549

[2391 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2200  0.151918
2201  0.129547
2202  0.080562
2203  0.077866
2204  0.038703

[2205 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2490  0.582591
2491  0.583450
2492  0.592648
2493  0.624653
2494  0.643729

[2495 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2464  0.767152
2465  0.756606
2466  0.712012
2467  0.660501
2468  0.634203

[2469 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2108  0.710517
2109  0.734533
2110  0.722130
2111  0.686712
2112  0.662197

[2113 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2392  0.615988
2393  0.609616
2394  0.613953
2395  0.600082
2396  0.588357

[2397 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2513  1.031359
2514  0.997058
2515  0.997542
2516  1.015155
2517  1.053847

[2518 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2497  0.961325
2498  0.956400
2499  0.995433
2500  1.020676
2501  1.061735

[2502 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2511  0.817073
2512  0.808210
2513  0.824043
2514  0.775771
2515  0.899264

[2516 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2468  0.572325
2469  0.562419
2470  0.560107
2471  0.538743
2472  0.540389

[2473 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2349  0.333152
2350  0.308114
2351  0.339912
2352  0.492181
2353  0.501939

[2354 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2529  0.845898
2530  0.893702
2531  0.884678
2532  0.924756
2533  0.878439

[2534 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2425  0.584441
2426  0.606575
2427  0.621359
2428  0.592111
2429  0.554807

[2430 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2519  0.968433
2520  0.966223
2521  1.023168
2522  1.042781
2523  1.059425

[2524 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2360  0.715158
2361  0.756272
2362  0.779453
2363  0.779514
2364  0.769868

[2365 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2393  1.176820
2394  1.120129
2395  1.121213
2396  1.095182
2397  1.182560

[2398 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2389  0.792125
2390  0.791709
2391  0.772141
2392  0.747992
2393  0.705879

[2394 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2528  0.815223
2529  0.835996
2530  0.877189
2531  0.916137
2532  0.991547

[2533 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2447  0.838498
2448  0.941789
2449  0.920372
2450  0.954230
2451  0.964159

[2452 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2469  1.014227
2470  0.938670
2471  0.931502
2472  0.783881
2473  0.784016

[2474 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2433  0.582244
2434  0.604178
2435  0.612067
2436  0.609467
2437  0.656795

[2438 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2112  0.821738
2113  0.961289
2114  0.941445
2115  0.990271
2116  1.034049

[2117 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2386  0.718734
2387  0.777807
2388  0.775186
2389  0.800667
2390  0.795453

[2391 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2077  1.430438
2078  1.404338
2079  1.438236
2080  1.431508
2081  1.562619

[2082 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2509  0.791045
2510  0.818679
2511  0.892701
2512  0.832537
2513  0.820405

[2514 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2423  1.275885
2424  1.403423
2425  1.393996
2426  1.485089
2427  1.461411

[2428 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2434  0.949074
2435  0.951970
2436  0.838506
2437  0.879948
2438  1.005372

[2439 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2510  0.720227
2511  0.727003
2512  0.739300
2513  0.760291
2514  0.745419

[2515 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2495  0.948784
2496  0.946000
2497  0.934450
2498  0.882419
2499  0.851780

[2500 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2365  0.888069
2366  0.856537
2367  0.819141
2368  0.769594
2369  0.937353

[2370 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2241  0.268823
2242  0.405952
2243  0.453118
2244  0.480682
2245  0.466848

[2246 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2150  0.258335
2151  0.182343
2152  0.202028
2153  0.192882
2154  0.040160

[2155 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2430  0.829530
2431  0.802404
2432  0.837865
2433  0.777368
2434  0.823277

[2435 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2528  0.723295
2529  0.695689
2530  0.714969
2531  0.682307
2532  0.702293

[2533 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2179  2.299182
2180  2.266011
2181  2.250489
2182  2.112958
2183  2.076747

[2184 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2445  0.924859
2446  0.905255
2447  0.883140
2448  0.750397
2449  0.817075

[2450 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2234  0.912837
2235  0.901860
2236  0.909664
2237  0.890005
2238  0.880918

[2239 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2222  0.643008
2223  0.613243
2224  0.640167
2225  0.576389
2226  0.524148

[2227 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2185  1.578699
2186  1.514089
2187  1.541318
2188  1.425783
2189  1.412239

[2190 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2430  0.596922
2431  0.577696
2432  0.578010
2433  0.508822
2434  0.526097

[2435 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2093  2.428088
2094  2.427648
2095  2.461024
2096  2.355040
2097  2.316908

[2098 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2537  0.874589
2538  0.850928
2539  0.912164
2540  1.005474
2541  0.965102

[2542 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1627  1.252928
1628  1.249609
1629  1.165206
1630  1.167059
1631  1.207727

[1632 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2341  0.857189
2342  0.845709
2343  0.845127
2344  0.987552
2345  0.970956

[2346 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2534  0.588965
2535  0.596724
2536  0.591730
2537  0.559951
2538  0.562276

[2539 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2537  2.254269
2538  2.245924
2539  2.198655
2540  2.131822
2541  2.064628

[2542 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2431  0.915348
2432  0.908681
2433  0.928647
2434  0.921863
2435  0.921245

[2436 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2463  1.257779
2464  1.254626
2465  1.249272
2466  1.195300
2467  1.203111

[2468 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2467  0.424572
2468  0.411788
2469  0.429160
2470  0.400331
2471  0.404891

[2472 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2284  1.460671
2285  1.464359
2286  1.484107
2287  1.456844
2288  1.383981

[2289 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2535  0.865389
2536  0.881555
2537  0.884979
2538  0.973064
2539  0.984429

[2540 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2063  0.258679
2064  0.294288
2065  0.294511
2066  0.265517
2067  0.268599

[2068 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2344  0.994483
2345  1.075824
2346  1.044557
2347  1.195669
2348  1.161422

[2349 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2237  1.365133
2238  1.502543
2239  1.536144
2240  1.384954
2241  1.163160

[2242 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2270  1.579488
2271  1.521811
2272  1.540911
2273  1.382070
2274  1.374985

[2275 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2465  0.681273
2466  0.713111
2467  0.682014
2468  0.618387
2469  0.437071

[2470 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2413  0.768069
2414  0.734970
2415  0.770869
2416  0.745182
2417  0.772792

[2418 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2410  1.565845
2411  1.567685
2412  1.584353
2413  1.568213
2414  1.563666

[2415 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2540  0.735703
2541  0.772514
2542  0.753373
2543  0.879761
2544  0.915229

[2545 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2384  1.166339
2385  1.154272
2386  1.152955
2387  1.113535
2388  1.099785

[2389 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2335  2.038681
2336  1.924127
2337  1.819813
2338  1.655202
2339  1.627051

[2340 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2457  1.133732
2458  1.211224
2459  1.201248
2460  1.098775
2461  1.090981

[2462 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2517  0.816215
2518  0.913068
2519  0.942610
2520  1.086357
2521  1.087691

[2522 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2480  1.246209
2481  1.253735
2482  1.266899
2483  1.240170
2484  1.314701

[2485 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2520  1.271082
2521  1.244924
2522  1.228457
2523  1.113923
2524  1.084562

[2525 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2499  0.712800
2500  0.752191
2501  0.796162
2502  0.947489
2503  0.982260

[2504 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2431 -0.051809
2432 -0.041530
2433  0.057550
2434  0.228267
2435  0.199600

[2436 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2227  1.190666
2228  1.175980
2229  1.141570
2230  1.022664
2231  0.988427

[2232 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1792  0.397695
1793  0.374090
1794  0.384175
1795  0.410936
1796  0.391859

[1797 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2438  0.248181
2439  0.228008
2440  0.179169
2441  0.180094
2442  0.363885

[2443 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2530  0.447784
2531  0.465107
2532  0.448615
2533  0.460748
2534  0.475810

[2535 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2420  1.133764
2421  1.144553
2422  1.097066
2423  0.896362
2424  0.899075

[2425 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2357  0.306908
2358  0.354398
2359  0.306969
2360  0.446242
2361  0.517449

[2362 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2503  0.867568
2504  0.816992
2505  0.840432
2506  0.914917
2507  1.022173

[2508 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2389  1.195046
2390  1.188888
2391  1.158024
2392  1.125504
2393  1.229386

[2394 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2537  0.519277
2538  0.507766
2539  0.448250
2540  0.444176
2541  0.415839

[2542 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2369  0.829612
2370  0.839768
2371  0.878060
2372  0.736887
2373  0.738228

[2374 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2425  0.905572
2426  0.875515
2427  0.881610
2428  0.887245
2429  0.881742

[2430 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2402  0.396421
2403  0.402691
2404  0.403660
2405  0.419480
2406  0.427224

[2407 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2455  0.803610
2456  0.802903
2457  0.782222
2458  0.714388
2459  0.701805

[2460 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2536  1.046417
2537  1.116784
2538  1.121168
2539  1.114860
2540  1.124108

[2541 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2319  0.704963
2320  0.893377
2321  0.964870
2322  0.984938
2323  0.978951

[2324 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2534  0.683567
2535  0.724776
2536  0.743697
2537  0.636218
2538  0.645268

[2539 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2106  2.124427
2107  2.258505
2108  2.227319
2109  2.088882
2110  2.096896

[2111 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2360  1.007977
2361  0.992056
2362  1.008169
2363  1.014685
2364  0.903786

[2365 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2234  1.155085
2235  1.202983
2236  1.217881
2237  1.198265
2238  1.184138

[2239 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2248  0.759677
2249  0.822983
2250  0.829066
2251  0.916803
2252  0.896133

[2253 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2326  0.669380
2327  0.631878
2328  0.598058
2329  0.634194
2330  0.669422

[2331 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2514  0.655410
2515  0.845689
2516  0.845860
2517  0.867674
2518  0.775951

[2519 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2534  0.666399
2535  0.654874
2536  0.684255
2537  0.729741
2538  0.748515

[2539 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2476  0.332389
2477  0.330388
2478  0.339602
2479  0.294291
2480  0.293185

[2481 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2354  0.560437
2355  0.543442
2356  0.527304
2357  0.501195
2358  0.505894

[2359 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2394  1.117917
2395  1.119663
2396  1.102601
2397  1.084760
2398  1.070690

[2399 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2402  1.101559
2403  1.139174
2404  1.128095
2405  1.273989
2406  1.220162

[2407 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2373  1.855464
2374  1.960690
2375  2.036574
2376  1.980611
2377  1.913479

[2378 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2497  1.153410
2498  1.139567
2499  1.158243
2500  1.185979
2501  1.189906

[2502 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2409  0.735440
2410  0.738328
2411  0.746878
2412  0.776292
2413  0.722273

[2414 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2394  0.193814
2395  0.243484
2396  0.217415
2397  0.179442
2398  0.207279

[2399 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2513  1.666805
2514  1.634611
2515  1.497594
2516  1.443627
2517  1.226230

[2518 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2521  1.469867
2522  1.454637
2523  1.468077
2524  1.373450
2525  1.372706

[2526 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2483  0.399109
2484  0.222644
2485  0.258231
2486  0.272569
2487  0.344989

[2488 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2173  0.745906
2174  0.753896
2175  0.778598
2176  0.948905
2177  0.930472

[2178 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2497  0.705189
2498  0.694619
2499  0.669804
2500  0.631057
2501  0.570993

[2502 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2541  0.840083
2542  0.838674
2543  0.869373
2544  0.993197
2545  0.911288

[2546 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2236  0.599173
2237  0.594072
2238  0.626553
2239  0.570640
2240  0.552009

[2241 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2483  0.851932
2484  0.830098
2485  0.888226
2486  0.755878
2487  0.781966

[2488 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2541  0.501949
2542  0.528583
2543  0.527252
2544  0.495100
2545  0.473476

[2546 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2329  0.632369
2330  0.606073
2331  0.502603
2332  0.376606
2333  0.382993

[2334 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2517  1.242617
2518  1.220456
2519  1.248195
2520  1.278661
2521  1.250354

[2522 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2390  1.148376
2391  1.101316
2392  1.114302
2393  1.067976
2394  1.073282

[2395 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2391  0.680964
2392  0.667037
2393  0.711734
2394  0.798414
2395  0.798164

[2396 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2286  1.078032
2287  1.033755
2288  1.050154
2289  1.140634
2290  1.099170

[2291 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2498  0.626928
2499  0.613783
2500  0.629863
2501  0.631288
2502  0.669240

[2503 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2451  0.689710
2452  0.700563
2453  0.669596
2454  0.273112
2455  0.025765

[2456 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2433  0.735501
2434  0.704726
2435  0.712081
2436  0.735106
2437  0.732825

[2438 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2405  0.761220
2406  0.752129
2407  0.783367
2408  0.794345
2409  0.819581

[2410 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2394  0.857031
2395  0.902072
2396  0.864903
2397  1.000688
2398  0.990000

[2399 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2462  1.255560
2463  1.249480
2464  1.367858
2465  1.030746
2466  0.986980

[2467 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2370  0.539036
2371  0.522287
2372  0.543688
2373  0.554372
2374  0.572067

[2375 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2516  0.605003
2517  0.580694
2518  0.607489
2519  0.643471
2520  0.666514

[2521 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2265  0.726204
2266  0.716199
2267  0.725443
2268  0.671901
2269  0.693788

[2270 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2489  1.405956
2490  1.390650
2491  1.444873
2492  1.324972
2493  1.217979

[2494 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2529  0.657462
2530  0.646266
2531  0.660321
2532  0.653926
2533  0.671324

[2534 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2333  1.461539
2334  1.486105
2335  1.489416
2336  1.507516
2337  1.506061

[2338 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1942  0.774570
1943  0.724477
1944  0.711841
1945  0.686835
1946  0.676661

[1947 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2431  1.340346
2432  1.347346
2433  1.373309
2434  1.374083
2435  1.307571

[2436 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2506  0.877624
2507  0.898016
2508  0.886354
2509  0.996174
2510  0.982890

[2511 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1940  0.555814
1941  0.553946
1942  0.550413
1943  0.510209
1944  0.502999

[1945 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2540  0.906221
2541  0.937412
2542  0.927562
2543  1.061317
2544  1.009309

[2545 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2419  0.511361
2420  0.521746
2421  0.539851
2422  0.565763
2423  0.571648

[2424 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2288  0.495077
2289  0.455986
2290  0.424279
2291  0.638576
2292  0.632792

[2293 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2410  0.736278
2411  0.691111
2412  0.669576
2413  0.818419
2414  0.812695

[2415 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2522  1.282258
2523  1.256431
2524  1.253091
2525  1.280747
2526  1.262243

[2527 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2430  0.853116
2431  0.845416
2432  0.869338
2433  0.806514
2434  0.782357

[2435 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2168  0.414888
2169  0.395082
2170  0.403976
2171  0.365833
2172  0.411760

[2173 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2433  0.969264
2434  0.966258
2435  0.985860
2436  0.977013
2437  1.010249

[2438 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2505  0.685609
2506  0.652816
2507  0.671480
2508  0.710007
2509  0.820213

[2510 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2360  0.924147
2361  0.948537
2362  0.953323
2363  0.847254
2364  0.845279

[2365 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2497  0.904657
2498  0.916433
2499  0.887654
2500  0.947830
2501  0.960041

[2502 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2532  0.622305
2533  0.597865
2534  0.617754
2535  0.583313
2536  0.624242

[2537 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2522  0.501687
2523  0.470557
2524  0.462246
2525  0.436407
2526  0.453396

[2527 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2315  0.434343
2316  0.444670
2317  0.436832
2318  0.443597
2319  0.397846

[2320 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2325  0.846344
2326  0.875549
2327  0.869944
2328  0.837762
2329  0.829896

[2330 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2447  1.396879
2448  1.415975
2449  1.389829
2450  1.513267
2451  1.471852

[2452 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2526  0.565929
2527  0.576439
2528  0.608043
2529  0.661171
2530  0.650944

[2531 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2263  0.665571
2264  0.648487
2265  0.690622
2266  0.539717
2267  0.503990

[2268 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2195  0.467686
2196  0.511666
2197  0.459225
2198  0.440613
2199  0.411869

[2200 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2409  1.274565
2410  1.249965
2411  1.254982
2412  1.225566
2413  1.204407

[2414 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2214  0.644725
2215  0.719555
2216  0.707021
2217  0.531088
2218  0.528266

[2219 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2286  1.234773
2287  1.214110
2288  1.187794
2289  1.354674
2290  1.341995

[2291 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2461  1.807023
2462  1.779513
2463  1.843600
2464  1.935709
2465  1.822394

[2466 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2468  0.940221
2469  0.908629
2470  0.908001
2471  0.774521
2472  0.786583

[2473 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1850  0.919989
1851  0.928331
1852  0.852074
1853  0.795433
1854  0.725243

[1855 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2379  1.472133
2380  1.189424
2381  1.222450
2382  1.074938
2383  1.025837

[2384 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1804 -0.073079
1805 -0.141966
1806 -0.161901
1807 -0.208742
1808 -0.268962

[1809 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1938  0.704854
1939  0.718310
1940  0.724249
1941  0.580606
1942  0.557417

[1943 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2536  0.618174
2537  0.611179
2538  0.607542
2539  0.613506
2540  0.620499

[2541 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2537  0.656843
2538  0.671036
2539  0.716115
2540  0.710432
2541  0.683568

[2542 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2359  0.431050
2360  0.406076
2361  0.481581
2362  0.851773
2363  0.864785

[2364 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2529  1.779998
2530  1.744164
2531  1.745806
2532  1.568521
2533  1.567730

[2534 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2434  0.508224
2435  0.519921
2436  0.531216
2437  0.651995
2438  0.649768

[2439 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2330  1.266795
2331  1.237397
2332  1.256929
2333  1.267470
2334  1.363455

[2335 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2522  0.600282
2523  0.640326
2524  0.658337
2525  0.667404
2526  0.670008

[2527 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1809  0.652100
1810  0.727524
1811  0.771900
1812  0.711264
1813  0.639290

[1814 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2170  1.712220
2171  1.714440
2172  1.742572
2173  1.771868
2174  1.762280

[2175 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2389  1.504557
2390  1.483704
2391  1.481772
2392  1.406235
2393  1.375634

[2394 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2376  0.882104
2377  0.951664
2378  0.923856
2379  1.128064
2380  1.090134

[2381 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2464  0.748140
2465  0.771177
2466  0.769610
2467  0.785824
2468  0.801188

[2469 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2387  0.704522
2388  0.676636
2389  0.562204
2390  0.656662
2391  0.630509

[2392 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
360  0.366282
361  0.381348
362  0.397662
363  0.312279
364  0.273423

[365 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2410  0.834286
2411  0.825609
2412  0.832069
2413  0.750814
2414  0.750506

[2415 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
125  1.022142
126  1.039407
127  1.020081
128  0.930203
129  0.904702

[130 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
605  0.579059
606  0.551697
607  0.568753
608  0.550384
609  0.577683

[610 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1085  0.734487
1086  0.724798
1087  0.675688
1088  0.567747
1089  0.633042

[1090 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2520  1.139114
2521  1.204117
2522  1.156530
2523  1.354658
2524  1.315331

[2525 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2235  0.866281
2236  0.835269
2237  0.819748
2238  0.972967
2239  0.960025

[2240 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2436  0.460955
2437  0.439702
2438  0.467793
2439  0.398222
2440  0.391783

[2441 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2379  0.306385
2380  0.292032
2381  0.262632
2382  0.316042
2383  0.291684

[2384 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2258  0.314349
2259  0.328538
2260  0.399725
2261  0.432558
2262  0.428750

[2263 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2186  1.046951
2187  1.081396
2188  1.036142
2189  0.975252
2190  0.939519

[2191 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2526  0.599729
2527  0.664892
2528  0.596021
2529  0.523220
2530  0.429905

[2531 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2519  1.810381
2520  1.778547
2521  1.752780
2522  1.743081
2523  1.741892

[2524 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2390  0.957077
2391  0.924647
2392  0.942189
2393  0.893436
2394  0.905370

[2395 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2394  0.709383
2395  0.743522
2396  0.744692
2397  0.745986
2398  0.748676

[2399 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2360  1.119383
2361  1.064025
2362  1.027010
2363  1.094860
2364  1.082029

[2365 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2193  1.280842
2194  1.323483
2195  1.346438
2196  1.270689
2197  1.254776

[2198 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2394  0.917968
2395  0.886089
2396  0.879371
2397  0.823664
2398  0.816357

[2399 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2433  0.748153
2434  0.718955
2435  0.742571
2436  0.695711
2437  0.682602

[2438 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1998  1.140673
1999  1.143302
2000  1.112608
2001  1.148722
2002  1.127141

[2003 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2474  0.681403
2475  0.658332
2476  0.680172
2477  0.634913
2478  0.690632

[2479 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2506  1.253696
2507  1.242022
2508  1.229050
2509  1.164630
2510  1.149367

[2511 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2037  0.336834
2038  0.500949
2039  0.537827
2040  0.467686
2041  0.370050

[2042 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2427  1.018953
2428  1.053061
2429  1.085065
2430  1.039299
2431  0.957833

[2432 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2433  0.774162
2434  0.798921
2435  0.771023
2436  0.782486
2437  0.767154

[2438 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2205  0.638129
2206  0.658650
2207  0.672002
2208  0.762547
2209  0.752916

[2210 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2507  0.814747
2508  0.912598
2509  0.833425
2510  0.640287
2511  0.566435

[2512 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2525  1.844785
2526  1.845435
2527  1.824501
2528  1.727356
2529  1.675813

[2530 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2523  0.716478
2524  0.717776
2525  0.738767
2526  0.735768
2527  0.734813

[2528 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2346  1.164833
2347  1.151428
2348  1.057077
2349  1.014257
2350  0.906955

[2351 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2418  0.730538
2419  0.713946
2420  0.734807
2421  0.726553
2422  0.713033

[2423 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2439  1.559235
2440  1.554555
2441  1.576476
2442  1.491348
2443  1.521153

[2444 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2538  2.127497
2539  2.055072
2540  1.972621
2541  1.956528
2542  1.915979

[2543 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2522  0.677250
2523  0.670588
2524  0.698046
2525  0.647119
2526  0.651223

[2527 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2480  0.787086
2481  0.877371
2482  0.842259
2483  0.692483
2484  0.597946

[2485 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2478  1.123063
2479  1.102058
2480  1.104940
2481  1.066966
2482  1.042519

[2483 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2534  0.484361
2535  0.515345
2536  0.495641
2537  0.413301
2538  0.428255

[2539 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2438  0.910844
2439  0.901190
2440  0.890171
2441  0.751491
2442  0.762856

[2443 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2402  0.992046
2403  0.988213
2404  1.008872
2405  0.894682
2406  0.885376

[2407 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2478  0.731058
2479  0.724641
2480  0.757014
2481  0.842508
2482  0.869581

[2483 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2427  2.580095
2428  2.564600
2429  2.535978
2430  2.502891
2431  2.445186

[2432 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2352  0.417337
2353  0.406140
2354  0.436059
2355  0.384776
2356  0.407265

[2357 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2534  0.836043
2535  0.855565
2536  0.820895
2537  0.888747
2538  0.857580

[2539 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2539  0.458879
2540  0.468610
2541  0.448189
2542  0.363499
2543  0.345653

[2544 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2398  0.650439
2399  0.617948
2400  0.631569
2401  0.576474
2402  0.582097

[2403 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2538  1.020186
2539  1.111787
2540  1.037881
2541  1.300051
2542  1.295589

[2543 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2518  0.504550
2519  0.518681
2520  0.520377
2521  0.490372
2522  0.508925

[2523 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2419  1.045654
2420  1.077384
2421  1.112594
2422  0.966458
2423  1.027831

[2424 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2235  1.803421
2236  1.915052
2237  1.833967
2238  1.784701
2239  1.758505

[2240 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2485  2.293226
2486  2.226082
2487  2.239069
2488  1.999926
2489  1.944400

[2490 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2443  1.253643
2444  1.218888
2445  1.213596
2446  1.176241
2447  1.174421

[2448 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2295  0.401184
2296  0.495011
2297  0.523243
2298  0.524583
2299  0.563485

[2300 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2423  1.785978
2424  1.761328
2425  1.768137
2426  1.736353
2427  1.754151

[2428 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2260  1.895622
2261  2.064246
2262  2.038303
2263  1.969995
2264  2.095845

[2265 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2420  1.366555
2421  1.328060
2422  1.338201
2423  1.387760
2424  1.352958

[2425 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2342  1.047367
2343  1.027809
2344  1.051072
2345  1.008392
2346  1.009188

[2347 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2261  1.250070
2262  1.104494
2263  1.109992
2264  1.137282
2265  1.055292

[2266 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2274  0.698744
2275  0.706315
2276  0.696570
2277  0.577183
2278  0.601886

[2279 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2515  0.984542
2516  0.991899
2517  0.986214
2518  0.969023
2519  0.951498

[2520 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2441  1.467352
2442  1.441155
2443  1.406741
2444  1.334207
2445  1.321456

[2446 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2529  1.779667
2530  1.768676
2531  1.776492
2532  1.667263
2533  1.655836

[2534 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2297  0.462119
2298  0.480830
2299  0.527114
2300  0.477442
2301  0.493076

[2302 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2500  0.403808
2501  0.498965
2502  0.510463
2503  0.373081
2504  0.338427

[2505 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2195  1.607231
2196  1.553167
2197  1.541566
2198  1.391427
2199  1.387465

[2200 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2503  0.598415
2504  0.584028
2505  0.639214
2506  0.772671
2507  0.775779

[2508 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2293  0.765740
2294  0.752434
2295  0.774965
2296  0.774270
2297  0.770156

[2298 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2517  1.345058
2518  1.274002
2519  1.293524
2520  1.456629
2521  1.485598

[2522 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2447  1.798280
2448  2.003893
2449  1.979449
2450  1.762917
2451  1.695977

[2452 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2525  1.226635
2526  1.216879
2527  1.228389
2528  1.197469
2529  1.214783

[2530 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2229  2.362672
2230  2.389941
2231  2.360464
2232  2.217228
2233  2.158537

[2234 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2540  0.962457
2541  0.914025
2542  0.940740
2543  0.952677
2544  0.955652

[2545 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2525  0.819647
2526  0.801877
2527  0.793155
2528  0.752119
2529  0.751009

[2530 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2518  0.489252
2519  0.488909
2520  0.533097
2521  0.614262
2522  0.616288

[2523 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2369  0.614764
2370  0.686507
2371  0.772963
2372  0.935184
2373  1.089494

[2374 rows x 1 columns]
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2181  1.394302
2182  1.438001
2183  1.475330
2184  1.307889
2185  1.066048

[2186 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2036  0.690883
2037  0.700152
2038  0.720280
2039  0.698884
2040  0.701229

[2041 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2497  1.187609
2498  1.155860
2499  1.172686
2500  1.132836
2501  1.124237

[2502 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2316  1.907302
2317  1.931345
2318  2.069427
2319  2.042982
2320  2.099006

[2321 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1623  2.206032
1624  2.174241
1625  2.188254
1626  1.851063
1627  1.767444

[1628 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2217  1.006556
2218  1.057363
2219  0.997900
2220  0.842782
2221  0.693958

[2222 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2433  1.053950
2434  1.046812
2435  1.046495
2436  1.019652
2437  0.894095

[2438 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2504  1.176990
2505  1.151069
2506  1.099295
2507  1.056483
2508  1.100924

[2509 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2480  1.437079
2481  1.495641
2482  1.525824
2483  1.477136
2484  1.431525

[2485 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2420  1.468206
2421  1.479434
2422  1.490857
2423  1.464814
2424  1.365928

[2425 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2480  0.781461
2481  0.755110
2482  0.779548
2483  0.838439
2484  0.881843

[2485 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2159  0.647858
2160  0.777262
2161  0.740923
2162  0.761678
2163  0.720388

[2164 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2540  0.094020
2541  0.049978
2542  0.074167
2543  0.130334
2544  0.202555

[2545 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2483  1.525819
2484  1.552389
2485  1.524775
2486  1.547689
2487  1.659024

[2488 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2385  0.579523
2386  0.557321
2387  0.521393
2388  0.487113
2389  0.511127

[2390 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2423  0.458269
2424  0.281878
2425  0.250147
2426  0.285127
2427  0.296121

[2428 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2518  0.707323
2519  0.678860
2520  0.675879
2521  0.808035
2522  0.806715

[2523 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2471  0.677038
2472  0.669038
2473  0.666418
2474  0.617203
2475  0.632939

[2476 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2258  0.974142
2259  0.926749
2260  0.995887
2261  0.811893
2262  0.886174

[2263 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2399  1.166194
2400  1.176680
2401  1.090822
2402  1.410906
2403  1.443041

[2404 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2393  1.276764
2394  1.250976
2395  1.274029
2396  1.192895
2397  1.189499

[2398 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2374  0.830670
2375  0.830234
2376  0.834957
2377  0.792849
2378  0.782197

[2379 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2507  1.976936
2508  1.957365
2509  1.922615
2510  1.830567
2511  1.794942

[2512 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2327  0.697754
2328  0.757822
2329  0.800267
2330  0.786290
2331  0.766332

[2332 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2541  1.214229
2542  1.191557
2543  1.216827
2544  1.282172
2545  1.246509

[2546 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2469  0.702870
2470  0.702393
2471  0.712274
2472  0.691476
2473  0.674046

[2474 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2430  1.175164
2431  1.137547
2432  1.154150
2433  1.122053
2434  1.131259

[2435 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2206  1.118088
2207  1.091304
2208  1.058013
2209  1.016457
2210  0.970925

[2211 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2343  0.606907
2344  0.616529
2345  0.598829
2346  0.605992
2347  0.582259

[2348 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2449  0.591866
2450  0.769387
2451  0.704887
2452  0.787248
2453  0.864562

[2454 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2415  1.397118
2416  1.335841
2417  1.348638
2418  1.174629
2419  1.164603

[2420 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2177  0.677353
2178  0.650923
2179  0.658216
2180  0.595131
2181  0.615478

[2182 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2220  1.803203
2221  1.804192
2222  1.785687
2223  1.717319
2224  1.696888

[2225 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2479  2.059017
2480  2.121141
2481  2.091571
2482  2.075804
2483  2.023716

[2484 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2522  1.493796
2523  1.489375
2524  1.374710
2525  1.294630
2526  1.277325

[2527 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2386  1.065899
2387  1.023391
2388  0.985554
2389  1.066955
2390  1.041330

[2391 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2516  0.575284
2517  0.622067
2518  0.590473
2519  0.649517
2520  0.620950

[2521 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2494  1.385707
2495  1.384253
2496  1.370523
2497  1.331394
2498  1.317563

[2499 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2353  0.368452
2354  0.393421
2355  0.387253
2356  0.617296
2357  0.618219

[2358 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2252  0.530907
2253  0.526072
2254  0.558122
2255  0.605781
2256  0.615382

[2257 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2446  1.060294
2447  1.030117
2448  0.988569
2449  1.041839
2450  1.019233

[2451 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2199  1.630003
2200  1.564059
2201  1.498516
2202  1.391244
2203  1.330683

[2204 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2026  1.569579
2027  1.506109
2028  1.469524
2029  1.431618
2030  1.349056

[2031 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2357  0.805936
2358  0.802706
2359  0.788918
2360  0.721444
2361  0.670854

[2362 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2369  1.741869
2370  1.713587
2371  1.712867
2372  1.595272
2373  1.535423

[2374 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2470  0.757342
2471  0.752939
2472  0.771230
2473  0.761068
2474  0.769721

[2475 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2520  1.666586
2521  1.684218
2522  1.733086
2523  1.720201
2524  1.714211

[2525 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2476  1.068673
2477  1.102043
2478  1.102231
2479  1.056609
2480  1.032321

[2481 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2423  1.449901
2424  1.421647
2425  1.422483
2426  1.270724
2427  1.266228

[2428 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2422  0.825890
2423  0.783105
2424  0.786161
2425  0.784751
2426  0.792459

[2427 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2365  0.429268
2366  0.428862
2367  0.407982
2368  0.480813
2369  0.230896

[2370 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2348  0.888147
2349  0.890857
2350  0.884757
2351  0.925087
2352  0.913415

[2353 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2406  1.760799
2407  1.741752
2408  1.770109
2409  1.684795
2410  1.597686

[2411 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2483  0.643693
2484  0.697317
2485  0.570183
2486  0.724141
2487  0.705419

[2488 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2405  2.218484
2406  2.308196
2407  2.346539
2408  2.198130
2409  2.264359

[2410 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2456  1.281212
2457  1.273108
2458  1.286935
2459  1.351808
2460  1.450716

[2461 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2206  0.845958
2207  0.848400
2208  0.960080
2209  1.020055
2210  0.988973

[2211 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2398  0.413315
2399  0.417549
2400  0.440359
2401  0.425004
2402  0.450880

[2403 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2067  1.839967
2068  1.805515
2069  1.764034
2070  1.767575
2071  1.739561

[2072 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2453  1.251473
2454  1.233672
2455  1.240859
2456  1.183106
2457  1.215617

[2458 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2210  1.167581
2211  1.155735
2212  1.185825
2213  1.067268
2214  1.030410

[2215 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2434  0.581946
2435  0.554619
2436  0.573542
2437  0.648694
2438  0.659640

[2439 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2530  0.697175
2531  0.660319
2532  0.673561
2533  0.633164
2534  0.678298

[2535 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2398  0.692302
2399  0.664894
2400  0.702080
2401  0.656475
2402  0.587936

[2403 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2503  1.480638
2504  1.544796
2505  1.532996
2506  1.628642
2507  1.656280

[2508 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2524  0.689629
2525  0.665210
2526  0.667846
2527  0.588247
2528  0.572671

[2529 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2356  1.996317
2357  1.983938
2358  1.972765
2359  1.925845
2360  1.901038

[2361 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2530  1.889462
2531  1.863739
2532  1.889278
2533  1.916717
2534  1.900978

[2535 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2499  1.657248
2500  1.616941
2501  1.608717
2502  1.516759
2503  1.482083

[2504 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2523  0.767551
2524  0.751129
2525  0.753976
2526  0.681639
2527  0.677101

[2528 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2346  0.453753
2347  0.424441
2348  0.442222
2349  0.437290
2350  0.424614

[2351 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2534  0.951066
2535  0.964088
2536  0.938164
2537  0.826324
2538  0.869182

[2539 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1981  0.119201
1982  0.124047
1983  0.131512
1984  0.092572
1985  0.145542

[1986 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2527  0.710963
2528  0.693210
2529  0.700963
2530  0.700284
2531  0.699046

[2532 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2211  1.025507
2212  0.995546
2213  1.002530
2214  1.002464
2215  1.015188

[2216 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2502  0.663944
2503  0.646615
2504  0.674539
2505  0.683479
2506  0.776348

[2507 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2190  0.804861
2191  0.796921
2192  0.793220
2193  0.779667
2194  0.685663

[2195 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2463  2.044391
2464  2.030615
2465  2.041499
2466  2.042679
2467  1.995505

[2468 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2474  0.924140
2475  0.953026
2476  0.960909
2477  0.854034
2478  0.826782

[2479 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2469  1.476506
2470  1.443683
2471  1.333449
2472  0.972906
2473  0.916383

[2474 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2345  0.829661
2346  0.808873
2347  0.782022
2348  0.673951
2349  0.662807

[2350 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2478  2.332972
2479  2.361052
2480  2.322571
2481  2.339210
2482  2.265630

[2483 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2423  1.610297
2424  1.617794
2425  1.615408
2426  1.418215
2427  1.323592

[2428 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2524  0.846836
2525  0.861126
2526  0.925074
2527  1.043771
2528  1.024150

[2529 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2466  0.664218
2467  0.724486
2468  0.692780
2469  0.590930
2470  0.598593

[2471 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2439  1.723334
2440  1.704134
2441  1.649653
2442  1.617478
2443  1.558530

[2444 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2436  0.764783
2437  0.810387
2438  0.743403
2439  0.790106
2440  0.837772

[2441 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2527  1.755084
2528  1.759911
2529  1.708002
2530  1.904863
2531  1.859744

[2532 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2385  1.039655
2386  1.040065
2387  1.026222
2388  0.950195
2389  0.934475

[2390 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2261  1.983376
2262  2.020445
2263  2.016194
2264  1.943413
2265  1.957956

[2266 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2383  1.655174
2384  1.648822
2385  1.596280
2386  1.425646
2387  1.368026

[2388 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2394  0.879683
2395  0.903594
2396  0.901410
2397  0.910689
2398  0.899060

[2399 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2388  1.125457
2389  1.225765
2390  1.246835
2391  1.201479
2392  1.167066

[2393 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2358  0.915722
2359  0.914283
2360  0.933640
2361  0.999063
2362  1.018764

[2363 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2450  0.704784
2451  0.693994
2452  0.700960
2453  0.868968
2454  0.903474

[2455 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2426  0.823514
2427  0.893321
2428  0.865803
2429  0.866743
2430  0.839954

[2431 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2378  0.489554
2379  0.482667
2380  0.471597
2381  0.404543
2382  0.414843

[2383 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2135  1.281379
2136  1.269936
2137  1.349727
2138  1.270488
2139  1.187540

[2140 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2465  1.955166
2466  1.902671
2467  1.985900
2468  1.834384
2469  1.819551

[2470 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2420  0.899095
2421  0.985512
2422  0.961461
2423  1.121932
2424  1.091438

[2425 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2294  1.135938
2295  1.158194
2296  1.049978
2297  0.866713
2298  0.819913

[2299 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2444  0.931206
2445  0.909412
2446  0.932038
2447  0.911555
2448  0.890682

[2449 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2371  0.832915
2372  0.847656
2373  0.737481
2374  0.582776
2375  0.526154

[2376 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2294  1.951830
2295  1.906274
2296  1.903141
2297  1.784679
2298  1.711300

[2299 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2165  1.145422
2166  1.126928
2167  1.175488
2168  1.095825
2169  1.076737

[2170 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2398  1.037130
2399  0.969741
2400  0.920495
2401  1.009524
2402  1.046046

[2403 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2501  1.591258
2502  1.573522
2503  1.589942
2504  1.594306
2505  1.556689

[2506 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2434  1.816830
2435  1.746931
2436  1.696196
2437  1.665122
2438  1.593268

[2439 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2531  0.636056
2532  0.651465
2533  0.675658
2534  0.859361
2535  0.824786

[2536 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2211  1.972353
2212  1.947873
2213  2.004347
2214  1.923808
2215  1.847509

[2216 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2433  1.193507
2434  1.175080
2435  1.206263
2436  1.149164
2437  1.148116

[2438 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2523  1.490405
2524  1.464836
2525  1.509884
2526  1.444821
2527  1.522707

[2528 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2389  1.798528
2390  1.766508
2391  1.772653
2392  1.698239
2393  1.756418

[2394 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2493  1.794832
2494  1.671334
2495  1.680226
2496  1.584377
2497  1.635050

[2498 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2521  2.066269
2522  2.035681
2523  2.048307
2524  2.033777
2525  2.012863

[2526 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2528  0.449429
2529  0.428352
2530  0.423156
2531  0.284385
2532  0.265807

[2533 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2529  0.255996
2530  0.272453
2531  0.285089
2532  0.175064
2533  0.246149

[2534 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2354  0.800713
2355  0.841740
2356  0.844209
2357  0.804364
2358  0.809385

[2359 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2369  1.831150
2370  1.898257
2371  1.858158
2372  1.736146
2373  1.722863

[2374 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2285  0.708782
2286  0.704158
2287  0.721752
2288  0.718393
2289  0.624545

[2290 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2408  0.600097
2409  0.627725
2410  0.644815
2411  0.693445
2412  0.761257

[2413 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2419  0.899286
2420  0.825583
2421  0.841066
2422  0.924339
2423  1.306031

[2424 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2305  0.520693
2306  0.496640
2307  0.574966
2308  0.782523
2309  0.774521

[2310 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2492  1.801101
2493  1.779061
2494  1.767641
2495  1.654285
2496  1.606366

[2497 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2448  1.564541
2449  1.552707
2450  1.537401
2451  1.489140
2452  1.458558

[2453 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2387  0.899805
2388  0.886058
2389  0.894241
2390  0.848872
2391  0.843671

[2392 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2491  1.955001
2492  1.908309
2493  1.930566
2494  1.840885
2495  1.770188

[2496 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2392  0.969577
2393  0.978500
2394  1.029803
2395  0.966762
2396  1.115982

[2397 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2313  1.526293
2314  1.503298
2315  1.510764
2316  1.456746
2317  1.406609

[2318 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2388  0.152269
2389  0.168684
2390  0.120831
2391  0.186680
2392  0.203417

[2393 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2320  1.663227
2321  1.677362
2322  1.668518
2323  1.645395
2324  1.736929

[2325 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2522  0.984554
2523  0.958428
2524  0.953184
2525  0.904864
2526  0.895773

[2527 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2303  0.458531
2304  0.447475
2305  0.470463
2306  0.447432
2307  0.440106

[2308 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2511  0.312705
2512  0.278985
2513  0.271024
2514  0.296922
2515  0.336183

[2516 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2517  1.207231
2518  1.227366
2519  1.173396
2520  1.589290
2521  1.532704

[2522 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2503  0.672223
2504  0.657551
2505  0.642310
2506  0.578240
2507  0.580344

[2508 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2186  0.727640
2187  0.713915
2188  0.744171
2189  0.743054
2190  0.643490

[2191 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2516  0.866940
2517  0.823620
2518  0.821692
2519  0.772999
2520  0.825623

[2521 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2371  0.995712
2372  0.985804
2373  0.997828
2374  0.995810
2375  0.977418

[2376 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2293  0.025919
2294  0.007208
2295 -0.066365
2296 -0.079991
2297  0.008519

[2298 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2146  1.242374
2147  1.243894
2148  1.245530
2149  1.426759
2150  1.397547

[2151 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2282  1.894433
2283  1.893065
2284  1.818362
2285  1.711323
2286  1.653016

[2287 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2468  0.836955
2469  0.876556
2470  0.832109
2471  0.792478
2472  0.755393

[2473 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2382  1.518628
2383  1.655374
2384  1.535768
2385  1.469680
2386  1.448132

[2387 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2473  0.764309
2474  0.773250
2475  0.743189
2476  0.719735
2477  0.695918

[2478 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2520  0.764303
2521  0.803864
2522  0.761137
2523  0.779765
2524  0.821239

[2525 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2339  1.887748
2340  1.844747
2341  1.846884
2342  1.822416
2343  1.808354

[2344 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2524  1.336689
2525  1.365157
2526  1.290618
2527  1.292529
2528  1.243471

[2529 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2069  0.532631
2070  0.483171
2071  0.393353
2072  0.507487
2073  0.581790

[2074 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2465  0.608288
2466  0.543849
2467  0.527567
2468  0.402925
2469  0.256047

[2470 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2493  0.663456
2494  0.638885
2495  0.647580
2496  0.772206
2497  0.767147

[2498 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2539  1.300252
2540  1.276010
2541  1.230949
2542  1.190371
2543  1.123465

[2544 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2464  1.015396
2465  1.208126
2466  1.114888
2467  1.167033
2468  1.127924

[2469 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2429  1.190970
2430  1.164897
2431  1.198007
2432  1.153852
2433  1.132405

[2434 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2420  0.615288
2421  0.600984
2422  0.617947
2423  0.616135
2424  0.626318

[2425 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2209  0.876105
2210  0.843735
2211  0.863518
2212  0.795385
2213  0.755562

[2214 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2510  0.925665
2511  0.987527
2512  0.915487
2513  1.273004
2514  1.235519

[2515 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2394  0.287737
2395  0.256677
2396  0.342025
2397  0.296225
2398  0.310116

[2399 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2506  1.319300
2507  1.305489
2508  1.273375
2509  1.124840
2510  1.098373

[2511 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2460  1.427226
2461  1.437262
2462  1.442775
2463  1.425545
2464  1.390498

[2465 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2391  1.502901
2392  1.490481
2393  1.458621
2394  1.363467
2395  1.387150

[2396 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2528  1.458931
2529  1.448459
2530  1.402921
2531  1.356319
2532  1.307471

[2533 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2493  0.919561
2494  0.903416
2495  0.924989
2496  0.914994
2497  0.951929

[2498 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2526  0.863009
2527  0.899609
2528  0.901965
2529  1.090046
2530  1.074244

[2531 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2332  1.959901
2333  1.977747
2334  1.984803
2335  1.976169
2336  1.944290

[2337 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2522  1.753798
2523  1.737267
2524  1.728128
2525  1.711188
2526  1.754911

[2527 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2516  0.987337
2517  0.996424
2518  0.997761
2519  0.882655
2520  0.901253

[2521 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2384  0.303693
2385  0.283787
2386  0.337395
2387  0.292999
2388  0.258921

[2389 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2020  2.181819
2021  2.387882
2022  2.429786
2023  2.804583
2024  2.855601

[2025 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2255  1.023709
2256  1.012826
2257  1.025101
2258  0.884175
2259  0.892566

[2260 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2521  1.940457
2522  1.956410
2523  1.952402
2524  2.234750
2525  2.162202

[2526 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2510  0.924751
2511  0.919273
2512  0.915459
2513  0.842986
2514  0.819025

[2515 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2514  0.536211
2515  0.494126
2516  0.471102
2517  0.398027
2518  0.346547

[2519 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2528  0.456145
2529  0.453303
2530  0.483441
2531  0.495322
2532  0.637683

[2533 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2502  1.359395
2503  1.343665
2504  1.342283
2505  1.256471
2506  1.258401

[2507 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2314  0.246698
2315  0.232829
2316  0.227132
2317  0.296879
2318  0.286314

[2319 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2422  1.249703
2423  1.207112
2424  1.231253
2425  1.252325
2426  1.131498

[2427 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2275  1.064690
2276  1.048479
2277  1.108720
2278  1.202680
2279  1.209489

[2280 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2420  1.146268
2421  1.128231
2422  1.150707
2423  1.147723
2424  1.159889

[2425 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2514  0.798683
2515  0.761375
2516  0.713266
2517  0.687579
2518  0.779002

[2519 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2462  0.651900
2463  0.658302
2464  0.649235
2465  0.761231
2466  0.697706

[2467 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2062  0.716454
2063  0.743787
2064  0.714738
2065  0.689188
2066  0.652701

[2067 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2518  1.109764
2519  1.089603
2520  1.088505
2521  1.083887
2522  1.061176

[2523 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2502  0.850314
2503  0.830009
2504  0.706493
2505  0.749146
2506  0.785983

[2507 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2341  1.283707
2342  1.219807
2343  1.185178
2344  1.257076
2345  1.155882

[2346 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2161  0.878153
2162  0.742539
2163  0.663601
2164  0.639422
2165  0.582631

[2166 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2507  1.195463
2508  1.217892
2509  1.241692
2510  1.304913
2511  1.340369

[2512 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2296  0.385380
2297  0.350169
2298  0.259545
2299  0.393299
2300  0.372307

[2301 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1850  1.039747
1851  1.073476
1852  1.056669
1853  1.085228
1854  1.103959

[1855 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2372  1.990573
2373  1.919275
2374  1.935573
2375  1.779630
2376  1.923524

[2377 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2540  1.137697
2541  1.158707
2542  1.153142
2543  1.328642
2544  1.224517

[2545 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2059  0.458292
2060  0.517946
2061  0.476140
2062  0.461916
2063  0.478553

[2064 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2328  1.205895
2329  1.204504
2330  1.206918
2331  1.303950
2332  1.252979

[2333 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2436  0.563568
2437  0.548039
2438  0.544024
2439  0.522667
2440  0.521932

[2441 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2383  1.144532
2384  1.126089
2385  1.160188
2386  1.090893
2387  1.063288

[2388 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2532  0.477779
2533  0.468912
2534  0.475939
2535  0.439947
2536  0.435579

[2537 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2416  1.481000
2417  1.495619
2418  1.516704
2419  1.476492
2420  1.443213

[2421 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2492  1.188761
2493  1.202024
2494  1.273750
2495  1.438036
2496  1.427445

[2497 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2350  1.227660
2351  1.112814
2352  1.101773
2353  1.215371
2354  1.182644

[2355 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2522  0.880810
2523  0.852719
2524  0.851259
2525  0.872451
2526  0.932074

[2527 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2338  1.707831
2339  1.640263
2340  1.613572
2341  1.501188
2342  1.477488

[2343 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2471  2.337149
2472  2.317972
2473  2.332391
2474  2.374946
2475  2.353728

[2476 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2500  1.148477
2501  1.139593
2502  1.102395
2503  1.066414
2504  1.038957

[2505 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2535  0.236933
2536  0.244489
2537  0.213723
2538  0.180667
2539  0.227306

[2540 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2444  1.378362
2445  1.375955
2446  1.357583
2447  1.295998
2448  1.314712

[2449 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2523  0.813192
2524  0.779939
2525  0.796820
2526  0.935291
2527  0.891077

[2528 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2325  1.147939
2326  1.136985
2327  1.145513
2328  1.006173
2329  1.151960

[2330 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2390  1.579400
2391  1.565545
2392  1.574820
2393  1.480485
2394  1.431013

[2395 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2276  1.426165
2277  1.474903
2278  1.468043
2279  1.314212
2280  1.202827

[2281 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2479  1.918312
2480  1.910590
2481  1.897560
2482  1.838251
2483  1.773776

[2484 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2373  0.745164
2374  0.671566
2375  0.644769
2376  0.546003
2377  0.513120

[2378 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2393  0.860766
2394  0.837805
2395  0.859456
2396  0.750516
2397  0.740350

[2398 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2504  1.154657
2505  1.113237
2506  1.048822
2507  0.971367
2508  1.006337

[2509 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2509  1.585396
2510  1.601479
2511  1.621051
2512  1.703491
2513  1.739504

[2514 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2385  1.460069
2386  1.401605
2387  1.386974
2388  1.465942
2389  1.464130

[2390 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2533  0.244247
2534  0.243678
2535  0.254558
2536  0.360925
2537  0.365644

[2538 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2375  1.767929
2376  1.753062
2377  1.778232
2378  1.675032
2379  1.649962

[2380 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2109  0.368522
2110  0.381676
2111  0.407029
2112  0.433487
2113  0.381133

[2114 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2399  0.389574
2400  0.405881
2401  0.436381
2402  0.548660
2403  0.588866

[2404 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2400  1.934160
2401  1.905996
2402  1.941634
2403  1.929626
2404  1.899642

[2405 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2394  1.324130
2395  1.323498
2396  1.406751
2397  1.406436
2398  1.347333

[2399 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2514  0.538409
2515  0.524071
2516  0.569698
2517  0.662872
2518  0.658211

[2519 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2540  0.453581
2541  0.459868
2542  0.462197
2543  0.621322
2544  0.518643

[2545 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2449  0.609215
2450  0.597584
2451  0.610244
2452  0.610724
2453  0.610428

[2454 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2396  1.317818
2397  1.288028
2398  1.293971
2399  1.319349
2400  1.299158

[2401 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2298  0.148600
2299  0.112312
2300  0.140740
2301  0.036175
2302  0.078718

[2303 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2390  1.471118
2391  1.430686
2392  1.448019
2393  1.392976
2394  1.437950

[2395 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2419  0.482182
2420  0.548833
2421  0.576566
2422  0.773454
2423  0.808960

[2424 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2534  1.341296
2535  1.255296
2536  1.255020
2537  1.145490
2538  1.130337

[2539 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2183  1.382665
2184  1.333344
2185  1.346217
2186  1.246554
2187  1.268029

[2188 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2436  0.986285
2437  0.958352
2438  0.976799
2439  0.969031
2440  0.987649

[2441 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2404  1.017652
2405  1.026206
2406  0.974907
2407  0.949277
2408  0.937590

[2409 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2534  0.776432
2535  0.734854
2536  0.770509
2537  0.673834
2538  0.747914

[2539 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2449  1.377068
2450  1.261638
2451  1.116971
2452  1.000066
2453  1.078299

[2454 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2121  0.472697
2122  0.393369
2123  0.441535
2124  0.431065
2125  0.436974

[2126 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2514  0.944047
2515  0.997712
2516  0.950851
2517  0.961672
2518  1.199896

[2519 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2433  1.762387
2434  1.615553
2435  1.600681
2436  1.429136
2437  1.370702

[2438 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2343  1.276991
2344  1.212629
2345  1.179472
2346  1.015258
2347  0.999658

[2348 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2311  1.113903
2312  1.047008
2313  1.029397
2314  0.876100
2315  0.890186

[2316 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2520  0.739890
2521  0.748852
2522  0.749885
2523  0.773097
2524  0.757183

[2525 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2148  1.156681
2149  1.166984
2150  1.196793
2151  1.307996
2152  1.279870

[2153 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2404  1.388617
2405  1.346909
2406  1.361867
2407  1.257231
2408  1.235082

[2409 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2347  1.103889
2348  1.073861
2349  0.988650
2350  0.882591
2351  0.898856

[2352 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2538  1.685623
2539  1.672023
2540  1.690542
2541  1.673390
2542  1.658364

[2543 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2095  1.532281
2096  1.528435
2097  1.530343
2098  1.494870
2099  1.464936

[2100 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2472  1.189461
2473  1.253666
2474  1.091548
2475  1.294780
2476  1.345756

[2477 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2508  0.941356
2509  0.946640
2510  0.942705
2511  0.948222
2512  0.937560

[2513 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2339  0.939675
2340  0.985578
2341  0.980180
2342  0.962576
2343  0.902258

[2344 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2386  1.163347
2387  1.189765
2388  1.207426
2389  1.271009
2390  1.255228

[2391 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2479  0.985467
2480  1.048707
2481  1.049521
2482  1.206055
2483  1.239098

[2484 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2408  1.188654
2409  1.173849
2410  1.164449
2411  1.071536
2412  1.151613

[2413 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2085  0.629962
2086  0.646385
2087  0.643139
2088  0.554931
2089  0.366481

[2090 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2450  0.633026
2451  0.619713
2452  0.609929
2453  0.629896
2454  0.661128

[2455 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2417  0.912560
2418  0.906761
2419  0.908194
2420  1.013674
2421  0.996936

[2422 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2428  2.400296
2429  2.381231
2430  2.343194
2431  2.203817
2432  2.144036

[2433 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2531  0.675489
2532  0.682190
2533  0.686954
2534  0.703192
2535  0.689718

[2536 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2469  1.679355
2470  1.671519
2471  1.667702
2472  1.541507
2473  1.507830

[2474 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2377  0.659783
2378  0.671609
2379  0.660047
2380  0.765609
2381  0.728987

[2382 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2461  0.696130
2462  0.715105
2463  0.667386
2464  0.704184
2465  0.701434

[2466 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2201  1.062837
2202  1.000067
2203  1.020190
2204  0.805838
2205  0.859573

[2206 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2511  1.215688
2512  1.167068
2513  1.165509
2514  1.354663
2515  1.246278

[2516 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2501  0.414179
2502  0.410959
2503  0.411928
2504  0.399222
2505  0.408386

[2506 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2505  1.492009
2506  1.437716
2507  1.433808
2508  1.340905
2509  1.493344

[2510 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2414  2.021865
2415  1.993917
2416  1.904645
2417  1.643068
2418  1.649208

[2419 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2469  0.317063
2470  0.351686
2471  0.340571
2472  0.341115
2473  0.344052

[2474 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2488  0.868338
2489  0.841618
2490  0.801626
2491  0.670445
2492  0.655542

[2493 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2489  0.882222
2490  0.766889
2491  0.748278
2492  0.532873
2493  0.486469

[2494 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2470  1.574371
2471  1.467126
2472  1.434870
2473  1.316326
2474  1.346951

[2475 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2442  1.328106
2443  1.325869
2444  1.346914
2445  1.386543
2446  1.348011

[2447 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2340  0.896376
2341  0.874365
2342  0.902168
2343  1.125351
2344  1.116944

[2345 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2504  1.370291
2505  1.303285
2506  1.300700
2507  1.183203
2508  1.171895

[2509 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2335  2.072568
2336  2.145044
2337  2.183502
2338  1.960821
2339  1.957284

[2340 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2422  0.906366
2423  0.901677
2424  0.898621
2425  0.896644
2426  0.895204

[2427 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2312  1.064654
2313  1.083442
2314  1.094879
2315  1.026854
2316  1.010318

[2317 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2333  1.127014
2334  1.147412
2335  1.151683
2336  1.069679
2337  1.046355

[2338 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2364  1.367037
2365  1.366235
2366  1.374892
2367  1.283287
2368  1.275269

[2369 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2380  1.188688
2381  1.172527
2382  1.180098
2383  1.143429
2384  1.135673

[2385 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2295  0.587323
2296  0.650339
2297  0.629858
2298  0.649700
2299  0.667093

[2300 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2475  1.264802
2476  1.188834
2477  1.151635
2478  0.843158
2479  0.865338

[2480 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2489  2.054070
2490  2.018325
2491  2.050940
2492  1.959239
2493  1.957176

[2494 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2466  0.579187
2467  0.558859
2468  0.565273
2469  0.676407
2470  0.675848

[2471 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2401  1.837167
2402  1.821031
2403  1.820804
2404  1.704475
2405  1.672311

[2406 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2183  1.122505
2184  1.085872
2185  0.978842
2186  0.925576
2187  0.741798

[2188 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2399  0.880581
2400  0.769069
2401  0.754983
2402  0.645590
2403  0.657440

[2404 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2216  0.920617
2217  0.940956
2218  0.934249
2219  0.783557
2220  0.692088

[2221 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2310  0.983151
2311  0.882227
2312  0.889545
2313  0.831303
2314  0.824784

[2315 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2299  1.615152
2300  1.568453
2301  1.543941
2302  1.413540
2303  1.411553

[2304 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2245  1.187405
2246  1.217216
2247  1.176947
2248  1.275375
2249  1.153544

[2250 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2404  0.757586
2405  0.733942
2406  0.740549
2407  0.722401
2408  0.727345

[2409 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2403  0.562622
2404  0.563022
2405  0.537746
2406  0.466550
2407  0.456866

[2408 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2500  1.692780
2501  1.681713
2502  1.684964
2503  1.697509
2504  1.684365

[2505 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2479  0.520528
2480  0.449696
2481  0.456636
2482  0.547117
2483  0.544851

[2484 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2442  2.008924
2443  2.012367
2444  1.963750
2445  1.758843
2446  1.765227

[2447 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2499  1.196759
2500  1.167496
2501  1.155259
2502  1.164252
2503  1.103334

[2504 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2294  2.166507
2295  2.160015
2296  2.137670
2297  2.086983
2298  2.079973

[2299 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2428  1.350047
2429  1.360169
2430  1.336642
2431  1.238626
2432  1.231892

[2433 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2272  1.618890
2273  1.631799
2274  1.612578
2275  1.538896
2276  1.462453

[2277 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2252  1.261400
2253  1.191570
2254  1.219696
2255  0.993603
2256  1.004141

[2257 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2366  0.435155
2367  0.449146
2368  0.400073
2369  0.295647
2370  0.281639

[2371 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2416  2.492562
2417  2.477341
2418  2.483397
2419  2.403676
2420  2.381751

[2421 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2484  0.857241
2485  0.826588
2486  0.846662
2487  0.844820
2488  0.852132

[2489 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2209  1.523962
2210  1.520746
2211  1.459968
2212  1.366184
2213  1.299177

[2214 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2388  0.863889
2389  0.848475
2390  0.808088
2391  0.808876
2392  0.776610

[2393 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2436  1.535947
2437  1.530150
2438  1.581979
2439  1.673455
2440  1.659028

[2441 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2417  1.115856
2418  1.139593
2419  1.153259
2420  1.135748
2421  1.127434

[2422 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2277  1.265601
2278  1.456838
2279  1.421265
2280  1.298480
2281  1.311763

[2282 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2452  0.770148
2453  0.785021
2454  0.791842
2455  0.746091
2456  0.770430

[2457 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2135  1.136177
2136  1.104030
2137  1.126702
2138  1.142690
2139  1.130879

[2140 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2469  1.369132
2470  1.350165
2471  1.358518
2472  1.299384
2473  1.278294

[2474 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2441  0.887219
2442  0.865606
2443  0.829208
2444  0.767201
2445  0.798815

[2446 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2288  0.200437
2289  0.231884
2290  0.158357
2291  0.174387
2292  0.107909

[2293 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2263  0.869205
2264  0.841394
2265  0.866735
2266  0.759915
2267  0.734526

[2268 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2269  2.385803
2270  2.382252
2271  2.387312
2272  2.376251
2273  2.318458

[2274 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2436  1.176881
2437  1.234366
2438  1.201315
2439  1.346833
2440  1.295988

[2441 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2435  0.713023
2436  0.695499
2437  0.699925
2438  0.704449
2439  0.696840

[2440 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2327  0.936028
2328  0.999603
2329  1.033378
2330  1.040671
2331  1.032270

[2332 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2310  1.173758
2311  1.124963
2312  1.085584
2313  0.904271
2314  0.854604

[2315 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2197  1.450286
2198  1.425886
2199  1.401289
2200  1.233299
2201  1.226789

[2202 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2320  0.944016
2321  0.968228
2322  0.955658
2323  0.859013
2324  0.835950

[2325 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2467  0.921853
2468  0.976111
2469  0.891651
2470  0.889664
2471  0.864734

[2472 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2327  0.626497
2328  0.607985
2329  0.603143
2330  0.541652
2331  0.527761

[2332 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2464  0.739197
2465  0.747430
2466  0.743243
2467  0.746644
2468  0.731746

[2469 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2461  0.523666
2462  0.503451
2463  0.514080
2464  0.472051
2465  0.468553

[2466 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2425  0.730947
2426  0.739379
2427  0.707632
2428  0.711680
2429  0.685013

[2430 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2224  1.955515
2225  1.933665
2226  1.892363
2227  1.853932
2228  1.793527

[2229 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2453  0.633137
2454  0.613113
2455  0.678684
2456  0.548758
2457  0.521402

[2458 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2337  1.373565
2338  1.302418
2339  1.316473
2340  1.382193
2341  1.490095

[2342 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2225  1.358189
2226  1.380198
2227  1.313808
2228  1.248696
2229  1.193388

[2230 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2231  1.937384
2232  1.884845
2233  1.818373
2234  1.718755
2235  1.790382

[2236 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2371  1.578111
2372  1.500521
2373  1.548624
2374  1.611565
2375  1.636277

[2376 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2431  1.994710
2432  1.986023
2433  1.952700
2434  1.857864
2435  1.804987

[2436 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2409  0.786318
2410  0.765859
2411  0.760246
2412  0.816027
2413  0.970360

[2414 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2414  0.750756
2415  0.747148
2416  0.786987
2417  0.705243
2418  0.643405

[2419 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2313  1.482480
2314  1.453818
2315  1.367460
2316  1.227159
2317  1.245660

[2318 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2425  1.108479
2426  1.065749
2427  1.080911
2428  0.898694
2429  0.923700

[2430 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2358  1.100586
2359  1.076661
2360  1.080066
2361  1.046024
2362  1.035631

[2363 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2281  0.725421
2282  0.700572
2283  0.720876
2284  0.714317
2285  0.692795

[2286 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2146  1.821003
2147  1.782184
2148  1.727840
2149  1.650219
2150  1.611728

[2151 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2405  1.102741
2406  1.213747
2407  1.217528
2408  1.061724
2409  1.100588

[2410 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2141  1.266185
2142  1.121360
2143  1.085089
2144  1.067220
2145  0.977252

[2146 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2322  0.546154
2323  0.587046
2324  0.581500
2325  0.589593
2326  0.583080

[2327 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2192  1.437179
2193  1.406730
2194  1.386688
2195  1.229425
2196  1.181219

[2197 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2324  1.665428
2325  1.727241
2326  1.661992
2327  1.633969
2328  1.601115

[2329 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2393  1.152142
2394  1.135878
2395  1.166886
2396  1.158177
2397  1.233708

[2398 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2370  1.577812
2371  1.549250
2372  1.571132
2373  1.542829
2374  1.581969

[2375 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2210  1.385815
2211  1.361562
2212  1.361447
2213  1.337398
2214  1.322731

[2215 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2227  0.482440
2228  0.396603
2229  0.365831
2230  0.353916
2231  0.236522

[2232 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2438  0.455087
2439  0.433003
2440  0.469439
2441  0.401864
2442  0.403967

[2443 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2434  0.849326
2435  0.835431
2436  0.835306
2437  0.838484
2438  0.828144

[2439 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2326  1.878340
2327  1.857923
2328  1.835949
2329  1.825968
2330  1.778260

[2331 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2416  1.059268
2417  1.062621
2418  1.063193
2419  1.055200
2420  1.128771

[2421 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2271  0.976396
2272  0.988577
2273  0.997502
2274  0.979508
2275  0.981663

[2276 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2425  0.542055
2426  0.538703
2427  0.521027
2428  0.459344
2429  0.446957

[2430 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2236  1.188842
2237  1.142148
2238  1.148462
2239  1.083820
2240  1.007205

[2241 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2110  0.975060
2111  1.224581
2112  1.031548
2113  1.023706
2114  0.888376

[2115 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2237  0.334761
2238  0.359976
2239  0.391927
2240  0.272624
2241  0.236047

[2242 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2424  1.599887
2425  1.595718
2426  1.578019
2427  1.484430
2428  1.480871

[2429 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2344  1.970570
2345  1.948501
2346  1.966542
2347  1.878981
2348  1.813130

[2349 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2414  1.093543
2415  1.055258
2416  1.062788
2417  1.161915
2418  1.169630

[2419 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2272  0.936776
2273  0.917681
2274  0.916404
2275  0.851076
2276  0.805178

[2277 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2393  0.879152
2394  0.979158
2395  0.933574
2396  0.898880
2397  0.847397

[2398 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2392  0.691173
2393  0.707985
2394  0.709420
2395  0.661924
2396  0.651721

[2397 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2288  0.828655
2289  0.847220
2290  0.833141
2291  0.836974
2292  0.827656

[2293 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2273  0.927202
2274  1.044328
2275  1.015543
2276  0.931184
2277  0.926632

[2278 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2273  2.339357
2274  2.380659
2275  2.317504
2276  2.185157
2277  2.124181

[2278 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2161  0.479354
2162  0.452893
2163  0.391840
2164  0.418795
2165  0.426631

[2166 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2304  0.609075
2305  0.573416
2306  0.585837
2307  0.665846
2308  0.725973

[2309 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2188  1.375324
2189  1.407612
2190  1.395909
2191  1.371505
2192  1.296782

[2193 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2358  0.972041
2359  0.955959
2360  0.962965
2361  1.041029
2362  1.013605

[2363 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2368  1.213392
2369  1.185444
2370  1.195870
2371  1.144677
2372  1.143355

[2373 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2120  0.957016
2121  0.969657
2122  0.971906
2123  0.944990
2124  0.929534

[2125 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2167  0.675884
2168  0.651132
2169  0.670824
2170  0.644146
2171  0.614012

[2172 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2408  1.289255
2409  1.260877
2410  1.244183
2411  1.184066
2412  1.149603

[2413 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2089  0.467201
2090  0.437242
2091  0.436543
2092  0.430293
2093  0.549879

[2094 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2274  1.447213
2275  1.406230
2276  1.381393
2277  1.243098
2278  1.210892

[2279 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2103  1.691732
2104  1.698163
2105  1.649962
2106  1.565153
2107  1.405928

[2108 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2403  0.771771
2404  0.704164
2405  0.682387
2406  0.653283
2407  0.636254

[2408 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2360  1.949643
2361  1.952121
2362  1.959388
2363  1.888017
2364  1.844007

[2365 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1908  0.670604
1909  0.727164
1910  0.735032
1911  0.737105
1912  0.742702

[1913 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2256  1.191672
2257  1.078492
2258  1.052938
2259  0.971428
2260  0.966039

[2261 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2255  1.449493
2256  1.399270
2257  1.417743
2258  1.556621
2259  1.514162

[2260 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2192  0.770236
2193  0.855305
2194  0.835905
2195  0.779618
2196  0.740692

[2197 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2358  0.955864
2359  0.922122
2360  0.894337
2361  0.836988
2362  0.826620

[2363 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2353  0.853432
2354  0.856444
2355  0.827471
2356  0.798439
2357  0.774982

[2358 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2331  2.206153
2332  2.171352
2333  2.165947
2334  2.215030
2335  2.218702

[2336 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2396  0.582923
2397  0.559218
2398  0.534914
2399  0.610262
2400  0.581791

[2401 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2284  0.554500
2285  0.608369
2286  0.595090
2287  0.851418
2288  0.867650

[2289 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2307  1.257311
2308  1.308209
2309  1.236657
2310  1.330992
2311  1.250882

[2312 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2309  1.968001
2310  1.934157
2311  1.920812
2312  1.864201
2313  1.857976

[2314 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2340  0.622177
2341  0.679314
2342  0.679475
2343  0.799134
2344  0.778672

[2345 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2283  0.558031
2284  0.556620
2285  0.562762
2286  0.600682
2287  0.594777

[2288 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2383  1.679879
2384  1.656189
2385  1.653315
2386  1.563206
2387  1.528598

[2388 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1802  1.891518
1803  1.879246
1804  1.910179
1805  1.932175
1806  1.881776

[1807 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2235  0.874605
2236  0.848844
2237  0.822778
2238  0.854049
2239  0.801892

[2240 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2224  2.423588
2225  2.363077
2226  2.462933
2227  2.169353
2228  2.060688

[2229 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2309  1.731704
2310  1.710361
2311  1.724571
2312  1.633706
2313  1.671579

[2314 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2241  0.807900
2242  0.786972
2243  0.812459
2244  0.817773
2245  0.826890

[2246 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2282  0.905261
2283  0.917692
2284  0.937512
2285  0.972218
2286  0.966159

[2287 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2263  1.230761
2264  1.226795
2265  1.300755
2266  1.303924
2267  1.381209

[2268 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2257  1.354615
2258  1.288417
2259  1.308742
2260  1.246386
2261  1.233456

[2262 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2359  0.865224
2360  0.844046
2361  0.857733
2362  0.788223
2363  0.784706

[2364 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1924  1.638759
1925  1.584181
1926  1.606308
1927  1.499690
1928  1.453573

[1929 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2303  1.331457
2304  1.349407
2305  1.364419
2306  1.282132
2307  1.256136

[2308 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2344  1.661382
2345  1.603144
2346  1.620189
2347  1.874002
2348  1.839127

[2349 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2220  1.193830
2221  1.231025
2222  1.228486
2223  1.170303
2224  1.174180

[2225 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2012 -0.356119
2013 -0.485042
2014 -0.460324
2015 -0.244469
2016 -0.192994

[2017 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2282  0.643256
2283  0.621308
2284  0.646180
2285  0.653314
2286  0.647441

[2287 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2321  0.974599
2322  0.972202
2323  0.991112
2324  0.944843
2325  0.936891

[2326 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2330  0.712194
2331  0.668251
2332  0.769150
2333  0.657104
2334  0.776467

[2335 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2233  1.942808
2234  1.923870
2235  1.897780
2236  1.891545
2237  1.857955

[2238 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2312  0.988328
2313  0.975317
2314  0.992321
2315  0.975505
2316  1.023607

[2317 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2213  1.253114
2214  1.224723
2215  1.192880
2216  1.073553
2217  1.087861

[2218 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2359  1.671498
2360  1.646903
2361  1.651457
2362  1.517936
2363  1.481583

[2364 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2016  0.647141
2017  0.676035
2018  0.722785
2019  0.637290
2020  0.624642

[2021 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2127  1.414177
2128  1.409569
2129  1.400404
2130  1.452674
2131  1.485197

[2132 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2333  1.192280
2334  1.165672
2335  1.148455
2336  1.128947
2337  1.132340

[2338 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2321  1.590069
2322  1.598881
2323  1.573475
2324  1.578762
2325  1.541359

[2326 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2315  0.878994
2316  0.777426
2317  0.800633
2318  0.659434
2319  0.667032

[2320 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2348  0.838673
2349  0.734913
2350  0.693984
2351  0.497729
2352  0.456020

[2353 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2111  1.589350
2112  1.538712
2113  1.525875
2114  1.353427
2115  1.333611

[2116 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2054  0.882845
2055  0.870101
2056  0.903437
2057  0.841758
2058  0.806250

[2059 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2334  0.364023
2335  0.365351
2336  0.352455
2337  0.358554
2338  0.345745

[2339 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2314  0.714870
2315  0.717775
2316  0.778782
2317  0.809426
2318  0.812874

[2319 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2331  0.712607
2332  0.739935
2333  0.723008
2334  0.778680
2335  0.776070

[2336 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2311  0.308068
2312  0.178633
2313  0.156319
2314  0.163373
2315 -0.022084

[2316 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2280  2.045868
2281  2.004516
2282  2.004950
2283  1.941524
2284  1.864109

[2285 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2263  1.748222
2264  1.712155
2265  1.768499
2266  1.973748
2267  1.951477

[2268 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2177  0.800501
2178  0.790754
2179  0.772507
2180  0.737855
2181  0.721553

[2182 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2211  1.047567
2212  0.975170
2213  0.935342
2214  0.963342
2215  0.959740

[2216 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2311 -0.127476
2312 -0.050351
2313 -0.089165
2314 -0.171222
2315 -0.177482

[2316 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1972  0.215968
1973  0.261842
1974  0.206832
1975  0.212103
1976  0.066406

[1977 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2294  1.226657
2295  1.207657
2296  1.234996
2297  1.359508
2298  1.327495

[2299 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1988  0.655569
1989  0.622001
1990  0.619846
1991  0.690392
1992  0.690149

[1993 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2082  0.826676
2083  0.891644
2084  0.857658
2085  0.996311
2086  0.950313

[2087 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1923  1.614901
1924  1.539803
1925  1.440902
1926  1.440395
1927  1.426624

[1928 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2137  0.919456
2138  0.933505
2139  0.954405
2140  1.002705
2141  1.090166

[2142 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2323  0.471318
2324  0.497025
2325  0.560523
2326  0.696965
2327  0.732632

[2328 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1892  0.785478
1893  0.771788
1894  0.772356
1895  0.744696
1896  0.796322

[1897 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2247  1.679054
2248  1.669340
2249  1.671356
2250  1.771587
2251  1.800296

[2252 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2285  0.204322
2286  0.188587
2287  0.192288
2288  0.317697
2289  0.294350

[2290 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1907  1.608789
1908  1.594293
1909  1.591753
1910  1.542414
1911  1.524081

[1912 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2117  0.558104
2118  0.484850
2119  0.464797
2120  0.418211
2121  0.363696

[2122 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2081  0.452860
2082  0.416858
2083  0.444284
2084  0.387709
2085  0.393362

[2086 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2076  1.445092
2077  1.479332
2078  1.437657
2079  1.468553
2080  1.461066

[2081 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2282  1.058060
2283  1.033374
2284  1.019902
2285  0.952610
2286  0.927598

[2287 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2043  1.361785
2044  1.339212
2045  1.476093
2046  1.319525
2047  1.459075

[2048 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2288  1.756181
2289  1.721035
2290  1.675247
2291  1.486164
2292  1.473076

[2293 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2181  1.248067
2182  1.179236
2183  1.167550
2184  1.017270
2185  1.005301

[2186 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2111  0.196455
2112  0.149826
2113  0.167991
2114  0.302933
2115  0.291689

[2116 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2307  0.769525
2308  0.760663
2309  0.765024
2310  0.719504
2311  0.725410

[2312 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2282  1.364445
2283  1.312521
2284  1.290525
2285  1.100525
2286  1.093072

[2287 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2198  0.637546
2199  0.662888
2200  0.674137
2201  0.633200
2202  0.642382

[2203 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2058  0.831088
2059  0.809301
2060  0.788745
2061  0.689545
2062  0.587957

[2063 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2107  1.136061
2108  1.109358
2109  1.132328
2110  1.057558
2111  1.094163

[2112 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2153  1.122170
2154  1.082832
2155  1.072949
2156  0.996153
2157  0.988146

[2158 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2182  0.849066
2183  0.825895
2184  0.855018
2185  0.837727
2186  0.806252

[2187 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2184 -0.002427
2185 -0.077069
2186 -0.123477
2187 -0.051668
2188  0.291863

[2189 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2139  2.748040
2140  2.764748
2141  2.784786
2142  2.731065
2143  2.662668

[2144 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2258  0.972283
2259  0.948795
2260  0.900282
2261  0.830234
2262  0.807007

[2263 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2183  1.014197
2184  1.009265
2185  0.923592
2186  0.843106
2187  0.798361

[2188 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2274  0.952913
2275  0.868639
2276  0.848176
2277  0.895132
2278  0.905024

[2279 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2244  0.744428
2245  0.742058
2246  0.754729
2247  0.783675
2248  0.730467

[2249 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2179  0.751149
2180  0.736849
2181  0.696582
2182  0.716129
2183  0.665810

[2184 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2280  1.150014
2281  1.137246
2282  1.195570
2283  1.173127
2284  1.186359

[2285 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2143  2.233444
2144  2.255026
2145  2.264096
2146  2.344804
2147  2.258544

[2148 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2240  0.935617
2241  0.959946
2242  0.963724
2243  1.085143
2244  1.057372

[2245 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2254  0.939887
2255  0.899860
2256  0.903164
2257  1.146242
2258  1.167440

[2259 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2276  1.130699
2277  1.112153
2278  1.115628
2279  1.050877
2280  1.033421

[2281 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2278  1.669221
2279  1.680345
2280  1.635052
2281  1.771310
2282  1.739197

[2283 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2094  0.959397
2095  0.931386
2096  0.942209
2097  0.925559
2098  0.923626

[2099 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2247  0.692286
2248  0.678943
2249  0.704516
2250  0.658252
2251  0.657326

[2252 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2124  1.693701
2125  1.677733
2126  1.677888
2127  1.572058
2128  1.539149

[2129 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2043  0.834525
2044  0.915089
2045  0.863488
2046  0.848074
2047  0.859480

[2048 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2203  1.517191
2204  1.453816
2205  1.441320
2206  1.331644
2207  1.312653

[2208 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2069  1.538999
2070  1.485674
2071  1.487365
2072  1.383322
2073  1.366510

[2074 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2181  0.540063
2182  0.665275
2183  0.616606
2184  0.706712
2185  0.716759

[2186 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2162  0.795912
2163  0.804825
2164  0.832592
2165  0.735033
2166  0.717195

[2167 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2268  0.655753
2269  0.679841
2270  0.690056
2271  0.681345
2272  0.673553

[2273 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2112  0.016986
2113  0.130348
2114  0.044812
2115  0.181164
2116  0.143638

[2117 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2184  1.450836
2185  1.461229
2186  1.442696
2187  1.370125
2188  1.383524

[2189 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2141  0.530989
2142  0.525666
2143  0.536852
2144  0.523536
2145  0.488637

[2146 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2230  1.159329
2231  1.149616
2232  1.128011
2233  1.052096
2234  1.056286

[2235 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1980  1.488411
1981  1.520463
1982  1.467987
1983  1.515870
1984  1.447221

[1985 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2242  0.873616
2243  0.906379
2244  0.833910
2245  0.954891
2246  0.937580

[2247 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2221  0.592722
2222  0.645733
2223  0.635021
2224  0.638392
2225  0.612874

[2226 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1894  0.551954
1895  0.529660
1896  0.561976
1897  0.578374
1898  0.551881

[1899 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2197  1.596524
2198  1.453273
2199  1.398880
2200  1.199832
2201  1.223842

[2202 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2119  1.639705
2120  1.662875
2121  1.686298
2122  2.083281
2123  2.073008

[2124 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2262  0.852967
2263  0.835473
2264  0.840224
2265  0.916068
2266  0.895714

[2267 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2216  1.259102
2217  1.206109
2218  1.204783
2219  1.361102
2220  1.396413

[2221 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2241  0.790495
2242  0.791765
2243  0.813338
2244  0.833665
2245  0.800215

[2246 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2124  1.024884
2125  0.982176
2126  1.005678
2127  1.022709
2128  1.015926

[2129 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2178  1.172511
2179  1.166068
2180  1.190730
2181  1.105558
2182  1.094771

[2183 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2186  0.494017
2187  0.563303
2188  0.552317
2189  0.649523
2190  0.648712

[2191 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2023  0.335788
2024  0.369340
2025  0.323098
2026  0.411391
2027  0.408647

[2028 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2175  0.593808
2176  0.638320
2177  0.670514
2178  0.709617
2179  0.680678

[2180 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1708  0.558342
1709  0.593235
1710  0.591752
1711  0.656866
1712  0.674362

[1713 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2120  0.877912
2121  0.874978
2122  0.862300
2123  0.842340
2124  0.836408

[2125 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1835  1.027098
1836  1.077645
1837  1.254438
1838  1.446620
1839  1.357181

[1840 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2205  0.928774
2206  0.929037
2207  0.922624
2208  1.047588
2209  1.062075

[2210 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1983  0.805453
1984  0.786795
1985  0.788351
1986  0.777819
1987  0.767175

[1988 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2045  0.775870
2046  0.844699
2047  0.858191
2048  0.716797
2049  0.710156

[2050 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1780  0.867119
1781  0.823653
1782  0.756959
1783  0.834737
1784  0.853407

[1785 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1858  0.601860
1859  0.543694
1860  0.568849
1861  0.432200
1862  0.406204

[1863 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2074  1.656043
2075  1.653383
2076  1.633006
2077  1.743712
2078  1.875326

[2079 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2056  0.834762
2057  0.874331
2058  0.837784
2059  0.762108
2060  0.705324

[2061 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1944  1.879609
1945  1.870698
1946  1.869336
1947  1.863181
1948  1.827325

[1949 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2061  1.139028
2062  1.130684
2063  1.105892
2064  1.026966
2065  1.012327

[2066 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2101  0.230417
2102  0.335237
2103  0.293648
2104  0.051424
2105 -0.036824

[2106 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2076  0.672524
2077  0.688020
2078  0.686512
2079  0.699831
2080  0.669873

[2081 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2153  1.637925
2154  1.608625
2155  1.564657
2156  1.408477
2157  1.364560

[2158 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1972  1.055232
1973  1.169966
1974  1.104769
1975  1.178350
1976  1.090695

[1977 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2193  1.212994
2194  1.176749
2195  1.107085
2196  1.302304
2197  1.380212

[2198 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1994  0.902821
1995  0.917223
1996  0.862931
1997  0.877632
1998  0.764488

[1999 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2071  1.568810
2072  1.542942
2073  1.579213
2074  1.551437
2075  1.544263

[2076 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2190  1.119431
2191  1.159027
2192  1.154858
2193  1.361035
2194  1.326449

[2195 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2082  0.510736
2083  0.616680
2084  0.604471
2085  0.593869
2086  0.571468

[2087 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2158  1.087066
2159  1.083667
2160  1.039859
2161  0.946504
2162  0.931787

[2163 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2029  1.088350
2030  1.080283
2031  1.137931
2032  1.106393
2033  1.181614

[2034 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1894  1.585551
1895  1.508934
1896  1.528884
1897  1.537951
1898  1.422260

[1899 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2165  1.065993
2166  1.075030
2167  1.059153
2168  0.913920
2169  0.907371

[2170 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2172  0.781559
2173  0.852394
2174  0.874878
2175  0.999499
2176  0.988602

[2177 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2182  0.609389
2183  0.600320
2184  0.628004
2185  0.620630
2186  0.663571

[2187 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1923  0.575013
1924  0.658205
1925  0.672166
1926  0.689591
1927  0.688578

[1928 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2146  1.189161
2147  1.202092
2148  1.235170
2149  1.225027
2150  1.206856

[2151 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2102  1.020382
2103  1.017511
2104  1.036263
2105  1.028476
2106  1.021448

[2107 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2077  1.278654
2078  1.262033
2079  1.287358
2080  1.273131
2081  1.245226

[2082 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1917  2.133889
1918  2.098011
1919  2.136079
1920  2.070225
1921  1.986279

[1922 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2067  0.637492
2068  0.630177
2069  0.626366
2070  0.731637
2071  0.698062

[2072 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1695  1.485023
1696  1.459241
1697  1.475152
1698  1.337185
1699  1.311418

[1700 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2144  0.507612
2145  0.666653
2146  0.625734
2147  0.471102
2148  0.418876

[2149 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1702  0.881551
1703  0.901476
1704  0.911042
1705  0.905333
1706  0.915784

[1707 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1996  1.811401
1997  1.777473
1998  1.714957
1999  1.876318
2000  1.862769

[2001 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1941  1.671283
1942  1.558944
1943  1.527295
1944  1.386999
1945  1.369436

[1946 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1979  0.921273
1980  0.935891
1981  0.925757
1982  0.764232
1983  0.743012

[1984 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1756  0.670944
1757  0.664635
1758  0.691587
1759  0.665411
1760  0.655760

[1761 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2126  1.810596
2127  1.777881
2128  1.759832
2129  1.815583
2130  1.721598

[2131 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1892  0.877419
1893  0.817328
1894  0.773860
1895  0.688972
1896  0.846606

[1897 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1893  0.798657
1894  0.765261
1895  0.751952
1896  0.761139
1897  0.734878

[1898 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1939  0.735987
1940  0.757423
1941  0.676907
1942  0.663350
1943  0.701929

[1944 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2131  1.408952
2132  1.364630
2133  1.202158
2134  1.514232
2135  1.656435

[2136 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2096  0.937903
2097  0.996354
2098  0.909949
2099  0.867023
2100  0.871576

[2101 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2121  1.041543
2122  0.886869
2123  0.924908
2124  0.777794
2125  0.762508

[2126 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2017 -0.042471
2018 -0.089793
2019 -0.100888
2020 -0.078646
2021 -0.111477

[2022 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1766  1.411074
1767  1.395660
1768  1.369114
1769  1.267708
1770  1.318686

[1771 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2118  0.982010
2119  0.971062
2120  0.949895
2121  0.946499
2122  0.917851

[2123 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1703  1.472781
1704  1.481549
1705  1.517191
1706  1.428534
1707  1.437745

[1708 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2067  0.916379
2068  0.895987
2069  0.904157
2070  0.868770
2071  0.873768

[2072 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1887  0.589143
1888  0.611475
1889  0.622686
1890  0.497712
1891  0.486897

[1892 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1714  1.121927
1715  1.085597
1716  1.103841
1717  1.117674
1718  1.095209

[1719 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2104  1.729812
2105  1.621444
2106  1.632151
2107  1.496613
2108  1.464928

[2109 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1717  0.999104
1718  1.001479
1719  1.000461
1720  0.943156
1721  0.893494

[1722 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1788  0.897069
1789  0.860558
1790  0.868447
1791  0.864946
1792  0.847196

[1793 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2010  0.919927
2011  0.982246
2012  0.980911
2013  1.155046
2014  1.104031

[2015 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2078  0.642599
2079  0.658705
2080  0.591726
2081  0.615701
2082  0.612425

[2083 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2069  0.544890
2070  0.529355
2071  0.545221
2072  0.578169
2073  0.579516

[2074 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1779  0.697747
1780  0.703374
1781  0.618200
1782  0.708394
1783  0.662578

[1784 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1835  1.371537
1836  1.366570
1837  1.347396
1838  1.305259
1839  1.278094

[1840 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1933  1.178256
1934  1.170841
1935  1.163822
1936  1.345611
1937  1.331130

[1938 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1956  0.881651
1957  0.861946
1958  0.889477
1959  0.836642
1960  0.821553

[1961 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1784  0.639428
1785  0.627163
1786  0.637917
1787  0.572743
1788  0.593310

[1789 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2056  0.651425
2057  0.584041
2058  0.534043
2059  0.523943
2060  0.483743

[2061 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1982  2.717496
1983  2.708809
1984  2.639592
1985  2.605485
1986  2.636234

[1987 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1962  1.446676
1963  1.444630
1964  1.381079
1965  1.372226
1966  1.308141

[1967 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2005  0.301307
2006  0.392099
2007  0.437090
2008  0.474366
2009  0.467904

[2010 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1724  0.825341
1725  0.898540
1726  0.927130
1727  1.044772
1728  1.051860

[1729 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1867  1.263826
1868  1.258861
1869  1.250997
1870  1.133377
1871  1.119951

[1872 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1901  1.450785
1902  1.416052
1903  1.285739
1904  1.445727
1905  1.590596

[1906 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2073  1.120627
2074  1.088923
2075  1.091207
2076  1.200597
2077  1.231512

[2078 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1813  1.029840
1814  1.083416
1815  1.177861
1816  1.191013
1817  1.241408

[1818 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1946  1.638996
1947  1.593077
1948  1.542266
1949  1.486189
1950  1.417330

[1951 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2054  0.523272
2055  0.573979
2056  0.534947
2057  0.622127
2058  0.600447

[2059 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1909  1.033936
1910  1.057514
1911  1.095598
1912  1.082382
1913  1.058096

[1914 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2064  0.692311
2065  0.691002
2066  0.668500
2067  0.647029
2068  0.745426

[2069 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1511  0.300921
1512  0.277160
1513  0.157128
1514 -0.023377
1515 -0.055090

[1516 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2035  1.383443
2036  1.353017
2037  1.352761
2038  1.265208
2039  1.242518

[2040 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1989  1.714248
1990  1.679712
1991  1.636185
1992  1.628513
1993  1.626322

[1994 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1726  0.954369
1727  0.868549
1728  0.873308
1729  0.828180
1730  1.018798

[1731 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2010  0.949485
2011  0.927472
2012  0.940569
2013  0.863610
2014  0.818838

[2015 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1759  1.084525
1760  0.994254
1761  0.839052
1762  0.588096
1763  0.494946

[1764 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2043  0.327041
2044  0.365469
2045  0.366118
2046  0.384557
2047  0.340647

[2048 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1708  1.671703
1709  1.670986
1710  1.656575
1711  1.608509
1712  1.611804

[1713 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1817  2.205020
1818  2.187017
1819  2.185331
1820  2.168582
1821  2.150534

[1822 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1736  0.982553
1737  1.026153
1738  1.009153
1739  0.934653
1740  0.905283

[1741 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1954  1.620920
1955  1.620925
1956  1.600350
1957  1.769120
1958  1.706843

[1959 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2005  1.012321
2006  1.006826
2007  0.998903
2008  0.928664
2009  0.913458

[2010 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1818  0.759801
1819  0.756698
1820  0.786194
1821  0.759906
1822  0.712912

[1823 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1836  1.000602
1837  1.089358
1838  1.100244
1839  1.306211
1840  1.332377

[1841 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1941  0.611441
1942  0.644996
1943  0.595901
1944  0.768241
1945  0.724511

[1946 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1833  0.962363
1834  0.894015
1835  0.901925
1836  0.927997
1837  0.934465

[1838 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1781  1.435786
1782  1.499897
1783  1.508854
1784  1.458304
1785  1.465808

[1786 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1799  1.251945
1800  1.243750
1801  1.259050
1802  1.259122
1803  1.257622

[1804 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1724  0.837448
1725  0.882964
1726  0.888920
1727  0.986370
1728  0.965412

[1729 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1995  1.448785
1996  1.439477
1997  1.485391
1998  1.384238
1999  1.368693

[2000 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1822  0.656250
1823  0.647725
1824  0.678001
1825  0.727597
1826  0.716934

[1827 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1776  1.517757
1777  1.521086
1778  1.516990
1779  1.500623
1780  1.457577

[1781 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1780  1.034204
1781  1.035625
1782  1.022844
1783  0.868447
1784  0.817881

[1785 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1783  0.864517
1784  0.884462
1785  0.922191
1786  0.939038
1787  0.940999

[1788 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1881  0.434033
1882  0.433591
1883  0.429966
1884  0.326585
1885  0.311996

[1886 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1883  0.628730
1884  0.620359
1885  0.631611
1886  0.622442
1887  0.638297

[1888 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1962  1.081945
1963  1.049531
1964  1.076375
1965  1.075886
1966  1.080021

[1967 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1958  0.985097
1959  0.979802
1960  0.956784
1961  0.977863
1962  0.956723

[1963 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1583  0.351059
1584  0.355167
1585  0.344604
1586  0.254791
1587  0.195658

[1588 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1729  0.907584
1730  0.844150
1731  0.865012
1732  0.950948
1733  0.952241

[1734 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1900  0.764836
1901  0.774987
1902  0.779712
1903  0.732509
1904  0.762377

[1905 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1926 -0.330531
1927 -0.360036
1928 -0.347786
1929 -0.505329
1930 -0.492772

[1931 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1881  1.382457
1882  1.487184
1883  1.472657
1884  1.461322
1885  1.431332

[1886 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1504  0.834973
1505  0.664319
1506  0.754273
1507  0.669497
1508  0.613690

[1509 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1806  1.385382
1807  1.081948
1808  1.066581
1809  1.135071
1810  1.098705

[1811 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1860  0.702994
1861  0.687239
1862  0.703865
1863  0.735704
1864  0.711072

[1865 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1785  1.879588
1786  1.813582
1787  1.797358
1788  1.446718
1789  1.454333

[1790 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1615  0.898684
1616  0.863435
1617  0.825532
1618  0.736134
1619  0.698340

[1620 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1743  1.454190
1744  1.424988
1745  1.410768
1746  1.374553
1747  1.434005

[1748 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1838  0.814022
1839  0.737817
1840  0.745186
1841  0.677704
1842  0.687895

[1843 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1927  0.538866
1928  0.521481
1929  0.550023
1930  0.495960
1931  0.494711

[1932 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1851  1.500694
1852  1.589463
1853  1.650823
1854  1.804490
1855  1.803914

[1856 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1911  1.431723
1912  1.387182
1913  1.396606
1914  1.375072
1915  1.362292

[1916 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1914  1.103860
1915  1.129622
1916  1.131840
1917  1.024148
1918  0.947988

[1919 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1722  0.289003
1723  0.276767
1724  0.294105
1725  0.250007
1726  0.254518

[1727 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1817  0.528806
1818  0.630690
1819  0.639465
1820  0.633558
1821  0.640732

[1822 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1826 -0.306167
1827 -0.255048
1828 -0.284761
1829 -0.110554
1830 -0.129252

[1831 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1649  0.376901
1650  0.377533
1651  0.356443
1652  0.289527
1653  0.269434

[1654 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1879  0.833683
1880  0.854834
1881  0.851120
1882  0.835711
1883  0.810920

[1884 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1688  1.143844
1689  1.332429
1690  1.299184
1691  1.094246
1692  1.071717

[1693 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1823  0.936944
1824  0.913753
1825  0.906860
1826  0.862723
1827  0.818041

[1828 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1870  0.992905
1871  1.027428
1872  1.019153
1873  1.025401
1874  0.993467

[1875 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1632  1.854213
1633  1.847732
1634  1.877995
1635  1.823194
1636  1.761905

[1637 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1863  0.600642
1864  0.556879
1865  0.586541
1866  0.552691
1867  0.519676

[1868 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1795  0.546260
1796  0.545800
1797  0.553722
1798  0.547808
1799  0.562026

[1800 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1813  1.348242
1814  1.456436
1815  1.337919
1816  1.242880
1817  1.320867

[1818 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1699  1.043612
1700  1.039459
1701  0.990686
1702  0.912877
1703  0.895846

[1704 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1564  0.967039
1565  0.978612
1566  1.002033
1567  0.855791
1568  0.806706

[1569 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1551  1.135502
1552  1.131498
1553  1.072294
1554  1.370928
1555  1.335181

[1556 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1311  1.220539
1312  1.181953
1313  1.173543
1314  0.925675
1315  1.002544

[1316 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1485  0.935672
1486  0.917112
1487  0.931179
1488  0.834526
1489  0.825732

[1490 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1535  1.755551
1536  1.728268
1537  1.684948
1538  1.581167
1539  1.542780

[1540 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1396  0.387264
1397  0.414500
1398  0.509356
1399  0.982901
1400  0.946908

[1401 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1365  1.343881
1366  1.327715
1367  1.350435
1368  1.246925
1369  1.205605

[1370 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1513  1.467930
1514  1.438944
1515  1.460244
1516  1.370581
1517  1.343740

[1518 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1534  0.288273
1535  0.286048
1536  0.217915
1537  0.333032
1538  0.344614

[1539 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1535  1.044327
1536  0.992296
1537  0.924027
1538  0.765556
1539  0.743264

[1540 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1379  0.519508
1380  0.534483
1381  0.573045
1382  0.566999
1383  0.428750

[1384 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1386  1.029348
1387  0.991341
1388  0.990082
1389  0.942267
1390  0.919689

[1391 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1534  0.976656
1535  0.820073
1536  0.773578
1537  0.949943
1538  0.845956

[1539 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1290  0.789638
1291  0.722702
1292  0.679721
1293  0.703398
1294  0.868124

[1295 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1160  0.984970
1161  1.037764
1162  1.048168
1163  1.098147
1164  1.079876

[1165 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1469  0.821059
1470  0.827788
1471  0.838226
1472  0.848205
1473  0.836005

[1474 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1463 -0.157549
1464 -0.108357
1465 -0.078370
1466 -0.151474
1467 -0.157476

[1468 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1302  1.112662
1303  1.098681
1304  1.105672
1305  1.112623
1306  1.122914

[1307 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1427  1.738518
1428  1.721970
1429  1.685862
1430  1.558433
1431  1.506823

[1432 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1387  0.638893
1388  0.655411
1389  0.653292
1390  0.775354
1391  0.762584

[1392 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1360  0.663377
1361  0.682534
1362  0.657714
1363  0.796134
1364  0.711221

[1365 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1305  0.815203
1306  0.834245
1307  0.819582
1308  0.779188
1309  0.769946

[1310 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1309  1.262965
1310  1.255175
1311  1.257853
1312  1.272936
1313  1.250657

[1314 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1260  1.384420
1261  1.379520
1262  1.357250
1263  1.218868
1264  1.201378

[1265 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1362  0.802460
1363  0.985946
1364  0.951831
1365  0.651495
1366  0.628387

[1367 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1339  0.898638
1340  0.907011
1341  0.915445
1342  0.964361
1343  0.959738

[1344 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1337  1.369932
1338  1.417679
1339  1.416921
1340  1.350119
1341  1.346238

[1342 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1306  1.263646
1307  1.323623
1308  1.329152
1309  1.496318
1310  1.362588

[1311 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1137  1.088233
1138  1.135366
1139  1.194888
1140  1.083385
1141  1.077010

[1142 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1328  0.809290
1329  0.808402
1330  0.832639
1331  0.863732
1332  0.867274

[1333 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1334  0.445471
1335  0.450051
1336  0.431200
1337  0.456151
1338  0.449888

[1339 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1206  1.183580
1207  1.183896
1208  1.181536
1209  1.136263
1210  1.138739

[1211 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
874  1.044321
875  1.064714
876  1.091984
877  0.932230
878  0.956259

[879 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1148  0.760256
1149  0.798914
1150  0.651839
1151  0.751347
1152  0.913563

[1153 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1257  1.221917
1258  1.192111
1259  1.207117
1260  1.145657
1261  1.106444

[1262 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1217  0.061375
1218  0.045136
1219  0.057967
1220  0.084425
1221  0.072774

[1222 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1279  1.295849
1280  1.248854
1281  1.220145
1282  1.255473
1283  1.259744

[1284 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1090  0.712653
1091  0.752603
1092  0.786050
1093  0.628543
1094  0.620183

[1095 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1289  0.774318
1290  0.844503
1291  0.834630
1292  0.920577
1293  0.936556

[1294 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1224  2.105719
1225  2.099496
1226  2.032184
1227  1.996678
1228  2.017189

[1229 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1272  0.580949
1273  0.632554
1274  0.638601
1275  0.703118
1276  0.750146

[1277 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1283  0.703289
1284  0.718720
1285  0.756550
1286  0.680960
1287  0.673877

[1288 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1277  0.741814
1278  0.712728
1279  0.734654
1280  0.684746
1281  0.666427

[1282 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1216  1.386170
1217  1.374807
1218  1.361375
1219  1.371139
1220  1.314201

[1221 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1199  0.171031
1200  0.132151
1201  0.147826
1202  0.118045
1203  0.101071

[1204 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1243  0.628352
1244  0.632471
1245  0.575657
1246  0.646000
1247  0.647464

[1248 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1218  0.613725
1219  0.604138
1220  0.593793
1221  0.836474
1222  0.785856

[1223 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1110  1.184192
1111  1.172444
1112  1.154605
1113  1.052541
1114  0.997945

[1115 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1148  1.987205
1149  1.945781
1150  1.914344
1151  1.731809
1152  1.657511

[1153 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1216  0.623727
1217  0.655005
1218  0.638711
1219  0.673548
1220  0.643355

[1221 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1157  0.896750
1158  0.892939
1159  0.903620
1160  0.929886
1161  0.928527

[1162 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1203  0.421717
1204  0.346027
1205  0.365844
1206  0.332006
1207  0.314481

[1208 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1149  0.619804
1150  0.609323
1151  0.645687
1152  0.772439
1153  0.781971

[1154 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1111  0.987958
1112  0.956627
1113  1.006157
1114  1.048676
1115  1.010760

[1116 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1227  1.012352
1228  1.002291
1229  1.021708
1230  0.990272
1231  0.967336

[1232 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1174  0.703916
1175  0.693163
1176  0.666254
1177  0.767006
1178  0.745464

[1179 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1083  0.311931
1084  0.350074
1085  0.359287
1086  0.217990
1087  0.257500

[1088 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1225  0.653286
1226  0.596656
1227  0.610035
1228  0.514688
1229  0.488552

[1230 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1210 -0.207493
1211 -0.175277
1212 -0.118564
1213  0.213688
1214  0.184825

[1215 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1188  1.217097
1189  1.187470
1190  1.183862
1191  1.120993
1192  1.094036

[1193 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1093  1.712179
1094  1.722349
1095  1.837665
1096  1.663535
1097  1.679969

[1098 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1167  1.123536
1168  1.158239
1169  1.134786
1170  1.058147
1171  1.037424

[1172 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1206  0.650189
1207  0.838788
1208  0.740709
1209  0.831024
1210  0.827411

[1211 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1216  0.689504
1217  0.769118
1218  0.754606
1219  0.891609
1220  0.770131

[1221 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
788  0.799696
789  0.835583
790  0.849051
791  0.684959
792  0.695108

[793 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1209  0.680129
1210  0.663609
1211  0.680203
1212  0.669607
1213  0.759825

[1214 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1204  0.860578
1205  0.940158
1206  0.877623
1207  1.061356
1208  1.141690

[1209 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1079  1.941051
1080  1.994117
1081  1.983508
1082  1.955305
1083  1.926578

[1084 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1025  0.861809
1026  0.877627
1027  0.838304
1028  0.890396
1029  0.796510

[1030 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1061  0.314062
1062  0.299202
1063  0.384366
1064  0.322711
1065  0.365939

[1066 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1095  0.824205
1096  0.807580
1097  0.910433
1098  0.926097
1099  0.857905

[1100 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
991  0.798146
992  0.868516
993  0.864361
994  0.844203
995  0.830357

[996 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1096  0.826069
1097  0.806408
1098  0.816714
1099  0.887731
1100  0.913248

[1101 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1105  0.552361
1106  0.548612
1107  0.544520
1108  0.535438
1109  0.533790

[1110 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1089  0.686641
1090  0.641836
1091  0.658243
1092  0.628784
1093  0.564101

[1094 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1095  1.554884
1096  1.533678
1097  1.538352
1098  1.485138
1099  1.458629

[1100 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
954  0.619439
955  0.605494
956  0.644767
957  0.606482
958  0.614207

[959 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1060  0.785106
1061  0.791997
1062  0.790392
1063  0.798755
1064  0.765718

[1065 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1044  0.600002
1045  0.589309
1046  0.619185
1047  0.582329
1048  0.556948

[1049 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1047  0.608132
1048  0.724343
1049  0.682433
1050  0.404680
1051  0.421033

[1052 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1032  0.830372
1033  0.872894
1034  0.866270
1035  1.032725
1036  0.898900

[1037 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1033  1.618796
1034  1.593739
1035  1.601053
1036  1.464278
1037  1.454969

[1038 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1009  0.303100
1010  0.350351
1011  0.344638
1012  0.381233
1013  0.385562

[1014 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
932  0.572301
933  0.642331
934  0.637367
935  0.717977
936  0.695428

[937 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
942  1.516979
943  1.497570
944  1.516301
945  1.417949
946  1.391372

[947 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
986  1.136819
987  1.130024
988  1.165779
989  1.167142
990  1.187012

[991 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
925  1.419494
926  1.411490
927  1.442100
928  1.494959
929  1.564159

[930 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
924  0.932210
925  0.962370
926  1.025403
927  1.108867
928  1.066879

[929 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
990  0.969066
991  0.994569
992  1.012928
993  1.050882
994  1.055575

[995 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
975  0.648547
976  0.610102
977  0.616119
978  0.601015
979  0.626758

[980 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
970  0.221610
971  0.191166
972  0.208692
973  0.144719
974  0.158138

[975 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
905  1.298791
906  1.330318
907  1.383184
908  1.191321
909  1.281088

[910 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
964  1.184201
965  1.233874
966  1.240602
967  1.195223
968  1.196891

[969 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
795  1.115547
796  1.081055
797  1.107036
798  1.084509
799  1.073985

[800 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
915  0.391942
916  0.383951
917  0.399010
918  0.397308
919  0.403662

[920 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
938  1.779438
939  1.814090
940  1.784500
941  1.724283
942  1.679408

[943 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
898  1.156484
899  1.118389
900  1.150389
901  1.079707
902  1.063248

[903 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
928  1.247970
929  1.234319
930  1.179896
931  1.187236
932  1.132419

[933 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
919  0.834287
920  0.789079
921  0.769547
922  0.710478
923  0.746592

[924 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
834  1.740057
835  1.724739
836  1.720705
837  1.609264
838  1.617134

[839 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
864  0.995716
865  1.061072
866  0.897989
867  0.876426
868  0.824004

[869 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
902  1.805272
903  1.765117
904  1.737180
905  1.736842
906  1.672145

[907 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
806  0.598698
807  0.713050
808  0.691356
809  0.686700
810  0.675432

[811 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
893  0.625880
894  0.553798
895  0.561352
896  0.654241
897  0.626620

[898 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
882  0.739322
883  0.772678
884  0.790077
885  0.892099
886  0.876735

[887 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
792  0.652019
793  0.744284
794  0.779976
795  0.830616
796  0.790254

[797 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
865  1.084888
866  1.134542
867  1.064863
868  1.224919
869  1.193200

[870 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
875  1.167433
876  1.197854
877  1.141441
878  1.074938
879  1.005159

[880 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
867  0.460610
868  0.251462
869  0.238625
870  0.263184
871  0.205127

[872 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
854  1.579902
855  1.559995
856  1.535568
857  1.493149
858  1.466395

[859 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
837  1.842751
838  1.815613
839  1.853122
840  2.001039
841  1.909822

[842 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
867  0.768105
868  0.956919
869  0.973895
870  0.996547
871  0.987857

[872 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
860  0.458044
861  0.449590
862  0.430143
863  0.413128
864  0.398428

[865 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
860  0.714826
861  0.700376
862  0.681290
863  0.675191
864  0.678237

[865 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
859  1.341415
860  1.396661
861  1.411602
862  1.357966
863  1.350558

[864 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
858  1.061254
859  0.968771
860  0.848257
861  1.028697
862  1.064313

[863 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
858  0.964856
859  1.039698
860  1.083833
861  1.161075
862  1.162141

[863 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
855  0.956350
856  0.959877
857  0.985673
858  0.921197
859  0.898645

[860 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
850  0.563118
851  0.520945
852  0.424393
853  0.535394
854  0.551449

[855 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
847  0.842342
848  0.885285
849  0.907196
850  0.926493
851  0.903916

[852 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
847  1.489931
848  1.493460
849  1.434862
850  1.315240
851  1.264201

[852 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
836  1.168910
837  1.167179
838  1.179331
839  1.185198
840  1.158806

[841 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
770  2.634739
771  2.603367
772  2.595052
773  2.399345
774  2.298853

[775 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
826  0.606247
827  0.537554
828  0.542833
829  0.824051
830  0.775226

[831 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
818  0.676548
819  0.681720
820  0.699159
821  0.755009
822  0.808935

[823 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
839  0.890853
840  0.886120
841  0.789180
842  0.746335
843  0.740191

[844 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
832  0.689927
833  0.682110
834  0.697746
835  0.679277
836  0.672190

[837 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
828  0.734675
829  0.750125
830  0.736037
831  0.684587
832  0.705897

[833 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
831  0.961518
832  0.946499
833  0.957665
834  1.063994
835  1.045458

[836 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
828  2.172408
829  2.126019
830  2.189260
831  2.136729
832  2.086048

[833 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
824  1.918636
825  1.903809
826  1.910440
827  1.852022
828  1.809987

[829 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
823  0.563762
824  0.599236
825  0.694347
826  0.932897
827  0.874106

[828 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
820  1.152295
821  1.104331
822  1.098165
823  0.965968
824  0.985440

[825 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
816  1.071052
817  1.087561
818  1.104434
819  1.086819
820  1.073056

[821 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
807  2.142145
808  2.114012
809  2.079316
810  1.896983
811  1.947348

[812 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
725  0.708237
726  0.659186
727  0.699198
728  0.926015
729  0.895563

[730 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
801  0.641733
802  0.704530
803  0.678793
804  0.999927
805  1.016023

[806 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
797  1.332306
798  1.296648
799  1.323960
800  1.366176
801  1.393849

[802 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
794  1.614253
795  1.605457
796  1.608560
797  1.583640
798  1.550333

[799 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
665  0.375353
666  0.355406
667  0.395192
668  0.434052
669  0.433868

[670 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
721  0.769624
722  0.693829
723  0.694367
724  0.694685
725  0.798171

[726 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
783  0.389535
784  0.403111
785  0.420775
786  0.320105
787  0.305094

[788 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
783  1.067621
784  1.072735
785  0.997944
786  0.864769
787  0.889357

[788 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
773  0.871586
774  0.957338
775  0.945663
776  0.883642
777  0.868940

[778 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
777  1.743302
778  1.749906
779  1.732551
780  1.729781
781  1.759021

[782 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
781  0.364689
782  0.299204
783  0.307251
784  0.454898
785  0.451125

[786 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
776  1.016251
777  1.028169
778  1.018376
779  0.927790
780  0.912470

[781 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
626 -0.417900
627 -0.384503
628 -0.369636
629 -0.399952
630 -0.417049

[631 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
771  0.820693
772  0.946770
773  0.926376
774  1.082448
775  1.068295

[776 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
694  1.445491
695  1.427268
696  1.389395
697  1.259309
698  1.194001

[699 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
769  0.709934
770  0.686893
771  0.654526
772  0.661739
773  0.684005

[774 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
766  0.916099
767  0.944002
768  0.850006
769  0.758635
770  0.744489

[771 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
758  1.369497
759  1.356953
760  1.387665
761  1.281330
762  1.315986

[763 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
713  0.951934
714  0.939966
715  0.946430
716  0.892551
717  0.893146

[718 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
760  1.153391
761  1.126948
762  1.148550
763  1.160097
764  1.151682

[765 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
693  0.784961
694  0.806517
695  0.784117
696  0.631924
697  0.623269

[698 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
754  0.749366
755  0.802086
756  0.803813
757  0.712781
758  0.677628

[759 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
747  1.141164
748  1.213835
749  1.219266
750  1.233834
751  1.216749

[752 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
748  1.324852
749  1.298287
750  1.268126
751  1.330154
752  1.240565

[753 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
745  1.136114
746  1.335184
747  1.284584
748  1.277106
749  1.260272

[750 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
744  1.737100
745  1.735087
746  1.761313
747  1.736493
748  1.695166

[749 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
721  1.276936
722  1.230062
723  1.234275
724  1.244890
725  1.243233

[726 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
698  0.946239
699  0.985840
700  0.917577
701  0.873224
702  0.810840

[703 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
732  1.153071
733  1.128823
734  1.044964
735  0.885906
736  0.929045

[737 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
715  1.012818
716  0.999216
717  0.972635
718  0.882812
719  0.871471

[720 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
734  1.141610
735  1.129639
736  1.120869
737  1.085139
738  1.062338

[739 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
713  0.966888
714  0.794417
715  0.760589
716  0.855448
717  0.842655

[718 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
726  1.406542
727  1.358330
728  1.329429
729  1.269007
730  1.250450

[731 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
726  1.618258
727  1.595878
728  1.585940
729  1.548660
730  1.509233

[731 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
704  1.192166
705  1.152867
706  1.187412
707  1.078244
708  1.082562

[709 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
707  1.461686
708  1.449969
709  1.465533
710  1.632127
711  1.624830

[712 rows x 1 columns]

            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
705  0.931640
706  0.938038
707  0.953185
708  0.921142
709  0.894358

[710 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
703  0.383863
704  0.403338
705  0.391627
706  0.337907
707  0.319961

[708 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
678  1.372689
679  1.390175
680  1.404875
681  1.288970
682  1.277223

[683 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
690  1.100252
691  1.083338
692  1.070815
693  1.006175
694  0.999058

[695 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
669  0.988688
670  1.075563
671  1.061520
672  0.834790
673  0.802801

[674 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
682  1.561958
683  1.616139
684  1.611383
685  1.601044
686  1.647825

[687 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
682  0.807078
683  0.792079
684  0.802522
685  0.845954
686  0.822463

[687 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
677  2.859741
678  2.847817
679  2.777424
680  2.657463
681  2.591653

[682 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
674  0.744938
675  0.754185
676  0.721792
677  0.750039
678  0.747422

[679 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
669  0.792384
670  0.730238
671  0.719028
672  0.657501
673  0.640277

[674 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
666  0.498730
667  0.491315
668  0.488239
669  0.485394
670  0.464247

[671 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
666  1.421167
667  1.494998
668  1.437224
669  1.339753
670  1.259806

[671 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
652  1.547526
653  1.522316
654  1.554012
655  1.446356
656  1.407584

[657 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
655  1.188062
656  1.178081
657  1.147339
658  1.065030
659  1.030053

[660 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
655  1.074125
656  1.099765
657  1.140531
658  1.025832
659  1.058124

[660 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
656  1.874997
657  1.856640
658  1.806290
659  1.749356
660  1.675361

[661 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
647  0.397561
648  0.443121
649  0.403770
650  0.366857
651  0.342511

[652 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
649  1.703133
650  1.717928
651  1.696273
652  1.699541
653  1.638354

[654 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
645  0.747117
646  0.765538
647  0.839799
648  0.866660
649  0.829030

[650 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
642  0.749183
643  0.621288
644  0.620953
645  0.723320
646  0.707596

[647 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
628  0.469522
629  0.455757
630  0.470000
631  0.401497
632  0.391807

[633 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
629  1.981034
630  1.991179
631  1.973397
632  1.890639
633  1.801907

[634 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
621  1.999546
622  1.995686
623  1.997325
624  1.851387
625  1.796519

[626 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
614  1.369393
615  1.357079
616  1.260500
617  1.105019
618  1.061444

[619 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
611  1.676499
612  1.671196
613  1.672220
614  1.640061
615  1.623825

[616 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
616  0.715907
617  0.682831
618  0.665506
619  0.584088
620  0.569684

[621 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
609  1.503338
610  1.557554
611  1.540291
612  1.392875
613  1.393494

[614 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
608  0.985948
609  1.102082
610  1.055916
611  1.026716
612  1.005186

[613 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
604  1.973900
605  1.965615
606  1.931049
607  2.112955
608  2.124080

[609 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
603  0.965717
604  0.931581
605  0.930137
606  0.880529
607  0.839736

[608 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
599  1.328671
600  1.246109
601  1.151986
602  0.792817
603  0.698421

[604 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
597  0.834405
598  0.812121
599  0.728324
600  0.638568
601  0.643599

[602 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
589  1.745617
590  1.751068
591  1.743645
592  1.793662
593  1.722421

[594 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
576  1.555531
577  1.530935
578  1.585970
579  1.630285
580  1.662389

[581 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
565  1.478813
566  1.424139
567  1.439730
568  1.173980
569  1.172826

[570 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
562  1.006067
563  1.000369
564  1.006115
565  1.055646
566  1.055021

[567 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
563  1.200549
564  1.168739
565  1.178300
566  1.490121
567  1.496134

[568 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
535  0.875504
536  0.901389
537  0.894759
538  1.007699
539  0.951527

[540 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
538  0.710312
539  0.725887
540  0.752779
541  0.785299
542  0.763100

[543 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
475  0.446256
476  0.601670
477  0.566593
478  0.631684
479  0.703754

[480 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
440  0.789389
441  0.771758
442  0.751403
443  0.744128
444  0.733799

[445 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
436  1.353593
437  1.357947
438  1.336938
439  1.239850
440  1.182105

[441 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
424  0.433203
425  0.425825
426  0.427087
427  0.398446
428  0.396645

[429 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
420  1.158793
421  1.146193
422  1.172533
423  1.112219
424  1.091902

[425 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
425  1.808316
426  1.792124
427  1.793884
428  1.686449
429  1.616545

[430 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
403  1.175144
404  1.160487
405  1.215366
406  1.284475
407  1.283176

[408 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
406  0.902262
407  0.947525
408  0.951443
409  0.838689
410  0.845118

[411 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
380  0.725088
381  0.672874
382  0.697814
383  0.721119
384  0.748187

[385 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
375  0.832171
376  0.843861
377  0.809881
378  0.902585
379  0.876614

[380 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
379  1.427819
380  1.434264
381  1.437468
382  1.362478
383  1.347248

[384 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
346  1.235858
347  1.206575
348  1.266653
349  1.390346
350  1.382997

[351 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
340  1.109632
341  1.160205
342  1.162687
343  1.286242
344  1.303522

[345 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
335  1.944331
336  1.928595
337  1.939619
338  1.999659
339  1.985514

[340 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
347  0.462098
348  0.447747
349  0.445493
350  0.415107
351  0.424820

[352 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
323  0.736908
324  0.718881
325  0.729183
326  0.776871
327  0.779699

[328 rows x 1 columns]

            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
314  0.924326
315  0.996399
316  0.943803
317  1.331383
318  1.333015

[319 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
310  1.344400
311  1.354609
312  1.327938
313  1.205145
314  1.186792

[315 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
301  1.646385
302  1.646381
303  1.642709
304  1.403452
305  1.366443

[306 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
275  0.595726
276  0.741922
277  0.736443
278  1.138535
279  1.115808

[280 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
265  1.590849
266  1.630291
267  1.615389
268  1.361458
269  1.331492

[270 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
247  0.555415
248  0.593187
249  0.457775
250  0.628134
251  0.601130

[252 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
220  1.520217
221  1.607718
222  1.639164
223  1.572168
224  1.556349

[225 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
303  0.773429
304  0.674228
305  0.674706
306  0.608873
307  0.635429

[308 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
199  1.555678
200  1.533588
201  1.540431
202  1.580597
203  1.619562

[204 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
210  0.838677
211  0.891027
212  0.891308
213  0.948076
214  1.003047

[215 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
191  1.760574
192  1.747875
193  1.799747
194  1.811141
195  1.780932

[196 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
184  1.258951
185  1.302216
186  1.313342
187  1.215915
188  1.318799

[189 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
160  0.761102
161  0.757465
162  0.782151
163  0.736929
164  0.726999

[165 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
161  1.209169
162  1.164181
163  1.126033
164  1.049353
165  0.999876

[166 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
215  0.747769
216  0.752085
217  0.757479
218  0.719159
219  0.743445

[220 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
151  1.421153
152  1.437558
153  1.410838
154  1.453450
155  1.451485

[156 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
134  1.112842
135  1.131350
136  1.156240
137  1.328128
138  1.258025

[139 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
135  1.024859
136  0.981426
137  0.996970
138  1.140325
139  1.141976

[140 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
124  2.413262
125  2.424919
126  2.356124
127  2.343585
128  2.264847

[129 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
106  1.464427
107  1.522660
108  1.474010
109  1.404847
110  1.411609

[111 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
116  1.580936
117  1.582056
118  1.628323
119  1.545471
120  1.512454

[121 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
111  1.576419
112  1.566807
113  1.541203
114  1.432670
115  1.391472

[116 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
95  2.104533
96  2.136428
97  2.077933
98  1.897497
99  1.914962

[100 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
73  0.662341
74  0.583344
75  0.629712
76  0.854904
77  0.834067

[78 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
66  0.534221
67  0.711195
68  0.679099
69  0.697118
70  0.735377

[71 rows x 1 columns]
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
36 NaN
37 NaN
38 NaN
39 NaN
40 NaN
41 NaN
42 NaN
43 NaN
44 NaN
45 NaN
46 NaN
47 NaN
48 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
36 NaN
37 NaN
38 NaN
39 NaN
40 NaN
41 NaN
42 NaN
43 NaN
44 NaN
45 NaN
46 NaN
47 NaN
48 NaN
49 NaN
50 NaN
51 NaN
52 NaN
53 NaN
54 NaN
55 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
36 NaN
37 NaN
38 NaN
39 NaN
40 NaN
41 NaN
42 NaN
43 NaN
44 NaN
45 NaN
46 NaN
47 NaN
48 NaN
49 NaN
50 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
36 NaN
37 NaN
38 NaN
39 NaN
40 NaN
41 NaN
42 NaN
43 NaN
44 NaN
45 NaN
46 NaN
47 NaN
48 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
36 NaN
37 NaN
38 NaN
39 NaN
40 NaN
41 NaN
42 NaN
43 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
36 NaN
37 NaN
38 NaN
39 NaN
40 NaN
41 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
36 NaN
37 NaN
38 NaN
39 NaN
40 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
36 NaN
37 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
198  0.397424
199  0.386141
200  0.394031
201  0.389321
202  0.388486

[203 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2451  1.456958
2452  1.398984
2453  1.412334
2454  1.374836
2455  1.404315

[2456 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2426  2.682196
2427  2.648544
2428  2.768145
2429  2.592769
2430  2.549492

[2431 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2423  0.707966
2424  0.733623
2425  0.720947
2426  0.897171
2427  0.877252

[2428 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2370  1.380217
2371  1.383395
2372  1.378838
2373  1.303781
2374  1.266900

[2375 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2462  1.113672
2463  1.095011
2464  1.147803
2465  0.991658
2466  0.970809

[2467 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2410  0.791240
2411  0.814509
2412  0.801970
2413  0.793912
2414  0.804570

[2415 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2414  1.504313
2415  1.611167
2416  1.544686
2417  1.630866
2418  1.570488

[2419 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2358  0.361631
2359  0.362271
2360  0.406156
2361  0.329966
2362  0.409758

[2363 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2403  1.351599
2404  1.370858
2405  1.376257
2406  1.405946
2407  1.333210

[2408 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2205  1.885945
2206  1.867794
2207  1.872317
2208  1.912406
2209  1.979817

[2210 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2363  1.491316
2364  1.407893
2365  1.362021
2366  1.260911
2367  1.219758

[2368 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2446  0.774112
2447  0.830343
2448  0.824933
2449  0.867684
2450  0.904617

[2451 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2367  1.625096
2368  1.579292
2369  1.595613
2370  1.438831
2371  1.467441

[2372 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2482  1.835611
2483  1.769225
2484  1.663033
2485  1.727159
2486  1.665509

[2487 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2520  0.894494
2521  0.864545
2522  0.902697
2523  0.877372
2524  0.825274

[2525 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2453  0.718956
2454  0.731650
2455  0.701061
2456  0.617408
2457  0.526532

[2458 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2490  1.533577
2491  1.532667
2492  1.581397
2493  1.551546
2494  1.527826

[2495 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2458  1.600429
2459  1.482415
2460  1.464518
2461  1.430741
2462  1.392094

[2463 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2462  1.381243
2463  1.378812
2464  1.346616
2465  1.238039
2466  1.170802

[2467 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2366  1.591689
2367  1.707873
2368  1.689451
2369  1.690007
2370  1.521264

[2371 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2508  0.997451
2509  1.032031
2510  1.044743
2511  1.055360
2512  1.037999

[2513 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2348  1.193290
2349  1.199417
2350  1.190188
2351  1.090095
2352  1.016346

[2353 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2432  1.269290
2433  1.226766
2434  1.251498
2435  1.495791
2436  1.391772

[2437 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2534  1.339835
2535  1.330714
2536  1.352180
2537  1.335000
2538  1.331794

[2539 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2127  1.938971
2128  1.936245
2129  1.932659
2130  1.722028
2131  1.691667

[2132 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2421  1.072869
2422  1.042269
2423  1.029889
2424  0.877254
2425  0.819923

[2426 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2349  0.861390
2350  0.877100
2351  0.900687
2352  0.737764
2353  0.732154

[2354 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1710  0.928760
1711  0.889054
1712  0.861082
1713  0.808591
1714  0.849066

[1715 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2422  1.133305
2423  0.982458
2424  1.028446
2425  0.946562
2426  0.936636

[2427 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2348  0.735175
2349  0.808442
2350  0.781771
2351  1.045395
2352  0.982924

[2353 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2406  1.980302
2407  2.048960
2408  2.062561
2409  1.980346
2410  2.073974

[2411 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2315  1.215448
2316  1.128526
2317  1.150050
2318  1.092855
2319  1.068316

[2320 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2524  1.884467
2525  1.864279
2526  1.867717
2527  1.941592
2528  1.890364

[2529 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2447  1.065880
2448  1.086394
2449  1.022400
2450  0.838072
2451  0.770618

[2452 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2407  2.148133
2408  2.138103
2409  2.155519
2410  2.133133
2411  2.068895

[2412 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2461  1.683970
2462  1.700431
2463  1.679874
2464  1.587675
2465  1.526785

[2466 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2451  1.777417
2452  1.759221
2453  1.758960
2454  1.791039
2455  1.733141

[2456 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2141  1.495134
2142  1.477562
2143  1.503529
2144  1.457976
2145  1.449222

[2146 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2531  0.888683
2532  0.921863
2533  0.881948
2534  0.850532
2535  0.840440

[2536 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2302  1.428925
2303  1.351599
2304  1.317571
2305  1.183280
2306  1.146260

[2307 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2486  1.638156
2487  1.742607
2488  1.752286
2489  1.662062
2490  1.677738

[2491 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2510  2.210417
2511  2.214140
2512  2.211323
2513  2.002944
2514  1.935443

[2515 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2191  1.419398
2192  1.408479
2193  1.477025
2194  1.428128
2195  1.374005

[2196 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2329  1.603705
2330  1.580749
2331  1.648312
2332  1.659363
2333  1.632915

[2334 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2478  1.742690
2479  1.677164
2480  1.657122
2481  1.551234
2482  1.501816

[2483 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2386  1.619684
2387  1.680653
2388  1.658065
2389  1.414686
2390  1.369348

[2391 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2325  2.032054
2326  2.016163
2327  2.022698
2328  2.035399
2329  1.982218

[2330 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2448  1.563774
2449  1.760985
2450  1.746940
2451  1.818462
2452  1.771551

[2453 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2294  0.324726
2295  0.357850
2296  0.348601
2297  0.421144
2298  0.384954

[2299 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2389  1.688012
2390  1.803399
2391  1.779672
2392  1.955604
2393  1.937939

[2394 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2288  2.577837
2289  2.629624
2290  2.630616
2291  2.682366
2292  2.627834

[2293 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2310  1.979918
2311  2.007606
2312  2.025661
2313  2.039117
2314  2.094245

[2315 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2341  1.359964
2342  1.336007
2343  1.369216
2344  1.301947
2345  1.254939

[2346 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2382  1.954549
2383  1.873106
2384  1.832615
2385  1.730898
2386  1.741695

[2387 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2439  1.188433
2440  1.196260
2441  1.202091
2442  1.182734
2443  1.151994

[2444 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2191  0.912857
2192  0.896413
2193  0.916913
2194  0.907136
2195  1.046702

[2196 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2308  1.352786
2309  1.373792
2310  1.374427
2311  1.316746
2312  1.298561

[2313 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2302  1.655141
2303  1.641226
2304  1.636152
2305  1.560476
2306  1.575439

[2307 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2430  1.662895
2431  1.654403
2432  1.694208
2433  1.866619
2434  1.829267

[2435 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2331  1.596930
2332  1.594695
2333  1.443829
2334  1.543647
2335  1.443134

[2336 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2343  1.364271
2344  1.281431
2345  1.277581
2346  1.360257
2347  1.334861

[2348 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2208  2.174986
2209  2.182381
2210  2.119889
2211  1.996969
2212  2.053744

[2213 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2384  1.306995
2385  1.295444
2386  1.289235
2387  1.288897
2388  1.279800

[2389 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2269  0.986167
2270  0.997238
2271  1.015079
2272  1.069462
2273  1.060329

[2274 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2438  1.071489
2439  1.068351
2440  1.064999
2441  1.133060
2442  1.117448

[2443 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2375  1.000203
2376  1.009093
2377  1.038842
2378  1.117645
2379  1.077073

[2380 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2378  0.866579
2379  0.849729
2380  0.848575
2381  0.780268
2382  0.781724

[2383 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2367  0.836958
2368  0.808177
2369  0.851388
2370  0.816702
2371  0.766528

[2372 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2388  0.995540
2389  0.949355
2390  0.949297
2391  1.039386
2392  1.050703

[2393 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1911  1.907647
1912  1.943960
1913  1.927228
1914  1.875089
1915  1.847021

[1916 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2400  1.932733
2401  1.924587
2402  1.893865
2403  1.805665
2404  1.881101

[2405 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2358  1.778232
2359  1.766087
2360  1.771532
2361  1.744317
2362  1.708388

[2363 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2394  1.957539
2395  1.973369
2396  1.978130
2397  1.896948
2398  1.874501

[2399 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2374  1.840735
2375  1.825442
2376  1.852841
2377  1.773590
2378  1.767475

[2379 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2331  1.279957
2332  1.251606
2333  1.242598
2334  1.211875
2335  1.173148

[2336 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2388  1.961107
2389  1.940071
2390  1.936618
2391  1.857555
2392  1.838711

[2393 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2378  2.102964
2379  2.048293
2380  2.015603
2381  1.908682
2382  1.830393

[2383 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2437  1.535128
2438  1.523707
2439  1.532939
2440  1.543573
2441  1.505207

[2442 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2073  0.670276
2074  0.757740
2075  0.748796
2076  0.706035
2077  0.703140

[2078 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2251  1.961923
2252  1.946838
2253  1.956379
2254  1.938379
2255  1.919915

[2256 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2429  1.215110
2430  1.217462
2431  1.217832
2432  1.174810
2433  1.168499

[2434 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2330  2.325391
2331  2.301106
2332  2.283675
2333  2.181849
2334  2.131280

[2335 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2338  1.038902
2339  1.129980
2340  1.104441
2341  1.137798
2342  1.148303

[2343 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2234  2.231587
2235  2.234184
2236  2.176870
2237  2.333549
2238  2.295465

[2239 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2265  0.954309
2266  0.975877
2267  0.934490
2268  0.820490
2269  0.798860

[2270 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2204  1.073892
2205  1.196749
2206  1.203411
2207  1.498177
2208  1.452948

[2209 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1992  2.314702
1993  2.310343
1994  2.280850
1995  2.280347
1996  2.273965

[1997 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1972  1.126199
1973  1.111140
1974  1.103990
1975  0.957863
1976  0.913095

[1977 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2169  0.877672
2170  0.899951
2171  0.848770
2172  0.745954
2173  0.951430

[2174 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2338  0.928411
2339  0.910765
2340  0.904883
2341  0.820980
2342  0.804463

[2343 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2256  1.016644
2257  1.039368
2258  0.988620
2259  0.834388
2260  0.798552

[2261 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2160  0.839047
2161  0.797272
2162  0.815581
2163  0.659752
2164  0.650230

[2165 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2308  1.054834
2309  1.155340
2310  1.081216
2311  1.176356
2312  1.161047

[2313 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2331  1.161775
2332  1.129041
2333  1.089634
2334  0.976599
2335  0.987869

[2336 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2275  1.625604
2276  1.670166
2277  1.522238
2278  1.430808
2279  1.411681

[2280 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2304  1.324181
2305  1.502736
2306  1.607118
2307  1.740307
2308  1.807854

[2309 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2189  1.449658
2190  1.449470
2191  1.367178
2192  1.435137
2193  1.382044

[2194 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2225  1.464154
2226  1.449325
2227  1.447356
2228  1.385882
2229  1.382959

[2230 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2130  1.465200
2131  1.450821
2132  1.297810
2133  1.240723
2134  1.218421

[2135 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2316  1.575208
2317  1.556231
2318  1.553946
2319  1.466040
2320  1.427423

[2321 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2303  2.314338
2304  2.296762
2305  2.306801
2306  2.088881
2307  2.076499

[2308 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2302  0.456694
2303  0.439741
2304  0.457065
2305  0.443819
2306  0.417834

[2307 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1682  1.409945
1683  1.423662
1684  1.461900
1685  1.408605
1686  1.376532

[1687 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2387  1.016384
2388  0.966391
2389  0.972851
2390  0.905874
2391  0.894393

[2392 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2328  0.404944
2329  0.363957
2330  0.342159
2331  0.170580
2332  0.167733

[2333 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2384  0.908628
2385  0.894041
2386  0.910970
2387  0.857544
2388  0.840372

[2389 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2059  0.815901
2060  0.795102
2061  0.810034
2062  0.824969
2063  0.780446

[2064 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2033  1.360407
2034  1.449874
2035  1.444865
2036  1.379739
2037  1.451095

[2038 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2149  0.666700
2150  0.680501
2151  0.632220
2152  0.653638
2153  0.629055

[2154 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2178  0.933641
2179  0.925051
2180  0.894383
2181  0.697023
2182  0.676700

[2183 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2196  1.474128
2197  1.495619
2198  1.445418
2199  1.351888
2200  1.312694

[2201 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2240  2.121137
2241  2.130170
2242  2.233407
2243  2.300653
2244  2.229777

[2245 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2306  1.218453
2307  1.196760
2308  1.171655
2309  1.111560
2310  1.080001

[2311 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2346  2.395434
2347  2.383711
2348  2.375958
2349  2.388275
2350  2.367760

[2351 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2087 -0.092722
2088  0.080466
2089  0.139843
2090  0.503514
2091  0.494471

[2092 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2281  1.381216
2282  1.371245
2283  1.384558
2284  1.399393
2285  1.553223

[2286 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2228  2.155833
2229  2.127766
2230  2.069678
2231  1.965794
2232  1.941424

[2233 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2327  1.124144
2328  1.131772
2329  1.114366
2330  1.096104
2331  1.079823

[2332 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2252  1.173220
2253  1.084227
2254  1.074721
2255  1.025468
2256  0.991505

[2257 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2326  0.963323
2327  0.989965
2328  1.044077
2329  0.991829
2330  1.082287

[2331 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2290  0.979830
2291  1.012028
2292  1.029966
2293  0.989975
2294  0.915140

[2295 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2107  2.133758
2108  2.117849
2109  2.094952
2110  2.072039
2111  2.038890

[2112 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2345  0.859626
2346  0.895969
2347  0.916625
2348  0.870542
2349  0.872295

[2350 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2221  0.684140
2222  0.750064
2223  0.693501
2224  0.793011
2225  0.739588

[2226 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2238  1.128766
2239  1.104662
2240  1.105960
2241  0.830979
2242  0.824626

[2243 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2357  0.617119
2358  0.696755
2359  0.703337
2360  0.699281
2361  0.724919

[2362 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2199  1.391390
2200  1.383794
2201  1.412355
2202  1.360432
2203  1.335474

[2204 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2314  0.956752
2315  0.942581
2316  0.949591
2317  1.032801
2318  1.003411

[2319 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2225  1.647335
2226  1.626746
2227  1.604980
2228  1.541060
2229  1.509464

[2230 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1992  1.412554
1993  1.457476
1994  1.461390
1995  1.367567
1996  1.350218

[1997 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2235  1.397668
2236  1.377895
2237  1.375120
2238  1.361907
2239  1.324199

[2240 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2224  1.233126
2225  1.186210
2226  1.163513
2227  1.013268
2228  0.988541

[2229 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1968  1.987015
1969  1.986212
1970  1.989162
1971  1.842593
1972  1.815588

[1973 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2212  1.144743
2213  1.146433
2214  1.143084
2215  1.112498
2216  1.096226

[2217 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2269  2.095432
2270  2.078823
2271  2.101219
2272  2.243417
2273  2.216306

[2274 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2277  1.080517
2278  1.066296
2279  1.085458
2280  1.066349
2281  1.055899

[2282 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2311  1.074284
2312  1.033160
2313  1.015393
2314  0.932775
2315  0.848082

[2316 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2323  1.556306
2324  1.544023
2325  1.570236
2326  1.533266
2327  1.534396

[2328 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2126  1.549363
2127  1.466075
2128  1.453421
2129  1.411077
2130  1.402779

[2131 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2234  1.476778
2235  1.666416
2236  1.635695
2237  1.329826
2238  1.407736

[2239 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2064  1.047368
2065  1.073962
2066  1.111341
2067  0.913971
2068  0.860717

[2069 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1908  1.539695
1909  1.625727
1910  1.589854
1911  1.349781
1912  1.331478

[1913 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2227  1.337903
2228  1.303007
2229  1.344091
2230  1.117828
2231  1.126551

[2232 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2174  1.050279
2175  1.024983
2176  1.033205
2177  0.971797
2178  0.946460

[2179 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2143  0.894562
2144  0.895541
2145  1.024479
2146  0.905699
2147  0.932412

[2148 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2293  1.232040
2294  1.242744
2295  1.190080
2296  1.142225
2297  1.102425

[2298 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2007  1.275435
2008  1.280273
2009  1.285909
2010  1.234043
2011  1.327951

[2012 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1895  1.677166
1896  1.686854
1897  1.768922
1898  1.765994
1899  1.726389

[1900 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2117  1.088949
2118  1.073373
2119  1.122291
2120  1.151827
2121  1.134257

[2122 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2213  0.256074
2214  0.276219
2215  0.312606
2216  0.226362
2217  0.112891

[2218 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2115  1.476597
2116  1.493967
2117  1.494133
2118  1.478472
2119  1.468216

[2120 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2178  0.883235
2179  0.815115
2180  0.796663
2181  0.701988
2182  0.672684

[2183 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2272  1.061528
2273  1.033892
2274  1.057213
2275  0.934089
2276  0.925816

[2277 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2266  1.863265
2267  1.825963
2268  1.825073
2269  1.809717
2270  1.751349

[2271 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2019  1.067834
2020  1.129771
2021  1.124031
2022  1.013730
2023  1.072670

[2024 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2050  1.665642
2051  1.679060
2052  1.667477
2053  1.650727
2054  1.627344

[2055 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2157  0.597894
2158  0.598404
2159  0.581576
2160  0.559593
2161  0.540045

[2162 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2142  1.100146
2143  1.053196
2144  1.051076
2145  1.006126
2146  0.980985

[2147 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2221  2.543100
2222  2.541432
2223  2.590796
2224  2.820777
2225  2.812079

[2226 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2080  1.343753
2081  1.317301
2082  1.273194
2083  1.316127
2084  1.325141

[2085 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2134  1.643167
2135  1.634999
2136  1.635013
2137  1.625141
2138  1.639419

[2139 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1885  0.577670
1886  0.526017
1887  0.618598
1888  0.660314
1889  0.726587

[1890 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1987  1.234083
1988  1.230368
1989  1.242595
1990  1.392593
1991  1.379982

[1992 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2085  0.796177
2086  0.819780
2087  0.829607
2088  0.709244
2089  0.639674

[2090 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2059  1.738256
2060  1.732700
2061  1.827296
2062  1.691620
2063  1.735733

[2064 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2202  1.547405
2203  1.468554
2204  1.489691
2205  1.388403
2206  1.366434

[2207 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2056  1.273457
2057  1.309822
2058  1.352674
2059  1.268710
2060  1.177157

[2061 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2022  1.535409
2023  1.587402
2024  1.606638
2025  1.650941
2026  1.623667

[2027 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2211  1.594688
2212  1.612138
2213  1.578426
2214  1.483990
2215  1.453775

[2216 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2273  1.137361
2274  1.146152
2275  1.140565
2276  1.208052
2277  1.166641

[2278 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2277  1.044980
2278  1.032602
2279  1.025368
2280  0.961919
2281  0.949467

[2282 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1961  1.715762
1962  1.676442
1963  1.668316
1964  1.538969
1965  1.455893

[1966 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2234  0.342515
2235  0.294874
2236  0.273421
2237  0.424017
2238  0.476717

[2239 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2246  0.552923
2247  0.591978
2248  0.570863
2249  0.597850
2250  0.623618

[2251 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2135  1.344000
2136  1.336293
2137  1.359186
2138  1.421507
2139  1.387309

[2140 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2191  0.928394
2192  0.907576
2193  0.899036
2194  0.772989
2195  0.686713

[2196 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2169  0.819770
2170  0.812020
2171  0.820805
2172  0.823298
2173  0.816483

[2174 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2114  1.431032
2115  1.406487
2116  1.439605
2117  1.370242
2118  1.343062

[2119 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2105  0.373126
2106  0.349440
2107  0.386263
2108  0.485125
2109  0.543418

[2110 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2145  0.517892
2146  0.704547
2147  0.669298
2148  0.464382
2149  0.445580

[2150 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2120  1.717873
2121  1.696204
2122  1.770010
2123  1.705448
2124  1.697332

[2125 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2168  2.167414
2169  2.162176
2170  2.060321
2171  1.984253
2172  1.969887

[2173 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1931  1.324576
1932  1.526604
1933  1.513718
1934  1.643458
1935  1.618061

[1936 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2217  0.729761
2218  0.683865
2219  0.607862
2220  0.588326
2221  0.545429

[2222 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2041  1.507278
2042  1.602485
2043  1.574421
2044  1.522933
2045  1.503834

[2046 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2153  1.473396
2154  1.459581
2155  1.476525
2156  1.427935
2157  1.387457

[2158 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1994  0.611194
1995  0.680662
1996  0.642477
1997  0.752802
1998  0.728392

[1999 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2029  1.173034
2030  1.164820
2031  1.191742
2032  1.307156
2033  1.300356

[2034 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2156  1.443877
2157  1.470653
2158  1.478953
2159  1.546948
2160  1.465347

[2161 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1942  0.783753
1943  0.971018
1944  1.017467
1945  0.945660
1946  1.096767

[1947 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2239  0.615096
2240  0.605737
2241  0.627254
2242  0.647917
2243  0.638379

[2244 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2054  0.513829
2055  0.529723
2056  0.514444
2057  0.705507
2058  0.667790

[2059 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2112  0.938527
2113  0.941199
2114  0.934881
2115  0.984024
2116  0.966515

[2117 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2088  1.242260
2089  1.248992
2090  1.260617
2091  1.210298
2092  1.189824

[2093 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1935  0.703062
1936  0.696109
1937  0.631082
1938  0.437198
1939  0.429150

[1940 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1972  0.499001
1973  0.455074
1974  0.412360
1975  0.448318
1976  0.457098

[1977 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2084  0.567978
2085  0.665232
2086  0.655404
2087  0.673357
2088  0.671748

[2089 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2194  1.358956
2195  1.297260
2196  1.269489
2197  1.108454
2198  1.065064

[2199 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1923  1.771381
1924  1.757518
1925  1.777792
1926  1.723790
1927  1.720087

[1928 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2225  1.949594
2226  1.954280
2227  1.993927
2228  2.058896
2229  1.968657

[2230 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2153  1.190426
2154  1.165158
2155  1.243421
2156  1.082988
2157  1.052850

[2158 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2234  1.568343
2235  1.573907
2236  1.528465
2237  1.458769
2238  1.376501

[2239 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2199  1.603538
2200  1.632688
2201  1.617614
2202  1.546835
2203  1.515438

[2204 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2227  1.330373
2228  1.490169
2229  1.416449
2230  1.214198
2231  1.166258

[2232 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2178  2.926550
2179  2.887031
2180  2.907403
2181  2.917818
2182  2.886074

[2183 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2034  1.268751
2035  1.268154
2036  1.192774
2037  1.032917
2038  0.981995

[2039 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1900  1.310454
1901  1.287143
1902  1.123202
1903  1.146011
1904  1.084303

[1905 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2181  1.253694
2182  1.200093
2183  1.237842
2184  1.278108
2185  1.245310

[2186 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2184  0.725190
2185  0.767035
2186  0.707589
2187  0.719582
2188  0.607188

[2189 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2037  1.686016
2038  1.707250
2039  1.687445
2040  1.767797
2041  1.743386

[2042 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1983  1.985832
1984  1.970601
1985  1.929383
1986  1.789033
1987  1.737183

[1988 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2169  0.887955
2170  0.870376
2171  0.886426
2172  0.881715
2173  0.867681

[2174 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2182  1.325296
2183  1.253078
2184  1.240551
2185  1.341252
2186  1.359640

[2187 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1748  1.618289
1749  1.635895
1750  1.702142
1751  1.738436
1752  1.555549

[1753 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2183  1.741941
2184  1.745893
2185  1.753512
2186  1.649614
2187  1.634552

[2188 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2196  1.371216
2197  1.373934
2198  1.379251
2199  1.388306
2200  1.363826

[2201 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1986  1.462463
1987  1.440712
1988  1.435477
1989  1.288910
1990  1.248688

[1991 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1990  0.322271
1991  0.307767
1992  0.434347
1993  0.424056
1994  0.372755

[1995 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2127  1.164997
2128  1.151606
2129  1.134475
2130  1.054416
2131  1.027727

[2132 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1888  1.422945
1889  1.412174
1890  1.418175
1891  1.362413
1892  1.347192

[1893 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1958  2.380242
1959  2.401827
1960  2.427155
1961  2.395493
1962  2.375462

[1963 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2118  0.811905
2119  0.862707
2120  0.867409
2121  1.139162
2122  1.287901

[2123 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2032  0.675286
2033  0.645230
2034  0.623545
2035  0.542109
2036  0.480827

[2037 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2085  1.616067
2086  1.638785
2087  1.633157
2088  1.539145
2089  1.485882

[2090 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2106  1.543266
2107  1.541708
2108  1.454366
2109  1.399832
2110  1.371414

[2111 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2130  0.929651
2131  0.917573
2132  0.919686
2133  0.870655
2134  0.846268

[2135 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2040  1.806576
2041  1.846095
2042  1.864162
2043  1.972673
2044  1.947708

[2045 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2067  1.659372
2068  1.664489
2069  1.671681
2070  1.707613
2071  1.685915

[2072 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2179  1.270218
2180  1.236256
2181  1.274777
2182  1.245879
2183  1.216704

[2184 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2103  1.458211
2104  1.469474
2105  1.468002
2106  1.453511
2107  1.431208

[2108 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2085  0.298424
2086  0.397545
2087  0.410969
2088  0.524283
2089  0.629854

[2090 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2100  1.733319
2101  1.744523
2102  1.734016
2103  1.979212
2104  1.955766

[2105 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2048  2.283750
2049  2.290880
2050  2.313037
2051  2.242937
2052  2.206797

[2053 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2146  2.266924
2147  2.260316
2148  2.257662
2149  2.091991
2150  2.034287

[2151 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2059  1.145643
2060  1.141441
2061  1.143008
2062  1.095609
2063  1.088330

[2064 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1946  0.958343
1947  1.022673
1948  0.967161
1949  0.886573
1950  0.829186

[1951 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2102  1.477725
2103  1.506806
2104  1.500969
2105  1.438810
2106  1.410504

[2107 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2028  1.062297
2029  1.054254
2030  1.084795
2031  1.014111
2032  1.006947

[2033 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2052  1.592905
2053  1.595280
2054  1.586546
2055  1.525191
2056  1.469563

[2057 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1890  1.958546
1891  1.931622
1892  1.907853
1893  1.847481
1894  1.793721

[1895 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2003  1.064700
2004  1.044343
2005  1.017840
2006  1.039255
2007  0.977449

[2008 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2078  1.485649
2079  1.623884
2080  1.577063
2081  1.497803
2082  1.438186

[2083 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2160  1.512647
2161  1.492435
2162  1.475966
2163  1.455213
2164  1.404768

[2165 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2167  0.590694
2168  0.765496
2169  0.628933
2170  0.609369
2171  0.521282

[2172 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1909  0.987323
1910  0.999756
1911  1.015578
1912  0.964951
1913  0.946198

[1914 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2017  1.698548
2018  1.709378
2019  1.699186
2020  1.718484
2021  1.662001

[2022 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2040  2.285161
2041  2.270662
2042  2.230893
2043  2.017845
2044  1.967720

[2045 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2039  2.235200
2040  2.230528
2041  2.232013
2042  2.176884
2043  2.143674

[2044 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2043  1.423668
2044  1.403585
2045  1.450473
2046  1.242426
2047  1.290554

[2048 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2005  1.867518
2006  1.802606
2007  1.782045
2008  1.713025
2009  1.673748

[2010 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2085  2.067484
2086  2.124249
2087  2.035752
2088  2.121828
2089  1.963952

[2090 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2053  0.948611
2054  0.970606
2055  0.968889
2056  0.985862
2057  0.963337

[2058 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2119  0.737105
2120  0.756032
2121  0.731577
2122  0.693228
2123  0.713300

[2124 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1991  1.348877
1992  1.692139
1993  1.791993
1994  1.572203
1995  1.526663

[1996 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2098  0.798814
2099  0.791772
2100  0.814935
2101  0.688094
2102  0.652976

[2103 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2141  1.000926
2142  0.981592
2143  1.012303
2144  0.994362
2145  0.991874

[2146 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2116  1.571997
2117  1.573203
2118  1.591226
2119  1.568970
2120  1.560904

[2121 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2056  2.201316
2057  2.156252
2058  1.985027
2059  1.941436
2060  1.821451

[2061 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2069  0.939518
2070  0.946401
2071  0.921575
2072  0.754232
2073  0.647122

[2074 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2031  0.748331
2032  0.731846
2033  0.749973
2034  0.681463
2035  0.676556

[2036 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1996  1.913270
1997  1.912630
1998  1.906022
1999  1.812950
2000  1.751817

[2001 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2118  1.578396
2119  1.503230
2120  1.510010
2121  1.520464
2122  1.479288

[2123 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1998  1.470752
1999  1.472078
2000  1.435934
2001  1.823853
2002  1.819626

[2003 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1735  1.178799
1736  1.151700
1737  1.157380
1738  1.196618
1739  1.215637

[1740 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1957  0.885144
1958  0.893055
1959  0.868309
1960  0.919783
1961  0.886000

[1962 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1551  0.847874
1552  0.911881
1553  0.943102
1554  0.928218
1555  0.897551

[1556 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1852  1.434527
1853  1.427892
1854  1.453912
1855  1.427329
1856  1.403739

[1857 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2105  1.833548
2106  1.831589
2107  1.802477
2108  1.580330
2109  1.532950

[2110 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1906  1.525384
1907  1.536052
1908  1.539947
1909  1.487607
1910  1.403577

[1911 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1940  1.255845
1941  1.258717
1942  1.230376
1943  1.302473
1944  1.204991

[1945 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1962  0.722655
1963  0.900286
1964  0.991698
1965  1.100120
1966  1.033709

[1967 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2073  1.207707
2074  1.178794
2075  1.115412
2076  1.023588
2077  1.056687

[2078 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2087  0.595942
2088  0.553231
2089  0.553451
2090  0.585691
2091  0.552776

[2092 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1952  1.343014
1953  1.373848
1954  1.345863
1955  1.176954
1956  1.166669

[1957 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2027  1.512021
2028  1.470805
2029  1.435884
2030  1.500019
2031  1.376334

[2032 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1494  1.515109
1495  1.497823
1496  1.526326
1497  1.510485
1498  1.483957

[1499 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1806  1.647198
1807  1.854205
1808  1.841786
1809  1.779563
1810  1.748838

[1811 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1708  1.484780
1709  1.489494
1710  1.513838
1711  1.743639
1712  1.706060

[1713 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2004  0.631647
2005  0.641712
2006  0.656261
2007  0.706390
2008  0.634629

[2009 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1846  0.981824
1847  0.966937
1848  0.978101
1849  0.933273
1850  0.913079

[1851 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2012  1.289670
2013  1.229303
2014  1.201865
2015  1.072903
2016  1.052067

[2017 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1918  1.119213
1919  1.100364
1920  1.118026
1921  1.464023
1922  1.459130

[1923 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1916  1.708784
1917  1.709070
1918  1.689200
1919  1.685936
1920  1.684655

[1921 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2045  0.875559
2046  0.877761
2047  0.882607
2048  0.842911
2049  0.823762

[2050 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1901  2.047165
1902  2.026268
1903  2.025827
1904  1.936707
1905  1.920891

[1906 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1854  1.445073
1855  1.428647
1856  1.475332
1857  1.476067
1858  1.448309

[1859 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1949  0.311899
1950  0.336711
1951  0.190178
1952  0.176166
1953  0.095087

[1954 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1731  1.578028
1732  1.541253
1733  1.506071
1734  1.483129
1735  1.454650

[1736 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1808  1.123082
1809  1.116477
1810  1.086372
1811  1.005115
1812  0.969615

[1813 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1631  1.937745
1632  1.910987
1633  1.927773
1634  1.831911
1635  1.816623

[1636 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1925  2.323254
1926  2.165343
1927  2.153000
1928  2.202326
1929  2.223861

[1930 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1849  1.327422
1850  1.359399
1851  1.338495
1852  1.203763
1853  1.185132

[1854 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1866  0.994133
1867  1.140887
1868  1.226615
1869  1.411392
1870  1.403837

[1871 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1834  1.821499
1835  1.803234
1836  1.796408
1837  1.703489
1838  1.628498

[1839 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1881  1.907797
1882  1.888790
1883  1.915737
1884  1.867923
1885  1.878884

[1886 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1796  0.874189
1797  0.934187
1798  0.935458
1799  0.769837
1800  0.745002

[1801 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1655  1.505838
1656  1.416407
1657  1.505063
1658  1.304876
1659  1.174904

[1660 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1805  0.735245
1806  0.723799
1807  0.735076
1808  0.797033
1809  0.772605

[1810 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1862  1.354223
1863  1.382310
1864  1.390861
1865  1.508767
1866  1.482101

[1867 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1978  2.147122
1979  2.118923
1980  2.118368
1981  2.072929
1982  2.052151

[1983 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1994  1.874270
1995  1.868062
1996  1.854093
1997  1.772320
1998  1.717150

[1999 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1982  1.185831
1983  1.182368
1984  1.186152
1985  1.134441
1986  1.121568

[1987 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
2000  1.102420
2001  1.132430
2002  1.113218
2003  1.191862
2004  1.178198

[2005 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1904  1.538500
1905  1.539694
1906  1.555161
1907  1.687822
1908  1.694262

[1909 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1990  0.949018
1991  0.984726
1992  1.062531
1993  0.983640
1994  0.940370

[1995 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1828  1.654131
1829  1.618340
1830  1.606055
1831  1.589942
1832  1.526173

[1833 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1817  0.253987
1818  0.307883
1819  0.374325
1820  0.342010
1821  0.283715

[1822 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1827  1.419792
1828  1.330802
1829  1.280439
1830  1.431430
1831  1.396097

[1832 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1825  1.309568
1826  1.319278
1827  1.321963
1828  1.277919
1829  1.237918

[1830 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1784  1.903843
1785  1.800725
1786  1.828021
1787  1.710945
1788  1.669326

[1789 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1719  0.882029
1720  0.884040
1721  0.887578
1722  1.106054
1723  1.088761

[1724 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1971  0.863988
1972  0.972488
1973  0.824772
1974  1.116545
1975  1.029202

[1976 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1594  1.123125
1595  1.127216
1596  1.114316
1597  1.116133
1598  1.039440

[1599 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1873  1.953220
1874  1.909488
1875  1.860387
1876  1.730397
1877  1.657862

[1878 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1679  0.913585
1680  0.902522
1681  0.886334
1682  0.773083
1683  0.931592

[1684 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1850  1.161622
1851  1.339817
1852  1.307131
1853  1.365559
1854  1.363308

[1855 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1728  2.272345
1729  2.267980
1730  2.247533
1731  2.194764
1732  2.127295

[1733 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1866  1.313737
1867  1.285401
1868  1.317005
1869  1.202851
1870  1.206926

[1871 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1968  0.946413
1969  0.934914
1970  0.931228
1971  0.915555
1972  0.893403

[1973 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1698  1.787560
1699  1.759026
1700  1.737099
1701  1.664467
1702  1.634647

[1703 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1614  1.599016
1615  1.546170
1616  1.523147
1617  1.404293
1618  1.362865

[1619 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1615  2.206991
1616  2.209914
1617  2.208984
1618  2.157221
1619  2.049257

[1620 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1846  0.402914
1847  0.354986
1848  0.368437
1849  0.269738
1850  0.285340

[1851 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1681  1.620118
1682  1.694486
1683  1.681235
1684  1.646700
1685  1.519973

[1686 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1949  1.698806
1950  1.682238
1951  1.677223
1952  1.573485
1953  1.540737

[1954 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1912  1.771412
1913  1.749101
1914  1.738594
1915  1.694269
1916  1.620205

[1917 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1922  0.636401
1923  0.623235
1924  0.623468
1925  0.630061
1926  0.611962

[1927 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1897  1.643077
1898  1.612334
1899  1.611534
1900  1.575240
1901  1.539789

[1902 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1786  2.234334
1787  2.220582
1788  2.188627
1789  2.033291
1790  1.938471

[1791 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1717  1.066052
1718  1.025493
1719  1.037246
1720  0.982293
1721  0.981289

[1722 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1943  1.495194
1944  1.499127
1945  1.500660
1946  1.488606
1947  1.454372

[1948 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1726  0.723756
1727  0.720351
1728  0.634631
1729  1.002116
1730  1.155952

[1731 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1785  0.971966
1786  0.972971
1787  0.978303
1788  1.004912
1789  0.985833

[1790 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1808  1.339487
1809  1.292288
1810  1.255911
1811  1.024521
1812  1.031501

[1813 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1869  1.202921
1870  1.191491
1871  1.185153
1872  1.134008
1873  1.119943

[1874 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1819  0.354759
1820  0.347836
1821  0.362088
1822  0.232544
1823  0.194649

[1824 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1783  1.852507
1784  1.860200
1785  1.806912
1786  1.742653
1787  1.688887

[1788 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1760  1.097853
1761  1.133002
1762  1.118188
1763  1.190794
1764  1.180378

[1765 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1741  2.365930
1742  2.369729
1743  2.267925
1744  2.276718
1745  2.209780

[1746 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1844  2.389006
1845  2.382835
1846  2.357763
1847  2.278761
1848  2.219890

[1849 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1637  1.867875
1638  1.855239
1639  1.821362
1640  1.772843
1641  1.776958

[1642 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1797  1.281088
1798  1.291663
1799  1.301735
1800  1.412419
1801  1.292881

[1802 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1788  1.090171
1789  1.058721
1790  1.018369
1791  0.859843
1792  0.824976

[1793 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1859  2.907152
1860  2.958245
1861  2.902656
1862  2.676888
1863  2.546002

[1864 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1769  1.277356
1770  1.294522
1771  1.206782
1772  0.975515
1773  0.881540

[1774 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1730  2.037361
1731  2.075427
1732  2.062944
1733  1.987982
1734  1.879199

[1735 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1708  1.089709
1709  1.085810
1710  1.107590
1711  1.082854
1712  1.044947

[1713 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1713  1.492771
1714  1.498691
1715  1.487269
1716  1.431599
1717  1.404696

[1718 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1746  1.363491
1747  1.344074
1748  1.339687
1749  1.253373
1750  1.211968

[1751 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1773  1.899652
1774  1.951801
1775  1.963420
1776  1.714512
1777  1.688316

[1778 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1546  1.508106
1547  1.456153
1548  1.476940
1549  1.291781
1550  1.319923

[1551 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1883  1.269461
1884  1.254227
1885  1.227342
1886  1.174475
1887  1.142706

[1888 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1756  0.878561
1757  0.874296
1758  0.876791
1759  0.830557
1760  0.825156

[1761 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1636  1.856010
1637  1.906207
1638  1.983437
1639  1.842086
1640  1.985433

[1641 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1562  0.574876
1563  0.620620
1564  0.617328
1565  0.686531
1566  0.619755

[1567 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1439  0.876345
1440  0.944404
1441  0.815194
1442  0.959353
1443  0.798308

[1444 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1394  1.379341
1395  1.388922
1396  1.342611
1397  1.214205
1398  1.197505

[1399 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1475  1.448614
1476  1.436097
1477  1.415715
1478  1.429158
1479  1.411020

[1480 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1142  1.160025
1143  1.204706
1144  1.232112
1145  1.238477
1146  1.309002

[1147 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1446  1.251038
1447  1.203866
1448  1.201568
1449  1.227869
1450  1.187901

[1451 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1159  2.772413
1160  2.795612
1161  2.796713
1162  2.741096
1163  2.614878

[1164 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1499  1.592604
1500  1.572307
1501  1.590162
1502  1.483023
1503  1.467316

[1504 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1373  1.972139
1374  2.030238
1375  2.003305
1376  1.828301
1377  1.817435

[1378 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1372  1.163107
1373  1.128824
1374  1.173786
1375  1.153736
1376  1.249790

[1377 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1440  2.038837
1441  2.019348
1442  2.001555
1443  2.075258
1444  2.007544

[1445 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1463  1.566754
1464  1.608194
1465  1.568263
1466  1.474218
1467  1.421814

[1468 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1468  1.457722
1469  1.424738
1470  1.420841
1471  1.360044
1472  1.385789

[1473 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1562  1.064454
1563  1.049935
1564  1.048074
1565  1.059104
1566  0.980213

[1567 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1527  2.211598
1528  2.193680
1529  2.075949
1530  1.984335
1531  1.920710

[1532 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1152  1.278506
1153  1.231771
1154  1.177237
1155  1.071595
1156  1.004021

[1157 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1514  1.385444
1515  1.400885
1516  1.375732
1517  1.698740
1518  1.663169

[1519 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1438  1.494263
1439  1.415076
1440  1.370137
1441  1.234904
1442  1.160516

[1443 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1513  1.854287
1514  1.844680
1515  1.833814
1516  1.983029
1517  1.905279

[1518 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1555  1.830723
1556  1.887406
1557  1.816444
1558  1.692078
1559  1.700762

[1560 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1443  2.353060
1444  2.343996
1445  2.325483
1446  2.118973
1447  2.069757

[1448 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1559  1.545940
1560  1.529113
1561  1.537807
1562  1.686653
1563  1.652030

[1564 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1403  0.974557
1404  0.996117
1405  0.949356
1406  0.896781
1407  0.888471

[1408 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1546  1.069496
1547  1.039538
1548  1.049116
1549  1.030696
1550  1.056958

[1551 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1368  1.791624
1369  1.765290
1370  1.771527
1371  1.631052
1372  1.633071

[1373 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1320  1.286757
1321  1.287943
1322  1.272916
1323  1.215822
1324  1.177862

[1325 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1444  1.348001
1445  1.331696
1446  1.333547
1447  1.261857
1448  1.239686

[1449 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1461  2.618155
1462  2.610236
1463  2.584126
1464  2.541227
1465  2.471609

[1466 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1366  0.898417
1367  0.889843
1368  0.913804
1369  0.852251
1370  0.857012

[1371 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1390  0.995809
1391  0.960833
1392  0.936652
1393  0.887538
1394  0.884901

[1395 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1429  2.005556
1430  1.996227
1431  2.002188
1432  1.918718
1433  1.869327

[1434 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1366  2.177192
1367  2.130882
1368  2.125062
1369  2.037738
1370  2.033949

[1371 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1332  0.297831
1333  0.314877
1334  0.306374
1335  0.289961
1336  0.247906

[1337 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1151  1.412946
1152  1.390108
1153  1.364937
1154  1.207518
1155  1.326821

[1156 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1399  0.785789
1400  0.732143
1401  0.666782
1402  0.642203
1403  0.628563

[1404 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1289  1.726584
1290  1.675639
1291  1.604364
1292  1.522003
1293  1.438800

[1294 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1408  1.339100
1409  1.305350
1410  1.259700
1411  1.186815
1412  1.117790

[1413 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1351  1.475716
1352  1.557584
1353  1.679663
1354  1.629440
1355  1.558985

[1356 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1369  2.147159
1370  2.126199
1371  2.091902
1372  2.039849
1373  2.002708

[1374 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1297  2.255536
1298  2.229355
1299  2.249330
1300  2.224709
1301  2.148639

[1302 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1377  2.065567
1378  2.028005
1379  2.050748
1380  2.196205
1381  2.145059

[1382 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1391  0.982486
1392  0.974176
1393  0.908898
1394  0.830708
1395  0.839200

[1396 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1375  1.275702
1376  1.266233
1377  1.172882
1378  1.448377
1379  1.450035

[1380 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1304  0.927879
1305  0.914140
1306  0.886851
1307  0.800811
1308  0.787389

[1309 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1377  1.119702
1378  1.138209
1379  1.160180
1380  1.113788
1381  1.142846

[1382 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1190 -0.433517
1191 -0.468419
1192 -0.496861
1193 -0.295503
1194 -0.291859

[1195 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1300  0.956381
1301  0.941243
1302  0.946331
1303  0.996325
1304  0.990951

[1305 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1377  1.012359
1378  1.091633
1379  1.083162
1380  1.014427
1381  0.960252

[1382 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1234  1.568117
1235  1.453564
1236  1.426326
1237  1.521215
1238  1.490556

[1239 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1343  1.618170
1344  1.586766
1345  1.584035
1346  1.684764
1347  1.588754

[1348 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1263  1.582420
1264  1.592900
1265  1.597545
1266  1.569411
1267  1.551025

[1268 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1118  0.835936
1119  0.808041
1120  0.786505
1121  0.641896
1122  0.596969

[1123 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1052  1.691941
1053  1.738288
1054  1.713156
1055  1.658371
1056  1.678819

[1057 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1238  1.004360
1239  1.037983
1240  0.956679
1241  0.961832
1242  0.865438

[1243 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1060  1.449510
1061  1.523463
1062  1.491197
1063  1.466070
1064  1.361053

[1065 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1038  1.461717
1039  1.499882
1040  1.483615
1041  1.244068
1042  1.239631

[1043 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1309  1.533155
1310  1.513986
1311  1.491070
1312  1.423502
1313  1.477639

[1314 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1310  1.539730
1311  1.564082
1312  1.520632
1313  1.396087
1314  1.363778

[1315 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1318  0.721150
1319  0.714476
1320  0.765263
1321  0.929210
1322  0.889466

[1323 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1249  1.314445
1250  1.291383
1251  1.281750
1252  1.200841
1253  1.169945

[1254 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1218  0.847153
1219  0.857221
1220  0.902971
1221  1.143733
1222  1.189697

[1223 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1150  1.782877
1151  1.759144
1152  1.782205
1153  1.908973
1154  1.863815

[1155 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1260  0.709210
1261  0.710205
1262  0.719422
1263  0.672806
1264  0.664185

[1265 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1290  1.154194
1291  1.120234
1292  1.148533
1293  1.057866
1294  1.047448

[1295 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1043  1.379118
1044  1.350146
1045  1.378992
1046  1.343453
1047  1.299566

[1048 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1206  1.310879
1207  1.312595
1208  1.306415
1209  1.320080
1210  1.308042

[1211 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1167  0.708448
1168  0.673546
1169  0.670964
1170  0.647910
1171  0.637520

[1172 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1216  1.381467
1217  1.358228
1218  1.339993
1219  1.345708
1220  1.472181

[1221 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1097  1.470873
1098  1.490764
1099  1.481591
1100  1.583657
1101  1.697911

[1102 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1113  0.454202
1114  0.459296
1115  0.458499
1116  0.286707
1117  0.226539

[1118 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1185  2.303302
1186  2.347746
1187  2.350644
1188  2.158002
1189  2.091291

[1190 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1213  0.952505
1214  0.964801
1215  0.925426
1216  0.923303
1217  0.891883

[1218 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1045  2.107765
1046  1.995147
1047  2.117962
1048  2.162150
1049  2.043927

[1050 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1197  0.902857
1198  0.874222
1199  0.837986
1200  0.620642
1201  0.591360

[1202 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1260  2.007368
1261  1.948843
1262  1.908784
1263  2.030626
1264  2.067353

[1265 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1136  1.157894
1137  1.200772
1138  1.163923
1139  1.120746
1140  1.082943

[1141 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1268  1.231574
1269  1.243709
1270  1.217794
1271  1.143130
1272  1.120465

[1273 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1210  0.531291
1211  0.501151
1212  0.509455
1213  0.491221
1214  0.484499

[1215 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1143  1.196140
1144  1.216753
1145  1.205700
1146  1.124065
1147  1.099071

[1148 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1214  2.199348
1215  2.151985
1216  2.106234
1217  1.877480
1218  1.863084

[1219 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1257  0.715067
1258  0.832926
1259  0.797061
1260  0.877321
1261  0.814188

[1262 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1125  1.347805
1126  1.279999
1127  1.316118
1128  1.242278
1129  1.088430

[1130 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1014  0.348435
1015  0.309509
1016  0.286256
1017  0.307657
1018  0.406831

[1019 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1259  1.040943
1260  1.025975
1261  1.004348
1262  0.823955
1263  0.886670

[1264 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1255  0.791787
1256  0.807828
1257  0.750965
1258  0.466044
1259  0.477577

[1260 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1153  1.344454
1154  1.312871
1155  1.305520
1156  1.283881
1157  1.275624

[1158 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1259  1.493225
1260  1.452534
1261  1.471654
1262  1.416339
1263  1.406203

[1264 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1260  1.479211
1261  1.461849
1262  1.460361
1263  1.492926
1264  1.469956

[1265 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1162  1.635637
1163  1.590587
1164  1.598761
1165  1.564724
1166  1.520252

[1167 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1253  1.586161
1254  1.671647
1255  1.686249
1256  1.573454
1257  1.525570

[1258 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1177  1.455645
1178  1.442703
1179  1.412514
1180  1.383017
1181  1.309961

[1182 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1095  1.824636
1096  1.792644
1097  1.785006
1098  1.776880
1099  1.712864

[1100 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1176  2.037206
1177  2.118950
1178  2.017640
1179  1.870314
1180  1.768545

[1181 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1245  1.015414
1246  1.114442
1247  1.087097
1248  1.112182
1249  1.003189

[1250 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1235 -0.139583
1236 -0.036328
1237 -0.026150
1238 -0.069868
1239 -0.054200

[1240 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
513  1.552906
514  1.553075
515  1.495833
516  1.481166
517  1.380269

[518 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1112  1.976691
1113  1.986508
1114  1.980151
1115  2.070526
1116  1.994316

[1117 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1095  2.131950
1096  2.127168
1097  2.142167
1098  2.023385
1099  1.992725

[1100 rows x 1 columns]

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1185  1.513686
1186  1.614045
1187  1.624361
1188  1.564462
1189  1.514340

[1190 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1235  1.808996
1236  1.801981
1237  1.809580
1238  1.815860
1239  1.774323

[1240 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1026  1.959311
1027  1.909423
1028  1.879255
1029  1.741646
1030  1.626228

[1031 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1235  1.976292
1236  1.960646
1237  1.881293
1238  1.830005
1239  1.764501

[1240 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1033  0.422767
1034  0.401810
1035  0.438618
1036  0.667589
1037  0.681197

[1038 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
951  1.773052
952  1.776115
953  1.805198
954  1.820246
955  1.778053

[956 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1235  0.811953
1236  0.886487
1237  0.830459
1238  0.660675
1239  0.605560

[1240 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1045  1.854900
1046  1.878763
1047  1.733276
1048  2.011156
1049  2.147640

[1050 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1140  2.243074
1141  2.239642
1142  2.226496
1143  2.256906
1144  2.157402

[1145 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
879  1.031282
880  0.962417
881  1.010314
882  0.837438
883  1.003580

[884 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1035  1.604361
1036  1.560830
1037  1.609723
1038  1.572231
1039  1.577872

[1040 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1204  2.279901
1205  2.276183
1206  2.249072
1207  2.221097
1208  2.130037

[1209 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1122  0.196690
1123  0.165708
1124  0.177411
1125  0.258992
1126  0.252893

[1127 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1225  0.932114
1226  0.905724
1227  0.908529
1228  0.940674
1229  1.023785

[1230 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1216  1.995404
1217  2.032001
1218  2.051033
1219  1.940637
1220  1.927066

[1221 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1032  0.679707
1033  0.616142
1034  0.565299
1035  0.464433
1036  0.435311

[1037 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1158  0.739130
1159  0.690799
1160  0.706996
1161  0.621639
1162  0.620599

[1163 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1023  1.831517
1024  1.806391
1025  1.838354
1026  1.814346
1027  1.821014

[1028 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1206  0.870219
1207  0.860390
1208  0.874554
1209  0.843415
1210  0.824834

[1211 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1221  1.814129
1222  1.783598
1223  1.783807
1224  1.668635
1225  1.637364

[1226 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1119  0.786586
1120  0.823669
1121  0.842645
1122  1.000660
1123  0.966616

[1124 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1132  0.423897
1133  0.370274
1134  0.429282
1135  0.401824
1136  0.370448

[1137 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1132  1.705449
1133  1.695842
1134  1.703576
1135  1.633576
1136  1.584179

[1137 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1145  1.260871
1146  1.245415
1147  1.216668
1148  1.287041
1149  1.258630

[1150 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1193  1.437719
1194  1.437845
1195  1.411514
1196  1.456259
1197  1.434075

[1198 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1205  0.431934
1206  0.569769
1207  0.485607
1208  0.580912
1209  0.520302

[1210 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1134  0.819985
1135  0.823264
1136  0.811939
1137  0.780415
1138  0.812941

[1139 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1037  1.881773
1038  1.887686
1039  1.933930
1040  1.768028
1041  1.804927

[1042 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1216 -0.038405
1217  0.121389
1218  0.081129
1219  0.108759
1220  0.116331

[1221 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1079  0.750048
1080  0.749037
1081  0.837441
1082  0.731097
1083  0.692444

[1084 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1203  1.625375
1204  1.622949
1205  1.609204
1206  1.617063
1207  1.664354

[1208 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1073  0.836135
1074  0.843454
1075  0.861081
1076  0.759238
1077  0.764764

[1078 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1208  1.164042
1209  1.065387
1210  1.077013
1211  1.409029
1212  1.329422

[1213 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
946  1.255794
947  1.247544
948  1.246235
949  1.229366
950  1.212775

[951 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1000  1.480324
1001  1.482513
1002  1.501762
1003  1.408030
1004  1.393089

[1005 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
901  0.943367
902  0.912698
903  0.779308
904  0.701255
905  0.672420

[906 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1095  1.704785
1096  1.664681
1097  1.669267
1098  1.642349
1099  1.620339

[1100 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1089  1.149330
1090  1.087874
1091  1.210829
1092  1.169333
1093  1.190113

[1094 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1027  0.998909
1028  1.013127
1029  1.140420
1030  1.078368
1031  1.021046

[1032 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1042  2.140352
1043  2.115183
1044  1.959611
1045  1.907185
1046  1.849357

[1047 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1096  0.865560
1097  0.878545
1098  0.920516
1099  0.939321
1100  0.955014

[1101 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1121  0.661951
1122  0.619913
1123  0.620263
1124  0.752082
1125  0.780215

[1126 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1067  1.856721
1068  1.779813
1069  1.800747
1070  1.683895
1071  1.608287

[1072 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1000  1.029151
1001  1.008865
1002  1.022044
1003  0.978904
1004  0.968794

[1005 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1065  1.193730
1066  1.181236
1067  1.086648
1068  0.904744
1069  0.862634

[1070 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1048  1.833551
1049  1.800097
1050  1.780165
1051  1.766514
1052  1.684258

[1053 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1041  0.444027
1042  0.427110
1043  0.402331
1044  0.447831
1045  0.431060

[1046 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
542  2.099800
543  2.064617
544  2.071265
545  2.000880
546  1.944156

[547 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1037  1.097244
1038  1.083868
1039  1.094204
1040  1.077607
1041  1.088841

[1042 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1024  1.254300
1025  1.196382
1026  1.257354
1027  1.223916
1028  1.219802

[1029 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1007  1.425954
1008  1.408923
1009  1.354006
1010  1.263199
1011  1.239035

[1012 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1014  1.565833
1015  1.543445
1016  1.565234
1017  1.553792
1018  1.548036

[1019 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1010  0.798483
1011  0.758472
1012  0.759521
1013  0.635056
1014  0.603652

[1015 rows x 1 columns]

            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
736  1.463609
737  1.448370
738  1.420745
739  1.336599
740  1.315442

[741 rows x 1 columns]
             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1008  0.735487
1009  0.786846
1010  0.620449
1011  0.701538
1012  0.690033

[1013 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
992  1.008848
993  0.956900
994  0.936650
995  0.793720
996  0.724450

[997 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
896  2.005067
897  1.975759
898  2.003105
899  1.939636
900  1.900630

[901 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
770  1.578611
771  1.558062
772  1.562763
773  1.491005
774  1.478251

[775 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
981  1.117313
982  1.021525
983  1.013506
984  1.046872
985  1.069935

[986 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
987  0.584491
988  0.580650
989  0.538250
990  0.632007
991  0.593836

[992 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
956  0.640621
957  0.606068
958  0.604398
959  0.679917
960  0.645853

[961 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
835  0.956039
836  0.946095
837  1.009116
838  1.100761
839  1.008685

[840 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
968  0.774379
969  0.791389
970  0.768890
971  0.656993
972  0.598168

[973 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
952  1.613773
953  1.591403
954  1.611670
955  1.685525
956  1.640450

[957 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
956  0.898300
957  0.928485
958  0.917197
959  1.021069
960  1.027498

[961 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
961  0.348377
962  0.312201
963  0.330628
964  0.380644
965  0.368364

[966 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
869  1.212182
870  1.187125
871  1.179125
872  1.090912
873  1.100302

[874 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
931  0.954120
932  0.910317
933  0.872177
934  0.679949
935  0.718723

[936 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
810  0.928243
811  1.100953
812  1.165634
813  1.429800
814  1.361171

[815 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
941  0.680399
942  0.657494
943  0.601400
944  0.706942
945  0.671647

[946 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
942  1.076450
943  1.104226
944  1.069611
945  0.905854
946  0.914756

[947 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
946  1.369369
947  1.412737
948  1.412579
949  1.540987
950  1.461876

[951 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
936 -0.192530
937 -0.192995
938 -0.190470
939 -0.213774
940 -0.258448

[941 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
936  0.540257
937  0.492131
938  0.441032
939  0.532611
940  0.502011

[941 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
934  1.378177
935  1.368313
936  1.368938
937  1.351301
938  1.401407

[939 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
934  1.602454
935  1.583417
936  1.640236
937  1.624636
938  1.550883

[939 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
916  0.614157
917  0.640770
918  0.620649
919  0.632064
920  0.617064

[921 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
865  0.673391
866  0.663129
867  0.677804
868  0.677757
869  0.662518

[870 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
913  0.409382
914  0.400864
915  0.398930
916  0.366246
917  0.357847

[918 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
848  1.992015
849  1.959807
850  1.934039
851  1.755627
852  1.654083

[853 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
928  1.561167
929  1.467324
930  1.399673
931  1.316221
932  1.229077

[933 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
925  0.924444
926  0.946907
927  0.910457
928  0.831917
929  0.764099

[930 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
926  0.714859
927  0.681457
928  0.732481
929  0.596765
930  0.559855

[931 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
916  1.692849
917  1.662163
918  1.675300
919  1.598279
920  1.557222

[921 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
913  1.470348
914  1.452037
915  1.466032
916  1.445852
917  1.420907

[918 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
837  1.726483
838  1.706114
839  1.753064
840  1.835763
841  1.766910

[842 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
907  1.820359
908  1.789711
909  1.815460
910  1.734070
911  1.667279

[912 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
907  1.375122
908  1.355129
909  1.352591
910  1.279441
911  1.238690

[912 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
905  0.833837
906  0.820758
907  0.827647
908  0.781761
909  0.781494

[910 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
902  2.502792
903  2.525612
904  2.526206
905  2.641154
906  2.687750

[907 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
905  0.823092
906  0.797132
907  0.791704
908  0.685858
909  0.687254

[910 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
898  1.393801
899  1.407134
900  1.405013
901  1.355271
902  1.346718

[903 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
890  0.713407
891  0.766495
892  0.713203
893  0.780546
894  0.743364

[895 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
895  1.889285
896  1.878808
897  1.834526
898  1.697690
899  1.673858

[900 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
895  0.873711
896  0.871224
897  0.890954
898  0.927088
899  0.905077

[900 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
773  1.069019
774  1.044571
775  1.020889
776  1.045864
777  1.010627

[778 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
898  1.546608
899  1.549404
900  1.547715
901  1.515043
902  1.487629

[903 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
885  1.372521
886  1.397925
887  1.422920
888  1.585514
889  1.553524

[890 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
888  1.318812
889  1.285314
890  1.268143
891  1.153124
892  1.104075

[893 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
884  0.418118
885  0.418174
886  0.431481
887  0.378644
888  0.315479

[889 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
888  1.252542
889  1.241283
890  1.248606
891  1.231777
892  1.213684

[893 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
888  0.916942
889  1.103431
890  1.050182
891  1.250837
892  1.218504

[893 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
820  1.757832
821  1.891780
822  1.681594
823  1.974515
824  1.881760

[825 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
874  1.146190
875  1.181688
876  1.124422
877  1.056782
878  0.988696

[879 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
879  1.474148
880  1.433979
881  1.463343
882  1.443860
883  1.470030

[884 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
151  0.989314
152  0.973122
153  1.012625
154  1.167848
155  1.173312

[156 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
873  1.584411
874  1.526666
875  1.483633
876  1.506326
877  1.484306

[878 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
868  1.985360
869  1.960318
870  1.969242
871  1.830011
872  1.856933

[873 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
873  2.065993
874  2.055214
875  2.096768
876  1.944892
877  2.008504

[878 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
866  1.735559
867  1.751896
868  1.755617
869  1.681360
870  1.638707

[871 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
870  0.865455
871  0.858524
872  0.855196
873  0.816492
874  0.801906

[875 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
863  1.777010
864  1.754757
865  1.816387
866  1.736932
867  1.687376

[868 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
853  1.950534
854  2.100164
855  2.127108
856  2.107860
857  2.111149

[858 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
863  1.492320
864  1.476317
865  1.443819
866  1.355831
867  1.429249

[868 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
861  0.621157
862  0.618240
863  0.588182
864  0.671210
865  0.623710

[866 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
853  1.271351
854  1.325828
855  1.277418
856  1.370803
857  1.354789

[858 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
843  2.088586
844  2.077626
845  1.941017
846  1.763944
847  1.644014

[848 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
852  1.484055
853  1.479141
854  1.529079
855  1.419086
856  1.402183

[857 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
754  1.971367
755  1.956777
756  1.939453
757  1.899307
758  1.900704

[759 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
850  2.028324
851  2.013313
852  2.038006
853  1.934527
854  1.949140

[855 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
730  1.524436
731  1.470951
732  1.496036
733  1.453886
734  1.395198

[735 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
853  1.232992
854  1.214343
855  1.191275
856  1.133257
857  1.103370

[858 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
805  1.280107
806  1.271190
807  1.241271
808  1.159643
809  1.116562

[810 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
841  0.955084
842  0.946387
843  0.908120
844  0.818506
845  0.796916

[846 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
837  0.951382
838  0.974100
839  0.958498
840  0.910247
841  0.871339

[842 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
840  0.727762
841  0.780885
842  0.795464
843  0.873044
844  0.874902

[845 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
751  0.552109
752  0.523906
753  0.534247
754  0.621768
755  0.608109

[756 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
842  0.421417
843  0.419962
844  0.434838
845  0.487806
846  0.483883

[847 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
842  1.637896
843  1.617764
844  1.601496
845  1.413602
846  1.370102

[847 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
836  0.520218
837  0.510998
838  0.526043
839  0.625548
840  0.601507

[841 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
734  2.669366
735  2.671184
736  2.647658
737  2.552017
738  2.534612

[739 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
839  0.744391
840  0.598514
841  0.615047
842  0.538980
843  0.533905

[844 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
810  1.183628
811  1.066712
812  0.946229
813  0.875286
814  0.807193

[815 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
795  1.802997
796  1.768128
797  1.731934
798  1.556731
799  1.584770

[800 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
245  1.267592
246  1.259770
247  1.273775
248  1.244241
249  1.239175

[250 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
834  0.871467
835  0.898574
836  0.885897
837  0.810500
838  0.689993

[839 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
831  1.376850
832  1.395685
833  1.361807
834  1.300326
835  1.274198

[836 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
825  1.541469
826  1.499948
827  1.515766
828  1.269141
829  1.253535

[830 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
826  2.850963
827  2.988316
828  2.900138
829  2.724131
830  2.657476

[831 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
830  1.950692
831  1.931177
832  1.957260
833  1.981133
834  1.933556

[835 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
828  1.021965
829  0.992320
830  1.023092
831  1.016692
832  1.000147

[833 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
824  0.973828
825  1.042476
826  1.014961
827  0.998007
828  0.951303

[829 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
827  1.973488
828  1.940406
829  1.894971
830  1.881311
831  1.834056

[832 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
666  2.802575
667  2.769975
668  2.747953
669  2.688766
670  2.642712

[671 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
776  2.102709
777  2.086056
778  2.045513
779  1.883467
780  1.825430

[781 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
823  1.546946
824  1.534291
825  1.554102
826  1.519690
827  1.492889

[828 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
823  0.934960
824  0.964301
825  0.966438
826  1.051556
827  1.068711

[828 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
810  0.638930
811  0.638654
812  0.640647
813  0.583017
814  0.539147

[815 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
820  1.518929
821  1.485053
822  1.549731
823  1.649331
824  1.596901

[825 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
818  1.675073
819  1.698006
820  1.737042
821  1.602349
822  1.603457

[823 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
820  0.971890
821  0.958343
822  0.958685
823  1.035549
824  1.002294

[825 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
815  0.900859
816  0.916570
817  0.926655
818  0.885833
819  0.874260

[820 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
647  1.613339
648  1.598441
649  1.453072
650  1.482280
651  1.527808

[652 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
815  1.430993
816  1.424036
817  1.412924
818  1.310522
819  1.305160

[820 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
818  1.410899
819  1.336258
820  1.319434
821  1.259775
822  1.243813

[823 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
804  0.793497
805  0.822698
806  0.854244
807  0.883935
808  0.900874

[809 rows x 1 columns]

            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
809  1.252891
810  1.326393
811  1.336855
812  1.381366
813  1.381376

[814 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
803  2.156202
804  2.157852
805  2.131115
806  2.096325
807  2.072321

[808 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
808  1.104690
809  1.127136
810  1.121650
811  1.107320
812  1.093147

[813 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
801  1.259948
802  1.181742
803  1.179928
804  1.224040
805  1.364182

[806 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
797  0.495905
798  0.496421
799  0.564920
800  0.621323
801  0.607918

[802 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
798  1.334182
799  1.357487
800  1.356488
801  1.338513
802  1.288533

[803 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
799  2.082879
800  2.065274
801  2.027344
802  1.894400
803  1.870873

[804 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
578  1.828547
579  1.816832
580  1.858871
581  1.740822
582  1.775123

[583 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
796  0.822773
797  0.813898
798  0.823889
799  0.787396
800  0.768755

[801 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
795  1.267828
796  1.219474
797  1.261067
798  1.272481
799  1.221655

[800 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
794  1.277598
795  1.269872
796  1.261183
797  1.207693
798  1.153488

[799 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
796  1.598582
797  1.546443
798  1.491091
799  1.344045
800  1.294352

[801 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
748  0.661440
749  0.669535
750  0.683086
751  0.732012
752  0.750602

[753 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
789  0.632323
790  0.635370
791  0.621143
792  0.542618
793  0.485285

[794 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
792  0.985942
793  0.969083
794  0.950882
795  0.895138
796  0.872292

[797 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
784  1.863944
785  1.853636
786  1.886108
787  1.794477
788  1.730068

[789 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
784  1.153134
785  1.185248
786  1.128094
787  1.077623
788  0.969179

[789 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
547  2.577459
548  2.537269
549  2.472568
550  2.243412
551  2.154192

[552 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
781  0.907065
782  0.875413
783  0.905335
784  0.857995
785  0.803541

[786 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
785  0.968471
786  0.962315
787  0.975752
788  1.046777
789  1.030032

[790 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
780  1.458907
781  1.445012
782  1.510693
783  1.406651
784  1.369713

[785 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
779  1.213846
780  1.202572
781  1.166766
782  1.183192
783  1.064855

[784 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
780  0.758461
781  0.889014
782  0.861565
783  0.834381
784  0.799015

[785 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
758  1.134674
759  1.104180
760  1.146464
761  0.962376
762  0.901076

[763 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
776  0.914124
777  0.882256
778  0.899063
779  0.858237
780  0.862009

[781 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
773  0.675005
774  0.740462
775  0.713133
776  0.737807
777  0.699580

[778 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
764  2.150717
765  2.135883
766  2.108153
767  2.094344
768  2.053488

[769 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
572  1.223028
573  1.216543
574  1.189340
575  1.480846
576  1.446345

[577 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
773  1.154599
774  1.077018
775  1.050390
776  0.947615
777  0.910959

[778 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
724  1.360987
725  1.418929
726  1.426337
727  1.367483
728  1.329274

[729 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
771  0.872757
772  0.917579
773  0.953609
774  1.098440
775  1.060822

[776 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
759  0.567753
760  0.560123
761  0.566818
762  0.501629
763  0.493066

[764 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
766  0.674244
767  0.648765
768  0.580802
769  0.484283
770  0.496079

[771 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
762  0.871386
763  0.927733
764  1.005685
765  0.935378
766  0.899393

[767 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
757  0.718928
758  0.707953
759  0.703734
760  0.675723
761  0.678970

[762 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
757  0.820581
758  0.833634
759  0.785019
760  0.678304
761  0.651470

[762 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
664  1.628493
665  1.622014
666  1.625071
667  1.584625
668  1.568410

[669 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
745  2.543098
746  2.504001
747  2.527389
748  2.484931
749  2.449469

[750 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
686  1.923081
687  1.937601
688  1.941612
689  1.910000
690  1.828954

[691 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
717  2.079028
718  2.055758
719  2.093809
720  1.970061
721  1.920110

[722 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
746  1.118615
747  1.052817
748  1.100645
749  1.275666
750  1.234544

[751 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
641  2.034428
642  2.017285
643  2.025136
644  1.763951
645  1.668088

[646 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
746  1.086608
747  1.068993
748  1.088694
749  1.075657
750  1.041792

[751 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
734  1.662941
735  1.606734
736  1.641583
737  2.049015
738  2.060645

[739 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
694  0.884074
695  0.847576
696  0.830116
697  0.866978
698  0.753983

[699 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
742  2.268022
743  2.292021
744  2.311802
745  2.474336
746  2.394037

[747 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
597  0.758550
598  0.767938
599  0.740144
600  0.652945
601  0.594244

[602 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
739  1.005202
740  0.957716
741  0.964626
742  0.876229
743  0.857837

[744 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
721  1.313436
722  1.439581
723  1.420332
724  1.381613
725  1.235019

[726 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
719  1.281988
720  1.249601
721  1.201938
722  1.196204
723  1.200773

[724 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
735  0.767968
736  0.746807
737  0.758645
738  0.754977
739  0.741010

[740 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
727 -0.016379
728  0.004875
729 -0.039059
730 -0.032470
731 -0.030531

[732 rows x 1 columns]

            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
639  1.520474
640  1.517849
641  1.488636
642  1.328037
643  1.311824

[644 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
723  1.976169
724  1.968209
725  1.918507
726  1.836822
727  1.891697

[728 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
705  1.897805
706  1.892731
707  1.903990
708  1.803684
709  1.773159

[710 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
719  1.239921
720  1.242110
721  1.233731
722  1.122159
723  1.130186

[724 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
395  1.867925
396  1.835736
397  1.854896
398  1.782931
399  1.698689

[400 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
713  0.884814
714  0.864787
715  0.890225
716  0.904943
717  0.929386

[718 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
706  0.693531
707  0.859917
708  0.824540
709  0.802839
710  0.752893

[711 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
711  0.456103
712  0.493884
713  0.385054
714  0.346391
715  0.241424

[716 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
691  1.584962
692  1.596106
693  1.637962
694  1.473662
695  1.445234

[696 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
705  2.200892
706  2.222112
707  2.241178
708  2.166265
709  2.143615

[710 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
625  1.623329
626  1.664108
627  1.624051
628  1.849225
629  1.745541

[630 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
709  0.367154
710  0.325840
711  0.348295
712  0.242776
713  0.212261

[714 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
653  1.675739
654  1.735735
655  1.725734
656  1.643342
657  1.630852

[658 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
641  1.476949
642  1.385967
643  1.383247
644  1.473776
645  1.470800

[646 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
603  1.852072
604  1.832871
605  1.865061
606  1.941702
607  1.865801

[608 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
703  1.319939
704  1.357183
705  1.250472
706  1.119159
707  1.042992

[708 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
701  1.993359
702  1.977149
703  1.916890
704  1.802926
705  1.745014

[706 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
692  1.664957
693  1.642560
694  1.742630
695  1.550163
696  1.492337

[697 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
686  0.888332
687  0.843831
688  0.887488
689  0.891144
690  0.858432

[691 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
698  1.435243
699  1.435956
700  1.457459
701  1.403021
702  1.385672

[703 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
699  0.916806
700  0.928337
701  0.943101
702  1.037052
703  1.035599

[704 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
696  1.278563
697  1.264632
698  1.278860
699  1.147875
700  1.133624

[701 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
685  0.512930
686  0.495978
687  0.477737
688  0.505692
689  0.527991

[690 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
684  1.304530
685  1.266537
686  1.211893
687  1.057602
688  1.024948

[689 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
412  0.847332
413  0.889375
414  0.883930
415  0.862597
416  0.842792

[417 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
676  0.920968
677  0.887283
678  0.930004
679  0.890228
680  0.906764

[681 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
689  1.022433
690  1.018196
691  0.982775
692  0.896139
693  0.922932

[694 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
677  1.497914
678  1.585864
679  1.560344
680  1.371490
681  1.373040

[682 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
682  1.854067
683  1.718089
684  1.716325
685  1.924669
686  1.900211

[687 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
681  1.127187
682  1.123591
683  1.097423
684  1.117341
685  1.099463

[686 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
664  1.049976
665  1.018975
666  1.005734
667  0.934040
668  0.911219

[669 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
671  1.495474
672  1.555396
673  1.524999
674  1.690237
675  1.642946

[676 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
669  1.133482
670  1.191614
671  1.242877
672  1.458725
673  1.378121

[674 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
669  1.059058
670  1.056999
671  1.081699
672  1.004595
673  1.037716

[674 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
659  0.863588
660  0.888010
661  0.867238
662  0.847805
663  0.810034

[664 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
664  1.656460
665  1.744047
666  1.717415
667  1.563710
668  1.467960

[669 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
659  1.431961
660  1.415489
661  1.485950
662  1.397188
663  1.404268

[664 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
655  1.754333
656  1.730690
657  1.731605
658  1.887688
659  1.921966

[660 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
652  2.662386
653  2.627071
654  2.637023
655  2.659161
656  2.626473

[657 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
652  1.358162
653  1.325481
654  1.305216
655  1.244462
656  1.207309

[657 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
643  1.467666
644  1.556170
645  1.545750
646  1.390785
647  1.387495

[648 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
644  1.068102
645  0.975225
646  0.958669
647  0.797708
648  0.773407

[649 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
643  1.599131
644  1.462253
645  1.395517
646  1.153243
647  1.154979

[648 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
641  1.233045
642  1.213608
643  1.250332
644  1.252257
645  1.231123

[646 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
637  1.322080
638  1.313945
639  1.290679
640  1.291394
641  1.273822

[642 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
640  1.051397
641  1.032172
642  1.015246
643  1.050408
644  1.022145

[645 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
640  0.932760
641  0.974011
642  0.969731
643  1.103975
644  1.116269

[645 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
637  1.068946
638  1.053655
639  1.000624
640  1.016215
641  1.001774

[642 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
640  1.166523
641  1.148033
642  1.192039
643  1.206097
644  1.141864

[645 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
633  0.768075
634  0.640071
635  0.569376
636  0.410979
637  0.358731

[638 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
636  1.138198
637  1.122671
638  1.091043
639  1.025430
640  1.056297

[641 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
632  0.971567
633  1.023140
634  1.054182
635  1.164219
636  1.163368

[637 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
452  2.719770
453  2.680655
454  2.687985
455  2.567210
456  2.434280

[457 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
631  1.807915
632  1.847948
633  1.776907
634  1.749427
635  1.653388

[636 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
629  1.537374
630  1.519302
631  1.524309
632  1.478269
633  1.442585

[634 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
625  0.978889
626  0.984240
627  0.974132
628  1.002273
629  0.967237

[630 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
621  1.074649
622  1.074316
623  1.043897
624  0.970880
625  0.909179

[626 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
614  2.036626
615  1.937502
616  1.935712
617  1.832632
618  1.803204

[619 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
601  1.219649
602  1.215790
603  1.218934
604  1.171088
605  1.139446

[606 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
570  1.212319
571  1.186176
572  1.194542
573  1.154645
574  1.164485

[575 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
590  1.000914
591  0.977101
592  0.975134
593  0.915528
594  0.915467

[595 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
601  1.569837
602  1.653351
603  1.626437
604  1.623482
605  1.656427

[606 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
595  1.432998
596  1.443021
597  1.383024
598  1.567835
599  1.452336

[600 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
583  1.440103
584  1.489160
585  1.469898
586  1.608627
587  1.600662

[588 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
587  2.694446
588  2.688083
589  2.614048
590  2.394844
591  2.286699

[592 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
578  2.036094
579  2.050891
580  2.057714
581  1.894153
582  1.845076

[583 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
473  1.778400
474  1.767199
475  1.849211
476  1.654090
477  1.671484

[478 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
563  0.692338
564  0.698900
565  0.702601
566  0.654307
567  0.643705

[568 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
519  0.971527
520  1.053705
521  0.987231
522  0.928084
523  0.881964

[524 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
524  1.215489
525  1.238645
526  1.293856
527  1.207252
528  1.137760

[529 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
508  0.963959
509  0.939762
510  0.951624
511  0.892309
512  0.864247

[513 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
490  0.939701
491  0.939364
492  0.985471
493  0.977960
494  0.967941

[495 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
486  1.041003
487  0.996898
488  1.041160
489  0.986022
490  0.920287

[491 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
422  0.351892
423  0.535874
424  0.550476
425  0.433170
426  0.470586

[427 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
406  1.033450
407  1.010952
408  1.035297
409  0.874018
410  0.854972

[411 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
495  1.299081
496  1.289157
497  1.282687
498  1.341970
499  1.260607

[500 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
393  2.335668
394  2.367416
395  2.347452
396  2.112643
397  1.999293

[398 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
378  1.134611
379  1.116613
380  1.086947
381  1.260119
382  1.194442

[383 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
369  1.211195
370  1.268532
371  1.263314
372  1.200772
373  1.126327

[374 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
338  1.529188
339  1.620887
340  1.498254
341  1.536433
342  1.567870

[343 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
358  0.653257
359  0.648103
360  0.668012
361  0.735864
362  0.746502

[363 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
353  0.683064
354  0.734630
355  0.718740
356  0.923075
357  0.888669

[358 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
325  1.146871
326  1.125456
327  1.137523
328  1.216028
329  1.301017

[330 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
339  1.553397
340  1.656924
341  1.545257
342  1.520182
343  1.456610

[344 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
411  0.582025
412  0.690563
413  0.662394
414  0.642975
415  0.587003

[416 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
329  0.899948
330  0.919375
331  0.922550
332  1.045968
333  1.041074

[334 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
311  1.354490
312  1.389174
313  1.387472
314  1.351865
315  1.496122

[316 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
308  1.996704
309  2.184022
310  2.123106
311  2.022372
312  1.998114

[313 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
305  1.112897
306  1.196198
307  1.212661
308  1.607098
309  1.548193

[310 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
304  1.640200
305  1.548050
306  1.539193
307  1.375813
308  1.284225

[309 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
300  1.910725
301  1.883656
302  1.823480
303  1.687667
304  1.598827

[305 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
291  1.676666
292  1.705069
293  1.675684
294  1.574227
295  1.473103

[296 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
290  2.189756
291  2.202469
292  2.215224
293  2.346674
294  2.281608

[295 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
286  1.507410
287  1.699611
288  1.575282
289  1.475829
290  1.279661

[291 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
285  1.625048
286  1.603078
287  1.631319
288  1.580927
289  1.562624

[290 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
281  0.545379
282  0.557510
283  0.532913
284  0.633504
285  0.615508

[286 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
282  1.749619
283  1.727629
284  1.715921
285  1.707854
286  1.677686

[287 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
267  0.819922
268  0.866193
269  0.845076
270  0.983580
271  0.997494

[272 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
269  0.895424
270  0.866093
271  0.852438
272  0.743930
273  0.801564

[274 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
270  1.123370
271  1.238023
272  1.203669
273  1.118449
274  1.131653

[275 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
274  1.162051
275  1.170501
276  1.108825
277  1.023878
278  1.054912

[279 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
266  1.286126
267  1.346969
268  1.339272
269  1.314955
270  1.311635

[271 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
257  0.870371
258  0.886731
259  0.883335
260  0.887377
261  0.889848

[262 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
255  1.903597
256  1.920350
257  1.936091
258  1.923674
259  1.920037

[260 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
248  1.999556
249  2.035432
250  2.057516
251  2.042404
252  2.009256

[253 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
230  0.895328
231  0.946361
232  0.965371
233  1.016368
234  0.985184

[235 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
229  2.050909
230  2.035718
231  2.071534
232  2.172850
233  2.109456

[234 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
223  0.757636
224  0.756330
225  0.736792
226  0.687788
227  0.657811

[228 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
206  1.672865
207  1.678090
208  1.690136
209  1.712041
210  1.666225

[211 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
235  1.049794
236  1.082363
237  1.148395
238  1.058684
239  1.056636

[240 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
197  1.419061
198  1.408005
199  1.431650
200  1.385868
201  1.352236

[202 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
181  0.661652
182  0.618703
183  0.648368
184  0.588584
185  0.624260

[186 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
178  1.403836
179  1.403219
180  1.258473
181  1.349670
182  1.238430

[183 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
176  1.018639
177  0.950715
178  0.973294
179  0.992327
180  0.945298

[181 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
166  1.678327
167  1.603940
168  1.593474
169  1.496791
170  1.451506

[171 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
164  1.393234
165  1.369213
166  1.401074
167  1.375837
168  1.341894

[169 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
146  0.660178
147  0.845375
148  0.809319
149  0.980152
150  0.948046

[151 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
156  0.831741
157  0.869766
158  0.923305
159  0.831322
160  0.849976

[161 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
141  0.775712
142  0.865801
143  0.907777
144  1.135671
145  1.104932

[146 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
159  1.222109
160  1.216426
161  1.214324
162  1.065406
163  1.022494

[164 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
153  1.271771
154  1.239361
155  1.254904
156  1.236606
157  1.294825

[158 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
137  0.938964
138  0.996267
139  0.994521
140  1.223186
141  1.191697

[142 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
146  1.390646
147  1.374066
148  1.288418
149  1.230342
150  1.073281

[151 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
145  1.920509
146  1.920387
147  1.960282
148  1.946764
149  1.930196

[150 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
142  2.329823
143  2.233828
144  2.210858
145  2.123887
146  2.123364

[147 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
140  1.826436
141  1.786729
142  1.796790
143  1.813894
144  1.799231

[145 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
122  0.965516
123  0.942662
124  0.940447
125  0.874868
126  0.879916

[127 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
136  0.837869
137  0.807905
138  0.857579
139  0.751595
140  0.736878

[141 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
133  1.339195
134  1.325688
135  1.316772
136  1.285703
137  1.261413

[138 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
131  1.309233
132  1.306481
133  1.316387
134  1.298806
135  1.315071

[136 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
115  1.583941
116  1.545959
117  1.510188
118  1.375832
119  1.362520

[120 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
108  1.612437
109  1.637075
110  1.557246
111  1.392077
112  1.336031

[113 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
105  0.326306
106  0.318324
107  0.261837
108  0.115757
109  0.087306

[110 rows x 1 columns]
            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
98   1.885161
99   1.948494
100  1.958488
101  2.004315
102  2.009270

[103 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
92  1.118778
93  1.040929
94  0.993657
95  0.863006
96  0.836735

[97 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
86  0.697965
87  0.599210
88  0.576343
89  0.483431
90  0.468073

[91 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
90  0.860427
91  0.827482
92  0.861395
93  0.794361
94  0.777309

[95 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
69  0.753383
70  0.597165
71  0.666045
72  0.787727
73  0.785122

[74 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
89 -0.073254
90  0.101876
91  0.025687
92  0.637287
93  0.680164

[94 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
69  1.766954
70  1.689504
71  1.689102
72  1.833277
73  1.803383

[74 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
68  1.426320
69  1.324001
70  1.343928
71  1.414107
72  1.375599

[73 rows x 1 columns]
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
64  1.410146
65  1.611569
66  1.586645
67  1.494078
68  1.465329

[69 rows x 1 columns]
    0
0 NaN
1 NaN
2 NaN
3 NaN
4 NaN
5 NaN
6 NaN
           0
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
..       ...
58       NaN
59  0.581145
60  0.868872
61  1.202113
62  1.139512

[63 rows x 1 columns]
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
36 NaN
37 NaN
38 NaN
39 NaN
40 NaN
41 NaN
42 NaN
43 NaN
44 NaN
45 NaN
46 NaN
47 NaN
48 NaN
49 NaN
50 NaN
51 NaN
52 NaN
53 NaN
54 NaN
55 NaN
56 NaN
57 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
36 NaN
37 NaN
38 NaN
39 NaN
40 NaN
41 NaN
42 NaN
43 NaN
44 NaN
45 NaN
46 NaN
47 NaN
48 NaN
49 NaN
50 NaN
51 NaN
52 NaN
53 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
36 NaN
37 NaN
38 NaN
39 NaN
40 NaN
41 NaN
42 NaN
43 NaN
44 NaN
45 NaN
46 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
36 NaN
37 NaN
38 NaN
39 NaN
40 NaN
41 NaN
42 NaN
43 NaN
44 NaN
45 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
36 NaN
37 NaN
38 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
35 NaN
36 NaN
37 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
29 NaN
30 NaN
31 NaN
32 NaN
33 NaN
34 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
25 NaN
26 NaN
27 NaN
28 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
23 NaN
24 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN
17 NaN
18 NaN
19 NaN
20 NaN
21 NaN
22 NaN
     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
16 NaN

     0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
5  NaN
6  NaN
7  NaN
8  NaN
9  NaN
10 NaN
11 NaN
12 NaN
13 NaN
14 NaN
15 NaN
    0
0 NaN
1 NaN
    0
0 NaN
1 NaN
2 NaN
3 NaN
4 NaN
5 NaN
6 NaN
7 NaN
8 NaN
9 NaN
    0
0 NaN
1 NaN
2 NaN
3 NaN
4 NaN
5 NaN
6 NaN
7 NaN
    0
0 NaN

In [1]:
import glob
import pymongo
import numpy as np
import pandas as pd
import pickle
import time
import gzip
import lzma
import pytz
import warnings
import glob
import datetime
from collections import defaultdict, OrderedDict

warnings.filterwarnings(action='ignore')


def DB(host, db_name, user, passwd):
    auth_db = db_name if user not in ('admin', 'root') else 'admin'
    uri = 'mongodb://%s:%s@%s/?authSource=%s' % (user, passwd, host, auth_db)
    return DBObj(uri, db_name=db_name)


class DBObj(object):
    def __init__(self, uri, symbol_column='skey', db_name='white_db'):
        self.db_name = db_name
        self.uri = uri
        self.client = pymongo.MongoClient(self.uri)
        self.db = self.client[self.db_name]
        self.chunk_size = 20000
        self.symbol_column = symbol_column
        self.date_column = 'date'

    def parse_uri(self, uri):
        # mongodb://user:password@example.com
        return uri.strip().replace('mongodb://', '').strip('/').replace(':', ' ').replace('@', ' ').split(' ')

    def drop_table(self, table_name):
        self.db.drop_collection(table_name)

    def rename_table(self, old_table, new_table):
        self.db[old_table].rename(new_table)

    def write(self, table_name, df):
        if len(df) == 0: return

        multi_date = False

        if self.date_column in df.columns:
            date = str(df.head(1)[self.date_column].iloc[0])
            multi_date = len(df[self.date_column].unique()) > 1
        else:
            raise Exception('DataFrame should contain date column')

        collection = self.db[table_name]
        collection.create_index([('date', pymongo.ASCENDING), ('symbol', pymongo.ASCENDING)], background=True)
        collection.create_index([('symbol', pymongo.ASCENDING), ('date', pymongo.ASCENDING)], background=True)

        if multi_date:
            for (date, symbol), sub_df in df.groupby([self.date_column, self.symbol_column]):
                date = str(date)
                symbol = int(symbol)
                collection.delete_many({'date': date, 'symbol': symbol})
                self.write_single(collection, date, symbol, sub_df)
        else:
            for symbol, sub_df in df.groupby([self.symbol_column]):
                collection.delete_many({'date': date, 'symbol': symbol})
                self.write_single(collection, date, symbol, sub_df)

    def write_single(self, collection, date, symbol, df):
        for start in range(0, len(df), self.chunk_size):
            end = min(start + self.chunk_size, len(df))
            df_seg = df[start:end]
            version = 1
            seg = {'ver': version, 'data': self.ser(df_seg, version), 'date': date, 'symbol': symbol, 'start': start}
            collection.insert_one(seg)

    def build_query(self, start_date=None, end_date=None, symbol=None):
        query = {}

        def parse_date(x):
            if type(x) == str:
                if len(x) != 8:
                    raise Exception("`date` must be YYYYMMDD format")
                return x
            elif type(x) == datetime.datetime or type(x) == datetime.date:
                return x.strftime("%Y%m%d")
            elif type(x) == int:
                return parse_date(str(x))
            else:
                raise Exception("invalid `date` type: " + str(type(x)))

        if start_date is not None or end_date is not None:
            query['date'] = {}
            if start_date is not None:
                query['date']['$gte'] = parse_date(start_date)
            if end_date is not None:
                query['date']['$lte'] = parse_date(end_date)

        def parse_symbol(x):
            if type(x) == int:
                return x
            else:
                return int(x)

        if symbol:
            if type(symbol) == list or type(symbol) == tuple:
                query['symbol'] = {'$in': [parse_symbol(x) for x in symbol]}
            else:
                query['symbol'] = parse_symbol(symbol)

        return query

    def delete(self, table_name, start_date=None, end_date=None, symbol=None):
        collection = self.db[table_name]

        query = self.build_query(start_date, end_date, symbol)
        if not query:
            print('cannot delete the whole table')
            return None

        collection.delete_many(query)

    def read(self, table_name, start_date=None, end_date=None, symbol=None):
        collection = self.db[table_name]

        query = self.build_query(start_date, end_date, symbol)
        if not query:
            print('cannot read the whole table')
            return None

        segs = []
        for x in collection.find(query):
            x['data'] = self.deser(x['data'], x['ver'])
            segs.append(x)
        segs.sort(key=lambda x: (x['symbol'], x['date'], x['start']))
        return pd.concat([x['data'] for x in segs], ignore_index=True) if segs else None

    def list_tables(self):
        return self.db.collection_names()

    def list_dates(self, table_name, start_date=None, end_date=None, symbol=None):
        collection = self.db[table_name]
        dates = set()
        if start_date is None:
            start_date = '00000000'
        if end_date is None:
            end_date = '99999999'
        for x in collection.find(self.build_query(start_date, end_date, symbol), {"date": 1, '_id': 0}):
            dates.add(x['date'])
        return sorted(list(dates))

    def ser(self, s, version):
        if version == 1:
            return gzip.compress(pickle.dumps(s), compresslevel=2)
        elif version == 2:
            return lzma.compress(pickle.dumps(s), preset=1)
        else:
            raise Exception('unknown version')

    def deser(self, s, version):
        def unpickle(s):
            return pickle.loads(s)

        if version == 1:
            return unpickle(gzip.decompress(s))
        elif version == 2:
            return unpickle(lzma.decompress(s))
        else:
            raise Exception('unknown version')


def patch_pandas_pickle():
    if pd.__version__ < '0.24':
        import sys
        from types import ModuleType
        from pandas.core.internals import BlockManager
        pkg_name = 'pandas.core.internals.managers'
        if pkg_name not in sys.modules:
            m = ModuleType(pkg_name)
            m.BlockManager = BlockManager
            sys.modules[pkg_name] = m

In [2]:
db = DB("192.168.10.178", 'com_md_eq_cn', 'zhenyuy', 'bnONBrzSMGoE')

In [ ]:
db.read('md_order', start_date=thisDate_str, end_date=thisDate_str, symbol=[2000725])

In [5]:
m = 1
print('m' in dir())
del m
print('m' in dir())

True
False