In [1]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import pickle
from matplotlib import pyplot as plt
import statsmodels.api as sm
from matplotlib.ticker import Formatter
import collections
import glob
import os
import datetime
pd.set_option("max_columns", 200)



for y in ['20200602']:
    print('----------------------------------------------------------------')
    print(y)
    readPath = '\\\\192.168.10.30\\Kevin_zhenyu\\temp\\kuanrui\\' + y + '\\SH\\snapshot\\Level_2\\***'
    dataPathLs = np.array(glob.glob(readPath))
    dateLs = np.array([int(os.path.basename(i).split('.')[0]) for i in dataPathLs])
    dataPathLs = dataPathLs[(dateLs >= 600000) & (dateLs <= 700000)]
    logSH1 = []
    ll = []
    startTm = datetime.datetime.now()
    for i in dataPathLs:
        try:
            df = pd.read_csv(i)
        except:
            print("empty data")
            print(i)
            ll.append(int(os.path.basename(i).split('.')[0]))
            continue
        df["StockID"] = int(os.path.basename(i).split('.')[0])
        logSH1 += [df]
    del df
    logSH1 = pd.concat(logSH1).reset_index(drop=True)
    print(datetime.datetime.now() - startTm)
    
    for i in range(1, 6):
        if i == 1:
            logSH1["bid" + str(i) + "p"] = logSH1["BidPrice"].apply(lambda x: float(x.split(',')[0][1:]))
            logSH1["ask" + str(i) + "p"] = logSH1["OfferPrice"].apply(lambda x: float(x.split(',')[0][1:]))
            logSH1["bid" + str(i) + "q"] = logSH1["BidOrderQty"].apply(lambda x: int(x.split(',')[0][1:]))
            logSH1["ask" + str(i) + "q"] = logSH1["OfferOrderQty"].apply(lambda x: int(x.split(',')[0][1:]))
        else:
            logSH1["bid" + str(i) + "p"] = logSH1["BidPrice"].apply(lambda x: float(x.split(',')[i-1]))
            logSH1["ask" + str(i) + "p"] = logSH1["OfferPrice"].apply(lambda x: float(x.split(',')[i-1]))
            logSH1["bid" + str(i) + "q"] = logSH1["BidOrderQty"].apply(lambda x: int(x.split(',')[i-1]))
            logSH1["ask" + str(i) + "q"] = logSH1["OfferOrderQty"].apply(lambda x: int(x.split(',')[i-1]))
    logSH1 = logSH1.rename(columns={"Volume":"cum_volume", "Amount":"cum_amount", "LastPx":"close", "OpenPx":"openPrice"})
    logSH1["time"] = (logSH1["QuotTime"] - int(y)*1000000000).astype(np.int64)
        
    path1 = np.array(glob.glob('\\\\192.168.10.30\\Kevin_zhenyu\\rawData\\logs_' + y + '_zs_92_01_day_data\\mdLog_SH_*'))[0]
    path2 = np.array(glob.glob('\\\\192.168.10.30\\Kevin_zhenyu\\rawData\\logs_' + y + '_zs_92_01_day_data\\mdLog_SZ_*'))[0]
    path3 = np.array(glob.glob('\\\\192.168.10.30\\Kevin_zhenyu\\rawData\\logs_' + y + '_zt_96_04_day_96data\\mdLog_SH_*'))[0]
    
    
    startTm = datetime.datetime.now()
    logSH2 = pd.read_csv(path3,
                    encoding="utf-8").loc[:, ["clockAtArrival", "sequenceNo", "source", "StockID",
                                              "exchange", "time", "cum_volume", "cum_amount", "close",
                                              "bid1p", "bid2p", "bid3p", "bid4p", "bid5p", "bid1q",
                                              "bid2q", "bid3q", "bid4q", "bid5q", "ask1p", "ask2p",
                                              "ask3p", "ask4p", "ask5p", "ask1q", "ask2q", "ask3q",
                                              "ask4q", "ask5q", "openPrice"]]
    print(datetime.datetime.now() - startTm)
    logSH2["time"] = logSH2["time"].apply(lambda x: int((x.replace(':', "")).replace(".", ""))) 
    display(len(ll))
    display(len(set(logSH2["StockID"].unique()) & set(ll)))
    
    print('----------------------------------------------------------------')
    print('SH lv2 data:')
    in_dex = [16, 300, 852, 905]
    data1 = logSH2[~logSH2["StockID"].isin(in_dex) & (logSH2["time"] >= 91500000) & (logSH2["time"] <= 145700000) \
              & (logSH2["source"] == 13)]
    data1["cum_amount"] = data1["cum_amount"].round(2)
    data2 = logSH1[~logSH1["StockID"].isin(in_dex) & (logSH1["time"] >= 91500000) & (logSH1["time"] <= 145700000)]
    columns = ["StockID", "cum_volume", "cum_amount", "close", "bid1p", "bid2p", "bid3p", "bid4p", "bid5p", "bid1q", "bid2q",
           "bid3q", "bid4q", "bid5q", "ask1p", "ask2p", "ask3p", "ask4p", "ask5p", "ask1q", "ask2q", "ask3q",
           "ask4q", "ask5q", "openPrice"]
    data1_1 = data1.drop_duplicates(subset=columns, keep="first").reset_index()
    data2_1 = data2.drop_duplicates(subset=columns, keep="first").reset_index()

    n1 = len(data1_1["StockID"].unique())
    n2 = len(data2_1["StockID"].unique())
    print(n1)
    print(n2)
    print(len(set(data1_1["StockID"].unique()) - set(data2_1["StockID"].unique()) - set(ll)))
    print(set(data1_1["StockID"].unique()) - set(data2_1["StockID"].unique()) - set(ll))
    print(set(data2_1["StockID"].unique()) - set(data1_1["StockID"].unique()) - set(ll))
    
    
    
    print('----------------------------------------------------------------')
    print('SH index data:')

    readPath = '\\\\192.168.10.30\\Kevin_zhenyu\\temp\\kuanrui\\' + y + '\\SH\\snapshot\\Level_2\\***'
    dataPathLs = np.array(glob.glob(readPath))
    dateLs = np.array([int(os.path.basename(i).split('.')[0]) for i in dataPathLs])
    dataPathLs = dataPathLs[(dateLs == 16) | (dateLs == 300) | (dateLs == 852) | (dateLs == 905)]
    index = []
    
    startTm = datetime.datetime.now()
    for i in dataPathLs:
        df = pd.read_csv(i)
        df["StockID"] = int(os.path.basename(i).split('.')[0])
        index += [df]
    index = pd.concat(index).reset_index(drop=True)
    print(datetime.datetime.now() - startTm)
    
    for i in range(1, 6):
        if i == 1:
            index["bid" + str(i) + "p"] = index["BidPrice"].apply(lambda x: float(x.split(',')[0][1:]))
            index["ask" + str(i) + "p"] = index["OfferPrice"].apply(lambda x: float(x.split(',')[0][1:]))
            index["bid" + str(i) + "q"] = index["BidOrderQty"].apply(lambda x: int(x.split(',')[0][1:]))
            index["ask" + str(i) + "q"] = index["OfferOrderQty"].apply(lambda x: int(x.split(',')[0][1:]))
        else:
            index["bid" + str(i) + "p"] = index["BidPrice"].apply(lambda x: float(x.split(',')[i-1]))
            index["ask" + str(i) + "p"] = index["OfferPrice"].apply(lambda x: float(x.split(',')[i-1]))
            index["bid" + str(i) + "q"] = index["BidOrderQty"].apply(lambda x: int(x.split(',')[i-1]))
            index["ask" + str(i) + "q"] = index["OfferOrderQty"].apply(lambda x: int(x.split(',')[i-1]))
    index = index.rename(columns={"Volume":"cum_volume", "Amount":"cum_amount", "LastPx":"close", "OpenPx":"openPrice"})
    index["time"] = (index["QuotTime"] - int(y)*1000000000).astype(np.int64)
    
    startTm = datetime.datetime.now()
    logSH = pd.read_csv(path1,
                    encoding="utf-8").loc[:, ["clockAtArrival", "sequenceNo", "source", "StockID",
                                              "exchange", "time", "cum_volume", "cum_amount", "close",
                                              "bid1p", "bid2p", "bid3p", "bid4p", "bid5p", "bid1q",
                                              "bid2q", "bid3q", "bid4q", "bid5q", "ask1p", "ask2p",
                                              "ask3p", "ask4p", "ask5p", "ask1q", "ask2q", "ask3q",
                                              "ask4q", "ask5q", "openPrice"]]
    print(datetime.datetime.now() - startTm)
    logSH["time"] = logSH["time"].apply(lambda x: int((x.replace(':', "")).replace(".", "")))
    
    print(index["StockID"].unique())
    
    data1 = logSH[(logSH["StockID"].isin(in_dex)) & (logSH["time"] >= 91500000) & (logSH["time"] <= 145700000)]
    data2 = index[(index["StockID"].isin(in_dex)) & (index["time"] >= 91500000) & (index["time"] <= 145700000)]

    data2["close"] = data2["close"].round(4)
    data1["close"] = data1["close"].round(4)
    data2["openPrice"] = data2["openPrice"].round(4)
    data1["openPrice"] = data1["openPrice"].round(4)

    columns = ["StockID", "cum_volume", "close", "openPrice"]
    data1_1 = data1.drop_duplicates(subset=columns, keep="first").reset_index()
    data2_1 = data2.drop_duplicates(subset=columns, keep="first").reset_index()

    test = pd.merge(data1_1, data2_1, left_on=columns, right_on=columns, how="outer")
    n1 = test["time_x"].count()
    n2 = test["time_y"].count()
    len1 = len(test)
    print(n1)
    print(n2)
    print(len1)
    if n2 < len1:
        display("test is not complete:")
        display(test[np.isnan(test["time_y"])])

----------------------------------------------------------------
20200602
0:03:22.633407
0:01:04.720676

0

0

----------------------------------------------------------------
SH lv2 data:

C:\Users\win\Anaconda3\lib\site-packages\ipykernel_launcher.py:77: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

1606
1607
10
{600226, 600074, 600589, 600175, 600145, 600081, 600306, 601969, 600824, 600889}
{688516, 688360, 605001, 605288, 688588, 603950, 605168, 688466, 601778, 688566, 688598}
----------------------------------------------------------------
SH index data:
0:00:00.336101
0:01:11.774156
[ 16 852 300 905]

C:\Users\win\Anaconda3\lib\site-packages\ipykernel_launcher.py:142: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\win\Anaconda3\lib\site-packages\ipykernel_launcher.py:143: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\win\Anaconda3\lib\site-packages\ipykernel_launcher.py:144: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\win\Anaconda3\lib\site-packages\ipykernel_launcher.py:145: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

11392
11392
11396

'test is not complete:'

,index_x,clockAtArrival,sequenceNo,source,StockID,exchange,time_x,cum_volume,cum_amount_x,close,bid1p_x,bid2p_x,bid3p_x,bid4p_x,bid5p_x,bid1q_x,bid2q_x,bid3q_x,bid4q_x,bid5q_x,ask1p_x,ask2p_x,ask3p_x,ask4p_x,ask5p_x,ask1q_x,ask2q_x,ask3q_x,ask4q_x,ask5q_x,openPrice,index_y,NumTrades,OfferTradeMaxDuration,ImageStatus,TotalBidNumber,TotalWarrantExecQty,WithdrawSellMoney,IOPV,BidOrders,ETFSellAmount,TotalOfferQty,WithdrawBuyNumber,WeightedAvgOfferPx,ETFBuyNumber,WarLowerPx,MsgSeqNum,WithdrawSellAmount,ETFSellMoney,BidOrderQty,HighPx,PreClosePx,LowPx,WeightedAvgBidPx,ETFSellNumber,OfferNumOrders,WithdrawSellNumber,ETFBuyAmount,TotalOfferNumber,OfferPrice,NumOfferOrders,BidPrice,OfferOrderQty,TotalBidQty,SendingTime,ETFBuyMoney,InstrumentStatus,WithdrawBuyAmount,ClosePx,BidTradeMaxDuration,NumBidOrders,cum_amount_y,AveragePx,WarUpperPx,YieldToMaturity,BidNumOrders,WithdrawBuyMoney,TradingPhaseCode,QuotTime,OfferOrders,bid1p_y,ask1p_y,bid1q_y,ask1q_y,bid2p_y,ask2p_y,bid2q_y,ask2q_y,bid3p_y,ask3p_y,bid3q_y,ask3q_y,bid4p_y,ask4p_y,bid4q_y,ask4q_y,bid5p_y,ask5p_y,bid5q_y,ask5q_y,time_y
8405,9685489.0,1.591077e+15,99370292.0,5.0,300,SH,135446000.0,110564926,1.501225e+11,3983.2830,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3969.9521,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8406,9685493.0,1.591077e+15,99370376.0,5.0,852,SH,135446000.0,151634694,1.534475e+11,6012.6158,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6012.5660,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8407,9685494.0,1.591077e+15,99370377.0,5.0,905,SH,135446000.0,107750780,1.161571e+11,5575.9232,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5595.3589,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8441,9721519.0,1.591077e+15,99654992.0,5.0,300,SH,135531000.0,110819310,1.505186e+11,3983.2645,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3969.9521,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import pickle
from matplotlib import pyplot as plt
import statsmodels.api as sm
from matplotlib.ticker import Formatter
import collections
import glob
import os
import datetime
pd.set_option("max_columns", 200)

df = pd.read_table(r"J:\LEVEL2_shenzhen\2016\01\06\SZL2_TRADE_20160106\SZL2_TRADE_20160106_AM.txt", header=None)
df.columns=["TRADEDATE", "SENDTIME", "SETNO", "RECNO", "BUYORDERRECNO", "SELLORDERRECNO", "SECURITYID", "PRICE",
           "TRADEQTY", "ORDERKIND", "FUNCTIONCODE", "TRADETIME"]

,TRADEDATE,SENDTIME,SETNO,RECNO,BUYORDERRECNO,SELLORDERRECNO,SECURITYID,PRICE,TRADEQTY,ORDERKIND,FUNCTIONCODE,TRADETIME
9103207,20160106,111105,6,1351780,1893761,1878257,2096,22.86,800,0,0,111104530
9103680,20160106,111109,6,1352253,1881770,1894363,2096,22.85,100,0,0,111108230
9103719,20160106,111109,6,1352292,1881770,1894419,2096,22.85,500,0,0,111108530
9103949,20160106,111111,6,1352522,1881770,1894691,2096,22.85,800,0,0,111110340
9104082,20160106,111112,6,1352655,1881770,1894927,2096,22.85,2000,0,0,111111720
...,...,...,...,...,...,...,...,...,...,...,...,...
9220969,20160106,112814,6,1469542,2023578,0,2096,0.00,1000,0,C,112811930
9223360,20160106,112839,6,1471933,2049190,1988932,2096,22.90,1000,0,0,112838430
9226129,20160106,112915,6,1474702,2052935,1988932,2096,22.90,500,0,0,112914640
9228931,20160106,112944,6,1477504,2052811,0,2096,0.00,1000,0,C,112942200
9229029,20160106,112944,6,1477602,2055953,1988932,2096,22.90,1000,0,0,112943790

In [12]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import pickle
from matplotlib import pyplot as plt
import statsmodels.api as sm
from matplotlib.ticker import Formatter
import collections
import glob
import os
import datetime
pd.set_option("max_columns", 200)

F1 = open(r"C:\Users\win\Desktop\data.pkl", 'rb')
snapshot = pickle.load(F1)

In [ ]:
tr = snapshot.groupby("StockID")["time4"].first().reset_index()
display(tr.head(20))

l1 = []
l2 = []
name = []
mr = pd.DataFrame()
for secid in np.sort(snapshot["StockID"].unique()):
    re = snapshot[(snapshot["StockID"] == secid) & (snapshot["time_interval"] > 60) & (snapshot["trade_diff"] > snapshot[(snapshot["StockID"] == secid) & (snapshot["time"] > 93000000) & (snapshot["time"] < 145700000)]["trade_diff"].describe([0.97])["97%"]) \
        & (snapshot["time"] > snapshot["time1"]) & (snapshot["time"] != snapshot["time2"]) & (snapshot["time"] != snapshot["time3"])]
    l1.append(re.shape[0])
    name.append(secid)
    if re.shape[0] == 1:
        l2.append(re["time"].values[0])
    else:
        l2.append(re["time"].values)
mr["StockID"] = name
mr["count"] = l1
mr["time"] = l2
mr

    StockID      time4
0         1  140735860
1         5  140735370
2         6  140735090
3         8  140735800
4         9  140737260
5        10  140735040
6        11  140732950
7        12  140732040
8        14  140734810
9        17  140734110
10       18  140736710
11       19  140736060
12       20  140736500
13       21  140736730
14       22  140726380
15       25  140737270
16       26  140734700
17       27  140735220
18       28  140737490
19       29  140736670

In [102]:
kk = pd.merge(mr[mr["count"] == 1], tr, on="StockID", how="left")
kk[kk["time"] != kk["time4"]]

Empty DataFrame
Columns: [StockID, count, time, time4]
Index: []

In [97]:
secid = 300417
snapshot[(snapshot["StockID"] == secid) & (snapshot["time_interval"] > 60) & (snapshot["trade_diff"] > snapshot[(snapshot["StockID"] == secid) & (snapshot["time"] > 93000000) & (snapshot["time"] < 145700000)]["trade_diff"].describe([0.97])["97%"]) \
        & (snapshot["time"] > snapshot["time1"]) & (snapshot["time"] != snapshot["time2"]) & (snapshot["time"] != snapshot["time3"])]

,Date,SENDTIME,StockID,DATATIMESTAMP,PreClosePx,openPrice,HighPx,LowPx,close,NUMTRADES,cum_volume,cum_amount,TOTALLONGPOSITION,PERATIO1,PERATIO2,ENDOFDAYMAKER,TOTALOFFERQTY,WEIGHTEDAVGOFFERPX,TOTALBIDQTY,WEIGHTEDAVGBIDPX,ask10p,ask9p,ask8p,ask7p,ask6p,ask5p,ask4p,ask3p,ask2p,ask1p,bid1p,bid2p,bid3p,bid4p,bid5p,bid6p,bid7p,bid8p,bid9p,bid10p,ask10q,ask9q,ask8q,ask7q,ask6q,ask5q,ask4q,ask3q,ask2q,ask1q,bid1q,bid2q,bid3q,bid4q,bid5q,bid6q,bid7q,bid8q,bid9q,bid10q,NUMORDERS_B1,NOORDERS _B1,ORDERQTY_B1,NUMORDERS_S1,NOORDERS _S1,ORDERQTY_S1,time,OrigTime,cum_max,group,trade_diff,time_diff,volume_update,time1,time2,time3,time4,datetime,time_interval
7389901,20160329,140741,300417,140709630,72.49,72.24,72.96,69.51,71.0,1279,355630,25195148.4,0,98.37,0.0,N,63093,75.97,70200,68.0,71.64,71.61,71.6,71.5,71.46,71.45,71.42,71.4,71.36,71.14,71.08,71.02,71.0,70.91,70.89,70.88,70.65,70.64,70.57,70.56,200,700,500,200,1300,500,1200,100,200,500,200,100,3400,100,200,1000,200,100,300,200,1,1,200,1,1,200,140709630,20160329140709630,455019,4690,4.0,300990.0,400.0,93000440,130004690,150039230.0,140709630,2016-03-29 14:07:09,181.0

In [76]:
for secid in mr[mr["count"] < 1]["StockID"]:
    print(secid)
    print(snapshot[(snapshot["StockID"] == secid) & (snapshot["time_interval"] > 60) & (snapshot["trade_diff"] > snapshot[(snapshot["StockID"] == secid) & (snapshot["time"] > 93000000) & (snapshot["time"] < 145700000)]["trade_diff"].describe([0.95])["95%"]) \
        & (snapshot["time"] > snapshot["time1"]) & (snapshot["time"] != snapshot["time2"]) & (snapshot["time"] != snapshot["time3"])].shape[0])
    print(snapshot[(snapshot["StockID"] == secid) & (snapshot["time_interval"] > 60) & (snapshot["trade_diff"] > snapshot[(snapshot["StockID"] == secid) & (snapshot["time"] > 93000000) & (snapshot["time"] < 145700000)]["trade_diff"].describe([0.9])["90%"]) \
        & (snapshot["time"] > snapshot["time1"]) & (snapshot["time"] != snapshot["time2"]) & (snapshot["time"] != snapshot["time3"])].shape[0])

70
1
1
828
1
1
877
1
1
985
1
1
2082
1
1
2110
1
1
2188
1
1
2394
1
1
2451
1
1
2531
1
1
2534
1
1
2674
1
1
2725
0
0
2731
1
1
2791
0
0
2792
0
0
300238
0
0
300368
1
1
300417
1
1
300484
0
0
300506
0
0

In [1]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import pickle
from matplotlib import pyplot as plt
import statsmodels.api as sm
from matplotlib.ticker import Formatter
import collections
import glob
import os
import datetime
pd.set_option("max_columns", 200)


readPath = r"\\192.168.10.30\Kevin_zhenyu\temp\kuanrui\20200602\SZ\snapshot\Level_2\***"
dataPathLs = np.array(glob.glob(readPath))
dateLs = np.array([int(os.path.basename(i).split('.')[0]) for i in dataPathLs])
dataPathLs = dataPathLs[(dateLs > 1) & (dateLs <= 200)]
for i in dataPathLs[:1]:
    df = pd.read_csv(i)
    assert(len(df.columns) == 36)
    m = 0
    l = []
    for j in df.columns:
        if (len(df[j].unique()) == 1):
            l.append(j)
            m = m + 1
#             print(j)
#             print(df[j].unique())
    if len(l) == 8:
        print(i)
        print(l)

\\192.168.10.30\Kevin_zhenyu\temp\kuanrui\20200602\SZ\snapshot\Level_2\000031.csv
['LowerLimitPx', 'ImageStatus', 'PeRatio2', 'WeightedAvgPxChg', 'UpperLimitPx', 'TotalLongPosition', 'PreWeightedAvgPx', 'PreClosePx']

In [6]:
(5.26 * 2020230 + 4.94 * 641861) / (2020230 + 641861)

5.18284429044687

In [3]:
df[(df["SendingTime"] > 20200602093030000)]

,NumTrades,OfferNumOrders,LowerLimitPx,ImageStatus,OfferPrice,BidPrice,BidOrders,OfferOrderQty,PeRatio2,TotalBidQty,SendingTime,PeRatio1,TotalOfferQty,ClosePx,WeightedAvgPxChg,Change2,Change1,LastPx,WeightedAvgOfferPx,Amount,UpperLimitPx,AveragePx,TotalLongPosition,MsgSeqNum,Volume,BidNumOrders,BidOrderQty,TradingPhaseCode,QuotTime,OpenPx,OfferOrders,PreWeightedAvgPx,HighPx,PreClosePx,LowPx,WeightedAvgBidPx
103,181,"[13,23,31,42,15,20,5,14,11,10]",4.51,1,"[5.05,5.06,5.07,5.08,5.09,5.1,5.11,5.12,5.13,5...","[5.04,5.03,5.02,5.01,5,4.99,4.98,4.97,4.96,4.95]","[1400,300,1200,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...","[63910,104000,101320,194700,127900,146000,1840...",0,641861,20200602093033000,9.10,2020230,0.00,0,0.01,0.04,5.05,5.26,1521272.07,5.51,5.05005,0,358172,301239,"[3,8,13,6,9,6,5,6,16,14]","[2900,55161,44000,20000,13700,8600,26100,51000...",T0,20200602093033000,5.06,"[6810,8100,8800,2000,21500,1000,3000,300,2900,...",0,5.06,5.01,5.03,4.94
104,184,"[13,22,31,42,15,20,5,14,11,10]",4.51,1,"[5.05,5.06,5.07,5.08,5.09,5.1,5.11,5.12,5.13,5...","[5.04,5.03,5.02,5.01,5,4.99,4.98,4.97,4.96,4.95]","[800,300,1200,29300,1900,3200,100,100,100,200,...","[58410,100600,101320,194700,127900,146000,1840...",0,654961,20200602093036000,9.10,2011330,0.00,0,0.01,0.04,5.05,5.26,1552071.07,5.51,5.05003,0,358921,307339,"[12,7,14,6,9,6,5,6,16,14]","[38900,29861,46400,20000,13700,8600,26100,5100...",T0,20200602093036000,5.06,"[1310,8100,8800,2000,21500,1000,3000,300,2900,...",0,5.06,5.01,5.03,4.94
105,196,"[12,22,31,42,15,20,5,14,11,10]",4.51,1,"[5.05,5.06,5.07,5.08,5.09,5.1,5.11,5.12,5.13,5...","[5.04,5.03,5.02,5.01,5,4.99,4.98,4.97,4.96,4.95]","[1400,100,100,100,200,100,100,200,200,35100,0,...","[38010,98900,101320,194700,127900,146000,18400...",0,662561,20200602093039000,9.10,1989230,0.00,0,0.01,0.04,5.05,5.26,1739366.07,5.51,5.04985,0,359651,344439,"[10,8,14,7,9,6,5,6,16,14]","[37600,37761,46400,21000,13700,8600,26100,5100...",T0,20200602093039000,5.06,"[10610,1000,3000,300,2900,5000,400,2000,2100,5...",0,5.06,5.01,5.03,4.94
106,213,"[22,31,42,15,20,4,15,11,10,17]",4.51,1,"[5.06,5.07,5.08,5.09,5.1,5.11,5.12,5.13,5.14,5...","[5.05,5.04,5.03,5.02,5.01,5,4.99,4.98,4.97,4.96]","[90,900,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","[98900,101320,194700,127900,146000,16800,92300...",0,678651,20200602093042000,9.10,1951620,0.00,0,0.00,0.04,5.05,5.26,1931316.57,5.51,5.04987,0,360391,382449,"[2,9,8,14,7,9,6,5,6,16]","[990,52700,37761,46400,21000,13700,8600,26100,...",T0,20200602093042000,5.06,"[1000,20300,10800,9700,1000,500,2000,2000,4200...",0,5.06,5.01,5.03,4.94
107,220,"[21,31,41,15,20,4,15,11,10,17]",4.51,1,"[5.06,5.07,5.08,5.09,5.1,5.11,5.12,5.13,5.14,5...","[5.05,5.04,5.03,5.02,5.01,5,4.99,4.98,4.97,4.96]","[25790,200,50000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...","[96000,101320,192700,127900,146000,16800,92300...",0,720151,20200602093045000,9.10,1946720,0.00,0,-0.01,0.04,5.05,5.27,2003063.57,5.51,5.04997,0,361120,396649,"[3,4,8,14,7,9,6,5,6,16]","[75990,17000,39961,46400,21000,13700,8600,2610...",T0,20200602093045000,5.06,"[17600,10800,9700,1000,500,2000,4200,3200,2000...",0,5.06,5.01,5.03,4.95
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4024,8029,"[44,52,61,115,52,64,79,77,122,18]",4.51,1,"[5.12,5.13,5.14,5.15,5.16,5.17,5.18,5.19,5.2,5...","[5.11,5.1,5.09,5.08,5.07,5.06,5.05,5.04,5.03,5...","[11970,1400,100,2100,8200,10000,1600,1000,1000...","[224500,472793,262200,253400,170300,183800,350...",0,1144070,20200602161003000,9.21,5328761,5.11,0,0.00,0.10,5.11,5.30,58923768.79,5.51,5.12332,0,12150924,11501087,"[18,74,20,41,12,18,16,7,14,5]","[151670,303600,66700,151400,45200,36300,23200,...",E0,20200602161003000,5.06,"[8200,1600,8000,11800,10000,2000,2000,3000,100...",0,5.19,5.01,5.03,5.03
4025,8029,"[44,52,61,115,52,64,79,77,122,18]",4.51,1,"[5.12,5.13,5.14,5.15,5.16,5.17,5.18,5.19,5.2,5...","[5.11,5.1,5.09,5.08,5.07,5.06,5.05,5.04,5.03,5...","[11970,1400,100,2100,8200,10000,1600,1000,1000...","[224500,472793,262200,253400,170300,183800,350...",0,1144070,20200602161103000,9.21,5328761,5.11,0,0.00,0.10,5.11,5.30,58923768.79,5.51,5.12332,0,12151930,11501087,"[18,74,20,41,12,18,16,7,14,5]","[151670,303600,66700,151400,45200,36300,23200,...",E0,20200602161103000,5.06,"[8200,1600,8000,11800,10000,2000,2000,3000,100...",0,5.19,5.01,5.03,5.03
4026,8029,"[44,52,61,115,52,64,79,77,122,18]",4.51,1,"[5.12,5.13,5.14,5.15,5.16,5.17,5.18,5.19,5.2,5...","[5.11,5.1,5.09,5.08,5.07,5.06,5.05,5.04,5.03,5...","[11970,1400,100,2100,8200,10000,1600,1000,1000...","[224500,472793,262200,253400,170300,183800,350...",0,1144070,20200602161203000,9.21,5328761,5.11,0,0.00,0.10,5.11,5.30,58923768.79,5.51,5.12332,0,12152945,11501087,"[18,74,20,41,12,18,16,7,14,5]","[151670,303600,66700,151400,45200,36300,23200,...",E0,20200602161203000,5.06,"[8200,1600,8000,11800,10000,2000,2000,3000,100...",0,5.19,5.01,5.03,5.03
4027,8029,"[44,52,61,115,52,64,79,77,122,18]",4.51,1,"[5.12,5.13,5.14,5.15,5.16,5.17,5.18,5.19,5.2,5...","[5.11,5.1,5.09,5.08,5.07,5.06,5.05,5.04,5.03,5...","[11970,1400,100,2100,8200,10000,1600,1000,1000...","[224500,472793,262200,253400,170300,183800,350...",0,1144070,20200602161303000,9.21,5328761,5.11,0,0.00,0.10,5.11,5.30,58923768.79,5.51,5.12332,0,12153927,11501087,"[18,74,20,41,12,18,16,7,14,5]","[151670,303600,66700,151400,45200,36300,23200,...",E0,20200602161303000,5.06,"[8200,1600,8000,11800,10000,2000,2000,3000,100...",0,5.19,5.01,5.03,5.03
4028,8029,"[44,52,61,115,52,64,79,77,122,18]",4.51,1,"[5.12,5.13,5.14,5.15,5.16,5.17,5.18,5.19,5.2,5...","[5.11,5.1,5.09,5.08,5.07,5.06,5.05,5.04,5.03,5...","[11970,1400,100,2100,8200,10000,1600,1000,1000...","[224500,472793,262200,253400,170300,183800,350...",0,1144070,20200602161403000,9.21,5328761,5.11,0,0.00,0.10,5.11,5.30,58923768.79,5.51,5.12332,0,12154948,11501087,"[18,74,20,41,12,18,16,7,14,5]","[151670,303600,66700,151400,45200,36300,23200,...",E0,20200602161403000,5.06,"[8200,1600,8000,11800,10000,2000,2000,3000,100...",0,5.19,5.01,5.03,5.03

In [158]:
df['PeRatio1'].unique()

array([85.5 , 85.16, 85.06, 85.11, 85.21, 85.01, 85.26, 84.96, 85.3 ,
       85.35, 85.4 , 85.45, 85.6 , 85.55, 85.64, 85.69, 85.74, 85.79,
       85.84, 85.89, 85.94, 85.99, 86.03, 86.08, 86.13, 86.18, 86.23,
       86.28, 86.37, 86.47, 86.42, 86.52, 86.91, 86.86, 86.96, 86.67,
       86.81, 87.01, 87.06, 87.1 , 87.15, 87.25, 87.3 , 87.35, 87.2 ,
       86.76, 86.62, 86.72, 86.57])

In [62]:
df["IOPV"].unique()

array([0.   , 1.235, 1.246, 1.249, 1.25 , 1.251, 1.252, 1.254, 1.255,
       1.256, 1.257, 1.253, 1.258, 1.259, 1.26 , 1.261, 1.262, 1.263,
       1.264, 1.265, 1.266, 1.267, 1.268, 1.269])

In [33]:
sum(df[i] != 0)

0

In [9]:
df

,NumTrades,OfferTradeMaxDuration,ImageStatus,TotalBidNumber,TotalWarrantExecQty,WithdrawSellMoney,IOPV,BidOrders,ETFSellAmount,TotalOfferQty,...,LastPx,Amount,AveragePx,WarUpperPx,YieldToMaturity,BidNumOrders,WithdrawBuyMoney,TradingPhaseCode,QuotTime,OfferOrders
0,0,-1,1,0,0,0,0,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",0,0,...,0.00,0,0.00,0,0,"[0,0,0,0,0,0,0,0,0,0]",0,S 10,20200601084550000,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0..."
1,0,-1,1,0,0,0,0,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",0,0,...,0.00,0,0.00,0,0,"[0,0,0,0,0,0,0,0,0,0]",0,S 10,20200601084650000,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0..."
2,0,-1,1,0,0,0,0,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",0,0,...,0.00,0,0.00,0,0,"[0,0,0,0,0,0,0,0,0,0]",0,S 10,20200601084750000,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0..."
3,0,-1,1,0,0,0,0,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",0,0,...,0.00,0,0.00,0,0,"[0,0,0,0,0,0,0,0,0,0]",0,S 10,20200601084850000,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0..."
4,0,-1,1,0,0,0,0,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",0,0,...,0.00,0,0.00,0,0,"[0,0,0,0,0,0,0,0,0,0]",0,S 10,20200601084951000,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421,1,3,1,0,0,0,0,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",0,0,...,99.45,9945000,99.45,0,0,"[0,0,0,0,0,0,0,0,0,0]",0,E110,20200601154007000,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0..."
422,1,3,1,0,0,0,0,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",0,0,...,99.45,9945000,99.45,0,0,"[0,0,0,0,0,0,0,0,0,0]",0,E110,20200601154107000,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0..."
423,1,3,1,0,0,0,0,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",0,0,...,99.45,9945000,99.45,0,0,"[0,0,0,0,0,0,0,0,0,0]",0,E110,20200601154207000,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0..."
424,1,3,1,0,0,0,0,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",0,0,...,99.45,9945000,99.45,0,0,"[0,0,0,0,0,0,0,0,0,0]",0,E110,20200601154307000,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0..."
425,1,3,1,0,0,0,0,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",0,0,...,99.45,9945000,99.45,0,0,"[0,0,0,0,0,0,0,0,0,0]",0,E110,20200601154408000,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0..."

In [9]:
test[np.isnan(test["time_x"])]

,index_x,clockAtArrival,sequenceNo,source,StockID,exchange,time_x,cum_volume,cum_amount_x,close,bid1p_x,bid2p_x,bid3p_x,bid4p_x,bid5p_x,bid1q_x,bid2q_x,bid3q_x,bid4q_x,bid5q_x,ask1p_x,ask2p_x,ask3p_x,ask4p_x,ask5p_x,ask1q_x,ask2q_x,ask3q_x,ask4q_x,ask5q_x,openPrice,index_y,NumTrades,OfferTradeMaxDuration,ImageStatus,TotalBidNumber,TotalWarrantExecQty,WithdrawSellMoney,IOPV,BidOrders,ETFSellAmount,TotalOfferQty,WithdrawBuyNumber,WeightedAvgOfferPx,ETFBuyNumber,WarLowerPx,MsgSeqNum,WithdrawSellAmount,ETFSellMoney,BidOrderQty,HighPx,PreClosePx,LowPx,WeightedAvgBidPx,ETFSellNumber,OfferNumOrders,WithdrawSellNumber,ETFBuyAmount,TotalOfferNumber,OfferPrice,NumOfferOrders,BidPrice,OfferOrderQty,TotalBidQty,SendingTime,ETFBuyMoney,InstrumentStatus,WithdrawBuyAmount,ClosePx,BidTradeMaxDuration,NumBidOrders,cum_amount_y,AveragePx,WarUpperPx,YieldToMaturity,BidNumOrders,WithdrawBuyMoney,TradingPhaseCode,QuotTime,OfferOrders,bid1p_y,ask1p_y,bid1q_y,ask1q_y,bid2p_y,ask2p_y,bid2q_y,ask2q_y,bid3p_y,ask3p_y,bid3q_y,ask3q_y,bid4p_y,ask4p_y,bid4q_y,ask4q_y,bid5p_y,ask5p_y,bid5q_y,ask5q_y,time_y
11392,NaN,NaN,NaN,NaN,16,NaN,NaN,26346135,NaN,2884.6224,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2864.5289,3462.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",0.0,0.0,0.0,0.0,0.0,0.0,3408009.0,0.0,0.0,"[0,0,0,0,0,0,0,0,0,0]",2890.8071,2870.3558,2862.6765,0.0,0.0,"[0,0,0,0,0,0,0,0,0,0]",0.0,0.0,0.0,"[0,0,0,0,0,0,0,0,0,0]",0.0,"[0,0,0,0,0,0,0,0,0,0]","[0,0,0,0,0,0,0,0,0,0]",0.0,2.020060e+16,0.0,NaN,0.0,0.0,0.0,0.0,4.759531e+10,2877.51965,0.0,0.0,"[0,0,0,0,0,0,0,0,0,0]",0.0,NaN,2.020060e+16,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,145659020.0
11393,NaN,NaN,NaN,NaN,852,NaN,NaN,192626851,NaN,6002.2036,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6012.5660,7031.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",0.0,0.0,0.0,0.0,0.0,0.0,3408028.0,0.0,0.0,"[0,0,0,0,0,0,0,0,0,0]",6021.2651,5993.7853,5978.7724,0.0,0.0,"[0,0,0,0,0,0,0,0,0,0]",0.0,0.0,0.0,"[0,0,0,0,0,0,0,0,0,0]",0.0,"[0,0,0,0,0,0,0,0,0,0]","[0,0,0,0,0,0,0,0,0,0]",0.0,2.020060e+16,0.0,NaN,0.0,0.0,0.0,0.0,1.954922e+11,6001.82714,0.0,0.0,"[0,0,0,0,0,0,0,0,0,0]",0.0,NaN,2.020060e+16,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,145659020.0
11394,NaN,NaN,NaN,NaN,300,NaN,NaN,142610849,NaN,3981.9625,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3969.9521,10599.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",0.0,0.0,0.0,0.0,0.0,0.0,3408023.0,0.0,0.0,"[0,0,0,0,0,0,0,0,0,0]",3991.7761,3971.3402,3958.9774,0.0,0.0,"[0,0,0,0,0,0,0,0,0,0]",0.0,0.0,0.0,"[0,0,0,0,0,0,0,0,0,0]",0.0,"[0,0,0,0,0,0,0,0,0,0]","[0,0,0,0,0,0,0,0,0,0]",0.0,2.020060e+16,0.0,NaN,0.0,0.0,0.0,0.0,1.934532e+11,3975.10907,0.0,0.0,"[0,0,0,0,0,0,0,0,0,0]",0.0,NaN,2.020060e+16,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,145659020.0
11395,NaN,NaN,NaN,NaN,905,NaN,NaN,137419045,NaN,5567.2595,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5595.3589,14168.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",0.0,0.0,0.0,0.0,0.0,0.0,3408028.0,0.0,0.0,"[0,0,0,0,0,0,0,0,0,0]",5596.4399,5569.4800,5544.1862,0.0,0.0,"[0,0,0,0,0,0,0,0,0,0]",0.0,0.0,0.0,"[0,0,0,0,0,0,0,0,0,0]",0.0,"[0,0,0,0,0,0,0,0,0,0]","[0,0,0,0,0,0,0,0,0,0]",0.0,2.020060e+16,0.0,NaN,0.0,0.0,0.0,0.0,1.475484e+11,5571.70179,0.0,0.0,"[0,0,0,0,0,0,0,0,0,0]",0.0,NaN,2.020060e+16,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,145659020.0

In [13]:
data1_1[(data1_1["StockID"] == 300) & (data1_1["cum_volume"] >= 110564926)].head(5)

,index,clockAtArrival,sequenceNo,source,StockID,exchange,time,cum_volume,cum_amount,close,bid1p,bid2p,bid3p,bid4p,bid5p,bid1q,bid2q,bid3q,bid4q,bid5q,ask1p,ask2p,ask3p,ask4p,ask5p,ask1q,ask2q,ask3q,ask4q,ask5q,openPrice
8405,9685489,1591077286501317,99370292,5,300,SH,135446000,110564926,1.501225e+11,3983.2830,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,3969.9521
8409,9689388,1591077291502174,99399842,5,300,SH,135451000,110601156,1.501711e+11,3983.3345,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,3969.9521
8413,9693856,1591077296501956,99431053,5,300,SH,135456000,110627779,1.502133e+11,3983.3730,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,3969.9521
8417,9697455,1591077301503092,99462655,5,300,SH,135501000,110649056,1.502460e+11,3983.1262,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,3969.9521
8421,9701417,1591077306503229,99493140,5,300,SH,135506000,110676880,1.502890e+11,3982.8281,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,3969.9521

In [15]:
index[(index["StockID"] == 300) & (index["cum_volume"] >= 110564926)].head(5)

,NumTrades,OfferTradeMaxDuration,ImageStatus,TotalBidNumber,TotalWarrantExecQty,WithdrawSellMoney,IOPV,BidOrders,ETFSellAmount,TotalOfferQty,WithdrawBuyNumber,WeightedAvgOfferPx,ETFBuyNumber,WarLowerPx,MsgSeqNum,WithdrawSellAmount,ETFSellMoney,cum_volume,BidOrderQty,openPrice,HighPx,PreClosePx,LowPx,WeightedAvgBidPx,ETFSellNumber,OfferNumOrders,WithdrawSellNumber,ETFBuyAmount,TotalOfferNumber,OfferPrice,NumOfferOrders,BidPrice,OfferOrderQty,TotalBidQty,SendingTime,ETFBuyMoney,InstrumentStatus,WithdrawBuyAmount,ClosePx,BidTradeMaxDuration,NumBidOrders,close,cum_amount,AveragePx,WarUpperPx,YieldToMaturity,BidNumOrders,WithdrawBuyMoney,TradingPhaseCode,QuotTime,OfferOrders,StockID,bid1p,ask1p,bid1q,ask1q,bid2p,ask2p,bid2q,ask2q,bid3p,ask3p,bid3q,ask3q,bid4p,ask4p,bid4q,ask4q,bid5p,ask5p,bid5q,ask5q,time
9792,0,0,1,0,0,0,0,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",0,0,0,0,0,0,2575664,0,0,110601156,"[0,0,0,0,0,0,0,0,0,0]",3969.9521,3984.0966,3971.3402,3958.9774,0,0,"[0,0,0,0,0,0,0,0,0,0]",0,0,0,"[0,0,0,0,0,0,0,0,0,0]",0,"[0,0,0,0,0,0,0,0,0,0]","[0,0,0,0,0,0,0,0,0,0]",0,20200602135451000,0,NaN,0,0.0,0,0,3983.3345,1.501711e+11,3972.84221,0,0,"[0,0,0,0,0,0,0,0,0,0]",0,NaN,20200602135449940,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",300,0.0,0.0,0,0,0.0,0.0,0,0,0.0,0.0,0,0,0.0,0.0,0,0,0.0,0.0,0,0,135449940
9793,0,0,1,0,0,0,0,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",0,0,0,0,0,0,2576844,0,0,110627779,"[0,0,0,0,0,0,0,0,0,0]",3969.9521,3984.0966,3971.3402,3958.9774,0,0,"[0,0,0,0,0,0,0,0,0,0]",0,0,0,"[0,0,0,0,0,0,0,0,0,0]",0,"[0,0,0,0,0,0,0,0,0,0]","[0,0,0,0,0,0,0,0,0,0]",0,20200602135456000,0,NaN,0,0.0,0,0,3983.3730,1.502133e+11,3972.84474,0,0,"[0,0,0,0,0,0,0,0,0,0]",0,NaN,20200602135455640,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",300,0.0,0.0,0,0,0.0,0.0,0,0,0.0,0.0,0,0,0.0,0.0,0,0,0.0,0.0,0,0,135455640
9794,0,0,1,0,0,0,0,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",0,0,0,0,0,0,2577954,0,0,110649056,"[0,0,0,0,0,0,0,0,0,0]",3969.9521,3984.0966,3971.3402,3958.9774,0,0,"[0,0,0,0,0,0,0,0,0,0]",0,0,0,"[0,0,0,0,0,0,0,0,0,0]",0,"[0,0,0,0,0,0,0,0,0,0]","[0,0,0,0,0,0,0,0,0,0]",0,20200602135501000,0,NaN,0,0.0,0,0,3983.1262,1.502460e+11,3972.84672,0,0,"[0,0,0,0,0,0,0,0,0,0]",0,NaN,20200602135500740,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",300,0.0,0.0,0,0,0.0,0.0,0,0,0.0,0.0,0,0,0.0,0.0,0,0,0.0,0.0,0,0,135500740
9795,0,0,1,0,0,0,0,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",0,0,0,0,0,0,2579055,0,0,110676880,"[0,0,0,0,0,0,0,0,0,0]",3969.9521,3984.0966,3971.3402,3958.9774,0,0,"[0,0,0,0,0,0,0,0,0,0]",0,0,0,"[0,0,0,0,0,0,0,0,0,0]",0,"[0,0,0,0,0,0,0,0,0,0]","[0,0,0,0,0,0,0,0,0,0]",0,20200602135506000,0,NaN,0,0.0,0,0,3982.8281,1.502890e+11,3972.84923,0,0,"[0,0,0,0,0,0,0,0,0,0]",0,NaN,20200602135504940,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",300,0.0,0.0,0,0,0.0,0.0,0,0,0.0,0.0,0,0,0.0,0.0,0,0,0.0,0.0,0,0,135504940
9796,0,0,1,0,0,0,0,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",0,0,0,0,0,0,2580239,0,0,110712623,"[0,0,0,0,0,0,0,0,0,0]",3969.9521,3984.0966,3971.3402,3958.9774,0,0,"[0,0,0,0,0,0,0,0,0,0]",0,0,0,"[0,0,0,0,0,0,0,0,0,0]",0,"[0,0,0,0,0,0,0,0,0,0]","[0,0,0,0,0,0,0,0,0,0]",0,20200602135511000,0,NaN,0,0.0,0,0,3983.0402,1.503296e+11,3972.85252,0,0,"[0,0,0,0,0,0,0,0,0,0]",0,NaN,20200602135510920,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",300,0.0,0.0,0,0,0.0,0.0,0,0,0.0,0.0,0,0,0.0,0.0,0,0,0.0,0.0,0,0,135510920

In [158]:
import pandas as pd
import random
import numpy as np
import glob
import os
from unrar import rarfile
import py7zr
import pickle
import datetime

pd.set_option("max_columns", 200)

columns1 = ["Date","OrigTime","SendTime","ercvtime","dbtime","ChannelNo","SecurityID","SecurityIDsource", "MDStreamID","PreClosePx",
                   "PxChnage1","PXChange2","openPrice","HighPx","LowPx","close","NumTrades","cum_volume","cum_amount","PE1","PE2","TradingPhase",
                   "totalofferqty", "wa_offerPrice", "totalbidqty", "wa_bidPrice", "PreNAV", "RealTimeNAV", "WarrantPremiumRate", "UpLimitPx",
                   "DownLimitPx", "TotalLongPosition", "unknown1", "unknown2", "unknown3"]
columns2 = ['Date',"OrigTime","SendTime","ercvtime","dbtime","ChannelNo","SecurityID","SecurityIDsource", "MDStreamID",'ask1p','bid1p',
                   "ask1q","bid1q", 'ask2p','bid2p',"ask2q","bid2q",'ask3p','bid3p',"ask3q","bid3q",'ask4p','bid4p',"ask4q","bid4q",'ask5p',
                    'bid5p',"ask5q","bid5q",'ask6p','bid6p',"ask6q","bid6q",'ask7p','bid7p',"ask7q","bid7q",'ask8p','bid8p',"ask8q","bid8q",
                   'ask9p','bid9p',"ask9q","bid9q",'ask10p','bid10p',"ask10q","bid10q","NUMORDERS_B1","NOORDERS_B1","ORDERQTY_B1",
                    "NUMORDERS_S1","NOORDERS_S1","ORDERQTY_S1"]
columns3 = ["Date", "SENDTIME", "SecurityID", "DATATIMESTAMP", "PreClosePx", "openPrice", "HighPx", "LowPx", "close", "NUMTRADES", "cum_volume",
           "cum_amount", "TOTALLONGPOSITION", "PERATIO1", "PERATIO2", "ENDOFDAYMAKER", "TOTALOFFERQTY", "WEIGHTEDAVGOFFERPX", "TOTALBIDQTY", "WEIGHTEDAVGBIDPX"]
columns4 = ["Date", "SENDTIME", "SecurityID", "DATATIMESTAMP", "ask10p", "ask9p", "ask8p", "ask7p", "ask6p", "ask5p", "ask4p", "ask3p", "ask2p",
           "ask1p", "bid1p", "bid2p", "bid3p", "bid4p", "bid5p", "bid6p", "bid7p", "bid8p", "bid9p", "bid10p", "ask10q", "ask9q", "ask8q", "ask7q",
           "ask6q", "ask5q", "ask4q", "ask3q", "ask2q", "ask1q", "bid1q", "bid2q", "bid3q", "bid4q", "bid5q", "bid6q", "bid7q", "bid8q", "bid9q", 
           "bid10q", "NUMORDERS_B1", "NOORDERS _B1", "ORDERQTY_B1", "NUMORDERS_S1", "NOORDERS _S1", "ORDERQTY_S1"]
columns5 =  ["Date","OrigTime","SendTime","ercvtime","dbtime","ChannelNo","SecurityID","SecurityIDsource", "MDStreamID","PreClosePx",
                   "PxChnage1","PXChange2","openPrice","HighPx","LowPx","close","NumTrades","cum_volume","cum_amount","PE1","PE2","TradingPhase",
                   "totalofferqty", "wa_offerPrice", "totalbidqty", "wa_bidPrice", "PreNAV", "RealTimeNAV", "WarrantPremiumRate", "UpLimitPx",
                   "DownLimitPx", "TotalLongPosition"]

year = "2016"
df = []
bad = []
readPath = 'J:\\LEVEL2_shenzhen\\' + year + '\\12\\26'
dataPathLs = np.array(glob.glob(readPath))

for data in dataPathLs:
    if len(np.array(glob.glob(data +'\\***'))) == 0:
        continue
    
    if data[-5:-3] + data[-2:] == '0413':
        bad.append(data)
        continue
    
    print('---------------------------------------------------------------------------------------------')
    print(data)
    # SZ version A without AM PM, 未分卷
    if len(np.array(glob.glob(data +'\\SZL2_SNAPSHOTDW_***.7z'))) == 1:
        path = r'F:\SZ\2016' 
        d_ate = os.path.basename(glob.glob(data +'\\SZL2_SNAPSHOTDW_***.7z')[0]).split('.')[0].split('_')[2]
        os.chdir(data)
        n_ame = os.path.basename(glob.glob(data +'\\SZL2_SNAPSHOTDW_***.7z')[0]).split('.')[0]
        try:
            a = py7zr.SevenZipFile(data + "\\" + n_ame + '.7z','r',filters=None)
        except:
            print("Bad unzip here!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
            print(data + "\\" + n_ame + '.7z')
            bad.append(data + "\\" + n_ame + '.7z')
            continue
        path1 = path + '\\' + d_ate
        a.extractall(path = path1)
        a.close()
        
        snapshot1 = pd.DataFrame()
        snapshot2 = pd.DataFrame()
        if len(np.array(glob.glob(path1 +'\\SZL2_SNAPSHOTDW_***.txt'))) != 2:
            print("Less data!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
            bad.append(data + '\\SZL2_SNAPSHOTDW_***')
            print(np.array(glob.glob(path1 +'\\***'))[0])
            continue
        if len(np.array(glob.glob(path1 +'\\SZL2_SNAPSHOT_***.txt'))) != 2:
            print("Less data!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
            bad.append(data + '\\SZL2_SNAPSHOT_***')
            print(np.array(glob.glob(path1 +'\\***'))[0])
            continue
        for pp in np.array(glob.glob(path1 +'\\SZL2_SNAPSHOT_***.txt')):
            s1 = pd.read_table(pp, header=None)
            assert(s1.shape[1] == len(columns3))
            s1.columns = columns3
            snapshot1 = pd.concat([snapshot1, s1])
        del s1
        for pp in np.array(glob.glob(path1 +'\\SZL2_SNAPSHOTDW_***.txt')):
            s2 = pd.read_table(pp, header=None)
            assert(s2.shape[1] == len(columns4))
            s2.columns = columns4
            snapshot2 = pd.concat([snapshot2, s2])
        del s2
        snapshot1 = snapshot1[(snapshot1["SecurityID"] < 4000) | (snapshot1["SecurityID"] > 300000)]
        snapshot2 = snapshot2[(snapshot2["SecurityID"] < 4000) | (snapshot2["SecurityID"] > 300000)]
        snapshot1 = snapshot1[snapshot1["DATATIMESTAMP"] != 0]
        snapshot2 = snapshot2[snapshot2["DATATIMESTAMP"] != 0]
        snapshot = pd.merge(snapshot1, snapshot2, on=["Date", "SENDTIME", "SecurityID", "DATATIMESTAMP"], how="outer")
        try:
            assert((snapshot1.shape[0] == snapshot.shape[0]) & (snapshot2.shape[0] == snapshot.shape[0]))
        except:
            if snapshot1.shape[0] == snapshot.shape[0]:
                print("snapshot have more ticks than snapshotdw")
                tt = snapshot[(snapshot["ask1p"].isnull()) & (snapshot["DATATIMESTAMP"] < 145600000)]["DATATIMESTAMP"].unique()
                print(tt)
                print(snapshot[(snapshot["ask1p"].isnull()) & (snapshot["DATATIMESTAMP"].isin(tt))].groupby("DATATIMESTAMP")["ask1p"].size())
                print(np.sort(snapshot[(snapshot["ask1p"].isnull()) & (snapshot["DATATIMESTAMP"] >= 145600000)]["DATATIMESTAMP"].unique()))
                print(snapshot[(snapshot["ask1p"].isnull()) & (snapshot["DATATIMESTAMP"] >= 145600000)].shape[0])
                print((snapshot.shape[0] - snapshot2.shape[0])/snapshot.shape[0])
            elif snapshot2.shape[0] == snapshot.shape[0]:
                print("snapshotdw have more ticks than snapshot")
                print(snapshot[snapshot["close"].isnull()]["DATATIMESTAMP"].unique().min())
                print((snapshot.shape[0] - snapshot1.shape[0])/snapshot.shape[0])
            else:
                print("snapshotdw don't join with snapshot")
            snapshot = pd.merge(snapshot1, snapshot2, on=["Date", "SENDTIME", "SecurityID", "DATATIMESTAMP"])
        del snapshot1
        del snapshot2
        snapshot['time'] = snapshot["DATATIMESTAMP"]
        snapshot["SecurityID"] = snapshot["SecurityID"].astype(int)
        snapshot = snapshot.rename(columns={"SecurityID":"StockID"})
        snapshot["OrigTime"] = snapshot["Date"] * 1000000000 + snapshot["DATATIMESTAMP"]
        snapshot.loc[snapshot["openPrice"] == 0, "LowPx"] = 0
        
        print("SZ version A without AM PM，未分卷")
        
    # SZ version A without AM PM, 分卷
    elif len(np.array(glob.glob(data +'\\SZL2_SNAPSHOTDW_***.7z.001'))) == 1:
        path = r'F:\SZ\2016' 
        d_ate = os.path.basename(glob.glob(data +'\\SZL2_SNAPSHOTDW_***.7z.001')[0]).split('.')[0].split('_')[2]
        os.chdir(data)
        n_ame = os.path.basename(glob.glob(data +'\\SZL2_SNAPSHOTDW_***.7z.001')[0]).split('.')[0]
        os.system("copy /b " + n_ame + ".7z.* " + n_ame + ".7z")
        try:
            a = py7zr.SevenZipFile(data + "\\" + n_ame + '.7z','r',filters=None)
        except:
            print("Bad unzip here!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
            print(data + "\\" + n_ame + '.7z')
            bad.append(data + "\\" + n_ame + '.7z')
            continue
        path1 = path + '\\' + d_ate
        a.extractall(path = path1)
        a.close()
        
        snapshot1 = pd.DataFrame()
        snapshot2 = pd.DataFrame()
        if len(np.array(glob.glob(path1 +'\\SZL2_SNAPSHOTDW_***.txt'))) != 2:
            print("Less data!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
            bad.append(data + '\\SZL2_SNAPSHOTDW_***')
            print(np.array(glob.glob(path1 +'\\***'))[0])
            continue
        elif len(np.array(glob.glob(path1 +'\\SZL2_SNAPSHOT_***.txt'))) != 2:
            print("Less data!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
            bad.append(data + '\\SZL2_SNAPSHOT_***')
            print(np.array(glob.glob(path1 +'\\***'))[0])
            continue
        for pp in np.array(glob.glob(path1 +'\\SZL2_SNAPSHOT_***.txt')):
            s1 = pd.read_table(pp, header=None)
            assert(s1.shape[1] == len(columns3))
            s1.columns = columns3
            snapshot1 = pd.concat([snapshot1, s1])
        del s1
        for pp in np.array(glob.glob(path1 +'\\SZL2_SNAPSHOTDW_***.txt')):
            s2 = pd.read_table(pp, header=None)
            assert(s2.shape[1] == len(columns4))
            s2.columns = columns4
            snapshot2 = pd.concat([snapshot2, s2])
        del s2
        snapshot1 = snapshot1[(snapshot1["SecurityID"] < 4000) | (snapshot1["SecurityID"] > 300000)]
        snapshot2 = snapshot2[(snapshot2["SecurityID"] < 4000) | (snapshot2["SecurityID"] > 300000)]
        snapshot1 = snapshot1[snapshot1["DATATIMESTAMP"] != 0]
        snapshot2 = snapshot2[snapshot2["DATATIMESTAMP"] != 0]
        snapshot = pd.merge(snapshot1, snapshot2, on=["Date", "SENDTIME", "SecurityID", "DATATIMESTAMP"], how="outer")
        try:
            assert((snapshot1.shape[0] == snapshot.shape[0]) & (snapshot2.shape[0] == snapshot.shape[0]))
        except:
            if snapshot1.shape[0] == snapshot.shape[0]:
                print("snapshot have more ticks than snapshotdw")
                print(snapshot[(snapshot["ask1p"].isnull()) & (snapshot["DATATIMESTAMP"] < 145600000)]["DATATIMESTAMP"].unique())
                print(snapshot[(snapshot["ask1p"].isnull()) & (snapshot["DATATIMESTAMP"] < 145600000)].shape[0])
                print(np.sort(snapshot[(snapshot["ask1p"].isnull()) & (snapshot["DATATIMESTAMP"] >= 145600000)]["DATATIMESTAMP"].unique()))
                print(snapshot[(snapshot["ask1p"].isnull()) & (snapshot["DATATIMESTAMP"] >= 145600000)].shape[0])
                print((snapshot.shape[0] - snapshot2.shape[0])/snapshot.shape[0])
            elif snapshot2.shape[0] == snapshot.shape[0]:
                print("snapshotdw have more ticks than snapshot")
                print(snapshot[snapshot["close"].isnull()]["DATATIMESTAMP"].unique().min())
                print((snapshot.shape[0] - snapshot1.shape[0])/snapshot.shape[0])
            else:
                print("snapshotdw don't join with snapshot")
            snapshot = pd.merge(snapshot1, snapshot2, on=["Date", "SENDTIME", "SecurityID", "DATATIMESTAMP"])
        del snapshot1
        del snapshot2
        snapshot['time'] = snapshot["DATATIMESTAMP"]
        snapshot["SecurityID"] = snapshot["SecurityID"].astype(int)
        snapshot = snapshot.rename(columns={"SecurityID":"StockID"})
        snapshot["OrigTime"] = snapshot["Date"] * 1000000000 + snapshot["DATATIMESTAMP"]
        snapshot.loc[snapshot["openPrice"] == 0, "LowPx"] = 0
        
        print("SZ version A without AM PM，分卷")
        
    # SZ version A AM PM
    # I:\\LEVEL2_shenzhen\\2016\\04\\19\\SZL2_SNAPSHOT_20160419_AM.7z 58
    # I:\\LEVEL2_shenzhen\\2016\\05\\06\\SZL2_SNAPSHOT_20160506_AM.txt 59
    elif len(np.array(glob.glob(data +'\\SZL2_SNAPSHOTDW_***_AM.txt'))) == 1:
        snap1 = pd.read_table(np.array(glob.glob(data +'\\SZL2_SNAPSHOTDW_***_AM.txt'))[0], header=None)
        assert(snap1.shape[1] == len(columns4))
        snap1.columns = columns4
        snap2 = pd.read_table(np.array(glob.glob(data +'\\SZL2_SNAPSHOTDW_***_PM.txt'))[0], header=None)
        assert(snap2.shape[1] == len(columns4))
        snap2.columns = columns4
        snapshot2 = pd.concat([snap1, snap2]).sort_values(by=["SecurityID", "DATATIMESTAMP"])
        del snap1
        del snap2
        
        snap1 = pd.read_table(np.array(glob.glob(data +'\\SZL2_SNAPSHOT_***_AM.txt'))[0], header=None)
        assert(snap1.shape[1] == len(columns3))
        snap1.columns = columns3
        snap2 = pd.read_table(np.array(glob.glob(data +'\\SZL2_SNAPSHOT_***_PM.txt'))[0], header=None)
        assert(snap2.shape[1] == len(columns3))
        snap2.columns = columns3
        snapshot1 = pd.concat([snap1, snap2]).sort_values(by=["SecurityID", "DATATIMESTAMP"])
        del snap1
        del snap2
        
        snapshot1 = snapshot1[(snapshot1["SecurityID"] < 4000) | (snapshot1["SecurityID"] > 300000)]
        snapshot2 = snapshot2[(snapshot2["SecurityID"] < 4000) | (snapshot2["SecurityID"] > 300000)]
        snapshot1 = snapshot1[snapshot1["DATATIMESTAMP"] != 0]
        snapshot2 = snapshot2[snapshot2["DATATIMESTAMP"] != 0]
        snapshot = pd.merge(snapshot1, snapshot2, on=["Date", "SENDTIME", "SecurityID", "DATATIMESTAMP"], how="outer")
        
        try:
            assert((snapshot1.shape[0] == snapshot.shape[0]) & (snapshot2.shape[0] == snapshot.shape[0]))
        except:
            if snapshot1.shape[0] == snapshot.shape[0]:
                print("snapshot have more ticks than snapshotdw")
                print(snapshot[(snapshot["ask1p"].isnull()) & (snapshot["DATATIMESTAMP"] < 145600000)]["DATATIMESTAMP"].unique())
                print(snapshot[(snapshot["ask1p"].isnull()) & (snapshot["DATATIMESTAMP"] < 145600000)].shape[0])
                print(np.sort(snapshot[(snapshot["ask1p"].isnull()) & (snapshot["DATATIMESTAMP"] >= 145600000)]["DATATIMESTAMP"].unique()))
                print(snapshot[(snapshot["ask1p"].isnull()) & (snapshot["DATATIMESTAMP"] >= 145600000)].shape[0])
                print((snapshot.shape[0] - snapshot2.shape[0])/snapshot.shape[0])
            elif snapshot2.shape[0] == snapshot.shape[0]:
                print("snapshotdw have more ticks than snapshot")
                print(snapshot[snapshot["close"].isnull()]["DATATIMESTAMP"].unique().min())
                print((snapshot.shape[0] - snapshot1.shape[0])/snapshot.shape[0])
            else:
                print("snapshotdw don't join with snapshot")
            snapshot = pd.merge(snapshot1, snapshot2, on=["Date", "SENDTIME", "SecurityID", "DATATIMESTAMP"])
            
        del snapshot1
        del snapshot2
        snapshot["SecurityID"] = snapshot["SecurityID"].astype(int)
        snapshot = snapshot.rename(columns={"SecurityID":"StockID"})
        snapshot['time'] = snapshot["DATATIMESTAMP"]
        snapshot["OrigTime"] = snapshot["Date"] * 1000000000 + snapshot["DATATIMESTAMP"]
        snapshot.loc[snapshot["openPrice"] == 0, "LowPx"] = 0
        
        print("SZ version A AM PM, txt")
                
        
    elif len(np.array(glob.glob(data +'\\SZL2_SNAPSHOTDW_***_AM.7z'))) == 1:
        path = r'F:\SZ\2016' 
        d_ate = os.path.basename(glob.glob(data +'\\SZL2_SNAPSHOTDW_***_AM.7z')[0]).split('.')[0].split('_')[2]
        os.chdir(data)
        n_ame = os.path.basename(glob.glob(data +'\\SZL2_SNAPSHOTDW_***_AM.7z')[0]).split('.')[0]
        try:
            a = py7zr.SevenZipFile(data + "\\" + n_ame + '.7z','r',filters=None)
        except:
            print("Bad unzip here!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
            print(data + "\\" + n_ame + '.7z')
            bad.append(data + "\\" + n_ame + '.7z')
            continue
        path1 = path + '\\' + d_ate
        a.extractall(path = path1)
        
        n_ame1 = os.path.basename(glob.glob(data +'\\SZL2_SNAPSHOTDW_***_PM.7z')[0]).split('.')[0]
        try:
            a = py7zr.SevenZipFile(data + "\\" + n_ame1 + '.7z','r',filters=None)
        except:
            print("Bad unzip here!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
            print(data + "\\" + n_ame1 + '.7z')
            bad.append(data + "\\" + n_ame1 + '.7z')
            continue
        a.extractall(path = path1)
        
        if len(np.array(glob.glob(path1 +'\\SZL2_SNAPSHOT_***'))) != 2:
            print("Less data!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
            bad.append(data + '\\SZL2_SNAPSHOT_***')
            print(np.array(glob.glob(path1 +'\\***'))[0])
            continue
        snap1 = pd.read_table(np.array(glob.glob(path1 +'\\SZL2_SNAPSHOT_***_AM.txt'))[0], header=None)
        assert(snap1.shape[1] == len(columns3))
        snap1.columns = columns3
        snap2 = pd.read_table(np.array(glob.glob(path1 +'\\SZL2_SNAPSHOT_***_PM.txt'))[0], header=None)
        assert(snap2.shape[1] == len(columns3))
        snap2.columns = columns3
        snapshot1 = pd.concat([snap1, snap2]).sort_values(by=["SecurityID", "DATATIMESTAMP"])
        del snap1
        del snap2
        
        snap1 = pd.read_table(np.array(glob.glob(path1 +'\\SZL2_SNAPSHOTDW_***_AM.txt'))[0], header=None)
        assert(snap1.shape[1] == len(columns4))
        snap1.columns = columns4
        snap2 = pd.read_table(np.array(glob.glob(path1 +'\\SZL2_SNAPSHOTDW_***_PM.txt'))[0], header=None)
        assert(snap2.shape[1] == len(columns4))
        snap2.columns = columns4
        snapshot2 = pd.concat([snap1, snap2]).sort_values(by=["SecurityID", "DATATIMESTAMP"])
        del snap1
        del snap2
        
        snapshot1 = snapshot1[(snapshot1["SecurityID"] < 4000) | (snapshot1["SecurityID"] > 300000)]
        snapshot2 = snapshot2[(snapshot2["SecurityID"] < 4000) | (snapshot2["SecurityID"] > 300000)]
        snapshot1 = snapshot1[snapshot1["DATATIMESTAMP"] != 0]
        snapshot2 = snapshot2[snapshot2["DATATIMESTAMP"] != 0]
        snapshot = pd.merge(snapshot1, snapshot2, on=["Date", "SENDTIME", "SecurityID", "DATATIMESTAMP"], how="outer")
        
        try:
            assert((snapshot1.shape[0] == snapshot.shape[0]) & (snapshot2.shape[0] == snapshot.shape[0]))
        except:
            if snapshot1.shape[0] == snapshot.shape[0]:
                print("snapshot have more ticks than snapshotdw")
                print(snapshot[(snapshot["ask1p"].isnull()) & (snapshot["DATATIMESTAMP"] < 145600000)]["DATATIMESTAMP"].unique())
                print(snapshot[(snapshot["ask1p"].isnull()) & (snapshot["DATATIMESTAMP"] < 145600000)].shape[0])
                print(np.sort(snapshot[(snapshot["ask1p"].isnull()) & (snapshot["DATATIMESTAMP"] >= 145600000)]["DATATIMESTAMP"].unique()))
                print(snapshot[(snapshot["ask1p"].isnull()) & (snapshot["DATATIMESTAMP"] >= 145600000)].shape[0])
                print((snapshot.shape[0] - snapshot2.shape[0])/snapshot.shape[0])
            elif snapshot2.shape[0] == snapshot.shape[0]:
                print("snapshotdw have more ticks than snapshot")
                print(snapshot[snapshot["close"].isnull()]["DATATIMESTAMP"].unique().min())
                print((snapshot.shape[0] - snapshot1.shape[0])/snapshot.shape[0])
            else:
                print("snapshotdw don't join with snapshot")
            snapshot = pd.merge(snapshot1, snapshot2, on=["Date", "SENDTIME", "SecurityID", "DATATIMESTAMP"])
        del snapshot1
        del snapshot2
        
        snapshot["SecurityID"] = snapshot["SecurityID"].astype(int)
        snapshot = snapshot.rename(columns={"SecurityID":"StockID"})
        snapshot['time'] = snapshot["DATATIMESTAMP"]
        snapshot["OrigTime"] = snapshot["Date"] * 1000000000 + snapshot["DATATIMESTAMP"]
        snapshot.loc[snapshot["openPrice"] == 0, "LowPx"] = 0
        
        print("SZ version A AM PM, .7z")
 
    # am & pm
    # 'I:\\LEVEL2_shenzhen\\2016\\05\\09\\am_snap_level_spot.7z'
    # 'I:\\LEVEL2_shenzhen\\2016\\05\\10\\am_snap_level_spot.7z.001'
    
    elif len(np.array(glob.glob(data +'\\am_snap_level_spot.7z'))) == 1:
        date = glob.glob(data +'\\am_snap_level_spot.7z')[0][19:23] + glob.glob(data +'\\am_snap_level_spot.7z')[0][24:26] + glob.glob(data +'\\am_snap_level_spot.7z')[0][27:29]
        path = r'F:\SZ\2016' 
        os.chdir(data)
        try:
            a = py7zr.SevenZipFile(data + '\\am_snap_level_spot.7z','r',filters=None)
        except:
            print("Bad unzip here!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
            print(data + '\\am_snap_level_spot.7z')
            bad.append(data + '\\am_snap_level_spot.7z')
            continue
        path1 = path + '\\' + date
        a.extractall(path = path1)
        a.close()
        try:
            a = py7zr.SevenZipFile(data + '\\pm_snap_level_spot.7z','r',filters=None)
        except:
            print("Bad unzip here!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
            print(data + '\\pm_snap_level_spot.7z')
            bad.append(data + '\\pm_snap_level_spot.7z')
            continue
        a.extractall(path = path1)
        a.close()
        
        if len(np.array(glob.glob(path1 +'\\***_hq_snap_spot.txt'))) != 2:
            print("Less data!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
            bad.append(data + '\\***_hq_snap_spot.txt')
            print(np.array(glob.glob(path1 +'\\***'))[0])
            continue
        am_snap1 = pd.read_table(path1 + "\\am_hq_snap_spot.txt", header=None)
        try:
            assert(am_snap1.shape[1] == len(columns1))
            am_snap1.columns = columns1       
        except:
            assert(am_snap1.shape[1] == len(columns5))
            am_snap1.columns = columns5     
        pm_snap1 = pd.read_table(path1 + "\\pm_hq_snap_spot.txt", header=None)
        try:
            assert(pm_snap1.shape[1] == len(columns1))
            pm_snap1.columns = columns1       
        except:
            assert(pm_snap1.shape[1] == len(columns5))
            pm_snap1.columns = columns5     
        snapshot1 = pd.concat([am_snap1, pm_snap1]).sort_values(by=["SecurityID", "OrigTime"])
        del am_snap1
        del pm_snap1
        
        am_snap1 = pd.read_table(path1 + "\\am_snap_level_spot.txt", header=None)
        assert(am_snap1.shape[1] == len(columns2))
        am_snap1.columns = columns2       
        pm_snap1 = pd.read_table(path1 + "\\pm_snap_level_spot.txt", header=None)
        assert(pm_snap1.shape[1] == len(columns2))
        pm_snap1.columns = columns2       
        snapshot2 = pd.concat([am_snap1, pm_snap1]).sort_values(by=["SecurityID", "OrigTime"])
        del am_snap1
        del pm_snap1
        
        snapshot1 = snapshot1[(snapshot1["SecurityID"] < 4000) | (snapshot1["SecurityID"] > 300000)]
        snapshot2 = snapshot2[(snapshot2["SecurityID"] < 4000) | (snapshot2["SecurityID"] > 300000)]
        snapshot1['time'] = (snapshot1['OrigTime'] - int(snapshot1['OrigTime'].iloc[0]//1000000000*1000000000)).astype(int)
        snapshot2['time'] = (snapshot2['OrigTime'] - int(snapshot2['OrigTime'].iloc[0]//1000000000*1000000000)).astype(int)
        snapshot = pd.merge(snapshot1, snapshot2, on=['Date',"OrigTime","ChannelNo","SecurityID","SecurityIDsource", "MDStreamID", "time"], how="outer")
        try:
            assert((snapshot.shape[0] == snapshot1.shape[0]) & (snapshot.shape[0] == snapshot2.shape[0]))
        except:
            if snapshot.shape[0] == snapshot1.shape[0]:
                print("snapshot1 have more ticks than snapshot2")
                if all(snapshot[(snapshot["dbtime_y"].isnull()) & ((snapshot["SecurityID"] < 4000) | (snapshot["SecurityID"] > 200000))]["time"].unique() > 150000000):
                    print("More ticks happens after 15:00")
                elif all(snapshot[(snapshot["dbtime_y"].isnull()) & ((snapshot["SecurityID"] < 4000) | (snapshot["SecurityID"] > 200000))]["time"].unique() < 93000000):
                    print("More ticks happens before 9:30")
                else:
                    print("There are ticks happens before 15:00, after 9:30")
            elif snapshot.shape[0] == snapshot2.shape[0]:
                print("snapshot2 have more ticks than snapshot1")
                if all(snapshot[(snapshot["dbtime_x"].isnull()) & ((snapshot["SecurityID"] < 4000) | (snapshot["SecurityID"] > 200000))]["time"].unique() > 150000000):
                    print("More ticks happens after 15:00")
                elif all(snapshot[(snapshot["dbtime_x"].isnull()) & ((snapshot["SecurityID"] < 4000) | (snapshot["SecurityID"] > 200000))]["time"].unique() < 93000000):
                    print("More ticks happens before 9:30")
                else:
                    print("There are ticks happens before 15:00, after 9:30")
            else:
                print("snapshot2 don't join with snapshot1")
            snapshot = pd.merge(snapshot1, snapshot2, on=['Date',"OrigTime","ChannelNo","SecurityID","SecurityIDsource", "MDStreamID", "time"])
        del snapshot1
        del snapshot2
           
        snapshot = snapshot.rename(columns={"SecurityID":"StockID"})
        print(int(snapshot['OrigTime'].iloc[0]//1000000000*1000000000))
        
        print("am & pm data 未分卷")
        
    elif len(np.array(glob.glob(data +'\\am_snap_level_spot.7z.001'))) == 1:    
        date = glob.glob(data +'\\am_snap_level_spot.7z.001')[0][19:23] + glob.glob(data +'\\am_snap_level_spot.7z.001')[0][24:26] + glob.glob(data +'\\am_snap_level_spot.7z.001')[0][27:29]
        path = r'F:\SZ\2016' 
        os.chdir(data)
        os.system("copy /b am_snap_level_spot.7z.* am_snap_level_spot.7z")
        try:
            a = py7zr.SevenZipFile(data + '\\am_snap_level_spot.7z','r',filters=None)
        except:
            print("Bad unzip here!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
            print(data + '\\am_snap_level_spot.7z')
            bad.append(data + '\\am_snap_level_spot.7z')
            continue
        path1 = path + '\\' + date
        a.extractall(path = path1)
        a.close()
        
        os.system("copy /b pm_snap_level_spot.7z.* pm_snap_level_spot.7z")
        try:
            a = py7zr.SevenZipFile(data + '\\pm_snap_level_spot.7z','r',filters=None)
        except:
            print("Bad unzip here!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
            print(data + '\\pm_snap_level_spot.7z')
            bad.append(data + '\\pm_snap_level_spot.7z')
            continue
        a.extractall(path = path1)
        a.close()
        
        if len(np.array(glob.glob(path1 +'\\***_hq_snap_spot.txt'))) != 2:
            print("Less data!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
            bad.append(data + '\\***_hq_snap_spot.txt')
            print(np.array(glob.glob(path1 +'\\***'))[0])
            continue
        am_snap1 = pd.read_table(path1 + "\\am_hq_snap_spot.txt", header=None)
        try:
            assert(am_snap1.shape[1] == len(columns1))
            am_snap1.columns = columns1       
        except:
            assert(am_snap1.shape[1] == len(columns5))
            am_snap1.columns = columns5       
        pm_snap1 = pd.read_table(path1 + "\\pm_hq_snap_spot.txt", header=None)
        try:
            assert(pm_snap1.shape[1] == len(columns1))
            pm_snap1.columns = columns1       
        except:
            assert(pm_snap1.shape[1] == len(columns5))
            pm_snap1.columns = columns5     
        snapshot1 = pd.concat([am_snap1, pm_snap1]).sort_values(by=["SecurityID", "OrigTime"])
        del am_snap1
        del pm_snap1
        
        am_snap1 = pd.read_table(path1 + "\\am_snap_level_spot.txt", header=None)
        assert(am_snap1.shape[1] == len(columns2))
        am_snap1.columns = columns2        
        pm_snap1 = pd.read_table(path1 + "\\pm_snap_level_spot.txt", header=None)
        assert(pm_snap1.shape[1] == len(columns2))
        pm_snap1.columns = columns2       
        snapshot2 = pd.concat([am_snap1, pm_snap1]).sort_values(by=["SecurityID", "OrigTime"])
        del am_snap1
        del pm_snap1
        
        snapshot1 = snapshot1[(snapshot1["SecurityID"] < 4000) | (snapshot1["SecurityID"] > 300000)]
        snapshot2 = snapshot2[(snapshot2["SecurityID"] < 4000) | (snapshot2["SecurityID"] > 300000)]
        snapshot1['time'] = (snapshot1['OrigTime'] - int(snapshot1['OrigTime'].iloc[0]//1000000000*1000000000)).astype(int)
        snapshot2['time'] = (snapshot2['OrigTime'] - int(snapshot2['OrigTime'].iloc[0]//1000000000*1000000000)).astype(int)
        snapshot = pd.merge(snapshot1, snapshot2, on=['Date',"OrigTime","ChannelNo","SecurityID","SecurityIDsource", "MDStreamID", "time"], how="outer")
        try:
            assert((snapshot.shape[0] == snapshot1.shape[0]) & (snapshot.shape[0] == snapshot2.shape[0]))
        except:
            if snapshot.shape[0] == snapshot1.shape[0]:
                print("snapshot1 have more ticks than snapshot2")
                if all(snapshot[(snapshot["dbtime_y"].isnull()) & ((snapshot["SecurityID"] < 4000) | (snapshot["SecurityID"] > 200000))]["time"].unique() > 150000000):
                    print("More ticks happens after 15:00")
                elif all(snapshot[(snapshot["dbtime_y"].isnull()) & ((snapshot["SecurityID"] < 4000) | (snapshot["SecurityID"] > 200000))]["time"].unique() < 93000000):
                    print("More ticks happens before 9:30")
                else:
                    print("There are ticks happens before 15:00, after 9:30")
            elif snapshot.shape[0] == snapshot2.shape[0]:
                print("snapshot2 have more ticks than snapshot1")
                if all(snapshot[(snapshot["dbtime_x"].isnull()) & ((snapshot["SecurityID"] < 4000) | (snapshot["SecurityID"] > 200000))]["time"].unique() > 150000000):
                    print("More ticks happens after 15:00")
                elif all(snapshot[(snapshot["dbtime_x"].isnull()) & ((snapshot["SecurityID"] < 4000) | (snapshot["SecurityID"] > 200000))]["time"].unique() < 93000000):
                    print("More ticks happens before 9:30")
                else:
                    print("There are ticks happens before 15:00, after 9:30")
            else:
                print("snapshot2 don't join with snapshot1")
            snapshot = pd.merge(snapshot1, snapshot2, on=['Date',"OrigTime","ChannelNo","SecurityID","SecurityIDsource", "MDStreamID", "time"])
        del snapshot1
        del snapshot2
        
        snapshot = snapshot.rename(columns={"SecurityID":"StockID"})
        print(int(snapshot['OrigTime'].iloc[0]//1000000000*1000000000))
        
        print("am & pm data 分卷") 
    else:
        print("break!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
        break
        
        
    snapshot = snapshot[(snapshot["StockID"] < 4000) | (snapshot["StockID"] > 300000)]
    snapshot["cum_max"] = snapshot.groupby("StockID")["cum_volume"].transform(max)
    s2 = snapshot[snapshot["cum_volume"] == snapshot["cum_max"]].groupby("StockID").first().reset_index()
    s2["OrigTime"] = s2["OrigTime"].apply(lambda x: str(x//1000000000))
    s2["OrigTime"] = s2["OrigTime"].apply(lambda x: x[:4] + '-' + x[4:6] + '-' + x[6:])
    s2 = s2.rename(columns={"StockID": "ID", "OrigTime":"date", 'openPrice':"d_open", "PreClosePx":"d_yclose","HighPx":"d_high", "LowPx":"d_low", "close":"d_close", "cum_volume":"d_volume", "cum_amount":"d_amount"})
    s2 = s2[["ID", "date", "d_open", "d_yclose", "d_high", "d_low", "d_close", "d_volume", "d_amount"]]
    
    # 1. check massive missing   
    date = pd.DataFrame(pd.date_range(start='2019-06-10 08:30:00', end='2019-06-10 18:00:00', freq='s'), columns=["Orig"])
    date["time"] = date["Orig"].apply(lambda x: int(x.strftime("%H%M%S"))*1000)
    date["group"] = date["time"]//30000
    snapshot["group"] = snapshot["time"]//30000
    gl = date[((date["time"] >= 93000000) & (date["time"] <= 113000000))|((date["time"] >= 130000000) & (date["time"] <= 145700000))]["group"].unique()
    print("massive missing")
    print(set(gl) - set(snapshot["group"].unique()))
    
 
    # 2. check each security missing
#     snapshot = snapshot.sort_values(by=["StockID", "OrigTime"])
#     dd = snapshot[snapshot["cum_volume"] == snapshot["cum_max"]].groupby("StockID")["time"].first().reset_index()
    
#     data2 = snapshot[(snapshot["time"] > 92500000) & (snapshot["time"] <= 145700000) & (snapshot["cum_volume"] > 0)][["StockID", "cum_volume",
#                                                                                                                      "OrigTime", "time"]]
#     del snapshot
#     data2 = data2.sort_values(by=["StockID", "OrigTime"])    
#     data2["volume_update"] = data2.groupby("StockID")["cum_volume"].apply(lambda x: x - x.shift(1))
#     data2["time1"] = pd.to_datetime(data2["OrigTime"].apply(lambda x: str(x)[:-3]))
#     data2["time_interval"] = data2.groupby("StockID")["time1"].apply(lambda x: x - x.shift(1))
#     data2["time_interval"] = data2["time_interval"].apply(lambda x: x.seconds)
#     data2 = pd.merge(data2, data2[data2["volume_update"] > 0].groupby("StockID")["time_interval"].describe()["75%"].reset_index(), on="StockID")
#     data2 = data2.rename(columns={"75%": "75%_time"})
#     vu = data2[data2["volume_update"] > 0].groupby("StockID")["volume_update"].apply(lambda x: x.describe([0.9])["90%"]).reset_index()
#     vu = vu.rename(columns={"volume_update":"90%"})
#     data2 = pd.merge(data2, vu, on="StockID")
#     data2["90%"] = data2["90%"].apply(lambda x: max(1000, x))
#     data2["indicator"] = 0
#     data2.loc[data2[data2["time"] >= 130000000].groupby("StockID").head(1).index, 'indicator'] = 1
#     data2.loc[data2[data2["time"] >= 93000000].groupby("StockID").head(1).index, 'indicator'] = 1
#     data2 = data2[data2["indicator"] != 1]
#     print("single security missing")
#     print(data2[(data2["time_interval"] > 180) & (data2["volume_update"] >= data2["90%"]) & (data2["75%_time"] <= 4)])

---------------------------------------------------------------------------------------------
J:\LEVEL2_shenzhen\2016\12\26

C:\Users\win\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (51,54) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

20161226000000000
am & pm data 未分卷
massive missing
{3684, 3668, 3671, 3673, 3688, 3674, 4666, 4667, 4668, 3675, 4670, 4671, 3686, 4673, 4674, 4675, 4676, 4677, 4678, 3677, 4680, 4681, 3678, 4683, 4684, 4685, 4686, 4687, 4688, 4690, 4691, 3666, 4693, 4694, 4695, 4696, 4697, 4698, 3667, 4700, 4701, 3670, 4703, 4704, 4705, 4706, 4707, 4708, 3676, 4710, 4711, 3680, 4713, 4714, 4715, 4716, 4717, 4718, 3481, 4720, 4721, 3685, 4723, 4724, 4725, 4726, 4727, 4728, 3483, 4730, 4731, 3484, 4733, 4734, 4735, 4736, 4737, 4738, 3485, 4740, 4741, 3687, 4743, 4744, 4745, 4746, 4747, 4748, 3487, 4750, 4751, 3488, 4753, 4754, 4755, 4756, 4757, 4758, 3693, 4760, 4761, 3694, 4763, 4764, 4765, 4766, 4767, 4768, 3491, 4770, 4771, 3690, 4773, 4774, 4775, 4776, 4777, 4778, 3493, 4780, 4781, 3494, 4783, 3697, 3495, 3698, 3700, 3497, 3691, 3701, 3498, 3681, 3703, 3704, 3705, 3706, 3707, 3708, 3710, 3711, 3713, 3714, 3715, 3716, 3717, 3718, 3695, 3377, 3378, 3380, 3381, 3383, 3384, 3385, 3386, 3387, 3388, 3696, 3390, 3391, 3393, 3394, 3395, 3396, 3397, 3398, 3400, 3401, 3403, 3404, 3405, 3406, 3407, 3408, 3410, 3411, 3413, 3414, 3415, 3416, 3417, 3418, 3420, 3421, 3423, 3424, 3425, 3426, 3427, 3428, 3430, 3431, 3433, 3434, 3435, 3436, 3437, 3438, 3440, 3441, 3443, 3444, 3445, 3446, 3447, 3448, 3450, 3451, 3453, 3454, 3455, 3456, 3457, 3458, 3460, 3461, 3463, 3464, 3465, 3466, 3467, 3468, 3470, 3471, 3473, 3474, 3475, 3476, 4501, 3477, 4503, 4504, 4505, 4506, 4507, 4508, 3478, 4510, 4511, 3480, 4513, 4514, 4515, 4516, 4517, 4518, 3486, 4520, 4521, 3490, 4523, 4524, 4525, 4526, 4527, 4528, 3496, 4530, 4531, 3500, 3501, 3503, 3504, 3505, 3506, 3507, 3508, 3510, 3511, 3513, 3514, 3515, 3516, 3517, 3518, 3520, 3521, 3523, 3524, 3525, 3526, 3527, 3528, 3530, 3531, 3683}

In [165]:
snapshot[snapshot["group"] <= 3532]["time"].max()

101309000

In [176]:
date[date['group'] > 3531]

                     Orig       time  group
9000  2019-06-10 11:00:00  110000000   3666
9001  2019-06-10 11:00:01  110001000   3666
9002  2019-06-10 11:00:02  110002000   3666
9003  2019-06-10 11:00:03  110003000   3666
9004  2019-06-10 11:00:04  110004000   3666
...                   ...        ...    ...
34196 2019-06-10 17:59:56  175956000   5865
34197 2019-06-10 17:59:57  175957000   5865
34198 2019-06-10 17:59:58  175958000   5865
34199 2019-06-10 17:59:59  175959000   5865
34200 2019-06-10 18:00:00  180000000   6000

[25201 rows x 3 columns]

In [178]:
date[date["group"] == 4501]

                     Orig       time  group
19230 2019-06-10 13:50:30  135030000   4501
19231 2019-06-10 13:50:31  135031000   4501
19232 2019-06-10 13:50:32  135032000   4501
19233 2019-06-10 13:50:33  135033000   4501
19234 2019-06-10 13:50:34  135034000   4501
19235 2019-06-10 13:50:35  135035000   4501
19236 2019-06-10 13:50:36  135036000   4501
19237 2019-06-10 13:50:37  135037000   4501
19238 2019-06-10 13:50:38  135038000   4501
19239 2019-06-10 13:50:39  135039000   4501
19240 2019-06-10 13:50:40  135040000   4501
19241 2019-06-10 13:50:41  135041000   4501
19242 2019-06-10 13:50:42  135042000   4501
19243 2019-06-10 13:50:43  135043000   4501
19244 2019-06-10 13:50:44  135044000   4501
19245 2019-06-10 13:50:45  135045000   4501
19246 2019-06-10 13:50:46  135046000   4501
19247 2019-06-10 13:50:47  135047000   4501
19248 2019-06-10 13:50:48  135048000   4501
19249 2019-06-10 13:50:49  135049000   4501
19250 2019-06-10 13:50:50  135050000   4501
19251 2019-06-10 13:50:51  135051000   4501
19252 2019-06-10 13:50:52  135052000   4501
19253 2019-06-10 13:50:53  135053000   4501
19254 2019-06-10 13:50:54  135054000   4501
19255 2019-06-10 13:50:55  135055000   4501
19256 2019-06-10 13:50:56  135056000   4501
19257 2019-06-10 13:50:57  135057000   4501
19258 2019-06-10 13:50:58  135058000   4501
19259 2019-06-10 13:50:59  135059000   4501

In [182]:
snapshot[snapshot["time"] < 135013000]["time"].max()

135012000

In [184]:
# snapshot["trade_diff"] = snapshot.groupby("StockID")["NUMTRADES"].apply(lambda x: x-x.shift(1))
snapshot["time_diff"] = snapshot.groupby("StockID")["time"].apply(lambda x: x-x.shift(1))
snapshot["volume_update"] = snapshot.groupby("StockID")["cum_volume"].apply(lambda x: x-x.shift(1))
snapshot["datetime"] = pd.to_datetime(snapshot["OrigTime"].apply(lambda x: str(x)[:-3]))
snapshot["time_interval"] = snapshot.groupby("StockID")["datetime"].apply(lambda x: x - x.shift(1))
snapshot["time_interval"] = snapshot["time_interval"].apply(lambda x: x.seconds)

f1 = snapshot[(snapshot["time"] > 93000000) & (snapshot["volume_update"] != 0)].groupby("StockID")["time"].min().reset_index()
f1 = f1.rename(columns={"time": "time1"})
f2 = snapshot[(snapshot["time"] >= 130000000) & (snapshot["volume_update"] != 0)].groupby("StockID")["time"].min().reset_index()
f2 = f2.rename(columns={"time": "time2"})
f3 = snapshot[(snapshot["time"] > 150000000) & (snapshot["volume_update"] != 0)].groupby("StockID")["time"].min().reset_index()
f3 = f3.rename(columns={"time": "time3"})
snapshot = pd.merge(snapshot, f1, on="StockID", how="outer")
snapshot = pd.merge(snapshot, f2, on="StockID", how="outer")
snapshot = pd.merge(snapshot, f3, on="StockID", how="outer")

In [185]:
f4 = snapshot[(snapshot["time"] > 101310000) & (snapshot["volume_update"] != 0)].groupby("StockID")["time"].min().reset_index()
f4 = f4.rename(columns={"time": "time4"})
f5 = snapshot[(snapshot["time"] > 135013000) & (snapshot["volume_update"] != 0)].groupby("StockID")["time"].min().reset_index()
f5 = f5.rename(columns={"time": "time5"})
snapshot = pd.merge(snapshot, f4, on="StockID", how="outer")
snapshot = pd.merge(snapshot, f5, on="StockID", how="outer")
tr = snapshot.groupby("StockID")["time4", "time5"].first().reset_index()
display(tr.head(20))

    StockID        time4        time5
0         1  111609000.0  143524000.0
1         2  111600000.0  143524000.0
2         4  111609000.0  143524000.0
3         5  111600000.0  143527000.0
4         6  111609000.0  143524000.0
5         7  111615000.0  143524000.0
6         8  111603000.0  143524000.0
7         9  111600000.0  143524000.0
8        10  111600000.0  143524000.0
9        11  111609000.0  143524000.0
10       12  111600000.0  143524000.0
11       14  111615000.0  143524000.0
12       16  111609000.0  143524000.0
13       17  111600000.0  143524000.0
14       18  111600000.0  143524000.0
15       19  111609000.0  143524000.0
16       20  111600000.0  143524000.0
17       21  111600000.0  143524000.0
18       22  111600000.0  143524000.0
19       23  111612000.0  143524000.0

In [198]:
l1 = []
l2 = []
l3 = []
name = []
cum = []
mr1 = pd.DataFrame()

for secid in np.sort(snapshot["StockID"].unique()):
    re = snapshot[(snapshot["StockID"] == secid) & (snapshot["time_interval"] > 80) & (snapshot["volume_update"] > snapshot[(snapshot["StockID"] == secid) & (snapshot["time"] > 93000000) & (snapshot["time"] < 145700000) & (snapshot["time"] != snapshot["time2"])]["volume_update"].describe([0.9])["90%"]) \
        & (snapshot["time"] > snapshot["time1"]) & (snapshot["time"] != snapshot["time2"]) & (snapshot["time"] != snapshot["time3"])]
    l1.append(re.shape[0])
    name.append(secid)
    cum.append(len(snapshot[snapshot["StockID"] == secid]["cum_volume"].unique()))
    if re.shape[0] == 2:
        l2.append(re["time"].values[0])
        l3.append(re["time"].values[1])
    else:
        print(re)
        l2.append(re["time"].values)
        l3.append(np.nan)
mr1["StockID"] = name
mr1["count"] = l1
mr1["cum_volume"] = cum
mr1["time1"] = l2
mr1["time2"] = l3
mr1

Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []

Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []

Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []

Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []

Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []

Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []

Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []

Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []

Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []

Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []

Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []

Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []

Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []

Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
             Date           OrigTime         SendTime_x         ercvtime_x  \
3396057  20161226  20161226111606000  20161228094448452  20161228094448513

                  dbtime_x  ChannelNo  StockID  SecurityIDsource  MDStreamID  \
3396057  20161228094449713       1013   300575               102          10

         PreClosePx  PxChnage1  PXChange2  openPrice  HighPx  LowPx  close  \
3396057       42.72       4.27        0.0      46.99   46.99  46.99  46.99

         NumTrades  cum_volume  cum_amount    PE1  PE2 TradingPhase  \
3396057         17        6200    291338.0  36.34  0.0           T0

         totalofferqty  wa_offerPrice  totalbidqty  wa_bidPrice  PreNAV  \
3396057            0.0            0.0    1304000.0        46.82     0.0

         RealTimeNAV  WarrantPremiumRate  UpLimitPx  DownLimitPx  \
3396057          0.0                 0.0      46.99        38.45

         TotalLongPosition       time         SendTime_y         ercvtime_y  \
3396057                0.0  111606000  20161228094448452  20161228094448513

                  dbtime_y  ask1p  bid1p  ask1q    bid1q  ask2p  bid2p  ask2q  \
3396057  20161228094449713    0.0  46.99      0  1242300    0.0  46.98      0

         bid2q  ask3p  bid3p  ask3q  bid3q  ask4p  bid4p  ask4q  bid4q  ask5p  \
3396057    200    0.0  46.97      0    400    0.0   46.9      0    400    0.0

         bid5p  ask5q  bid5q  ask6p  bid6p  ask6q  bid6q  ask7p  bid7p  ask7q  \
3396057  46.69      0   4300    0.0  46.01      0   5000    0.0   46.0      0

         bid7q  ask8p  bid8p  ask8q  bid8q  ask9p  bid9p  ask9q  bid9q  \
3396057    300    0.0  44.82      0    100    0.0  42.72      0  50800

         ask10p  bid10p  ask10q  bid10q  NUMORDERS_B1  NOORDERS_B1  \
3396057     0.0    40.0       0     200           711           50

                                               ORDERQTY_B1  NUMORDERS_S1  \
3396057  2200|21500|20100|25100|30100|19600|3100|500|42...             0

         NOORDERS_S1 ORDERQTY_S1  cum_max  group   time_diff  volume_update  \
3396057            0         NaN     6900   3720  10355000.0         1700.0

                   datetime  time_interval       time1        time2  \
3396057 2016-12-26 11:16:06         3795.0  93006000.0  131730000.0

               time3        time4        time5
3396057  150003000.0  111606000.0  143727000.0
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []

Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
Empty DataFrame
Columns: [Date, OrigTime, SendTime_x, ercvtime_x, dbtime_x, ChannelNo, StockID, SecurityIDsource, MDStreamID, PreClosePx, PxChnage1, PXChange2, openPrice, HighPx, LowPx, close, NumTrades, cum_volume, cum_amount, PE1, PE2, TradingPhase, totalofferqty, wa_offerPrice, totalbidqty, wa_bidPrice, PreNAV, RealTimeNAV, WarrantPremiumRate, UpLimitPx, DownLimitPx, TotalLongPosition, time, SendTime_y, ercvtime_y, dbtime_y, ask1p, bid1p, ask1q, bid1q, ask2p, bid2p, ask2q, bid2q, ask3p, bid3p, ask3q, bid3q, ask4p, bid4p, ask4q, bid4q, ask5p, bid5p, ask5q, bid5q, ask6p, bid6p, ask6q, bid6q, ask7p, bid7p, ask7q, bid7q, ask8p, bid8p, ask8q, bid8q, ask9p, bid9p, ask9q, bid9q, ask10p, bid10p, ask10q, bid10q, NUMORDERS_B1, NOORDERS_B1, ORDERQTY_B1, NUMORDERS_S1, NOORDERS_S1, ORDERQTY_S1, cum_max, group, time_diff, volume_update, datetime, time_interval, time1, time2, time3, time4, time5]
Index: []
             Date           OrigTime         SendTime_x         ercvtime_x  \
3399807  20161226  20161226111648000  20161228094448776  20161228094449171

                  dbtime_x  ChannelNo  StockID  SecurityIDsource  MDStreamID  \
3399807  20161228094450858       1011   300581               102          10

         PreClosePx  PxChnage1  PXChange2  openPrice  HighPx  LowPx  close  \
3399807       46.44       4.64        0.0      51.08   51.08  51.08  51.08

         NumTrades  cum_volume  cum_amount    PE1  PE2 TradingPhase  \
3399807          6        1800     91944.0  45.85  0.0           T0

         totalofferqty  wa_offerPrice  totalbidqty  wa_bidPrice  PreNAV  \
3399807            0.0            0.0    1497700.0        51.05     0.0

         RealTimeNAV  WarrantPremiumRate  UpLimitPx  DownLimitPx  \
3399807          0.0                 0.0      51.08         41.8

         TotalLongPosition       time         SendTime_y         ercvtime_y  \
3399807                0.0  111648000  20161228094448776  20161228094449171

                  dbtime_y  ask1p  bid1p  ask1q    bid1q  ask2p  bid2p  ask2q  \
3399807  20161228094450858    0.0  51.08      0  1481600    0.0  51.07      0

         bid2q  ask3p  bid3p  ask3q  bid3q  ask4p  bid4p  ask4q  bid4q  ask5p  \
3399807   1000    0.0  51.06      0    900    0.0  51.05      0    900    0.0

         bid5p  ask5q  bid5q  ask6p  bid6p  ask6q  bid6q  ask7p  bid7p  ask7q  \
3399807  51.04      0    300    0.0  50.84      0    100    0.0  50.67      0

         bid7q  ask8p  bid8p  ask8q  bid8q  ask9p  bid9p  ask9q  bid9q  \
3399807    500    0.0   50.1      0    200    0.0  50.08      0    800

         ask10p  bid10p  ask10q  bid10q  NUMORDERS_B1  NOORDERS_B1  \
3399807     0.0   49.88       0    1100           693           50

                                               ORDERQTY_B1  NUMORDERS_S1  \
3399807  7800|20500|17500|32600|31600|8100|122600|20100...             0

         NOORDERS_S1 ORDERQTY_S1  cum_max  group   time_diff  volume_update  \
3399807            0         NaN     2200   3721  10391000.0          600.0

                   datetime  time_interval       time1        time2  time3  \
3399807 2016-12-26 11:16:48         3831.0  95045000.0  132003000.0    NaN

               time4        time5
3399807  111648000.0  145030000.0

      StockID  count  cum_volume        time1        time2
0           1      2        1830    111609000  143524000.0
1           2      2        2402    111600000  143524000.0
2           4      2         468    111609000  143524000.0
3           5      2         848    111600000  143527000.0
4           6      2        1608    111609000  143524000.0
...       ...    ...         ...          ...          ...
1845   300575      1          16  [111606000]          NaN
1846   300576      0           9           []          NaN
1847   300577      0           5           []          NaN
1848   300579      0           6           []          NaN
1849   300581      1           7  [111648000]          NaN

[1850 rows x 5 columns]

In [206]:
kk = pd.merge(mr1[mr1["count"] == 2], tr, on="StockID", how="left")
display(kk[kk["time1"] != kk["time4"]])
kk[kk["time2"] != kk["time5"]]

Empty DataFrame
Columns: [StockID, count, cum_volume, time1, time2, time4, time5]
Index: []

Empty DataFrame
Columns: [StockID, count, cum_volume, time1, time2, time4, time5]
Index: []

In [202]:
mr1.shape[0]

1850

In [197]:
snapshot[snapshot["StockID"] == 29]["cum_volume"].unique()

array([0], dtype=int64)

In [142]:
secid = 2459
snapshot[(snapshot["StockID"] == secid) & (snapshot["time_interval"] > 80) & (snapshot["volume_update"] > snapshot[(snapshot["StockID"] == secid) & (snapshot["time"] > 93000000) & (snapshot["time"] < 145700000) & (snapshot["time"] != snapshot["time2"])]["volume_update"].describe([0.95])["95%"]) \
        & (snapshot["time"] > snapshot["time1"]) & (snapshot["time"] != snapshot["time2"]) & (snapshot["time"] != snapshot["time3"])]

,Date,SENDTIME,StockID,DATATIMESTAMP,PreClosePx,openPrice,HighPx,LowPx,close,NUMTRADES,cum_volume,cum_amount,TOTALLONGPOSITION,PERATIO1,PERATIO2,ENDOFDAYMAKER,TOTALOFFERQTY,WEIGHTEDAVGOFFERPX,TOTALBIDQTY,WEIGHTEDAVGBIDPX,ask10p,ask9p,ask8p,ask7p,ask6p,ask5p,ask4p,ask3p,ask2p,ask1p,bid1p,bid2p,bid3p,bid4p,bid5p,bid6p,bid7p,bid8p,bid9p,bid10p,ask10q,ask9q,ask8q,ask7q,ask6q,ask5q,ask4q,ask3q,ask2q,ask1q,bid1q,bid2q,bid3q,bid4q,bid5q,bid6q,bid7q,bid8q,bid9q,bid10q,NUMORDERS_B1,NOORDERS _B1,ORDERQTY_B1,NUMORDERS_S1,NOORDERS _S1,ORDERQTY_S1,time,OrigTime,cum_max,group,trade_diff,time_diff,volume_update,datetime,time_interval,time1,time2,time3,time4,time5
3630439,20160127,101755,2459,101749420,14.72,15.46,15.46,13.8,14.29,468,915568,13349436.20,0,122.67,0.0,N,546333,15.14,271900,13.60,14.68,14.66,14.60,14.59,14.58,14.56,14.55,14.53,14.42,14.40,14.29,14.28,14.09,14.00,13.97,13.88,13.83,13.82,13.81,13.8,600,4700,1500,16000,1000,1000,5000,30000,900,1500,18700,500,2400,700,1000,10000,3000,6600,8000,20100,1,1,18700,2,2,100|500,101749420,20160127101749420,2231518,3391,122.0,1133730.0,215308.0,2016-01-27 10:17:49,694.0,93000480.0,130001830.0,150018570.0,112945600.0,101749420.0
3631438,20160127,110758,2459,110750470,14.72,15.46,15.46,13.8,14.23,582,1155668,16779882.20,0,122.67,0.0,N,519533,15.12,280600,13.75,14.53,14.46,14.42,14.40,14.38,14.35,14.34,14.26,14.25,14.24,14.23,14.22,14.21,14.20,14.19,14.18,14.16,14.15,14.11,14.1,500,100,2000,300,1000,19400,100,4700,500,1500,6000,1300,7200,100,15300,30900,1000,1000,3200,3000,2,2,5000|1000,1,1,500,110750470,20160127110750470,2231518,3691,1.0,202730.0,3200.0,2016-01-27 11:07:50,123.0,93000480.0,130001830.0,150018570.0,112945600.0,101749420.0
3631486,20160127,125901,2459,112945600,14.72,15.46,15.46,13.8,13.90,679,1410868,20361264.08,0,122.67,0.0,N,459736,15.13,205900,13.50,14.38,14.35,14.26,14.24,14.20,14.19,14.18,14.10,14.07,14.06,13.88,13.85,13.84,13.83,13.82,13.81,13.80,13.78,13.75,13.7,200,7100,100,500,1000,10100,1714,1000,1000,19400,900,1000,1000,300,1000,24100,23600,1500,500,300,1,1,900,1,1,200,112945600,20160127112945600,2231518,3764,87.0,1930830.0,247900.0,2016-01-27 11:29:45,1171.0,93000480.0,130001830.0,150018570.0,112945600.0,101749420.0

In [203]:
snapshot[(snapshot["StockID"] == 300575) & (snapshot["time"] > 134900000)].head(50)

,Date,OrigTime,SendTime_x,ercvtime_x,dbtime_x,ChannelNo,StockID,SecurityIDsource,MDStreamID,PreClosePx,PxChnage1,PXChange2,openPrice,HighPx,LowPx,close,NumTrades,cum_volume,cum_amount,PE1,PE2,TradingPhase,totalofferqty,wa_offerPrice,totalbidqty,wa_bidPrice,PreNAV,RealTimeNAV,WarrantPremiumRate,UpLimitPx,DownLimitPx,TotalLongPosition,time,SendTime_y,ercvtime_y,dbtime_y,ask1p,bid1p,ask1q,bid1q,ask2p,bid2p,ask2q,bid2q,ask3p,bid3p,ask3q,bid3q,ask4p,bid4p,ask4q,bid4q,ask5p,bid5p,ask5q,bid5q,ask6p,bid6p,ask6q,bid6q,ask7p,bid7p,ask7q,bid7q,ask8p,bid8p,ask8q,bid8q,ask9p,bid9p,ask9q,bid9q,ask10p,bid10p,ask10q,bid10q,NUMORDERS_B1,NOORDERS_B1,ORDERQTY_B1,NUMORDERS_S1,NOORDERS_S1,ORDERQTY_S1,cum_max,group,time_diff,volume_update,datetime,time_interval,time1,time2,time3,time4,time5
3396229,20161226,20161226134903000,20161228095512732,20161228095513054,20161228095513762,1013,300575,102,10,42.72,4.27,0.0,46.99,46.99,46.99,46.99,19,6600,310134.0,36.34,0.0,T0,0.0,0.0,1233400.0,46.81,0.0,0.0,0.0,46.99,38.45,0.0,134903000,20161228095512732,20161228095513054,20161228095513762,0.0,46.99,0,1170100,0.0,46.98,0,1100,0.0,46.97,0,400,0.0,46.9,0,400,0.0,46.69,0,4300,0.0,46.01,0,5000,0.0,46.00,0,300,0.0,45.6,0,1000,0.0,44.82,0,100,0.0,42.72,0,50500,715,50,1800|21500|20100|25100|30100|19600|500|16900|1...,0,0,NaN,6900,4496,46000.0,0.0,2016-12-26 13:49:03,6.0,93006000.0,131730000.0,150003000.0,111606000.0,143727000.0
3396230,20161226,20161226134924000,20161228095512927,20161228095513436,20161228095514580,1013,300575,102,10,42.72,4.27,0.0,46.99,46.99,46.99,46.99,19,6600,310134.0,36.34,0.0,T0,0.0,0.0,1232900.0,46.81,0.0,0.0,0.0,46.99,38.45,0.0,134924000,20161228095512927,20161228095513436,20161228095514580,0.0,46.99,0,1169600,0.0,46.98,0,1100,0.0,46.97,0,400,0.0,46.9,0,400,0.0,46.69,0,4300,0.0,46.01,0,5000,0.0,46.00,0,300,0.0,45.6,0,1000,0.0,44.82,0,100,0.0,42.72,0,50500,714,50,1800|21500|20100|25100|30100|19600|500|16900|1...,0,0,NaN,6900,4497,21000.0,0.0,2016-12-26 13:49:24,21.0,93006000.0,131730000.0,150003000.0,111606000.0,143727000.0
3396231,20161226,20161226134927000,20161228095512949,20161228095513479,20161228095514693,1013,300575,102,10,42.72,4.27,0.0,46.99,46.99,46.99,46.99,19,6600,310134.0,36.34,0.0,T0,0.0,0.0,1233100.0,46.81,0.0,0.0,0.0,46.99,38.45,0.0,134927000,20161228095512949,20161228095513479,20161228095514693,0.0,46.99,0,1169800,0.0,46.98,0,1100,0.0,46.97,0,400,0.0,46.9,0,400,0.0,46.69,0,4300,0.0,46.01,0,5000,0.0,46.00,0,300,0.0,45.6,0,1000,0.0,44.82,0,100,0.0,42.72,0,50500,715,50,1800|21500|20100|25100|30100|19600|500|16900|1...,0,0,NaN,6900,4497,3000.0,0.0,2016-12-26 13:49:27,3.0,93006000.0,131730000.0,150003000.0,111606000.0,143727000.0
3396232,20161226,20161226134945000,20161228095513103,20161228095513794,20161228095515372,1013,300575,102,10,42.72,4.27,0.0,46.99,46.99,46.99,46.99,19,6600,310134.0,36.34,0.0,T0,0.0,0.0,1224600.0,46.81,0.0,0.0,0.0,46.99,38.45,0.0,134945000,20161228095513103,20161228095513794,20161228095515372,0.0,46.99,0,1161300,0.0,46.98,0,1100,0.0,46.97,0,400,0.0,46.9,0,400,0.0,46.69,0,4300,0.0,46.01,0,5000,0.0,46.00,0,300,0.0,45.6,0,1000,0.0,44.82,0,100,0.0,42.72,0,50500,714,50,1800|21500|20100|25100|30100|19600|500|16900|1...,0,0,NaN,6900,4498,18000.0,0.0,2016-12-26 13:49:45,18.0,93006000.0,131730000.0,150003000.0,111606000.0,143727000.0
3396233,20161226,20161226134948000,20161228095513134,20161228095513840,20161228095515496,1013,300575,102,10,42.72,4.27,0.0,46.99,46.99,46.99,46.99,19,6600,310134.0,36.34,0.0,T0,0.0,0.0,1224900.0,46.81,0.0,0.0,0.0,46.99,38.45,0.0,134948000,20161228095513134,20161228095513840,20161228095515496,0.0,46.99,0,1161600,0.0,46.98,0,1100,0.0,46.97,0,400,0.0,46.9,0,400,0.0,46.69,0,4300,0.0,46.01,0,5000,0.0,46.00,0,300,0.0,45.6,0,1000,0.0,44.82,0,100,0.0,42.72,0,50500,715,50,1800|21500|20100|25100|30100|19600|500|16900|1...,0,0,NaN,6900,4498,3000.0,0.0,2016-12-26 13:49:48,3.0,93006000.0,131730000.0,150003000.0,111606000.0,143727000.0
3396234,20161226,20161226135006000,20161228095513321,20161228095514279,20161228095516406,1013,300575,102,10,42.72,4.27,0.0,46.99,46.99,46.99,46.99,19,6600,310134.0,36.34,0.0,T0,0.0,0.0,1224700.0,46.81,0.0,0.0,0.0,46.99,38.45,0.0,135006000,20161228095513321,20161228095514279,20161228095516406,0.0,46.99,0,1161400,0.0,46.98,0,1100,0.0,46.97,0,400,0.0,46.9,0,400,0.0,46.69,0,4300,0.0,46.01,0,5000,0.0,46.00,0,300,0.0,45.6,0,1000,0.0,44.82,0,100,0.0,42.72,0,50500,714,50,1800|21500|20100|25100|30100|19600|500|16900|1...,0,0,NaN,6900,4500,58000.0,0.0,2016-12-26 13:50:06,18.0,93006000.0,131730000.0,150003000.0,111606000.0,143727000.0
3396235,20161226,20161226143527000,20161228095513441,20161228095514514,20161228095516862,1013,300575,102,10,42.72,4.27,0.0,46.99,46.99,46.99,46.99,19,6600,310134.0,36.34,0.0,T0,0.0,0.0,981900.0,46.85,0.0,0.0,0.0,46.99,38.45,0.0,143527000,20161228095513441,20161228095514514,20161228095516862,0.0,46.99,0,941600,0.0,46.98,0,1100,0.0,46.97,0,400,0.0,46.9,0,400,0.0,46.39,0,4000,0.0,46.01,0,5000,0.0,42.72,0,29200,0.0,40.0,0,200,0.0,0.00,0,0,0.0,0.00,0,0,676,50,1800|21500|20100|25100|30100|19600|500|16900|1...,0,0,NaN,6900,4784,8521000.0,0.0,2016-12-26 14:35:27,2721.0,93006000.0,131730000.0,150003000.0,111606000.0,143727000.0
3396236,20161226,20161226143536000,20161228095514560,20161228095514735,20161228095517202,1013,300575,102,10,42.72,4.27,0.0,46.99,46.99,46.99,46.99,19,6600,310134.0,36.34,0.0,T0,0.0,0.0,948400.0,46.85,0.0,0.0,0.0,46.99,38.45,0.0,143536000,20161228095514560,20161228095514735,20161228095517202,0.0,46.99,0,908100,0.0,46.98,0,1100,0.0,46.97,0,400,0.0,46.9,0,400,0.0,46.39,0,4000,0.0,46.01,0,5000,0.0,42.72,0,29200,0.0,40.0,0,200,0.0,0.00,0,0,0.0,0.00,0,0,674,50,1800|21500|20100|25100|30100|19600|500|300|100...,0,0,NaN,6900,4784,9000.0,0.0,2016-12-26 14:35:36,9.0,93006000.0,131730000.0,150003000.0,111606000.0,143727000.0
3396237,20161226,20161226143542000,20161228095514640,20161228095514904,20161228095517424,1013,300575,102,10,42.72,4.27,0.0,46.99,46.99,46.99,46.99,19,6600,310134.0,36.34,0.0,T0,0.0,0.0,946600.0,46.85,0.0,0.0,0.0,46.99,38.45,0.0,143542000,20161228095514640,20161228095514904,20161228095517424,0.0,46.99,0,906300,0.0,46.98,0,1100,0.0,46.97,0,400,0.0,46.9,0,400,0.0,46.39,0,4000,0.0,46.01,0,5000,0.0,42.72,0,29200,0.0,40.0,0,200,0.0,0.00,0,0,0.0,0.00,0,0,673,50,1800|21500|20100|25100|30100|19600|500|300|100...,0,0,NaN,6900,4784,6000.0,0.0,2016-12-26 14:35:42,6.0,93006000.0,131730000.0,150003000.0,111606000.0,143727000.0
3396238,20161226,20161226143603000,20161228095514936,20161228095515552,20161228095518190,1013,300575,102,10,42.72,4.27,0.0,46.99,46.99,46.99,46.99,19,6600,310134.0,36.34,0.0,T0,0.0,0.0,945600.0,46.85,0.0,0.0,0.0,46.99,38.45,0.0,143603000,20161228095514936,20161228095515552,20161228095518190,0.0,46.99,0,905300,0.0,46.98,0,1100,0.0,46.97,0,400,0.0,46.9,0,400,0.0,46.39,0,4000,0.0,46.01,0,5000,0.0,42.72,0,29200,0.0,40.0,0,200,0.0,0.00,0,0,0.0,0.00,0,0,672,50,1800|21500|20100|25100|30100|19600|500|300|100...,0,0,NaN,6900,4786,61000.0,0.0,2016-12-26 14:36:03,21.0,93006000.0,131730000.0,150003000.0,111606000.0,143727000.0
3396239,20161226,20161226143606000,20161228095514973,20161228095515629,20161228095518259,1013,300575,102,10,42.72,4.27,0.0,46.99,46.99,46.99,46.99,19,6600,310134.0,36.34,0.0,T0,0.0,0.0,945700.0,46.85,0.0,0.0,0.0,46.99,38.45,0.0,143606000,20161228095514973,20161228095515629,20161228095518259,0.0,46.99,0,905400,0.0,46.98,0,1100,0.0,46.97,0,400,0.0,46.9,0,400,0.0,46.39,0,4000,0.0,46.01,0,5000,0.0,42.72,0,29200,0.0,40.0,0,200,0.0,0.00,0,0,0.0,0.00,0,0,673,50,1800|21500|20100|25100|30100|19600|500|300|100...,0,0,NaN,6900,4786,3000.0,0.0,2016-12-26 14:36:06,3.0,93006000.0,131730000.0,150003000.0,111606000.0,143727000.0
3396240,20161226,20161226143609000,20161228095515018,20161228095515697,20161228095518327,1013,300575,102,10,42.72,4.27,0.0,46.99,46.99,46.99,46.99,19,6600,310134.0,36.34,0.0,T0,0.0,0.0,944700.0,46.85,0.0,0.0,0.0,46.99,38.45,0.0,143609000,20161228095515018,20161228095515697,20161228095518327,0.0,46.99,0,904400,0.0,46.98,0,1100,0.0,46.97,0,400,0.0,46.9,0,400,0.0,46.39,0,4000,0.0,46.01,0,5000,0.0,42.72,0,29200,0.0,40.0,0,200,0.0,0.00,0,0,0.0,0.00,0,0,672,50,1800|21500|20100|25100|30100|19600|500|300|100...,0,0,NaN,6900,4786,3000.0,0.0,2016-12-26 14:36:09,3.0,93006000.0,131730000.0,150003000.0,111606000.0,143727000.0
3396241,20161226,20161226143618000,20161228095515129,20161228095515899,20161228095518528,1013,300575,102,10,42.72,4.27,0.0,46.99,46.99,46.99,46.99,19,6600,310134.0,36.34,0.0,T0,0.0,0.0,944300.0,46.85,0.0,0.0,0.0,46.99,38.45,0.0,143618000,20161228095515129,20161228095515899,20161228095518528,0.0,46.99,0,904000,0.0,46.98,0,1100,0.0,46.97,0,400,0.0,46.9,0,400,0.0,46.39,0,4000,0.0,46.01,0,5000,0.0,42.72,0,29200,0.0,40.0,0,200,0.0,0.00,0,0,0.0,0.00,0,0,671,50,1800|21500|20100|25100|30100|19600|500|300|100...,0,0,NaN,6900,4787,9000.0,0.0,2016-12-26 14:36:18,9.0,93006000.0,131730000.0,150003000.0,111606000.0,143727000.0
3396242,20161226,20161226143627000,20161228095515239,20161228095516099,20161228095518713,1013,300575,102,10,42.72,4.27,0.0,46.99,46.99,46.99,46.99,19,6600,310134.0,36.34,0.0,T0,0.0,0.0,944800.0,46.85,0.0,0.0,0.0,46.99,38.45,0.0,143627000,20161228095515239,20161228095516099,20161228095518713,0.0,46.99,0,904500,0.0,46.98,0,1100,0.0,46.97,0,400,0.0,46.9,0,400,0.0,46.39,0,4000,0.0,46.01,0,5000,0.0,42.72,0,29200,0.0,40.0,0,200,0.0,0.00,0,0,0.0,0.00,0,0,672,50,1800|21500|20100|25100|30100|19600|500|300|100...,0,0,NaN,6900,4787,9000.0,0.0,2016-12-26 14:36:27,9.0,93006000.0,131730000.0,150003000.0,111606000.0,143727000.0
3396243,20161226,20161226143639000,20161228095515381,20161228095516338,20161228095518942,1013,300575,102,10,42.72,4.27,0.0,46.99,46.99,46.99,46.99,19,6600,310134.0,36.34,0.0,T0,0.0,0.0,945200.0,46.85,0.0,0.0,0.0,46.99,38.45,0.0,143639000,20161228095515381,20161228095516338,20161228095518942,0.0,46.99,0,904900,0.0,46.98,0,1100,0.0,46.97,0,400,0.0,46.9,0,400,0.0,46.39,0,4000,0.0,46.01,0,5000,0.0,42.72,0,29200,0.0,40.0,0,200,0.0,0.00,0,0,0.0,0.00,0,0,673,50,1800|21500|20100|25100|30100|19600|500|300|100...,0,0,NaN,6900,4787,12000.0,0.0,2016-12-26 14:36:39,12.0,93006000.0,131730000.0,150003000.0,111606000.0,143727000.0
3396244,20161226,20161226143648000,20161228095515501,20161228095516539,20161228095519123,1013,300575,102,10,42.72,4.27,0.0,46.99,46.99,46.99,46.99,19,6600,310134.0,36.34,0.0,T0,0.0,0.0,925900.0,46.85,0.0,0.0,0.0,46.99,38.45,0.0,143648000,20161228095515501,20161228095516539,20161228095519123,0.0,46.99,0,885600,0.0,46.98,0,1100,0.0,46.97,0,400,0.0,46.9,0,400,0.0,46.39,0,4000,0.0,46.01,0,5000,0.0,42.72,0,29200,0.0,40.0,0,200,0.0,0.00,0,0,0.0,0.00,0,0,673,50,1800|21500|20100|25100|30100|500|300|10000|100...,0,0,NaN,6900,4788,9000.0,0.0,2016-12-26 14:36:48,9.0,93006000.0,131730000.0,150003000.0,111606000.0,143727000.0
3396245,20161226,20161226143706000,20161228095547468,20161228095547708,20161228095548193,1013,300575,102,10,42.72,4.27,0.0,46.99,46.99,46.99,46.99,19,6600,310134.0,36.34,0.0,T0,0.0,0.0,905700.0,46.84,0.0,0.0,0.0,46.99,38.45,0.0,143706000,20161228095547468,20161228095547708,20161228095548193,0.0,46.99,0,865400,0.0,46.98,0,1100,0.0,46.97,0,400,0.0,46.9,0,400,0.0,46.39,0,4000,0.0,46.01,0,5000,0.0,42.72,0,29200,0.0,40.0,0,200,0.0,0.00,0,0,0.0,0.00,0,0,671,50,1800|21500|25100|30100|500|300|10000|100|300|4...,0,0,NaN,6900,4790,58000.0,0.0,2016-12-26 14:37:06,18.0,93006000.0,131730000.0,150003000.0,111606000.0,143727000.0
3396246,20161226,20161226143709000,20161228095547505,20161228095547771,20161228095548323,1013,300575,102,10,42.72,4.27,0.0,46.99,46.99,46.99,46.99,19,6600,310134.0,36.34,0.0,T0,0.0,0.0,905400.0,46.84,0.0,0.0,0.0,46.99,38.45,0.0,143709000,20161228095547505,20161228095547771,20161228095548323,0.0,46.99,0,865100,0.0,46.98,0,1100,0.0,46.97,0,400,0.0,46.9,0,400,0.0,46.39,0,4000,0.0,46.01,0,5000,0.0,42.72,0,29200,0.0,40.0,0,200,0.0,0.00,0,0,0.0,0.00,0,0,669,50,1800|21500|25100|30100|500|300|10000|100|300|4...,0,0,NaN,6900,4790,3000.0,0.0,2016-12-26 14:37:09,3.0,93006000.0,131730000.0,150003000.0,111606000.0,143727000.0
3396247,20161226,20161226143712000,20161228095547543,20161228095547847,20161228095548467,1013,300575,102,10,42.72,4.27,0.0,46.99,46.99,46.99,46.99,19,6600,310134.0,36.34,0.0,T0,0.0,0.0,905900.0,46.84,0.0,0.0,0.0,46.99,38.45,0.0,143712000,20161228095547543,20161228095547847,20161228095548467,0.0,46.99,0,865600,0.0,46.98,0,1100,0.0,46.97,0,400,0.0,46.9,0,400,0.0,46.39,0,4000,0.0,46.01,0,5000,0.0,42.72,0,29200,0.0,40.0,0,200,0.0,0.00,0,0,0.0,0.00,0,0,670,50,1800|21500|25100|30100|500|300|10000|100|300|4...,0,0,NaN,6900,4790,3000.0,0.0,2016-12-26 14:37:12,3.0,93006000.0,131730000.0,150003000.0,111606000.0,143727000.0
3396248,20161226,20161226143727000,20161228095547730,20161228095548186,20161228095549145,1013,300575,102,10,42.72,4.27,0.0,46.99,46.99,46.99,46.99,20,6700,314833.0,36.34,0.0,T0,0.0,0.0,905800.0,46.84,0.0,0.0,0.0,46.99,38.45,0.0,143727000,20161228095547730,20161228095548186,20161228095549145,0.0,46.99,0,865500,0.0,46.98,0,1100,0.0,46.97,0,400,0.0,46.9,0,400,0.0,46.39,0,4000,0.0,46.01,0,5000,0.0,42.72,0,29200,0.0,40.0,0,200,0.0,0.00,0,0,0.0,0.00,0,0,670,50,1700|21500|25100|30100|500|300|10000|100|300|4...,0,0,NaN,6900,4790,15000.0,100.0,2016-12-26 14:37:27,15.0,93006000.0,131730000.0,150003000.0,111606000.0,143727000.0
3396249,20161226,20161226143803000,20161228095548182,20161228095548990,20161228095550648,1013,300575,102,10,42.72,4.27,0.0,46.99,46.99,46.99,46.99,20,6700,314833.0,36.34,0.0,T0,0.0,0.0,905300.0,46.84,0.0,0.0,0.0,46.99,38.45,0.0,143803000,20161228095548182,20161228095548990,20161228095550648,0.0,46.99,0,865000,0.0,46.98,0,1100,0.0,46.97,0,400,0.0,46.9,0,400,0.0,46.39,0,4000,0.0,46.01,0,5000,0.0,42.72,0,29200,0.0,40.0,0,200,0.0,0.00,0,0,0.0,0.00,0,0,669,50,1700|21500|25100|30100|500|300|10000|100|300|4...,0,0,NaN,6900,4793,76000.0,0.0,2016-12-26 14:38:03,36.0,93006000.0,131730000.0,150003000.0,111606000.0,143727000.0
3396250,20161226,20161226143806000,20161228095548216,20161228095549052,20161228095550772,1013,300575,102,10,42.72,4.27,0.0,46.99,46.99,46.99,46.99,20,6700,314833.0,36.34,0.0,T0,0.0,0.0,905000.0,46.84,0.0,0.0,0.0,46.99,38.45,0.0,143806000,20161228095548216,20161228095549052,20161228095550772,0.0,46.99,0,864700,0.0,46.98,0,1100,0.0,46.97,0,400,0.0,46.9,0,400,0.0,46.39,0,4000,0.0,46.01,0,5000,0.0,42.72,0,29200,0.0,40.0,0,200,0.0,0.00,0,0,0.0,0.00,0,0,668,50,1700|21500|25100|30100|500|300|10000|100|300|4...,0,0,NaN,6900,4793,3000.0,0.0,2016-12-26 14:38:06,3.0,93006000.0,131730000.0,150003000.0,111606000.0,143727000.0
3396251,20161226,20161226143812000,20161228095548292,20161228095549162,20161228095551047,1013,300575,102,10,42.72,4.27,0.0,46.99,46.99,46.99,46.99,20,6700,314833.0,36.34,0.0,T0,0.0,0.0,909900.0,46.84,0.0,0.0,0.0,46.99,38.45,0.0,143812000,20161228095548292,20161228095549162,20161228095551047,0.0,46.99,0,869600,0.0,46.98,0,1100,0.0,46.97,0,400,0.0,46.9,0,400,0.0,46.39,0,4000,0.0,46.01,0,5000,0.0,42.72,0,29200,0.0,40.0,0,200,0.0,0.00,0,0,0.0,0.00,0,0,669,50,1700|21500|25100|30100|500|300|10000|100|300|4...,0,0,NaN,6900,4793,6000.0,0.0,2016-12-26 14:38:12,6.0,93006000.0,131730000.0,150003000.0,111606000.0,143727000.0
3396252,20161226,20161226143815000,20161228095549385,20161228095549388,20161228095551162,1013,300575,102,10,42.72,4.27,0.0,46.99,46.99,46.99,46.99,20,6700,314833.0,36.34,0.0,T0,0.0,0.0,910100.0,46.84,0.0,0.0,0.0,46.99,38.45,0.0,143815000,20161228095549385,20161228095549388,20161228095551162,0.0,46.99,0,869800,0.0,46.98,0,1100,0.0,46.97,0,400,0.0,46.9,0,400,0.0,46.39,0,4000,0.0,46.01,0,5000,0.0,42.72,0,29200,0.0,40.0,0,200,0.0,0.00,0,0,0.0,0.00,0,0,670,50,1700|21500|25100|30100|500|300|10000|100|300|4...,0,0,NaN,6900,4793,3000.0,0.0,2016-12-26 14:38:15,3.0,93006000.0,131730000.0,150003000.0,111606000.0,143727000.0
3396253,20161226,20161226143824000,20161228095549501,20161228095549542,20161228095551466,1013,300575,102,10,42.72,4.27,0.0,46.99,46.99,46.99,46.99,20,6700,314833.0,36.34,0.0,T0,0.0,0.0,910300.0,46.84,0.0,0.0,0.0,46.99,38.45,0.0,143824000,20161228095549501,20161228095549542,20161228095551466,0.0,46.99,0,870000,0.0,46.98,0,1100,0.0,46.97,0,400,0.0,46.9,0,400,0.0,46.39,0,4000,0.0,46.01,0,5000,0.0,42.72,0,29200,0.0,40.0,0,200,0.0,0.00,0,0,0.0,0.00,0,0,671,50,1700|21500|25100|30100|500|300|10000|100|300|4...,0,0,NaN,6900,4794,9000.0,0.0,2016-12-26 14:38:24,9.0,93006000.0,131730000.0,150003000.0,111606000.0,143727000.0
3396254,20161226,20161226143839000,20161228095549669,20161228095549942,20161228095551889,1013,300575,102,10,42.72,4.27,0.0,46.99,46.99,46.99,46.99,20,6700,314833.0,36.34,0.0,T0,0.0,0.0,910500.0,46.84,0.0,0.0,0.0,46.99,38.45,0.0,143839000,20161228095549669,20161228095549942,20161228095551889,0.0,46.99,0,870200,0.0,46.98,0,1100,0.0,46.97,0,400,0.0,46.9,0,400,0.0,46.39,0,4000,0.0,46.01,0,5000,0.0,42.72,0,29200,0.0,40.0,0,200,0.0,0.00,0,0,0.0,0.00,0,0,672,50,1700|21500|25100|30100|500|300|10000|100|300|4...,0,0,NaN,6900,4794,15000.0,0.0,2016-12-26 14:38:39,15.0,93006000.0,131730000.0,150003000.0,111606000.0,143727000.0
3396255,20161226,20161226143848000,20161228095549770,20161228095550195,20161228095552124,1013,300575,102,10,42.72,4.27,0.0,46.99,46.99,46.99,46.99,20,6700,314833.0,36.34,0.0,T0,0.0,0.0,911000.0,46.84,0.0,0.0,0.0,46.99,38.45,0.0,143848000,20161228095549770,20161228095550195,20161228095552124,0.0,46.99,0,870700,0.0,46.98,0,1100,0.0,46.97,0,400,0.0,46.9,0,400,0.0,46.39,0,4000,0.0,46.01,0,5000,0.0,42.72,0,29200,0.0,40.0,0,200,0.0,0.00,0,0,0.0,0.00,0,0,673,50,1700|21500|25100|30100|500|300|10000|100|300|4...,0,0,NaN,6900,4794,9000.0,0.0,2016-12-26 14:38:48,9.0,93006000.0,131730000.0,150003000.0,111606000.0,143727000.0
3396256,20161226,20161226143900000,20161228095549919,20161228095550540,20161228095552445,1013,300575,102,10,42.72,4.27,0.0,46.99,46.99,46.99,46.99,20,6700,314833.0,36.34,0.0,T0,0.0,0.0,880000.0,46.84,0.0,0.0,0.0,46.99,38.45,0.0,143900000,20161228095549919,20161228095550540,20161228095552445,0.0,46.99,0,839700,0.0,46.98,0,1100,0.0,46.97,0,400,0.0,46.9,0,400,0.0,46.39,0,4000,0.0,46.01,0,5000,0.0,42.72,0,29200,0.0,40.0,0,200,0.0,0.00,0,0,0.0,0.00,0,0,671,50,1700|21500|25100|500|300|10000|100|300|40000|3...,0,0,NaN,6900,4796,52000.0,0.0,2016-12-26 14:39:00,12.0,93006000.0,131730000.0,150003000.0,111606000.0,143727000.0
3396257,20161226,20161226143903000,20161228095549977,20161228095550686,20161228095552579,1013,300575,102,10,42.72,4.27,0.0,46.99,46.99,46.99,46.99,20,6700,314833.0,36.34,0.0,T0,0.0,0.0,875000.0,46.84,0.0,0.0,0.0,46.99,38.45,0.0,143903000,20161228095549977,20161228095550686,20161228095552579,0.0,46.99,0,834700,0.0,46.98,0,1100,0.0,46.97,0,400,0.0,46.9,0,400,0.0,46.39,0,4000,0.0,46.01,0,5000,0.0,42.72,0,29200,0.0,40.0,0,200,0.0,0.00,0,0,0.0,0.00,0,0,670,50,1700|21500|25100|500|300|10000|100|300|40000|3...,0,0,NaN,6900,4796,3000.0,0.0,2016-12-26 14:39:03,3.0,93006000.0,131730000.0,150003000.0,111606000.0,143727000.0
3396258,20161226,20161226143921000,20161228095550185,20161228095551035,20161228095552914,1013,300575,102,10,42.72,4.27,0.0,46.99,46.99,46.99,46.99,20,6700,314833.0,36.34,0.0,T0,0.0,0.0,861300.0,46.84,0.0,0.0,0.0,46.99,38.45,0.0,143921000,20161228095550185,20161228095551035,20161228095552914,0.0,46.99,0,821000,0.0,46.98,0,1100,0.0,46.97,0,400,0.0,46.9,0,400,0.0,46.39,0,4000,0.0,46.01,0,5000,0.0,42.72,0,29200,0.0,40.0,0,200,0.0,0.00,0,0,0.0,0.00,0,0,669,50,1700|21500|25100|500|300|10000|100|300|40000|3...,0,0,NaN,6900,4797,18000.0,0.0,2016-12-26 14:39:21,18.0,93006000.0,131730000.0,150003000.0,111606000.0,143727000.0

In [122]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import pickle
from matplotlib import pyplot as plt
import statsmodels.api as sm
from matplotlib.ticker import Formatter
import collections
import glob
import os
import datetime
pd.set_option("max_columns", 200)

df = pd.read_table(r"J:\LEVEL2_shenzhen\2016\01\27\SZL2_TRADE_20160127\SZL2_TRADE_20160127_PM.txt", header=None)
df.columns=["TRADEDATE", "SENDTIME", "SETNO", "RECNO", "BUYORDERRECNO", "SELLORDERRECNO", "SECURITYID", "PRICE",
           "TRADEQTY", "ORDERKIND", "FUNCTIONCODE", "TRADETIME"]

In [125]:
df[(df["SECURITYID"] == 300242) & (df["TRADETIME"] > 141000000)].head(50)

,TRADEDATE,SENDTIME,SETNO,RECNO,BUYORDERRECNO,SELLORDERRECNO,SECURITYID,PRICE,TRADEQTY,ORDERKIND,FUNCTIONCODE,TRADETIME
4246029,20160127,141141,4,1753421,0,984269,300242,0.00,100,0,C,141139100
4247341,20160127,141153,4,1754733,2470273,6631,300242,32.77,300,0,0,141152580
4248441,20160127,141205,4,1755833,0,492269,300242,0.00,500,0,C,141203730
4289355,20160127,141820,4,1796747,2527162,6631,300242,32.77,5000,0,0,141819640
4301052,20160127,141914,4,1808444,2541136,6631,300242,32.77,300,0,0,141912720
4337138,20160127,142220,4,1844530,2586757,6631,300242,32.77,100,0,0,142218360
4359496,20160127,142450,4,1866888,0,175170,300242,0.00,2000,0,C,142448650
4373020,20160127,142544,4,1880412,0,2268915,300242,0.00,2100,0,C,142541990
4375524,20160127,142553,4,1882916,0,114217,300242,0.00,200,0,C,142551060
4382617,20160127,142612,4,1890009,0,275663,300242,0.00,100,0,C,142611270
4390110,20160127,142633,4,1897502,0,306632,300242,0.00,1500,0,C,142631920
4393615,20160127,142644,4,1901007,0,2641138,300242,0.00,6700,0,C,142643290
4408427,20160127,142727,4,1915819,2675553,6631,300242,32.77,100,0,0,142726690
4411306,20160127,142736,4,1918698,0,1103759,300242,0.00,3000,0,C,142734820
4417240,20160127,142753,4,1924632,2686286,6631,300242,32.77,300,0,0,142752450
4421529,20160127,142808,4,1928921,0,2674416,300242,0.00,6000,0,C,142806140
4421643,20160127,142808,4,1929035,0,441653,300242,0.00,4000,0,C,142806530
4429200,20160127,142830,4,1936592,0,1236497,300242,0.00,100,0,C,142829610
4431683,20160127,142838,4,1939075,0,520554,300242,0.00,1500,0,C,142837400
4432687,20160127,142841,4,1940079,0,7057,300242,0.00,1600,0,C,142840650
4437339,20160127,142856,4,1944731,0,832990,300242,0.00,500,0,C,142855730
4441044,20160127,142911,4,1948436,2716072,6631,300242,32.77,300,0,0,142910010
4444826,20160127,142923,4,1952218,0,103104,300242,0.00,1100,0,C,142922340
4445652,20160127,142927,4,1953044,2721776,6631,300242,32.77,1000,0,0,142925290
4450831,20160127,142947,4,1958223,2728578,6631,300242,32.77,2400,0,0,142945880
4451075,20160127,142948,4,1958467,2728929,6631,300242,32.77,200,0,0,142946980
4453969,20160127,143000,4,1961361,2732928,6631,300242,32.77,100,0,0,142959210
4456955,20160127,143014,4,1964347,2737161,6631,300242,32.77,900,0,0,143011840
4461073,20160127,143030,4,1968465,0,1235298,300242,0.00,200,0,C,143029400
4472539,20160127,143118,4,1979931,0,188721,300242,0.00,4000,0,C,143116930
4475931,20160127,143133,4,1983323,0,746343,300242,0.00,200,0,C,143132390
4478094,20160127,143144,4,1985486,0,146454,300242,0.00,16900,0,C,143141800
4479593,20160127,143150,4,1986985,0,1169079,300242,0.00,5000,0,C,143149040
4482147,20160127,143200,4,1989539,2774684,6631,300242,32.77,600,0,0,143158900
4487551,20160127,143223,4,1994943,2782735,6631,300242,32.77,1000,0,0,143222500
4487948,20160127,143226,4,1995340,0,1607888,300242,0.00,200,0,C,143224290
4488757,20160127,143229,4,1996149,0,920249,300242,0.00,750,0,C,143228020
4492722,20160127,143248,4,2000114,0,2769438,300242,0.00,1000,0,C,143246060
4494546,20160127,143256,4,2001938,0,2300796,300242,0.00,2000,0,C,143254880
4504635,20160127,143347,4,2012027,2806285,6631,300242,32.77,100,0,0,143346400
4508250,20160127,143408,4,2015642,0,2063848,300242,0.00,500,0,C,143407380
4519270,20160127,143511,4,2026662,2826779,6631,300242,32.77,400,0,0,143510390
4529793,20160127,143615,4,2037185,2841198,6631,300242,32.77,200,0,0,143614350
4533892,20160127,143641,4,2041284,2846802,6631,300242,32.77,500,0,0,143639690
4539979,20160127,143718,4,2047371,2854828,6631,300242,32.77,500,0,0,143717430
4546574,20160127,143805,4,2053966,2864206,6631,300242,32.77,300,0,0,143803960
4546847,20160127,143808,4,2054239,0,1014667,300242,0.00,500,0,C,143805900
4548047,20160127,143815,4,2055439,0,6687,300242,0.00,1900,0,C,143813660
4548062,20160127,143815,4,2055454,2866213,6631,300242,32.77,200,0,0,143813760
4548567,20160127,143818,4,2055959,2866883,6631,300242,32.77,100,0,0,143817110